Repository gradle/gradle, pull requests merged in 2018-07, with the labels that each got.

#5813 Stop using atomic types in non-thread-safe contexts
  subprojects/antlr/src/main/java/org/gradle/api/plugins/antlr/AntlrTask.java
  subprojects/base-services/src/main/java/org/gradle/internal/MutableBoolean.java
  subprojects/base-services/src/main/java/org/gradle/internal/MutableReference.java
  subprojects/base-services/src/main/java/org/gradle/internal/package-info.java
  subprojects/base-services/src/main/java/org/gradle/internal/work/DefaultConditionalExecutionQueue.java
  subprojects/base-services/src/main/java/org/gradle/internal/work/DefaultWorkerLeaseService.java
  subprojects/base-services/src/test/groovy/org/gradle/internal/MutableBooleanTest.groovy
  subprojects/base-services/src/test/groovy/org/gradle/internal/MutableReferenceTest.groovy
  subprojects/base-services/src/test/groovy/org/gradle/internal/work/DefaultWorkerLeaseServiceProjectLockTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/file/AbstractFileTree.java
  subprojects/core/src/main/java/org/gradle/execution/taskgraph/DefaultTaskPlanExecutor.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/collections/MapFileTreeTest.java
  subprojects/core/src/testFixtures/groovy/org/gradle/api/tasks/AbstractSpockTaskTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/api/tasks/AbstractTaskTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/rules/RuleSourceBackedRuleActionTest.groovy
  subprojects/model-core/src/main/java/org/gradle/model/internal/typeregistration/BaseInstanceFactory.java
  subprojects/model-groovy/src/main/java/org/gradle/model/dsl/internal/NonTransformedModelDslBacking.java
  subprojects/persistent-cache/src/test/groovy/org/gradle/cache/internal/locklistener/DefaultFileLockContentionHandlerTest.groovy
Labels: from:member

#5820 Revert to using serializable return value
  subprojects/core/src/main/java/org/gradle/api/internal/file/AbstractFileCollection.java
Labels: from:member

#5826 Draft release notes and features for Gradle 4.9
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/release/release-features.txt
Labels: from:member, in:docs

#5842 Remove `ModuleVersionSelector.versionConstraint`
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/DependencyConstraint.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/ExternalDependency.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/ModuleVersionSelector.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultModuleVersionSelector.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultDependencyConstraint.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/ModuleVersionSelectorParsers.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/DefaultModuleVersionSelectorTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/dsl/ModuleVersionSelectorParsersTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/DefaultUnresolvedDependencySpec.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/dependencysubstitution/DefaultDependencyResolveDetailsSpec.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/dependencysubstitution/DefaultDependencySubstitutionsSpec.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolutionstrategy/DefaultResolutionStrategySpec.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolutionstrategy/ModuleForcingResolveRuleSpec.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/CachingDependencyResultFactoryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/DefaultResolutionResultBuilderSpec.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/DependencyResultSerializerTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/resolve/ModuleVersionResolveExceptionTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/resolve/result/DefaultBuildableComponentResolveResultTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/resolve/result/DefaultBuildableModuleComponentMetaDataResolveResultTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/resolve/result/DefaultBuildableModuleVersionListingResolveResultTest.groovy
  subprojects/dependency-management/src/testFixtures/groovy/org/gradle/api/internal/artifacts/result/ResolutionResultDataBuilder.groovy
  subprojects/distributions/src/changes/accepted-public-api-changes.json
Labels: from:member, in:dependency-management

#5847 Add GNU Trove license information
  LICENSE
Labels: a:feature, from:member, in:core

#5854 Update TeamCity Kotlin DSL to 2018.1 for Gradle_check
  .teamcity/Gradle_AgentTest/settings.kts
  .teamcity/Gradle_Check/configurations/BaseGradleBuildType.kt
  .teamcity/Gradle_Check/configurations/BuildDistributions.kt
  .teamcity/Gradle_Check/configurations/DependenciesCheck.kt
  .teamcity/Gradle_Check/configurations/FunctionalTest.kt
  .teamcity/Gradle_Check/configurations/GradleBuildConfigurationDefaults.kt
  .teamcity/Gradle_Check/configurations/Gradleception.kt
  .teamcity/Gradle_Check/configurations/IndividualPerformanceScenarioWorkers.kt
  .teamcity/Gradle_Check/configurations/PerformanceTest.kt
  .teamcity/Gradle_Check/configurations/SanityCheck.kt
  .teamcity/Gradle_Check/configurations/SmokeTests.kt
  .teamcity/Gradle_Check/configurations/StagePasses.kt
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/Gradle_Check/projects/FunctionalTestProject.kt
  .teamcity/Gradle_Check/projects/RootProject.kt
  .teamcity/Gradle_Check/projects/StageProject.kt
  .teamcity/Gradle_Check/projects/WorkersProject.kt
  .teamcity/Gradle_Check/settings.kts
  .teamcity/Gradle_Check_dsl.iml
  .teamcity/pom.xml
  .teamcityTest/Gradle_Check_Tests/CIConfigIntegrationTests.kt
Labels: a:chore

#5853 Allow ProjectBuilder tests when classpath contains relative paths
  subprojects/core/src/main/java/org/gradle/api/internal/classpath/EffectiveClassPath.java
Labels: a:bug, from:member, in:core

#5855 Parallelize incremental compile jar analysis
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/IncrementalCompilerFactory.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/jar/JarClasspathSnapshotFactory.java
  subprojects/language-java/src/main/java/org/gradle/language/java/internal/JavaLanguagePluginServiceRegistry.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/incremental/jar/JarClasspathSnapshotFactoryTest.groovy
Labels: a:feature, from:member, in:jvm-platform

#5858 Polish `BuildScanPlugin`
  buildSrc/subprojects/profiling/src/main/kotlin/org/gradle/gradlebuild/profiling/buildscan/BuildScanPlugin.kt
Labels: a:feature, from:member, in:gradle-build

#5843 Delete unused shared caches
  subprojects/core/src/integTest/groovy/org/gradle/initialization/buildsrc/BuildScriptClasspathIntegrationSpec.groovy
  subprojects/core/src/main/java/org/gradle/cache/internal/VersionSpecificCacheAndWrapperDistributionCleanupService.java
  subprojects/core/src/main/java/org/gradle/cache/internal/VersionSpecificCacheDirectory.java
  subprojects/core/src/main/java/org/gradle/cache/internal/VersionSpecificCacheDirectoryService.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/DefaultCachedClasspathTransformer.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GradleUserHomeScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/cache/internal/VersionSpecificCacheAndWrapperDistributionCleanupServiceTest.groovy
  subprojects/core/src/test/groovy/org/gradle/cache/internal/VersionSpecificCacheDirectoryServiceTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/classpath/DefaultCachedClasspathTransformerTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/caching/DefaultArtifactCacheLockingManagerIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/CacheLayout.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/DefaultArtifactCacheLockingManager.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/DefaultArtifactCacheMetadata.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/CacheLayoutTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/DefaultArtifactCacheLockingManagerTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/DefaultGradleDistribution.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/GradleDistribution.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/AbstractCacheCleanup.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/CacheVersion.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/CacheVersionMapping.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/CompositeCleanupAction.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/UnusedVersionsCacheCleanup.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/UsedGradleVersions.java
  subprojects/persistent-cache/src/test/groovy/org/gradle/cache/internal/CacheVersionMappingTest.groovy
  subprojects/persistent-cache/src/test/groovy/org/gradle/cache/internal/CacheVersionTest.groovy
  subprojects/persistent-cache/src/test/groovy/org/gradle/cache/internal/CompositeCleanupActionTest.groovy
  subprojects/persistent-cache/src/test/groovy/org/gradle/cache/internal/UnusedVersionsCacheCleanupTest.groovy
Labels: a:feature, from:member, in:dependency-management

#5874 Update to build scan plugin 1.15.1
  buildSrc/subprojects/profiling/profiling.gradle.kts
  subprojects/core/src/main/java/org/gradle/plugin/management/internal/autoapply/AutoAppliedBuildScanPlugin.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/BuildScanPluginSmokeTest.groovy
Labels: from:member

#5815 Minor doc tweak
  subprojects/core-api/src/main/java/org/gradle/api/tasks/TaskOutputs.java
Labels: a:chore, from:contributor, in:build-cache

#5870 Make tests robust against additional root build operations
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/AbstractCompositeBuildIntegrationTest.groovy
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildBuildSrcBuildOperationsIntegrationTest.groovy
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildOperationsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/buildsrc/BuildSrcBuildOperationsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/internal/operations/logging/LoggingBuildOperationProgressIntegTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/BuildOperationsFixture.groovy
  subprojects/version-control/src/integTest/groovy/org/gradle/vcs/internal/SourceDependencyBuildOperationIntegrationTest.groovy
Labels: a:chore, from:member, in:composite-builds

#5882 Injecting a no-op RepositoryResourceAccessor for flat dir repos
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ComponentMetadataRulesInjectionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/AbstractArtifactRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultFlatDirArtifactRepository.java
Labels: a:bug, from:member, in:dependency-management

#5859 Add missing @Nullable annotations on org.gradle.internal types
  subprojects/base-services/src/main/java/org/gradle/api/NonNullApi.java
  subprojects/base-services/src/main/java/org/gradle/internal/Actions.java
  subprojects/base-services/src/main/java/org/gradle/internal/Cast.java
  subprojects/base-services/src/main/java/org/gradle/internal/IoActions.java
  subprojects/base-services/src/main/java/org/gradle/internal/Pair.java
Labels: a:chore, from:member, in:core

#5806 Set timeout for AbstractIntegrationSpec
  subprojects/build-cache-http/src/integTest/groovy/org/gradle/caching/http/internal/HttpBuildCacheServiceIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/InitScriptExecutionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/artifactreuse/ArtifactResolutionQueryIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/caching/RecoverFromBrokenResolutionIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/BuildSourceBuilderIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/StaleOutputHistoryLossIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractIntegrationSpec.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/AbstractGradleExecuter.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/timeout/IntegrationTestTimeout.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/timeout/IntegrationTestTimeoutExtension.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/timeout/IntegrationTestTimeoutInterceptor.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/timeout/TimeoutAdapter.java
  subprojects/internal-integ-testing/src/test/groovy/org/gradle/integtests/fixtures/timeout/IntegrationTestTimeoutInterceptorSpec.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/DaemonFeedbackIntegrationSpec.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/server/scaninfo/DaemonScanInfoIntegrationSpec.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/groovy/compile/InProcessGroovyCompilerIntegrationTest.groovy
  subprojects/process-services/src/integTest/groovy/org/gradle/process/internal/health/memory/MemoryStatusUpdateIntegrationTest.groovy
  subprojects/testing-base/src/integTest/groovy/org/gradle/testing/SecurityManagerIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/ParallelTestExecutionIntegrationTest.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/NoIsolationWorkerExecutorSampleIntegrationTest.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WaitForCompletionWorkerExecutorSampleIntegrationTest.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerDaemonExpirationIntegrationTest.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerDaemonIntegrationTest.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerDaemonLifecycleTest.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerDaemonWorkerExecutorSampleIntegrationTest.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerExecutorErrorHandlingIntegrationTest.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerExecutorInjectionIntegrationTest.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerExecutorIntegrationTest.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerExecutorNestingIntegrationTest.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerExecutorParallelIntegrationTest.groovy
Labels: a:chore, from:member, in:testing

#5875 Update the manual-maintained xml configurations to 2018.1
  .teamcity/Gradle_Promotion/buildTypes/Gradle_Promotion_FinalRelease.xml
  .teamcity/Gradle_Promotion/buildTypes/Gradle_Promotion_MasterNightlySnapshotManual.xml
  .teamcity/Gradle_Promotion/buildTypes/Gradle_Promotion_MasterSanityCheck.xml
  .teamcity/Gradle_Promotion/buildTypes/Gradle_Promotion_MilestoneMaster.xml
  .teamcity/Gradle_Promotion/buildTypes/Gradle_Promotion_ReleaseSnapshotFromQuickFeedback.xml
  .teamcity/Gradle_Promotion/buildTypes/Gradle_Promotion_StartReleaseCycle.xml
  .teamcity/Gradle_Promotion/buildTypes/bt39.xml
  .teamcity/Gradle_Promotion/buildTypes/bt60.xml
  .teamcity/Gradle_Promotion/buildTypes/bt61.xml
  .teamcity/Gradle_Promotion/pluginData/plugin-settings.xml
  .teamcity/Gradle_Promotion/project-config.xml
  .teamcity/Gradle_Promotion/vcsRoots/Gradle_Promotion_GradlePromotionBranches.xml
  .teamcity/Gradle_Promotion/vcsRoots/Gradle_Promotion__master_.xml
  .teamcity/Gradle_Util/buildTypes/Gradle_Util_AdHocFunctionalTestLinux.xml
  .teamcity/Gradle_Util/buildTypes/Gradle_Util_AdHocFunctionalTestWindows.xml
  .teamcity/Gradle_Util/project-config.xml
  .teamcity/Gradle_Util_Performance/buildTypes/Gradle_Util_Performance_AdHocPerformanceScenarioLinux.xml
  .teamcity/Gradle_Util_Performance/buildTypes/Gradle_Util_Performance_PerformanceTestCoordinatorLinux.xml
  .teamcity/Gradle_Util_Performance/project-config.xml
Labels: a:chore, from:member

#5869 Defer parsing of force rules
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolutionstrategy/DefaultResolutionStrategy.java
Labels: a:chore, from:member, in:dependency-management

#5872 Defer parsing of exclude rules
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/LocalExcludeResolveIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java
Labels: a:chore, from:member, in:dependency-management

#5892 Expose `sourceSets` extension as `SourceSetContainer`
  subprojects/plugins/src/main/java/org/gradle/api/internal/tasks/DefaultSourceSetContainer.java
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/JavaBasePluginTest.groovy
Labels: a:feature, from:member, in:core

#5893 Make CiReportingPlugin cheaper
  buildSrc/subprojects/buildquality/src/main/kotlin/org/gradle/gradlebuild/buildquality/CiReportingPlugin.kt
Labels: a:chore, from:member

#5895 Defer parsing of substitutions to runtime
  buildSrc/subprojects/configuration/src/main/kotlin/org/gradle/gradlebuild/dependencies/DependenciesMetadataRulesPlugin.kt
Labels: a:chore, from:member

#5896 Read capabilities.json only once
  buildSrc/subprojects/configuration/src/main/kotlin/org/gradle/gradlebuild/dependencies/DependenciesMetadataRulesPlugin.kt
Labels: a:chore, from:member

#5886 Intern type names in incremental compile caches
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/IncrementalCompilerFactory.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/analyzer/DefaultClassDependenciesAnalyzer.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/asm/ClassDependenciesVisitor.java
  subprojects/language-java/src/main/java/org/gradle/language/java/internal/JavaLanguagePluginServiceRegistry.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/incremental/analyzer/DefaultClassDependenciesAnalyzerTest.groovy
Labels: a:chore, from:member, in:jvm-platform

#5786 Don't run play tests in build branch accept
  .teamcity/Gradle_Check/configurations/StagePasses.kt
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/Gradle_Check/projects/FunctionalTestProject.kt
  .teamcity/Gradle_Check/projects/RootProject.kt
  .teamcity/Gradle_Check/projects/StageProject.kt
  .teamcityTest/Gradle_Check_Tests/CIConfigIntegrationTests.kt
Labels: a:chore, from:member

#5811 Preliminary support for building Gradle on Java 9
  buildSrc/subprojects/configuration/src/main/kotlin/org/gradle/gradlebuild/java/AvailableJavaInstallations.kt
  buildSrc/subprojects/ide/src/main/kotlin/org/gradle/gradlebuild/ide/IdePlugin.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/DistributionTest.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/gradlebuild/unittestandcompile/UnitTestAndCompilePlugin.kt
  subprojects/base-services/base-services.gradle.kts
  subprojects/base-services/src/main/java/org/gradle/internal/classloader/ClassLoaderUtils.java
  subprojects/base-services/src/main/java/org/gradle/internal/classloader/MultiParentClassLoader.java
  subprojects/base-services/src/main/java/org/gradle/internal/hash/Hashing.java
  subprojects/base-services/src/main/java/org/gradle/internal/io/StreamByteBuffer.java
  subprojects/distributions/src/integTest/groovy/org/gradle/SrcDistributionIntegrationSpec.groovy
  subprojects/language-java/language-java.gradle
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/AnnotationProcessingCompileTask.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/ResourceCleaningCompilationTask.java
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/SupportedBuildJvmIntegrationTest.groovy
  subprojects/messaging/src/main/java/org/gradle/internal/remote/internal/inet/SocketConnection.java
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/inception/GradleBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/inception/GradleInceptionPerformanceTest.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/ToolingApiUnsupportedClientJvmCrossVersionSpec.groovy
  subprojects/wrapper/src/crossVersionTest/groovy/org/gradle/integtests/WrapperCrossVersionIntegrationTest.groovy
  subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy
  subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperHttpIntegrationTest.groovy
  subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperSupportedBuildJvmIntegrationTest.groovy
Labels: a:chore

#5910 Simplify incremental compile logging
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractCrossTaskIncrementalJavaCompilationIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/SourceIncrementalJavaCompilationIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/IncrementalCompilerDecorator.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/IncrementalCompilerFactory.java
Labels: from:member

#5856 Emit build operations for early executed artifact transforms
  subprojects/core/src/main/java/org/gradle/execution/TaskExecutionGraphInternal.java
  subprojects/core/src/main/java/org/gradle/execution/taskgraph/DefaultTaskExecutionGraph.java
  subprojects/core/src/main/java/org/gradle/execution/taskgraph/DefaultTaskExecutionPlan.java
  subprojects/core/src/main/java/org/gradle/execution/taskgraph/TaskExecutionPlan.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/api/artifacts/transform/ArtifactTransformBuildScanIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformInfoFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformArtifactOperation.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformArtifactsAction.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformFileOperation.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformInfo.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformInfoExecutor.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformingAsyncArtifactListener.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/DefaultIvyArtifactName.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/internal/scan/config/fixtures/BuildScanPluginFixture.groovy
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/AbstractConsoleBuildPhaseFunctionalTest.groovy
Labels: from:member, in:build-cache

#5884 Document periodic cache cleanup in Release Notes
  subprojects/docs/src/docs/release/notes.md
Labels: a:chore, from:member, in:docs

#5918 Update mockito-kotlin to 1.6.0
  buildSrc/subprojects/kotlin-dsl/kotlin-dsl.gradle.kts
  buildSrc/subprojects/plugins/plugins.gradle.kts
Labels: a:chore, from:member

#5862 Remove workaround in Gradle build
  subprojects/docs/docs.gradle
  subprojects/runtime-api-info/runtime-api-info.gradle.kts
Labels: a:chore, from:member, in:gradle-build

#5687 Let ProjectConnection extend Closeable interface
  subprojects/tooling-api/src/main/java/org/gradle/tooling/ProjectConnection.java
Labels: from:contributor, in:tooling-api

#5922 Delete empty package directories
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/SourceIncrementalJavaCompilationIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/IncrementalCompilationInitializer.java
  subprojects/platform-base/src/main/java/org/gradle/language/base/internal/tasks/SimpleStaleClassCleaner.java
  subprojects/platform-base/src/main/java/org/gradle/language/base/internal/tasks/StaleClassCleaner.java
  subprojects/platform-base/src/test/groovy/org/gradle/language/base/internal/tasks/SimpleStaleClassCleanerTest.groovy
Labels: from:member

#5925 Fix undeterministic order of resolution of capability conflicts
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/conflicts/DefaultCapabilitiesConflictHandler.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/conflicts/DefaultCapabilitiesConflictHandlerTest.groovy
Labels: a:bug, in:dependency-management

#5924 Add section for lazy task APIs in release notes
  subprojects/docs/src/docs/release/notes.md
Labels: a:chore, from:member, in:docs

#5904 Avoid reinitializing DefaultPersistentDirectoryStores
  subprojects/build-cache/src/integTest/groovy/org/gradle/caching/local/internal/DirectoryBuildCacheCleanupIntegrationTest.groovy
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/DefaultCacheFactory.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/DefaultPersistentDirectoryCache.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/DefaultPersistentDirectoryStore.java
  subprojects/persistent-cache/src/test/groovy/org/gradle/cache/internal/DefaultPersistentDirectoryCacheTest.groovy
  subprojects/persistent-cache/src/test/groovy/org/gradle/cache/internal/DefaultPersistentDirectoryStoreConcurrencyTest.groovy
  subprojects/persistent-cache/src/test/groovy/org/gradle/cache/internal/DefaultPersistentDirectoryStoreTest.groovy
Labels: a:feature, from:member, in:core

#5906 Clean up custom distributions
  subprojects/base-services/src/main/java/org/gradle/util/GradleVersion.java
  subprojects/core/src/integTest/groovy/org/gradle/cache/internal/VersionSpecificCacheAndWrapperDistributionCleanupServiceIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/cache/internal/WrapperDistributionCleanupAction.java
  subprojects/core/src/test/groovy/org/gradle/cache/internal/VersionSpecificCacheAndWrapperDistributionCleanupServiceTest.groovy
  subprojects/core/src/test/groovy/org/gradle/cache/internal/WrapperDistributionCleanupActionTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/cache/internal/VersionSpecificCacheAndWrapperDistributionCleanupServiceFixture.groovy
Labels: a:feature, from:member, in:core

#5919 Document periodic cache cleanup in User Guide
  subprojects/docs/src/docs/userguide/dependencyCache.adoc
Labels: a:chore, from:member, in:docs

#5916 Make artifact and transforms caches user-home scoped
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementGradleUserHomeScopeServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/DefaultArtifactCacheLockingManager.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformedFileCache.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/DefaultArtifactCacheLockingManagerTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/DefaultTransformedFileCacheTest.groovy
Labels: a:feature, from:member, in:dependency-management

#5887 Fix failing test on Windows
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/BaseDirFileResolverSpec.groovy
Labels: from:contributor, waiting-for:gradle-team

#5932 Log info instead of warning on cleanup timeout
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/AbstractCacheCleanup.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/DefaultPersistentDirectoryStore.java
Labels: a:feature, from:member, in:core

#5863 Mention `Task` dependencies/ordering can take a `Provider`
  subprojects/core-api/src/main/java/org/gradle/api/Task.java
Labels: a:chore, from:member, in:docs

#5946 Remove leading slash when reading from JAR file
  subprojects/core/src/integTest/groovy/org/gradle/cache/internal/WrapperDistributionCleanupActionIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/cache/internal/WrapperDistributionCleanupAction.java
  subprojects/core/src/testFixtures/groovy/org/gradle/cache/internal/VersionSpecificCacheAndWrapperDistributionCleanupServiceFixture.groovy
Labels: a:bug, from:member, in:core

#5952 Make UriNotationConverter faster on Windows
  subprojects/core/src/main/java/org/gradle/api/internal/file/FileOrUriNotationConverter.java
Labels: a:chore, from:member

#5958 Intern more paths/path segments for file snapshots
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/DefaultClasspathSnapshotter.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/DefaultCompileClasspathSnapshotter.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/DefaultGenericFileCollectionSnapshotter.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/SnapshotMapSerializer.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/mirror/MirrorUpdatingDirectoryWalker.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/mirror/logical/ClasspathFingerprintingStrategy.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/mirror/logical/RelativePathFingerprintingStrategy.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/changedetection/state/mirror/logical/PathNormalizationStrategyTest.groovy
Labels: from:member

#5936 Clarify deprecation message for FileTrees as outputs
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalBuildIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/CacheBackedTaskHistoryRepository.java
Labels: from:member

#5933 Make incremental compilation the default.
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/buildingJavaProjects.adoc
  subprojects/docs/src/docs/userguide/javaPlugin.adoc
  subprojects/docs/src/samples/java/incrementalAnnotationProcessing/user/build.gradle
  subprojects/docs/src/samples/userguide/java/basic/build.gradle
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/AbstractIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractCrossTaskIncrementalJavaCompilationIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/CompileAvoidanceWithIncrementalJavaCompilationIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/SourceIncrementalJavaCompilationIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/language/java/JavaLanguageIncrementalBuildIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/CompileOptions.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
  subprojects/language-jvm/src/testFixtures/groovy/org/gradle/integtests/language/AbstractJvmLanguageIncrementalBuildIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/MultiProjectContinuousIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/SimpleJavaContinuousIntegrationTest.groovy
  subprojects/performance/src/templates/project-with-source/build.gradle
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/AbstractJavaCompileAvoidanceIntegrationSpec.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/IncrementalCompileMultiProjectTestFixture.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/IncrementalJavaCompileAvoidanceAgainstClassDirIntegrationSpec.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/IncrementalJavaCompileAvoidanceAgainstJarIntegrationSpec.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/IncrementalJavaCompileIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/NonIncrementalJavaCompileAvoidanceAgainstClassDirIntegrationSpec.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/NonIncrementalJavaCompileAvoidanceAgainstJarIntegrationSpec.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/IncrementalTestIntegrationTest.groovy
Labels: from:member

#5966 Honor singleUse when creating GlobalScopeServices
  subprojects/core/src/integTest/groovy/org/gradle/internal/environment/GradleBuildEnvironmentIntegrationTest.groovy
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/DaemonServices.java
Labels: a:bug, from:member

#5954 Fix distribution cleanup for pre 4.x releases
  subprojects/core/src/main/java/org/gradle/cache/internal/WrapperDistributionCleanupAction.java
  subprojects/core/src/test/groovy/org/gradle/cache/internal/WrapperDistributionCleanupActionTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/cache/internal/VersionSpecificCacheAndWrapperDistributionCleanupServiceFixture.groovy
Labels: a:bug, from:member, in:core

#5937 Prevent eager realization for `dependsOn tasks.withType(...)`
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/DeferredTaskDefinitionIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/collections/FilteredCollection.java
Labels: a:bug, from:member, in:core

#5970 Remove `TaskProvider` from task dependencies when the `Task` instance is provided
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskDependencyIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskDependency.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/DefaultTaskDependencyTest.groovy
Labels: a:bug, from:member, in:core

#5956 Fix thread leak in worker API
  subprojects/base-services/src/main/java/org/gradle/internal/concurrent/ManagedExecutor.java
  subprojects/base-services/src/main/java/org/gradle/internal/concurrent/ManagedExecutorImpl.java
  subprojects/base-services/src/main/java/org/gradle/internal/work/DefaultConditionalExecutionQueue.java
  subprojects/base-services/src/test/groovy/org/gradle/internal/work/DefaultConditionalExecutionQueueTest.groovy
  subprojects/core/src/main/java/org/gradle/internal/work/AsyncWorkTracker.java
  subprojects/core/src/main/java/org/gradle/internal/work/DefaultAsyncWorkTracker.java
  subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/ConcurrentTestUtil.groovy
  subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/concurrent/TestManagedExecutor.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerExecutorNestingIntegrationTest.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerExecutorParallelIntegrationTest.groovy
  subprojects/workers/src/main/java/org/gradle/workers/internal/DefaultWorkerExecutor.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/WorkerExecutionQueueFactory.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/WorkersServices.java
  subprojects/workers/src/test/groovy/org/gradle/workers/internal/DefaultWorkerExecutorParallelTest.groovy
  subprojects/workers/src/test/groovy/org/gradle/workers/internal/DefaultWorkerExecutorTest.groovy
Labels: a:bug, from:member

#5986 Rebase native performance test on latest nightly
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeBuildDependentsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeCleanBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/RealWorldNativePluginPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftCleanBuildPerformanceTest.groovy
Labels: a:chore, from:member, in:native-platform

#5993 Remove unused parameter
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/plugins/MavenPluginPublishPlugin.java
Labels: a:chore, from:member, in:plugin-development

#5999 Mention build scan instead of internal flag in the userguide
  subprojects/docs/src/docs/userguide/task_configuration_avoidance.adoc
Labels: a:chore, from:member, in:docs

#5967 Extract lenient platform classes from `NodeState`
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/LenientPlatformDependencyMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/LenientPlatformResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/NodeState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/PotentialEdge.java
Labels: a:chore, from:member, in:dependency-management

#5901 Add diagnose code for NPE thrown in ExceptionPlaceHolder
  subprojects/messaging/src/main/java/org/gradle/internal/serialize/ExceptionPlaceholder.java
Labels: a:chore, from:member, in:core

#5988 Add displayName and description to PluginDeclaration
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/plugins/JavaGradlePluginPluginPublishingIntegrationTest.groovy
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/PluginDeclaration.java
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/plugins/IvyPluginPublishingPlugin.java
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/plugins/MavenPluginPublishPlugin.java
Labels: a:feature, from:member, in:plugin-development

#6028 Improvements on ClassLoaderUtils
  subprojects/base-services/src/integTest/groovy/org/gradle/internal/classloader/ClassLoaderUtilsIntegrationTest.groovy
  subprojects/base-services/src/main/java/org/gradle/internal/classloader/ClassLoaderUtils.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/LogContent.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/OutputScrapingExecutionResult.java
  subprojects/model-core/src/main/java/org/gradle/model/internal/asm/AsmClassGenerator.java
Labels: a:chore, from:member

#5621 Issue: #5571 Implement http header based authorization for maven repositories
  subprojects/core-api/src/main/java/org/gradle/api/credentials/HttpHeaderCredentials.java
  subprojects/core/src/main/java/org/gradle/internal/credentials/DefaultHttpHeaderCredentials.java
  subprojects/core/src/main/java/org/gradle/internal/credentials/DefaultPasswordCredentials.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/http/HttpAuthenticationDependencyResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/AuthenticationSupporter.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/AbstractAuthenticationSupportedRepositoryTest.groovy
  subprojects/docs/src/docs/dsl/dsl.xml
  subprojects/docs/src/docs/dsl/org.gradle.api.credentials.HttpHeaderCredentials.xml
  subprojects/docs/src/docs/dsl/org.gradle.authentication.http.HttpHeaderAuthentication.xml
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/repository_types.adoc
  subprojects/docs/src/samples/userguide/artifacts/defineRepository/build.gradle
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/AuthScheme.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/HttpServerFixture.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/TestHttpHeaderAuthenticator.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishHttpIntegTest.groovy
  subprojects/resources-http/src/main/java/org/gradle/authentication/http/HttpHeaderAuthentication.java
  subprojects/resources-http/src/main/java/org/gradle/internal/authentication/DefaultHttpHeaderAuthentication.java
  subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/HttpClientConfigurer.java
  subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/HttpClientHttpHeaderCredentials.java
  subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/HttpConnectorFactory.java
  subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/HttpHeaderAuthScheme.java
  subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/HttpHeaderSchemeFactory.java
  subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/HttpProxySettings.java
  subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/HttpResourcesPluginServiceRegistry.java
  subprojects/resources-http/src/test/groovy/org/gradle/internal/resource/transport/http/HttpClientConfigurerTest.groovy
  subprojects/resources-http/src/test/groovy/org/gradle/internal/resource/transport/http/HttpClientHttpHeaderCredentialsTest.groovy
  subprojects/resources-http/src/test/groovy/org/gradle/internal/resource/transport/http/HttpHeaderAuthSchemeTest.groovy
  subprojects/resources-sftp/src/integTest/groovy/org/gradle/integtests/resolve/resource/sftp/SftpClientReuseIntegrationTest.groovy
  subprojects/resources-sftp/src/test/groovy/org/gradle/internal/resource/transport/sftp/SftpClientFactoryTest.groovy
Labels: from:contributor, waiting-for:gradle-team

#6032 Recompile when module-info files change
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/compile/ApiMemberSelector.java
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractCrossTaskIncrementalJavaCompilationIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/SourceIncrementalJavaCompilationIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/DefaultJavaCompileSpec.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompileSpec.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/IncrementalResultStoringCompiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/asm/ClassDependenciesVisitor.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/CurrentCompilation.java
Labels: a:feature, from:member, in:jvm-platform

#6037 Recompile types in a package if its package-info changes
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractCrossTaskIncrementalJavaCompilationIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/SourceIncrementalJavaCompilationIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/classpath/ClasspathEntrySnapshot.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/AffectedClasses.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassDependentsAccumulator.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisData.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisDataSerializerTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisTest.groovy
Labels: a:feature, from:member, in:jvm-platform

#6043 Reduce performance cost of repository descriptors by caching
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/AbstractArtifactRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/AbstractAuthenticationSupportedRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/AbstractResolutionAwareArtifactRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultFlatDirArtifactRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultIvyArtifactRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultMavenArtifactRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/descriptor/RepositoryDescriptor.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/AbstractAuthenticationSupportedRepositoryTest.groovy
Labels: from:member

#6034 Deprecation progress events are enriched to allow better visualisation
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CheckstylePlugin.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/CheckstyleInvoker.groovy
  subprojects/core-api/src/main/java/org/gradle/internal/deprecation/LoggingDeprecatable.java
  subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalBuildSymlinkHandlingIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskInputPropertiesIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/groovy/scripts/GradleUtilDefaultImportDeprecationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/CacheBackedTaskHistoryRepository.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/AbstractFileCollection.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskInputs.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskValidationContext.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/options/OptionReader.java
  subprojects/core/src/main/java/org/gradle/groovy/scripts/internal/DefaultScriptCompilationHandler.java
  subprojects/core/src/main/java/org/gradle/internal/jvm/UnsupportedJavaRuntimeException.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompilerArgumentsBuilder.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/AnnotationProcessorPathFactory.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/DefaultConnection.java
  subprojects/logging/src/integTest/groovy/org/gradle/DeprecatedUsageBuildOperationProgressIntegrationTest.groovy
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/DefaultDeprecatedUsageProgressDetails.java
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/DeprecatedUsageProgressDetails.java
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/FeatureUsage.java
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/LoggingIncubatingFeatureHandler.java
  subprojects/logging/src/main/java/org/gradle/util/DeprecationLogger.java
  subprojects/logging/src/main/java/org/gradle/util/SingleMessageLogger.java
  subprojects/logging/src/test/groovy/org/gradle/internal/featurelifecycle/FeatureUsageTest.groovy
  subprojects/logging/src/test/groovy/org/gradle/internal/featurelifecycle/LoggingDeprecatedFeatureHandlerTest.groovy
  subprojects/logging/src/test/groovy/org/gradle/internal/featurelifecycle/SimulatedDeprecationMessageLogger.java
  subprojects/publish/src/main/java/org/gradle/api/publish/plugins/PublishingPlugin.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java
Labels: from:member

#6013 Use Groovy 2.4.15
  buildSrc/build.gradle.kts
  gradle/dependencies.gradle
  gradle/shared-with-buildSrc/code-quality-configuration.gradle.kts
  subprojects/base-services/src/test/groovy/org/gradle/internal/service/ServiceLocatorTest.groovy
  subprojects/docs/src/docs/userguide/installation.adoc
  subprojects/docs/src/samples/groovy/crossCompilation/build.gradle
  subprojects/docs/src/samples/groovy/customizedLayout/build.gradle
  subprojects/docs/src/samples/groovy/mixedJavaAndGroovy/build.gradle
  subprojects/docs/src/samples/groovy/multiproject/groovycDetector/build.gradle
  subprojects/docs/src/samples/groovy/multiproject/testproject/build.gradle
  subprojects/docs/src/samples/groovy/multiproject/testproject/src/test/groovy/org/gradle/VersionTest.groovy
  subprojects/docs/src/samples/groovy/quickstart/build.gradle
  subprojects/docs/src/samples/groovy/quickstart/src/test/groovy/org/gradle/PersonTest.groovy
  subprojects/docs/src/samples/osgi/build.gradle
  subprojects/docs/src/samples/userguide/artifacts/externalDependencies/build.gradle
  subprojects/docs/src/samples/userguide/groovy/groovyDependency/build.gradle
  subprojects/docs/src/samples/userguide/tutorial/groovyWithFlatDir/build.gradle
  subprojects/docs/src/samples/userguide/tutorial/projectReports/build.gradle
  subprojects/performance/src/templates/config-inject/build.gradle
  subprojects/performance/src/templates/kts-project-with-source/build.gradle.kts
  subprojects/performance/src/templates/project-with-source/build.gradle
  subprojects/performance/templates.gradle
  subprojects/testing-jvm/src/integTest/resources/org/gradle/testing/junit/JUnitConsoleLoggingIntegrationTest/shared/build.gradle
  subprojects/testing-jvm/src/integTest/resources/org/gradle/testing/junit/JUnitConsoleLoggingIntegrationTest/standardOutputLogging/build.gradle
Labels: from:member, in:build-cache

#6052 Let task logger be replaceable temporarily
  subprojects/core/src/main/java/org/gradle/api/internal/AbstractTask.java
  subprojects/core/src/main/java/org/gradle/api/internal/TaskInternal.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/DefaultTaskTest.groovy
Labels: from:member

#6050 Avoid calling File.listRoots()
  subprojects/core/src/main/java/org/gradle/api/internal/file/FileOrUriNotationConverter.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/BaseDirFileResolverSpec.groovy
Labels: a:chore, from:member, in:core

#6057 Intern Strings when read from the backing store of the file hasher
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/CachingFileHasher.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/CrossBuildFileHashCache.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/DefaultTaskHistoryStore.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/TaskHistoryStore.java
Labels: a:chore, from:member, in:core

#6060 Simplify PatternSpec caching
  subprojects/core-api/src/main/java/org/gradle/api/tasks/util/internal/CachingPatternSpecFactory.java
Labels: a:chore, from:member, in:core

#6054 Ensure root component metadata artifacts are resolved with mutable project
  subprojects/core/src/test/groovy/org/gradle/util/NameValidatorTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultDependencyManagementServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationContainer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/moduleconverter/DefaultRootComponentMetadataBuilder.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationContainerSpec.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationContainerTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/moduleconverter/DefaultRootComponentMetadataBuilderTest.groovy
Labels: a:bug, from:member

#6069 Let the `kotlin-dsl` plugin handle the Kotlin DSL dependencies
  buildSrc/subprojects/kotlin-dsl/kotlin-dsl.gradle.kts
  buildSrc/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/kotlin-dsl-upstream.kt
Labels: dogfood:kotlin-dsl, from:member, in:gradle-build

#6047 Change release-note.gradle mavenCentral() to mirror
  buildSrc/build.gradle.kts
  buildSrc/subprojects/docs/docs.gradle.kts
  gradle/shared-with-buildSrc/mirrors.gradle.kts
  subprojects/docs/src/transforms/release-notes.gradle
Labels: a:chore, dev-productivity, from:member

#6041 Disable adding tasks/providers directly to TaskContainer
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskContainer.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskContainerFactory.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskContainerInternal.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/DefaultTaskContainerTest.groovy
  subprojects/docs/src/docs/release/notes.md
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/CachedKotlinTaskExecutionIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/NestedInputKotlinImplementationTrackingIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskDefinitionIntegrationTest.groovy
  subprojects/logging/src/main/java/org/gradle/util/SingleMessageLogger.java
  subprojects/platform-base/src/main/java/org/gradle/platform/base/plugins/BinaryBasePlugin.java
  subprojects/plugin-development/src/test/groovy/org/gradle/plugin/devel/plugins/JavaGradlePluginPluginTest.groovy
  subprojects/testing-base/src/main/java/org/gradle/testing/base/plugins/TestingModelBasePlugin.java
Labels: a:chore, from:member

#6079 Make task output parsing robust against sub progress loggers
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/logging/GroupedOutputFixture.java
  subprojects/internal-integ-testing/src/test/groovy/org/gradle/integtests/fixtures/logging/GroupedOutputFixtureTest.groovy
Labels: a:chore, from:member, in:logging

#6071 Upgrade Kotlin DSL {0.18.4 => 0.19.0}
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/settings.gradle.kts
  buildSrc/subprojects/buildquality/src/main/kotlin/org/gradle/gradlebuild/buildquality/DependencyVulnerabilitiesPlugin.kt
  buildSrc/subprojects/configuration/src/main/kotlin/org/gradle/gradlebuild/build-environment.kt
  buildSrc/subprojects/ide/src/main/kotlin/org/gradle/gradlebuild/ide/IdePlugin.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/fixtures/TestFixturesPlugin.kt
  buildSrc/subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/TaskContainerExtensionsTest.kt
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/ShadedJar.kt
  buildSrc/subprojects/performance/performance.gradle.kts
  buildSrc/subprojects/plugins/plugins.gradle.kts
  buildSrc/subprojects/plugins/src/main/kotlin/gradlebuild/strict-compile.gradle.kts
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/gradlebuild/unittestandcompile/UnitTestAndCompilePlugin.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/buildtypes/BuildTypesPlugin.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/performance/PerformanceTestPlugin.kt
  buildSrc/subprojects/plugins/src/test/kotlin/org/gradle/plugins/buildtypes/BuildTypesPluginTest.kt
  buildSrc/subprojects/profiling/profiling.gradle.kts
  buildSrc/subprojects/uber-plugins/src/main/kotlin/gradlebuild/java-projects.gradle.kts
  buildSrc/subprojects/uber-plugins/uber-plugins.gradle.kts
  settings.gradle.kts
  subprojects/distributions/src/integTest/groovy/org/gradle/DistributionIntegrationSpec.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/CachedKotlinTaskExecutionIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/NestedInputKotlinImplementationTrackingIntegrationTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationPerformanceTest.groovy
  subprojects/performance/src/templates/kts-empty/build.gradle.kts
  subprojects/performance/src/templates/kts-project-with-source/build.gradle.kts
  subprojects/performance/templates.gradle
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/kotlin-dsl-multi-project-with-buildSrc/buildSrc/settings.gradle.kts
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/kotlin-dsl-multi-project-with-buildSrc/settings.gradle
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/kotlin-dsl-multi-project-with-buildSrc/settings.gradle.kts
  subprojects/tooling-api/tooling-api.gradle.kts
Labels: dogfood:kotlin-dsl, from:member, in:core

#6076 Make URI scheme matching faster
  subprojects/core/src/main/java/org/gradle/api/internal/file/AbstractFileResolver.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/FileOrUriNotationConverter.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/FileOrUriNotationConverterTest.groovy
Labels: a:chore, from:member, in:core

#6066 Intern class names when reading back from the cache
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/CachingFileHasher.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/IncrementalCompilerDecorator.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/IncrementalCompilerFactory.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/IncrementalResultStoringCompiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/analyzer/ClassAnalysisSerializer.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/asm/ClassDependenciesVisitor.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/cache/DefaultGeneralCompileCaches.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/cache/DefaultUserHomeScopedCompileCaches.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/classpath/ClasspathEntrySnapshotDataSerializer.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisData.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/processing/AnnotationProcessingData.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/PreviousCompilationData.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisDataSerializerTest.groovy
  subprojects/messaging/src/main/java/org/gradle/internal/serialize/InterningStringSerializer.java
  subprojects/plugins/src/main/java/org/gradle/api/internal/tasks/CompileServices.java
Labels: a:chore, from:member, in:jvm-platform

#6087 Add a settings script to "create many deprecations" perf test
  subprojects/performance/src/templates/generateLotsOfDeprecationWarnings/settings.gradle
Labels: from:member

#6080 Reinstate requirement for removal details in deprecation notices
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskContainer.java
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskDefinitionIntegrationTest.groovy
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/DeprecatedFeatureUsage.java
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/DeprecatedUsageProgressDetails.java
  subprojects/logging/src/main/java/org/gradle/util/SingleMessageLogger.java
Labels: from:member

#6082 Post kotlin-dsl 0.19.0 activities
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/fixtures/TestFixturesPlugin.kt
  buildSrc/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/kotlin-dsl-upstream-candidates.kt
  buildSrc/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/kotlin-dsl-upstream.kt
  buildSrc/subprojects/plugins/src/main/kotlin/gradlebuild/strict-compile.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/inception/GradleInceptionPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationPerformanceTest.groovy
Labels: from:member, in:gradle-build

#6078 Monitor execution timeout in build
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/IntegrationTest.kt
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/timeout/IntegrationTestTimeoutInterceptor.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/timeout/JavaProcessStackTracesMonitor.groovy
  subprojects/internal-integ-testing/src/test/groovy/org/gradle/integtests/fixtures/timeout/JavaProcessStackTracesMonitorSpec.groovy
Labels: a:chore, dev-productivity, from:member

#6085 Respect default excludes for snapshotting
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/mirror/MirrorUpdatingDirectoryWalker.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/changedetection/state/mirror/MirrorUpdatingDirectoryWalkerTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskUpToDateIntegrationTest.groovy
Labels: from:member

#6046 Restrict memory usage of Java performance tests
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/generator/JavaTestProject.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidStudioMockupPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingJavaPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingNativePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingSwiftPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ArchiveTreePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/DeprecationCreationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ExcludeRuleMergingPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/IdeIntegrationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/LargeDependencyGraphPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ParallelDownloadsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ProjectCreationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/RichConsolePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/TaskCreationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/VerboseTestOutputPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/inception/GradleInceptionPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaABIChangePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaCleanAssemblePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaDependencyReportPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaFirstUsePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIDEModelPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaNonABIChangePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaTasksPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaTestChangePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaUpToDatePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/kotlindsl/GradleKotlinDslBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeBuildDependentsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeCleanBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/RealWorldNativePluginPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftCleanBuildPerformanceTest.groovy
Labels: a:chore, from:member, in:jvm-platform

#6088 Clean up distributions at most every 24 hours
  subprojects/core/src/main/java/org/gradle/cache/internal/DirectoryCleanupAction.java
  subprojects/core/src/main/java/org/gradle/cache/internal/GradleUserHomeCleanupService.java
  subprojects/core/src/main/java/org/gradle/cache/internal/VersionSpecificCacheCleanupAction.java
  subprojects/core/src/main/java/org/gradle/cache/internal/WrapperDistributionCleanupAction.java
  subprojects/core/src/test/groovy/org/gradle/cache/internal/GradleUserHomeCleanupServiceTest.groovy
  subprojects/core/src/test/groovy/org/gradle/cache/internal/VersionSpecificCacheCleanupActionTest.groovy
Labels: a:bug, from:member, in:core

#6105 Let all performance tests require a settings script
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/TestProjectLocator.groovy
Labels: from:member

#6106 Disable daemon conditionally
  .teamcity/Gradle_Check/configurations/BuildDistributions.kt
  .teamcity/Gradle_Check/configurations/FunctionalTest.kt
  .teamcity/Gradle_Check/configurations/GradleBuildConfigurationDefaults.kt
  .teamcity/Gradle_Check/configurations/Gradleception.kt
  .teamcity/Gradle_Check/configurations/IndividualPerformanceScenarioWorkers.kt
  .teamcity/Gradle_Check/configurations/PerformanceTest.kt
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/Gradle_Check/projects/FunctionalTestProject.kt
  .teamcity/Gradle_Check/projects/StageProject.kt
Labels: a:chore, dev-productivity, from:member

#6093 Remove stale files for scala compilation
  subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/CleaningScalaCompiler.java
  subprojects/language-scala/src/main/java/org/gradle/language/scala/tasks/AbstractScalaCompile.java
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/CachedScalaCompileIntegrationTest.groovy
Labels: from:member

#6003 Disallow use of hooks by a lazy task configuration action
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/DistributionTestingPlugin.kt
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/DeferredTaskDefinitionIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/project/BuildOperationCrossProjectConfigurator.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/CrossProjectConfigurator.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProject.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskContainer.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskContainerFactory.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/ProjectScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/BuildOperationCrossProjectConfiguratorTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/DefaultProjectSpec.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/DefaultProjectTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/DefaultTaskContainerTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/service/scopes/ProjectScopeServicesTest.groovy
  subprojects/core/src/test/groovy/org/gradle/invocation/DefaultGradleSpec.groovy
  subprojects/docs/src/docs/release/notes.md
  subprojects/performance/templates.gradle
Labels: a:chore, from:member, in:core

#6107 Assert no-daemon for AsciidoctorTask
  subprojects/docs/docs.gradle
Labels: a:chore, dev-productivity, from:member

#6055 Retain iteration order in domain object collections
  subprojects/core/src/main/java/org/gradle/api/internal/CompositeDomainObjectSet.java
  subprojects/core/src/main/java/org/gradle/api/internal/DefaultDomainObjectCollection.java
  subprojects/core/src/main/java/org/gradle/api/internal/collections/AbstractIterationOrderRetainingElementSource.java
  subprojects/core/src/main/java/org/gradle/api/internal/collections/DefaultPendingSource.java
  subprojects/core/src/main/java/org/gradle/api/internal/collections/ElementSource.java
  subprojects/core/src/main/java/org/gradle/api/internal/collections/FilteredCollection.java
  subprojects/core/src/main/java/org/gradle/api/internal/collections/IterationOrderRetainingSetElementSource.java
  subprojects/core/src/main/java/org/gradle/api/internal/collections/ListElementSource.java
  subprojects/core/src/main/java/org/gradle/api/internal/collections/PendingSource.java
  subprojects/core/src/main/java/org/gradle/api/internal/collections/SortedSetElementSource.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/AbstractDomainObjectCollectionSpec.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/DefaultDomainObjectCollectionTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/collections/AbstractIterationOrderRetainingElementSourceTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/collections/DefaultPendingSourceTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/collections/IterationOrderRetainingSetElementSourceTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/collections/ListElementSourceTest.groovy
Labels: a:feature, from:member

#6132 Allow Project.subprojects and Project.allprojects to be called from l…
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/DeferredTaskDefinitionIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProject.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/task_configuration_avoidance.adoc
Labels: a:chore, from:member, in:core

#6104 Remove verbose logging of downloads and JAR generation
  subprojects/core/src/integTest/groovy/org/gradle/internal/operations/logging/LoggingBuildOperationProgressIntegTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/internal/progress/NoOpProgressLoggerFactory.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/runtimeshaded/RuntimeShadedJarCreator.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/runtimeshaded/RuntimeShadedJarFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resource/transfer/AbstractProgressLoggingHandler.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/runtimeshaded/RuntimeShadedJarCreatorTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/resource/transfer/ProgressLoggingExternalResourceUploaderTest.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/impldeps/BaseGradleImplDepsIntegrationTest.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/impldeps/GradleImplDepsConcurrencyIntegrationTest.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/impldeps/GradleImplDepsGenerationIntegrationTest.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/impldeps/GradleImplDepsLoggingIntegrationTest.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/impldeps/ResolvedGeneratedJarsIntegrationTest.groovy
Labels: from:member

#6138 Allow initializing nested builds
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/BuildInitPluginIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/initialization/layout/BuildLayoutConfiguration.java
Labels: from:member

#5997 Document how plugin authors should migrate to lazy task APIs
  subprojects/docs/src/docs/userguide/task_configuration_avoidance.adoc
Labels: a:chore, from:member, in:docs

#6141 Mitigate performance issues with iteration order
  subprojects/core/src/main/java/org/gradle/api/internal/collections/AbstractIterationOrderRetainingElementSource.java
  subprojects/core/src/main/java/org/gradle/api/internal/collections/IterationOrderRetainingSetElementSource.java
  subprojects/core/src/main/java/org/gradle/api/internal/collections/ListElementSource.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/collections/IterationOrderRetainingSetElementSourceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/RealWorldNativePluginPerformanceTest.groovy
Labels: a:chore, from:member
