Repository gradle/gradle, pull requests merged in 2018-03, with the labels that each got.

#4536 Move task property validation task dependency declaration in the corresponding plugin
  buildSrc/src/main/kotlin/org/gradle/plugins/codequality/ConfigureTaskPropertyValidationPlugin.kt
  gradle/codeQualityConfiguration.gradle.kts
Labels: dogfood:kotlin-dsl, from:member, in:gradle-build

#4517 Support Named Iterables/Maps as nested inputs
  buildSrc/src/main/groovy/org/gradle/testing/DistributionTest.groovy
  buildSrc/src/main/groovy/org/gradle/testing/IntegrationTest.groovy
  gradle/groovyProject.gradle.kts
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginVersionIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/findbugs/AbstractFindBugsPluginIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/pmd/PmdPluginVersionIntegrationTest.groovy
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/FindBugsXmlReport.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/FindBugsReportsImpl.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/FindBugsReportsInternal.java
  subprojects/core-api/src/main/java/org/gradle/api/tasks/Nested.java
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/NestedInputIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/AbstractNestedPropertyContext.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/BeanNode.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/DefaultPropertyWalker.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/NestedPropertyContext.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/PropertyNode.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/PropertyValidationAccess.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/NestedBeanAnnotationHandler.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/taskfactory/AnnotationProcessingTaskFactoryTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/taskfactory/AnnotationProcessingTasks.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/DefaultPropertyWalkerTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/PropertyValidationAccessTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/annotations/NestedBeanAnnotationHandlerTest.groovy
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/moreAboutTasks.adoc
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoPluginExtension.java
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoTaskExtension.java
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/package-info.java
  subprojects/reporting/src/integTest/groovy/org/gradle/api/reporting/internal/TaskReportContainerIntegTest.groovy
  subprojects/reporting/src/main/java/org/gradle/api/reporting/CustomizableHtmlReport.java
  subprojects/reporting/src/main/java/org/gradle/api/reporting/DirectoryReport.java
  subprojects/reporting/src/main/java/org/gradle/api/reporting/Report.java
  subprojects/reporting/src/main/java/org/gradle/api/reporting/ReportContainer.java
  subprojects/reporting/src/main/java/org/gradle/api/reporting/SingleFileReport.java
  subprojects/reporting/src/main/java/org/gradle/api/reporting/internal/DefaultReportContainer.java
  subprojects/reporting/src/main/java/org/gradle/api/reporting/internal/TaskGeneratedReport.java
  subprojects/reporting/src/test/groovy/org/gradle/api/reporting/internal/TaskGeneratedReportTest.groovy
  subprojects/reporting/src/test/groovy/org/gradle/api/reporting/internal/TaskReportContainerTest.groovy
Labels: from:member

#4549 Only generate VisualStudio metadata for buildable binaries
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/visualstudio/VisualStudioSoftwareModelSingleProjectIntegrationTest.groovy
  subprojects/ide-native/src/main/groovy/org/gradle/ide/visualstudio/plugins/VisualStudioPluginRules.java
  subprojects/platform-native/src/testFixtures/groovy/org/gradle/nativeplatform/fixtures/AvailableToolChains.java
  subprojects/platform-native/src/testFixtures/groovy/org/gradle/nativeplatform/fixtures/ToolChainRequirement.java
Labels: a:feature, from:member

#4555 Use a different workaround for Kotlin DSL `buildscript.sourceFile`
  gradle/codeQualityConfiguration.gradle.kts
Labels: a:chore, from:member

#4357 Document deprecated configurations and replacements
  subprojects/docs/src/docs/userguide/img/javaPluginConfigurations.dot
  subprojects/docs/src/docs/userguide/img/javaPluginConfigurations.graphml
  subprojects/docs/src/docs/userguide/img/javaPluginConfigurations.png
  subprojects/docs/src/docs/userguide/javaPlugin.adoc
Labels: a:chore, from:member

#4531 Make Visual Studio metadata generation tasks incremental
  subprojects/base-services-groovy/src/main/java/org/gradle/api/internal/ClosureBackedAction.java
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/NestedInputIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/NestedBeanAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/util/ConfigureUtil.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/annotations/NestedBeanAnnotationHandlerTest.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/visualstudio/VisualStudioIncrementalIntegrationTest.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/visualstudio/VisualStudioSoftwareModelIncrementalIntegrationTest.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/visualstudio/VisualStudioSoftwareModelSingleProjectIntegrationTest.groovy
  subprojects/ide-native/src/main/groovy/org/gradle/ide/visualstudio/tasks/GenerateFiltersFileTask.java
  subprojects/ide-native/src/main/groovy/org/gradle/ide/visualstudio/tasks/GenerateProjectFileTask.java
  subprojects/ide-native/src/main/groovy/org/gradle/ide/visualstudio/tasks/GenerateSolutionFileTask.java
  subprojects/ide-native/src/main/java/org/gradle/ide/visualstudio/VisualStudioProject.java
  subprojects/ide-native/src/main/java/org/gradle/ide/visualstudio/VisualStudioSolution.java
  subprojects/ide-native/src/main/java/org/gradle/ide/visualstudio/internal/DefaultVisualStudioProject.java
  subprojects/ide-native/src/main/java/org/gradle/ide/visualstudio/internal/DefaultVisualStudioSolution.java
  subprojects/ide-native/src/main/java/org/gradle/ide/visualstudio/internal/VisualStudioProjectConfiguration.java
  subprojects/ide-native/src/main/java/org/gradle/ide/visualstudio/internal/VisualStudioTargetBinary.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/api/GeneratorTask.java
Labels: a:feature, from:member

#4565 Migrated build-comparison buildscript to Kotlin
  build.gradle
  gradle/intTestImage.gradle
  settings.gradle.kts
  subprojects/build-comparison/build-comparison.gradle
  subprojects/build-comparison/build-comparison.gradle.kts
  subprojects/docs/docs.gradle
  subprojects/tooling-api/tooling-api.gradle
Labels: dogfood:kotlin-dsl, from:member

#4573 Moved wrapper and dependency resolution check to buildSrc
  build.gradle
  buildSrc/subprojects/plugins/plugins.gradle.kts
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/codequality/FailDependencyResolutionAtConfiguration.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/wrapper/ConfigureWrapperTasksPlugin.kt
  gradle/noDependencyResolutionDuringConfiguration.gradle.kts
  gradle/wrapper.gradle.kts
Labels: dogfood:kotlin-dsl, from:member

#4584 Moved groovyPlugin.gradle.kts into a buildSrc plugin
  build.gradle
  buildSrc/settings.gradle.kts
  buildSrc/subprojects/plugins/plugins.gradle.kts
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/build/ClasspathManifest.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/gradlebuild/unittestandcompile/UnitTestAndCompilePlugin.kt
  buildSrc/subprojects/plugins/src/main/kotlin/plugins-extensions.kt
  buildSrc/subprojects/uber-plugins/src/main/kotlin/org/gradle/gradlebuild.uberplugins/JavaProjectsPlugin.kt
  buildSrc/subprojects/uber-plugins/uber-plugins.gradle.kts
  subprojects/base-services/base-services.gradle.kts
  subprojects/core/core.gradle
  subprojects/docs/docs.gradle
  subprojects/internal-integ-testing/internal-integ-testing.gradle
  subprojects/internal-performance-testing/internal-performance-testing.gradle
  subprojects/reporting/reporting.gradle
  subprojects/wrapper/wrapper.gradle
Labels: dogfood:kotlin-dsl, from:member

#4566 Fix issue with TERM being set to null on bare metal agents
  subprojects/native/src/test/groovy/org/gradle/internal/nativeintegration/console/NativePlatformConsoleDetectorTest.groovy
Labels: a:chore, from:member

#4588 Prepare for Kotlin DSL upgrade to 0.16.1
  gradle/distributionTesting.gradle.kts
Labels: a:chore, from:member

#4569 Deduplicated integration testing logic and moved it to Kotlin
  buildSrc/subprojects/build/src/main/groovy/org/gradle/build/ReleasedVersionsFromVersionControl.groovy
  buildSrc/subprojects/plugins/plugins.gradle.kts
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/integrationtests/CrossVersionTestsPlugin.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/integrationtests/IntegrationTestsPlugin.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/integrationtests/excluded-tests.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/integrationtests/shared-configuration.kt
  buildSrc/subprojects/plugins/src/test/kotlin/org/gradle/plugins/integrationtests/ExcludedTestsTest.kt
  buildSrc/subprojects/uber-plugins/src/main/kotlin/org/gradle/gradlebuild.uberplugins/JavaProjectsPlugin.kt
  gradle/crossVersionTest.gradle
  gradle/integTest.gradle.kts
  gradle/java9plus.gradle
  subprojects/integ-test/integ-test.gradle
Labels: dogfood:kotlin-dsl, from:member

#4576 Fix archiving artifacts for buildSrc test failures
  buildSrc/build.gradle.kts
Labels: from:member

#4480 Handle exceptions in JUnit 5 test engine initialization
  subprojects/testing-junit-platform/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestClassProcessor.java
  subprojects/testing-junit-platform/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestExecutionListener.java
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformIntegrationTest.groovy
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/junit/AbstractJUnitTestClassProcessor.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitTestClassProcessor.java
Labels: a:bug, from:member, in:testing

#4592 Refactored Kotlin gradlebuildJava extension into Gradle extension
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/build/ClasspathManifest.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/gradlebuild/unittestandcompile/UnitTestAndCompilePlugin.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/compile/GradleCompilePlugin.kt
  buildSrc/subprojects/plugins/src/main/kotlin/plugins-extensions.kt
  subprojects/base-services/base-services.gradle.kts
  subprojects/core/core.gradle
  subprojects/docs/docs.gradle
  subprojects/internal-integ-testing/internal-integ-testing.gradle
  subprojects/internal-performance-testing/internal-performance-testing.gradle
  subprojects/reporting/reporting.gradle
  subprojects/wrapper/wrapper.gradle
Labels: dogfood:kotlin-dsl, from:member

#4492 Ignore non-static nested classes
  subprojects/testing-junit-platform/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestClassProcessor.java
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformIntegrationTest.groovy
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitTestClassExecutor.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestFramework.java
Labels: a:bug, from:member, in:testing

#4542 Fix release note transform after jsoup upgrade
  subprojects/docs/src/transforms/release-notes.gradle
Labels: a:bug, from:member, in:gradle-build

#4571 Refactored distribution test logic
  build.gradle
  buildSrc/settings.gradle.kts
  buildSrc/subprojects/cleanup/cleanup.gradle.kts
  buildSrc/subprojects/cleanup/src/main/kotlin/org/gradle/cleanup/CleanupPlugin.kt
  buildSrc/subprojects/integration-testing/integration-testing.gradle.kts
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/integrationtesting/DistributionTestingPlugin.kt
  buildSrc/subprojects/kotlin-dsl/src/main/kotlin/build-env.kt
  buildSrc/subprojects/uber-plugins/src/main/kotlin/org/gradle/gradlebuild.uberplugins/JavaProjectsPlugin.kt
  gradle/distributionTesting.gradle.kts
Labels: dogfood:kotlin-dsl, from:member

#4607 Fix inclusion of performance test debug artifacts dir in results zip
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/performance/PerformanceTestPlugin.kt
Labels: dogfood:kotlin-dsl, from:member

#4604 Stabilize memory leak avoidance test
  subprojects/soak/src/integTest/groovy/org/gradle/launcher/daemon/ClassLoaderLeakAvoidanceSoakTest.groovy
Labels: a:chore, from:member

#4548 Track implementation without trailing `.class`
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/project/taskfactory/TaskPropertyNamingIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/NestedInputIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/rules/InputPropertyValueTaskStateChanges.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/NestedBeanAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/caching/internal/tasks/DebuggingTaskOutputCachingBuildCacheKeyBuilder.java
  subprojects/core/src/main/java/org/gradle/caching/internal/tasks/DefaultTaskOutputCachingBuildCacheKeyBuilder.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/taskfactory/AnnotationProcessingTaskFactoryTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/DefaultPropertyWalkerTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/annotations/NestedBeanAnnotationHandlerTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/NestedInputKotlinImplementationTrackingIntegrationTest.groovy
  subprojects/reporting/src/test/groovy/org/gradle/api/reporting/internal/TaskReportContainerTest.groovy
Labels: from:member

#4600 Add validateTaskProperties task to buildSrc
  buildSrc/build.gradle.kts
Labels: dogfood:kotlin-dsl, from:member

#4606 Lock in plugin-resolve performance improvement
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ParallelDownloadsPerformanceTest.groovy
Labels: in:dependency-management

#4595 Simpler fix to avoid services gradle org lookups
  subprojects/distributions/binary-compatibility.gradle
Labels: from:member, in:dependency-management

#4575 Re-introduce removed lock for building buildSrc
  subprojects/core/src/main/java/org/gradle/initialization/buildsrc/BuildSourceBuilder.java
  subprojects/core/src/main/java/org/gradle/initialization/buildsrc/BuildSrcUpdateFactory.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/BuildScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/initialization/buildsrc/BuildSrcUpdateFactoryTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/BuildSourceBuilderIntegrationTest.groovy
Labels: from:member

#4614 Fix for broken publication in docs project
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/ivypublish/DefaultArtifactPublisher.java
  subprojects/docs/docs.gradle
Labels: a:bug, from:member

#4594 More test coverage for constraints, including several bug demonstrations
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/BeforeResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/DependencyConstraintsIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/RichVersionConstraintsIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/VersionConflictResolutionIntegrationTest.groovy
Labels: from:member, in:dependency-management

#4590 Apply java-library plugin for Groovy projects in buildSrc
  buildSrc/build.gradle.kts
Labels: dogfood:kotlin-dsl, from:member

#4546 Refactor code for walking bean properties
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/AbstractNestedPropertyContext.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/AbstractPropertyNode.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/BeanNode.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/BeanPropertyContext.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/DefaultPropertyMetadataStore.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/DefaultPropertyWalker.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/PropertyValidationAccess.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/PropertyValueVisitor.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/TypeMetadata.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/AbstractInputPropertyAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/AbstractOutputPropertyAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/ClasspathPropertyAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/CompileClasspathPropertyAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/DestroysPropertyAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/InputPropertyAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/LocalStatePropertyAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/NestedBeanAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/NoOpPropertyAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/bean/AbstractNestedRuntimeBeanNode.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/bean/IterableRuntimeBeanNode.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/bean/MapRuntimeBeanNode.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/bean/NestedRuntimeBeanNode.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/bean/RootRuntimeBeanNode.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/bean/RuntimeBeanNode.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/bean/RuntimeBeanNodeFactory.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/bean/package-info.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/DefaultPropertyMetadataStoreTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/PropertyValidationAccessTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/annotations/NestedBeanAnnotationHandlerTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/bean/NestedRuntimeBeanNodeTest.groovy
Labels: from:member

#4633 Deprecate Task.deleteAllActions()
  subprojects/core-api/src/main/java/org/gradle/api/Task.java
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/ExecutionTimeTaskConfigurationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/AbstractTask.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskExecutionIntegrationTest.groovy
Labels: from:member

#4631 Restructured top level Gradle dir
  build.gradle
  buildSrc/build.gradle.kts
  buildSrc/settings.gradle.kts
  buildSrc/subprojects/buildquality/src/main/kotlin/org/gradle/gradlebuild/buildquality/classycle/ClassycleExtension.kt
  config/classycle_report_resources.zip
  gradle/buildScanInit.gradle
  gradle/init-scripts/build-scan.init.gradle.kts
  gradle/init-scripts/overlapping-task-outputs-stats-init.gradle
  gradle/shared-with-buildSrc/build-cache-configuration.settings.gradle.kts
  gradle/shared-with-buildSrc/code-quality-configuration.gradle.kts
  settings.gradle.kts
  subprojects/smoke-test/smoke-test.gradle
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/cache-init-scripts/build.gradle
Labels: from:member

#4632 Moved publicApi script to buildSrc/configuration and polish
  build.gradle
  buildSrc/subprojects/cleanup/cleanup.gradle.kts
  buildSrc/subprojects/configuration/src/main/kotlin/org/gradle/gradlebuild/public-api.kt
  buildSrc/subprojects/ide/src/main/kotlin/org/gradle/gradlebuild/ide/IdePlugin.kt
  buildSrc/subprojects/profiling/profiling.gradle.kts
  buildSrc/subprojects/uber-plugins/src/main/kotlin/org/gradle/gradlebuild.uberplugins/JavaProjectsPlugin.kt
  gradle/publicApi.gradle
  subprojects/distributions/binary-compatibility.gradle
  subprojects/distributions/distributions.gradle
  subprojects/docs/docs.gradle
Labels: dogfood:kotlin-dsl, from:member

#4636 Fix generating IDE code style settings
  buildSrc/subprojects/ide/src/main/kotlin/org/gradle/gradlebuild/ide/IdePlugin.kt
Labels: dogfood:kotlin-dsl, from:member

#4433 Construct a composite 'variant name' when multiple configurations are selected
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/VariantAttributesRulesIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ComponentState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ModuleResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/VariantNameBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/IvyDependencyDescriptor.java
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/DependencyInsightReportTaskIntegrationTest.groovy
  subprojects/docs/src/samples/userguideOutput/dependencyInsightReport.out
Labels: in:dependency-management

#4653 Polish IdePlugin a little bit
  buildSrc/subprojects/ide/src/main/kotlin/org/gradle/gradlebuild/ide/IdePlugin.kt
Labels: dogfood:kotlin-dsl, from:member

#4601 Polish incremental compiler
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/MultipleOriginIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/SingleOriginIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/UnknownIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassDependentsAccumulator.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisData.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/DefaultDependentsSet.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/DependencyToAll.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/DependentsSet.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/jar/JarChangeDependentsFinder.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/jar/JarSnapshot.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/ElementUtils.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/IncrementalAnnotationProcessorType.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/IncrementalFiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/MultipleOriginFiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/MultipleOriginProcessor.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisDataSerializerTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/incremental/jar/JarSnapshotTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/processing/IncrementalFilerTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/processing/MultipleOriginFilerTest.groovy
Labels: a:chore, from:member, in:jvm-platform

#4396 DefaultConfiguration performance improvement: create sets lazily
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationPublications.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/PublishArtifactSetProvider.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationPublicationsTest.groovy
Labels: from:member, in:dependency-management

#4667 Re-enabled build scans on CI
  .teamcity/Gradle_Check/configurations/GradleBuildConfigurationDefaults.kt
  .teamcity/Gradle_Util/buildTypes/Gradle_Util_AdHocFunctionalTestLinux.xml
  .teamcity/Gradle_Util/buildTypes/Gradle_Util_AdHocFunctionalTestWindows.xml
  .teamcity/Gradle_Util_Performance/buildTypes/Gradle_Util_Performance_AdHocPerformanceScenarioLinux.xml
  .teamcity/Gradle_Util_Performance/buildTypes/Gradle_Util_Performance_PerformanceTestCoordinatorLinux.xml
Labels: dogfood:kotlin-dsl, from:member

#4616 Create lookup table for macros and macro functions
  subprojects/language-native/src/main/java/org/gradle/language/nativeplatform/internal/incremental/CollectingMacroLookup.java
  subprojects/language-native/src/main/java/org/gradle/language/nativeplatform/internal/incremental/DefaultSourceIncludesResolver.java
  subprojects/language-native/src/main/java/org/gradle/language/nativeplatform/internal/incremental/sourceparser/DefaultIncludeDirectives.java
  subprojects/language-native/src/main/java/org/gradle/language/nativeplatform/internal/incremental/sourceparser/IncludeDirectivesSerializer.java
  subprojects/language-native/src/test/groovy/org/gradle/language/nativeplatform/internal/incremental/DefaultSourceIncludesResolverTest.groovy
  subprojects/language-native/src/test/groovy/org/gradle/language/nativeplatform/internal/incremental/sourceparser/RegexBackedCSourceParserTest.groovy
  subprojects/platform-native/src/main/java/org/gradle/language/nativeplatform/internal/IncludeDirectives.java
Labels: a:bug, from:member, in:native-platform

#4602 Fix issue where Xcode config fails when OS is different
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/visualstudio/VisualStudioSingleProjectIntegrationTest.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/xcode/XcodeSingleProjectIntegrationTest.groovy
  subprojects/ide-native/src/main/java/org/gradle/ide/xcode/plugins/XcodePlugin.java
Labels: a:bug, from:member

#4669 Fix ClassLoaderCache keys equals implementation
  subprojects/core/src/main/java/org/gradle/api/internal/initialization/loadercache/DefaultClassLoaderCache.java
Labels: a:bug, from:member, in:core

#4673 Remove `OperatorWrap` checkstyle rule
  config/checkstyle/checkstyle.xml
Labels: a:chore, from:member, in:gradle-build

#4674 Clarify Javadoc for doNotCacheIf
  subprojects/core-api/src/main/java/org/gradle/api/tasks/TaskOutputs.java
Labels: from:member, in:build-cache

#4507 Checkstyle plugin rules defined in the root project
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginMultiProjectTest.groovy
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CheckstyleExtension.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CheckstylePlugin.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/checkstylePlugin.adoc
Labels: a:feature, from:member, in:checkstyle-plugin

#4661 Avoid deadlock between output event renderer and listener manager
  subprojects/core/src/integTest/groovy/org/gradle/internal/operations/logging/LoggingBuildOperationProgressIntegTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/userinput/DefaultUserInputHandler.java
  subprojects/core/src/main/java/org/gradle/internal/operations/DefaultBuildOperationExecutor.java
  subprojects/core/src/main/java/org/gradle/internal/operations/logging/LoggingBuildOperationProgressBroadcaster.java
  subprojects/core/src/main/java/org/gradle/internal/operations/trace/BuildOperationRecord.java
  subprojects/core/src/main/java/org/gradle/internal/operations/trace/BuildOperationTrace.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/BuildScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/CrossBuildSessionScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/userinput/DefaultUserInputHandlerTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/operations/logging/LoggingBuildOperationProgressBroadcasterTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/AbstractGradleExecuter.java
  subprojects/logging/src/main/java/org/gradle/internal/logging/services/LoggingServiceRegistry.java
  subprojects/logging/src/main/java/org/gradle/internal/logging/sink/OutputEventListenerManager.java
Labels: from:member, in:core

#4557 Run previous failed test first
  subprojects/docs/src/docs/release/notes.md
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/DefaultTestClassRunInfo.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/processors/RunPreviousFailedFirstTestClassProcessor.java
  subprojects/testing-base/src/main/java/org/gradle/api/tasks/testing/AbstractTestTask.java
  subprojects/testing-base/src/test/groovy/org/gradle/api/internal/tasks/testing/processors/RunPreviousFailedFirstTestClassProcessorTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junit/RerunPreviousFailedTestIntegrationTest.groovy
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/JvmTestExecutionSpec.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/detection/DefaultTestExecuter.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java
Labels: from:member, in:testing

#4693 Allow build operation listeners to log
  subprojects/base-services/src/main/java/org/gradle/internal/operations/BuildOperationListener.java
  subprojects/base-services/src/main/java/org/gradle/internal/operations/BuildOperationListenerManager.java
  subprojects/base-services/src/main/java/org/gradle/internal/operations/DefaultBuildOperationListenerManager.java
  subprojects/base-services/src/test/groovy/org/gradle/internal/operations/DefaultBuildOperationListenerManagerTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/internal/operations/logging/LoggingBuildOperationProgressIntegTest.groovy
  subprojects/core/src/main/java/org/gradle/internal/operations/DefaultBuildOperationListenerManager.java
  subprojects/core/src/main/java/org/gradle/internal/operations/notify/BuildOperationNotificationBridge.java
  subprojects/core/src/main/java/org/gradle/internal/operations/trace/BuildOperationTrace.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/CrossBuildSessionScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GlobalScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/internal/operations/notify/BuildOperationNotificationBridgeTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/BuildOperationsFixture.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/TaskOutputOriginFixture.groovy
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/GradleRunnerCaptureOutputIntegrationTest.groovy
  subprojects/tooling-api-builders/src/main/java/org/gradle/tooling/internal/provider/runner/ClientForwardingTaskOperationListener.java
  subprojects/tooling-api-builders/src/main/java/org/gradle/tooling/internal/provider/runner/ClientForwardingTestOperationListener.java
  subprojects/tooling-api-builders/src/main/java/org/gradle/tooling/internal/provider/runner/TestExecutionResultEvaluator.java
  subprojects/tooling-api-builders/src/test/groovy/org/gradle/tooling/internal/provider/runner/TestExecutionResultEvaluatorTest.groovy
Labels: from:member, in:core

#4698 Rebaseline performance tests for large java project
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingJavaPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/RichConsolePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaABIChangePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaCleanAssemblePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaDependencyReportPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIDEModelPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaNonABIChangePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaTasksPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaTestChangePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaUpToDatePerformanceTest.groovy
Labels: from:member

#4630 Deleted obsolete build script test-with-unknown-os
  buildSrc/subprojects/uber-plugins/src/main/kotlin/org/gradle/gradlebuild.uberplugins/JavaProjectsPlugin.kt
  gradle/testWithUnknownOS.gradle
Labels: from:member

#4680 Fix annotation-processors cache
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/AnnotationProcessorDeclarationSerializer.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/AnnotationProcessorDetector.java
Labels: a:bug, from:contributor, in:jvm-platform

#4714 Declare optional `DefaultFileOperations` arguments as `@Nullable`
  subprojects/core/src/main/java/org/gradle/api/internal/artifacts/publish/AbstractPublishArtifact.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/DefaultFileOperations.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/FileOperations.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/collections/DefaultConfigurableFileCollection.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/collections/DefaultConfigurableFileTree.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskDependency.java
Labels: from:member, in:core

#4707 Add a couple missing links to the docs navigation
  subprojects/docs/src/docs/stylesheets/userGuideHtml.xsl
Labels: from:member, in:docs

#4597 Improves --tests pattern matching
  subprojects/docs/src/docs/userguide/javaPlugin.adoc
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcher.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/processors/PatternMatchTestClassProcessor.java
  subprojects/testing-base/src/main/java/org/gradle/api/tasks/testing/TestFilter.java
  subprojects/testing-base/src/test/groovy/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcherTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/fixture/AbstractTestFilteringIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junit/JUnitFilteringIntegrationTest.groovy
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/detection/DefaultTestExecuter.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java
  subprojects/testing-jvm/src/test/groovy/org/gradle/api/internal/tasks/testing/detection/DefaultTestClassScannerTest.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/TestLauncherSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r26/TestLauncherCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r27/TestLauncherCrossVersionSpec.groovy
Labels: a:feature, from:member, in:testing

#4696 Upgrade asm to 6.1
  gradle/dependencies.gradle
  subprojects/distributions/src/integTest/groovy/org/gradle/DistributionIntegrationSpec.groovy
Labels: from:contributor

#4671 Make multiple-origin processors incremental
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/MultipleOriginIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/SingleOriginIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/analyzer/CompilationResultAnalyzer.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassDependentsAccumulator.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisData.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/processing/AnnotationProcessingResult.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/DelegatingProcessor.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/IncrementalAnnotationProcessorType.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/IncrementalFiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/IncrementalProcessor.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/MultipleOriginFiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/MultipleOriginProcessor.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/SingleOriginFiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/SingleOriginProcessor.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisDataSerializerTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/incremental/jar/JarSnapshotTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/processing/IncrementalFilerTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/processing/MultipleOriginFilerTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/processing/MultipleOriginProcessorTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/processing/SingleOriginFilerTest.groovy
Labels: a:feature, from:member, in:jvm-platform

#4686 Let ModelType represent types of enums constants with class body
  subprojects/model-core/src/main/java/org/gradle/model/internal/type/ClassTypeWrapper.java
  subprojects/model-core/src/test/groovy/org/gradle/model/internal/core/ModelTypeTest.groovy
Labels: a:bug, from:member, in:core

#4721 Follow up on review comments on #4682
  subprojects/core-api/src/main/java/org/gradle/api/file/CopySpec.java
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/CopySpecWrapper.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DelegatingCopySpecInternal.java
  subprojects/core/src/main/java/org/gradle/api/tasks/AbstractCopyTask.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/copy/DefaultCopySpecTest.groovy
Labels: from:member, in:core

#4724 Upgrade Kotlin DSL {0.16.0 => 0.16.1}
  buildSrc/build.gradle.kts
  buildSrc/subprojects/configuration/src/main/kotlin/org/gradle/gradlebuild/build-environment.kt
  buildSrc/subprojects/kotlin-dsl/kotlin-dsl.gradle.kts
  subprojects/performance/templates.gradle
Labels: dogfood:kotlin-dsl, from:member

#4381 Change lib dir to exclude any files both in deploy and earlib configu…
  subprojects/ear/src/main/java/org/gradle/plugins/ear/EarPlugin.java
  subprojects/ear/src/test/groovy/org/gradle/plugins/ear/EarPluginTest.groovy
Labels: from:contributor, waiting-for:gradle-team

#4734 Remove remaining references to org.gradle.integtest.unknownos
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/samples/UserGuideSamplesRunner.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/GradleContextualExecuter.java
Labels: dogfood:kotlin-dsl, from:member

#4726 Let ModelType represent types of enums constants with class body
  subprojects/model-core/src/main/java/org/gradle/model/internal/type/ClassTypeWrapper.java
  subprojects/model-core/src/test/groovy/org/gradle/model/internal/core/ModelTypeTest.groovy
Labels: a:bug, from:member, in:core

#4715 Moved dependencies metadata rules into buildSrc
  build.gradle
  buildSrc/subprojects/configuration/configuration.gradle.kts
  buildSrc/subprojects/configuration/src/main/kotlin/org/gradle/gradlebuild/dependencies/DependenciesMetadataRulesPlugin.kt
Labels: dogfood:kotlin-dsl, from:member

#4725 De-incubate Google repository
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/RepositoryHandler.java
  subprojects/docs/src/docs/release/notes.md
Labels: a:chore, from:member, in:dependency-management

#4700 Document incremental annotation processing
  buildSrc/subprojects/build/src/main/groovy/org/gradle/build/docs/ExtractSnippetsTask.groovy
  subprojects/docs/src/docs/userguide/javaPlugin.adoc
  subprojects/docs/src/samples/java/incrementalAnnotationProcessing/library/build.gradle
  subprojects/docs/src/samples/java/incrementalAnnotationProcessing/library/src/main/java/Entity.java
  subprojects/docs/src/samples/java/incrementalAnnotationProcessing/library/src/main/java/Service.java
  subprojects/docs/src/samples/java/incrementalAnnotationProcessing/processor/build.gradle
  subprojects/docs/src/samples/java/incrementalAnnotationProcessing/processor/src/main/java/EntityProcessor.java
  subprojects/docs/src/samples/java/incrementalAnnotationProcessing/processor/src/main/java/ServiceRegistryProcessor.java
  subprojects/docs/src/samples/java/incrementalAnnotationProcessing/processor/src/main/resources/META-INF/gradle/incremental.annotation.processors
  subprojects/docs/src/samples/java/incrementalAnnotationProcessing/processor/src/main/resources/META-INF/services/javax.annotation.processing.Processor
  subprojects/docs/src/samples/java/incrementalAnnotationProcessing/settings.gradle
  subprojects/docs/src/samples/java/incrementalAnnotationProcessing/user/build.gradle
  subprojects/docs/src/samples/java/incrementalAnnotationProcessing/user/src/main/java/Entity1.java
  subprojects/docs/src/samples/java/incrementalAnnotationProcessing/user/src/main/java/Entity2.java
  subprojects/docs/src/samples/java/incrementalAnnotationProcessing/user/src/main/java/Main.java
  subprojects/docs/src/samples/java/incrementalAnnotationProcessing/user/src/main/java/Service1.java
  subprojects/docs/src/samples/java/incrementalAnnotationProcessing/user/src/main/java/Service2.java
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/samples/SamplesJavaIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/AggregatingIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/IsolatingIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/IncrementalAnnotationProcessingCompileTask.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/AggregatingFiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/AggregatingProcessor.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/IncrementalAnnotationProcessorType.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/IsolatingFiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/IsolatingProcessor.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/processing/AggregatingFilerTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/processing/AggregatingProcessorTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/processing/AnnotationProcessorDetectorTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/processing/IsolatingFilerTest.groovy
  subprojects/language-java/src/testFixtures/groovy/org/gradle/language/fixtures/HelperProcessorFixture.groovy
  subprojects/language-java/src/testFixtures/groovy/org/gradle/language/fixtures/ServiceRegistryProcessorFixture.groovy
Labels: a:chore, from:member, in:jvm-platform

#4713 Attach a "plain console" as a part of logging initialization
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/InProcessGradleExecuter.java
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/DaemonLifecycleSpec.groovy
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/taskgrouping/PlainConsoleGroupedTaskFunctionalTest.groovy
  subprojects/logging/src/main/java/org/gradle/internal/logging/LoggingOutputInternal.java
  subprojects/logging/src/main/java/org/gradle/internal/logging/console/ThrottlingOutputEventListener.java
  subprojects/logging/src/main/java/org/gradle/internal/logging/events/FlushOutputEvent.java
  subprojects/logging/src/main/java/org/gradle/internal/logging/services/DefaultLoggingManager.java
  subprojects/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java
  subprojects/logging/src/main/java/org/gradle/internal/logging/sink/LogEventDispatcher.java
  subprojects/logging/src/main/java/org/gradle/internal/logging/sink/OutputEventRenderer.java
  subprojects/logging/src/test/groovy/org/gradle/internal/logging/console/ConsoleFunctionalTest.groovy
  subprojects/logging/src/test/groovy/org/gradle/internal/logging/sink/LogEventDispatcherTest.groovy
  subprojects/logging/src/test/groovy/org/gradle/internal/logging/sink/OutputEventRendererTest.groovy
  subprojects/platform-play/src/integTest/groovy/org/gradle/play/integtest/continuous/PlayMultiProjectReloadIntegrationTest.groovy
  subprojects/platform-play/src/testFixtures/groovy/org/gradle/play/integtest/fixtures/AbstractMultiVersionPlayReloadIntegrationTest.groovy
  subprojects/testing-base/src/integTest/groovy/org/gradle/testing/SecurityManagerIntegrationTest.groovy
Labels: a:feature, from:member

#4723 Make it possible to fail on capability version conflict
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/capabilities/CapabilitiesUseCasesIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/DefaultArtifactDependencyResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/DependencyGraphBuilder.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/DependencyGraphBuilderTest.groovy
Labels: from:member, in:dependency-management

#4744 Fix link to building cpp libraries
  subprojects/docs/src/docs/stylesheets/userGuideHtml.xsl
Labels: from:member, in:docs

#4705 Embolden help.gradle.org URL in build failure suggestions
  subprojects/core/src/main/java/org/gradle/internal/buildevents/BuildExceptionReporter.java
Labels: from:member, in:core

#4751 Use own cache directory for testkit sample
  subprojects/docs/src/docs/userguide/testKit.adoc
  subprojects/docs/src/samples/testKit/gradleRunner/testKitFunctionalTestSpockBuildCache/src/test/groovy/org/gradle/sample/BuildLogicFunctionalTest.groovy
Labels: from:member, in:build-cache, in:docs

#4425 Add displayName and classDisplayName to TestDescriptor
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/TestNGExecutionResult.groovy
  subprojects/internal-testing/src/main/groovy/org/gradle/integtests/fixtures/DefaultTestExecutionResult.groovy
  subprojects/internal-testing/src/main/groovy/org/gradle/integtests/fixtures/HtmlTestExecutionResult.groovy
  subprojects/internal-testing/src/main/groovy/org/gradle/integtests/fixtures/JUnitTestClassExecutionResult.groovy
  subprojects/internal-testing/src/main/groovy/org/gradle/integtests/fixtures/TestClassExecutionResult.java
  subprojects/plugins/src/test/groovy/org/gradle/api/tasks/testing/TestTaskSpec.groovy
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/AbstractTestDescriptor.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/DecoratingTestDescriptor.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/DefaultTestClassDescriptor.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/DefaultTestDescriptor.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/TestDescriptorInternal.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/junit/result/TestClassResult.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/junit/result/TestMethodResult.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/junit/result/TestReportDataCollector.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/junit/result/TestResultSerializer.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/report/AllTestResults.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/report/ClassPageRenderer.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/report/ClassTestResults.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/report/DefaultTestReport.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/report/PackagePageRenderer.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/report/PackageTestResults.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/report/PageRenderer.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/report/TestResult.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/results/UnknownTestDescriptor.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java
  subprojects/testing-base/src/test/groovy/org/gradle/api/internal/tasks/testing/logging/SimpleTestDescriptor.groovy
  subprojects/testing-base/src/test/groovy/org/gradle/api/internal/tasks/testing/report/ClassTestResultsTest.groovy
  subprojects/testing-junit-platform/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestExecutionListener.java
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformSampleIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformUserGuideIntegrationTest.groovy
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/junit/GenericJUnitTestEventAdapter.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/junit/TestClassExecutionEventGenerator.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/junit/TestClassExecutionListener.java
Labels: a:bug, from:member, in:testing

#4758 Don't log excessively and without task attribution when maven publishing
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishLoggingIntegTest.groovy
  subprojects/maven/src/main/java/org/gradle/api/publication/maven/internal/action/AbstractMavenPublishAction.java
  subprojects/maven/src/main/java/org/gradle/api/publication/maven/internal/action/LoggingMavenTransferListener.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publisher/AbstractMavenPublisher.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publisher/MavenPublisher.java
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r40/BuildProgressCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r47/BuildProgressCrossVersionSpec.groovy
  subprojects/tooling-api/src/testFixtures/groovy/org/gradle/integtests/tooling/fixture/ProgressEvents.groovy
Labels: from:member, in:core

#4746 Remove known issues from build cache documentation
  subprojects/docs/src/docs/userguide/buildCache.adoc
Labels: from:member

#4690 Follow up on review items raised
  subprojects/core-api/src/main/java/org/gradle/api/component/BuildableComponent.java
  subprojects/core-api/src/main/java/org/gradle/api/component/PublishableComponent.java
  subprojects/docs/src/docs/userguide/gradleWrapper.adoc
  subprojects/language-native/src/integTest/groovy/org/gradle/language/cpp/CppApplicationIntegrationTest.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/language/cpp/CppApplicationPublishingIntegrationTest.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/language/cpp/CppLibraryPublishingIntegrationTest.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/language/cpp/CppLibraryWithBothLinkagePublishingIntegrationTest.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/language/cpp/CppLibraryWithStaticLinkagePublishingIntegrationTest.groovy
  subprojects/language-native/src/main/java/org/gradle/language/cpp/CppBinary.java
  subprojects/language-native/src/main/java/org/gradle/language/cpp/CppComponent.java
  subprojects/language-native/src/main/java/org/gradle/language/cpp/CppExecutable.java
  subprojects/language-native/src/main/java/org/gradle/language/cpp/CppSharedLibrary.java
  subprojects/language-native/src/main/java/org/gradle/language/cpp/CppStaticLibrary.java
  subprojects/language-native/src/main/java/org/gradle/language/cpp/plugins/CppApplicationPlugin.java
  subprojects/language-native/src/main/java/org/gradle/language/cpp/plugins/CppLibraryPlugin.java
  subprojects/language-native/src/main/java/org/gradle/language/plugins/NativeBasePlugin.java
  subprojects/language-native/src/main/java/org/gradle/language/swift/plugins/SwiftLibraryPlugin.java
  subprojects/language-native/src/test/groovy/org/gradle/language/plugins/NativeBasePluginTest.groovy
  subprojects/language-native/src/testFixtures/groovy/org/gradle/language/AbstractNativeLanguageComponentIntegrationTest.groovy
  subprojects/language-native/src/testFixtures/groovy/org/gradle/language/cpp/AbstractCppComponentIntegrationTest.groovy
  subprojects/platform-native/src/testFixtures/groovy/org/gradle/nativeplatform/fixtures/AbstractInstalledToolChainIntegrationSpec.groovy
  subprojects/testing-native/src/main/java/org/gradle/nativeplatform/test/cpp/plugins/CppUnitTestPlugin.java
Labels: from:member

#4752 Ensure that all children TestState are completed()
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/TestNGExecutionResult.groovy
  subprojects/internal-testing/src/main/groovy/org/gradle/integtests/fixtures/DefaultTestExecutionResult.groovy
  subprojects/internal-testing/src/main/groovy/org/gradle/integtests/fixtures/HtmlTestExecutionResult.groovy
  subprojects/internal-testing/src/main/groovy/org/gradle/integtests/fixtures/JUnitTestClassExecutionResult.groovy
  subprojects/internal-testing/src/main/groovy/org/gradle/integtests/fixtures/TestClassExecutionResult.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/results/StateTrackingTestResultProcessor.java
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/fixture/AbstractJvmFailFastIntegrationSpec.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGFailFastIntegrationTest.groovy
Labels: a:bug, from:member, in:testing

#4665 Properly support Providers for inputs and outputs
  subprojects/core-api/src/main/java/org/gradle/api/provider/Provider.java
  subprojects/core-api/src/main/java/org/gradle/api/tasks/Nested.java
  subprojects/core/src/integTest/groovy/org/gradle/api/file/FileProvidersIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/NestedInputIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/provider/package-info.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/PropertyValidationAccess.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/NestedBeanAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/bean/AbstractNestedRuntimeBeanNode.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/DefaultPropertyWalkerTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/PropertyValidationAccessTest.groovy
  subprojects/docs/src/docs/userguide/moreAboutTasks.adoc
Labels: from:member

#4768 Upgrade Gradle Kotlin DSL {0.16.1 => 0.16.2}
  buildSrc/subprojects/configuration/src/main/kotlin/org/gradle/gradlebuild/build-environment.kt
  buildSrc/subprojects/kotlin-dsl/kotlin-dsl.gradle.kts
Labels: dogfood:kotlin-dsl, from:member

#4770 Don't retry failed build cache HTTP uploads
  subprojects/build-cache-http/src/integTest/groovy/org/gradle/caching/http/internal/HttpBuildCacheServiceErrorHandlingIntegrationTest.groovy
  subprojects/build-cache-http/src/main/java/org/gradle/caching/http/internal/HttpBuildCacheService.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/DropConnectionFilter.groovy
Labels: from:member, in:build-cache

#4776 Do not add module metadata file to publishable files if deactivated
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publication/DefaultIvyPublication.java
  subprojects/ivy/src/test/groovy/org/gradle/api/publish/ivy/internal/publication/DefaultIvyPublicationTest.groovy
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/DefaultMavenPublication.java
  subprojects/maven/src/test/groovy/org/gradle/api/publish/maven/internal/publication/DefaultMavenPublicationTest.groovy
Labels: from:member, in:dependency-management

#4754 Improve message for annotation processors on the compile classpath
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/AnnotationProcessorPathFactory.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/CompileOptions.java
  subprojects/language-java/src/test/groovy/org/gradle/api/tasks/compile/CompileOptionsTest.groovy
Labels: a:bug, from:member, in:jvm-platform

#4775 Ignore scopes in <dependencyManagement> if it is used as BOM
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/GradlePomModuleDescriptorBuilder.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/GradlePomModuleDescriptorParserBomTest.groovy
Labels: from:member, in:dependency-management

#4498 Convert dependency management related subprojects to kotlin-dsl
  gradle/dependencies.gradle
  settings.gradle.kts
  subprojects/base-services/base-services.gradle.kts
  subprojects/dependency-management/dependency-management.gradle
  subprojects/dependency-management/dependency-management.gradle.kts
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/xcode/fixtures/XcodebuildExecutor.java
  subprojects/ivy/ivy.gradle
  subprojects/ivy/ivy.gradle.kts
  subprojects/language-groovy/language-groovy.gradle
  subprojects/language-java/language-java.gradle
  subprojects/language-native/language-native.gradle
  subprojects/language-native/src/test/groovy/org/gradle/language/nativeplatform/internal/incremental/sourceparser/RegexBackedCSourceParserTest.groovy
  subprojects/maven/maven.gradle
  subprojects/maven/maven.gradle.kts
  subprojects/platform-base/platform-base.gradle
  subprojects/platform-jvm/platform-jvm.gradle
  subprojects/platform-native/platform-native.gradle
  subprojects/publish/publish.gradle
  subprojects/testing-base/src/main/java/org/gradle/api/tasks/testing/AbstractTestTask.java
  subprojects/testing-base/testing-base.gradle
  subprojects/testing-junit-platform/testing-junit-platform.gradle
  subprojects/testing-jvm/testing-jvm.gradle
Labels: dogfood:kotlin-dsl, from:member, in:dependency-management, in:gradle-build

#4763 Convert tooling-api to kotlin dsl
  settings.gradle.kts
  subprojects/tooling-api/tooling-api.gradle
  subprojects/tooling-api/tooling-api.gradle.kts
Labels: dogfood:kotlin-dsl, from:member

#4747 Make aggregating annotation processors faster
  subprojects/docs/src/docs/userguide/javaPlugin.adoc
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/samples/SamplesJavaIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/AbstractIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/AggregatingIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/DefaultJavaCompileSpec.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompileSpec.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JdkJavaCompiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/ClassChangeProcessor.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/IncrementalCompilationInitializer.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/JavaChangeProcessor.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/RecompilationSpecProvider.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/SelectiveCompiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassDependentsAccumulator.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisData.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/jar/JarChangeProcessor.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/jar/PreviousCompilation.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/processing/AnnotationProcessingResult.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/RecompilationSpec.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/AggregatingFiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/AggregatingProcessor.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/incremental/ClassChangeProcessorTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/incremental/IncrementalCompilationInitializerTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisDataSerializerTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/processing/AggregatingFilerTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/processing/AggregatingProcessorTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/processing/IsolatingFilerTest.groovy
Labels: a:feature, from:member, in:jvm-platform

#4766 Render welcome message + release features upon first invocation
  subprojects/docs/docs.gradle
  subprojects/docs/src/docs/release/release-features.txt
  subprojects/launcher/launcher.gradle
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/cli/NotificationsIntegrationTest.groovy
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/CommandLineActionFactory.java
  subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperLoggingIntegrationTest.groovy
Labels: a:feature, from:member, in:core

#4778 Clean up code around TaskPropertyUtils
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskPropertyUtils.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/SkipCachedTaskExecuter.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/PropertyWalker.java
Labels: from:member, in:build-cache

#4774 Exclude anonymous class in JUnit Platform
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/gradlebuild/unittestandcompile/UnitTestAndCompilePlugin.kt
  subprojects/testing-junit-platform/src/test/groovy/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestClassProcessorTest.groovy
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/detection/DefaultTestClassScanner.java
  subprojects/testing-jvm/src/test/groovy/org/gradle/api/internal/tasks/testing/detection/DefaultTestClassScannerTest.groovy
Labels: a:bug, from:member

#4759 Make JavaVersion support JDK 11 and JEP-223
  subprojects/base-services/src/main/java/org/gradle/api/JavaVersion.java
  subprojects/base-services/src/test/groovy/org/gradle/api/JavaVersionSpec.groovy
  subprojects/distributions/src/changes/accepted-public-api-changes.json
  subprojects/launcher/src/test/groovy/org/gradle/launcher/cli/BuildActionsFactoryTest.groovy
Labels: a:chore, from:member

#4790 Add missing @Nullable annotation on Project.setProperty() value parameter
  subprojects/core-api/src/main/java/org/gradle/api/Project.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/DefaultProjectTest.groovy
Labels: a:chore, from:member, in:core

#4782 Fix #4608
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/RichVersionConstraintsIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/VersionRangeResolveIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultResolvedVersionConstraint.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/DynamicVersionResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/RepositoryChainDependencyToComponentIdResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/projectmodule/ProjectDependencyResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/ComponentResolutionState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ComponentState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/SelectorState.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/result/BuildableComponentIdResolveResult.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/result/ComponentIdResolveResult.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/result/DefaultBuildableComponentIdResolveResult.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/projectmodule/ProjectDependencyResolverTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/resolve/result/DefaultBuildableComponentIdResolveResultTest.groovy
Labels: in:dependency-management

#4792 Create marker file to prevent rendering of initial welcome message in integration test
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/m8/ToolingApiLoggingCrossVersionSpec.groovy
Labels: a:chore, from:member

#4691 Wire operatingSystem into Swift binary types
  subprojects/language-native/src/main/java/org/gradle/language/cpp/internal/DefaultCppSharedLibrary.java
  subprojects/language-native/src/main/java/org/gradle/language/cpp/internal/DefaultCppStaticLibrary.java
  subprojects/language-native/src/main/java/org/gradle/language/cpp/plugins/CppApplicationPlugin.java
  subprojects/language-native/src/main/java/org/gradle/language/nativeplatform/internal/BuildType.java
  subprojects/language-native/src/main/java/org/gradle/language/swift/internal/DefaultSwiftApplication.java
  subprojects/language-native/src/main/java/org/gradle/language/swift/internal/DefaultSwiftBinary.java
  subprojects/language-native/src/main/java/org/gradle/language/swift/internal/DefaultSwiftExecutable.java
  subprojects/language-native/src/main/java/org/gradle/language/swift/internal/DefaultSwiftSharedLibrary.java
  subprojects/language-native/src/main/java/org/gradle/language/swift/internal/DefaultSwiftStaticLibrary.java
  subprojects/language-native/src/main/java/org/gradle/language/swift/plugins/SwiftApplicationPlugin.java
  subprojects/language-native/src/test/groovy/org/gradle/language/swift/internal/DefaultSwiftApplicationTest.groovy
  subprojects/language-native/src/test/groovy/org/gradle/language/swift/internal/DefaultSwiftBinaryTest.groovy
  subprojects/language-native/src/test/groovy/org/gradle/language/swift/internal/DefaultSwiftLibraryTest.groovy
  subprojects/language-native/src/test/groovy/org/gradle/language/swift/plugins/SwiftBasePluginTest.groovy
  subprojects/testing-native/src/main/java/org/gradle/nativeplatform/test/xctest/internal/DefaultSwiftXCTestBinary.java
  subprojects/testing-native/src/main/java/org/gradle/nativeplatform/test/xctest/internal/DefaultSwiftXCTestBundle.java
  subprojects/testing-native/src/main/java/org/gradle/nativeplatform/test/xctest/internal/DefaultSwiftXCTestExecutable.java
  subprojects/testing-native/src/main/java/org/gradle/nativeplatform/test/xctest/internal/DefaultSwiftXCTestSuite.java
  subprojects/testing-native/src/main/java/org/gradle/nativeplatform/test/xctest/plugins/XCTestConventionPlugin.java
  subprojects/testing-native/src/test/groovy/org/gradle/nativeplatform/test/xctest/internal/DefaultSwiftXCTestSuiteTest.groovy
Labels: from:member

#4791 Remove the verbose flag by default for `swiftc`
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/swift/SwiftCompiler.java
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/swift/SwiftLinker.java
  subprojects/platform-native/src/test/groovy/org/gradle/nativeplatform/toolchain/internal/swift/SwiftLinkerTest.groovy
Labels: a:chore, from:member, in:native-platform

#3901 Always report Checkstyle violations-summary from xml report
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginVersionIntegrationTest.groovy
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/CheckstyleInvoker.groovy
Labels: from:contributor, in:checkstyle-plugin, waiting-for:gradle-team

#4796 By default don't render the welcome message to avoid test flakiness
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/AbstractGradleExecuter.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/GradleExecuter.java
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/cli/NotificationsIntegrationTest.groovy
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/CommandLineActionFactory.java
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/m8/ToolingApiLoggingCrossVersionSpec.groovy
  subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperLoggingIntegrationTest.groovy
Labels: a:chore, from:member

#4808 Fix NPE in capabilities conflict resolution
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/capabilities/CapabilitiesRulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/capabilities/CapabilitiesUseCasesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/capabilities/PublishedCapabilitiesIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ComponentState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/conflicts/DefaultCapabilitiesConflictHandler.java
Labels: a:bug, from:member, in:dependency-management

#4809 Allow creation of Task with constructor arguments
  subprojects/core-api/src/main/java/org/gradle/api/Task.java
  subprojects/core-api/src/main/java/org/gradle/api/tasks/TaskContainer.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/taskfactory/AnnotationProcessingTaskFactory.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/taskfactory/ITaskFactory.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/taskfactory/TaskFactory.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskContainer.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/AbstractTaskSpec.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/taskfactory/AnnotationProcessingTaskFactoryTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/taskfactory/TaskFactoryTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/DefaultTaskContainerTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/api/tasks/AbstractSpockTaskTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/api/tasks/AbstractTaskTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/util/TestUtil.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/GradleKotlinDslIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskDefinitionIntegrationSpec.groovy
Labels: a:feature, from:member, in:core

#4797 Make ClassMethodNameStackTraceSpec support anonymous class matching
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/logging/ClassMethodNameStackTraceSpec.java
  subprojects/testing-base/src/test/groovy/org/gradle/api/internal/tasks/testing/logging/ClassMethodNameStackTraceSpecTest.groovy
  subprojects/testing-base/src/test/groovy/org/gradle/api/internal/tasks/testing/logging/FullExceptionFormatterTest.groovy
Labels: a:feature, from:member

#4794 Fix 4457. Don't set parallel mode and threadCount for testng if not explicitly defined
  subprojects/plugins/src/test/groovy/org/gradle/api/tasks/testing/testng/TestNGOptionsTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/fixture/TestNGCoverage.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGParallelSuiteIntegrationTest.groovy
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGTestClassProcessor.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/testng/TestNGOptions.java
Labels: a:bug, from:contributor

#4807 Use JaCoCo 0.8.1 by default
  subprojects/docs/src/docs/dsl/org.gradle.testing.jacoco.plugins.JacocoPluginExtension.xml
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/samples/testing/jacoco/quickstart/build.gradle
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoPlugin.java
  subprojects/jacoco/src/test/groovy/org/gradle/internal/jacoco/JacocoAgentJarTest.groovy
Labels: a:chore, from:contributor

#4803 DefaultClassLoaderScope exposes its ID in exception messages
  subprojects/core/src/main/java/org/gradle/api/internal/initialization/DefaultClassLoaderScope.java
Labels: a:chore, from:member, in:core

#4710 Lint Kotlin code in buildSrc
  buildSrc/build.gradle.kts
  buildSrc/subprojects/buildquality/src/main/kotlin/org/gradle/gradlebuild/buildquality/AddVerifyProductionEnvironmentTaskPlugin.kt
  buildSrc/subprojects/buildquality/src/main/kotlin/org/gradle/gradlebuild/buildquality/CiReportingPlugin.kt
  buildSrc/subprojects/buildquality/src/main/kotlin/org/gradle/gradlebuild/buildquality/DependencyVulnerabilitiesPlugin.kt
  buildSrc/subprojects/buildquality/src/main/kotlin/org/gradle/gradlebuild/buildquality/NoResolutionAtConfigurationTimePlugin.kt
  buildSrc/subprojects/buildquality/src/main/kotlin/org/gradle/gradlebuild/buildquality/TaskPropertyValidationPlugin.kt
  buildSrc/subprojects/buildquality/src/main/kotlin/org/gradle/gradlebuild/buildquality/classycle/Classycle.kt
  buildSrc/subprojects/buildquality/src/main/kotlin/org/gradle/gradlebuild/buildquality/classycle/ClassycleExtension.kt
  buildSrc/subprojects/buildquality/src/main/kotlin/org/gradle/gradlebuild/buildquality/testfiles/TestFilesCleanUpPlugin.kt
  buildSrc/subprojects/cleanup/src/main/kotlin/org/gradle/gradlebuild/testing/integrationtests/cleanup/CleanUpCaches.kt
  buildSrc/subprojects/cleanup/src/main/kotlin/org/gradle/gradlebuild/testing/integrationtests/cleanup/CleanUpDaemons.kt
  buildSrc/subprojects/cleanup/src/main/kotlin/org/gradle/gradlebuild/testing/integrationtests/cleanup/Cleanup.kt
  buildSrc/subprojects/cleanup/src/main/kotlin/org/gradle/gradlebuild/testing/integrationtests/cleanup/CleanupPlugin.kt
  buildSrc/subprojects/cleanup/src/main/kotlin/org/gradle/gradlebuild/testing/integrationtests/cleanup/KillLeakingJavaProcesses.kt
  buildSrc/subprojects/cleanup/src/main/kotlin/org/gradle/gradlebuild/testing/integrationtests/cleanup/Process.kt
  buildSrc/subprojects/cleanup/src/main/kotlin/org/gradle/testing/LeakingProcessKillPattern.kt
  buildSrc/subprojects/configuration/src/main/kotlin/build-extensions.kt
  buildSrc/subprojects/configuration/src/main/kotlin/org/gradle/gradlebuild/build-environment.kt
  buildSrc/subprojects/configuration/src/main/kotlin/org/gradle/gradlebuild/dependencies/DependenciesMetadataRulesPlugin.kt
  buildSrc/subprojects/configuration/src/main/kotlin/org/gradle/gradlebuild/java/AvailableJavaInstallations.kt
  buildSrc/subprojects/configuration/src/main/kotlin/org/gradle/gradlebuild/java/AvailableJavaInstallationsPlugin.kt
  buildSrc/subprojects/configuration/src/main/kotlin/org/gradle/gradlebuild/project-groups.kt
  buildSrc/subprojects/docs/src/main/kotlin/org/gradle/gradlebuild/docs/PegDown.kt
  buildSrc/subprojects/ide/src/main/kotlin/org/gradle/gradlebuild/ide/IdeExtension.kt
  buildSrc/subprojects/ide/src/main/kotlin/org/gradle/gradlebuild/ide/IdePlugin.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/fixtures/TestFixturesExtension.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/CrossVersionTestsPlugin.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/DistributionTestingPlugin.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/IntegrationTest.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/IntegrationTestsPlugin.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/SoakTest.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/excluded-tests.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/shared-configuration.kt
  buildSrc/subprojects/integration-testing/src/test/kotlin/org/gradle/gradlebuild/test/integrationtests/ExcludedTestsTest.kt
  buildSrc/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/kotlin-dsl-upstream.kt
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/MinifyPlugin.kt
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/MinifyTransform.kt
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/ShadedJarCreator.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/build/ClasspathManifest.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/gradlebuild/tools/ResumeBuildPlugin.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/gradlebuild/unittestandcompile/UnitTestAndCompilePlugin.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/modules/ClasspathManifestPatcher.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/modules/JarPatcher.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/buildtypes/BuildTypesPlugin.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/jsoup/JsoupCopyExtension.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/jsoup/JsoupFilterReader.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/performance/PerformanceTestPlugin.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/publish/GeneratePom.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/publish/PublishPublicLibrariesPlugin.kt
  buildSrc/subprojects/plugins/src/main/kotlin/plugins-extensions.kt
  buildSrc/subprojects/plugins/src/test/kotlin/org/gradle/plugins/performance/PerformanceTestPluginTest.kt
  buildSrc/subprojects/plugins/src/test/kotlin/org/gradle/plugins/publish/ArtifactPatternTest.kt
  buildSrc/subprojects/profiling/src/main/kotlin/org/gradle/gradlebuild/profiling/JmhPlugin.kt
  buildSrc/subprojects/profiling/src/main/kotlin/org/gradle/gradlebuild/profiling/buildscan/BuildScanPlugin.kt
  buildSrc/subprojects/profiling/src/main/kotlin/org/gradle/gradlebuild/profiling/buildscan/Visitor.kt
  buildSrc/subprojects/versioning/src/main/kotlin/org/gradle/gradlebuild/versioning/UpdateVersionsPlugin.kt
  buildSrc/subprojects/versioning/src/main/kotlin/org/gradle/gradlebuild/versioning/WrapperPlugin.kt
  buildSrc/subprojects/versioning/src/main/kotlin/versioning-extensions.kt
Labels: a:chore, dogfood:kotlin-dsl, from:member, in:gradle-build

#4821 Split out classes from ShadedJarCreator.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/DistributionTestingPlugin.kt
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/ClassAnalysisException.kt
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/ClassGraph.kt
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/MinifyPlugin.kt
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/MinifyTransform.kt
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/ShadedJar.kt
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/ShadedJarCreator.kt
Labels: from:member

#4822 Replace honest profiler with JFR
  buildSrc/subprojects/performance/src/main/groovy/org/gradle/testing/PerformanceTest.java
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/performance/PerformanceTestPlugin.kt
  subprojects/internal-performance-testing/internal-performance-testing.gradle.kts
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/AbstractToolingApiCrossVersionPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/AbstractGradleBuildPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/BuildExperimentRunner.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/CrossVersionPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/FlameGraphSanitizer.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleBuildExperimentSpec.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleInvocationSpec.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/HonestProfilerCollector.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/JfrProfiler.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/Profiler.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/YourKitProfiler.groovy
  subprojects/internal-performance-testing/src/main/resources/org/gradle/reporting/flamegraph.pl
  subprojects/internal-performance-testing/src/test/groovy/org/gradle/performance/fixture/CrossVersionPerformanceTestRunnerTest.groovy
  subprojects/internal-performance-testing/src/test/groovy/org/gradle/performance/fixture/YourKitProfilerTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/RealWorldNativePluginPerformanceTest.groovy
Labels: a:chore

#4824 Avoid `containsKey` call in the happy path
  subprojects/core/src/main/java/org/gradle/api/internal/plugins/DefaultExtraPropertiesExtension.java
Labels: from:member

#4825 Fix buildSrc import into IDEA
  buildSrc/build.gradle.kts
  buildSrc/subprojects/ide/src/main/kotlin/org/gradle/gradlebuild/ide/IdePlugin.kt
Labels: dogfood:kotlin-dsl, from:member

#4829 Update nightly wrapper
  buildSrc/gradle/wrapper/gradle-wrapper.jar
  buildSrc/gradle/wrapper/gradle-wrapper.properties
  buildSrc/gradlew
  buildSrc/gradlew.bat
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore, from:member

#4812 Task constructor argument test cleanup
  subprojects/core/src/test/groovy/org/gradle/api/internal/DependencyInjectingInstantiatorTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/DefaultTaskContainerTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/GradleKotlinDslIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskDefinitionIntegrationSpec.groovy
Labels: from:member, in:core

#4779 Removed extraneous 'chmod' (#4627)
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/ApplicationPluginIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/ApplicationPlugin.java
Labels: a:chore, from:contributor

#4804 Deprecate FileCollection.asType()
  subprojects/core-api/src/main/java/org/gradle/api/file/FileCollection.java
  subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/file/AbstractFileCollection.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/AbstractFileCollectionTest.groovy
  subprojects/docs/src/docs/release/notes.md
Labels: from:member

#4840 Resolve version conflicts when selecting
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/DependencyMetadataRulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/RichVersionConstraintsIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/RichVersionConstraintsResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/VersionConflictResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/VersionRangeResolveIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/strategy/SubVersionSelector.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/ComponentResolutionState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/LatestModuleConflictResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ComponentState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ComponentStateWithDependents.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/DependencyGraphBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ModuleResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/RejectedModuleMessageBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/SelectorState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/conflicts/DefaultConflictHandler.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/conflicts/ModuleConflictHandler.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/GradleDependencyMetadata.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/AbstractConflictResolverTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/LatestModuleConflictResolverTest.groovy
Labels: from:member, in:dependency-management

#4820 Shaded jar as artifact transform take 2
  buildSrc/subprojects/integration-testing/integration-testing.gradle.kts
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/DistributionTestingPlugin.kt
  buildSrc/subprojects/packaging/packaging.gradle.kts
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/AnalyzeAndShade.kt
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/ClassGraph.kt
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/MinifyPlugin.kt
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/MinifyTransform.kt
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/ShadeClassesTransform.kt
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/ShadedJar.kt
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/ShadedJarCreator.kt
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/ShadedJarPlugin.kt
  subprojects/tooling-api/buildship.gradle
  subprojects/tooling-api/tooling-api.gradle.kts
Labels: from:member

#4811 Introduce build script best practices chapter in user guide
  subprojects/docs/src/docs/stylesheets/userGuideHtml.xsl
  subprojects/docs/src/docs/userguide/authoringMaintainableBuildScripts.adoc
  subprojects/docs/src/docs/userguide/commandLineInterface.adoc
  subprojects/docs/src/docs/userguide/userguide.xml
  subprojects/docs/src/samples/userguide/bestPractices/conditionalLogic/do/build.gradle
  subprojects/docs/src/samples/userguide/bestPractices/conditionalLogic/do/buildSrc/src/main/java/com/enterprise/ReleasePlugin.java
  subprojects/docs/src/samples/userguide/bestPractices/conditionalLogic/do/buildSrc/src/main/resources/META-INF/gradle-plugins/com.enterprise.release.properties
  subprojects/docs/src/samples/userguide/bestPractices/conditionalLogic/dont/build.gradle
  subprojects/docs/src/samples/userguide/bestPractices/logicDuringConfiguration/do/build.gradle
  subprojects/docs/src/samples/userguide/bestPractices/logicDuringConfiguration/dont/build.gradle
  subprojects/docs/src/samples/userguide/bestPractices/taskGroupDescription/build.gradle
  subprojects/docs/src/samples/userguide/bestPractices/taskGroupDescription/settings.gradle
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/samples/bestpractices/SamplesAuthoringMaintainableBuildsIntegrationTest.groovy
Labels: a:feature, from:member, in:docs

#4852 Update ASM 6.1 to 6.1.1 to fix a regression
  gradle/dependencies.gradle
Labels: from:member

#4772 Remove PatchedClassReader
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/AbiExtractingClasspathResourceHasher.java
  subprojects/core/src/main/java/org/gradle/initialization/MixInLegacyTypesClassLoader.java
  subprojects/core/src/main/java/org/gradle/util/internal/PatchedClassReader.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/ClassChangeProcessor.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/analyzer/DefaultClassDependenciesAnalyzer.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/serialization/ClasspathInferer.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/serialization/ClientSidePayloadClassLoaderFactory.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/tasks/api/ApiJar.java
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/ValidateTaskProperties.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/detection/AbstractTestFrameworkDetector.java
Labels: a:chore, from:member

#3724 Add support for resources and test resources in IDEA module
  subprojects/distributions/src/changes/accepted-public-api-changes.json
  subprojects/docs/src/docs/dsl/org.gradle.plugins.ide.idea.model.IdeaModule.xml
  subprojects/docs/src/docs/release/notes.md
  subprojects/ide/src/crossVersionTest/groovy/org/gradle/plugins/ide/tooling/r47/ToolingApiIdeaModelCrossVersionSpec.groovy
  subprojects/ide/src/crossVersionTest/groovy/org/gradle/plugins/ide/tooling/r50/ToolingApiIdeaModelCrossVersionSpec.groovy
  subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/idea/IdeaModuleIntegrationTest.groovy
  subprojects/ide/src/main/java/org/gradle/plugins/ide/idea/IdeaPlugin.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/idea/model/IdeaModule.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/idea/model/Module.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/IdeaModelBuilder.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/idea/DefaultIdeaContentRoot.java
  subprojects/ide/src/test/groovy/org/gradle/plugins/ide/idea/model/ModuleTest.groovy
  subprojects/ide/src/test/resources/org/gradle/plugins/ide/idea/model/customModule.xml
  subprojects/tooling-api/src/main/java/org/gradle/tooling/model/idea/IdeaContentRoot.java
Labels: a:bug, from:contributor, in:idea-plugin, waiting-for:gradle-team

#4855 Upgrade Kotlin DSL {0.16.2 => 0.16.3}
  buildSrc/subprojects/configuration/src/main/kotlin/org/gradle/gradlebuild/build-environment.kt
  buildSrc/subprojects/kotlin-dsl/kotlin-dsl.gradle.kts
  buildSrc/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/kotlin-dsl-upstream.kt
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/inception/GradleInceptionPerformanceTest.groovy
  subprojects/performance/templates.gradle
Labels: a:feature, from:member, in:core

#4833 Use an empty Object[] const to call through from non-parameterized create() method
  subprojects/base-services/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java
  subprojects/base-services/src/main/java/org/gradle/internal/service/ServiceRegistry.java
  subprojects/core-api/src/main/java/org/gradle/api/tasks/TaskContainer.java
  subprojects/core/src/main/java/org/gradle/api/internal/DependencyInjectingInstantiator.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/taskfactory/TaskFactory.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskContainer.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/DependencyInjectingInstantiatorTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/DependencyInjectingServiceLoaderTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/DependencyInjectionUsingClassGeneratorBackedInstantiatorTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskDefinitionIntegrationSpec.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerExecutorInjectionIntegrationTest.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerExecutorNestingIntegrationTest.groovy
Labels: from:member, in:core

#4857 Add JavaVersion.getName() back
  subprojects/base-services/src/main/java/org/gradle/api/JavaVersion.java
Labels: a:chore, from:member

#4866 Fix failed tests in #3724
  subprojects/distributions/src/changes/accepted-public-api-changes.json
  subprojects/docs/src/docs/dsl/org.gradle.plugins.ide.idea.model.IdeaModule.xml
  subprojects/docs/src/docs/release/notes.md
  subprojects/ide/src/crossVersionTest/groovy/org/gradle/plugins/ide/tooling/r47/ToolingApiIdeaModelCrossVersionSpec.groovy
  subprojects/ide/src/crossVersionTest/groovy/org/gradle/plugins/ide/tooling/r50/ToolingApiIdeaModelCrossVersionSpec.groovy
  subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/idea/IdeaModuleIntegrationTest.groovy
  subprojects/ide/src/main/java/org/gradle/plugins/ide/idea/IdeaPlugin.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/idea/model/IdeaModule.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/idea/model/Module.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/IdeaModelBuilder.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/idea/DefaultIdeaContentRoot.java
  subprojects/ide/src/test/groovy/org/gradle/plugins/ide/idea/model/ModuleTest.groovy
  subprojects/ide/src/test/resources/org/gradle/plugins/ide/idea/model/customModule.xml
  subprojects/tooling-api/src/main/java/org/gradle/tooling/model/idea/IdeaContentRoot.java
Labels: from:member

#4868 Add @Incubating and @since for JavaVersion
  subprojects/base-services/src/main/java/org/gradle/api/JavaVersion.java
  subprojects/distributions/src/changes/accepted-public-api-changes.json
Labels: a:chore, from:member

#4869 Mention changes to ReportContainer in release notes
  subprojects/docs/src/docs/release/notes.md
Labels: from:member

#4871 Deprecate FileCollection.add()
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/pmd/PmdPluginVersionIntegrationTest.groovy
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdExtension.java
  subprojects/core-api/src/main/java/org/gradle/api/file/FileCollection.java
  subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/file/UnionFileCollection.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/UnionFileTree.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/UnionFileCollectionTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/UnionFileTreeTest.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/TestReport.java
Labels: from:member

#4864 Combine TaskDefinitionIntegrationSpec into TaskDefinitionIntegrationTest
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskDefinitionIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskDefinitionIntegrationTest.java
Labels: a:chore, from:member

#4876 Fix some minor issues with the rich console
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/taskgrouping/rich/RichConsoleBasicGroupedTaskLoggingFunctionalTest.groovy
  subprojects/logging/src/main/java/org/gradle/internal/logging/sink/GroupingProgressLogEventGenerator.java
  subprojects/logging/src/test/groovy/org/gradle/internal/logging/sink/GroupingProgressLogEventGeneratorTest.groovy
Labels: a:bug, from:member

#4873 Extract logic for resolving selectors out of DependencyGraphBuilder
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/VersionConflictResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/VersionRangeResolveIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/ComponentResolutionState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/ProjectDependencyForcingResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ComponentState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/DependencyGraphBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/RejectedModuleMessageBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/SelectorState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/selectors/ComponentStateFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/selectors/ResolvableSelectorState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/selectors/SelectorStateResolver.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/AbstractConflictResolverTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/selectors/SelectorStateResolverTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/selectors/TestComponentResolutionState.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/selectors/TestSelectorState.java
  subprojects/dependency-management/src/testFixtures/groovy/org/gradle/resolve/scenarios/VersionRangeResolveTestScenarios.groovy
Labels: from:member, in:dependency-management

#4865 Improvements to "Authoring Maintainable Build Scripts" docs
  subprojects/docs/src/docs/userguide/authoringMaintainableBuildScripts.adoc
Labels: from:member, in:docs

#4880 Fix documentation distribution plugin
  subprojects/docs/src/docs/userguide/distributionPlugin.adoc
Labels: a:chore, from:contributor

#4890 Fix NPE when partial installs of Visual Studio are found
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/msvcpp/version/CommandLineToolVersionLocator.java
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/msvcpp/version/DefaultVisualCppMetadataProvider.java
  subprojects/platform-native/src/test/groovy/org/gradle/nativeplatform/toolchain/internal/msvcpp/version/CommandLineToolVersionLocatorTest.groovy
Labels: a:bug, from:member

#4885 Link to release notes in welcome message instead of gradle.org/releases
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/cli/NotificationsIntegrationTest.groovy
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/CommandLineActionFactory.java
Labels: from:member, in:logging

#4891 Improve improved nested inputs release notes section
  subprojects/docs/src/docs/release/notes.md
Labels: from:member
