Repository gradle/gradle, pull requests merged in 2018-08, with the labels that each got.

#5329 Give S3 bucket owner full control over the published maven artifacts
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/repository_types.adoc
  subprojects/resources-s3/src/integTest/groovy/org/gradle/integtests/resource/s3/fixtures/S3Server.groovy
  subprojects/resources-s3/src/main/java/org/gradle/internal/resource/transport/aws/s3/S3Client.java
  subprojects/resources-s3/src/test/groovy/org/gradle/internal/resource/transport/aws/s3/S3ClientTest.groovy
Labels: a:bug, from:contributor, in:publishing-plugin, waiting-for:gradle-team

#6139 Make recommendation against `new File(relativePath)` stronger
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenLocalRepoResolveIntegrationTest.groovy
  subprojects/docs/src/docs/userguide/working_with_files.adoc
  subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/eclipse/EclipseClasspathFixture.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/environment/BuildEnvironmentIntegrationTest.groovy
  subprojects/internal-testing/src/main/groovy/org/gradle/util/TestPrecondition.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r35/BuildEnvironmentCrossVersionSpec.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerDaemonIntegrationTest.groovy
Labels: from:member

#6127 Add first-class support for Javac's -h option
  subprojects/docs/src/docs/dsl/org.gradle.api.tasks.compile.CompileOptions.xml
  subprojects/language-groovy/src/test/groovy/org/gradle/api/internal/tasks/compile/DefaultGroovyJavaJointCompileSpecFactoryTest.groovy
  subprojects/language-groovy/src/test/groovy/org/gradle/api/internal/tasks/compile/NormalizingGroovyCompilerTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/SourceIncrementalJavaCompilationIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/CleaningJavaCompilerSupport.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompilerArgumentsBuilder.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/MinimalJavaCompileOptions.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/IncrementalCompilationInitializer.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/CompileOptions.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/AnnotationProcessorDiscoveringCompilerTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/AnnotationProcessorPathFactoryTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/CleaningJavaCompilerTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/CommandLineJavaCompilerArgumentsGeneratorTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/DefaultJavaCompileSpecFactoryTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/JavaCompilerArgumentsBuilderTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/NormalizingJavaCompilerTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/incremental/IncrementalCompilationInitializerTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/tasks/compile/CompileOptionsTest.groovy
  subprojects/language-scala/src/test/groovy/org/gradle/api/internal/tasks/scala/DefaultScalaJavaJointCompileSpecFactoryTest.groovy
  subprojects/language-scala/src/test/groovy/org/gradle/api/internal/tasks/scala/NormalizingScalaCompilerTest.groovy
Labels: from:member

#6154 Add plugin portal mirror system property to startup parameters
  .teamcity/Gradle_Check/configurations/GradleBuildConfigurationDefaults.kt
Labels: a:chore, dev-productivity, from:member

#6097 Expose insights to build script compilation
  subprojects/core-api/src/main/java/org/gradle/internal/scripts/CompileScriptBuildOperationType.java
  subprojects/core/src/integTest/groovy/org/gradle/groovy/scripts/GroovyCompileScriptBuildOperationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/configuration/DefaultScriptPluginFactory.java
  subprojects/core/src/main/java/org/gradle/groovy/scripts/internal/BuildOperationBackedScriptCompilationHandler.java
  subprojects/core/src/main/java/org/gradle/groovy/scripts/internal/CompileOperation.java
  subprojects/core/src/main/java/org/gradle/groovy/scripts/internal/FactoryBackedCompileOperation.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/BuildScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/groovy/scripts/internal/BuildScriptTransformerSpec.groovy
  subprojects/core/src/test/groovy/org/gradle/groovy/scripts/internal/DefaultScriptCompilationHandlerTest.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r40/PluginApplicationBuildProgressCrossVersionSpec.groovy
Labels: a:feature, from:member, in:core

#6160 Let the distributions contain a gradle-api-metadata jar
  buildSrc/subprojects/packaging/packaging.gradle.kts
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/ApiMetadataPlugin.kt
  subprojects/distributions/distributions.gradle
  subprojects/distributions/src/integTest/groovy/org/gradle/DistributionIntegrationSpec.groovy
Labels: from:member

#6162 New navigation for user manual (revised)
  subprojects/docs/src/docs/userguide/plugin_reference.adoc
  subprojects/docs/src/docs/userguide/third_party_integration.adoc
  subprojects/docs/src/main/resources/header.html
Labels: from:member, in:docs

#6166 Fix build logic to work with -Dorg.gradle.internal.tasks.eager=true
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/ApiMetadataPlugin.kt
  subprojects/distributions/distributions.gradle
Labels: from:member

#6129 Pass mirror init script down to smoke test builds
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
Labels: a:chore, dev-productivity, from:member

#6157 Ignore artifact transforms when resolving Task.getTaskDependencies()
  subprojects/core-api/src/main/java/org/gradle/api/internal/artifacts/transform/ArtifactTransformDependency.java
  subprojects/core-api/src/main/java/org/gradle/api/internal/artifacts/transform/package-info.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/AbstractTaskDependency.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/ConsumerProvidedResolvedVariant.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultArtifactTransformDependency.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformInfoDependencyResolver.java
Labels: from:member, in:build-cache

#6149 Disable daemon in noDaemonTest
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/Gradle_Check/projects/FunctionalTestProject.kt
  .teamcity/Gradle_Check/projects/StageProject.kt
Labels: a:chore, dev-productivity, from:member

#6159 Schedule same transforms only once per artifact
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformInfoFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformInfo.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/UserCodeBackedTransformer.java
Labels: from:member

#6123 Set mirror for kotlin
  build.gradle.kts
  buildSrc/settings.gradle.kts
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/RepoScriptBlockUtil.groovy
Labels: a:chore, dev-productivity, from:member

#6181 Expose which build included the build being loaded to operation listeners
  subprojects/composite-builds/src/test/groovy/org/gradle/composite/internal/DefaultIncludedBuildRegistryTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/BuildInitializationBuildOperationsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/internal/operations/notify/BuildOperationNotificationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/BuildDefinition.java
  subprojects/core/src/main/java/org/gradle/api/internal/GradleInternal.java
  subprojects/core/src/main/java/org/gradle/api/tasks/GradleBuild.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradleLauncher.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradleLauncherFactory.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultSettingsLoader.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultSettingsLoaderFactory.java
  subprojects/core/src/main/java/org/gradle/initialization/LoadBuildBuildOperationType.java
  subprojects/core/src/main/java/org/gradle/initialization/buildsrc/BuildSourceBuilder.java
  subprojects/core/src/main/java/org/gradle/internal/build/DefaultPublicBuildPath.java
  subprojects/core/src/main/java/org/gradle/internal/build/MutablePublicBuildPath.java
  subprojects/core/src/main/java/org/gradle/internal/build/PublicBuildPath.java
  subprojects/core/src/main/java/org/gradle/internal/composite/ChildBuildRegisteringSettingsLoader.java
  subprojects/core/src/main/java/org/gradle/internal/operations/trace/BuildOperationTrace.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/BuildScopeServices.java
  subprojects/core/src/main/java/org/gradle/invocation/DefaultGradle.java
  subprojects/core/src/main/java/org/gradle/testfixtures/internal/TestBuildScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/initialization/DefaultGradleLauncherFactoryTest.groovy
  subprojects/core/src/test/groovy/org/gradle/initialization/DefaultGradleLauncherSpec.groovy
  subprojects/core/src/test/groovy/org/gradle/initialization/DefaultSettingsLoaderTest.groovy
  subprojects/core/src/test/groovy/org/gradle/invocation/DefaultGradleSpec.groovy
  subprojects/launcher/src/main/java/org/gradle/launcher/exec/InProcessBuildActionExecuter.java
  subprojects/version-control/src/main/java/org/gradle/vcs/internal/resolver/VcsDependencyResolver.java
  subprojects/version-control/src/main/java/org/gradle/vcs/internal/services/VersionControlServices.java
Labels: from:member, in:core

#6173 Remove reference to Nebula documentation
  subprojects/docs/src/docs/userguide/dependency_locking.adoc
Labels: from:member, in:docs

#6183 Make Lombok work in forked compilers
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/AnnotationProcessingCompileTask.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AnnotationProcessingSmokeTest.groovy
Labels: a:bug, from:member, in:jvm-platform

#6188 Update Nebula recommender plugin version for smoke test
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/resolve/ResolveTestFixture.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/BomSupportPluginsSmokeTest.groovy
Labels: from:member, in:dependency-management

#6180 Add link to user manual PDF in navigation
  subprojects/docs/src/docs/css/manual.css
  subprojects/docs/src/main/resources/header.html
Labels: from:member, in:docs

#6186 Use new BuildOperation category for transforms
  subprojects/base-services/src/main/java/org/gradle/internal/operations/BuildOperationCategory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformInfo.java
  subprojects/logging/src/main/java/org/gradle/internal/logging/console/BuildStatusRenderer.java
  subprojects/logging/src/main/java/org/gradle/internal/logging/progress/DefaultProgressLoggerFactory.java
  subprojects/logging/src/main/java/org/gradle/internal/logging/sink/GroupingProgressLogEventGenerator.java
Labels: from:member

#6191 Fix issue with CME when mutating the collection while inside configureEach action
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/DeferredTaskDefinitionIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/DefaultDomainObjectCollection.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/AbstractDomainObjectCollectionSpec.groovy
Labels: a:bug, from:member

#6185 Prevent CMEs when creating Ivy instances
  subprojects/base-services/src/integTest/groovy/org/gradle/internal/SystemPropertiesIntegrationTest.groovy
  subprojects/base-services/src/main/java/org/gradle/internal/SystemProperties.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/DefaultIvyContextManager.java
Labels: from:member

#6190 Ensure file lock is released before cache cleanup
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/DefaultCacheAccess.java
  subprojects/persistent-cache/src/test/groovy/org/gradle/cache/internal/DefaultCacheAccessTest.groovy
Labels: a:bug, from:member, in:core

#6158 Dependency management entries are no longer transitive
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenBomResolveIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/GradlePomModuleDescriptorBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/GradlePomModuleDescriptorParser.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/maven/MavenDependencyDescriptor.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/GradlePomModuleDescriptorParserBomTest.groovy
Labels: from:member, in:dependency-management

#5926 Improve performance of nodes being queued
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/DefaultPendingDependenciesHandler.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/NodeState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ResolveState.java
Labels: a:chore, in:dependency-management

#6179 Gradle 4.10 release notes/features
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/release/release-features.txt
Labels: from:member, in:docs

#6199 Improve performance for getRegularFileSnapshot
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/DefaultFileSystemSnapshotter.java
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/RealWorldNativePluginPerformanceTest.groovy
Labels: from:member

#6218 Workaround for Groovy compiler bug
  subprojects/core/src/main/java/org/gradle/api/internal/AbstractTask.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProject.java
  subprojects/integ-test/src/crossVersionTest/groovy/org/gradle/integtests/TaskSubclassingBinaryCompatibilityCrossVersionSpec.groovy
Labels: from:member, in:build-cache

#6224 Trim performance test scenario names
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/TestScenarioSelector.java
Labels: from:member

#6202 Leverage defaultDependencies for zinc configuration
  subprojects/scala/src/main/java/org/gradle/api/plugins/scala/ScalaBasePlugin.java
  subprojects/scala/src/test/groovy/org/gradle/api/plugins/scala/ScalaBasePluginTest.groovy
Labels: from:member, in:dependency-management

#6231 Only run static Groovy compile subclassing tests with Gradle 2.1+
  subprojects/integ-test/src/crossVersionTest/groovy/org/gradle/integtests/StaticGroovyTaskSubclassingBinaryCompatibilityCrossVersionSpec.groovy
  subprojects/integ-test/src/crossVersionTest/groovy/org/gradle/integtests/TaskSubclassingBinaryCompatibilityCrossVersionSpec.groovy
Labels: from:member, in:build-cache

#6184 Include artifact transforms in profile report
  subprojects/core-api/src/main/java/org/gradle/api/internal/artifacts/transform/ArtifactTransformListener.java
  subprojects/core-api/src/main/java/org/gradle/api/internal/artifacts/transform/ArtifactTransformer.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/EventFiringTaskExecuter.java
  subprojects/core/src/main/java/org/gradle/execution/TaskExecutionGraphInternal.java
  subprojects/core/src/main/java/org/gradle/execution/taskgraph/DefaultTaskExecutionGraph.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradleLauncherFactory.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GradleScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/TaskExecutionServices.java
  subprojects/core/src/main/java/org/gradle/profile/BuildProfile.java
  subprojects/core/src/main/java/org/gradle/profile/CompositeOperation.java
  subprojects/core/src/main/java/org/gradle/profile/ContinuousOperation.java
  subprojects/core/src/main/java/org/gradle/profile/FragmentedOperation.java
  subprojects/core/src/main/java/org/gradle/profile/Operation.java
  subprojects/core/src/main/java/org/gradle/profile/ProfileEventAdapter.java
  subprojects/core/src/main/java/org/gradle/profile/ProfileReportRenderer.java
  subprojects/core/src/main/java/org/gradle/profile/ProjectProfile.java
  subprojects/core/src/main/java/org/gradle/profile/package-info.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/EventFiringTaskExecuterTest.groovy
  subprojects/core/src/test/groovy/org/gradle/execution/taskgraph/DefaultTaskExecutionGraphSpec.groovy
  subprojects/core/src/test/groovy/org/gradle/profile/ProfileReportRendererTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultDependencyManagementServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/AttributeMatchingVariantSelector.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/ConsumerProvidedResolvedVariant.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultArtifactTransforms.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformArtifactOperation.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformFileOperation.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformInfo.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformInfoExecutor.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformingAsyncArtifactListener.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/DefaultArtifactTransformsTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/TransformingAsyncArtifactListenerTest.groovy
Labels: from:member

#6219 Refine Kotlin DSL release notes preamble & breaking changes section
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/release/release-features.txt
Labels: from:member

#6148 Allow domain object collections to accept provider of Iterable
  subprojects/core-api/src/main/java/org/gradle/api/DomainObjectCollection.java
  subprojects/core/src/main/java/org/gradle/api/internal/CompositeDomainObjectSet.java
  subprojects/core/src/main/java/org/gradle/api/internal/DefaultDomainObjectCollection.java
  subprojects/core/src/main/java/org/gradle/api/internal/DelegatingDomainObjectSet.java
  subprojects/core/src/main/java/org/gradle/api/internal/TypedDomainObjectContainerWrapper.java
  subprojects/core/src/main/java/org/gradle/api/internal/collections/AbstractIterationOrderRetainingElementSource.java
  subprojects/core/src/main/java/org/gradle/api/internal/collections/DefaultPendingSource.java
  subprojects/core/src/main/java/org/gradle/api/internal/collections/FilteredCollection.java
  subprojects/core/src/main/java/org/gradle/api/internal/collections/IterationOrderRetainingSetElementSource.java
  subprojects/core/src/main/java/org/gradle/api/internal/collections/ListElementSource.java
  subprojects/core/src/main/java/org/gradle/api/internal/collections/PendingSource.java
  subprojects/core/src/main/java/org/gradle/api/internal/collections/SortedSetElementSource.java
  subprojects/core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java
  subprojects/core/src/main/java/org/gradle/api/internal/provider/CollectionProviderInternal.java
  subprojects/core/src/main/java/org/gradle/api/internal/provider/Collector.java
  subprojects/core/src/main/java/org/gradle/api/internal/provider/Collectors.java
  subprojects/core/src/main/java/org/gradle/api/internal/provider/ValueCollector.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskContainer.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/RealizableTaskCollection.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/AbstractDomainObjectCollectionSpec.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/collections/AbstractIterationOrderRetainingElementSourceTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/collections/ListElementSourceTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskDefinitionIntegrationTest.groovy
  subprojects/platform-base/src/main/java/org/gradle/platform/base/internal/BinaryTasksCollectionWrapper.java
Labels: a:feature, from:contributor

#6200 Use one build operation per transform step
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformInfoFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformArtifactOperation.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformFileOperation.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformInfo.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformingAsyncArtifactListener.java
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/AbstractConsoleBuildPhaseFunctionalTest.groovy
Labels: from:member

#6214 Introduce Kotlin DSL user manual chapter
  subprojects/docs/src/docs/userguide/kotlin_dsl.adoc
Labels: from:member

#6178 Treat 'prefer' version constraints as recommendations
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/MutableVersionConstraint.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ConfigurationMutationIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/DependencyMetadataRulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/VersionRangeResolveIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultMutableVersionConstraint.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/selectors/SelectorStateResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/selectors/SelectorStateResolverResults.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/dependencies/DefaultMutableVersionConstraintTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/selectors/SelectorStateResolverTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/selectors/TestModuleSelectorState.java
  subprojects/dependency-management/src/testFixtures/groovy/org/gradle/resolve/scenarios/VersionRangeResolveTestScenarios.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyPublishJavaIntegTest.groovy
Labels: a:feature, in:dependency-management

#6234 Make sure clean tasks are instantiated while project state is mutable
  subprojects/platform-base/src/main/java/org/gradle/language/base/plugins/LifecycleBasePlugin.java
Labels: a:bug, from:member

#6237 Remove unnecessary condition
  subprojects/integ-test/src/crossVersionTest/groovy/org/gradle/integtests/StaticGroovyTaskSubclassingBinaryCompatibilityCrossVersionSpec.groovy
Labels: from:member

#6242 Mention that incremental build now uses less memory
  subprojects/docs/src/docs/release/notes.md
Labels: from:member

#6194 Use experimental ASM 7 mode
  subprojects/base-services/base-services.gradle.kts
  subprojects/base-services/src/main/java/org/gradle/internal/classanalysis/AsmConstants.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/compile/ApiMemberSelector.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/compile/MethodStubbingApiMemberAdapter.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/compile/SortingAnnotationVisitor.java
  subprojects/core/src/main/java/org/gradle/groovy/scripts/internal/FileCacheBackedScriptClassCompiler.java
  subprojects/core/src/main/java/org/gradle/initialization/MixInLegacyTypesClassLoader.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/runtimeshaded/RuntimeShadedJarCreator.java
  subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/file/ClassFile.groovy
  subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/GroovyCompileTransformingClassLoader.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/asm/ClassDependenciesVisitor.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/serialization/ClientSidePayloadClassLoaderFactory.java
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/tasks/api/internal/ApiClassExtractorTest.groovy
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/ValidateTaskProperties.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/detection/TestClassVisitor.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitTestClassDetector.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGTestClassDetector.java
Labels: a:feature, from:member, in:core

#6182 Decrease first use of largeJavaMultiProjectKotlinDsl runs to 5
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaFirstUsePerformanceTest.groovy
Labels: a:chore, dev-productivity, from:member

#6258 Show conflict resolution reason for 2nd level dependencies
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/DependencyInsightReportTaskIntegrationTest.groovy
  subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/internal/graph/nodes/InvertedRenderableModuleResult.java
Labels: from:member, in:dependency-management

#6309 Always use upper case for script compile build operation language
  subprojects/core-api/src/main/java/org/gradle/internal/scripts/CompileScriptBuildOperationType.java
  subprojects/core/src/integTest/groovy/org/gradle/groovy/scripts/GroovyCompileScriptBuildOperationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/groovy/scripts/internal/BuildOperationBackedScriptCompilationHandler.java
Labels: from:member

#6323 Disable scan plugin <= 1.15.1 if Kotlin script build caching is used
  subprojects/core/src/integTest/groovy/org/gradle/internal/scan/config/BuildScanConfigIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/internal/scan/config/BuildScanConfigServices.java
  subprojects/core/src/main/java/org/gradle/internal/scan/config/BuildScanPluginCompatibility.java
  subprojects/core/src/test/groovy/org/gradle/internal/scan/config/BuildScanConfigManagerTest.groovy
Labels: from:member

#6221 Add dedicated chapter on directory layout
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/directory_layout.adoc
  subprojects/docs/src/docs/userguide/userguide_single.adoc
  subprojects/docs/src/main/resources/header.html
Labels: a:chore, from:member, in:docs

#6325 Add a test for consistent handling of root directories between `@InputFiles` and `@InputDirectory
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskUpToDateIntegrationTest.groovy
Labels: from:contributor, in:incremental-build

#6333 Upgrade Kotlin DSL `1.0-rc-{1 => 2}`
  buildSrc/subprojects/configuration/src/main/kotlin/org/gradle/gradlebuild/build-environment.kt
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/release/release-features.txt
Labels: a:feature, dogfood:kotlin-dsl, from:member

#6347 Add missing doc for kotlinDslPluginOptions.experimentalWarning
  subprojects/docs/src/docs/userguide/kotlin_dsl.adoc
Labels: from:member, in:docs

#6247 Fix BuildDashboardPlugin forcing configuration of all tasks
  subprojects/reporting/src/main/java/org/gradle/api/reporting/plugins/BuildDashboardPlugin.java
Labels: from:contributor, in:core

#6335 Validate Jdks at execution time
  build.gradle.kts
  buildSrc/subprojects/buildquality/src/main/kotlin/org/gradle/gradlebuild/buildquality/AddVerifyProductionEnvironmentTaskPlugin.kt
  buildSrc/subprojects/configuration/src/main/kotlin/org/gradle/gradlebuild/java/AvailableJavaInstallations.kt
  buildSrc/subprojects/configuration/src/main/kotlin/org/gradle/gradlebuild/java/AvailableJavaInstallationsPlugin.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/gradlebuild/unittestandcompile/UnitTestAndCompilePlugin.kt
Labels: from:member, in:gradle-build

#6328 Rename PhysicalSnapshot -> FileSystemLocationSnapshot
  subprojects/core/src/main/java/org/gradle/api/internal/OverlappingOutputs.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/CacheBackedTaskHistoryRepository.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/DefaultTaskOutputFilesRepository.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/JarHasher.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/ResolveBuildCacheKeyExecuter.java
  subprojects/core/src/main/java/org/gradle/caching/internal/tasks/TarTaskOutputPacker.java
  subprojects/core/src/main/java/org/gradle/caching/internal/tasks/TaskOutputCacheCommandFactory.java
  subprojects/core/src/main/java/org/gradle/caching/internal/tasks/TaskOutputPacker.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/FileCollectionFingerprint.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/FileSystemLocationFingerprint.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/FingerprintingStrategy.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/AbsolutePathFingerprintCompareStrategy.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/AbsolutePathFingerprintingStrategy.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/AbstractFileSystemLocationFingerprint.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/ClasspathCompareStrategy.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/ClasspathFingerprintingStrategy.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/DefaultCurrentFileCollectionFingerprint.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/DefaultFileSystemLocationFingerprint.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/DefaultHistoricalFileCollectionFingerprint.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/EmptyCurrentFileCollectionFingerprint.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/EmptyHistoricalFileCollectionFingerprint.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/FingerprintCompareStrategy.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/FingerprintMapSerializer.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/IgnoredPathCompareStrategy.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/IgnoredPathFileSystemLocationFingerprint.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/IgnoredPathFingerprintingStrategy.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/NameOnlyFingerprintingStrategy.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/NormalizedPathFingerprintCompareStrategy.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/RelativePathFingerprintingStrategy.java
  subprojects/core/src/main/java/org/gradle/internal/snapshot/AbstractFileSystemLocationSnapshot.java
  subprojects/core/src/main/java/org/gradle/internal/snapshot/DirectorySnapshot.java
  subprojects/core/src/main/java/org/gradle/internal/snapshot/FileSystemLocationSnapshot.java
  subprojects/core/src/main/java/org/gradle/internal/snapshot/FileSystemMirror.java
  subprojects/core/src/main/java/org/gradle/internal/snapshot/FileSystemSnapshot.java
  subprojects/core/src/main/java/org/gradle/internal/snapshot/FileSystemSnapshotVisitor.java
  subprojects/core/src/main/java/org/gradle/internal/snapshot/FileSystemSnapshotter.java
  subprojects/core/src/main/java/org/gradle/internal/snapshot/MerkleDirectorySnapshotBuilder.java
  subprojects/core/src/main/java/org/gradle/internal/snapshot/MissingFileSnapshot.java
  subprojects/core/src/main/java/org/gradle/internal/snapshot/RegularFileSnapshot.java
  subprojects/core/src/main/java/org/gradle/internal/snapshot/RelativePathSegmentsTracker.java
  subprojects/core/src/main/java/org/gradle/internal/snapshot/RelativePathStringTracker.java
  subprojects/core/src/main/java/org/gradle/internal/snapshot/impl/DefaultFileSystemMirror.java
  subprojects/core/src/main/java/org/gradle/internal/snapshot/impl/DefaultFileSystemSnapshotter.java
  subprojects/core/src/main/java/org/gradle/internal/snapshot/impl/DirectorySnapshotter.java
  subprojects/core/src/main/java/org/gradle/internal/snapshot/impl/FileSystemSnapshotFilter.java
  subprojects/core/src/test/groovy/org/gradle/internal/fingerprint/impl/DefaultClasspathFingerprinterTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/fingerprint/impl/DefaultHistoricalFileCollectionFingerprintSerializerTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/fingerprint/impl/EmptyFileCollectionFingerprintTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/fingerprint/impl/FingerprintCompareStrategyTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/fingerprint/impl/PathNormalizationStrategyTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/snapshot/impl/DefaultFileSystemMirrorTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/snapshot/impl/DefaultFileSystemSnapshotterTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/snapshot/impl/FileSystemSnapshotBuilderTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/snapshot/impl/FileSystemSnapshotFilterTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/internal/snapshot/impl/TestFileSnapshotter.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformedFileCache.java
Labels: from:member

#6352 Reduce flakiness of CorruptedTaskHistoryIntegrationTest
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/changedetection/CorruptedTaskHistoryIntegrationTest.groovy
Labels: from:member

#6367 Upgrade Kotlin DSL `1.0-rc-{2 => 3}`
  buildSrc/subprojects/configuration/src/main/kotlin/org/gradle/gradlebuild/build-environment.kt
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/release/release-features.txt
Labels: a:feature, dogfood:kotlin-dsl, from:member, in:core

#6315 Remove deprecated Signature methods
  subprojects/docs/src/docs/release/notes.md
  subprojects/signing/src/integTest/groovy/org/gradle/plugins/signing/SigningTasksIntegrationSpec.groovy
  subprojects/signing/src/main/java/org/gradle/plugins/signing/Signature.java
Labels: a:chore, from:member, in:signing-plugin

#6364 Use compileAll to warm up the build cache
  .teamcity/Gradle_AgentTest/settings.kts
  .teamcity/Gradle_Check/configurations/CompileAll.kt
  .teamcity/Gradle_Check/configurations/GradleBuildConfigurationDefaults.kt
  .teamcity/Gradle_Check/configurations/SanityCheck.kt
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcityTest/Gradle_Check_Tests/CIConfigIntegrationTests.kt
Labels: dev-productivity, from:member

#6351 Use setup/cleanup instead of rule
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r47/BuildProgressCrossVersionSpec.groovy
Labels: from:member

#6357 Fix deprecation warning
  subprojects/platform-play/src/main/java/org/gradle/scala/internal/reflect/ScalaListBuffer.java
Labels: from:member

#6358 Remove DirectoryBuildCache#targetSizeInMb
  subprojects/build-cache/src/main/java/org/gradle/caching/local/DirectoryBuildCache.java
  subprojects/docs/src/docs/release/notes.md
Labels: from:member

#6359 Remove deprecated methods on Task and TaskInternal
  subprojects/core-api/src/main/java/org/gradle/api/Task.java
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/ExecutionTimeTaskConfigurationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/AbstractTask.java
  subprojects/core/src/main/java/org/gradle/api/internal/TaskInternal.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/SkipTaskWithNoActionsExecuter.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/DefaultTaskTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/SkipTaskWithNoActionsExecuterTest.groovy
  subprojects/core/src/test/groovy/org/gradle/testfixtures/ProjectBuilderTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/api/tasks/AbstractSpockTaskTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/api/tasks/AbstractTaskTest.groovy
  subprojects/distributions/src/changes/accepted-public-api-changes.json
  subprojects/docs/src/docs/dsl/org.gradle.api.Task.xml
  subprojects/docs/src/docs/release/notes.md
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskExecutionIntegrationTest.groovy
Labels: from:member

#6356 Only cleanup untracked cache entries not modified recently
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/DefaultFileAccessTimeJournal.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/changedetection/state/DefaultFileAccessTimeJournalTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/cache/FileAccessTimeJournalFixture.groovy
Labels: a:bug, from:member, in:core

#6373 Remove `ExecuteAtMostOnceTaskExecuter`
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/ExecuteAtMostOnceTaskExecuter.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/TaskExecutionServices.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ExecuteAtMostOnceTaskExecuterTest.groovy
Labels: from:member

#6208 No Deprecated Configurations In Build Init
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/BuildScriptBuilder.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/GroovyProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/JavaProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/ScalaLibraryProjectInitDescriptor.java
  subprojects/build-init/src/test/groovy/org/gradle/buildinit/plugins/internal/BuildScriptBuilderGroovyTest.groovy
  subprojects/build-init/src/test/groovy/org/gradle/buildinit/plugins/internal/BuildScriptBuilderKotlinTest.groovy
  subprojects/docs/src/docs/release/notes.md
Labels: a:feature, from:contributor, in:build-init-plugin, waiting-for:gradle-team

#5976 Update JavaLibraryDistributionPlugin
  subprojects/docs/src/docs/release/notes.md
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/JavaLibraryDistributionIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaLibraryDistributionPlugin.java
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/JavaLibraryDistributionPluginTest.groovy
Labels: a:feature, from:contributor, in:jvm-platform, waiting-for:gradle-team

#6365 Remove deprecated FileCollection methods
  subprojects/core-api/src/main/java/org/gradle/api/file/FileCollection.java
  subprojects/core-api/src/test/groovy/org/gradle/api/tasks/util/PatternSetTest.groovy
  subprojects/core-api/src/testFixtures/groovy/org/gradle/api/tasks/util/AbstractTestForPatternSet.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/file/collections/SimpleFileCollectionIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/file/AbstractFileCollection.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/UnionFileCollection.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/UnionFileTree.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/collections/SimpleFileCollection.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/AbstractFileCollectionTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/DefaultSourceDirectorySetTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/collections/DefaultConfigurableFileTreeTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/collections/ImmutableFileCollectionTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/collections/SimpleFileCollectionTest.groovy
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/samples/userguide/files/fileCollections/build.gradle
Labels: from:member

#6376 Remove SimpleWorkResult
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/SimpleWorkResult.java
  subprojects/docs/src/docs/release/notes.md
Labels: from:member

#6378 Fix BuildScanPluginCompatibility after Kotlin DSL 1.0-RC3
  subprojects/core/src/integTest/groovy/org/gradle/internal/scan/config/BuildScanConfigIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/internal/scan/config/BuildScanConfigServices.java
  subprojects/core/src/main/java/org/gradle/internal/scan/config/BuildScanPluginCompatibility.java
  subprojects/core/src/test/groovy/org/gradle/internal/scan/config/BuildScanConfigManagerTest.groovy
Labels: from:member, in:core

#6375 Remove TaskDestroyables.file(s)
  subprojects/core-api/src/main/java/org/gradle/api/tasks/TaskDestroyables.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskDestroyables.java
  subprojects/docs/src/docs/release/notes.md
Labels: from:member

#6377 Remove ScalaDocOptions.stylesheet
  subprojects/docs/src/docs/release/notes.md
  subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaDocOptions.java
  subprojects/scala/src/test/groovy/org/gradle/api/tasks/scala/ScalaDocOptionsTest.groovy
Labels: from:member

#6372 Add dependency on SanityCheck for Windows builds
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/Gradle_Check/projects/StageProject.kt
Labels: from:member

#6049 Deprecate `TaskContainer#remove*` methods for Gradle 6.0
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/DeferredTaskDefinitionIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskRemovalIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/AbstractNamedDomainObjectContainer.java
  subprojects/core/src/main/java/org/gradle/api/internal/AbstractPolymorphicDomainObjectContainer.java
  subprojects/core/src/main/java/org/gradle/api/internal/DefaultDomainObjectCollection.java
  subprojects/core/src/main/java/org/gradle/api/internal/DefaultNamedDomainObjectCollection.java
  subprojects/core/src/main/java/org/gradle/api/internal/collections/AbstractIterationOrderRetainingElementSource.java
  subprojects/core/src/main/java/org/gradle/api/internal/collections/ListElementSource.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskCollection.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskContainer.java
  subprojects/core/src/main/java/org/gradle/model/collection/internal/BridgedCollections.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/AbstractDomainObjectCollectionSpec.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/AbstractNamedDomainObjectContainerTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/DefaultDomainObjectCollectionTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/DefaultDomainObjectSetTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/DefaultNamedDomainObjectCollectionTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/DefaultNamedDomainObjectListTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/DefaultNamedDomainObjectSetSpec.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/DefaultTaskContainerTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/StaleOutputHistoryLossIntegrationTest.groovy
Labels: a:chore, from:member, in:core

#6409 Forbid null as copySpec configuration action
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java
  subprojects/docs/src/docs/release/notes.md
Labels: from:member

#6411 Remove smoke test for xtend plugin
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ThirdPartyPluginsSmokeTest.groovy
Labels: from:member

#6401 Make watchpoint registration faster
  subprojects/core/src/integTest/groovy/org/gradle/internal/filewatch/jdk7/WatchServiceFileWatcherBackingTest.groovy
  subprojects/core/src/main/java/org/gradle/internal/filewatch/jdk7/Jdk7FileWatcherFactory.java
  subprojects/core/src/main/java/org/gradle/internal/filewatch/jdk7/WatchPointsRegistry.java
  subprojects/core/src/main/java/org/gradle/internal/filewatch/jdk7/WatchServiceFileWatcherBacking.java
  subprojects/core/src/main/java/org/gradle/internal/filewatch/jdk7/WatchServiceRegistrar.java
  subprojects/core/src/test/groovy/org/gradle/internal/filewatch/jdk7/WatchPointsRegistryTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/filewatch/jdk7/WatchServiceRegistrarTest.groovy
Labels: a:performance-issue, from:member, in:continuous-build

#6380 Remove CompileOptions.bootClasspath
  subprojects/docs/src/docs/dsl/org.gradle.api.tasks.compile.CompileOptions.xml
  subprojects/docs/src/docs/release/notes.md
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompilerArgumentsBuilder.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/MinimalJavaCompileOptions.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/CompileOptions.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/JavaCompilerArgumentsBuilderTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/tasks/compile/CompileOptionsTest.groovy
  subprojects/performance/templates.gradle
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
Labels: from:member

#6392 Skip afterResolve when result has errors
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/DependencyInsightReportTaskIntegrationTest.groovy
Labels: from:member, in:dependency-management

#6415 Fix incorrect conflict detection
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/VersionConflictResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/selectors/SelectorStateResolverResults.java
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/DependencyInsightReportTaskIntegrationTest.groovy
Labels: a:bug, in:dependency-management

#6408 Forbid registering invalid file inputs via the runtime API
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalBuildSymlinkHandlingIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskInputFilePropertiesIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskInputPropertiesIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultPropertySpecFactory.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskInputs.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskValidationContext.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/PropertySpecFactory.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/StaticValue.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskValidationContext.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/ValidationAction.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/ValidationActions.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/DefaultTaskProperties.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/ValidatingTaskExecuter.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/ClasspathPropertyAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/CompileClasspathPropertyAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/InputDirectoryPropertyAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/InputFilePropertyAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/InputFilesPropertyAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/NestedBeanAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/bean/AbstractNestedRuntimeBeanNode.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/changedetection/changes/DefaultTaskArtifactStateRepositoryTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ValidatingTaskExecuterTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/annotations/NestedBeanAnnotationHandlerTest.groovy
  subprojects/docs/src/docs/release/notes.md
Labels: from:member

#6430 Add samples as an input to `integTest:integTest`
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/DistributionTest.kt
  subprojects/integ-test/integ-test.gradle
Labels: in:gradle-build

#6366 Remove '@' from Provider link in more_about_tasks
  subprojects/docs/src/docs/userguide/more_about_tasks.adoc
Labels: from:contributor, in:docs

#6410 Disallow task inputs/outputs chaining
  buildSrc/subprojects/binary-compatibility/src/main/groovy/org/gradle/binarycompatibility/rules/AbstractGradleViolationRule.groovy
  buildSrc/subprojects/binary-compatibility/src/main/groovy/org/gradle/binarycompatibility/rules/BinaryBreakingChangesRule.java
  subprojects/core-api/src/main/java/org/gradle/api/tasks/CompatibilityAdapterForTaskInputs.java
  subprojects/core-api/src/main/java/org/gradle/api/tasks/CompatibilityAdapterForTaskOutputs.java
  subprojects/core-api/src/main/java/org/gradle/api/tasks/TaskInputFilePropertyBuilder.java
  subprojects/core-api/src/main/java/org/gradle/api/tasks/TaskInputPropertyBuilder.java
  subprojects/core-api/src/main/java/org/gradle/api/tasks/TaskInputs.java
  subprojects/core-api/src/main/java/org/gradle/api/tasks/TaskOutputFilePropertyBuilder.java
  subprojects/core-api/src/main/java/org/gradle/api/tasks/TaskOutputs.java
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskInputPropertiesIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/AbstractTaskOutputPropertySpec.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultPropertySpecFactory.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskInputFilePropertySpec.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskInputPropertySpec.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskInputs.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskOutputs.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/LenientTaskInputsDeprecationSupport.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/NonCacheableTaskOutputPropertySpec.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskInputsDeprecationSupport.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskOutputsDeprecationSupport.java
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/MixInCoreTypesTransformingClassLoaderIntegrationTest.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r33/IncompatibilityCrossVersionSpec.groovy
Labels: from:member

#6451 Avoid expensive ExceptionUtils.getRootCause
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/ResolveExceptionAnalyzer.java
Labels: a:performance-issue, from:member, in:dependency-management

#6456 Re-introduce CompatibilityAdapterForTaskInputs
  subprojects/core-api/src/main/java/org/gradle/api/tasks/CompatibilityAdapterForTaskInputs.java
  subprojects/core-api/src/main/java/org/gradle/api/tasks/TaskInputPropertyBuilder.java
  subprojects/core-api/src/main/java/org/gradle/api/tasks/TaskInputs.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskInputPropertySpec.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/integ-test/src/crossVersionTest/groovy/org/gradle/integtests/TaskSubclassingBinaryCompatibilityCrossVersionSpec.groovy
Labels: in:incremental-build

#6459 Update build scan plugin to 1.16
  buildSrc/subprojects/profiling/profiling.gradle.kts
  subprojects/core/src/main/java/org/gradle/plugin/management/internal/autoapply/AutoAppliedBuildScanPlugin.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/BuildScanPluginSmokeTest.groovy
Labels: from:member

#6464 Every task must run after clean in `gradle/gradle`
  buildSrc/subprojects/cleanup/src/main/kotlin/org/gradle/gradlebuild/testing/integrationtests/cleanup/CleanupPlugin.kt
  subprojects/distributions/distributions.gradle
Labels: from:member, in:gradle-build

#6437 Disallow more project configuration hooks from lazy configuration actions
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/DeferredTaskDefinitionIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/project/BuildOperationCrossProjectConfigurator.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/CrossProjectConfigurator.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProject.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskContainer.java
  subprojects/core/src/main/java/org/gradle/invocation/DefaultGradle.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/BuildOperationCrossProjectConfiguratorTest.groovy
Labels: a:feature, from:member

#6471 Replace `tasks.named(n).configureAs<T> {}` by `tasks.named<T>(n) {}`
  buildSrc/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/kotlin-dsl-upstream.kt
  subprojects/build-comparison/build-comparison.gradle.kts
  subprojects/dependency-management/dependency-management.gradle.kts
  subprojects/internal-performance-testing/internal-performance-testing.gradle.kts
  subprojects/runtime-api-info/runtime-api-info.gradle.kts
  subprojects/tooling-api/tooling-api.gradle.kts
Labels: a:chore, from:member, in:gradle-build

#6122 Improve performance test
  buildSrc/subprojects/performance/src/main/groovy/org/gradle/testing/DistributedPerformanceTest.groovy
  buildSrc/subprojects/performance/src/main/groovy/org/gradle/testing/PerformanceTest.java
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/performance/PerformanceTestPlugin.kt
  subprojects/build-scan-performance/build-scan-performance.gradle
Labels: a:chore, dev-productivity, from:member

#6473 Remove getting-started.html as input
  buildSrc/subprojects/build/src/main/groovy/org/gradle/build/GradleDistribution.groovy
Labels: from:member, in:gradle-build

#6466 Update userguide for strict runtime API validation
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/more_about_tasks.adoc
Labels: from:member

#6418 Reduce overhead of artifact transform listeners
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformArtifactOperation.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformFileOperation.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/TransformingAsyncArtifactListenerTest.groovy
  subprojects/messaging/src/main/java/org/gradle/internal/event/DefaultListenerManager.java
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidStudioMockupPerformanceTest.groovy
Labels: from:member

#6469 Guard against broken incremental compile caches
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/SourceIncrementalJavaCompilationIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/classpath/ClasspathEntrySnapshotCache.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/classpath/DefaultClasspathEntrySnapshotCache.java
Labels: a:bug, from:member, in:jvm-platform

#6311 Prepare for Gradle 5.0
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/internal/WrapperPluginAutoApplyActionIntegTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginMultiProjectTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginVersionIntegrationTest.groovy
  subprojects/core-api/src/main/java/org/gradle/api/DomainObjectCollection.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/MutableVersionConstraint.java
  subprojects/core/src/integTest/groovy/org/gradle/NameValidationIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/DeferredConfigurableExtensionIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/file/FileProvidersIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/provider/PropertyIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/options/InternalTaskOptionApiIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/groovy/scripts/GradleUtilDefaultImportDeprecationIntegrationTest.groovy
  subprojects/core/src/test/groovy/org/gradle/util/NameValidatorTest.groovy
  subprojects/ide/src/crossVersionTest/groovy/org/gradle/plugins/ide/tooling/r50/ToolingApiIdeaModelCrossVersionSpec.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/GradleKotlinDslIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/ProjectLoadingIntegrationTest.java
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskDefinitionIntegrationTest.groovy
  subprojects/logging/src/integTest/groovy/org/gradle/DeprecatedUsageBuildOperationProgressIntegrationTest.groovy
  subprojects/model-core/src/main/java/org/gradle/api/reflect/TypeOf.java
  subprojects/plugins/src/test/groovy/org/gradle/api/internal/tasks/DefaultSourceSetContainerTest.groovy
  subprojects/reporting/src/integTest/groovy/org/gradle/api/reporting/internal/TaskGeneratedReportIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestTaskIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestingIntegrationTest.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r42/ToolingApiDeprecatedBuildJvmCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r43/ToolingApiVersionSpecification.groovy
  version.txt
Labels: a:chore, from:member, in:core

#6465 Recompile when a resource file changes
  subprojects/docs/src/docs/userguide/java_plugin.adoc
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/AbstractIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/AggregatingIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/IsolatingIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/SourceIncrementalJavaCompilationIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/InputChangeAction.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/RecompilationSpecProvider.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/ResourceChangeProcessor.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/IncrementalProcessingStrategy.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/processing/IncrementalFilerTest.groovy
Labels: from:member

#6477 Disallow build scan plugin < 1.13
  subprojects/core/src/integTest/groovy/org/gradle/internal/scan/config/BuildScanConfigIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/internal/scan/config/BuildScanPluginCompatibility.java
  subprojects/core/src/test/groovy/org/gradle/internal/scan/config/BuildScanConfigManagerTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/BuildScanPluginSmokeTest.groovy
Labels: from:member

#6468 Remove JvmLanguageCompileSpec.{source,classpath}
  subprojects/language-jvm/src/main/java/org/gradle/api/internal/tasks/compile/DefaultJvmLanguageCompileSpec.java
  subprojects/language-jvm/src/main/java/org/gradle/api/internal/tasks/compile/JvmLanguageCompileSpec.java
Labels: from:member

#6444 Detect port in use befor JDWP tests
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/debug/JDWPUtil.groovy
Labels: a:chore, dev-productivity, from:member

#6480 Document build operations categories
  subprojects/base-services/src/main/java/org/gradle/internal/operations/BuildOperationCategory.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradleLauncher.java
  subprojects/logging/src/main/java/org/gradle/internal/logging/console/BuildStatusRenderer.java
  subprojects/logging/src/test/groovy/org/gradle/internal/logging/console/BuildStatusRendererTest.groovy
Labels: from:member

#6419 Fix Jacoco to work with build cache
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/jacoco_plugin.adoc
  subprojects/docs/src/samples/testing/jacoco/quickstart/build.gradle
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoCachingIntegrationTest.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoPluginIntegrationTest.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoPluginMultiVersionIntegrationTest.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoReportFixture.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoTestRelocationIntegrationTest.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/fixtures/JavaProjectUnderTest.groovy
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoPluginExtension.java
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoTaskExtension.java
  subprojects/logging/src/main/java/org/gradle/util/SingleMessageLogger.java
Labels: from:member

#6463 Create own build type for compileAll
  build.gradle.kts
Labels: in:gradle-build

#6498 fix: remove the double "Example" prefix in base_plugin doc
  subprojects/docs/src/docs/userguide/base_plugin.adoc
Labels: from:contributor, in:docs

#6484 Fix double "Example"
  subprojects/docs/src/docs/userguide/gradle_wrapper.adoc
Labels: from:contributor, in:docs

#6499 Platform edges shouldn't be transitive
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/alignment/AlignmentIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/LenientPlatformDependencyMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/PotentialEdge.java
Labels: a:bug, in:dependency-management

#6455 Make FileUtils#calculateRoots more efficient
  subprojects/base-services/src/main/java/org/gradle/internal/FileUtils.java
  subprojects/base-services/src/test/groovy/org/gradle/internal/FileUtilsTest.groovy
  subprojects/docs/src/docs/release/notes.md
Labels: a:performance-issue, from:member, in:core

#6449 Set mirror for all repositories
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/settings.gradle.kts
  gradle/shared-with-buildSrc/mirrors.gradle.kts
  gradle/shared-with-buildSrc/mirrors.settings.gradle.kts
  settings.gradle.kts
Labels: a:chore, dev-productivity, from:member

#6502 Minor code changes to improve performance
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/oldresult/ResolutionFailureCollector.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/DefaultResolutionResultBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/StreamingResolutionResultBuilder.java
Labels: from:member, in:dependency-management

#6506 Silence kotlin-dsl warning
  buildSrc/build.gradle.kts
Labels: a:chore, from:member, in:gradle-build

#6494 Remove dependency on Java 7 in our build
  build.gradle.kts
  buildSrc/subprojects/buildquality/buildquality.gradle.kts
  buildSrc/subprojects/buildquality/src/main/kotlin/org/gradle/gradlebuild/buildquality/AddVerifyProductionEnvironmentTaskPlugin.kt
  buildSrc/subprojects/buildquality/src/main/kotlin/org/gradle/gradlebuild/buildquality/VerifyBuildEnvironmentPlugin.kt
  buildSrc/subprojects/configuration/src/main/kotlin/org/gradle/gradlebuild/java/AvailableJavaInstallations.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/gradlebuild/unittestandcompile/UnitTestAndCompilePlugin.kt
  subprojects/base-services/base-services.gradle.kts
  subprojects/base-services/src/main/java/org/gradle/internal/hash/Hashing.java
  subprojects/base-services/src/main/java/org/gradle/internal/io/BufferCaster.java
  subprojects/base-services/src/main/java/org/gradle/internal/io/StreamByteBuffer.java
  subprojects/language-java/language-java.gradle
  subprojects/launcher/launcher.gradle
  subprojects/messaging/src/main/java/org/gradle/internal/remote/internal/inet/SocketConnection.java
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/inception/GradleBuildPerformanceTest.groovy
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaInstallationProbe.java
Labels: a:chore, dev-productivity, from:member

#6533 Make `CopySpec#duplicatesStrategy` representable in Kotlin as a mutable non-null property
  subprojects/core-api/src/main/java/org/gradle/api/file/CopySpec.java
  subprojects/core-api/src/main/java/org/gradle/api/file/DuplicatesStrategy.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/CopySpecWrapper.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DelegatingCopySpecInternal.java
  subprojects/core/src/main/java/org/gradle/api/tasks/AbstractCopyTask.java
  subprojects/docs/src/docs/release/notes.md
Labels: a:feature, from:member, in:core

#6507 Ensure plugin bootstrapping in composites works without workarounds
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildPluginDevelopmentIntegrationTest.groovy
Labels: a:chore, from:member, in:composite-builds

#6503 Handle Java lambdas as task inputs.
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedCustomTaskExecutionIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedTaskExecutionIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/LambdaInputsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/NestedInputIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/AbstractTask.java
  subprojects/core/src/main/java/org/gradle/api/internal/TaskOutputsInternal.java
  subprojects/core/src/main/java/org/gradle/api/internal/attributes/AttributeDefinitionSnapshot.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/rules/TaskTypeTaskStateChanges.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/CacheBackedTaskHistoryRepository.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/ImplementationSnapshot.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/SnapshotSerializer.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/TaskExecutionFingerprintSerializer.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/ValueSnapshotter.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/taskfactory/StandardTaskAction.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/ContextAwareTaskAction.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskOutputs.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/ImplementationAwareTaskAction.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskMutator.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskOutputCachingDisabledReasonCategory.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/ResolveBuildCacheKeyExecuter.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/ResolveTaskOutputCachingStateExecuter.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/SkipCachedTaskExecuter.java
  subprojects/core/src/main/java/org/gradle/caching/internal/tasks/DebuggingTaskOutputCachingBuildCacheKeyBuilder.java
  subprojects/core/src/main/java/org/gradle/caching/internal/tasks/DefaultTaskOutputCachingBuildCacheKeyBuilder.java
  subprojects/core/src/main/java/org/gradle/caching/internal/tasks/TaskCacheKeyCalculator.java
  subprojects/core/src/main/java/org/gradle/caching/internal/tasks/TaskOutputCachingBuildCacheKeyBuilder.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/changedetection/rules/TaskTypeTaskStateChangesTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/changedetection/state/ImplementationSnapshotTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/changedetection/state/InputPropertiesSerializerTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/DefaultTaskOutputsTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ResolveTaskOutputCachingStateExecuterTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/SkipCachedTaskExecuterTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/tasks/AbstractCopyTaskTest.groovy
  subprojects/docs/src/docs/userguide/more_about_tasks.adoc
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/NestedInputKotlinImplementationTrackingIntegrationTest.groovy
Labels: from:member

#6553 Enable Kotlin build scripts build-cache
  buildSrc/gradle.properties
  gradle.properties
Labels: from:member, in:gradle-build

#6548 Fix broken links in Working With Files chapter
  subprojects/docs/src/docs/userguide/working_with_files.adoc
Labels: from:contributor, in:docs

#6516 Allow plural outputs to be cached
  subprojects/core-api/src/main/java/org/gradle/api/tasks/OutputDirectories.java
  subprojects/core-api/src/main/java/org/gradle/api/tasks/OutputFiles.java
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/tasks/TaskCacheabilityReasonIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedCustomTaskExecutionIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/CompositeTaskOutputPropertySpec.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskOutputs.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/NonCacheableTaskOutputPropertySpec.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskOutputCachingDisabledReasonCategory.java
  subprojects/core/src/main/java/org/gradle/internal/snapshot/impl/DefaultFileSystemSnapshotter.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/AbstractFileCollectionTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/AbstractFileTreeTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/CompositeFileCollectionSpec.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/DefaultTaskOutputsTest.groovy
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/more_about_tasks.adoc
  subprojects/files/src/main/java/org/gradle/api/internal/file/AbstractFileCollection.java
  subprojects/files/src/main/java/org/gradle/api/internal/file/AbstractFileTree.java
  subprojects/files/src/main/java/org/gradle/api/internal/file/CompositeFileCollection.java
  subprojects/files/src/main/java/org/gradle/api/internal/file/FileCollectionInternal.java
  subprojects/files/src/main/java/org/gradle/api/internal/file/FileCollectionLeafVisitor.java
  subprojects/files/src/main/java/org/gradle/api/internal/file/collections/FileTreeAdapter.java
  subprojects/files/src/test/groovy/org/gradle/api/internal/file/collections/FileTreeAdapterTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/CompilationSourceDirs.java
Labels: from:member, in:build-cache

#6490 Fix two broken links to old documentation pages
  subprojects/testing-base/src/integTest/groovy/org/gradle/testing/SecurityManagerIntegrationTest.groovy
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/ForkingTestClassProcessor.java
Labels: from:contributor, in:docs

#6559 include Kotlin DSL sample for chapter artifact_management
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/artifact_management.adoc
  subprojects/docs/src/samples/userguide/artifacts/uploading/archiveTaskArtifact.sample.conf
  subprojects/docs/src/samples/userguide/artifacts/uploading/groovy/build.gradle
  subprojects/docs/src/samples/userguide/artifacts/uploading/groovy/settings.gradle
  subprojects/docs/src/samples/userguide/artifacts/uploading/kotlin/build.gradle.kts
  subprojects/docs/src/samples/userguide/artifacts/uploading/kotlin/settings.gradle.kts
Labels: from:contributor, in:docs

#6569 include Kotlin DSL sample for chapter idea_plugin
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/idea_plugin.adoc
  subprojects/docs/src/samples/idea/groovy/build.gradle
  subprojects/docs/src/samples/idea/groovy/settings.gradle
  subprojects/docs/src/samples/idea/kotlin/build.gradle.kts
  subprojects/docs/src/samples/idea/kotlin/settings.gradle.kts
  subprojects/docs/src/samples/idea/projectWithXml.sample.conf
Labels: from:contributor, in:docs

#6556 include Kotlin DSL sample for chapter application_plugin
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/application_plugin.adoc
  subprojects/docs/src/samples/application/build.gradle
  subprojects/docs/src/samples/application/dependentTaskForApplicationDistributionOutput.sample.conf
  subprojects/docs/src/samples/application/groovy/build.gradle
  subprojects/docs/src/samples/application/groovy/settings.gradle
  subprojects/docs/src/samples/application/groovy/src/dist/LICENSE
  subprojects/docs/src/samples/application/groovy/src/main/java/org/gradle/sample/Main.java
  subprojects/docs/src/samples/application/kotlin/build.gradle.kts
  subprojects/docs/src/samples/application/kotlin/settings.gradle.kts
  subprojects/docs/src/samples/application/kotlin/src/dist/LICENSE
  subprojects/docs/src/samples/application/kotlin/src/main/java/org/gradle/sample/Main.java
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/samples/SamplesApplicationIntegrationTest.groovy
Labels: from:contributor, in:docs

#6542 Include Kotlin DSL samples in build_environment chapter
  subprojects/docs/src/docs/userguide/build_environment.adoc
  subprojects/docs/src/samples/userguide/buildEnvironment/javaCompileOptions/groovy/build.gradle
  subprojects/docs/src/samples/userguide/buildEnvironment/javaCompileOptions/groovy/settings.gradle
  subprojects/docs/src/samples/userguide/buildEnvironment/javaCompileOptions/javaCompileOptions.sample.conf
  subprojects/docs/src/samples/userguide/buildEnvironment/javaCompileOptions/kotlin/build.gradle.kts
  subprojects/docs/src/samples/userguide/buildEnvironment/javaCompileOptions/kotlin/settings.gradle.kts
  subprojects/docs/src/samples/userguide/tutorial/configureTaskUsingProjectProperty/configureTaskUsingProjectProperty.sample.conf
  subprojects/docs/src/samples/userguide/tutorial/configureTaskUsingProjectProperty/groovy/build.gradle
  subprojects/docs/src/samples/userguide/tutorial/configureTaskUsingProjectProperty/groovy/settings.gradle
  subprojects/docs/src/samples/userguide/tutorial/configureTaskUsingProjectProperty/kotlin/build.gradle.kts
  subprojects/docs/src/samples/userguide/tutorial/configureTaskUsingProjectProperty/kotlin/settings.gradle.kts
  subprojects/docs/src/samples/userguide/tutorial/properties/groovy/build.gradle
  subprojects/docs/src/samples/userguide/tutorial/properties/groovy/gradle.properties
  subprojects/docs/src/samples/userguide/tutorial/properties/groovy/settings.gradle
  subprojects/docs/src/samples/userguide/tutorial/properties/kotlin/build.gradle.kts
  subprojects/docs/src/samples/userguide/tutorial/properties/kotlin/gradle.properties
  subprojects/docs/src/samples/userguide/tutorial/properties/kotlin/settings.gradle.kts
  subprojects/docs/src/samples/userguide/tutorial/properties/properties.sample.conf
  subprojects/docs/src/samples/userguide/tutorial/properties/settings.gradle
Labels: from:member, in:docs

#6512 Include Kotlin DSL samples for chapter dependency_management_for_java_projects
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/dependency_management_for_java_projects.adoc
  subprojects/docs/src/docs/userguide/dependency_types.adoc
  subprojects/docs/src/docs/userguide/repository_types.adoc
  subprojects/docs/src/samples/userguide/artifacts/defineRepository/defineMavenCentral.sample.conf
  subprojects/docs/src/samples/userguide/artifacts/defineRepository/groovy/build.gradle
  subprojects/docs/src/samples/userguide/artifacts/defineRepository/groovy/settings.gradle
  subprojects/docs/src/samples/userguide/artifacts/defineRepository/kotlin/build.gradle.kts
  subprojects/docs/src/samples/userguide/artifacts/defineRepository/kotlin/settings.gradle.kts
  subprojects/docs/src/samples/userguide/artifacts/dependencyBasics/basicDependencyDeclarations.sample.conf
  subprojects/docs/src/samples/userguide/artifacts/dependencyBasics/groovy/build.gradle
  subprojects/docs/src/samples/userguide/artifacts/dependencyBasics/groovy/settings.gradle
  subprojects/docs/src/samples/userguide/artifacts/dependencyBasics/kotlin/build.gradle.kts
  subprojects/docs/src/samples/userguide/artifacts/dependencyBasics/kotlin/settings.gradle.kts
  subprojects/docs/src/samples/userguide/artifacts/externalDependencies/externalDependencies.sample.conf
  subprojects/docs/src/samples/userguide/artifacts/externalDependencies/groovy/build.gradle
  subprojects/docs/src/samples/userguide/artifacts/externalDependencies/groovy/settings.gradle
  subprojects/docs/src/samples/userguide/artifacts/externalDependencies/kotlin/build.gradle.kts
  subprojects/docs/src/samples/userguide/artifacts/externalDependencies/kotlin/settings.gradle.kts
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/samples/SamplesRepositoriesIntegrationTest.groovy
Labels: from:contributor, in:docs

#6413 Update build instructions for JDK 9 requirement
  CONTRIBUTING.md
Labels: from:member, in:docs

#6570 Polish build scripts and plugins
  buildSrc/subprojects/buildquality/src/main/kotlin/org/gradle/gradlebuild/buildquality/TaskPropertyValidationPlugin.kt
  buildSrc/subprojects/cleanup/src/main/kotlin/org/gradle/gradlebuild/testing/integrationtests/cleanup/CleanupPlugin.kt
  buildSrc/subprojects/cleanup/src/main/kotlin/org/gradle/gradlebuild/testing/integrationtests/cleanup/EmptyDirectoryCheck.kt
  buildSrc/subprojects/cleanup/src/main/kotlin/org/gradle/gradlebuild/testing/integrationtests/cleanup/TestFileCleanUpExtension.kt
  buildSrc/subprojects/cleanup/src/main/kotlin/org/gradle/gradlebuild/testing/integrationtests/cleanup/TestFilesCleanUpPlugin.kt
  buildSrc/subprojects/configuration/src/main/kotlin/org/gradle/gradlebuild/dependencies/DependenciesMetadataRulesPlugin.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/fixtures/IntTestImagePlugin.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/fixtures/TestFixturesPlugin.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/IntegrationTest.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/IntegrationTestsPlugin.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/shared-configuration.kt
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/ApiMetadataPlugin.kt
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/MinifyPlugin.kt
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/ShadedJarPlugin.kt
  buildSrc/subprojects/plugins/src/main/kotlin/gradlebuild/publish-public-libraries.gradle.kts
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/gradlebuild/unittestandcompile/UnitTestAndCompilePlugin.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/buildtypes/BuildTypesPlugin.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/performance/PerformanceTestPlugin.kt
  buildSrc/subprojects/profiling/src/main/kotlin/org/gradle/gradlebuild/profiling/buildscan/BuildScanPlugin.kt
  buildSrc/subprojects/versioning/src/main/kotlin/org/gradle/gradlebuild/versioning/UpdateVersionsPlugin.kt
  buildSrc/subprojects/versioning/src/main/kotlin/org/gradle/gradlebuild/versioning/WrapperPlugin.kt
  subprojects/build-comparison/build-comparison.gradle.kts
Labels: a:feature, dogfood:kotlin-dsl, from:member, in:gradle-build

#6551 Support type-safe configuration for Checkstyle/FindBugs HTML report stylesheet
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CheckstyleReports.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/FindBugsReports.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/CheckstyleReportsImpl.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/FindBugsReportsImpl.java
  subprojects/distributions/src/changes/accepted-public-api-changes.json
  subprojects/docs/src/docs/release/notes.md
Labels: a:feature, from:contributor, in:checkstyle-plugin, in:findbugs-plugin

#6581 Name task correctly for example
  subprojects/docs/src/docs/userguide/more_about_tasks.adoc
Labels: from:contributor, in:docs

#6579 Introduce `AutoAppliedBuildScanPlugin#addBuildScanPluginDependencySpecTo`
  subprojects/core/src/main/java/org/gradle/plugin/management/internal/autoapply/AutoAppliedBuildScanPlugin.java
Labels: a:feature, from:member, in:core

#6583 Deincubate both plugins {} and pluginManagement {} blocks
  subprojects/core-api/src/main/java/org/gradle/plugin/management/PluginManagementSpec.java
  subprojects/core-api/src/main/java/org/gradle/plugin/management/PluginRequest.java
  subprojects/core-api/src/main/java/org/gradle/plugin/management/PluginResolutionStrategy.java
  subprojects/core-api/src/main/java/org/gradle/plugin/management/PluginResolveDetails.java
  subprojects/core-api/src/main/java/org/gradle/plugin/management/package-info.java
  subprojects/core-api/src/main/java/org/gradle/plugin/use/PluginDependenciesSpec.java
  subprojects/core-api/src/main/java/org/gradle/plugin/use/PluginDependencySpec.java
  subprojects/core-api/src/main/java/org/gradle/plugin/use/PluginId.java
  subprojects/core-api/src/main/java/org/gradle/plugin/use/package-info.java
  subprojects/docs/src/docs/userguide/custom_plugins.adoc
  subprojects/docs/src/docs/userguide/plugins.adoc
Labels: from:member, in:plugin-management
