Repository gradle/gradle, pull requests merged in 2019-09, with the labels that each got.

#10304 Allow init scripts to apply plugins to settings
  subprojects/core-api/src/main/java/org/gradle/BuildAdapter.java
  subprojects/core-api/src/main/java/org/gradle/BuildListener.java
  subprojects/core-api/src/main/java/org/gradle/api/invocation/Gradle.java
  subprojects/core/src/integTest/groovy/org/gradle/configuration/ExecuteUserLifecycleListenerBuildOperationIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/InitScriptIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/configuration/internal/DefaultListenerBuildOperationDecorator.java
  subprojects/core/src/main/java/org/gradle/initialization/ScriptEvaluatingSettingsProcessor.java
  subprojects/core/src/main/java/org/gradle/invocation/DefaultGradle.java
  subprojects/core/src/test/groovy/org/gradle/configuration/internal/DefaultListenerBuildOperationDecoratorTest.groovy
  subprojects/core/src/test/groovy/org/gradle/invocation/DefaultGradleSpec.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/plugin/PluginBuilder.groovy
Labels: a:feature, from:member

#10305 Build buildSrc after applying the settings file
  subprojects/base-services/src/main/java/org/gradle/internal/classloader/ConfigurableClassLoaderHierarchyHasher.java
  subprojects/base-services/src/main/java/org/gradle/internal/classloader/DeprecatedClassloader.java
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildBuildSrcBuildOperationsIntegrationTest.groovy
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildBuildSrcIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/CrossBuildScriptCachingIntegrationSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/SettingsPluginIntegrationSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/SettingsScriptExecutionIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedImplementationIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/caching/configuration/internal/BuildCacheCompositeConfigurationIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/BuildInitializationBuildOperationsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/buildsrc/BuildSrcDeprecatedInSettingsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/buildsrc/BuildSrcVisibilityIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/GradleInternal.java
  subprojects/core/src/main/java/org/gradle/api/internal/SettingsInternal.java
  subprojects/core/src/main/java/org/gradle/api/internal/initialization/ClassLoaderScope.java
  subprojects/core/src/main/java/org/gradle/api/internal/initialization/DefaultClassLoaderScope.java
  subprojects/core/src/main/java/org/gradle/api/internal/initialization/DefaultDeprecatedClassLoader.java
  subprojects/core/src/main/java/org/gradle/api/internal/initialization/DefaultScriptHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/initialization/DeprecatedClassLoaderScope.java
  subprojects/core/src/main/java/org/gradle/api/internal/initialization/RootClassLoaderScope.java
  subprojects/core/src/main/java/org/gradle/api/internal/initialization/ScriptHandlerInternal.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/IProjectFactory.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/ProjectFactory.java
  subprojects/core/src/main/java/org/gradle/caching/internal/services/BuildCacheServices.java
  subprojects/core/src/main/java/org/gradle/configuration/DefaultProjectsPreparer.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradleLauncher.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradleLauncherFactory.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultSettings.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultSettingsLoader.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultSettingsLoaderFactory.java
  subprojects/core/src/main/java/org/gradle/initialization/InstantiatingBuildLoader.java
  subprojects/core/src/main/java/org/gradle/initialization/ScriptEvaluatingSettingsProcessor.java
  subprojects/core/src/main/java/org/gradle/initialization/SettingsFactory.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/BuildScopeServices.java
  subprojects/core/src/main/java/org/gradle/invocation/DefaultGradle.java
  subprojects/core/src/main/java/org/gradle/testfixtures/internal/ProjectBuilderImpl.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/initialization/DefaultDeprecatedClassLoaderTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/ProjectFactoryTest.groovy
  subprojects/core/src/test/groovy/org/gradle/initialization/DefaultGradleLauncherSpec.groovy
  subprojects/core/src/test/groovy/org/gradle/initialization/DefaultSettingsLoaderTest.groovy
  subprojects/core/src/test/groovy/org/gradle/initialization/InstantiatingBuildLoaderTest.groovy
  subprojects/core/src/test/groovy/org/gradle/initialization/SettingsFactoryTest.groovy
  subprojects/docs/src/docs/userguide/upgrading_version_5.adoc
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/InstantExecutionHost.kt
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/internal/scan/config/fixtures/BuildScanPluginFixture.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/plugin/PluginBuilder.groovy
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/GradleKotlinDslIntegrationTest.kt
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/precompiled/PrecompiledScriptPluginTemplatesTest.kt
  subprojects/kotlin-dsl-tooling-builders/src/crossVersionTest/groovy/org/gradle/kotlin/dsl/tooling/builders/AbstractKotlinScriptModelCrossVersionTest.groovy
  subprojects/kotlin-dsl-tooling-builders/src/crossVersionTest/groovy/org/gradle/kotlin/dsl/tooling/builders/r54/KotlinSettingsScriptModelCrossVersionSpec.groovy
  subprojects/kotlin-dsl-tooling-builders/src/main/kotlin/org/gradle/kotlin/dsl/tooling/builders/KotlinBuildScriptModelBuilder.kt
  subprojects/kotlin-dsl/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/KotlinSettingsScriptIntegrationTest.kt
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/AbstractConsoleBuildPhaseFunctionalTest.groovy
  subprojects/version-control/src/integTest/groovy/org/gradle/vcs/internal/AbstractSourceDependencyIntegrationTest.groovy
  subprojects/version-control/src/integTest/groovy/org/gradle/vcs/internal/NestedSourceDependencyIntegrationTest.groovy
Labels: a:feature, from:member

#10423 Detect removed methods only in public superclass
  buildSrc/subprojects/binary-compatibility/src/main/groovy/org/gradle/binarycompatibility/rules/MethodsRemovedInInternalSuperClassRule.groovy
  buildSrc/subprojects/binary-compatibility/src/test/groovy/org/gradle/binarycompatibility/rules/AbstractContextAwareRuleSpecification.groovy
  buildSrc/subprojects/binary-compatibility/src/test/groovy/org/gradle/binarycompatibility/rules/MethodsRemovedInInternalSuperClassRuleTest.groovy
  subprojects/distributions/src/changes/accepted-public-api-changes.json
Labels: @build-cache, from:member

#10426 Allow collection properties to be added to containers
  subprojects/core/src/test/groovy/org/gradle/api/internal/AbstractDomainObjectCollectionSpec.groovy
  subprojects/docs/src/docs/release/notes.md
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/CollectionPropertyInternal.java
Labels: @core, a:bug, from:member, in:core

#10424 Update AGP nightly to the latest in instant execution integ tests
  subprojects/instant-execution/instant-execution.gradle.kts
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/AbstractInstantExecutionAndroidIntegrationTest.groovy
Labels: a:chore, in:instant-execution

#10267 Use input changes in JavaCompile
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/tasks/SnapshotTaskInputsOperationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/project/taskfactory/BridgingIncrementalInputsTaskAction.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/taskfactory/DefaultTaskClassInfoStore.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/taskfactory/AnnotationProcessingTaskFactoryTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/taskfactory/AnnotationProcessingTasks.java
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/FileCollectionCodec.kt
  subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/GroovyServices.java
  subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java
  subprojects/language-groovy/src/main/resources/META-INF/services/org.gradle.internal.service.scopes.PluginServiceRegistry
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/UnknownIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractSourceIncrementalCompilationIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/GroovyJavaJointIncrementalCompilationIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/GroovySourceIncrementalCompilationIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/JavaSourceIncrementalCompilationIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AnnotationProcessorChangeProcessor.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/GroovyRecompilationSpecProvider.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/InputChangeAction.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/JavaConventionalSourceFileClassNameConverter.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/JavaRecompilationSpecProvider.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/ResourceChangeProcessor.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/incremental/recomp/CompilationSourceDirsTest.groovy
Labels: @build-cache, from:member

#10434 Introduce public api FileSystemOperations service
  subprojects/core-api/src/main/java/org/gradle/api/file/FileSystemOperations.java
  subprojects/core-api/src/main/java/org/gradle/api/model/ObjectFactory.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/DefaultFileSystemOperations.java
  subprojects/core/src/main/java/org/gradle/api/internal/model/DefaultObjectFactory.java
  subprojects/core/src/main/java/org/gradle/api/internal/model/InstantiatorBackedObjectFactory.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/ProjectScopeServices.java
  subprojects/distributions/src/changes/accepted-public-api-changes.json
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionIntegrationTest.groovy
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/Codecs.kt
  subprojects/language-native/src/main/java/org/gradle/language/cpp/plugins/CppLibraryPlugin.java
  subprojects/language-native/src/main/java/org/gradle/language/swift/plugins/SwiftApplicationPlugin.java
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/tasks/InstallExecutable.java
  subprojects/platform-play/src/main/java/org/gradle/play/tasks/JavaScriptMinify.java
  subprojects/testing-native/src/main/java/org/gradle/nativeplatform/test/xctest/tasks/InstallXCTestBundle.java
Labels: @instant-execution, a:feature, from:member

#10441 Remove and ignore .teamcity iml file
  .gitignore
  .teamcity/Gradle_Check_dsl.iml
Labels: @dev-productivity, from:member

#10402 Add detection of long command line on Windows
  subprojects/core/src/main/java/org/gradle/process/internal/DefaultExecHandle.java
  subprojects/core/src/main/java/org/gradle/process/internal/util/LongCommandLineDetectionUtil.java
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecIntegrationTest.groovy
Labels: @core, a:feature, from:member, in:core

#10436 Properties are rehydrated with the proper provided type
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/ManagedFactories.java
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerExecutorNestingIntegrationTest.groovy
  subprojects/workers/src/testFixtures/groovy/org/gradle/workers/fixtures/WorkerExecutorFixture.groovy
Labels: @core, a:bug, affects-version:5.6, from:member, in:core

#10447 Use InputChanges in AntlrTask
  subprojects/antlr/src/integTest/groovy/org/gradle/api/plugins/antlr/IncrementalAntlrTaskIntegrationTest.groovy
  subprojects/antlr/src/main/java/org/gradle/api/plugins/antlr/AntlrTask.java
  subprojects/distributions/src/changes/accepted-public-api-changes.json
Labels: @build-cache, from:member

#10444 Mark tasks as did work even when all they did was remove stale output
  subprojects/core-api/src/main/java/org/gradle/api/tasks/WorkResult.java
  subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/CleaningGroovyCompiler.java
  subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/CleaningJavaCompiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/CleaningJavaCompilerSupport.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/IncrementalCompilerDecorator.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/IncrementalCompilerFactory.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/SelectiveCompiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/GroovyRecompilationSpecProvider.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/JavaRecompilationSpecProvider.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/RecompilationSpecProvider.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
  subprojects/language-jvm/src/main/java/org/gradle/language/jvm/tasks/ProcessResources.java
  subprojects/language-native/src/main/java/org/gradle/language/assembler/tasks/Assemble.java
  subprojects/language-native/src/main/java/org/gradle/language/nativeplatform/internal/incremental/IncrementalNativeCompiler.java
  subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/CleaningScalaCompiler.java
  subprojects/language-scala/src/main/java/org/gradle/language/scala/tasks/AbstractScalaCompile.java
  subprojects/platform-base/src/main/java/org/gradle/language/base/internal/tasks/SimpleStaleClassCleaner.java
  subprojects/platform-base/src/main/java/org/gradle/language/base/internal/tasks/StaleClassCleaner.java
  subprojects/platform-base/src/main/java/org/gradle/language/base/internal/tasks/StaleOutputCleaner.java
  subprojects/platform-base/src/test/groovy/org/gradle/language/base/internal/tasks/StaleOutputCleanerTest.groovy
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/tasks/AbstractLinkTask.java
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/swift/IncrementalSwiftCompiler.java
  subprojects/platform-play/src/main/java/org/gradle/play/internal/CleaningPlayToolCompiler.java
  subprojects/platform-play/src/main/java/org/gradle/play/tasks/JavaScriptMinify.java
  subprojects/platform-play/src/main/java/org/gradle/play/tasks/PlayCoffeeScriptCompile.java
  subprojects/scala/src/test/groovy/org/gradle/api/tasks/scala/ScalaCompileTest.groovy
Labels: @build-cache, from:member

#10435 Add build cache training promotion link to selected docs
  subprojects/docs/src/docs/userguide/build_cache.adoc
  subprojects/docs/src/docs/userguide/build_environment.adoc
  subprojects/docs/src/docs/userguide/intro_multi_project_builds.adoc
  subprojects/docs/src/docs/userguide/migrating_from_maven.adoc
  subprojects/docs/src/docs/userguide/userguide.adoc
Labels: @build-cache

#10449 Remove empty subproject build configuration
  .teamcity/Gradle_Check/model/CIBuildModel.kt
Labels: @dev-productivity, a:chore, from:member

#10445 Work around AGP static state in instant execution
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionSantaTrackerIntegrationTest.groovy
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/Contexts.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/Workarounds.kt
Labels: from:member, in:instant-execution

#10440 Allow resolving fixed file collections from a Directory or DirectoryProperty
  subprojects/core-api/src/main/java/org/gradle/api/file/Directory.java
  subprojects/core-api/src/main/java/org/gradle/api/file/DirectoryProperty.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/DefaultFilePropertyFactory.java
  subprojects/file-collections/src/test/groovy/org/gradle/api/internal/file/DirectoryPropertyTest.groovy
Labels: @instant-execution, a:feature, from:member, in:core

#10450 Clean up ivy publication and publish more information to ivy.xml metadata
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/RepositoryInteractionDependencyResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ivy/ComponentSelectionRulesDependencyResolveIntegTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ivy/IvyDescriptorDependencyExcludeResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/DependencyMetadataRulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/VariantAttributesRulesIntegrationTest.groovy
  subprojects/docs/src/samples/ivy-publish/java-multi-project/output-ivy.xml
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/ivy/IvyDescriptor.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/ivy/IvyDescriptorDependency.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/ivy/IvyFileModule.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/ivy/IvyJavaModule.groovy
  subprojects/internal-integ-testing/src/test/groovy/org/gradle/test/fixtures/ivy/IvyDescriptorDependencyTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyPublishCoordinatesIntegTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyPublishDescriptorCustomizationIntegTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyPublishJavaIntegTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/IvyPublishResolvedVersionsJavaIntegTest.groovy
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publication/DefaultIvyPublication.java
Labels: from:member, in:dependency-management, in:publishing-plugin

#10459 Remove caching being disabled when TaskOutputs.files/dirs() is used
  subprojects/core-api/src/main/java/org/gradle/api/tasks/TaskOutputs.java
Labels: @build-cache, from:member

#10453 Ignore property methods annotated with `@ReplacedBy`
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/ModifierAnnotationCategory.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/ExecutionGlobalServices.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/taskfactory/AnnotationProcessingTaskFactoryTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/DefaultTaskInputsTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/DefaultTaskOutputsTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/DefaultPropertyWalkerTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/DefaultTypeMetadataStoreTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/InspectionSchemeFactoryTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/annotations/TaskAnnotations.groovy
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/AnnotationCategory.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/annotations/impl/DefaultTypeAnnotationMetadataStore.java
  subprojects/model-core/src/test/groovy/org/gradle/internal/reflect/annotations/impl/DefaultTypeAnnotationMetadataStoreTest.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidateTaskPropertiesIntegrationTest.groovy
Labels: @build-cache, from:member

#10460 No `@Optional` on method parameters
  subprojects/core-api/src/main/java/org/gradle/api/tasks/Optional.java
  subprojects/core/src/main/java/org/gradle/api/internal/artifacts/ExcludeRuleNotationConverter.java
  subprojects/core/src/main/java/org/gradle/internal/typeconversion/MapNotationConverter.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/artifacts/DefaultExcludeRuleContainerTest.java
  subprojects/core/src/test/groovy/org/gradle/internal/typeconversion/MapNotationConverterTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/CapabilityNotationParserFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/notations/DependencyMapNotationConverter.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/notations/ProjectDependencyFactory.java
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/internal/resolve/NativeDependencyNotationParser.java
  subprojects/platform-play/src/main/java/org/gradle/play/internal/PlayPlatformNotationParser.java
Labels: @build-cache, from:member

#10479 Always register optional features for publishing
  subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/AbstractIvyPublishFeaturesJavaIntegTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyPublishFeaturesJavaIntegTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyPublishFeaturesJavaPluginIntegTest.groovy
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publication/DefaultIvyPublication.java
  subprojects/ivy/src/testFixtures/groovy/org/gradle/api/publish/ivy/AbstractIvyPublishIntegTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/DefaultJavaFeatureSpec.java
Labels: from:member, in:dependency-management

#10486 Remove SourceSetOutput.legacyLayout
  subprojects/docs/src/docs/userguide/upgrading_version_5.adoc
  subprojects/plugins/src/main/java/org/gradle/api/internal/tasks/DefaultSourceSetOutput.java
  subprojects/plugins/src/main/java/org/gradle/api/tasks/SourceSetOutput.java
Labels: from:member

#10488 Use notimestamp for JavaDoc and notimestamp+noversionstamp for GroovyDoc
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/upgrading_version_5.adoc
  subprojects/language-groovy/src/integTest/groovy/org/gradle/groovy/GroovyDocIntegrationTest.groovy
  subprojects/language-groovy/src/integTest/groovy/org/gradle/groovy/GroovyDocStampsIntegrationTest.groovy
  subprojects/language-groovy/src/main/java/org/gradle/api/tasks/javadoc/Groovydoc.java
  subprojects/language-java/src/main/java/org/gradle/external/javadoc/StandardJavadocDocletOptions.java
  subprojects/language-java/src/test/groovy/org/gradle/external/javadoc/StandardJavadocDocletOptionsTest.java
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaCrossCompilationIntegrationTest.groovy
Labels: @build-cache, from:member

#8619 Use notimestamp for JavaDoc and notimestamp+noversionstamp for GroovyDoc
  subprojects/language-groovy/src/main/java/org/gradle/api/tasks/javadoc/Groovydoc.java
  subprojects/language-java/src/main/java/org/gradle/external/javadoc/StandardJavadocDocletOptions.java
  subprojects/language-java/src/test/groovy/org/gradle/external/javadoc/StandardJavadocDocletOptionsTest.java
Labels: @build-cache, from:contributor

#10495 Ensure plugin collection mutation results in an error
  subprojects/core/src/main/java/org/gradle/api/internal/plugins/DefaultPluginCollection.java
  subprojects/core/src/main/java/org/gradle/api/internal/plugins/DefaultPluginContainer.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/plugins/DefaultPluginContainerTest.groovy
Labels: a:chore, from:member

#10482 Fix Kotlin DSL caching soak test
  subprojects/soak/src/integTest/kotlin/org/gradle/kotlin/dsl/caching/BuildCacheIntegrationTest.kt
  subprojects/soak/src/integTest/kotlin/org/gradle/kotlin/dsl/caching/ScriptCachingIntegrationTest.kt
  subprojects/soak/src/integTest/kotlin/org/gradle/kotlin/dsl/caching/fixtures/ClassLoadingCache.kt
  subprojects/soak/src/integTest/kotlin/org/gradle/kotlin/dsl/caching/fixtures/CompilationCache.kt
  subprojects/soak/src/integTest/kotlin/org/gradle/kotlin/dsl/caching/fixtures/CompilationTrace.kt
  subprojects/soak/src/integTest/kotlin/org/gradle/kotlin/dsl/caching/fixtures/KotlinDslCacheFixtures.kt
Labels: from:member, in:kotlin-dsl

#10425 Set ValidateTaskProperties.failOnWarning = true
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskPropertyUtils.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/AbstractValidatingProperty.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/DefaultParameterValidationContext.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/DefaultTypeMetadataStore.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/PropertyValidationAccess.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/ValidationActions.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/CacheableTaskTypeAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/DestroysPropertyAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/InputPropertyAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/LocalStatePropertyAnnotationHandler.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/taskfactory/AnnotationProcessingTaskFactoryTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/DefaultTaskInputsTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/DefaultTaskOutputsTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/DefaultTypeMetadataStoreTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/annotations/NestedBeanAnnotationHandlerTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformValuesInjectionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/CacheableTransformTypeAnnotationHandler.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformer.java
  subprojects/docs/src/docs/userguide/upgrading_version_5.adoc
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/ParameterValidationContext.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/annotations/impl/DefaultPropertyAnnotationMetadata.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/annotations/impl/DefaultTypeAnnotationMetadata.java
  subprojects/model-core/src/test/groovy/org/gradle/internal/reflect/annotations/impl/DefaultTypeAnnotationMetadataStoreTest.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidateTaskPropertiesIntegrationTest.groovy
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/ValidateTaskProperties.java
Labels: @build-cache, from:member

#10472 Make annotations inherited from interface take precedence over superclass
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/annotations/impl/DefaultTypeAnnotationMetadataStore.java
  subprojects/model-core/src/test/groovy/org/gradle/internal/reflect/annotations/impl/DefaultTypeAnnotationMetadataStoreTest.groovy
Labels: @build-cache, from:member

#10462 Make TaskInputs.getProperties() unmodifiable
  subprojects/core-api/src/main/java/org/gradle/api/tasks/TaskInputs.java
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskPropertiesIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskInputs.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/GetInputPropertiesVisitor.java
  subprojects/docs/src/docs/userguide/upgrading_version_5.adoc
Labels: @build-cache, from:member

#10504 Small improvements to performance test report
  buildSrc/subprojects/performance/src/main/groovy/org/gradle/testing/DefaultPerformanceReporter.groovy
  buildSrc/subprojects/performance/src/main/groovy/org/gradle/testing/DistributedPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/ScenarioResult.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/DefaultPerformanceFlakinessDataProvider.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/DefaultReportGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/IndexPageGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/PerformanceFlakinessDataProvider.java
Labels: @dev-productivity, from:member

#10409 Use environment variable to shorten the command line path
  subprojects/core/src/main/java/org/gradle/process/internal/AbstractExecHandleBuilder.java
  subprojects/core/src/main/java/org/gradle/process/internal/JavaExecHandleBuilder.java
  subprojects/core/src/main/java/org/gradle/process/internal/util/LongCommandLineDetectionUtil.java
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecWIthLongCommandLineIntegrationTest.groovy
Labels: @core, a:feature, from:member, in:core

#10481 Add documentation and release notes for new apis for files and processes
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/custom_gradle_types.adoc
  subprojects/docs/src/docs/userguide/lazy_configuration.adoc
Labels: @instant-execution, from:member

#10493 Fix Visual Studio IntelliSense when specifying the language standard compiler flag
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/visualstudio/AbstractVisualStudioProjectIntegrationTest.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/visualstudio/VisualStudioSoftwareModelSingleProjectIntegrationTest.groovy
  subprojects/ide-native/src/main/groovy/org/gradle/ide/visualstudio/tasks/internal/VisualStudioProjectFile.groovy
  subprojects/ide-native/src/main/java/org/gradle/ide/visualstudio/internal/AbstractCppBinaryVisualStudioTargetBinary.java
  subprojects/ide-native/src/main/java/org/gradle/ide/visualstudio/internal/NativeSpecVisualStudioTargetBinary.java
  subprojects/ide-native/src/main/java/org/gradle/ide/visualstudio/internal/VisualStudioTargetBinary.java
  subprojects/platform-native/src/testFixtures/groovy/org/gradle/ide/visualstudio/fixtures/ProjectFile.groovy
Labels: @core, a:bug, from:member, in:native-platform

#10547 Upgrade AGP nightly in instant execution tests
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/AbstractInstantExecutionAndroidIntegrationTest.groovy
Labels: a:chore, in:instant-execution

#10536 Let new FileSystemOperations and ExecOperations services be @Incubating
  subprojects/core-api/src/main/java/org/gradle/api/file/FileSystemOperations.java
  subprojects/core-api/src/main/java/org/gradle/process/ExecOperations.java
  subprojects/distributions/src/changes/accepted-public-api-changes.json
Labels: @instant-execution, from:member, in:core

#10490 Deprecate IncrementalTaskInputs (without nagging)
  subprojects/core-api/src/main/java/org/gradle/api/tasks/incremental/IncrementalTaskInputs.java
  subprojects/core-api/src/main/java/org/gradle/work/ChangeType.java
  subprojects/core-api/src/main/java/org/gradle/work/FileChange.java
  subprojects/core-api/src/main/java/org/gradle/work/Incremental.java
  subprojects/core-api/src/main/java/org/gradle/work/InputChanges.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/custom_tasks.adoc
  subprojects/docs/src/docs/userguide/upgrading_version_5.adoc
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
  subprojects/platform-play/src/main/java/org/gradle/play/tasks/TwirlCompile.java
Labels: @build-cache, from:member

#10404 Smoke test Kotlin Gradle Plugin with Worker based tasks
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleKotlinDslSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/kotlin-dsl-multi-project-with-buildSrc/README.md
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/kotlin-dsl-multi-project-with-buildSrc/bluewhale/build.gradle.kts
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/kotlin-dsl-multi-project-with-buildSrc/build.gradle.kts
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/kotlin-dsl-multi-project-with-buildSrc/buildSrc/build.gradle.kts
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/kotlin-dsl-multi-project-with-buildSrc/buildSrc/settings.gradle.kts
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/kotlin-dsl-multi-project-with-buildSrc/buildSrc/src/main/kotlin/HelloTask.kt
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/kotlin-dsl-multi-project-with-buildSrc/krill/build.gradle.kts
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/kotlin-dsl-multi-project-with-buildSrc/settings.gradle.kts
Labels: a:chore, from:member

#10537 Schedule individual failed performance scenarios
  .teamcity/Gradle_Check/configurations/PerformanceTestCoordinator.kt
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcityTest/Gradle_Check_Tests/PerformanceTestBuildTypeTest.kt
  buildSrc/subprojects/performance/src/main/groovy/org/gradle/testing/DistributedPerformanceTest.groovy
  buildSrc/subprojects/performance/src/main/groovy/org/gradle/testing/PerformanceScenarioRerunStrategy.java
  buildSrc/subprojects/performance/src/main/groovy/org/gradle/testing/RepeatRerunStrategy.java
  buildSrc/subprojects/performance/src/main/groovy/org/gradle/testing/RetryFailedRerunStrategy.java
  buildSrc/subprojects/performance/src/test/groovy/org/gradle/testing/DistributedPerformanceTestTest.groovy
  buildSrc/subprojects/performance/src/test/groovy/org/gradle/testing/RepeatRerunStrategyTest.groovy
  buildSrc/subprojects/performance/src/test/groovy/org/gradle/testing/RetryFailedRerunStrategyTest.groovy
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/performance/PerformanceTestPlugin.kt
Labels: @dev-productivity, from:member

#10554 Remove one level from the JUnitXmlEvents
  buildSrc/subprojects/performance/src/main/groovy/org/gradle/testing/JUnitXmlTestEventsGenerator.groovy
Labels: @dev-productivity, from:member

#10608 Fix :instantExecution warnings
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/Codec.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/Contexts.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/beans/BeanPropertyWriter.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/ArtifactCollectionCodec.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/ProviderCodecs.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/ProxyCodec.kt
Labels: a:chore, from:member, in:instant-execution

#10552 Make buckets in TeamCity configuration
  .teamcity/Gradle_Check/configurations/FunctionalTest.kt
  .teamcity/Gradle_Check/configurations/GradleBuildConfigurationDefaults.kt
  .teamcity/Gradle_Check/configurations/StagePasses.kt
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/Gradle_Check/projects/FunctionalTestProject.kt
  .teamcity/Gradle_Check/projects/StageProject.kt
  .teamcityTest/Gradle_Check_Tests/CIConfigIntegrationTests.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/shared-configuration.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/buildtypes/BuildTypesPlugin.kt
Labels: @dev-productivity, a:chore, from:member

#10692 Small optimization for hashing in ModelMap
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/internal/modulemap/ModuleMap.java
Labels: from:member, in:native-platform

#10695 Migrate tests to use new transforms API
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildArtifactTransformIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/api/artifacts/transform/ArtifactTransformBuildScanIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ArtifactSelectionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/ResolvedArtifactsApiIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactFilterIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformParallelIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ConcurrentBuildsArtifactTransformIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/CrashingBuildsArtifactTransformIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/DisambiguateArtifactTransformIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/TransformationLoggingIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformOutputs.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/LegacyTransformer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformOutputsInternal.java
  subprojects/language-native/src/integTest/groovy/org/gradle/language/cpp/CppCustomHeaderDependencyIntegrationTest.groovy
Labels: @build-cache, from:member

#10607 Do not change extension of published artifact based on pom packaging
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/maven/MavenJavaModule.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishPomPackagingIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishPomPackagingJavaIntegTest.groovy
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publisher/AbstractMavenPublisher.java
Labels: from:member, in:dependency-management

#10696 Remove leftover reference to `getInstantiatorForNext`
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskPropertiesIntegrationTest.groovy
  subprojects/model-core/src/main/java/org/gradle/internal/instantiation/generator/AsmBackedClassGenerator.java
Labels: @build-cache, from:member

#10702 Do not split tests on AllVersionsCrossVersion
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/Gradle_Check/projects/FunctionalTestProject.kt
  .teamcity/Gradle_Check/projects/StageProject.kt
Labels: a:bug, a:chore, from:member

#10535 Update scan plugin to v. 2.4.2
  buildSrc/subprojects/profiling/profiling.gradle.kts
  subprojects/core/src/main/java/org/gradle/plugin/management/internal/autoapply/AutoAppliedBuildScanPlugin.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/BuildScanPluginSmokeTest.groovy
Labels: a:chore, from:member, in:build-scan

#10711 Re-add deferred tests
  .teamcity/Gradle_Check/configurations/StagePasses.kt
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/Gradle_Check/projects/FunctionalTestProject.kt
  .teamcity/Gradle_Check/projects/StageProject.kt
  .teamcityTest/Gradle_Check_Tests/CIConfigIntegrationTests.kt
Labels: @dev-productivity, from:member

#10712 Fix missing deferred_tests
  .teamcity/Gradle_Check/projects/StageProject.kt
Labels: @dev-productivity, a:chore, from:member

#10558 Preserve strict aspect when publishing resolved version
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/GradleModuleMetadataWriter.java
  subprojects/publish/src/test/groovy/org/gradle/api/publish/internal/ModuleMetadataFileGeneratorTest.groovy
Labels: a:bug, from:member, in:dependency-management

#10494 Feature Variant documentation: Improved confusing documentation and fixed odd grammar
  subprojects/docs/src/docs/userguide/dep-man/04-modeling-features/feature_variants.adoc
Labels: from:contributor

#10730 Upgrade under test AGP to latest alpha/nightly
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/AbstractInstantExecutionAndroidIntegrationTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
Labels: @instant-execution, a:chore, from:member, in:instant-execution

#10728 Improve teamcity DSL code for bucket generation
  .teamcity/Gradle_Check/configurations/StagePasses.kt
  .teamcity/Gradle_Check/projects/FunctionalTestProject.kt
  .teamcity/Gradle_Check/projects/RootProject.kt
  .teamcity/Gradle_Check/projects/StageProject.kt
Labels: @dev-productivity, from:member

#10732 Use unified timestamp when cleaning stale data
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/StaleDataCleanupInitializer.java
Labels: @dev-productivity, a:chore, from:member

#10731 Fix executing Specs tests via JUnit Platform and Vintage engine and remove unnecessary workarounds
  subprojects/testing-junit-platform/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestClassProcessor.java
  subprojects/testing-junit-platform/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestExecutionListener.java
  subprojects/testing-junit-platform/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/VintageTestNameAdapter.java
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junit/Specs2IntegrationTest.groovy
Labels: a:bug, from:member, in:testing

#10543 signing plugin: use SHA512 instead of SHA1 when signing artifacts
  subprojects/signing/src/main/java/org/gradle/plugins/signing/signatory/pgp/PgpSignatory.java
Labels: from:contributor

#10734 Hide task shared resources from the public api for now
  subprojects/core-api/src/main/java/org/gradle/api/Task.java
  subprojects/core-api/src/main/java/org/gradle/api/execution/SharedResource.java
  subprojects/core-api/src/main/java/org/gradle/api/invocation/Gradle.java
  subprojects/core/src/main/java/org/gradle/api/internal/AbstractTask.java
  subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java
  subprojects/core/src/main/java/org/gradle/invocation/DefaultGradle.java
Labels: @core, a:chore, from:member

#10700 Decorate artifact transform parameters
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformValuesInjectionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformWithFileInputsIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ConcurrentBuildsArtifactTransformIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/CrashingBuildsArtifactTransformIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementGlobalScopeServices.java
  subprojects/language-native/src/integTest/groovy/org/gradle/language/cpp/CppCustomHeaderDependencyIntegrationTest.groovy
Labels: @build-cache, from:member

#10701 Remove embedded-kotlin-repo and pin Kotlin dependencies with constraints
  subprojects/docs/src/docs/userguide/kotlin_dsl.adoc
  subprojects/docs/src/docs/userguide/upgrading_version_5.adoc
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/GradleKotlinDslIntegrationTest.kt
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/ProjectSchemaAccessorsIntegrationTest.kt
  subprojects/kotlin-dsl-plugins/kotlin-dsl-plugins.gradle.kts
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/embedded/EmbeddedKotlinPluginTest.kt
  subprojects/kotlin-dsl-plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/embedded/EmbeddedKotlinPlugin.kt
  subprojects/kotlin-dsl-tooling-builders/src/crossVersionTest/groovy/org/gradle/kotlin/dsl/tooling/builders/r54/PrecompiledScriptPluginModelCrossVersionSpec.groovy
  subprojects/kotlin-dsl/kotlin-dsl.gradle.kts
  subprojects/kotlin-dsl/src/integTest/kotlin/org/gradle/kotlin/dsl/support/EmbeddedKotlinProviderTest.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/execution/ResidualProgram.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/KotlinScriptEvaluator.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/EmbeddedKotlinProvider.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/GradleUserHomeServices.kt
Labels: from:member, in:kotlin-dsl

#10739 Add reified extensions for ComponentMetadataHandler
  subprojects/distributions/src/changes/accepted-public-api-changes.json
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/ComponentMetadataHandlerExtensions.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/ComponentMetadataHandlerExtensionsTest.kt
Labels: in:dependency-management, in:kotlin-dsl

#10748 Polish documentation of dependency platforms
  subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/controlling_transitive_dependencies.adoc
Labels: from:member, in:dependency-management

#10510 Allow modifications to variants of components for publishing
  subprojects/core-api/src/main/java/org/gradle/api/component/AdhocComponentWithVariants.java
  subprojects/docs/src/docs/userguide/dep-man/06-publishing/publishing.adoc
  subprojects/docs/src/docs/userguide/java_testing.adoc
  subprojects/docs/src/samples/userguide/java/fixtures/groovy/lib/build.gradle
  subprojects/docs/src/samples/userguide/java/fixtures/javaTestFixtures.sample.conf
  subprojects/docs/src/samples/userguide/java/fixtures/kotlin/lib/build.gradle.kts
  subprojects/docs/src/samples/userguide/java/fixtures/usages.out
  subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyPublishFeaturesJavaIntegTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyPublishJavaIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishFeaturesJavaIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishJavaIntegTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/fixtures/AbstractJavaTestFixturesIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/internal/java/usagecontext/ConfigurationVariantMapping.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/DefaultAdhocSoftwareComponent.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/DefaultSoftwareComponentFactory.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/PluginAuthorServices.java
Labels: from:member, in:dependency-management

#10129 Add generateDeploymentDescriptor boolean to Ear task and EarPluginCon…
  subprojects/docs/src/docs/dsl/org.gradle.plugins.ear.Ear.xml
  subprojects/docs/src/docs/dsl/org.gradle.plugins.ear.EarPluginConvention.xml
  subprojects/docs/src/docs/userguide/ear_plugin.adoc
  subprojects/ear/src/integTest/groovy/org/gradle/plugins/ear/EarPluginIntegrationTest.groovy
  subprojects/ear/src/main/java/org/gradle/plugins/ear/Ear.java
  subprojects/ear/src/main/java/org/gradle/plugins/ear/EarPlugin.java
  subprojects/ear/src/main/java/org/gradle/plugins/ear/EarPluginConvention.java
  subprojects/ear/src/main/java/org/gradle/plugins/ear/internal/DefaultEarPluginConvention.java
  subprojects/ear/src/test/groovy/org/gradle/plugins/ear/EarPluginTest.groovy
Labels: from:contributor

#10501 Expose public services to worker API actions
  subprojects/core/src/main/java/org/gradle/api/internal/file/DefaultFileOperations.java
  subprojects/core/src/main/java/org/gradle/api/internal/resources/DefaultResourceHandler.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GlobalScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/ProjectScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/WorkerSharedGlobalScopeServices.java
  subprojects/core/src/testFixtures/groovy/org/gradle/api/internal/file/TestFiles.java
  subprojects/language-jvm/src/main/java/org/gradle/api/internal/tasks/compile/daemon/AbstractDaemonCompiler.java
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerExecutorServicesIntegrationTest.groovy
  subprojects/workers/src/main/java/org/gradle/workers/internal/AbstractActionExecutionSpec.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/AbstractClassLoaderWorker.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/ActionExecutionSpec.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/ActionExecutionSpecFactory.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/DefaultActionExecutionSpecFactory.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/DefaultWorkerExecutor.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/DefaultWorkerServer.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/FlatClassLoaderWorker.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/IsolatedClassloaderWorker.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/IsolatedClassloaderWorkerFactory.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/IsolatedParametersActionExecutionSpec.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/NoIsolationWorkerFactory.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/SimpleActionExecutionSpec.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/TransportableActionExecutionSpec.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/TransportableActionExecutionSpecSerializer.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/WorkerDaemonServer.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/WorkerPublicServicesBuilder.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/WorkersServices.java
  subprojects/workers/src/test/groovy/org/gradle/workers/internal/DefaultWorkerExecutorParallelTest.groovy
  subprojects/workers/src/test/groovy/org/gradle/workers/internal/DefaultWorkerExecutorTest.groovy
  subprojects/workers/src/test/groovy/org/gradle/workers/internal/TransportableActionExecutionSpecSerializerTest.groovy
  subprojects/workers/src/test/groovy/org/gradle/workers/internal/WorkerDaemonClientTest.groovy
  subprojects/workers/src/testFixtures/groovy/org/gradle/workers/fixtures/WorkerExecutorFixture.groovy
  subprojects/workers/workers.gradle.kts
Labels: @core, a:feature, from:member, in:workers

#10750 Use `@ReplacedBy` on Java/GroovyCompile
  subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
Labels: @build-cache, from:member

#10767 Reword logging when changes require rebuild
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ResolveInputChangesStep.java
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/UnknownIncrementalAnnotationProcessingIntegrationTest.groovy
Labels: @build-cache, from:member

#10735 Rewrite section on component metadata rules
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/ComponentMetadataHandler.java
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/declaring_dependencies.adoc
  subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/component_metadata_rules.adoc
  subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/controlling_transitive_dependencies.adoc
  subprojects/docs/src/docs/userguide/dep-man/04-modeling-features/modeling_features.adoc
  subprojects/docs/src/docs/userguide/dep-man/04-modeling-features/variant_model.adoc
  subprojects/docs/src/docs/userguide/java_library_plugin.adoc
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/ivyMetadataRule/compileClasspathArtifacts.out
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/ivyMetadataRule/groovy/build.gradle
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/ivyMetadataRule/groovy/repo/org.sample/api/2.0/api-2.0.jar
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/ivyMetadataRule/groovy/repo/org.sample/api/2.0/ivy-2.0.xml
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/ivyMetadataRule/groovy/repo/org.sample/lib/2.0/ivy-2.0.xml
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/ivyMetadataRule/groovy/repo/org.sample/lib/2.0/lib-2.0.jar
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/ivyMetadataRule/groovy/settings.gradle
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/ivyMetadataRule/ivyComonentMetadataRule.sample.conf
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/ivyMetadataRule/kotlin/build.gradle.kts
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/ivyMetadataRule/kotlin/repo/org.sample/api/2.0/api-2.0.jar
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/ivyMetadataRule/kotlin/repo/org.sample/api/2.0/ivy-2.0.xml
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/ivyMetadataRule/kotlin/repo/org.sample/lib/2.0/ivy-2.0.xml
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/ivyMetadataRule/kotlin/repo/org.sample/lib/2.0/lib-2.0.jar
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/ivyMetadataRule/kotlin/settings.gradle.kts
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/ivyMetadataRule/runtimeClasspathArtifacts.out
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/comonentMetadataRules.sample.conf
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/compileClasspathArtifacts.out
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/failRuntimeClasspathResolve.out
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/groovy/build.gradle
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/groovy/repo/org.sample/api/1.9/ivy-1.9.xml
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/groovy/repo/org.sample/api/2.0/ivy-2.0.xml
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/groovy/repo/org.sample/client/1.3/ivy-1.3.xml
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/groovy/repo/org.sample/client/1.4/ivy-1.4.xml
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/groovy/repo/org.sample/client/1.5/client-1.5.jar
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/groovy/repo/org.sample/client/1.5/ivy-1.5.xml
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/groovy/repo/org.sample/lib/1.9/ivy-1.9.xml
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/groovy/repo/org.sample/lib/1.9/lib-1.9.jar
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/groovy/repo/org.sample/lib/2.0/ivy-2.0.xml
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/groovy/repo/org.sample/lib/2.0/lib-2.0.jar
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/kotlin/build.gradle.kts
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/kotlin/repo/org.sample/api/1.9/api-1.9.jar
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/kotlin/repo/org.sample/api/1.9/ivy-1.9.xml
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/kotlin/repo/org.sample/api/2.0/api-2.0.jar
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/kotlin/repo/org.sample/api/2.0/ivy-2.0.xml
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/kotlin/repo/org.sample/client/1.3/client-1.3.jar
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/kotlin/repo/org.sample/client/1.3/ivy-1.3.xml
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/kotlin/repo/org.sample/client/1.4/client-1.4.jar
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/kotlin/repo/org.sample/client/1.4/ivy-1.4.xml
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/kotlin/repo/org.sample/client/1.5/client-1.5.jar
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/kotlin/repo/org.sample/client/1.5/ivy-1.5.xml
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/kotlin/repo/org.sample/lib/1.9/ivy-1.9.xml
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/kotlin/repo/org.sample/lib/1.9/lib-1.9.jar
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/kotlin/repo/org.sample/lib/2.0/ivy-2.0.xml
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/kotlin/repo/org.sample/lib/2.0/lib-2.0.jar
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/latestSelector.out
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/latestSelector.sample.conf
  subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/runtimeClasspathArtifacts.out
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/samples/dependencymanagement/SamplesComponentMetadataRulesIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/logging/DependencyInsightOutputNormalizer.groovy
Labels: from:member, in:dependency-management, in:docs

#10758 Let Kotlin DSL gracefully handle lambdas registered as extensions
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/ProjectSchemaLambdaAccessorsIntegrationTest.kt
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/DefaultProjectSchemaProvider.kt
Labels: from:member, in:kotlin-dsl

#10769 Add validation at publication time
  subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyGradleModuleMetadataPublishIntegrationTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyPublishMultiProjectIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenGradleModuleMetadataPublishIntegrationTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishCustomComponentIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishJavaIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishMultiProjectIntegTest.groovy
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/DefaultMavenPublication.java
  subprojects/maven/src/test/groovy/org/gradle/api/publish/maven/internal/publication/DefaultMavenPublicationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/internal/java/WebApplication.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/WarPlugin.java
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/GradleModuleMetadataWriter.java
  subprojects/publish/src/test/groovy/org/gradle/api/publish/internal/ModuleMetadataFileGeneratorTest.groovy
Labels: from:member, in:dependency-management

#10774 Add error message in case GMM doesn't declare variants
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/validation/GradleMetadataValidationResolveIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/metadata/DefaultGradleModuleMetadataSource.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/Module.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/ivy/IvyFileModule.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/maven/AbstractMavenModule.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/maven/DelegatingMavenModule.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/DelegatingIvyModule.java
Labels: from:member, in:dependency-management

#10765 Make more buckets
  .teamcity/Gradle_Check/configurations/FunctionalTest.kt
  .teamcity/Gradle_Check/configurations/PerformanceTestCoordinator.kt
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/Gradle_Check/projects/FunctionalTestProject.kt
  .teamcity/Gradle_Check/projects/StageProject.kt
  .teamcityTest/Gradle_Check_Tests/CIConfigIntegrationTests.kt
Labels: @dev-productivity, a:chore, from:member

#10768 Remove duplicate vendor from javaVmVersion String
  subprojects/core/src/main/java/org/gradle/groovy/scripts/internal/RegistryAwareClassLoaderHierarchyHasher.java
Labels: @build-cache, from:member

#10780 Make feature dependencies available on test classpath
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaLibraryFeatureCompilationIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/DefaultJavaFeatureSpec.java
Labels: a:bug, from:member, in:dependency-management

#10779 Use Gradle profiler for running cross build tests
  subprojects/build-scan-performance/src/performanceTest/groovy/org/gradle/performance/BuildScanPluginPerformanceTest.groovy
  subprojects/build-scan-performance/src/testFixtures/groovy/org/gradle/performance/AbstractBuildScanPluginPerformanceTest.groovy
  subprojects/build-scan-performance/src/testFixtures/groovy/org/gradle/performance/fixture/BuildScanPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/integTest/groovy/org/gradle/performance/fixture/IdProviderCrossBuildPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/AbstractCrossBuildPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/AbstractCrossVersionGradleProfilerPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/AbstractGradleVsMavenPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/AbstractCrossBuildPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/AbstractGradleBuildPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/BuildExperimentSpec.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/CrossBuildGradleInternalPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/CrossBuildGradleProfilerPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleBuildExperimentSpec.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleInvocationSpec.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleProfilerBuildExperimentRunner.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleVsMavenPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/MavenBuildExperimentSpec.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/CompositeDataReporter.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/GradleProfilerReporter.java
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/experiment/buildcache/LocalTaskOutputCacheCrossBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/experiment/nativeplatform/NativeParallelPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/inception/GradleBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/kotlindsl/KotlinDslVsGroovyDslPerformanceTest.groovy
Labels: @build-cache, from:member

#10719 Add a test to reproduce finalizer/mustRunAfter behaviour
  subprojects/core/src/integTest/groovy/org/gradle/api/FinalizerTaskIntegrationTest.groovy
Labels: @build-cache, from:member

#10799 Create build scans and enable build cache for triggers
  .teamcity/Gradle_Check/configurations/StagePasses.kt
Labels: @dev-productivity, from:member

#10800 Emit lower bound for generic types of Kotlin DSL accessors
  subprojects/core-api/src/main/java/org/gradle/api/reflect/TypeOf.java
  subprojects/distributions/src/changes/accepted-public-api-changes.json
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/ProjectSchemaLambdaAccessorsIntegrationTest.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/AccessorFragments.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/KotlinTypeStrings.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/accessors/KotlinTypeStringTest.kt
Labels: a:bug, from:member, in:kotlin-dsl

#10795 Warn about deprecation of search upwards and similar APIs
  subprojects/core-api/src/main/java/org/gradle/StartParameter.java
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/GradleBuildTaskIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/InitScriptIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/BuildDefinition.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultCommandLineConverter.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultSettingsLoader.java
  subprojects/core/src/main/java/org/gradle/initialization/buildsrc/BuildSourceBuilder.java
  subprojects/core/src/main/java/org/gradle/initialization/layout/BuildLayoutConfiguration.java
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/action/BuildActionSerializer.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/ProviderStartParameterConverter.java
Labels: @core, a:chore, from:member, in:core

#10790 Improve error message when build fails because of missing metadata
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildDependencyGraphIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/buildsrc/BuildSrcIdentityIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/http/MetadataSourcesResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ivy/IvyBrokenRemoteResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenBrokenRemoteResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenLocalRepoResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenRemoteDependencyWithGradleMetadataResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenSnapshotResolveIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/ModuleVersionNotFoundException.java
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/DependencyInsightReportTaskIntegrationTest.groovy
  subprojects/resources-gcs/src/integTest/groovy/org/gradle/integtests/resource/gcs/maven/MavenGcsRepoErrorsIntegrationTest.groovy
  subprojects/resources-s3/src/integTest/groovy/org/gradle/integtests/resource/s3/maven/MavenS3RepoErrorsIntegrationTest.groovy
  subprojects/resources-sftp/src/integTest/groovy/org/gradle/integtests/resolve/resource/sftp/ivy/IvySftpRepoErrorsIntegrationTest.groovy
Labels: from:member, in:dependency-management

#10528 AWS S3 repositories using `credential_process` to authenticate
  gradle/dependencies.gradle
  subprojects/distributions/src/integTest/groovy/org/gradle/DistributionIntegritySpec.groovy
Labels: @core, from:contributor, in:dependency-management

#10802 Add worker services to the userguide, samples and release notes
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/custom_tasks.adoc
  subprojects/docs/src/samples/workerApi/noIsolation/groovy/build.gradle
  subprojects/docs/src/samples/workerApi/noIsolation/kotlin/build.gradle.kts
  subprojects/docs/src/samples/workerApi/waitForCompletion/groovy/build.gradle
  subprojects/docs/src/samples/workerApi/waitForCompletion/kotlin/build.gradle.kts
  subprojects/docs/src/samples/workerApi/workerDaemon/groovy/build.gradle
  subprojects/docs/src/samples/workerApi/workerDaemon/kotlin/build.gradle.kts
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/AbstractWorkerExecutorSampleIntegrationTest.groovy
Labels: @core, a:feature, from:member, in:workers

#10820 Add ProjectLayout and ProviderFactory services to workers
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GlobalScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/ProjectScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/WorkerSharedGlobalScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/WorkerSharedProjectScopeServices.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerExecutorServicesIntegrationTest.groovy
  subprojects/workers/src/main/java/org/gradle/workers/internal/WorkerDaemonServer.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/WorkerPublicServicesBuilder.java
Labels: @core, a:feature, from:member, in:workers

#10470 Fix enableFeaturePreview failure on template project execution
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/generator/FileContentGenerator.groovy
Labels: @dev-productivity, a:chore, from:member

#10824 Don't use mirror for Mac build agents
  .teamcity/Gradle_Check/configurations/GradleBuildConfigurationDefaults.kt
  .teamcity/common/extensions.kt
Labels: @dev-productivity, a:chore, from:member

#10811 Add performance experiment for faster incremental builds
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/BuildExperimentSpec.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/CrossBuildGradleProfilerPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleBuildExperimentSpec.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/MavenBuildExperimentSpec.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/experiment/buildcache/LocalTaskOutputCacheCrossBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/AndroidTestProject.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/FasterIncrementalAndroidBuildsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidBuildPerformanceTest.groovy
  subprojects/performance/templates.gradle
Labels: @build-cache, from:member

#10828 Set empty REPO_MIRROR_URLS for macos
  .teamcity/Gradle_Check/configurations/GradleBuildConfigurationDefaults.kt
  .teamcityTest/Gradle_Check_Tests/CIConfigIntegrationTests.kt
Labels: @dev-productivity, a:chore, from:member

#10809 Support publishing of Javadoc and sources
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/MavenConversionIntegrationTest.groovy
  subprojects/build-init/src/main/groovy/org/gradle/buildinit/plugins/internal/maven/Maven2Gradle.groovy
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/local/model/PublishArtifactLocalArtifactMetadata.java
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/OutgoingVariantsReportTaskIntegrationTest.groovy
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/building_java_projects.adoc
  subprojects/docs/src/docs/userguide/dep-man/06-publishing/publishing.adoc
  subprojects/docs/src/docs/userguide/publishing_ivy.adoc
  subprojects/docs/src/samples/ivy-publish/java-multi-project/groovy/build.gradle
  subprojects/docs/src/samples/ivy-publish/java-multi-project/kotlin/build.gradle.kts
  subprojects/docs/src/samples/ivy-publish/java-multi-project/output-ivy.xml
  subprojects/docs/src/samples/ivy-publish/java-multi-project/publish-multi-project.sample.conf
  subprojects/docs/src/samples/maven-publish/javaProject/groovy/build.gradle
  subprojects/docs/src/samples/maven-publish/javaProject/kotlin/build.gradle.kts
  subprojects/docs/src/samples/signing/maven-publish/groovy/build.gradle
  subprojects/docs/src/samples/signing/maven-publish/kotlin/build.gradle.kts
  subprojects/docs/src/samples/signing/maven-publish/publishingMavenSignAndPublish.out
  subprojects/docs/src/samples/signing/maven-publish/signingPluginSignPublication.out
  subprojects/docs/src/samples/userguide/antMigration/fileDeps/groovy/build.gradle
  subprojects/docs/src/samples/userguide/antMigration/fileDeps/kotlin/build.gradle.kts
  subprojects/docs/src/samples/userguide/java/basic/groovy/build.gradle
  subprojects/docs/src/samples/userguide/java/basic/kotlin/build.gradle.kts
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/JavaProjectIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/GradleModuleMetadata.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/maven/MavenJavaModule.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/SamplesIvyPublishIntegrationTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/AbstractMavenPublishJavaIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishJavaIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishJavaWithDocsAndFeaturesIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishJavaWithDocsIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishJavaWithFeaturesIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/SamplesMavenPublishIntegrationTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/integtests/publish/maven/MavenPublishIntegrationTest.groovy
  subprojects/maven/src/testFixtures/groovy/org/gradle/integtests/fixtures/publish/maven/AbstractMavenPublishIntegTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/ParallelJavaPluginTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaLibraryDocumentationIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaProjectOutgoingVariantsIntegrationTest.groovy
  subprojects/plugins/src/integTest/resources/org/gradle/api/plugins/ParallelJavaPluginTest/shared/build.gradle
  subprojects/plugins/src/integTest/resources/org/gradle/api/plugins/ParallelJavaPluginTest/shared/src/custom/resources/resource.txt
  subprojects/plugins/src/integTest/resources/org/gradle/api/plugins/ParallelJavaPluginTest/shared/src/customTest/resources/testResource.txt
  subprojects/plugins/src/integTest/resources/org/gradle/api/plugins/ParallelJavaPluginTest/shared/src/main/java/SomeClass.java
  subprojects/plugins/src/integTest/resources/org/gradle/api/plugins/ParallelJavaPluginTest/shared/src/main/resources/resource.txt
  subprojects/plugins/src/integTest/resources/org/gradle/api/plugins/ParallelJavaPluginTest/shared/src/test/resources/testResource.txt
  subprojects/plugins/src/main/java/org/gradle/api/internal/tasks/DefaultSourceSet.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/FeatureSpec.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPluginExtension.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/DefaultJavaFeatureSpec.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/DefaultJavaPluginExtension.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/JavaConfigurationVariantMapping.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/JvmPluginsHelper.java
  subprojects/plugins/src/main/java/org/gradle/api/tasks/SourceSet.java
  subprojects/signing/src/integTest/groovy/org/gradle/plugins/signing/SigningIntegrationSpec.groovy
  subprojects/signing/src/test/groovy/org/gradle/plugins/signing/SigningProjectSpec.groovy
Labels: from:member, in:dependency-management, in:publishing-plugin

#10829 Separate samples subproject
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  settings.gradle.kts
  subprojects/samples/samples.gradle.kts
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/AutoTestedSamplesCoreApiIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/AutoTestedSamplesCoreIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesAntlrIntegrationSpec.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesApplicationIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesClientModuleDependenciesIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesCodeQualityIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesCustomBuildLanguageIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesCustomPluginIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesGroovyCustomizedLayoutIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesGroovyMultiProjectIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesGroovyQuickstartIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesJUnitIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesJavaBaseIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesJavaCustomizedLayoutIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesJavaIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesJavaMultiProjectIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesJavaOnlyIfIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesJavaProjectWithIntTestsIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesJavaQuickstartIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesJavaTestListenerIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesMixedJavaAndGroovyIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesMultiProjectBuildSrcIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesRepositoriesIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesWebProjectIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesWebQuickstartIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/UserGuideSamplesIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/antmigration/SamplesAntImportIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/bestpractices/SamplesAuthoringMaintainableBuildsIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/dependencymanagement/SamplesComponentSelectionRulesIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/dependencymanagement/SamplesDeclaringDependenciesIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/dependencymanagement/SamplesDeclaringRepositoriesIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/dependencymanagement/SamplesDefiningUsingConfigurationsIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/dependencymanagement/SamplesDependencySubstitutionIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/dependencymanagement/SamplesManagingTransitiveDependenciesIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/dependencymanagement/SamplesResolutionStrategyIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/dependencymanagement/SamplesTroubleshootingDependencyResolutionIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/dependencymanagement/SamplesWorkingWithDependenciesIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/files/SamplesArchivesIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/files/SamplesCopyIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/files/SamplesFilesMiscIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/java/SamplesJavaTestingIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/multiprojectbuilds/SamplesMultiProjectBuildsIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/organizinggradleprojects/SamplesOrganizingGradleProjectsIntegrationTest.groovy
Labels: @dev-productivity, a:chore, from:member

#8485 upgraded Scala zinc compiler to version 1.2.5
  subprojects/language-jvm/src/testFixtures/groovy/org/gradle/api/tasks/compile/AbstractCompilerContinuousIntegrationTest.groovy
  subprojects/language-scala/language-scala.gradle.kts
  subprojects/language-scala/src/integTest/groovy/org/gradle/language/scala/LanguageScalaCompilationFixture.groovy
  subprojects/language-scala/src/integTest/groovy/org/gradle/language/scala/ScalaCompileParallelIntegrationTest.groovy
  subprojects/language-scala/src/integTest/groovy/org/gradle/language/scala/ScalaCompilerContinuousIntegrationTest.groovy
  subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/AnalysisStoreProvider.java
  subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/DaemonScalaCompiler.java
  subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/DefaultScalaJavaJointCompileSpec.java
  subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/ScalaCompileSpec.java
  subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/ZincScalaCompiler.java
  subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/ZincScalaCompilerFacade.java
  subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/ZincScalaCompilerFactory.java
  subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/ZincScalaCompilerUtil.java
  subprojects/language-scala/src/main/java/org/gradle/language/scala/internal/toolchain/DefaultScalaToolProvider.java
  subprojects/language-scala/src/main/java/org/gradle/language/scala/internal/toolchain/DownloadingScalaToolChain.java
  subprojects/language-scala/src/main/java/org/gradle/language/scala/tasks/AbstractScalaCompile.java
  subprojects/language-scala/src/test/groovy/org/gradle/language/scala/internal/toolchain/DownloadingScalaToolChainTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/integtests/ScalaAnnotationProcessingIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/integtests/fixtures/ZincCoverage.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/ScalaCompilationFixture.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/UpToDateScalaCompileIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/ZincScalaCompilerIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/ZincScalaCompilerMultiVersionIntegrationTest.groovy
  subprojects/scala/src/integTest/resources/org/gradle/scala/compile/ZincScalaCompilerIntegrationTest/compilesIncrementallyAcrossProjectBoundaries/prj1/src/main/scala/Person.scala
  subprojects/scala/src/integTest/resources/org/gradle/scala/compile/ZincScalaCompilerIntegrationTest/compilesIncrementallyAcrossProjectBoundaries/prj2/src/main/scala/House.scala
  subprojects/scala/src/integTest/resources/org/gradle/scala/compile/ZincScalaCompilerIntegrationTest/compilesScalaCodeIncrementally/src/main/scala/House.scala
  subprojects/scala/src/integTest/resources/org/gradle/scala/compile/ZincScalaCompilerIntegrationTest/compilesScalaCodeIncrementally/src/main/scala/Person.scala
  subprojects/scala/src/main/java/org/gradle/api/internal/tasks/scala/ScalaCompilerFactory.java
  subprojects/scala/src/main/java/org/gradle/api/plugins/scala/ScalaBasePlugin.java
  subprojects/scala/src/main/java/org/gradle/api/tasks/ScalaRuntime.java
  subprojects/scala/src/test/groovy/org/gradle/api/tasks/ScalaRuntimeTest.groovy
Labels: @core, from:contributor, in:scala-plugin

#10817 Fix regression when deprecating search upward APIs
  subprojects/composite-builds/src/test/groovy/org/gradle/composite/internal/DefaultIncludedBuildRegistryTest.groovy
  subprojects/core-api/src/main/java/org/gradle/StartParameter.java
  subprojects/core/src/main/java/org/gradle/api/internal/BuildDefinition.java
  subprojects/core/src/main/java/org/gradle/api/internal/StartParameterInternal.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultCommandLineConverter.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultSettingsLoader.java
  subprojects/core/src/main/java/org/gradle/initialization/buildsrc/BuildSourceBuilder.java
  subprojects/core/src/main/java/org/gradle/initialization/layout/BuildLayoutConfiguration.java
  subprojects/core/src/test/groovy/org/gradle/initialization/layout/BuildLayoutConfigurationTest.groovy
  subprojects/core/src/test/groovy/org/gradle/initialization/layout/BuildLayoutFactoryTest.groovy
  subprojects/distributions/src/changes/accepted-public-api-changes.json
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/action/BuildActionSerializer.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/ProviderStartParameterConverter.java
Labels: @core, a:chore, from:member, in:core

#10834 Fix extending JavaCompile deprecation message
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidPluginsSmokeTest.groovy
Labels: @build-cache, from:member

#10810 Fix test expectation
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/ErrorsOnStdoutScrapingExecutionResult.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/ExecutionResult.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/InProcessGradleExecuter.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/OutputScrapingExecutionResult.java
  subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperLoggingIntegrationTest.groovy
Labels: from:member, in:core

#10815 Steer users away from applying java directly
  subprojects/docs/src/docs/userguide/building_java_projects.adoc
  subprojects/docs/src/docs/userguide/groovy_plugin.adoc
  subprojects/docs/src/docs/userguide/java_plugin.adoc
  subprojects/docs/src/docs/userguide/scala_plugin.adoc
Labels: from:member, in:dependency-management, in:docs

#10832 Explicitly test for deprecation warning messages
  subprojects/file-collections/src/integTest/groovy/org/gradle/api/internal/file/FileCollectionIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/AbstractGradleExecuter.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/GradleExecuter.java
  subprojects/ivy/src/testFixtures/groovy/org/gradle/api/publish/ivy/AbstractIvyRemoteLegacyPublishIntegrationTest.groovy
  subprojects/logging/src/integTest/groovy/org/gradle/DeprecationHandlingIntegrationTest.groovy
  subprojects/platform-play/src/testFixtures/groovy/org/gradle/play/integtest/fixtures/external/AbstractMultiVersionPlayExternalContinuousBuildIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/DistributionPluginIntegrationTest.groovy
Labels: @build-cache, from:member

#10841 Add link to adoc source file to generated html
  subprojects/docs/docs.gradle
Labels: from:member, in:dependency-management, in:docs

#10845 Updates to maven migration guide
  subprojects/docs/src/docs/userguide/migrating_from_maven.adoc
Labels: from:member, in:dependency-management, in:docs

#10858 Display nice type names consistently for validation warnings
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalBuildSymlinkHandlingIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/NestedInputIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskInputFilePropertiesIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskParametersIntegrationTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/DefaultTypeMetadataStoreTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/PropertyValidationAccessTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformValuesInjectionIntegrationTest.groovy
  subprojects/execution/src/integTest/groovy/org/gradle/internal/execution/IncrementalExecutionIntegrationTest.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ValidateStep.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/ValidateStepTest.groovy
  subprojects/file-collections/src/integTest/groovy/org/gradle/api/file/FilePropertyIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskErrorExecutionIntegrationTest.groovy
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/MessageFormattingTypeValidationContext.java
  subprojects/model-core/src/test/groovy/org/gradle/internal/reflect/annotations/impl/DefaultTypeAnnotationMetadataStoreTest.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/AbstractPluginValidationIntegrationSpec.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/RuntimePluginValidationIntegrationTest.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidateTaskPropertiesConfiguredByPluginIntegrationTest.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidateTaskPropertiesIntegrationTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ThirdPartyPluginsSmokeTest.groovy
Labels: @build-cache, from:member

#10864 Upgrade integ and smoke tested AGP to latest
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/AbstractInstantExecutionAndroidIntegrationTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginSmokeTest.groovy
Labels: @instant-execution, a:chore

#10866 Add instant execution codec for ListenerManager service
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionIntegrationTest.groovy
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/Codecs.kt
Labels: from:member, in:instant-execution

#10869 Set minVersion for santa tracker
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidBuildPerformanceTest.groovy
Labels: a:chore, from:member

#10874 Warn when executing Gradle inside an undefined build
  subprojects/core/src/integTest/groovy/org/gradle/api/UndefinedBuildExecutionIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/execution/DeprecateUndefinedBuildWorkExecutor.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GradleScopeServices.java
  subprojects/docs/src/docs/userguide/upgrading_version_5.adoc
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractIntegrationSpec.groovy
Labels: @core, from:member

#10886 De-incubate latest dependency management APIs for 6.0
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/ComponentMetadataDetails.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/MutableVariantFilesMetadata.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/VariantFileMetadata.java
  subprojects/core-api/src/main/java/org/gradle/api/attributes/DocsType.java
  subprojects/core-api/src/main/java/org/gradle/api/attributes/LibraryElements.java
  subprojects/core-api/src/main/java/org/gradle/api/component/AdhocComponentWithVariants.java
  subprojects/distributions/src/changes/accepted-public-api-changes.json
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/IvyPublication.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/MavenPublication.java
Labels: from:member, in:dependency-management

#10873 Update user guide structure to make it easier accessible
  subprojects/docs/src/docs/userguide/artifact_management.adoc
  subprojects/docs/src/docs/userguide/authoring_maintainable_build_scripts.adoc
  subprojects/docs/src/docs/userguide/build_cache.adoc
  subprojects/docs/src/docs/userguide/building_cpp_projects.adoc
  subprojects/docs/src/docs/userguide/building_java_projects.adoc
  subprojects/docs/src/docs/userguide/building_swift_projects.adoc
  subprojects/docs/src/docs/userguide/command_line_interface.adoc
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/core_dependency_management.adoc
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/declaring_dependencies.adoc
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/declaring_repositories.adoc
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/dependency_resolution.adoc
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/library_vs_application.adoc
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/viewing_debugging_dependencies.adoc
  subprojects/docs/src/docs/userguide/dep-man/02-declaring-dependency-versions/dependency_locking.adoc
  subprojects/docs/src/docs/userguide/dep-man/02-declaring-dependency-versions/dynamic_versions.adoc
  subprojects/docs/src/docs/userguide/dep-man/02-declaring-dependency-versions/rich_versions.adoc
  subprojects/docs/src/docs/userguide/dep-man/02-declaring-dependency-versions/single_versions.adoc
  subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/component_metadata_rules.adoc
  subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/controlling_transitive_dependencies.adoc
  subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/dependency_capability_conflict.adoc
  subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/dependency_constraints.adoc
  subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/dependency_downgrade_and_exclude.adoc
  subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/dependency_version_alignment.adoc
  subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/platforms.adoc
  subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/resolution_rules.adoc
  subprojects/docs/src/docs/userguide/dep-man/04-modeling-features/artifact_transforms.adoc
  subprojects/docs/src/docs/userguide/dep-man/04-modeling-features/component_capabilities.adoc
  subprojects/docs/src/docs/userguide/dep-man/04-modeling-features/cross_project_publications.adoc
  subprojects/docs/src/docs/userguide/dep-man/04-modeling-features/feature_variants.adoc
  subprojects/docs/src/docs/userguide/dep-man/04-modeling-features/variant_model.adoc
  subprojects/docs/src/docs/userguide/dep-man/05-multirepo-environment/composite_builds.adoc
  subprojects/docs/src/docs/userguide/dep-man/05-working-multirepo/working_multi_source_repo_env.adoc
  subprojects/docs/src/docs/userguide/dep-man/06-publishing/publishing.adoc
  subprojects/docs/src/docs/userguide/dep-man/06-publishing/publishing_customization.adoc
  subprojects/docs/src/docs/userguide/dep-man/06-publishing/publishing_gradle_module_metadata.adoc
  subprojects/docs/src/docs/userguide/dep-man/06-publishing/publishing_setup.adoc
  subprojects/docs/src/docs/userguide/dep-man/06-publishing/publishing_signing.adoc
  subprojects/docs/src/docs/userguide/dep-man/07-fine-grained-dm-apis/fine_grained_dm_apis.adoc
  subprojects/docs/src/docs/userguide/dep-man/07-variant-aware-plugins/variant_attributes.adoc
  subprojects/docs/src/docs/userguide/dep-man/dependency_management.adoc
  subprojects/docs/src/docs/userguide/dep-man/dependency_management_terminology.adoc
  subprojects/docs/src/docs/userguide/dependency_management.adoc
  subprojects/docs/src/docs/userguide/dependency_management_for_java_projects.adoc
  subprojects/docs/src/docs/userguide/java_platform_plugin.adoc
  subprojects/docs/src/docs/userguide/java_plugin.adoc
  subprojects/docs/src/docs/userguide/migrating_from_ant.adoc
  subprojects/docs/src/docs/userguide/migrating_from_maven.adoc
  subprojects/docs/src/docs/userguide/plugin_reference.adoc
  subprojects/docs/src/docs/userguide/publishing_ivy.adoc
  subprojects/docs/src/docs/userguide/publishing_maven.adoc
  subprojects/docs/src/docs/userguide/upgrading_version_4.adoc
  subprojects/docs/src/docs/userguide/upgrading_version_5.adoc
  subprojects/docs/src/docs/userguide/userguide_single.adoc
  subprojects/docs/src/docs/userguide/war_plugin.adoc
  subprojects/docs/src/main/resources/header.html
  subprojects/docs/src/samples/userguide/dependencyManagement/declaringDependencies/strictForSubgraph/dependencies-strict.sample.conf
  subprojects/docs/src/samples/userguide/dependencyManagement/declaringDependencies/strictForSubgraph/groovy/build.gradle
  subprojects/docs/src/samples/userguide/dependencyManagement/declaringDependencies/strictForSubgraph/groovy/settings.gradle
  subprojects/docs/src/samples/userguide/dependencyManagement/declaringDependencies/strictForSubgraph/kotlin/build.gradle.kts
  subprojects/docs/src/samples/userguide/dependencyManagement/declaringDependencies/strictForSubgraph/kotlin/settings.gradle.kts
Labels: from:member, in:dependency-management, in:docs

#10859 Validate plugin source set defined in extension
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/plugins/JavaGradlePluginPluginTestKitSetupIntegrationTest.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidatePluginsIntegrationTest.groovy
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/plugins/JavaGradlePluginPlugin.java
Labels: @build-cache, from:member

#10865 Emit deprecation warning for duplicate files with default duplicate strategy
  subprojects/core-api/src/main/java/org/gradle/api/file/DuplicatesStrategy.java
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/bundling/ArchiveIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/bundling/ZipIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/CopySpecResolver.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultFileCopyDetails.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DuplicateHandlingCopyActionDecorator.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/FileCopyDetailsInternal.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/NormalizingCopyActionDecorator.java
  subprojects/core/src/main/java/org/gradle/api/tasks/bundling/AbstractArchiveTask.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy
  subprojects/docs/src/docs/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.xml
  subprojects/docs/src/docs/userguide/upgrading_version_5.adoc
  subprojects/docs/src/docs/userguide/working_with_files.adoc
  subprojects/language-native/src/integTest/groovy/org/gradle/language/cpp/CppApplicationPublishingIntegrationTest.groovy
Labels: @build-cache, from:member

#10883 Check for deprecations in samples
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/DependencyHandler.java
  subprojects/docs/src/samples/buildCache/cacheable-bundle/groovy/build.gradle
  subprojects/docs/src/samples/buildCache/cacheable-bundle/kotlin/build.gradle.kts
  subprojects/docs/src/samples/buildCache/configure-built-in-caches/groovy/settings.gradle
  subprojects/docs/src/samples/buildCache/configure-built-in-caches/kotlin/settings.gradle.kts
  subprojects/docs/src/samples/kotlinDsl/multiProjectBuild/build.gradle.kts
  subprojects/docs/src/samples/kotlinDsl/multiProjectBuild/multi-project-build.sample.conf
  subprojects/docs/src/samples/maven/pomGeneration/newPom.sample.conf
  subprojects/docs/src/samples/maven/quickstart/useMavenPlugin.sample.conf
  subprojects/docs/src/samples/signing/conditional/conditionalSigning.sample.conf
  subprojects/docs/src/samples/signing/maven/signingArchivesOutput.sample.conf
  subprojects/docs/src/samples/userguide/artifacts/maven/publishMavenRepository.sample.conf
  subprojects/docs/src/samples/userguide/dependencyManagement/declaringRepositories/filtering/groovy/build.gradle
  subprojects/docs/src/samples/userguide/dependencyManagement/declaringRepositories/filtering/kotlin/build.gradle.kts
  subprojects/docs/src/samples/userguide/dependencyManagement/managingTransitiveDependencies/forceForDependency/force-per-dependency.sample.conf
  subprojects/docs/src/samples/userguide/distribution/useDistributionPlugin.sample.conf
  subprojects/docs/src/samples/userguide/plugins/mutableManagedProperty/groovy/buildSrc/src/main/groovy/Download.groovy
  subprojects/docs/src/samples/userguide/plugins/mutableManagedProperty/java/buildSrc/src/main/java/Download.java
  subprojects/docs/src/samples/userguide/plugins/mutableManagedProperty/kotlin/buildSrc/src/main/kotlin/Download.kt
  subprojects/docs/src/samples/userguide/plugins/readOnlyManagedProperty/groovy/buildSrc/src/main/groovy/Download.groovy
  subprojects/docs/src/samples/userguide/plugins/readOnlyManagedProperty/java/buildSrc/src/main/java/Download.java
  subprojects/docs/src/samples/userguide/plugins/readOnlyManagedProperty/kotlin/buildSrc/src/main/kotlin/Download.kt
  subprojects/docs/src/samples/userguide/tasks/customTaskWithFileProperty/groovy/build.gradle
  subprojects/docs/src/samples/userguide/tasks/customTaskWithFileProperty/kotlin/build.gradle.kts
  subprojects/docs/src/samples/userguide/tasks/customTaskWithProperty/groovy/build.gradle
  subprojects/docs/src/samples/userguide/tasks/customTaskWithProperty/kotlin/build.gradle.kts
  subprojects/docs/src/samples/userguide/tasks/incrementalBuild/customTaskClass/runtimeIncrementalApi.out
  subprojects/docs/src/samples/userguide/tasks/incrementalBuild/customTaskClass/runtimeIncrementalApi.sample.conf
  subprojects/docs/src/samples/userguide/tasks/incrementalBuild/incrementalBuildAdvanced/groovy/build.gradle
  subprojects/docs/src/samples/userguide/tutorial/groovy/build.gradle
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractAutoTestedSamplesTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AutoTestedSamplesUtil.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/AutoTestedSamplesCoreApiIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/FailOnDeprecationSampleModifier.java
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/UserGuideSamplesIntegrationTest.groovy
  subprojects/signing/src/integTest/groovy/org/gradle/plugins/signing/AutoTestedSamplesSigningIntegrationTest.groovy
  subprojects/signing/src/main/java/org/gradle/plugins/signing/SigningExtension.java
Labels: @build-cache, from:member

#10893 Improvement: Add link to adoc source file to generated html
  subprojects/docs/docs.gradle
Labels: from:member, in:dependency-management, in:docs

#10896 Split cross version tests by task
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcityTest/Gradle_Check_Tests/CIConfigIntegrationTests.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/CrossVersionTestsPlugin.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/shared-configuration.kt
Labels: @dev-productivity, a:chore, from:member

#10905 Improve unsafe configuration resolution docs
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/viewing_debugging_dependencies.adoc
Labels: a:chore, from:member

#10860 Improved performance of logging for org.gradle.process.internal.DefaultExecHandle
  subprojects/core/src/main/java/org/gradle/process/internal/DefaultExecHandle.java
Labels: from:contributor
