Repository gradle/gradle, pull requests merged in 2019-04, with the labels that each got.

#8888 Move Kotlin DSL script caching tests to `soak`
  buildSrc/subprojects/buildquality/src/main/kotlin/org/gradle/gradlebuild/buildquality/classycle/ClassyclePlugin.kt
  settings.gradle.kts
  subprojects/soak/soak.gradle
  subprojects/soak/soak.gradle.kts
  subprojects/soak/src/integTest/kotlin/org/gradle/kotlin/dsl/caching/AbstractScriptCachingIntegrationTest.kt
  subprojects/soak/src/integTest/kotlin/org/gradle/kotlin/dsl/caching/BuildCacheIntegrationTest.kt
  subprojects/soak/src/integTest/kotlin/org/gradle/kotlin/dsl/caching/CompilationCache.kt
  subprojects/soak/src/integTest/kotlin/org/gradle/kotlin/dsl/caching/ScriptCachingIntegrationTest.kt
Labels: a:chore, from:member, in:gradle-build, in:kotlin-dsl

#8909 Fix ParallelTestTaskIntegrationTest test failure
  subprojects/plugins/src/integTest/groovy/org/gradle/java/ParallelTestTaskIntegrationTest.groovy
Labels: from:member

#8864 Automatically clean up output files on rebuild
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalInputsIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuter.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/SkipEmptySourceFilesTaskExecuter.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/FileParameterUtils.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/ExecutionGradleServices.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuterTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/SkipEmptySourceFilesTaskExecuterTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultDependencyManagementServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvoker.java
  subprojects/execution/execution.gradle.kts
  subprojects/execution/src/integTest/groovy/org/gradle/internal/execution/IncrementalExecutionIntegrationTest.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/InputChangesContext.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/UnitOfWork.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/impl/OutputsCleaner.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CleanupOutputsStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ExecuteStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ResolveChangesStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ResolveInputChangesStep.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CleanupOutputsStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/ExecuteStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/FingerprinterFixture.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/ResolveChangesStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/ResolveInputChangesStepTest.groovy
  subprojects/language-native/src/main/java/org/gradle/language/swift/tasks/UnexportMainSymbol.java
  subprojects/platform-base/platform-base.gradle
  subprojects/platform-base/src/main/java/org/gradle/language/base/internal/tasks/SimpleStaleClassCleaner.java
Labels: from:member

#8870 Report flaky performance test to issue tracker
  buildSrc/subprojects/performance/src/main/groovy/org/gradle/testing/DistributedPerformanceTest.groovy
  buildSrc/subprojects/performance/src/main/groovy/org/gradle/testing/ReportGenerationPerformanceTest.groovy
  subprojects/internal-performance-testing/internal-performance-testing.gradle.kts
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/AbstractTablePageGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/FlakinessIndexPageGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/FlakinessIssueReporter.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/FlakinessReportGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/ScenarioBuildResultData.groovy
  subprojects/internal-performance-testing/src/test/groovy/org/gradle/performance/results/FlakinessIssueReporterTest.groovy
Labels: @dev-productivity, a:chore, from:member

#8921 Support optional incremental inputs
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalInputsIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/StaticValue.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/DefaultInputFilePropertySpec.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/PropertyValue.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/NestedBeanAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/bean/AbstractNestedRuntimeBeanNode.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/bean/NestedRuntimeBeanNode.java
Labels: from:member

#8925 Add tests for different cache problems disabling caching
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CacheTaskArchiveErrorIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedTaskExecutionErrorHandlingIntegrationTest.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/caching/impl/DefaultCachingStateBuilder.java
Labels: @build-cache

#8922 Deprecate old transforms API
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/DependencyHandler.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/transform/ArtifactTransform.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/transform/VariantTransform.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformationRegistrationFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultVariantTransformRegistry.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/LegacyTransformer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/Transformation.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationRegistrationFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/Transformer.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/ConsumerProvidedVariantFinderTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvokerTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/AbstractGradleExecuter.java
Labels: from:member

#8926 Remove usage of `mavenLocal()` from `:integTest`
  subprojects/integ-test/integ-test.gradle.kts
Labels: @core, a:chore, from:member, in:gradle-build

#8927 Use HTTPS for GoogleAPIs repository
  subprojects/javascript/src/main/java/org/gradle/plugins/javascript/base/JavaScriptRepositoriesExtension.java
Labels: @core, a:chore, from:member, in:gradle-build

#8931 Mention potential breaking change regarding HTTPS usage
  subprojects/docs/src/docs/userguide/upgrading_version_5.adoc
Labels: @core, a:chore, from:member, in:docs

#8935 Deprecate using `File` as InputArtifact
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/transform/InputArtifact.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformInputArtifactIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIsolationIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformValuesInjectionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformWithDependenciesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformWithFileInputsIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/UnzipTransform.java
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/resolver/FindGradleSources.kt
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/AbstractConsoleBuildPhaseFunctionalTest.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidateTaskPropertiesIntegrationTest.groovy
Labels: from:member

#8929 Disable local cache in seed build
  .teamcity/Gradle_Check/configurations/CompileAll.kt
  gradle/shared-with-buildSrc/build-cache-configuration.settings.gradle.kts
Labels: @dev-productivity, a:chore, from:member

#8801 Rerun distributed performance test in RERUNNER step
  .teamcity/Gradle_Check/configurations/GradleBuildConfigurationDefaults.kt
  .teamcity/Gradle_Check/configurations/PerformanceTest.kt
  .teamcity/Gradle_Check/configurations/PerformanceTestCoordinator.kt
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/Gradle_Check/projects/StageProject.kt
  .teamcity/Gradle_Util_Performance/buildTypes/AdHocPerformanceScenarioLinux.kt
  .teamcity/Gradle_Util_Performance/buildTypes/AdHocPerformanceTestCoordinatorLinux.kt
  .teamcity/common/performance-test-extensions.kt
  .teamcityTest/Gradle_Check_Tests/ApplyDefaultConfigurationTest.kt
  .teamcityTest/Gradle_Check_Tests/PerformanceTestBuildTypeTest.kt
  buildSrc/subprojects/performance/src/main/groovy/org/gradle/testing/DistributedPerformanceTest.groovy
  buildSrc/subprojects/performance/src/main/groovy/org/gradle/testing/ReportGenerationPerformanceTest.groovy
  buildSrc/subprojects/performance/src/main/groovy/org/gradle/testing/RerunableDistributedPerformanceTest.groovy
  buildSrc/subprojects/performance/src/main/groovy/org/gradle/testing/ScenarioBuildResultData.groovy
  buildSrc/subprojects/performance/src/test/groovy/org/gradle/testing/RerunableDistributedPerformanceTestTest.groovy
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/performance/PerformanceTestPlugin.kt
  buildSrc/subprojects/profiling/src/main/kotlin/org/gradle/gradlebuild/profiling/buildscan/BuildScanPlugin.kt
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/AbstractCrossBuildPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/AbstractCrossVersionPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/AbstractTablePageGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/FlakinessIndexPageGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/IndexPageGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/ScenarioBuildResultData.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/inception/GradleBuildPerformanceTest.groovy
Labels: @dev-productivity, a:chore, from:member

#8941 Use Provider<FileSystemLocation> for artifact transforms
  buildSrc/subprojects/binary-compatibility/src/main/groovy/org/gradle/binarycompatibility/transforms/ExplodeZipAndFindJars.groovy
  buildSrc/subprojects/binary-compatibility/src/main/groovy/org/gradle/binarycompatibility/transforms/FindGradleClasspath.groovy
  buildSrc/subprojects/binary-compatibility/src/main/groovy/org/gradle/binarycompatibility/transforms/FindGradleJar.groovy
  buildSrc/subprojects/buildquality/src/main/kotlin/org/gradle/gradlebuild/buildquality/incubation/IncubatingApiReportTask.kt
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/Minify.kt
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/ShadeClasses.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: from:member

#8940 Add documentation for InputChanges
  subprojects/core-api/src/main/java/org/gradle/work/InputChanges.java
  subprojects/docs/src/docs/dsl/dsl.xml
  subprojects/docs/src/docs/dsl/org.gradle.work.InputChanges.xml
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/custom_tasks.adoc
  subprojects/docs/src/samples/userguide/tasks/incrementalTask/groovy/build.gradle
  subprojects/docs/src/samples/userguide/tasks/incrementalTask/incrementalTaskChangedProperty.out
  subprojects/docs/src/samples/userguide/tasks/incrementalTask/incrementalTaskFirstRun.out
  subprojects/docs/src/samples/userguide/tasks/incrementalTask/incrementalTaskRemovedInput.out
  subprojects/docs/src/samples/userguide/tasks/incrementalTask/incrementalTaskRemovedOutput.out
  subprojects/docs/src/samples/userguide/tasks/incrementalTask/incrementalTaskUpdatedInputs.out
  subprojects/docs/src/samples/userguide/tasks/incrementalTask/kotlin/build.gradle.kts
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/samples/UserGuideSamplesIntegrationTest.groovy
Labels: from:member

#8942 Fix Gradle Module Metadata marker disappearing
  subprojects/core/src/main/java/org/gradle/internal/xml/XmlTransformer.java
  subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyPublishDescriptorCustomizationIntegTest.groovy
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publisher/IvyDescriptorFileGenerator.java
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishPomCustomizationIntegTest.groovy
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/tasks/MavenPomFileGenerator.java
Labels: a:bug, in:dependency-management

#8947 Fix selection of target configuration with Ivy+constraints
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/DependenciesAttributesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ivy/IvyResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/platforms/JavaPlatformResolveIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/EdgeState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ModuleResolveState.java
Labels: a:bug, in:dependency-management

#8951 Let console report sub-second durations in milliseconds
  subprojects/base-services/src/main/java/org/gradle/internal/time/TimeFormatting.java
  subprojects/base-services/src/test/groovy/org/gradle/internal/time/TimeFormattingTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/internal/scan/eob/BuildScanEndOfBuildNotifierIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/OutputScrapingExecutionResult.java
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/taskgrouping/AbstractConsoleBuildResultFunctionalTest.groovy
  subprojects/logging/src/test/groovy/org/gradle/internal/logging/console/BuildStatusRendererTest.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/m8/ToolingApiLoggingCrossVersionSpec.groovy
Labels: from:member, in:console

#8949 Introduce VersionMapping support for IvyPublication
  subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/AbstractIvyPublishIntegTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/IvyPublishResolvedVersionsJavaIntegTest.groovy
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/IvyPublication.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publication/DefaultIvyPublication.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/versionmapping/DefaultVariantVersionMappingStrategy.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/versionmapping/DefaultVersionMappingStrategy.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/plugins/IvyPublishPlugin.java
  subprojects/ivy/src/test/groovy/org/gradle/api/publish/ivy/internal/publication/DefaultIvyPublicationTest.groovy
Labels: from:contributor, in:dependency-management

#8934 Re-use scheduled transform result only when available
  subprojects/core/src/main/java/org/gradle/execution/plan/Node.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultDependencyManagementServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformationNodeRegistry.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationNodeRegistry.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformingAsyncArtifactListener.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/DefaultArtifactTransformsTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/TransformingAsyncArtifactListenerTest.groovy
Labels: from:member

#8952 Improve incremental tasks documentation
  subprojects/core-api/src/main/java/org/gradle/work/InputChanges.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/custom_tasks.adoc
Labels: from:member

#8945 Rework configuration / variant exception messages
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildConfigurationAttributesResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ArtifactSelectionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/ResolvedArtifactsApiIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/ResolvedFilesApiIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/AbstractConfigurationAttributesResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/DependenciesAttributesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/ProjectDependenciesAttributesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/StronglyTypedConfigurationAttributesResolveIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/AmbiguousConfigurationSelectionException.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/AmbiguousVariantSelectionException.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/IncompatibleConfigurationSelectionException.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/NoMatchingConfigurationSelectionException.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/NoMatchingVariantSelectionException.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/AttributeMatchingVariantSelectorSpec.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/DefaultArtifactTransformsTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/model/AttributeConfigurationSelectorTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/model/LocalComponentDependencyMetadataTest.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/language/cpp/CppApplicationIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaLibraryCrossProjectTargetJvmVersionIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaLibraryPublishedTargetJvmVersionIntegrationTest.groovy
Labels: from:contributor, in:dependency-management

#8953 Fix ConcurrentModificationException in NodeState
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/VersionConflictResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/EdgeState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ModuleResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/NodeState.java
Labels: from:member, in:dependency-management

#7005 Convert more build script to Kotlin
  settings.gradle.kts
  subprojects/native/native.gradle
  subprojects/native/native.gradle.kts
  subprojects/osgi/osgi.gradle.kts
  subprojects/persistent-cache/persistent-cache.gradle.kts
  subprojects/platform-base/platform-base.gradle
  subprojects/platform-base/platform-base.gradle.kts
  subprojects/platform-jvm/platform-jvm.gradle
  subprojects/platform-jvm/platform-jvm.gradle.kts
  subprojects/platform-play/platform-play.gradle
  subprojects/platform-play/platform-play.gradle.kts
  subprojects/plugin-use/plugin-use.gradle.kts
  subprojects/plugins/plugins.gradle
  subprojects/plugins/plugins.gradle.kts
  subprojects/process-services/process-services.gradle
  subprojects/process-services/process-services.gradle.kts
  subprojects/publish/publish.gradle.kts
  subprojects/reporting/reporting.gradle
  subprojects/reporting/reporting.gradle.kts
  subprojects/resources-gcs/resources-gcs.gradle
  subprojects/resources-gcs/resources-gcs.gradle.kts
  subprojects/resources-http/resources-http.gradle.kts
  subprojects/resources-s3/resources-s3.gradle
  subprojects/resources-s3/resources-s3.gradle.kts
  subprojects/resources-sftp/resources-sftp.gradle.kts
  subprojects/resources/resources.gradle
  subprojects/resources/resources.gradle.kts
  subprojects/scala/scala.gradle.kts
  subprojects/signing/signing.gradle.kts
Labels: @dev-productivity, a:chore, from:member, in:gradle-build

#8967 Pass Github token to flakiness detection build
  .teamcity/Gradle_Check/configurations/PerformanceTestCoordinator.kt
  .teamcity/common/performance-test-extensions.kt
  .teamcityTest/Gradle_Check_Tests/PerformanceTestBuildTypeTest.kt
Labels: @dev-productivity, from:member

#8969 Add more validation for `@Incremental`
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskPropertyUtils.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/ValidatingTaskExecuter.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/DefaultParameterValidationContext.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/DefaultTypeMetadataStore.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/PropertyValidationAccess.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/InputPropertyAnnotationHandler.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformValuesInjectionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformationRegistrationFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformer.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/ParameterValidationContext.java
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidateTaskPropertiesIntegrationTest.groovy
Labels: from:member

#8946 Validate distribution jar files
  subprojects/distributions/src/integTest/groovy/org/gradle/DistributionIntegritySpec.groovy
  subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/file/TestFile.java
Labels: from:member

#8973 Clean up user manual section on incremental tasks
  subprojects/docs/src/docs/userguide/custom_tasks.adoc
  subprojects/docs/src/samples/userguide/tasks/incrementalTask/incrementalTaskNoChange.out
  subprojects/docs/src/samples/userguide/tasks/incrementalTask/incrementalTaskNoChange.sample.conf
Labels: from:member

#8976 Dissallow `@Incremental` on fields
  subprojects/core-api/src/main/java/org/gradle/work/Incremental.java
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalInputsIntegrationTest.groovy
Labels: from:member

#8975 Revert nullability changes to RelativePath
  subprojects/base-services/src/main/java/org/gradle/api/file/RelativePath.java
Labels: @build-cache, from:member

#8972 Fix integration tests which don't use repo mirrors
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/configuration/ExecuteDomainObjectCollectionCallbackBuildOperationTypeIntegrationTest.groovy
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/GradleKotlinDslIntegrationTest.kt
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/PrecompiledScriptPluginIntegrationTest.kt
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/ProjectSchemaAccessorsIntegrationTest.kt
Labels: @dev-productivity, a:chore, from:member

#8912 Introduce sanity check for repositories we use in the build
  build.gradle.kts
  buildSrc/subprojects/plugins/src/main/kotlin/gradlebuild/security.gradle.kts
  subprojects/performance/templates.gradle
Labels: a:chore, from:member

#8981 Use HTTPS mirror in `JavaProcessStackTracesMonitorSpec`
  subprojects/internal-integ-testing/src/test/groovy/org/gradle/integtests/fixtures/timeout/JavaProcessStackTracesMonitorSpec.groovy
Labels: @core, a:chore, from:member, in:testing

#8822 Gradle Module Metadata specification fixes
  subprojects/docs/src/docs/design/gradle-module-metadata-1.0-specification.md
Labels: from:member, in:dependency-management

#8932 Update plugin versions used in smoke test
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ThirdPartyPluginsSmokeTest.groovy
Labels: @core, a:chore, from:member, in:testing

#8985 Use sha-256 hashing to validate distribution dependencies
  subprojects/distributions/src/integTest/groovy/org/gradle/DistributionIntegritySpec.groovy
  subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/file/TestFile.java
Labels: from:member

#8984 Update release features for 5.4
  subprojects/docs/src/docs/release/release-features.txt
Labels: a:chore, from:member, in:docs

#8979 Adjust test assertions to fix flakiness
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/CancellationSpec.groovy
Labels: @dev-productivity, a:chore, from:member

#8988 GradleExecutor: Remove nested finally block to fail with the exception that occurs first
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/AbstractGradleExecuter.java
Labels: from:member

#8990 Capture JFR recording for compiler daemons
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/JfrProfiler.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/NoopProfiler.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/Profiler.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/generator/GroovyDslFileContentGenerator.groovy
Labels: from:member

#8999 Some more polishing for incremental tasks documentation
  subprojects/docs/src/docs/userguide/custom_tasks.adoc
  subprojects/docs/src/docs/userguide/more_about_tasks.adoc
Labels: from:member

#9000 Remove Gradle Wrapper version output from user manual
  subprojects/docs/src/docs/userguide/gradle_wrapper.adoc
  subprojects/docs/src/samples/userguide/wrapper/wrapperGradleVersionAfterUpgrade.out
Labels: from:member, in:docs

#8991 Use Java 8-compatible variant of Guava
  gradle/dependencies.gradle
  subprojects/base-services-groovy/src/main/java/org/gradle/groovy/scripts/internal/AstUtils.java
  subprojects/base-services/src/main/java/org/gradle/internal/Actions.java
  subprojects/base-services/src/main/java/org/gradle/internal/work/DefaultWorkerLeaseService.java
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalInputsIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/plugins/DefaultPluginContainer.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/DefaultTaskProperties.java
  subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java
  subprojects/core/src/main/java/org/gradle/internal/filewatch/jdk7/WatchPointsRegistry.java
  subprojects/core/src/testFixtures/groovy/org/gradle/internal/operations/TestBuildOperationExecutor.java
  subprojects/diagnostics/src/main/java/org/gradle/api/reporting/dependents/internal/DependentComponentsGraphRenderer.java
  subprojects/diagnostics/src/main/java/org/gradle/api/reporting/dependents/internal/DependentComponentsRenderableDependency.java
  subprojects/diagnostics/src/main/java/org/gradle/api/reporting/model/internal/ModelNodeRenderer.java
  subprojects/distributions/src/integTest/groovy/org/gradle/DistributionIntegritySpec.groovy
  subprojects/files/src/main/java/org/gradle/api/internal/file/AbstractFileCollection.java
  subprojects/files/src/main/java/org/gradle/api/internal/file/AntFileCollectionMatchingTaskBuilder.java
  subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/ApiGroovyCompiler.java
  subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/NormalizingGroovyCompiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/NormalizingJavaCompiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/asm/ClassRelevancyFilter.java
  subprojects/platform-base/src/main/java/org/gradle/api/internal/resolve/LocalLibraryDependencyResolver.java
  subprojects/platform-base/src/main/java/org/gradle/model/internal/core/DomainObjectCollectionBackedModelMap.java
  subprojects/platform-base/src/main/java/org/gradle/platform/base/internal/registry/ModelMapBasedRule.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/internal/resolve/DefaultVariantsMetaData.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/junit/result/AggregateTestResultsProvider.java
  subprojects/tooling-api/src/integTest/groovy/org/gradle/integtests/tooling/ToolingApiClasspathIntegrationTest.groovy
Labels: @build-cache, from:member

#8997 Mark known flaky performance test in report
  subprojects/build-scan-performance/src/testFixtures/groovy/org/gradle/performance/results/BuildScanReportGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/AbstractReportGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/AbstractTablePageGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/DefaultReportGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/FlakinessIndexPageGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/FlakinessReportGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/IndexPageGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/PerformanceFlakinessAnalyzer.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/Tag.java
  subprojects/internal-performance-testing/src/test/groovy/org/gradle/performance/results/IndexPageGeneratorTest.groovy
  subprojects/internal-performance-testing/src/test/groovy/org/gradle/performance/results/PerformanceFlakinessAnalyzerTest.groovy
  subprojects/internal-performance-testing/src/test/groovy/org/gradle/performance/results/ReportGeneratorTest.groovy
Labels: @dev-productivity, a:chore, from:member

#9011 Label current version in cross-version tests as 'current'
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/CrossVersionPerformanceTestRunner.groovy
Labels: from:member

#8986 Validate types for injection annotations
  buildSrc/subprojects/binary-compatibility/src/main/groovy/org/gradle/binarycompatibility/rules/SinceAnnotationMissingRule.java
  buildSrc/subprojects/binary-compatibility/src/test/groovy/org/gradle/binarycompatibility/PublicAPIRulesTest.groovy
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/transform/InputArtifact.java
  subprojects/core-api/src/main/java/org/gradle/api/reflect/InjectionPointQualifier.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformValuesInjectionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultVariantTransformRegistry.java
  subprojects/model-core/src/main/java/org/gradle/internal/instantiation/AbstractClassGenerator.java
Labels: from:member

#9015 Create NoOpPerformanceFlakinessAnalyzer if github token not found
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/DefaultPerformanceFlakinessAnalyzer.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/PerformanceFlakinessAnalyzer.java
  subprojects/internal-performance-testing/src/test/groovy/org/gradle/performance/results/DefaultPerformanceFlakinessAnalyzerTest.groovy
Labels: @dev-productivity, a:chore, from:member

#9143 Revert "Let Kotlin DSL resolver return given Java home"
  subprojects/kotlin-dsl/src/integTest/kotlin/org/gradle/kotlin/dsl/resolver/KotlinScriptDependenciesResolverTest.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/resolver/KotlinBuildScriptDependenciesResolver.kt
Labels: a:bug, from:member, in:kotlin-dsl

#8889 Simplify worker api isolated classloader structure
  subprojects/core/src/main/java/org/gradle/api/internal/DefaultClassPathProvider.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultClassLoaderRegistry.java
  subprojects/core/src/main/java/org/gradle/initialization/GradleApiUtil.java
  subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/daemon/DaemonGroovyCompiler.java
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerExecutorIntegrationTest.groovy
  subprojects/workers/src/main/java/org/gradle/workers/internal/ClassLoaderStructure.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/DaemonForkOptions.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/DaemonForkOptionsBuilder.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/IsolatedClassloaderWorkerFactory.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/WorkersServices.java
  subprojects/workers/src/test/groovy/org/gradle/workers/internal/DaemonForkOptionsMergeTest.groovy
  subprojects/workers/src/test/groovy/org/gradle/workers/internal/DaemonForkOptionsTest.groovy
Labels: @core, a:feature, from:member

#8899 Support C++ compilation with multiple Xcode version
  subprojects/platform-native/src/testFixtures/groovy/org/gradle/nativeplatform/fixtures/AvailableToolChains.java
Labels: @core, a:chore, from:member, in:native-platform

#8938 Let `ParameterNamesIndex` declare a `CompileClasspath` input
  buildSrc/subprojects/kotlin-dsl/src/main/kotlin/build/ParameterNamesIndex.kt
Labels: a:bug, from:member, in:gradle-build

#8989 Introduce Instant Execution
  settings.gradle.kts
  subprojects/base-services/src/main/java/org/gradle/util/Path.java
  subprojects/core/core.gradle.kts
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DestinationRootCopySpec.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/IProjectFactory.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradleLauncher.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultProjectDescriptor.java
  subprojects/core/src/main/java/org/gradle/initialization/InstantExecution.java
  subprojects/core/src/main/java/org/gradle/initialization/SettingsAttachingSettingsLoader.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/BuildScopeServiceRegistryFactory.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/BuildScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/initialization/DefaultGradleLauncherSpec.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/DependencyHandlerApiResolveIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/notations/DependencyClassPathNotationConverter.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/runtimeshaded/ImplementationDependencyRelocator.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/runtimeshaded/PackageListGenerator.java
  subprojects/distributions/src/integTest/groovy/org/gradle/DistributionIntegrationSpec.groovy
  subprojects/files/src/main/java/org/gradle/api/internal/file/FileCollectionFactory.java
  subprojects/instant-execution/instant-execution.gradle.kts
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionIntegrationTest.groovy
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/DefaultInstantExecution.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/EmptyArtifactCollection.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/InstantExecutionBuild.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/InstantExecutionHost.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/InstantExecutionServices.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/StateSerialization.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/StateSerializer.kt
  subprojects/instant-execution/src/main/resources/META-INF/services/org.gradle.internal.service.scopes.PluginServiceRegistry
  subprojects/instant-execution/src/test/kotlin/org/gradle/instantexecution/InstantExecutionTest.kt
  subprojects/model-core/src/main/java/org/gradle/api/internal/ConventionMapping.java
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/impldeps/GradleImplDepsGenerationIntegrationTest.groovy
Labels: @instant-execution, from:member, in:instant-execution

#9123 Upgrade to Guava 27.1
  buildSrc/subprojects/build/build.gradle.kts
  buildSrc/subprojects/configuration/src/main/kotlin/org/gradle/gradlebuild/dependencies/DependenciesMetadataRulesPlugin.kt
  buildSrc/subprojects/packaging/packaging.gradle.kts
  gradle/dependencies.gradle
  subprojects/distributions/src/integTest/groovy/org/gradle/DistributionIntegrationSpec.groovy
  subprojects/distributions/src/integTest/groovy/org/gradle/DistributionIntegritySpec.groovy
Labels: @build-cache, from:member

#9156 Polish `settings.gradle.kts`
  settings.gradle.kts
Labels: a:chore, from:member, in:gradle-build

#9158 Add explicit @Target to @Incubating
  subprojects/base-services/src/main/java/org/gradle/api/Incubating.java
Labels: from:member, in:core

#8957 Add documentation for artifact transforms
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/DependencyHandler.java
  subprojects/docs/src/docs/dsl/dsl.xml
  subprojects/docs/src/docs/dsl/org.gradle.api.artifacts.dsl.DependencyHandler.xml
  subprojects/docs/src/docs/dsl/org.gradle.api.artifacts.transform.TransformAction.xml
  subprojects/docs/src/docs/dsl/org.gradle.api.artifacts.transform.TransformOutputs.xml
  subprojects/docs/src/docs/dsl/org.gradle.api.artifacts.transform.TransformSpec.xml
  subprojects/docs/src/docs/userguide/build_cache.adoc
  subprojects/docs/src/docs/userguide/dependency_management_attribute_based_matching.adoc
  subprojects/docs/src/docs/userguide/more_about_tasks.adoc
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/incremental/artifactTransformIncremental.sample.conf
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/incremental/groovy/build.gradle
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/incremental/groovy/settings.gradle
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/incremental/kotlin/build.gradle.kts
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/incremental/kotlin/settings.gradle.kts
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/minify/artifactTransformMinify.out
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/minify/artifactTransformMinify.sample.conf
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/minify/groovy/build.gradle
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/minify/groovy/producer/build.gradle
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/minify/groovy/producer/src/main/java/producer/MyClass.java
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/minify/groovy/settings.gradle
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/minify/groovy/src/main/java/MyClass.java
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/minify/kotlin/build.gradle.kts
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/minify/kotlin/producer/build.gradle.kts
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/minify/kotlin/producer/src/main/java/producer/MyClass.java
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/minify/kotlin/settings.gradle.kts
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/minify/kotlin/src/main/java/MyClass.java
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/relocate/artifactTransformRelocate.sample.conf
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/relocate/groovy/build.gradle
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/relocate/groovy/settings.gradle
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/relocate/kotlin/build.gradle.kts
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/relocate/kotlin/settings.gradle.kts
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/unzip/artifactTransformUnzip.sample.conf
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/unzip/groovy/build.gradle
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/unzip/groovy/settings.gradle
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/unzip/kotlin/build.gradle.kts
  subprojects/docs/src/samples/userguide/dependencyManagement/artifactTransforms/unzip/kotlin/settings.gradle.kts
Labels: @build-cache, from:member

#9167 Add transform build operation
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultDependencyManagementServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvoker.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvokerTest.groovy
Labels: @build-cache, from:member

#9168 Replace `@Classpath` by `@CompileClasspath` in Kotlin DSL task
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/tasks/CompilePrecompiledScriptPluginPlugins.kt
Labels: a:performance-issue, from:member, in:kotlin-dsl

#9189 Fix Swift PM failures when no target is available
  subprojects/language-native/src/integTest/groovy/org/gradle/swiftpm/AbstractSwiftPackageManagerExportIntegrationTest.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/swiftpm/SwiftPackageManagerExportIntegrationTest.groovy
  subprojects/platform-native/src/testFixtures/groovy/org/gradle/language/swift/SwiftPmRunner.groovy
Labels: @core, a:chore, from:member, in:native-platform

#9192 Fix reference to `createStartScripts` task in docs
  subprojects/docs/src/docs/userguide/application_plugin.adoc
Labels: from:member, in:docs

#9188 Use `-fPIC` for C++ static library with Swift 4.1+ tool chain
  subprojects/language-native/src/integTest/groovy/org/gradle/language/swift/SwiftApplicationCppInteroperabilityIntegrationTest.groovy
  subprojects/platform-native/src/testFixtures/groovy/org/gradle/language/swift/AbstractSwiftMixedLanguageIntegrationTest.groovy
  subprojects/testing-native/src/integTest/groovy/org/gradle/nativeplatform/test/xctest/SwiftXCTestCppInteroperabilityIntegrationTest.groovy
Labels: @core, a:chore, from:member, in:native-platform

#9200 Fix DistributedPerformanceTest
  buildSrc/subprojects/performance/src/main/groovy/org/gradle/testing/DistributedPerformanceTest.groovy
Labels: @build-cache, from:member

#9201 Fix performance test project generator tasks
  buildSrc/subprojects/performance/src/main/groovy/org/gradle/testing/performance/generator/tasks/AbstractProjectGeneratorTask.groovy
Labels: @build-cache, from:member

#9197 Fix inconsistent classpath ordering when dependencies have lots of excludes
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/excludes/AbstractModuleExclusion.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/excludes/AllExclusion.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/excludes/EitherExclusion.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/excludes/ModuleExclusions.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/EdgeState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/NodeState.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/excludes/DefaultModuleExclusionTest.groovy
Labels: from:member, in:dependency-management

#9155 Upgrade embedded Kotlin to 1.3.30
  gradle/dependencies.gradle
  subprojects/distributions/src/integTest/groovy/org/gradle/DistributionIntegrationSpec.groovy
  subprojects/distributions/src/integTest/groovy/org/gradle/DistributionIntegritySpec.groovy
  subprojects/kotlin-dsl-plugins/kotlin-dsl-plugins.gradle.kts
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/embedded/EmbeddedKotlinPluginTest.kt
  subprojects/kotlin-dsl-plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/precompiled/PrecompiledScriptPlugins.kt
  subprojects/kotlin-dsl/kotlin-dsl.gradle.kts
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/EmbeddedKotlinProvider.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/KotlinCompiler.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/codegen/GradleApiExtensionsTest.kt
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
Labels: a:feature, from:member, in:kotlin-dsl

#9194 Adds C++ testing user manual chapter
  subprojects/docs/src/docs/userguide/cpp_testing.adoc
  subprojects/docs/src/docs/userguide/userguide_single.adoc
  subprojects/docs/src/main/resources/header.html
Labels: a:chore, from:member, in:docs

#9285 Direct kotlin-dsl issues to gradle/gradle in the kotlin-dsl user guide chapter
  subprojects/docs/src/docs/userguide/kotlin_dsl.adoc
Labels: from:member, in:docs

#9171 Document platform extending a third party platform
  subprojects/docs/src/docs/userguide/java_platform_plugin.adoc
  subprojects/docs/src/samples/java-platform/quickstart/groovy/build.gradle
  subprojects/docs/src/samples/java-platform/quickstart/kotlin/build.gradle.kts
Labels: from:member, in:dependency-management

#9297 Apply review suggestions to `checkBinaryCompatibility`
  buildSrc/subprojects/binary-compatibility/src/main/groovy/org/gradle/binarycompatibility/rules/NullabilityBreakingChangesRule.groovy
  buildSrc/subprojects/binary-compatibility/src/main/groovy/org/gradle/binarycompatibility/rules/SinceAnnotationMissingRule.java
  buildSrc/subprojects/binary-compatibility/src/main/kotlin/org/gradle/binarycompatibility/BinaryCompatibilityRepository.kt
  buildSrc/subprojects/binary-compatibility/src/main/kotlin/org/gradle/binarycompatibility/BinaryCompatibilityRepositoryLifecycle.kt
  buildSrc/subprojects/binary-compatibility/src/test/kotlin/org/gradle/binarycompatibility/NullabilityChangesTest.kt
Labels: a:feature, from:member, in:gradle-build

#9288 Prohibit underscore in package names and improve package validation performance
  subprojects/platform-jvm/src/jmh/java/org/gradle/jvm/internal/JvmPackageNameBenchmark.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/internal/DefaultJvmApiSpec.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/internal/JvmPackageName.java
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/internal/JvmPackageNameTest.groovy
Labels: @build-cache, from:member

#9292 Upgrade embedded Kotlin version to 1.3.31
  gradle/dependencies.gradle
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/library-versions.properties
  subprojects/distributions/src/integTest/groovy/org/gradle/DistributionIntegritySpec.groovy
  subprojects/kotlin-dsl-plugins/kotlin-dsl-plugins.gradle.kts
  subprojects/kotlin-dsl/kotlin-dsl.gradle.kts
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
Labels: a:feature, from:member, in:kotlin-dsl

#8895 Introduce support for Kotlin code in binary compatibility check
  buildSrc/build.gradle.kts
  buildSrc/subprojects/binary-compatibility/binary-compatibility.gradle.kts
  buildSrc/subprojects/binary-compatibility/src/main/groovy/org/gradle/binarycompatibility/BinaryCompatibilityHelper.groovy
  buildSrc/subprojects/binary-compatibility/src/main/groovy/org/gradle/binarycompatibility/filters/AnonymousClassesFilter.groovy
  buildSrc/subprojects/binary-compatibility/src/main/groovy/org/gradle/binarycompatibility/filters/KotlinInternalFilter.groovy
  buildSrc/subprojects/binary-compatibility/src/main/groovy/org/gradle/binarycompatibility/rules/AbstractGradleViolationRule.groovy
  buildSrc/subprojects/binary-compatibility/src/main/groovy/org/gradle/binarycompatibility/rules/KotlinModifiersBreakingChangeRule.groovy
  buildSrc/subprojects/binary-compatibility/src/main/groovy/org/gradle/binarycompatibility/rules/NullabilityBreakingChangesRule.groovy
  buildSrc/subprojects/binary-compatibility/src/main/groovy/org/gradle/binarycompatibility/rules/SinceAnnotationMissingRule.java
  buildSrc/subprojects/binary-compatibility/src/main/groovy/org/gradle/binarycompatibility/rules/SinceAnnotationMissingRuleAPISourceFoldersSetup.java
  buildSrc/subprojects/binary-compatibility/src/main/kotlin/org/gradle/binarycompatibility/BinaryCompatibilityRepository.kt
  buildSrc/subprojects/binary-compatibility/src/main/kotlin/org/gradle/binarycompatibility/BinaryCompatibilityRepositoryLifecycle.kt
  buildSrc/subprojects/binary-compatibility/src/main/kotlin/org/gradle/binarycompatibility/JApiCmpExtensions.kt
  buildSrc/subprojects/binary-compatibility/src/main/kotlin/org/gradle/binarycompatibility/JavassistExtensions.kt
  buildSrc/subprojects/binary-compatibility/src/main/kotlin/org/gradle/binarycompatibility/metadata/HasKotlinFlagsMetadataQuery.kt
  buildSrc/subprojects/binary-compatibility/src/main/kotlin/org/gradle/binarycompatibility/metadata/KotlinMetadataQueries.kt
  buildSrc/subprojects/binary-compatibility/src/main/kotlin/org/gradle/binarycompatibility/sources/JavaSourceQueries.kt
  buildSrc/subprojects/binary-compatibility/src/main/kotlin/org/gradle/binarycompatibility/sources/KotlinSourceQueries.kt
  buildSrc/subprojects/binary-compatibility/src/main/kotlin/org/gradle/binarycompatibility/sources/SourcesRepository.kt
  buildSrc/subprojects/binary-compatibility/src/test/groovy/org/gradle/binarycompatibility/PublicAPIRulesTest.groovy
  buildSrc/subprojects/binary-compatibility/src/test/kotlin/org/gradle/binarycompatibility/AbstractBinaryCompatibilityTest.kt
  buildSrc/subprojects/binary-compatibility/src/test/kotlin/org/gradle/binarycompatibility/AnonymousClassesFilteringTest.kt
  buildSrc/subprojects/binary-compatibility/src/test/kotlin/org/gradle/binarycompatibility/KotlinInternalFilteringTest.kt
  buildSrc/subprojects/binary-compatibility/src/test/kotlin/org/gradle/binarycompatibility/KotlinModifiersChangeTest.kt
  buildSrc/subprojects/binary-compatibility/src/test/kotlin/org/gradle/binarycompatibility/NullabilityChangesTest.kt
  buildSrc/subprojects/binary-compatibility/src/test/kotlin/org/gradle/binarycompatibility/RichReportScrapper.kt
  buildSrc/subprojects/binary-compatibility/src/test/kotlin/org/gradle/binarycompatibility/SinceAndIncubatingRulesKotlinTest.kt
  buildSrc/subprojects/configuration/src/main/kotlin/org/gradle/gradlebuild/ProjectGroups.kt
  buildSrc/subprojects/kotlin-dsl/src/main/kotlin/PublicKotlinDslApi.kt
  buildSrc/subprojects/kotlin-dsl/src/main/kotlin/build/KotlinCompilerConfiguration.kt
  buildSrc/subprojects/kotlin-dsl/src/main/kotlin/parser/KotlinSourceParser.kt
  buildSrc/subprojects/kotlin-dsl/src/main/kotlin/plugins/kotlin-library.gradle.kts
  subprojects/distributions/binary-compatibility.gradle
Labels: from:member, in:gradle-build

#9293 Pass compiler classes and instantiate them in the worker
  subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/GroovyCompilerFactory.java
  subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/daemon/DaemonGroovyCompiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/DaemonJavaCompiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/DefaultJavaCompilerFactory.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JdkJavaCompiler.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/DefaultJavaCompilerFactoryTest.groovy
  subprojects/language-jvm/src/main/java/org/gradle/api/internal/tasks/compile/daemon/AbstractDaemonCompiler.java
  subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/DaemonScalaCompiler.java
  subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/ZincScalaCompiler.java
  subprojects/language-scala/src/main/java/org/gradle/language/scala/internal/toolchain/DefaultScalaToolProvider.java
  subprojects/platform-base/src/main/java/org/gradle/language/base/internal/compile/RequiresServices.java
  subprojects/platform-play/src/main/java/org/gradle/play/internal/javascript/GoogleClosureCompiler.java
  subprojects/platform-play/src/main/java/org/gradle/play/internal/routes/RoutesCompiler.java
  subprojects/platform-play/src/main/java/org/gradle/play/internal/routes/RoutesCompilerAdapterFactory.java
  subprojects/platform-play/src/main/java/org/gradle/play/internal/toolchain/DaemonPlayCompiler.java
  subprojects/platform-play/src/main/java/org/gradle/play/internal/toolchain/DefaultPlayToolChain.java
  subprojects/platform-play/src/main/java/org/gradle/play/internal/toolchain/DefaultPlayToolProvider.java
  subprojects/platform-play/src/main/java/org/gradle/play/internal/twirl/TwirlCompiler.java
  subprojects/platform-play/src/main/java/org/gradle/play/internal/twirl/TwirlCompilerAdapterFactory.java
  subprojects/platform-play/src/main/java/org/gradle/play/tasks/TwirlCompile.java
  subprojects/platform-play/src/test/groovy/org/gradle/play/internal/routes/RoutesCompilerAdapterFactoryTest.groovy
  subprojects/platform-play/src/test/groovy/org/gradle/play/internal/toolchain/DaemonPlayCompilerTest.groovy
  subprojects/scala/src/main/java/org/gradle/api/internal/tasks/scala/ScalaCompilerFactory.java
Labels: a:feature, from:member, in:workers

#9303 Let all the gradle/gradle build inception performance tests skip buildSrc checks
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/inception/GradleInceptionPerformanceTest.groovy
Labels: a:chore, from:member

#9296 Support adding a 'gradle.properties' file to a Gradle distribution
  subprojects/core-api/src/main/java/org/gradle/StartParameter.java
  subprojects/core-api/src/main/java/org/gradle/initialization/BuildLayoutParameters.java
  subprojects/core/src/integTest/groovy/org/gradle/initialization/PropertiesLoaderIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradlePropertiesLoader.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/BuildScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/initialization/DefaultGradlePropertiesLoaderTest.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/build_environment.adoc
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractIntegrationSpec.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/UnderDevelopmentGradleDistribution.java
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/DaemonJvmSettingsIntegrationTest.groovy
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/converter/LayoutToPropertiesConverter.java
  subprojects/launcher/src/test/groovy/org/gradle/launcher/cli/converter/LayoutToPropertiesConverterTest.groovy
Labels: from:member

#9306 Polish Kotlin DSL
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/precompiled/PrecompiledScriptPluginAccessorsTest.kt
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/tasks/GeneratePrecompiledScriptPluginAccessors.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/KotlinScriptClassPathProvider.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/delegates/ClientModuleDelegate.kt
Labels: a:feature, from:member, in:kotlin-dsl

#9212 Exclude already used names when naming eclipse projects
  subprojects/docs/src/docs/release/notes.md
  subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/configurer/EclipseModelAwareUniqueProjectNameProvider.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/EclipseModelBuilder.java
  subprojects/ide/src/test/groovy/org/gradle/plugins/ide/internal/tooling/eclipse/EclipseModelBuilderTest.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r55/CompositeDeduplicationCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r55/DefaultEclipseWorkspace.java
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r55/DefaultEclipseWorkspaceProject.java
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r55/LoadCompositeEclipseModels.java
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r55/LoadEclipseModel.java
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r55/ReservedProjectNamesCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r55/SupplyRuntimeAndLoadCompositeEclipseModels.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/model/eclipse/EclipseRuntime.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/model/eclipse/EclipseWorkspace.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/model/eclipse/EclipseWorkspaceProject.java
Labels: from:contributor
