Repository gradle/gradle, pull requests merged in 2020-03, with the labels that each got.

#12390 Edits "Resolvable and consumable configurations" section
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/declaring_dependencies.adoc
Labels: @jvm, from:contributor, in:dependency-management, in:docs

#12373 Fix VFS retention soak test
  .teamcity/Gradle_Check/configurations/FunctionalTest.kt
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/VfsRetentionHelper.java
  subprojects/soak/src/integTest/groovy/org/gradle/vfs/VirtualFileSystemRetentionSoakTest.groovy
Labels: @build-cache, from:member

#12378 Fix tooling API metadata - bundling attribute
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/ShadedJarPlugin.kt
  subprojects/tooling-api/src/integTest/groovy/org/gradle/integtests/tooling/ToolingApiResolveIntegrationTest.groovy
Labels: @jvm, in:gradle-build, in:tooling-api

#12386 Log location of JVM crash log
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/ProcessCrashHandlingIntegrationTest.groovy
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/client/DaemonClient.java
Labels: @build-cache, from:member

#12398 Upgrade tested AGP versions
  gradle/dependency-management/agp-versions.properties
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerJavaCachingSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerKotlinCachingSmokeTest.groovy
Labels: a:chore, from:member

#12396 Add JavaVersion constants up to and including latest LTS Java 17
  subprojects/base-services/src/main/java/org/gradle/api/JavaVersion.java
  subprojects/base-services/src/test/groovy/org/gradle/api/JavaVersionSpec.groovy
Labels: @core, from:member, in:core

#12395 Add Java 14 constant to JavaVersion
  subprojects/base-services/src/main/java/org/gradle/api/JavaVersion.java
  subprojects/base-services/src/test/groovy/org/gradle/api/JavaVersionSpec.groovy
Labels: @core, from:member, in:core

#12372 Add sample and bump PMD version to 6.21.0
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/pmd/AbstractPmdPluginVersionIntegrationTest.groovy
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/Pmd.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdExtension.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdPlugin.java
  subprojects/docs/src/docs/userguide/core-plugins/pmd_plugin.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
  subprojects/docs/src/snippets/codeQuality/groovy/build.gradle
  subprojects/docs/src/snippets/codeQuality/kotlin/build.gradle.kts
Labels: @jvm, from:member, in:pmd-plugin

#12353 Do not add annotation processor classpaths to IDEA scopes
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
  subprojects/ide/src/main/java/org/gradle/plugins/ide/idea/IdeaPlugin.java
  subprojects/ide/src/test/groovy/org/gradle/plugins/ide/idea/IdeaPluginTest.groovy
Labels: @jvm, from:member, in:idea-plugin, in:jvm-ecosystem

#12391 Add access to POM packaging in component metadata rules
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/ComponentMetadataContext.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/ComponentMetadataHandler.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/maven/PomModuleDescriptor.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/maven/package-info.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/ComponentMetadataRulesCachingIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/ComponentMetadataRulesErrorHandlingIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/ComponentMetadataRulesIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultPomModuleDescriptor.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/DefaultComponentMetadataContext.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/DefaultComponentMetadataHandler.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/DefaultComponentMetadataProcessor.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/MetadataDescriptorFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/WrappingComponentMetadataContext.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/rules/DefaultRuleActionValidator.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/DefaultPomModuleDescriptorTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/dsl/DefaultComponentMetadataHandlerTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/dsl/MetadataDescriptorFactoryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/rules/DefaultRuleActionValidatorTest.groovy
  subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/component_metadata_rules.adoc
  subprojects/docs/src/snippets/userguide/dependencyManagement/customizingResolution/metadataRule/groovy/build.gradle
  subprojects/docs/src/snippets/userguide/dependencyManagement/customizingResolution/metadataRule/kotlin/build.gradle.kts
Labels: @jvm, from:member, in:dependency-management

#12406 Do not test CMS garbage collector in JDK14 because it has been removed
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/server/health/gc/GarbageCollectionMonitoringIntegrationTest.groovy
Labels: @core, from:member, in:core

#12405 Filter multi-version tested Groovy plugin versions by JDK
  subprojects/language-groovy/language-groovy.gradle.kts
  subprojects/language-groovy/src/testFixtures/groovy/org/gradle/testing/fixture/GroovyCoverage.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/groovy/compile/BasicGroovyCompilerIntegrationSpec.groovy
Labels: @core, from:member, in:core

#12411 Remove FIX_TO_WORK_ON_JAVA9 constraints from tests that pass with Java9+
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/pmd/PmdPluginDependenciesIntegrationTest.groovy
  subprojects/language-scala/src/integTest/groovy/org/gradle/language/scala/ScalaLanguageIncrementalBuildIntegrationTest.groovy
  subprojects/reporting/src/integTest/groovy/org/gradle/api/reporting/plugins/BuildDashboardPluginIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/CachedScalaCompileIntegrationTest.groovy
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/GradleRunnerUnsupportedFeatureFailureIntegrationTest.groovy
Labels: @core, from:member, in:core

#11555 Fix https://github.com/gradle/gradle/issues/11490
  subprojects/language-jvm/src/main/java/org/gradle/api/tasks/compile/BaseForkOptions.java
  subprojects/language-jvm/src/test/groovy/org/gradle/api/tasks/compile/BaseForkOptionsTest.groovy
Labels: @core, from:contributor

#12384 Use event driven Linux watcher
  gradle/dependencies.gradle
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java
  subprojects/core/src/main/java/org/gradle/internal/vfs/AbstractEventDrivenFileWatcherRegistry.java
  subprojects/core/src/main/java/org/gradle/internal/vfs/LinuxFileWatcherRegistry.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultWatchingVirtualFileSystem.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/watch/FileWatcherRegistry.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/watch/impl/JdkFileWatcherRegistry.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/watch/impl/NoopFileWatcherRegistry.java
Labels: @build-cache, from:member

#12414 Add release notes for crash log location
  subprojects/docs/src/docs/release/notes.md
Labels: @build-cache, from:member

#12421 Update to newer snapshot
  gradle/dependencies.gradle
Labels: @build-cache, from:member

#12430 Let `GradleBuildInstantExecutionSmokeTest` run with `CI` set
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildInstantExecutionSmokeTest.groovy
Labels: @instant-execution, a:feature, from:member, in:gradle-build

#12424 Upgrade embedded Kotlin to 1.3.70
  buildSrc/subprojects/kotlin-dsl/kotlin-dsl.gradle.kts
  gradle/dependencies.gradle
  gradle/verification-metadata.xml
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/KotlinApplicationInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/KotlinLibraryInitIntegrationTest.groovy
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/library-versions.properties
  subprojects/docs/src/docs/userguide/api/kotlin_dsl.adoc
  subprojects/docs/src/docs/userguide/compatibility.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
  subprojects/docs/src/samples/kotlin/application/groovy/build.gradle
  subprojects/docs/src/samples/kotlin/application/kotlin/build.gradle.kts
  subprojects/docs/src/samples/kotlin/library/groovy/build.gradle
  subprojects/docs/src/samples/kotlin/library/kotlin/build.gradle.kts
  subprojects/kotlin-dsl-plugins/kotlin-dsl-plugins.gradle.kts
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginGradlePluginCrossVersionSmokeTest.kt
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/embedded/EmbeddedKotlinPluginTest.kt
  subprojects/kotlin-dsl-plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslCompilerPlugins.kt
  subprojects/kotlin-dsl/kotlin-dsl.gradle.kts
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinBuildScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinInitScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinSettingsScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/KotlinCompiler.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/codegen/GradleApiExtensionsTest.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/integration/KotlinScriptCompilerTest.kt
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaFirstUsePerformanceTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildInstantExecutionSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/android-kotlin-library-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/android-kotlin-library-1.0.pom
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-library-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-library-1.0.pom
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-android-demo-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-android-demo-1.0.pom
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-android-demo-debug-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-android-demo-debug-1.0.pom
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-android-full-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-android-full-1.0.pom
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-android-full-debug-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-android-full-debug-1.0.pom
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-js-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-js-1.0.pom
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-linuxx64-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-linuxx64-1.0.pom
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-macosx64-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-macosx64-1.0.pom
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-library-js-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-library-js-1.0.pom
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-library-jvm-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-library-jvm-1.0.pom
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-library-linuxx64-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-library-linuxx64-1.0.pom
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-library-macosx64-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-library-macosx64-1.0.pom
Labels: @instant-execution, a:chore, from:member, in:gradle-build, in:kotlin-dsl

#6222 Evict expired connections in HTTP client
  subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/HttpClientConfigurer.java
Labels: @core, a:feature, from:contributor, in:core, waiting-for:contributor

#12420 Force current Groovy version in tests for CodeNarc if running in JDK14
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcPluginVersionIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcRelocationIntegrationTest.groovy
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CodeNarcPlugin.java
  subprojects/code-quality/src/testFixtures/groovy/org/gradle/quality/integtest/fixtures/CodeNarcCoverage.groovy
  subprojects/docs/src/snippets/codeQuality/groovy/build.gradle
  subprojects/docs/src/snippets/codeQuality/kotlin/build.gradle.kts
  subprojects/reporting/src/integTest/groovy/org/gradle/api/reporting/plugins/BuildDashboardPluginIntegrationTest.groovy
Labels: @core, from:member, in:core

#12418 Increase performance regression confidence to 0.999
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/BaselineVersion.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/AbstractTablePageGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/PerformanceFlakinessDataProvider.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/Tag.java
  subprojects/internal-performance-testing/src/test/groovy/org/gradle/performance/fixture/CrossVersionPerformanceTestExecutionTest.groovy
Labels: @dev-productivity, a:chore, from:member

#12439 Add experimental JDK14 builds
  .teamcity/Gradle_Check/model/CIBuildModel.kt
Labels: @core, from:member, in:core

#12410 Fix verification file generation
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationWritingIntegTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/writer/WriteDependencyVerificationFile.java
Labels: @jvm, from:member, in:dependency-management

#12399 Improve and document flags for running multi version tests
  build.gradle.kts
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/DistributionTestingPlugin.kt
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractCompatibilityTestRunner.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractContextualMultiVersionSpecRunner.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/CrossVersionTestRunner.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/MultiVersionIntegrationSpec.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/MultiVersionSpecRunner.groovy
  subprojects/platform-native/src/testFixtures/groovy/org/gradle/nativeplatform/fixtures/NativeToolChainTestRunner.java
  subprojects/tooling-api/src/testFixtures/groovy/org/gradle/integtests/tooling/fixture/ToolingApiCompatibilitySuiteRunner.groovy
Labels: from:member, in:gradle-build

#12443 Do not smoke test AspectJ plugin against JDK14 due to incompatible dependency
  subprojects/internal-testing/src/main/groovy/org/gradle/util/TestPrecondition.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ThirdPartyPluginsSmokeTest.groovy
Labels: @core, from:member, in:core

#12445 Enable dependency verification and buildSrc checks in instant execution dogfooding smoke test
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildInstantExecutionSmokeTest.groovy
Labels: @instant-execution, a:chore, from:member

#12444 Polish `WrapperPropertiesLoaderCrossVersionTest`
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/IgnoreVersions.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/TargetVersions.java
  subprojects/wrapper/src/crossVersionTest/groovy/org/gradle/integtests/WrapperCrossVersionIntegrationTest.groovy
  subprojects/wrapper/src/crossVersionTest/groovy/org/gradle/integtests/WrapperPropertiesLoaderCrossVersionTest.groovy
Labels: @instant-execution, a:chore, from:member, in:core

#12448 Handle errors while receiving file changes
  gradle/dependencies.gradle
  gradle/verification-metadata.xml
  subprojects/core/src/main/java/org/gradle/internal/vfs/AbstractEventDrivenFileWatcherRegistry.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultWatchingVirtualFileSystem.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/watch/FileWatcherRegistry.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/watch/impl/NoopFileWatcherRegistry.java
Labels: @build-cache, from:member

#12442 Mention native platform update in upgrade notes
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
Labels: @build-cache, from:member

#12446 Let instant execution load `gradle.properties` from the settings dir
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionBuildOptionsIntegrationTest.groovy
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/DefaultInstantExecution.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/initialization/InstantExecutionStartParameter.kt
Labels: @instant-execution, a:feature, from:member, in:instant-execution

#12432 Upgrade Groovy to version 2.5.10 for JDK14 support
  gradle/dependencies.gradle
  gradle/verification-metadata.xml
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/library-versions.properties
  subprojects/dependency-management/src/testFixtures/groovy/org/gradle/integtests/fixtures/publish/ModuleVersionSpec.groovy
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/release/release-features.txt
  subprojects/docs/src/docs/userguide/compatibility.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
  subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/AbstractSourcesAndJavadocJarsIntegrationTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/AbstractAndroidStudioMockupCrossVersionPerformanceTest.groovy
  subprojects/model-core/src/integTest/groovy/org/gradle/api/provider/PropertyIntegrationTest.groovy
  subprojects/model-core/src/main/java/org/gradle/internal/metaobject/AbstractDynamicObject.java
  subprojects/plugins/src/integTest/groovy/org/gradle/groovy/GroovyJavaLibraryInteractionIntegrationTest.groovy
Labels: @core, from:member, in:core

#12455 Update max Java version to 14 in CI and remove experimental jdk14 pipeline
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/common/JvmCategory.kt
  .teamcity/common/JvmVersion.kt
Labels: @core, from:member, in:core

#12461 Revert "Deactivate log level propagation to java.util.Logging for now"
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/JavaUtilLoggingSystemIntegrationTest.groovy
  subprojects/logging/src/main/java/org/gradle/internal/logging/source/JavaUtilLoggingSystem.java
  subprojects/logging/src/test/groovy/org/gradle/internal/logging/source/JavaUtilLoggingSystemTest.groovy
Labels: @build-cache, from:member

#12484 Refine 6.3 release notes
  subprojects/docs/src/docs/release/notes.md
Labels: a:chore, from:member

#12487 Add a section about Java preview features in user guide
  subprojects/docs/src/docs/userguide/jvm/building_java_projects.adoc
  subprojects/docs/src/snippets/userguide/java/preview/groovy/build.gradle
  subprojects/docs/src/snippets/userguide/java/preview/groovy/settings.gradle
  subprojects/docs/src/snippets/userguide/java/preview/javaFeaturePreview.sample.conf
  subprojects/docs/src/snippets/userguide/java/preview/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/userguide/java/preview/kotlin/settings.gradle.kts
Labels: from:member

#12486 Make Soak/Smoke tests cacheable
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/SmokeTest.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/SoakTest.kt
Labels: @dev-productivity, from:member

#12466 Let instant execution report more unsupported types
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/DependencyNotationIntegrationSpec.groovy
  subprojects/instant-execution/instant-execution.gradle.kts
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionScriptTaskDefinitionIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionUnsupportedTypesIntegrationTest.groovy
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/Logging.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/BindingsBackedCodec.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/Codecs.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/UnsupportedTypesCodecs.kt
Labels: @instant-execution, a:chore, from:member, in:instant-execution

#12491 Restore locking for moveIntoCache method
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementBuildScopeServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/transport/RepositoryTransportFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resource/transfer/DefaultCacheAwareExternalResourceAccessor.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resource/transport/ResourceConnectorRepositoryTransport.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resource/transport/file/FileTransport.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/transport/RepositoryTransportFactoryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/resource/transfer/DefaultCacheAwareExternalResourceAccessorTest.groovy
Labels: @jvm, from:member, in:dependency-management

#12490 Add more context to the metadata rules release notes
  subprojects/docs/src/docs/release/notes.md
Labels: @jvm, from:contributor, from:member

#12498 Disable VFS retention and VFS retention tests on `release`
  gradle.properties
  subprojects/snapshots/src/integTest/groovy/org/gradle/internal/vfs/VirtualFileSystemRetentionIntegrationTest.groovy
  subprojects/soak/src/integTest/groovy/org/gradle/vfs/VirtualFileSystemRetentionSoakTest.groovy
Labels: @build-cache, from:member

#12476 Replace HashMultimap with ArrayListMultimap
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/result/DefaultResolvedComponentResult.java
Labels: @jvm, from:member, in:dependency-management

#12502 Re-enable VFS retention tests
  gradle/dependencies.gradle
  subprojects/snapshots/src/integTest/groovy/org/gradle/internal/vfs/VirtualFileSystemRetentionIntegrationTest.groovy
  subprojects/soak/src/integTest/groovy/org/gradle/vfs/VirtualFileSystemRetentionSoakTest.groovy
Labels: @build-cache, from:member

#12501 Make sure all test files can be removed
  subprojects/dependency-management/dependency-management.gradle.kts
Labels: @jvm, from:member, in:dependency-management

#10981 Repository MetadataSources: add public API to retrieve current state
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/repositories/IvyArtifactRepository.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/repositories/MavenArtifactRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultIvyArtifactRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultMavenArtifactRepository.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/DefaultIvyArtifactRepositoryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/DefaultMavenArtifactRepositoryTest.groovy
Labels: @jvm, a:feature, from:contributor, in:dependency-management

#12482 Print daemon crash log if any exists
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/daemon/DaemonLogsAnalyzer.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/AbstractGradleExecuter.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/GradleExecuter.java
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/ProcessCrashHandlingIntegrationTest.groovy
Labels: @dev-productivity, a:chore, from:member

#12503 Let instant execution be strict by default
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/AbstractInstantExecutionIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionCompositeBuildsIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionJacocoIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionReportIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionScriptTaskDefinitionIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionUnsupportedTypesIntegrationTest.groovy
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/initialization/InstantExecutionStartParameter.kt
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/InstantExecutionGradleExecuter.groovy
Labels: from:member, in:instant-execution

#12504 Remove instant execution workarounds for AGP 3.x
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/Workarounds.kt
Labels: from:member, in:instant-execution

#12508 Remove unused test preconditions
  subprojects/internal-testing/src/main/groovy/org/gradle/util/TestPrecondition.groovy
Labels: @core, a:chore, from:member, in:core

#12489 Junit Platform upgrade
  buildSrc/subprojects/packaging/packaging.gradle.kts
  buildSrc/subprojects/plugins/plugins.gradle.kts
  gradle/dependencies.gradle
  gradle/verification-metadata.xml
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformIntegrationTest.groovy
Labels: @jvm, from:member

#11615 Support for scala compiler plugins.
  subprojects/docs/src/docs/dsl/org.gradle.api.tasks.scala.ScalaCompile.xml
  subprojects/docs/src/docs/userguide/jvm/scala_plugin.adoc
  subprojects/docs/src/snippets/scala/compilerPlugin/compilerPlugin.sample.conf
  subprojects/docs/src/snippets/scala/compilerPlugin/groovy/build.gradle
  subprojects/docs/src/snippets/scala/compilerPlugin/groovy/settings.gradle
  subprojects/docs/src/snippets/scala/compilerPlugin/groovy/src/main/scala/org/gradle/sample/Test.scala
  subprojects/docs/src/snippets/scala/compilerPlugin/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/scala/compilerPlugin/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/scala/compilerPlugin/kotlin/src/main/scala/org/gradle/sample/Test.scala
  subprojects/docs/src/snippets/scala/compilerPlugin/readme.xml
  subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/DefaultScalaJavaJointCompileSpec.java
  subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/ScalaCompileSpec.java
  subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/ZincScalaCompilerArgumentsGenerator.java
  subprojects/language-scala/src/test/groovy/org/gradle/api/internal/tasks/scala/ZincScalaCompilerArgumentsGeneratorTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/ZincScalaCompilerIntegrationTest.groovy
  subprojects/scala/src/main/java/org/gradle/api/plugins/scala/ScalaBasePlugin.java
  subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaCompile.java
  subprojects/scala/src/test/groovy/org/gradle/api/tasks/scala/ScalaCompileTest.groovy
Labels: @jvm, from:contributor

#12509 Let instant execution capture more details of CopySpecs
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/modulecache/StringDeduplicatingDecoder.java
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/DefaultCopySpecCodec.kt
  subprojects/instant-execution/src/test/kotlin/org/gradle/instantexecution/fingerprint/InstantExecutionFingerprintCheckerTest.kt
  subprojects/language-java/src/integTest/groovy/org/gradle/javadoc/JavadocWorkAvoidanceIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/ArchivesContinuousIntegrationTest.groovy
  subprojects/messaging/src/main/java/org/gradle/internal/serialize/AbstractDecoder.java
  subprojects/messaging/src/main/java/org/gradle/internal/serialize/AbstractEncoder.java
  subprojects/messaging/src/main/java/org/gradle/internal/serialize/Decoder.java
  subprojects/messaging/src/main/java/org/gradle/internal/serialize/Encoder.java
Labels: from:member, in:instant-execution

#12512 Remove IBM JDK test preconditions
  subprojects/internal-testing/src/main/groovy/org/gradle/util/TestPrecondition.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/DaemonFeedbackIntegrationSpec.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/DaemonLifecycleSpec.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/server/health/gc/GarbageCollectionMonitoringIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/server/scaninfo/DaemonScanInfoIntegrationSpec.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/groovy/compile/BasicGroovyCompilerIntegrationSpec.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/BasicJavaCompilerIntegrationSpec.groovy
Labels: @core, a:chore, from:member, in:core

#12529 Only add the build finished listener when required
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultDependencyManagementServices.java
Labels: @jvm, from:member, in:dependency-management

#12533 Fix hangs/crashes on Linux and Windows
  gradle/dependencies.gradle
  subprojects/core/src/main/java/org/gradle/internal/vfs/LinuxFileWatcherRegistry.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/watch/FileWatcherRegistryFactory.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/watch/WatchingNotSupportedException.java
Labels: @build-cache, from:member

#12537 Fix handling of transitive aspect of constraints
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/platforms/JavaPlatformResolveIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/GradleDependencyMetadata.java
Labels: @jvm, from:member, in:dependency-management

#12534 Test that we handle symlinks gracefully
  subprojects/snapshots/src/integTest/groovy/org/gradle/internal/vfs/VirtualFileSystemRetentionIntegrationTest.groovy
Labels: @build-cache, from:member

#12544 Use newer native platform snapshot
  gradle/dependencies.gradle
Labels: @build-cache, from:member

#12542 Some cleanup in :instantExecution
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionCompositeBuildsIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionJacocoIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionUnsupportedTypesIntegrationTest.groovy
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/Contexts.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/Workarounds.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/beans/BeanSchema.kt
Labels: from:member, in:instant-execution

#12549 Fix equals() and hashCode() of GradleDependencyMetadata
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/compatibility/ArtifactAndClassifierCompatibilityIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/GradleDependencyMetadata.java
Labels: @jvm, from:member, in:dependency-management

#12559 Refine release notes for native headers location
  subprojects/docs/src/docs/release/notes.md
Labels: from:member

#12567 Trigger sanityCheck for all member PRs
  .teamcity/Gradle_Check/configurations/GradleBuildConfigurationDefaults.kt
  .teamcity/Gradle_Check/configurations/SanityCheck.kt
  .teamcity/Gradle_Check/configurations/StagePasses.kt
  .teamcity/Gradle_Check/configurations/VcsTriggers.kt
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/common/extensions.kt
Labels: @dev-productivity, a:chore, from:member

#12573 Update native platform snapshot
  gradle/dependencies.gradle
Labels: @build-cache, from:member

#12540 Re-enable VFS retention with newer Gradle wrapper
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: @build-cache, from:member

#12578 Proper extra attribute keys disambiguation
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/MultipleCandidateMatcher.java
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/model/ComponentAttributeMatcherTest.groovy
Labels: @jvm, from:member, in:dependency-management

#12577 Let `ValidatePlugins` report the name of the class which triggered a `VerifyError`
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/internal/ValidateAction.java
Labels: a:feature, from:member, in:core

#12526 Assert at least 4 cores at CI environment
  buildSrc/build.gradle.kts
Labels: @dev-productivity, a:chore, from:member

#12562 Use Java Optionals instead of Guava's in PluginRegistry, remove unneeded cast
  subprojects/core/src/main/java/org/gradle/api/internal/plugins/DefaultPluginRegistry.java
Labels: @core, a:chore, from:member, in:core

#12553 Unignore a passing test
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesAntlrIntegrationSpec.groovy
Labels: @core, a:chore, from:member, in:core

#12517 Improve custom plugins documentation page
  subprojects/docs/src/docs/userguide/extending-gradle/custom_plugins.adoc
  subprojects/docs/src/docs/userguide/extending-gradle/custom_tasks.adoc
  subprojects/docs/src/snippets/customExternalTask/groovy/consumer/build.gradle
  subprojects/docs/src/snippets/customExternalTask/groovy/consumer/settings.gradle
  subprojects/docs/src/snippets/customExternalTask/groovy/task/build.gradle
  subprojects/docs/src/snippets/customExternalTask/groovy/task/settings.gradle
  subprojects/docs/src/snippets/customExternalTask/groovy/task/src/main/groovy/org/gradle/GreetingTask.groovy
  subprojects/docs/src/snippets/customExternalTask/groovy/task/src/test/groovy/org/gradle/GreetingTaskTest.groovy
  subprojects/docs/src/snippets/customExternalTask/kotlin/consumer/build.gradle.kts
  subprojects/docs/src/snippets/customExternalTask/kotlin/consumer/settings.gradle.kts
  subprojects/docs/src/snippets/customExternalTask/kotlin/task/build.gradle.kts
  subprojects/docs/src/snippets/customExternalTask/kotlin/task/settings.gradle.kts
  subprojects/docs/src/snippets/customExternalTask/kotlin/task/src/main/groovy/org/gradle/GreetingTask.groovy
  subprojects/docs/src/snippets/customExternalTask/kotlin/task/src/test/groovy/org/gradle/GreetingTaskTest.groovy
  subprojects/docs/src/snippets/customModel/componentType/build.gradle
  subprojects/docs/src/snippets/customModel/languageType/build.gradle
  subprojects/docs/src/snippets/customPlugin/customPluginStandalone.sample.conf.disabled
  subprojects/docs/src/snippets/customPlugin/groovy/consumer/build.gradle
  subprojects/docs/src/snippets/customPlugin/groovy/consumer/settings.gradle
  subprojects/docs/src/snippets/customPlugin/groovy/javaGradlePlugin/build.gradle
  subprojects/docs/src/snippets/customPlugin/groovy/javaGradlePlugin/src/main/groovy/org/gradle/GreetingPlugin.groovy
  subprojects/docs/src/snippets/customPlugin/groovy/javaGradlePlugin/src/main/java/org/gradle/GreetingPlugin.java
  subprojects/docs/src/snippets/customPlugin/groovy/javaGradlePlugin/src/main/java/org/gradle/GreetingTask.java
  subprojects/docs/src/snippets/customPlugin/groovy/plugin/src/main/groovy/org/gradle/GreetingPlugin.groovy
  subprojects/docs/src/snippets/customPlugin/groovy/plugin/src/main/java/org/gradle/GreetingPlugin.java
  subprojects/docs/src/snippets/customPlugin/groovy/plugin/src/main/java/org/gradle/GreetingTask.java
  subprojects/docs/src/snippets/customPlugin/groovy/plugin/src/test/groovy/org/gradle/GreetingPluginTest.groovy
  subprojects/docs/src/snippets/customPlugin/groovy/plugin/src/test/groovy/org/gradle/GreetingTaskTest.groovy
  subprojects/docs/src/snippets/customPlugin/groovy/plugin/src/test/java/org/gradle/GreetingPluginTest.java
  subprojects/docs/src/snippets/customPlugin/groovy/plugin/src/test/java/org/gradle/GreetingTaskTest.java
  subprojects/docs/src/snippets/customPlugin/kotlin/consumer/build.gradle.kts
  subprojects/docs/src/snippets/customPlugin/kotlin/consumer/settings.gradle.kts
  subprojects/docs/src/snippets/customPlugin/kotlin/javaGradlePlugin/build.gradle.kts
  subprojects/docs/src/snippets/customPlugin/kotlin/javaGradlePlugin/src/main/groovy/org/gradle/GreetingPlugin.groovy
  subprojects/docs/src/snippets/customPlugin/kotlin/javaGradlePlugin/src/main/groovy/org/gradle/GreetingTask.groovy
  subprojects/docs/src/snippets/customPlugin/kotlin/javaGradlePlugin/src/main/java/org/gradle/GreetingPlugin.java
  subprojects/docs/src/snippets/customPlugin/kotlin/javaGradlePlugin/src/main/java/org/gradle/GreetingTask.java
  subprojects/docs/src/snippets/customPlugin/kotlin/plugin/src/main/groovy/org/gradle/GreetingPlugin.groovy
  subprojects/docs/src/snippets/customPlugin/kotlin/plugin/src/main/groovy/org/gradle/GreetingTask.groovy
  subprojects/docs/src/snippets/customPlugin/kotlin/plugin/src/main/java/org/gradle/GreetingPlugin.java
  subprojects/docs/src/snippets/customPlugin/kotlin/plugin/src/main/java/org/gradle/GreetingTask.java
  subprojects/docs/src/snippets/customPlugin/kotlin/plugin/src/test/groovy/org/gradle/GreetingPluginTest.groovy
  subprojects/docs/src/snippets/customPlugin/kotlin/plugin/src/test/groovy/org/gradle/GreetingTaskTest.groovy
  subprojects/docs/src/snippets/customPlugin/kotlin/plugin/src/test/java/org/gradle/GreetingPluginTest.java
  subprojects/docs/src/snippets/customPlugin/kotlin/plugin/src/test/java/org/gradle/GreetingTaskTest.java
  subprojects/docs/src/snippets/customPlugin/usingCustomTask.sample.conf.disabled
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesCustomExternalTaskIntegrationTest.groovy
Labels: @core, from:member, in:core, in:docs

#12589 Only run help for vfsRetentionTest
  build.gradle.kts
Labels: @build-cache, from:member

#12585 Run VFS retention tests at least daily
  .teamcity/Gradle_Check/model/CIBuildModel.kt
Labels: @build-cache, from:member

#12007 Pass executable setting to Scala Compiler
  subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/DaemonScalaCompiler.java
  subprojects/language-scala/src/test/groovy/org/gradle/api/internal/tasks/scala/DaemonScalaCompilerTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/ScalaCrossCompilationIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/ZincScalaCompilerIntegrationTest.groovy
Labels: @jvm, from:contributor, in:jvm-ecosystem, in:scala-plugin

#12554 add bazel support in generator
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/generator/BazelFileContentGenerator.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/generator/FileContentGenerator.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/generator/TestProjectGenerator.groovy
Labels: @jvm, from:member

#12592 Do not enable partial invalidation in integTests
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/AbstractGradleExecuter.java
Labels: @build-cache, from:member

#11788 Use normal task dependencies to model build types
  build.gradle.kts
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/buildtypes/BuildTypesPlugin.kt
  buildSrc/subprojects/plugins/src/test/kotlin/org/gradle/plugins/buildtypes/BuildTypesPluginTest.kt
Labels: a:chore, from:member

#12543 Update tested AGP versions
  gradle/dependency-management/agp-versions.properties
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerJavaCachingSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerKotlinCachingSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/android-kotlin-library-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/android-library-1.0.module
Labels: @instant-execution, a:chore, from:member

#12434 Support for compiling Java modules
  subprojects/core-api/src/main/java/org/gradle/api/jpms/ModularClasspathHandling.java
  subprojects/core-api/src/main/java/org/gradle/api/jpms/package-info.java
  subprojects/core/src/main/java/org/gradle/internal/jpms/DefaultModularClasspathHandling.java
  subprojects/core/src/main/java/org/gradle/internal/jpms/JavaModuleDetector.java
  subprojects/core/src/test/groovy/org/gradle/internal/jpms/JavaModuleDetectorTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/cache/internal/TestFileContentCacheFactory.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/JavaCompileMultiTestRunner.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/AbstractModule.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/jpms/ModuleJarFixture.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/maven/AbstractMavenModule.groovy
  subprojects/language-groovy/src/test/groovy/org/gradle/api/internal/tasks/compile/DefaultGroovyJavaJointCompileSpecFactoryTest.groovy
  subprojects/language-groovy/src/test/groovy/org/gradle/api/internal/tasks/compile/NormalizingGroovyCompilerTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractCrossTaskIncrementalJavaCompilationIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/AbstractJavaModuleIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/compile/CachingAndIncrementalJavaModuleCompileIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/compile/JavaModuleCompileIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/compile/JavaModuleCrossCompileIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/compile/MultiProjectJavaModulesCompileIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/compile/MultiSourceSetsJavaModulesCompileIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/compile/MultipleLocalJavaModulesCompileIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/execution/JavaModuleExecutionIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/test/JavaModuleTestingIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/DefaultJavaCompileSpec.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/DefaultJavaCompilerFactory.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompileSpec.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompilerArgumentsBuilder.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/MinimalJavaCompileOptions.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/ModuleApplicationNameWritingCompiler.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/CompileOptions.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
  subprojects/language-java/src/main/java/org/gradle/language/java/internal/JavaLanguagePluginServiceRegistry.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/AnnotationProcessorDiscoveringCompilerTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/CommandLineJavaCompilerArgumentsGeneratorTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/DefaultJavaCompileSpecFactoryTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/DefaultJavaCompilerFactoryTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/JavaCompilerArgumentsBuilderTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/NormalizingJavaCompilerTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/tasks/compile/CompileOptionsTest.groovy
  subprojects/language-jvm/src/main/java/org/gradle/api/internal/tasks/compile/DefaultJvmLanguageCompileSpec.java
  subprojects/language-scala/src/test/groovy/org/gradle/api/internal/tasks/scala/DefaultScalaJavaJointCompileSpecFactoryTest.groovy
  subprojects/language-scala/src/test/groovy/org/gradle/api/internal/tasks/scala/NormalizingScalaCompilerTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaBasePlugin.java
Labels: @jvm, from:member, in:jvm-ecosystem, in:modular-java

#12596 Support for testing Java modules
  subprojects/core/src/integTest/groovy/org/gradle/process/internal/AbstractWorkerProcessIntegrationSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/process/internal/WorkerProcessIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/internal/jpms/JavaModuleDetector.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/BuildSessionScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GradleUserHomeScopeServices.java
  subprojects/core/src/main/java/org/gradle/process/internal/JavaExecHandleBuilder.java
  subprojects/core/src/main/java/org/gradle/process/internal/worker/DefaultMultiRequestWorkerProcessBuilder.java
  subprojects/core/src/main/java/org/gradle/process/internal/worker/DefaultSingleRequestWorkerProcessBuilder.java
  subprojects/core/src/main/java/org/gradle/process/internal/worker/DefaultWorkerProcessBuilder.java
  subprojects/core/src/main/java/org/gradle/process/internal/worker/DefaultWorkerProcessFactory.java
  subprojects/core/src/main/java/org/gradle/process/internal/worker/WorkerProcessBuilder.java
  subprojects/core/src/main/java/org/gradle/process/internal/worker/WorkerProcessSettings.java
  subprojects/core/src/main/java/org/gradle/process/internal/worker/child/ApplicationClassesInSystemClassLoaderWorkerImplementationFactory.java
  subprojects/core/src/main/java/org/gradle/process/internal/worker/child/WorkerImplementationFactory.java
  subprojects/core/src/test/groovy/org/gradle/internal/jpms/JavaModuleDetectorTest.groovy
  subprojects/core/src/test/groovy/org/gradle/process/internal/JavaExecHandleBuilderTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/AbstractJavaModuleCompileIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/AbstractJavaModuleIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/compile/AbstractMultipleLocalJavaModulesCompileIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/compile/JavaModuleCompileIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/compile/MultiProjectJavaModulesCompileIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/compile/MultiSourceSetsJavaModulesCompileIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/execution/JavaModuleExecutionIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/test/AbstractJavaModuleTestingIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/test/JavaModuleBackboxTestExcutionIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/test/JavaModuleTestCompilationIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/test/JavaModuleTestingIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/test/JavaModuleWhiteboxTestExcutionIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
  subprojects/plugins/src/test/groovy/org/gradle/api/tasks/testing/TestTest.groovy
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/ForkingTestClassProcessor.java
  subprojects/testing-base/src/test/groovy/org/gradle/api/internal/tasks/testing/worker/ForkingTestClassProcessorTest.groovy
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/JvmTestExecutionSpec.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/TestFramework.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/detection/DefaultTestClassScanner.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/detection/DefaultTestExecuter.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitTestFramework.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestFramework.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGTestFramework.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java
Labels: @jvm, from:member, in:jvm-ecosystem, in:modular-java

#12579 Use more recent version of JUnit Platform/Jupiter in snippets
  subprojects/docs/src/snippets/testing/junitplatform/engine/groovy/build.gradle
  subprojects/docs/src/snippets/testing/junitplatform/engine/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/testing/junitplatform/jupiter/groovy/build.gradle
  subprojects/docs/src/snippets/testing/junitplatform/jupiter/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/testing/junitplatform/mix/groovy/build.gradle
  subprojects/docs/src/snippets/testing/junitplatform/mix/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/testing/junitplatform/tagging/groovy/build.gradle
  subprojects/docs/src/snippets/testing/junitplatform/tagging/kotlin/build.gradle.kts
Labels: @jvm, from:member

#12521 exclusiveContent can be used in build script block
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/AbstractArtifactRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultMavenArtifactRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultMavenRepositoryContentDescriptor.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultRepositoryContentDescriptor.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/DefaultRepositoryContentDescriptorTest.groovy
  subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/use/DeployedPortalIntegrationSpec.groovy
  subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java
Labels: from:member, in:dependency-management

#12615 Do not cache patchKotlinCompiler for slow internet
  subprojects/kotlin-compiler-embeddable/kotlin-compiler-embeddable.gradle.kts
Labels: @dev-productivity, from:member

#12625 Adjust smoke test builds
  .teamcity/Gradle_Check/model/CIBuildModel.kt
Labels: @dev-productivity, a:chore, from:member

#12610 Upgrade embedded Kotlin version to 1.3.71
  gradle/dependencies.gradle
  gradle/verification-metadata.xml
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/library-versions.properties
  subprojects/core/src/main/java/org/gradle/initialization/exception/DefaultExceptionAnalyser.java
  subprojects/docs/src/docs/userguide/compatibility.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
  subprojects/docs/src/samples/kotlin/application/groovy/build.gradle
  subprojects/docs/src/samples/kotlin/application/kotlin/build.gradle.kts
  subprojects/docs/src/samples/kotlin/library/groovy/build.gradle
  subprojects/docs/src/samples/kotlin/library/kotlin/build.gradle.kts
  subprojects/kotlin-dsl-plugins/kotlin-dsl-plugins.gradle.kts
  subprojects/kotlin-dsl/kotlin-dsl.gradle.kts
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ThirdPartyGradleModuleMetadataSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/android-kotlin-library-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/android-kotlin-library-1.0.pom
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-library-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-library-1.0.pom
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-android-demo-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-android-demo-1.0.pom
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-android-demo-debug-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-android-demo-debug-1.0.pom
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-android-full-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-android-full-1.0.pom
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-android-full-debug-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-android-full-debug-1.0.pom
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-js-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-js-1.0.pom
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-linuxx64-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-linuxx64-1.0.pom
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-macosx64-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-android-library-macosx64-1.0.pom
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-library-js-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-library-js-1.0.pom
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-library-jvm-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-library-jvm-1.0.pom
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-library-linuxx64-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-library-linuxx64-1.0.pom
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-library-macosx64-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-multiplatform-library-macosx64-1.0.pom
Labels: a:feature, from:member, in:kotlin-dsl

#12632 Module path support in generated start scripts
  subprojects/core/src/integTest/groovy/org/gradle/initialization/CalculateTaskGraphBuildOperationIntegrationTest.groovy
  subprojects/distributions/src/changes/accepted-public-api-changes.json
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/ApplicationIntegrationSpec.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/ApplicationPluginConfigurationIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/ApplicationPluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/ApplicationPluginUnixShellsIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/internal/plugins/DefaultJavaAppStartScriptGenerationDetails.java
  subprojects/plugins/src/main/java/org/gradle/api/internal/plugins/StartScriptGenerator.java
  subprojects/plugins/src/main/java/org/gradle/api/internal/plugins/StartScriptTemplateBindingFactory.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/ApplicationPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/tasks/application/CreateStartScripts.java
  subprojects/plugins/src/main/java/org/gradle/jvm/application/scripts/JavaAppStartScriptGenerationDetails.java
  subprojects/plugins/src/main/java/org/gradle/jvm/application/scripts/package-info.java
  subprojects/plugins/src/main/java/org/gradle/jvm/application/tasks/CreateStartScripts.java
  subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
  subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/windowsStartScript.txt
  subprojects/plugins/src/test/groovy/org/gradle/api/internal/plugins/StartScriptGeneratorTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/internal/plugins/UnixStartScriptGeneratorTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/internal/plugins/WindowsStartScriptGeneratorTest.groovy
Labels: @jvm, from:member, in:jvm-ecosystem, in:modular-java

#12626 Clarify dependencies between tests and code coverage
  subprojects/docs/src/docs/userguide/core-plugins/jacoco_plugin.adoc
  subprojects/docs/src/snippets/testing/jacoco/quickstart/groovy/build.gradle
  subprojects/docs/src/snippets/testing/jacoco/quickstart/kotlin/build.gradle.kts
Labels: @jvm, from:member, in:jacoco-plugin

#12642 Add modular classpath handling to Java plugin extension
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/AbstractJavaModuleIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/compile/JavaModuleCompileIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/execution/JavaModuleExecutionIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/test/AbstractJavaModuleTestingIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/ApplicationPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaBasePlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPluginExtension.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/DefaultJavaPluginExtension.java
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/ApplicationPluginTest.groovy
Labels: @jvm, from:member, in:jvm-ecosystem, in:modular-java

#12652 Rebaseline `JavaFirstUsePerformanceTest` after Kotlin upgrade
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaFirstUsePerformanceTest.groovy
Labels: a:chore, a:performance-issue, from:member, in:testing

#11568 Add maxFailures property to PMD (resolves #11557)
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/pmd/PmdPluginVersionIntegrationTest.groovy
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/Pmd.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdExtension.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdPlugin.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/PmdInvoker.groovy
  subprojects/code-quality/src/test/groovy/org/gradle/api/plugins/quality/PmdPluginTest.groovy
  subprojects/docs/src/docs/dsl/org.gradle.api.plugins.quality.Pmd.xml
  subprojects/docs/src/docs/dsl/org.gradle.api.plugins.quality.PmdExtension.xml
Labels: @jvm, from:contributor, in:pmd-plugin

#12648 Add property to configure the `--release` flag
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompilerArgumentsBuilder.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/JavaCompilerArgumentsBuilderTest.groovy
  subprojects/language-jvm/src/main/java/org/gradle/api/internal/tasks/compile/DefaultJvmLanguageCompileSpec.java
  subprojects/language-jvm/src/main/java/org/gradle/api/internal/tasks/compile/JvmLanguageCompileSpec.java
  subprojects/language-jvm/src/main/java/org/gradle/api/tasks/compile/AbstractCompile.java
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/BasicJavaCompilerIntegrationSpec.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaBasePlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPluginExtension.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/DefaultJavaPluginExtension.java
Labels: @jvm, from:member, in:jvm-ecosystem

#12654 Add module path support to Javadoc task
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/javadoc/JavaModuleJavadocIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/tasks/javadoc/Javadoc.java
  subprojects/language-java/src/main/java/org/gradle/external/javadoc/CoreJavadocOptions.java
  subprojects/language-java/src/main/java/org/gradle/external/javadoc/MinimalJavadocOptions.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/DefaultJavaFeatureSpec.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/DefaultJavaPluginExtension.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/JvmPluginsHelper.java
Labels: @jvm, from:member, in:jvm-ecosystem, in:modular-java

#12464 Use task configuration avoidance in the Wrapper docs
  subprojects/docs/src/snippets/userguide/wrapper/customized-task/groovy/build.gradle
  subprojects/docs/src/snippets/userguide/wrapper/customized-task/kotlin/build.gradle.kts
Labels: @core, from:contributor

#12597 Add examples for tasks.withType method to userguide
  subprojects/docs/src/docs/userguide/authoring-builds/more_about_tasks.adoc
  subprojects/docs/src/snippets/userguide/tasks/accessUsingType/accessUsingType.sample.conf
  subprojects/docs/src/snippets/userguide/tasks/accessUsingType/groovy/build.gradle
  subprojects/docs/src/snippets/userguide/tasks/accessUsingType/groovy/settings.gradle
  subprojects/docs/src/snippets/userguide/tasks/accessUsingType/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/userguide/tasks/accessUsingType/kotlin/settings.gradle.kts
Labels: @core, from:contributor

#12667 Fix trivial copy paste error in CodeNarc plugin docs
  subprojects/docs/src/docs/userguide/core-plugins/codenarc_plugin.adoc
Labels: @jvm, from:contributor

#12595 Rework instant execution problem handling to report in build failure when appropriate
  subprojects/base-services/src/main/java/org/gradle/internal/exceptions/DefaultMultiCauseException.java
  subprojects/base-services/src/test/groovy/org/gradle/internal/exceptions/DefaultMultiCauseExceptionTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyErrorIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/AbstractInstantExecutionIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionBuildSrcChangesIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionCompositeBuildsIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionGroovyIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionJacocoIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionParallelTaskExecutionIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionReportIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionScriptTaskDefinitionIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionUnsupportedTypesIntegrationTest.groovy
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/DefaultInstantExecution.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/InstantExecutionException.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/InstantExecutionReport.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/InstantExecutionServices.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/extensions/ExceptionExtensions.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/extensions/ListenerManagerExtensions.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/initialization/InstantExecutionProjectAccessListener.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/problems/InstantExecutionProblems.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/problems/ProblemDescription.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/problems/ProblemsListener.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/problems/ProblemsSummary.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/problems/PropertyProblem.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/Codec.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/Contexts.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/Logging.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/beans/BeanPropertyReader.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/beans/BeanPropertyWriter.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/TaskNodeCodec.kt
  subprojects/instant-execution/src/test/kotlin/org/gradle/instantexecution/fingerprint/InstantExecutionFingerprintCheckerTest.kt
  subprojects/instant-execution/src/test/kotlin/org/gradle/instantexecution/problems/PropertyTraceTest.kt
  subprojects/instant-execution/src/test/kotlin/org/gradle/instantexecution/serialization/codecs/UserTypesCodecTest.kt
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/instantexecution/InstantExecutionBuildOperationsFixture.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/instantexecution/InstantExecutionProblemsFixture.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildInstantExecutionSmokeTest.groovy
Labels: from:member, in:instant-execution
