Repository gradle/gradle, pull requests merged in 2020-10, with the labels that each got.

#14700 Use daemon for parallel download tests
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ParallelDownloadsPerformanceTest.groovy
Labels: @execution, from:member

#14702 Add windows and macos performance tests on release
  .teamcity/Gradle_Check/configurations/PerformanceTest.kt
  .teamcity/Gradle_Check/configurations/PerformanceTestsPass.kt
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/Gradle_Check/model/PerformanceTestBucketProvider.kt
  .teamcity/Gradle_Check/model/PerformanceTestCoverage.kt
  .teamcity/Gradle_Check/model/bucket-extensions.kt
  .teamcity/Gradle_Check/projects/PerformanceTestProject.kt
  .teamcity/performance-tests-ci.json
  .teamcityTest/Gradle_Check_Tests/PerformanceTestBuildTypeTest.kt
Labels: @execution, from:member

#14721 Run macOs/Windows performance tests automatically
  .teamcity/Gradle_Check/model/CIBuildModel.kt
Labels: @execution, from:member

#14716 Clean up language-java subproject
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/AbstractJavaToolChain.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/analyzer/CachingClassDependenciesAnalyzer.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/analyzer/ClassAnalysisSerializer.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/analyzer/DefaultClassDependenciesAnalyzer.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/asm/ClassDependenciesVisitor.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/asm/ClassRelevancyFilter.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/classpath/ClasspathEntrySnapshot.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/classpath/ClasspathEntrySnapshotDataSerializer.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/classpath/ClasspathSnapshotDataSerializer.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/classpath/ClasspathSnapshotFactory.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/classpath/DefaultClasspathEntrySnapshotter.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/classpath/SplitClasspathEntrySnapshotCache.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassDependentsAccumulator.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisData.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/DependentsSet.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/processing/AnnotationProcessingData.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/processing/AnnotationProcessingResult.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/processing/GeneratedResourceSerializer.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/ClasspathChangeDependentsFinder.java
Labels: a:chore, from:member

#14718 Cleanup build logic around performance tests
  .teamcity/Gradle_Check/configurations/IndividualPerformanceScenarioWorkers.kt
  .teamcity/Gradle_Check/configurations/PerformanceTestCoordinator.kt
  .teamcity/Gradle_Check/configurations/PerformanceTestsPass.kt
  .teamcity/Gradle_Check/projects/RootProject.kt
  .teamcity/Gradle_Check/projects/StageProject.kt
  .teamcity/Gradle_Check/projects/WorkersProject.kt
  .teamcity/Gradle_Util_Performance/Project.kt
  .teamcity/Gradle_Util_Performance/buildTypes/AdHocPerformanceTestCoordinator.kt
  .teamcityTest/Gradle_Check_Tests/CIConfigIntegrationTests.kt
  .teamcityTest/Gradle_Check_Tests/PerformanceTestBuildTypeTest.kt
  buildSrc/subprojects/buildquality/src/main/kotlin/gradlebuild.ci-reporting.gradle.kts
  buildSrc/subprojects/performance-testing/build.gradle.kts
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild.performance-templates.gradle
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild/performance/CoordinatorBuild.groovy
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild/performance/JUnitXmlTestEventsGenerator.groovy
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild/performance/PerformanceTestService.java
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild/performance/ScenarioReportRenderer.groovy
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild/performance/reporter/DefaultPerformanceReporter.groovy
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild/performance/reporter/PerformanceReporter.groovy
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild/performance/rerun/PerformanceScenarioRerunStrategy.java
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild/performance/rerun/RetryFailedRerunStrategy.java
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild/performance/tasks/DistributedPerformanceTest.groovy
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild/performance/tasks/PerformanceTest.groovy
  buildSrc/subprojects/performance-testing/src/main/kotlin/gradlebuild/performance/PerformanceTestPlugin.kt
  buildSrc/subprojects/performance-testing/src/main/kotlin/gradlebuild/performance/tasks/PerformanceTestReport.kt
  buildSrc/subprojects/performance-testing/src/test/groovy/gradlebuild/performance/AbstractIntegrationTest.groovy
  buildSrc/subprojects/performance-testing/src/test/groovy/gradlebuild/performance/JUnitXmlTestEventsGeneratorTest.groovy
  buildSrc/subprojects/performance-testing/src/test/groovy/gradlebuild/performance/PerformanceTestIntegrationTest.groovy
  buildSrc/subprojects/performance-testing/src/test/groovy/gradlebuild/performance/RepeatRerunStrategyTest.groovy
  buildSrc/subprojects/performance-testing/src/test/groovy/gradlebuild/performance/RetryFailedRerunStrategyTest.groovy
  buildSrc/subprojects/performance-testing/src/test/resources/org/gradle/testing/TEST-sample.xml
  buildSrc/subprojects/performance-testing/src/test/resources/org/gradle/testing/sample-build-result-failure.xml
  buildSrc/subprojects/performance-testing/src/test/resources/org/gradle/testing/sample-build-result-success.xml
  subprojects/build-scan-performance/build.gradle.kts
Labels: @execution, from:member

#14680 Clarify explanation about overlapping outputs
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/tasks/TaskCacheabilityReasonIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/DefaultTaskCacheabilityResolver.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/DefaultTaskCacheabilityResolverTest.groovy
Labels: @execution, from:contributor

#14738 Add performance test triggers without dependencies
  .teamcity/Gradle_Check/configurations/PerformanceTest.kt
  .teamcity/Gradle_Check/configurations/PerformanceTestsPass.kt
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/Gradle_Check/projects/PerformanceTestProject.kt
Labels: @execution, from:member

#14743 Kill daemon leftover by Windows perf tests on substituted drive
  buildSrc/subprojects/cleanup/src/main/kotlin/gradlebuild/cleanup/services/LeakingProcessKillPattern.kt
  buildSrc/subprojects/cleanup/src/test/groovy/gradlebuild/cleanup/services/LeakingProcessKillPatternTest.groovy
Labels: @execution, from:member

#14746 Clean buildSrc before and after build on subst drive
  .teamcity/Gradle_Check/configurations/PerformanceTest.kt
  .teamcity/Gradle_Util_Performance/buildTypes/AdHocPerformanceScenario.kt
  .teamcity/common/performance-test-extensions.kt
Labels: @execution, from:member

#14747 Remove Gradle 3.4 version check from performance test templates
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/generator/FileContentGenerator.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/generator/GroovyDslFileContentGenerator.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/generator/KotlinDslFileContentGenerator.groovy
Labels: a:chore, from:member

#14723 Tentative fix for classloading issue in annotation processing
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/AggregatingProcessingStrategy.java
Labels: @jvm, in:jvm-ecosystem

#14745 Fix typo in multiproject sample readme
  subprojects/docs/src/samples/readme-templates/multi-common-body.adoc.template
Labels: a:chore, from:member, in:docs

#14753 Synchronize access to provisioning within daemon
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/install/internal/DefaultJavaToolchainProvisioningService.java
Labels: @jvm, from:member

#14748 Move ApiClassExtractor instantiation to a field
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/AbiExtractingClasspathResourceHasher.java
Labels: a:chore, from:member

#14696 Remove release bias in LatestModuleConflictResolver
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementBuildScopeServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/ConflictResolverFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/DefaultArtifactDependencyResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/LatestModuleConflictResolver.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/LatestModuleConflictResolverTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/selectors/SelectorStateResolverTest.groovy
Labels: @jvm, in:dependency-management

#14763 Refine `JavaExecMainClassIntegrationTest`
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecMainClassIntegrationTest.groovy
Labels: @configuration-cache, a:chore, from:member, in:configuration-cache

#14754 Follow up on allocating workspace in execution engine
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskInputs.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuter.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/InputParameterUtils.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java
  subprojects/execution/src/integTest/groovy/org/gradle/internal/execution/IncrementalExecutionIntegrationTest.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/UnitOfWork.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/impl/InputFingerprintUtil.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CaptureStateBeforeExecutionStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/IdentifyStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ResolveChangesStep.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CaptureStateBeforeExecutionStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/IdentifyStepTest.groovy
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/AccessorsClassPath.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/PluginAccessorsClassPath.kt
Labels: @execution, from:member

#14771 Suppress deprecation warnings in precompiled script plugin accessors
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/precompiled/PrecompiledScriptPluginAccessorsTest.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/codegen/SourceFileHeader.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/codegen/GradleApiExtensionsTest.kt
  subprojects/kotlin-dsl/src/testFixtures/kotlin/org/gradle/kotlin/dsl/fixtures/AbstractKotlinIntegrationTest.kt
Labels: a:bug, from:member, in:kotlin-dsl

#14712 Always close project connection in test
  subprojects/tooling-api/src/integTest/groovy/org/gradle/integtests/tooling/ToolingApiClientJdkCompatibilityTest.groovy
Labels: a:bug, from:member, in:testing

#14749 Capture GC times in performance tests
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild/performance/reporter/PerformanceReporter.groovy
  gradle/verification-metadata.xml
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/AbstractBuildExperimentRunner.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/AbstractCrossBuildPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/CrossVersionPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleBuildExperimentRunner.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleBuildExperimentSpec.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/MavenBuildExperimentRunner.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/TestScenarioSelector.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/GradleProfilerReporter.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/PerformanceExperiment.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/PerformanceScenario.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/PerformanceTestResult.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/DefaultReportGenerator.java
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/FileSystemWatchingPerformanceTest.groovy
Labels: @execution, from:member

#14769 Upgrade tested AGP versions and smoke test lint task
  gradle/dependency-management/agp-versions.properties
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractAndroidSantaTrackerSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerJavaCachingSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerKotlinCachingSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy
Labels: @configuration-cache, a:chore, from:member

#14780 Smoke test shadow 6.1.0
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ThirdPartyPluginsSmokeTest.groovy
Labels: @configuration-cache, a:chore, from:member

#14762 Implement performance test checking non-abi change in buildSrc
  .teamcity/performance-test-durations.json
  .teamcity/performance-tests-ci.json
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/inception/BuildSrcApiChangePerformanceTest.groovy
Labels: @idiomatic, from:member

#14775 Expand example for implementing tasks/plugins accepting a toolchain
  subprojects/docs/src/docs/userguide/jvm/toolchains.adoc
  subprojects/docs/src/snippets/java/toolchain-task/groovy/build.gradle
  subprojects/docs/src/snippets/java/toolchain-task/groovy/settings.gradle
  subprojects/docs/src/snippets/java/toolchain-task/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/java/toolchain-task/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/java/toolchain-task/tests/toolchainTask.sample.conf
Labels: @jvm, from:member

#14789 Add `@LeaksFileHandles` to cross version performance tests using the TAPI
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/AbstractCrossBuildPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/CrossVersionPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleBuildExperimentRunner.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/PerformanceTestGradleDistribution.groovy
  subprojects/performance/build.gradle.kts
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/FileSystemWatchingPerformanceTest.groovy
Labels: @execution, from:member

#14765 Follow up cleanups for file system watching
  subprojects/core/src/test/groovy/org/gradle/internal/fingerprint/impl/AbsolutePathFileCollectionFingerprinterTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/api/internal/file/TestFiles.java
  subprojects/core/src/testFixtures/groovy/org/gradle/api/internal/file/TestVirtualFileSystem.java
  subprojects/execution/src/integTest/groovy/org/gradle/internal/execution/IncrementalExecutionIntegrationTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/impl/OutputFilterUtilTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesDuringTheBuildFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingNotSupportedVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdaterTest.groovy
  subprojects/language-native/src/test/groovy/org/gradle/language/nativeplatform/internal/incremental/IncrementalCompileProcessorTest.groovy
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunner.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/VirtualFileSystem.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java
Labels: @execution, from:member

#14791 Refine KotlinDslPluginGradlePluginCrossVersionSmokeTest
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginGradlePluginCrossVersionSmokeTest.kt
Labels: @configuration-cache, a:chore, from:member, in:kotlin-dsl

#14792 Bump kotlin-dsl plugins version
  buildSrc/subprojects/kotlin-dsl/src/main/kotlin/gradlebuild.kotlin-dsl-dependencies-embedded.gradle.kts
  gradle/verification-metadata.xml
  subprojects/kotlin-dsl-plugins/build.gradle.kts
Labels: @configuration-cache, a:chore, from:member, in:kotlin-dsl

#14794 Document memory setting of performance tests
  buildSrc/subprojects/performance-testing/src/main/kotlin/gradlebuild/performance/PerformanceTestPlugin.kt
Labels: @execution, from:member

#14796 Set correct permissions on included build state files
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheCompositeBuildsIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheIO.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheRepository.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultConfigurationCache.kt
Labels: @configuration-cache, a:feature, from:member, in:configuration-cache

#14534 Add classpath for all sourceSets to Eclipse by default
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
  subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/eclipse/EclipseSourceSetIntegrationSpec.groovy
  subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/EclipsePlugin.java
  subprojects/ide/src/test/groovy/org/gradle/plugins/ide/eclipse/EclipsePluginTest.groovy
Labels: from:member, in:eclipse-plugin

#14793 Fix the Windows file system watching performance test
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/FileSystemWatchingPerformanceTest.groovy
Labels: @execution, from:member

#14806 Fix `BuildSrcApiChangePerformanceTest`
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/AbstractCrossBuildPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/CrossVersionPerformanceTestRunner.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/inception/BuildSrcApiChangePerformanceTest.groovy
Labels: @dev-productivity, from:member

#14785 Fix Kotlin Script File Patterns
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinBuildScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinInitScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinSettingsScript.kt
Labels: from:contributor, in:kotlin-dsl

#14795 Do not run promotion builds on EC2 agents
  .teamcity/Gradle_Promotion/buildTypes/BasePromotionBuildType.kt
  .teamcity/Gradle_Promotion/buildTypes/PublishGradleDistribution.kt
  .teamcity/common/extensions.kt
  .teamcity/common/performance-test-extensions.kt
Labels: @dev-productivity, from:member

#14810 Run Windows performance tests as part of Ready for Nightly
  .teamcity/Gradle_Check/configurations/PerformanceTestsPass.kt
  .teamcity/Gradle_Check/configurations/StagePasses.kt
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/Gradle_Check/model/PerformanceTestCoverage.kt
Labels: @execution, from:member

#14813 Fix resources being deleted even if they shouldn't
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/AggregatingIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/processing/AnnotationProcessingData.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisTest.groovy
Labels: @jvm, a:bug, from:member, in:jvm-ecosystem

#14816 Let configuration cache key include `--include-build` and `--settings-file`
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheKey.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/ConfigurationCacheStartParameter.kt
  subprojects/configuration-cache/src/test/kotlin/org/gradle/configurationcache/ConfigurationCacheKeyTest.kt
Labels: @configuration-cache, a:feature, from:member, in:configuration-cache

#14817 Add `@NonNullApi` to `org.gradle.initialization`
  subprojects/core/src/main/java/org/gradle/initialization/BuildOperationFiringSettingsPreparer.java
  subprojects/core/src/main/java/org/gradle/initialization/package-info.java
Labels: @configuration-cache, a:chore, from:member, in:core

#14735 Do not recompile Kotlin buildscripts for non-ABI changes in classpath
  subprojects/core/src/main/java/org/gradle/api/internal/initialization/loadercache/CompileClasspathHasher.java
  subprojects/core/src/main/java/org/gradle/api/internal/initialization/loadercache/package-info.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/classpath/impl/DefaultCompileClasspathFingerprinter.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/kotlin-dsl/build.gradle.kts
  subprojects/kotlin-dsl/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/BuildScriptCompileAvoidanceIntegrationTest.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/execution/Interpreter.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/execution/ProgramId.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/normalization/KotlinApiClassExtractor.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/BuildServices.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/KotlinScriptEvaluator.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/ScriptCacheRepository.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/execution/InterpreterTest.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/normalization/KotlinApiClassExtractorTest.kt
  subprojects/kotlin-dsl/src/testFixtures/kotlin/org/gradle/kotlin/dsl/fixtures/SimplifiedKotlinScriptEvaluator.kt
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/AbiExtractingClasspathResourceHasher.java
  subprojects/normalization-java/src/main/java/org/gradle/internal/normalization/java/ApiClassExtractor.java
  subprojects/normalization-java/src/main/java/org/gradle/internal/normalization/java/ApiMemberWriterFactory.java
  subprojects/normalization-java/src/main/java/org/gradle/internal/normalization/java/impl/ApiMemberSelector.java
  subprojects/normalization-java/src/main/java/org/gradle/internal/normalization/java/impl/ApiMemberWriter.java
Labels: @idiomatic, a:performance-issue, from:member, in:kotlin-dsl

#14820 Polish KotlinDSL compilation avoidance release note
  subprojects/docs/src/docs/release/notes.md
Labels: @idiomatic, from:member, in:docs

#14821 Cleanup KotlinApiClassExtractor
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/normalization/KotlinApiClassExtractor.kt
Labels: from:member, in:kotlin-dsl

#14811 Measure work execution time in Santa Tracker performance test for FSW
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/FasterIncrementalAndroidBuildsPerformanceTest.groovy
Labels: @execution, from:member

#14782 build-init should generate projects with "--split-project" option set to false without requiring user input
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/MultiProjectJvmApplicationInitIntegrationTest.groovy
  subprojects/build-init/src/main/java/org/gradle/buildinit/tasks/InitBuild.java
Labels: a:bug, from:member, in:build-init-plugin

#14826 Toolchains documentation
  subprojects/docs/src/docs/userguide/jvm/toolchains.adoc
  subprojects/docs/src/snippets/java/toolchain-kotlin/groovy/build.gradle
  subprojects/docs/src/snippets/java/toolchain-kotlin/groovy/settings.gradle
  subprojects/docs/src/snippets/java/toolchain-kotlin/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/java/toolchain-kotlin/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/java/toolchain-kotlin/tests/toolchainKotlin.sample.conf
  subprojects/docs/src/snippets/java/toolchain-task/groovy/build.gradle
  subprojects/docs/src/snippets/java/toolchain-task/kotlin/build.gradle.kts
Labels: @jvm, in:docs, in:jvm-ecosystem

#14828 Set minimum version for test for non-abi change to 4.0
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaTestChangePerformanceTest.groovy
Labels: @dev-productivity, from:member

#14827 Handle Kotlin multifile class metadata in buildscript compile avoidance
  subprojects/kotlin-dsl/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/BuildScriptCompileAvoidanceIntegrationTest.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/normalization/KotlinApiClassExtractor.kt
Labels: @idiomatic, a:bug, from:member, in:kotlin-dsl

#14807 Add evaluated init scripts to KotlinDslScriptsModel (#12640)
  subprojects/kotlin-dsl-tooling-builders/build.gradle.kts
  subprojects/kotlin-dsl-tooling-builders/src/crossVersionTest/groovy/org/gradle/kotlin/dsl/tooling/builders/AbstractKotlinScriptModelCrossVersionTest.groovy
  subprojects/kotlin-dsl-tooling-builders/src/crossVersionTest/groovy/org/gradle/kotlin/dsl/tooling/builders/r60/KotlinDslScriptsModelCrossVersionSpec.groovy
  subprojects/kotlin-dsl-tooling-builders/src/crossVersionTest/groovy/org/gradle/kotlin/dsl/tooling/builders/r68/KotlinDslScriptsModelCrossVersionSpec.groovy
  subprojects/kotlin-dsl-tooling-builders/src/main/kotlin/org/gradle/kotlin/dsl/tooling/builders/KotlinDslScriptsModelBuilder.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/KotlinScriptType.kt
Labels: from:contributor, in:kotlin-dsl

#14834 Fall back to hashing the whole jar on unknown Kotlin metadata when extracting Kotlin's ABI
  subprojects/kotlin-dsl/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/BuildScriptCompileAvoidanceIntegrationTest.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/normalization/KotlinApiClassExtractor.kt
Labels: @idiomatic, from:member, in:kotlin-dsl

#14843 Set FSW performance baseline to 6.8-milestone-1
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/FasterIncrementalAndroidBuildsPerformanceTest.groovy
Labels: @execution, from:member

#14815 Fix the removal of empty text nodes in the DOM based XML transformer
  subprojects/core/src/main/java/org/gradle/internal/xml/XmlTransformer.java
  subprojects/core/src/test/groovy/org/gradle/internal/xml/XmlTransformerTest.groovy
Labels: from:contributor, in:publishing-plugin

#14852 Allow using async-profiler-alloc in performance tests
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/AbstractBuildExperimentRunner.java
Labels: @dev-productivity, from:member

#14842 Polish Kotlin DSL plugin accessor generation
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/AccessorsClassPath.kt
Labels: @execution, from:member

#14841 Update tested AGP version from 4.1.0-rc03 to 4.1.0
  gradle/dependency-management/agp-versions.properties
Labels: a:chore, from:member

#14864 Ensure buildSrc/build.gradle.kts is not cached between tests in compile avoidance test
  subprojects/kotlin-dsl/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/BuildScriptCompileAvoidanceIntegrationTest.kt
Labels: @idiomatic, from:member

#14464 Update project README to link to samples instead of guides
  README.md
Labels: @idiomatic, from:member

#14572 Update component_capabilities.adoc
  subprojects/docs/src/docs/userguide/dep-man/04-modeling-features/component_capabilities.adoc
Labels: @jvm, from:contributor, in:dependency-management, in:docs

#14863 Set module name in the Kotlin metadata emitted for generated accessors
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/AccessorFragments.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/Emitter.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/PluginAccessorsClassPath.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/bytecode/KotlinMetadata.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/accessors/KotlinMetadataPrintingVisitor.kt
Labels: @configuration-cache, a:feature, from:member, in:kotlin-dsl

#14867 Apply `sam-with-receiver` plugin to `kotlin-dsl`
  buildSrc/subprojects/kotlin-dsl/build.gradle.kts
  buildSrc/subprojects/kotlin-dsl/src/main/kotlin/gradlebuild.kotlin-dsl-sam-with-receiver.gradle.kts
  subprojects/configuration-cache/build.gradle.kts
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/ListenerBroadcastCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/transform/TransformedExternalArtifactSetCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/transform/Transforms.kt
  subprojects/kotlin-dsl/build.gradle.kts
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/DependencyHandlerScope.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/PluginAwareExtensions.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/RepositoryHandlerExtensions.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/runtime/Runtime.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/cache/ScriptCache.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/resolver/SourceDistributionProvider.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/EmbeddedKotlinProvider.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/ComponentSelectionRulesTest.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/DependencyHandlerExtensionsTest.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/NamedContainersDslTest.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/NamedDomainObjectCollectionExtensionsTest.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/NamedDomainObjectContainerExtensionsTest.kt
Labels: a:chore, from:member, in:gradle-build, in:kotlin-dsl

#14868 Prefer `Action<T>` to `T.() -> Unit` for Kotlin DSL accessors
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/AllDistributionIntegrationSpec.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DocsDistributionIntegrationSpec.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/SrcDistributionIntegrationSpec.groovy
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/NamedDomainObjectContainerExtensions.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/AccessorFragments.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/CodeGenerator.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/accessors/ProjectAccessorsClassPathTest.kt
  subprojects/kotlin-dsl/src/test/resources/org/gradle/kotlin/dsl/accessors/tasks/PrintAccessors-expected-output.txt
Labels: a:feature, from:member, in:kotlin-dsl

#14886 Add a trigger to profile a performance test
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/Gradle_Check/model/PerformanceTestBucketProvider.kt
  .teamcity/Gradle_Check/projects/PerformanceTestProject.kt
  .teamcity/Gradle_Check/projects/StageProject.kt
Labels: @execution, from:member

#14858 Refine smoke test configurations
  .teamcity/Gradle_Check/configurations/SmokeTests.kt
  buildSrc/subprojects/lifecycle/src/main/kotlin/gradlebuild.lifecycle.gradle.kts
Labels: @dev-productivity, from:member

#14851 Use G1 GC when running BuildSrcApiChangePerformanceTest on Java 8
  .teamcity/performance-test-durations.json
  .teamcity/performance-tests-ci.json
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/inception/BuildSrcApiChangePerformanceTest.groovy
Labels: from:member, in:testing

#14873 Move CI integration docs from 'gradle.org/guides' to user manual
  subprojects/docs/src/docs/userguide/img/ci-systems/jenkins-build-scan.png
  subprojects/docs/src/docs/userguide/img/ci-systems/jenkins-build-step.png
  subprojects/docs/src/docs/userguide/img/ci-systems/jenkins-scm.png
  subprojects/docs/src/docs/userguide/img/ci-systems/teamcity-build-results.png
  subprojects/docs/src/docs/userguide/img/ci-systems/teamcity-build-scan-plugin.png
  subprojects/docs/src/docs/userguide/img/ci-systems/teamcity-build-step.png
  subprojects/docs/src/docs/userguide/img/ci-systems/teamcity-create-project.png
  subprojects/docs/src/docs/userguide/img/ci-systems/teamcity-log-link.png
  subprojects/docs/src/docs/userguide/img/ci-systems/teamcity-results.png
  subprojects/docs/src/docs/userguide/img/ci-systems/teamcity-scan.png
  subprojects/docs/src/docs/userguide/img/ci-systems/teamcity-step-added.png
  subprojects/docs/src/docs/userguide/img/ci-systems/teamcity-step-edit.png
  subprojects/docs/src/docs/userguide/img/ci-systems/teamcity-step-upd.png
  subprojects/docs/src/docs/userguide/img/ci-systems/teamcity-tests.png
  subprojects/docs/src/docs/userguide/img/ci-systems/travis-enable-project.png
  subprojects/docs/src/docs/userguide/reference/ci-systems/jenkins.adoc
  subprojects/docs/src/docs/userguide/reference/ci-systems/teamcity.adoc
  subprojects/docs/src/docs/userguide/reference/ci-systems/travis-ci.adoc
  subprojects/docs/src/docs/userguide/reference/third_party_integration.adoc
  subprojects/docs/src/main/resources/header.html
Labels: @idiomatic, from:member, in:docs

#14909 Rename WorkExecutor to ExecutionEngine
  subprojects/core/src/integTest/groovy/org/gradle/api/ContainerElementServiceInjectionIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/ObjectExtensionServiceInjectionIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/PluginServiceInjectionIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuter.java
  subprojects/core/src/main/java/org/gradle/execution/ProjectExecutionServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/ExecutionGradleServices.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuterTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultDependencyManagementServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactoryTest.groovy
  subprojects/execution/src/integTest/groovy/org/gradle/internal/execution/IncrementalExecutionIntegrationTest.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/ExecutionEngine.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/impl/DefaultExecutionEngine.java
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/AccessorsClassPath.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/GradleScopeServices.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/PluginAccessorsClassPath.kt
Labels: @execution, from:member

#14836 VFS statistics
  subprojects/core/src/main/java/org/gradle/api/internal/StartParameterInternal.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/CachingFileHasher.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/FileHasherStatistics.java
  subprojects/core/src/main/java/org/gradle/initialization/StartParameterBuildOptions.java
  subprojects/core/src/main/java/org/gradle/internal/hash/DefaultChecksumService.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java
  subprojects/core/src/main/java/org/gradle/internal/session/BuildSessionScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/changedetection/state/CachingFileHasherTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/api/internal/file/TestFiles.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdaterTest.groovy
  subprojects/files/src/main/java/org/gradle/internal/file/StatStatistics.java
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/action/BuildActionSerializer.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunner.java
  subprojects/launcher/src/test/groovy/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunnerTest.groovy
  subprojects/native/src/main/java/org/gradle/internal/nativeintegration/filesystem/services/FileSystemServices.java
  subprojects/native/src/main/java/org/gradle/internal/nativeintegration/filesystem/services/GenericFileSystem.java
  subprojects/native/src/test/groovy/org/gradle/internal/nativeintegration/filesystem/services/GenericFileSystemTest.groovy
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/impl/DirectorySnapshotter.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/impl/DirectorySnapshotterStatistics.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterAsDirectoryWalkerTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterStatisticsTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/vfs/impl/AbstractFileSystemAccessTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/vfs/impl/DefaultSnapshotHierarchyTest.groovy
Labels: @execution, from:member

#14904 Move 'Improving Performance of Gradle Builds' into user manual
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/AllDistributionIntegrationSpec.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DocsDistributionIntegrationSpec.groovy
  subprojects/docs/src/docs/userguide/api/kotlin_dsl.adoc
  subprojects/docs/src/docs/userguide/developing-plugins/designing_gradle_plugins.adoc
  subprojects/docs/src/docs/userguide/img/performance/bad-dependency-resolution.png
  subprojects/docs/src/docs/userguide/img/performance/build-scan-configuration-breakdown.png
  subprojects/docs/src/docs/userguide/img/performance/build-scan-home.png
  subprojects/docs/src/docs/userguide/img/performance/build-scan-performance-page.png
  subprojects/docs/src/docs/userguide/img/performance/build-scan-url.png
  subprojects/docs/src/docs/userguide/img/performance/cache-performance.png
  subprojects/docs/src/docs/userguide/img/performance/dependency-dynamic-versions.png
  subprojects/docs/src/docs/userguide/img/performance/gradle-profile-report.png
  subprojects/docs/src/docs/userguide/img/performance/parallel-task-fast.png
  subprojects/docs/src/docs/userguide/img/performance/parallel-task-slow.png
  subprojects/docs/src/docs/userguide/img/performance/script-a-application.png
  subprojects/docs/src/docs/userguide/img/performance/script-b-application.png
  subprojects/docs/src/docs/userguide/img/performance/slow-dependency-downloads.png
  subprojects/docs/src/docs/userguide/img/performance/task-execution-cacheable.png
  subprojects/docs/src/docs/userguide/img/performance/tests-longest.png
  subprojects/docs/src/docs/userguide/img/performance/timeline-not-cacheable.png
  subprojects/docs/src/docs/userguide/img/performance/timeline.png
  subprojects/docs/src/docs/userguide/migration/migrating_from_maven.adoc
  subprojects/docs/src/docs/userguide/reference/command_line_interface.adoc
  subprojects/docs/src/docs/userguide/running-builds/build_environment.adoc
  subprojects/docs/src/docs/userguide/running-builds/performance.adoc
  subprojects/docs/src/docs/userguide/troubleshooting.adoc
  subprojects/docs/src/main/resources/header.html
  subprojects/docs/src/snippets/performance/parallelTestExecution/groovy/build.gradle
  subprojects/docs/src/snippets/performance/parallelTestExecution/groovy/settings.gradle
  subprojects/docs/src/snippets/performance/parallelTestExecution/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/performance/parallelTestExecution/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/performance/resolveAtBuildTime/groovy/build.gradle
  subprojects/docs/src/snippets/performance/resolveAtBuildTime/groovy/settings.gradle
  subprojects/docs/src/snippets/performance/resolveAtBuildTime/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/performance/resolveAtBuildTime/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/performance/resolveAtConfigurationTime/groovy/build.gradle
  subprojects/docs/src/snippets/performance/resolveAtConfigurationTime/groovy/settings.gradle
  subprojects/docs/src/snippets/performance/resolveAtConfigurationTime/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/performance/resolveAtConfigurationTime/kotlin/settings.gradle.kts
Labels: @idiomatic, from:member, in:docs

#14837 Replace path to parent by a child map
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/AbstractCompleteFileSystemLocationSnapshot.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/AbstractFileSystemNode.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/AbstractIncompleteSnapshotWithChildren.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/AbstractInvalidateChildHandler.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/AbstractListChildMap.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/AbstractStorePathRelationshipHandler.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/ChildMap.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/ChildMapFactory.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/CompleteDirectorySnapshot.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/EmptyChildMap.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/FileSystemNode.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/LargeChildMap.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/MediumChildMap.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/MetadataSnapshot.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/MissingFileSnapshot.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PartialDirectorySnapshot.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/RegularFileSnapshot.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SingletonChildMap.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SnapshotUtil.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/UnknownSnapshot.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/VfsRelativePath.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultSnapshotHierarchy.java
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/AbstractIncompleteSnapshotWithChildrenTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/AbstractSnapshotWithChildrenTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/CompleteDirectorySnapshotTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/PartialDirectorySnapshotTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/SnapshotUtilTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/UnknownSnapshotTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/VfsRelativePathTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/vfs/impl/DefaultSnapshotHierarchyTest.groovy
Labels: @execution, from:member

#14911 Add default implementation for UnitOfWork.markExecutionTime()
  subprojects/execution/src/integTest/groovy/org/gradle/internal/execution/IncrementalExecutionIntegrationTest.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/UnitOfWork.java
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/AccessorsClassPath.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/PluginAccessorsClassPath.kt
Labels: @execution, from:member

#14908 Add builds for flame graph generation
  .teamcity/Gradle_Check/configurations/PerformanceTest.kt
  .teamcity/Gradle_Check/configurations/PerformanceTestsPass.kt
  .teamcity/Gradle_Check/configurations/StagePasses.kt
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/Gradle_Check/model/PerformanceTestBucketProvider.kt
  .teamcity/Gradle_Check/model/PerformanceTestCoverage.kt
  .teamcity/Gradle_Check/model/PerformanceTestSpec.kt
  .teamcity/Gradle_Check/projects/PerformanceTestProject.kt
  .teamcity/Gradle_Check/projects/StageProject.kt
  .teamcity/Gradle_Util_Performance/buildTypes/AdHocPerformanceScenario.kt
  .teamcity/common/Os.kt
  .teamcity/common/performance-test-extensions.kt
  .teamcityTest/Gradle_Check_Tests/PerformanceTestBuildTypeTest.kt
  buildSrc/subprojects/jvm/src/main/kotlin/gradlebuild/propagated-env-variables.kt
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/AbstractBuildExperimentRunner.java
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/FileSystemWatchingPerformanceTest.groovy
Labels: @execution, from:member

#14920 Bump wrapper
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: @execution, from:member

#14893 Make `ScopeIdsFixture` compatible with the configuration cache
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/outputorigin/ContinuousIncrementalBuildOutputOriginIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/outputorigin/IncrementalBuildOutputOriginIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/ScopeIdsFixture.groovy
Labels: @configuration-cache, from:member, in:configuration-cache

#14924 Move 'Migrating build logic from Groovy to Kotlin' into user manual
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DocsDistributionIntegrationSpec.groovy
  subprojects/docs/src/docs/userguide/api/kotlin_dsl.adoc
  subprojects/docs/src/docs/userguide/img/intellij-idea-android-studio.png
  subprojects/docs/src/docs/userguide/migration/migrating_from_groovy_to_kotlin_dsl.adoc
  subprojects/docs/src/main/resources/header.html
  subprojects/docs/src/snippets/kotlinDsl/applying-plugins-declarative/groovy/build.gradle
  subprojects/docs/src/snippets/kotlinDsl/applying-plugins-declarative/groovy/settings.gradle
  subprojects/docs/src/snippets/kotlinDsl/applying-plugins-declarative/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/applying-plugins-declarative/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/applying-plugins-imperative/groovy/build.gradle
  subprojects/docs/src/snippets/kotlinDsl/applying-plugins-imperative/groovy/settings.gradle
  subprojects/docs/src/snippets/kotlinDsl/applying-plugins-imperative/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/applying-plugins-imperative/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/configurations-and-dependencies-custom/groovy/build.gradle
  subprojects/docs/src/snippets/kotlinDsl/configurations-and-dependencies-custom/groovy/settings.gradle
  subprojects/docs/src/snippets/kotlinDsl/configurations-and-dependencies-custom/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/configurations-and-dependencies-custom/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/configurations-and-dependencies-declarative/groovy/build.gradle
  subprojects/docs/src/snippets/kotlinDsl/configurations-and-dependencies-declarative/groovy/settings.gradle
  subprojects/docs/src/snippets/kotlinDsl/configurations-and-dependencies-declarative/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/configurations-and-dependencies-declarative/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/configurations-and-dependencies-imperative/groovy/build.gradle
  subprojects/docs/src/snippets/kotlinDsl/configurations-and-dependencies-imperative/groovy/settings.gradle
  subprojects/docs/src/snippets/kotlinDsl/configurations-and-dependencies-imperative/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/configurations-and-dependencies-imperative/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/configuring-plugins-declaratively-applied/groovy/build.gradle
  subprojects/docs/src/snippets/kotlinDsl/configuring-plugins-declaratively-applied/groovy/settings.gradle
  subprojects/docs/src/snippets/kotlinDsl/configuring-plugins-declaratively-applied/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/configuring-plugins-declaratively-applied/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/configuring-plugins-imperatively-applied/groovy/build.gradle
  subprojects/docs/src/snippets/kotlinDsl/configuring-plugins-imperatively-applied/groovy/settings.gradle
  subprojects/docs/src/snippets/kotlinDsl/configuring-plugins-imperatively-applied/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/configuring-plugins-imperatively-applied/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/configuring-tasks-basics/groovy/build.gradle
  subprojects/docs/src/snippets/kotlinDsl/configuring-tasks-basics/groovy/settings.gradle
  subprojects/docs/src/snippets/kotlinDsl/configuring-tasks-basics/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/configuring-tasks-basics/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/configuring-tasks-spring-boot/groovy/build.gradle
  subprojects/docs/src/snippets/kotlinDsl/configuring-tasks-spring-boot/groovy/settings.gradle
  subprojects/docs/src/snippets/kotlinDsl/configuring-tasks-spring-boot/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/configuring-tasks-spring-boot/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/creating-tasks-eager/groovy/build.gradle
  subprojects/docs/src/snippets/kotlinDsl/creating-tasks-eager/groovy/settings.gradle
  subprojects/docs/src/snippets/kotlinDsl/creating-tasks-eager/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/creating-tasks-eager/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/creating-tasks-lazy/groovy/build.gradle
  subprojects/docs/src/snippets/kotlinDsl/creating-tasks-lazy/groovy/settings.gradle
  subprojects/docs/src/snippets/kotlinDsl/creating-tasks-lazy/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/creating-tasks-lazy/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/creating-tasks-project/groovy/build.gradle
  subprojects/docs/src/snippets/kotlinDsl/creating-tasks-project/groovy/settings.gradle
  subprojects/docs/src/snippets/kotlinDsl/creating-tasks-project/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/creating-tasks-project/kotlin/settings.gradle.kts
Labels: @idiomatic, from:member, in:docs, in:kotlin-dsl

#14910 Ensure the javadoc tests actually check the javadoc version
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/JavaExecToolchainIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/javadoc/JavadocToolchainIntegrationTest.groovy
Labels: @jvm, from:member

#14933 Let Kotlin DSL script compilation disable compatibility mode for kotlin new inference engine
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/KotlinCompiler.kt
Labels: from:member, in:kotlin-dsl

#14935 Make `ScopeIdsFixture` compatible with Gradle 4.0+
  subprojects/core/src/crossVersionTest/groovy/org/gradle/internal/scopeids/CrossVersionScopeIdsIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/ScopeIdsFixture.groovy
Labels: @configuration-cache, a:chore, from:member, in:testing

#14942 Remove unneccessary dependency
  subprojects/configuration-cache/build.gradle.kts
Labels: @jvm, from:member

#14947 Update performance test durations and improve `writePerformanceTimes`
  .teamcity/Gradle_Check/model/PerformanceTestBucketProvider.kt
  .teamcity/performance-test-durations.json
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/CompositeResultsStore.java
Labels: @execution, from:member

#14945 Composite builds: internal instantiation cosmetics
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/AbstractCompositeParticipantBuildState.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/CompositeBuildClassPathInitializer.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultBuildableCompositeBuildContext.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultIncludedBuildController.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultIncludedBuildControllers.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultIncludedBuildRegistry.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/IncludedBuildDependencyMetadataBuilder.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/RootOfNestedBuildTree.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/plugins/CompositeBuildPluginResolverContributor.java
Labels: a:chore, from:member, in:composite-builds

#14913 Share root build cache configuration with included builds loaded from the configuration cache
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultIncludedBuild.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultIncludedBuildController.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultIncludedBuildFactory.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultIncludedBuildTaskGraph.java
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheHost.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/build/ConfigurationCacheIncludedBuildState.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/TaskInAnotherBuildCodec.kt
  subprojects/core-api/src/main/java/org/gradle/StartParameter.java
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/outputorigin/IncrementalBuildOutputOriginIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/caching/configuration/internal/BuildCacheCompositeConfigurationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/composite/internal/IncludedBuildController.java
  subprojects/core/src/main/java/org/gradle/composite/internal/IncludedBuildTaskGraph.java
  subprojects/core/src/main/java/org/gradle/execution/plan/TaskInAnotherBuild.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradleLauncher.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradleLauncherFactory.java
  subprojects/core/src/main/java/org/gradle/initialization/RootBuildCacheControllerSettingsProcessor.java
  subprojects/core/src/main/java/org/gradle/initialization/SettingsLocation.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ResolveConfigurationDependenciesBuildOperationIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/WatchedDirectoriesFileSystemWatchingIntegrationTest.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/swiftpm/SwiftPackageManagerDependencyMappingIntegrationTest.groovy
Labels: @configuration-cache, a:feature, from:member, in:composite-builds, in:configuration-cache

#14948 Upgradlew to latest nightly
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore, from:member, in:gradle-build

#14956 Prevent race condition in InMemoryCache during parallel testing
  subprojects/core/src/main/java/org/gradle/testfixtures/internal/InMemoryCacheFactory.java
Labels: a:bug, from:contributor, in:plugin-development, in:test-kit

#14752 Add depency constraints to convention plugins in projects generated by the `init` task
  subprojects/build-init/build.gradle.kts
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/BuildScriptBuilder.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/DependenciesBuilder.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/JvmApplicationProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/JvmProjectInitDescriptor.java
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/groovyapplication/multi/app/App.groovy.template
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/javaapplication/multi/app/App.java.template
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/kotlinapplication/multi/app/App.kt.template
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/library-versions.properties
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/scalaapplication/multi/app/App.scala.template
  subprojects/docs/src/samples/readme-templates/multi-common-body.adoc.template
Labels: @idiomatic, from:member

#14964 Avoid null pointer exception when performance tests failed
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/CrossVersionResultsStore.java
Labels: @dev-productivity, from:member

#14928 Move memory and parallelism settings for performance test projects to gradle.properties
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild.performance-templates.gradle
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild/performance/generator/tasks/AbstractProjectGeneratorTask.groovy
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild/performance/generator/tasks/CppMultiProjectGeneratorTask.groovy
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild/performance/generator/tasks/KtsProjectGeneratorTask.groovy
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild/performance/generator/tasks/NativeProjectWithDepsGeneratorTask.groovy
  subprojects/build-scan-performance/build.gradle.kts
  subprojects/build-scan-performance/src/performanceTest/groovy/org/gradle/performance/BuildScanPluginPerformanceTest.groovy
  subprojects/build-scan-performance/src/templates/root/gradle.properties
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/WithExternalRepository.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/AbstractBuildExperimentRunner.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/AbstractCrossBuildPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/AndroidTestProject.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/CrossVersionPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/IncrementalAndroidTestProject.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/TestProjectLocator.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/TestProjects.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/experiment/buildcache/LocalTaskOutputCacheCrossBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/experiment/java/JavaLibraryPluginPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/experiment/java/ParallelBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/experiment/maven/JavaTestGradleVsMavenPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/FasterIncrementalAndroidBuildsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingJavaPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingNativePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingSwiftPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/DeprecationCreationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ExcludeRuleMergingPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/FileSystemWatchingPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/IdeIntegrationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ParallelDownloadsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/RichConsolePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/TaskCreationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/VerboseTestOutputPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/inception/BuildSrcApiChangePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaABIChangePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaCleanAssemblePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaDependencyReportPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaFirstUsePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIDEModelPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaNonABIChangePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaTasksPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaTestChangePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaUpToDatePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/kotlindsl/GradleKotlinDslBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeBuildDependentsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeCleanBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/RealWorldNativePluginPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftCleanBuildPerformanceTest.groovy
  subprojects/performance/src/templates/archivePerformanceProject/gradle.properties
  subprojects/performance/src/templates/generateLotsOfDeprecationWarnings/gradle.properties
  subprojects/performance/src/templates/gradle-properties/gradle.properties
  subprojects/performance/src/templates/project-with-source/gradle.properties
  subprojects/performance/src/templates/root-project/gradle.properties
Labels: @execution, from:member

#14970 Merge jvmargs from gradle.properties with actual args
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleBuildExperimentRunner.java
Labels: @execution, from:member

#14969 Code gardening
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/ProviderCodecs.kt
  subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java
  subprojects/core/src/main/java/org/gradle/execution/taskgraph/DefaultTaskExecutionGraph.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/tasks/AbstractTaskDependency.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/tasks/CachingTaskDependencyResolveContext.java
Labels: a:chore, from:member

#14979 Drop org.gradle.vfs.debug in favor of org.gradle.vfs.verbose
  subprojects/core/src/main/java/org/gradle/api/internal/StartParameterInternal.java
  subprojects/core/src/main/java/org/gradle/initialization/StartParameterBuildOptions.java
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/LoggingFileSystemWatchingIntegrationTest.groovy
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/action/BuildActionSerializer.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunner.java
Labels: @execution, from:member

#14751 Make sure source or release are set with toolchains
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
  subprojects/language-java/src/test/groovy/org/gradle/api/tasks/compile/JavaCompileTest.groovy
Labels: @jvm, from:member, in:jvm-ecosystem

#14938 Reorganize some things around execution engine
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuter.java
  subprojects/core/src/main/java/org/gradle/internal/execution/DefaultOutputSnapshotter.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/ExecutionGradleServices.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuterTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultDependencyManagementServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java
  subprojects/execution/src/integTest/groovy/org/gradle/internal/execution/IncrementalExecutionIntegrationTest.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/UnitOfWork.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/impl/InputFingerprintUtil.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/BroadcastChangingOutputsStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/BuildCacheStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CaptureStateBeforeExecutionStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CreateOutputsStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/IdentifyStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/RemovePreviousOutputsStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ResolveChangesStep.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/BroadcastChangingOutputsStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/BuildCacheStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CaptureStateBeforeExecutionStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CreateOutputsStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/IdentifyStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/RemovePreviousOutputsStepTest.groovy
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/AccessorsClassPath.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/PluginAccessorsClassPath.kt
Labels: @execution, from:member

#14982 Pass work separately of context
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultDependencyManagementServices.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/Context.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/DeferredExecutionAwareStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/Step.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/impl/DefaultExecutionEngine.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/AssignWorkspaceStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/BroadcastChangingOutputsStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/BuildCacheStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CancelExecutionStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CaptureStateBeforeExecutionStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CreateOutputsStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ExecuteStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/IdentifyStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/IdentityCacheStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/LoadExecutionStateStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/RecordOutputsStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/RemovePreviousOutputsStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ResolveCachingStateStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ResolveChangesStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ResolveInputChangesStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/SkipEmptyWorkStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/SkipUpToDateStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/SnapshotOutputsStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/StoreExecutionStateStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/TimeoutStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ValidateStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/legacy/MarkSnapshottingInputsFinishedStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/legacy/MarkSnapshottingInputsStartedStep.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/AssignWorkspaceStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/BroadcastChangingOutputsStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/BuildCacheStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CancelExecutionStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CaptureStateBeforeExecutionStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CreateOutputsStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/ExecuteStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/IdentifyStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/IdentityCacheStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/RecordOutputsStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/RemovePreviousOutputsStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/ResolveCachingStateStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/ResolveChangesStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/ResolveInputChangesStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/SkipEmptyWorkStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/SkipUpToDateStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/StepSpec.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/StoreExecutionStateStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/TimeoutStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/ValidateStepTest.groovy
Labels: @execution, from:member

#14980 Fail build scan performance test
  subprojects/build-scan-performance/src/testFixtures/groovy/org/gradle/performance/results/BuildScanReportGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/AbstractReportGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/DefaultReportGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/FlakinessReportGenerator.java
Labels: @dev-productivity, from:member

#14963 Run file system watching performance tests with the configuration cache enabled
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/performance-test-durations.json
  .teamcity/performance-tests-ci.json
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/KotlinGradlePluginVersions.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/FasterIncrementalAndroidBuildsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/FileSystemWatchingPerformanceTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
Labels: @execution, from:member

#14987 Fix duplicate test execution
  buildSrc/subprojects/module-identity/src/main/kotlin/gradlebuild/identity/extension/ReleasedVersionsDetails.kt
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/GradleDistributionTool.java
Labels: @dev-productivity, a:bug, from:member

#14918 Avoid executing filters on all candidates
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/DefaultVersionedComponentChooser.java
Labels: @jvm, from:contributor, in:dependency-management

#14981 Mention composite builds in the configuration cache release notes
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/PropertyProblem.kt
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
Labels: @configuration-cache, from:member, in:docs

#14998 Create mergify.yml
  .github/mergify.yml
Labels: @dev-productivity, from:member

#15000 Use normalized build jvm opts in TAPI tests
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r22/ClientShutdownCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r64/DaemonReuseCrossVersionSpec.groovy
  subprojects/tooling-api/src/testFixtures/groovy/org/gradle/integtests/tooling/fixture/ToolingApiSpecification.groovy
Labels: @dev-productivity, from:member

#14988 Do not canonicalize paths for mutation info
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskParametersIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskOutputs.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskExecutionContext.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskStateInternal.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/DefaultTaskExecutionContext.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/ResolveTaskExecutionModeExecuter.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/DefaultTaskProperties.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/GetOutputFilesVisitor.java
  subprojects/core/src/main/java/org/gradle/execution/ProjectExecutionServices.java
  subprojects/core/src/main/java/org/gradle/execution/plan/LocalTaskNode.java
  subprojects/core/src/main/java/org/gradle/execution/plan/LocalTaskNodeExecutor.java
  subprojects/core/src/main/java/org/gradle/execution/plan/TaskNodeFactory.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ResolveTaskExecutionModeExecuterTest.groovy
  subprojects/core/src/test/groovy/org/gradle/execution/plan/DefaultExecutionPlanParallelTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/test/fixtures/AbstractProjectBuilderSpec.groovy
Labels: @execution, a:performance-issue, from:member

#14995 Release GE plugin 3.5
  buildSrc/subprojects/build-platform/build.gradle.kts
  settings.gradle.kts
  subprojects/core/src/main/java/org/gradle/plugin/management/internal/autoapply/AutoAppliedGradleEnterprisePlugin.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/BuildScanPluginSmokeTest.groovy
Labels: from:member

#15011 Allow included/nested builds to include the root build
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildIncludeCycleIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/internal/composite/ChildBuildRegisteringSettingsLoader.java
Labels: @idiomatic, a:bug, from:member, in:composite-builds

#15012 Remove conflict check for 'included build name' vs 'root build root project name'
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildNestingIntegrationTest.groovy
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/IncludedBuildValidationIntegrationTest.groovy
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultIncludedBuildRegistry.java
Labels: @idiomatic, from:member, in:composite-builds

#14999 Remove some redundant code
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/PerformanceTestResult.java
Labels: @dev-productivity, from:member

#14994 Extract inception smoke tests to their own task and ci job
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  subprojects/smoke-test/build.gradle.kts
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuild.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildConfigurationCacheSmokeTest.groovy
Labels: @configuration-cache, a:chore, from:member, in:gradle-build

#10879 Move Software Model Check task to base plugin
  subprojects/platform-base/src/integTest/groovy/org/gradle/language/base/ComponentBinariesIntegrationTest.groovy
  subprojects/platform-base/src/integTest/groovy/org/gradle/language/base/ComponentModelReportIntegrationTest.groovy
  subprojects/platform-base/src/main/java/org/gradle/language/base/plugins/ComponentModelBasePlugin.java
  subprojects/testing-base/src/main/java/org/gradle/testing/base/plugins/TestingModelBasePlugin.java
Labels: @core, from:contributor

#15015 Deprecate and hide software model related help tasks
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/reporting/dependents/DependentComponentsReportIntegrationTest.groovy
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/reporting/model/ModelReportTaskIntegrationTest.groovy
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/TaskReportTaskIntegrationTest.groovy
  subprojects/diagnostics/src/main/java/org/gradle/api/plugins/HelpTasksPlugin.java
  subprojects/diagnostics/src/main/java/org/gradle/api/reporting/components/ComponentReport.java
  subprojects/diagnostics/src/main/java/org/gradle/api/reporting/dependents/DependentComponentsReport.java
  subprojects/diagnostics/src/main/java/org/gradle/api/reporting/model/ModelReport.java
  subprojects/diagnostics/src/main/java/org/gradle/api/reporting/model/internal/ModelNodeRenderer.java
  subprojects/diagnostics/src/test/groovy/org/gradle/api/plugins/HelpTasksPluginSpec.groovy
  subprojects/tooling-api/src/testFixtures/groovy/org/gradle/integtests/tooling/fixture/ToolingApiSpecification.groovy
Labels: from:member, in:core

#15014 Shorten the path for the flame graph directory
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/JfrDifferentialFlameGraphGenerator.groovy
Labels: @execution, from:member

#14940 Skip signed jars when instrumenting build logic
  subprojects/core/src/integTest/groovy/org/gradle/internal/classpath/BuildScriptClasspathIntegrationSpec.groovy
  subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingClasspathFileTransformer.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingTransformer.java
  subprojects/core/src/test/groovy/org/gradle/internal/classpath/DefaultCachedClasspathTransformerTest.groovy
Labels: @configuration-cache, from:member, in:core

#15013 Update tested AGP versions
  gradle/dependency-management/agp-versions.properties
Labels: a:chore, from:member

#15026 Let configuration cache handle composite builds with cycles
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildIncludeCycleIntegrationTest.groovy
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildPluginDevelopmentIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheBuild.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheHost.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheIO.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/PluginVariantResolveIntegrationTest.groovy
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/tasks/GenerateMavenPom.java
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/plugins/JavaGradlePluginPluginPublishingIntegrationTest.groovy
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/plugins/MavenPluginPublishPlugin.java
  subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/use/AlreadyOnClasspathPluginUseIntegrationTest.groovy
Labels: @configuration-cache, a:feature, from:member, in:configuration-cache

#14950 Allow cycles between included builds and fail only on cycles between tasks
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildArtifactTransformIntegrationTest.groovy
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildDependencyCycleIntegrationTest.groovy
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildPluginDevelopmentIntegrationTest.groovy
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildRootProjectIntegrationTest.groovy
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildTaskLifecycleIntegrationTest.groovy
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultIncludedBuildTaskGraph.java
  subprojects/core/src/integTest/groovy/org/gradle/initialization/CalculateTaskGraphBuildOperationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java
  subprojects/core/src/main/java/org/gradle/execution/plan/TaskInAnotherBuild.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/DefaultConfigurationResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/DefaultResolvedArtifactsBuilder.java
  subprojects/language-java/src/main/java/org/gradle/language/java/plugins/JavaLanguagePlugin.java
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/AbstractConsoleBuildPhaseFunctionalTest.groovy
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/internal/DependencyResolvingClasspath.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/internal/resolve/SourceSetDependencyResolvingClasspath.java
  subprojects/testing-jvm/src/main/java/org/gradle/jvm/plugins/JvmTestSuiteBasePlugin.java
Labels: @idiomatic, from:member, in:composite-builds

#14985 Not fail the build if cleanup step finds leftover test files
  buildSrc/subprojects/buildquality/src/main/kotlin/gradlebuild.ci-reporting.gradle.kts
Labels: @dev-productivity, from:member

#15036 Add missing default branch
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/generator/FileContentGenerator.groovy
Labels: @dev-productivity, from:member

#15034 Replace Guava Supplier with Java 8 Supplier
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/ResultsStoreHelper.java
Labels: @dev-productivity, from:member

#15025 Let classpath transformer use a bounded thread executor
  subprojects/core/src/main/java/org/gradle/internal/classpath/DefaultCachedClasspathTransformer.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GradleUserHomeScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/internal/classpath/DefaultCachedClasspathTransformerTest.groovy
Labels: @configuration-cache, from:member, in:core

#14971 Expose the ProviderFactory in settings.gradle.
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOptionsIntegrationTest.groovy
  subprojects/core-api/src/main/java/org/gradle/api/initialization/Settings.java
  subprojects/core-api/src/main/java/org/gradle/api/provider/ProviderFactory.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultSettings.java
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/delegates/SettingsDelegate.kt
Labels: @configuration-cache, a:feature, from:contributor, in:core

#15024 Register root build as included build so that it can be addressed
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildIncludeCycleIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/core/src/main/java/org/gradle/internal/composite/ChildBuildRegisteringSettingsLoader.java
  subprojects/core/src/main/java/org/gradle/internal/composite/IncludedRootBuild.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/GradleBuildBuilder.java
  subprojects/tooling-api-builders/src/main/java/org/gradle/tooling/internal/provider/runner/AbstractClientProvidedBuildActionRunner.java
Labels: @idiomatic, a:bug, from:member, in:composite-builds

#15040 Rename some file system nodes that were called snapshots before
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/AbstractIncompleteFileSystemNode.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/CompleteDirectorySnapshot.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/MetadataSnapshot.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/PartialDirectoryNode.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/UnknownFileSystemNode.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultSnapshotHierarchy.java
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/AbstractIncompleteFileSystemNodeTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/CompleteDirectorySnapshotTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/PartialDirectoryNodeTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/UnknownFileSystemNodeTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/vfs/impl/DefaultSnapshotHierarchyTest.groovy
Labels: @execution, from:member

#15030 Make the dependencies model builder more convenient
  subprojects/core-api/src/main/java/org/gradle/api/initialization/dsl/DependenciesModelBuilder.java
  subprojects/core/src/main/java/org/gradle/api/internal/std/TomlDependenciesFileParser.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/central/DependenciesExtensionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/central/KotlinDslDependenciesExtensionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/central/TomlDependenciesExtensionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/std/DefaultDependenciesModelBuilder.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/std/DefaultDependenciesAccessorsTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/std/DefaultDependenciesModelBuilderTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/std/DependenciesSourceGeneratorTest.groovy
Labels: @jvm, from:member, in:dependency-management

#15039 Support cyclic build includes in IDE import
  subprojects/ide/src/crossVersionTest/groovy/org/gradle/plugins/ide/tooling/r31/IdeaProjectUtil.java
  subprojects/ide/src/crossVersionTest/groovy/org/gradle/plugins/ide/tooling/r33/FetchEclipseProjects.java
  subprojects/ide/src/crossVersionTest/groovy/org/gradle/plugins/ide/tooling/r68/CompositeBuildModuleCycleCrossVersionSpec.groovy
  subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/EclipseModelBuilder.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/GradleBuildBuilder.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/IdeaModelBuilder.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/model/DefaultGradleBuild.java
  subprojects/tooling-api-builders/src/main/java/org/gradle/tooling/internal/provider/runner/AbstractClientProvidedBuildActionRunner.java
Labels: @idiomatic, a:bug, from:member, in:composite-builds, in:eclipse-plugin, in:idea-plugin

#14976 Simplify Git instructions for signing patch sets
  CONTRIBUTING.md
Labels: from:contributor

#14975 Better explain naming of .gradle files #14949
  subprojects/distributions-full/src/toplevel/init.d/readme.txt
Labels: from:contributor

#14869 Moved the antlr convention to the conventions section
  subprojects/docs/src/docs/userguide/core-plugins/antlr_plugin.adoc
Labels: from:contributor
