Repository gradle/gradle, pull requests merged in 2020-07, with the labels that each got.

#13572 Shorten path on windows
  subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/file/AbstractTestDirectoryProvider.java
Labels: @dev-productivity, a:chore, from:member

#13597 Apply Gradle Enterprise Conventions plugin
  .teamcity/Gradle_Check/projects/RootProject.kt
  .teamcity/common/BuildCache.kt
  .teamcityTest/Gradle_Check_Tests/PerformanceTestBuildTypeTest.kt
  buildSrc/subprojects/profiling/src/main/kotlin/org/gradle/gradlebuild/profiling/buildscan/BuildScanPlugin.kt
  gradle/build-cache-configuration.settings.gradle.kts
  gradle/init-scripts/build-scan.init.gradle.kts
  gradle/init-scripts/public-build-scan.init.gradle.kts
  gradle/verification-metadata.xml
  settings.gradle.kts
Labels: @dev-productivity, a:chore, from:member

#13633 Replace black/white list terms with more descriptive language
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/ResolutionStrategy.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/DependencySubstitutionRulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/DependencyUnresolvedModuleIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/DependencyResolveRulesIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementBuildScopeServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/ConnectionFailureRepositoryDisabler.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/ErrorHandlingModuleComponentRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/RepositoryDisabler.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/ResolveIvyFactory.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/ConnectionFailureRepositoryDisablerTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/ErrorHandlingModuleComponentRepositoryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/ResolveIvyFactoryTest.groovy
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/dependency_resolution.adoc
  subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/resolution_rules.adoc
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-resolutionStrategy/groovy/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-resolutionStrategy/kotlin/build.gradle.kts
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/SystemPropertyAccessListener.kt
  subprojects/model-core/src/test/groovy/org/gradle/internal/isolated/IsolationSchemeTest.groovy
Labels: a:bug, from:member, in:core, in:dependency-management

#13645 Revert version upgrades
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/library-versions.properties
Labels: @jvm, from:member

#13646 Fix @ToBeFixedForInstantExecution skip condition
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/ToBeFixedForInstantExecutionExtension.groovy
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/AbstractConsoleBuildPhaseFunctionalTest.groovy
Labels: @configuration-cache, from:member

#13638 Consider `BiProvider` as changing if either `left` or `right` is
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionBuildOptionsIntegrationTest.groovy
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/BiProvider.java
Labels: @configuration-cache, from:member, in:configuration-cache

#13641 Reduce window size for stale issues
  .github/stale.yml
Labels: @jvm, from:member

#13621 Add release note and documentation about credentials providers
  buildSrc/subprojects/docs/src/main/groovy/org/gradle/gradlebuild/docs/GradleUserManualPlugin.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/authoring-builds/authoring_maintainable_build_scripts.adoc
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/declaring_repositories.adoc
  subprojects/docs/src/samples/credentials-handling/publishing-credentials/groovy/build.gradle
  subprojects/docs/src/samples/credentials-handling/publishing-credentials/kotlin/build.gradle.kts
Labels: @core, from:member, in:core

#13635 Tighten file permissions in the configuration cache
  subprojects/instant-execution/instant-execution.gradle.kts
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/InstantExecutionCache.kt
Labels: @configuration-cache, from:member, in:configuration-cache

#13644 Enable build cache by default
  .teamcity/Gradle_Check/configurations/BaseGradleBuildType.kt
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/common/BuildCache.kt
  .teamcityTest/Gradle_Check_Tests/CIConfigIntegrationTests.kt
  .teamcityTest/Gradle_Check_Tests/PerformanceTestBuildTypeTest.kt
  gradle.properties
Labels: @dev-productivity, a:chore, from:member

#13668 Document the release flag support
  subprojects/docs/src/docs/dsl/org.gradle.api.tasks.compile.CompileOptions.xml
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/dep-man/04-modeling-features/cross_project_publications.adoc
  subprojects/docs/src/docs/userguide/jvm/building_java_projects.adoc
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/CompileOptions.java
Labels: @jvm, in:jvm-ecosystem

#13664 Add configuration cache to the release notes
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
Labels: @configuration-cache, from:member

#13649 Upgrade scala library
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/library-versions.properties
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/scalalibrary/LibrarySuite.scala.template
Labels: @jvm, from:member

#13675 Fix TestNG support for the configuration cache
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/JavaApplicationInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/JavaLibraryInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/MavenConversionIntegrationTest.groovy
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/jvm/AbstractConsoleJvmTestWorkerFunctionalTest.groovy
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/jvm/ConsoleTestNGUnsupportedTestWorkerFunctionalTest.groovy
  subprojects/platform-play/src/main/java/org/gradle/play/plugins/PlayTestPlugin.java
  subprojects/platform-play/src/test/groovy/org/gradle/play/plugins/PlayTestPluginTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/JavaPluginTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/tasks/testing/TestTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/java/SamplesJavaTestingIntegrationTest.groovy
  subprojects/testing-base/src/integTest/groovy/org/gradle/testing/TestExecutionBuildOperationsIntegrationTest.groovy
  subprojects/testing-base/src/testFixtures/groovy/org/gradle/testing/AbstractTestFrameworkIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/IncrementalTestIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestOutputListenerIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestingIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/fixture/AbstractJvmFailFastIntegrationSpec.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/fixture/AbstractTestFilteringIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/SampleTestNGIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGClassIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGConsoleLoggingIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGFailFastIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGFailurePolicyIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGFilteringIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGGroupByInstancesIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGGroupByInstancesNotSupportedIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGJdkNavigationIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGLoggingOutputCaptureIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGParallelSuiteIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGPreserveOrderIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGPreserveOrderNotSupportedIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGProducesOldReportsIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGStaticLoggingIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGSuiteInitialisationIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGSuiteIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGTestFrameworkIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGUpToDateCheckIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGXmlResultAndHtmlReportIntegrationTest.groovy
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/TestClassLoaderFactory.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGTestFramework.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/testng/TestNGOptions.java
  subprojects/testing-jvm/src/test/groovy/org/gradle/api/internal/tasks/testing/testng/TestNGTestFrameworkTest.groovy
Labels: @configuration-cache, from:member, in:testing

#13671 Fix UpdateReleasedVersions
  buildSrc/subprojects/build-update-utils/src/main/kotlin/gradlebuild/buildutils/tasks/UpdateReleasedVersions.kt
  buildSrc/subprojects/build-update-utils/src/test/groovy/gradlebuild/buildutils/tasks/UpdateReleasedVersionsIntegrationTest.groovy
  buildSrc/subprojects/build-update-utils/src/test/groovy/gradlebuild/buildutils/tasks/UpdateReleasedVersionsTest.groovy
Labels: @dev-productivity, a:bug, from:member

#13689 Move init script logic into build
  .teamcity/common/extensions.kt
  .travis.yml
  buildSrc/subprojects/profiling/src/main/kotlin/gradlebuild/buildscan.gradle.kts
  gradle/init-scripts/build-scan.init.gradle.kts
Labels: @dev-productivity, a:chore, from:member

#13610 Improve java serialization behaviour
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionProblemReportingIntegrationTest.groovy
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/InstantExecutionReport.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/InstantExecutionState.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/SystemPropertyAccessListener.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/initialization/InstantExecutionProblemsListener.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/problems/ProblemsSummary.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/problems/PropertyProblem.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/Combinators.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/Logging.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/Codecs.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/SerializableWriteObjectCodec.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/TaskReferenceCodec.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/jos/MethodCache.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/jos/ObjectInputStreamAdapter.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/jos/RecordingObjectOutputStream.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/jos/SerializableWriteObjectCodec.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/jos/SerializableWriteReplaceCodec.kt
  subprojects/instant-execution/src/test/kotlin/org/gradle/instantexecution/serialization/codecs/AbstractFunctionalTypeTest.kt
  subprojects/instant-execution/src/test/kotlin/org/gradle/instantexecution/serialization/codecs/AbstractUserTypeCodecTest.kt
  subprojects/instant-execution/src/test/kotlin/org/gradle/instantexecution/serialization/codecs/SerializableBeanCodecTest.kt
  subprojects/instant-execution/src/test/kotlin/org/gradle/instantexecution/serialization/codecs/UserTypesCodecTest.kt
Labels: @configuration-cache, a:feature, from:member, in:configuration-cache

#13683 Enable Kotlin DSL tests with file system watching
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginGradlePluginCrossVersionSmokeTest.kt
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginTest.kt
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/precompiled/AbstractPrecompiledScriptPluginTest.kt
Labels: @execution, from:member

#13361 Log number of watched directory hierarchies
  subprojects/core/src/integTest/groovy/org/gradle/internal/operations/logging/LoggingBuildOperationProgressIntegTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdater.java
Labels: @execution, from:member

#13648 Exclude all milestone version prefixes for kotlin
  subprojects/build-init/build-init.gradle.kts
Labels: @jvm

#13696 Small build logic simplification
  buildSrc/subprojects/jvm/src/main/kotlin/gradlebuild/unittest-and-compile.gradle.kts
  buildSrc/subprojects/lifecycle/src/main/kotlin/gradlebuild/lifecycle.gradle.kts
  gradle/remove-teamcity-temp-property.gradle
Labels: @dev-productivity, in:gradle-build

#13695 Introduce single `JavaObjectSerializationCodec`
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/beans/BeanPropertyReader.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/beans/BeanStateReader.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/Codecs.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/jos/JavaObjectSerializationCodec.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/jos/MethodCache.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/jos/ObjectInputStreamAdapter.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/jos/SerializableWriteObjectCodec.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/jos/SerializableWriteReplaceCodec.kt
  subprojects/instant-execution/src/test/kotlin/org/gradle/instantexecution/serialization/codecs/JavaObjectSerializationCodecTest.kt
Labels: @configuration-cache, a:chore, from:member, in:configuration-cache

#13647 Add CI pipelines for running tests against JDK15 and JDK16
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/common/JvmCategory.kt
  .teamcity/common/JvmVersion.kt
Labels: @core, from:member, in:core

#13714 Add Gradle user home directory to the configuration cache fingerprint
  subprojects/core/src/integTest/groovy/org/gradle/internal/scopeids/ScopeIdsIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/CacheResolveIntegrationTest.groovy
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/fingerprint/InstantExecutionCacheFingerprint.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/fingerprint/InstantExecutionCacheFingerprintChecker.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/fingerprint/InstantExecutionCacheFingerprintController.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/fingerprint/InstantExecutionCacheFingerprintWriter.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/initialization/InstantExecutionStartParameter.kt
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractSourceIncrementalCompilationIntegrationTest.groovy
Labels: @configuration-cache, a:feature, from:member, in:configuration-cache

#13721 Restore FileOperations API
  subprojects/core/src/main/java/org/gradle/api/internal/file/FileOperations.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProject.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/FileTreeCodec.kt
Labels: from:member

#13715 Add JVM name, vendor and version to the configuration cache fingerprint
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/JavaExecJavaVersionIntegrationSpec.groovy
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/fingerprint/InstantExecutionCacheFingerprint.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/fingerprint/InstantExecutionCacheFingerprintChecker.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/fingerprint/InstantExecutionCacheFingerprintWriter.kt
Labels: @configuration-cache, a:feature, from:member, in:configuration-cache

#13725 Add `StartParameter.projectDir` to the configuration cache fingerprint
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/InstantExecutionCacheKey.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/initialization/InstantExecutionStartParameter.kt
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/ProjectLoadingIntegrationTest.java
Labels: @configuration-cache, a:bug, from:member, in:configuration-cache

#13726 Remove `@ToBeFixedForInstantExecution` from a bunch of tests
  subprojects/core/src/integTest/groovy/org/gradle/api/FinalizerTaskIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskExecutionIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskUpToDateIntegrationTest.groovy
Labels: @configuration-cache, a:feature, from:member, in:configuration-cache

#13727 Explain `@ToBeFixedForInstantExecution` in `SyncTaskIntegrationTest`
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/FileCollectionCodec.kt
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/ProjectLoadingIntegrationTest.java
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/OrElseFixedValueProvider.java
Labels: @configuration-cache, a:feature, from:member, in:configuration-cache

#13729 Make `NestedInputIntegrationTest` compatible with the configuration cache
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/NestedInputIntegrationTest.groovy
Labels: @configuration-cache, a:feature, from:member, in:configuration-cache

#13728 Upgrade to native platform 0.22-milestone-4
  gradle/dependencies.gradle
  gradle/verification-metadata.xml
Labels: @execution, from:member

#13710 De-incubate new version of 'dependencies.constraints { }' (Kotlin DSL)
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/DependencyHandlerScope.kt
Labels: from:member

#13737 Favour `getOrElse('default')` over `orNull ?: 'default'`
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/NestedInputIntegrationTest.groovy
Labels: @configuration-cache, a:chore, from:member, in:configuration-cache

#13711 Enforce EdgeState invariant
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/platforms/JavaPlatformResolveIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/EdgeState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ModuleResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/NodeState.java
Labels: @jvm, from:member, in:dependency-management

#13739 Configuration cache documentation refinements
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
  subprojects/docs/src/snippets/configurationCache/problemsFixed/groovy/build.gradle
  subprojects/docs/src/snippets/configurationCache/problemsFixed/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/configurationCache/problemsFixedReuse/groovy/build.gradle
  subprojects/docs/src/snippets/configurationCache/problemsFixedReuse/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/configurationCache/problemsGroovy/tests/load.out
  subprojects/docs/src/snippets/configurationCache/problemsGroovy/tests/store.out
  subprojects/docs/src/snippets/configurationCache/problemsKotlin/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/configurationCache/problemsKotlin/tests/load.out
  subprojects/docs/src/snippets/configurationCache/problemsKotlin/tests/store.out
  subprojects/docs/src/snippets/configurationCache/projectAtExecutionFixed/groovy/build.gradle
  subprojects/docs/src/snippets/configurationCache/projectAtExecutionFixed/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/valueProviders/envVarsDont/groovy/build.gradle
  subprojects/docs/src/snippets/valueProviders/envVarsDont/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/valueProviders/gradlePropsDont/groovy/build.gradle
  subprojects/docs/src/snippets/valueProviders/gradlePropsDont/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/valueProviders/sysPropsDont/groovy/build.gradle
  subprojects/docs/src/snippets/valueProviders/sysPropsDont/kotlin/build.gradle.kts
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/InstantExecutionException.kt
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/instantexecution/InstantExecutionProblemsFixture.groovy
Labels: @configuration-cache, from:member, in:docs

#13607 Introduce `ProviderFactory#zip`
  subprojects/core-api/src/main/java/org/gradle/api/provider/Provider.java
  subprojects/core-api/src/main/java/org/gradle/api/provider/ProviderFactory.java
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionBuildOptionsIntegrationTest.groovy
  subprojects/model-core/src/integTest/groovy/org/gradle/api/provider/ProviderIntegrationTest.groovy
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/BiProvider.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/DefaultProviderFactory.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/ProviderInternal.java
  subprojects/model-core/src/test/groovy/org/gradle/api/internal/provider/DefaultProviderFactoryTest.groovy
  subprojects/model-core/src/testFixtures/groovy/org/gradle/api/internal/provider/ProviderAssertions.groovy
  subprojects/model-core/src/testFixtures/groovy/org/gradle/api/internal/provider/ProviderSpec.groovy
Labels: a:feature, from:member, in:core

#13743 Emit build operation progress events for configuration cache and file system watching build option values
  subprojects/base-services/src/main/java/org/gradle/internal/operations/BuildOperationProgressEventEmitter.java
  subprojects/build-option/src/main/java/org/gradle/internal/buildoption/BuildOption.java
  subprojects/core/src/integTest/groovy/org/gradle/internal/configurationcache/options/ConfigurationCacheSettingsFinalizedBuildOperationIntegTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/internal/operations/logging/LoggingBuildOperationProgressIntegTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/GradleInternal.java
  subprojects/core/src/main/java/org/gradle/api/internal/StartParameterInternal.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProject.java
  subprojects/core/src/main/java/org/gradle/caching/internal/BuildCacheServices.java
  subprojects/core/src/main/java/org/gradle/configuration/BuildOperatingFiringProjectsPreparer.java
  subprojects/core/src/main/java/org/gradle/configuration/DefaultProjectsPreparer.java
  subprojects/core/src/main/java/org/gradle/execution/BuildOperationFiringBuildWorkerExecutor.java
  subprojects/core/src/main/java/org/gradle/initialization/BuildOptionBuildOperationProgressEventsEmitter.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradleLauncher.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradleLauncherFactory.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultSettingsPreparer.java
  subprojects/core/src/main/java/org/gradle/initialization/RootBuildCacheControllerSettingsProcessor.java
  subprojects/core/src/main/java/org/gradle/internal/configurationcache/options/ConfigurationCacheSettingsFinalizedProgressDetails.java
  subprojects/core/src/main/java/org/gradle/internal/enterprise/core/GradleEnterprisePluginManager.java
  subprojects/core/src/main/java/org/gradle/internal/operations/logging/LoggingBuildOperationProgressBroadcaster.java
  subprojects/core/src/main/java/org/gradle/internal/operations/trace/BuildOperationRecord.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/BuildScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/BuildSessionScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/CrossBuildSessionScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GlobalScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GradleScopeServices.java
  subprojects/core/src/main/java/org/gradle/invocation/DefaultGradle.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/DefaultProjectSpec.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/DefaultProjectTest.groovy
  subprojects/core/src/test/groovy/org/gradle/configuration/DefaultProjectsPreparerTest.groovy
  subprojects/core/src/test/groovy/org/gradle/execution/DefaultTasksBuildExecutionActionTest.groovy
  subprojects/core/src/test/groovy/org/gradle/execution/DryRunBuildExecutionActionTest.groovy
  subprojects/core/src/test/groovy/org/gradle/execution/ExcludedTaskFilteringBuildConfigurationActionTest.groovy
  subprojects/core/src/test/groovy/org/gradle/execution/SelectedTaskExecutionActionTest.groovy
  subprojects/core/src/test/groovy/org/gradle/execution/TaskNameResolvingBuildConfigurationActionSpec.groovy
  subprojects/core/src/test/groovy/org/gradle/initialization/DefaultGradleLauncherSpec.groovy
  subprojects/core/src/test/groovy/org/gradle/initialization/InitScriptHandlerTest.groovy
  subprojects/core/src/test/groovy/org/gradle/initialization/buildsrc/BuildSrcBuildListenerFactoryTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/operations/logging/LoggingBuildOperationProgressBroadcasterTest.groovy
  subprojects/core/src/test/groovy/org/gradle/invocation/DefaultGradleSpec.groovy
  subprojects/core/src/test/groovy/org/gradle/testfixtures/ProjectBuilderTest.groovy
  subprojects/enterprise/src/test/groovy/org/gradle/internal/scan/config/LegacyGradleEnterprisePluginCheckInServiceTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/options/FileSystemWatchingSettingsFinalizedBuildOperationIntegTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/options/FileSystemWatchingSettingsFinalizedProgressDetails.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/BuildOperationNotificationsFixture.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/BuildOperationTreeFixture.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/BuildOperationTreeQueries.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/BuildOperationsFixture.groovy
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunner.java
  subprojects/logging/src/main/java/org/gradle/internal/deprecation/DeprecationLogger.java
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/DefaultDeprecatedUsageProgressDetails.java
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/DeprecatedUsageBuildOperationProgressBroadcaster.java
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/LoggingDeprecatedFeatureHandler.java
  subprojects/logging/src/test/groovy/org/gradle/internal/deprecation/DeprecationLoggerTest.groovy
  subprojects/logging/src/test/groovy/org/gradle/internal/deprecation/DeprecationMessagesTest.groovy
  subprojects/logging/src/test/groovy/org/gradle/internal/deprecation/LoggingDeprecatedFeatureHandlerTest.groovy
  subprojects/model-core/src/test/groovy/org/gradle/api/internal/provider/TransformBackedProviderTest.groovy
Labels: from:member

#13747 Use isolated gradle user home for DistributionIntegrationSpec
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DistributionIntegrationSpec.groovy
Labels: @dev-productivity

#13694 Support default excludes with file system watching
  subprojects/core-api/src/main/java/org/gradle/api/tasks/util/internal/PatternSpecFactory.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java
  subprojects/docs/src/docs/userguide/authoring-builds/working_with_files.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
  subprojects/docs/src/docs/userguide/running-builds/gradle_daemon.adoc
  subprojects/docs/src/snippets/files/copy/groovy/build.gradle
  subprojects/docs/src/snippets/files/copy/groovy/settings.gradle
  subprojects/docs/src/snippets/files/copy/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/files/copy/kotlin/settings.gradle.kts
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdaterTest.groovy
  subprojects/snapshots/src/integTest/groovy/org/gradle/internal/vfs/DefaultExcludesIntegrationTest.groovy
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/impl/DirectorySnapshotter.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultVirtualFileSystem.java
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterAsDirectoryWalkerTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/vfs/impl/DefaultSnapshotHierarchyTest.groovy
Labels: @execution, from:member

#13752 Add more supported Linux variants to file system watching documentation
  subprojects/docs/src/docs/userguide/running-builds/gradle_daemon.adoc
Labels: @execution, from:member

#13749 Let configuration cache decode `HashSet` as `LinkedHashSet`
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/Codecs.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/CollectionCodecs.kt
Labels: @configuration-cache, a:feature, from:member, in:configuration-cache

#13746 Improve fixtures around platform dependencies
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/platforms/JavaPlatformResolveIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/gradle/DependencySpec.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/gradle/VariantMetadataSpec.groovy
Labels: @jvm, in:dependency-management

#13761 Ignore jacoco plugin tests under JDK15
  subprojects/docs/docs.gradle
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractProjectRelocationIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractTaskRelocationIntegrationTest.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoCachingIntegrationTest.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoPluginIntegrationTest.groovy
  subprojects/jacoco/src/testFixtures/groovy/org/gradle/testing/jacoco/plugins/fixtures/JacocoCoverage.groovy
  subprojects/reporting/src/integTest/groovy/org/gradle/api/reporting/plugins/BuildDashboardPluginIntegrationTest.groovy
Labels: @core, from:member, in:core

#13765 Remove Groovy switch bug workaround
  subprojects/dependency-management/src/testFixtures/groovy/org/gradle/integtests/fixtures/publish/ModuleVersionSpec.groovy
Labels: @core, a:chore, from:member, in:core

#13548 Stabilize Shutdown API tests and improve implementation
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r65/ToolingApiShutdownCrossVersionSpec.groovy
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/connection/LazyConsumerActionExecutor.java
Labels: @core, from:member

#13750 Reduce stale window
  .github/stale.yml
Labels: @jvm

#13755 Stop watching on macOs when a watched directory is symlinked
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/FileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/WatchingNotSupportedException.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DarwinFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WindowsFileWatcherRegistryFactory.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdaterTest.groovy
Labels: @execution, from:member

#13773 Ignore Kotlin integration test with Jacoco on JDK>15
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/JacocoIntegrationTest.kt
Labels: @core, from:member, in:core

#13764 Avoid storing metadata rules in the in-memory cache
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ivy/IvyJvmLibraryArtifactResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/modulecache/AbstractModuleMetadataCache.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/modulecache/DefaultCachedMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/modulecache/InMemoryModuleMetadataCache.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/modulecache/ModuleMetadataCache.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/modulecache/PersistentModuleMetadataCache.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/modulecache/ReadOnlyModuleMetadataCache.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/modulecache/TwoStageModuleMetadataCache.java
Labels: from:member, in:dependency-management

#13734 Set up test distribution for QuickFeedbackLinux
  .teamcity/Gradle_Check/configurations/FunctionalTest.kt
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/Gradle_Check/projects/StageProject.kt
  .teamcityTest/Gradle_Check_Tests/CIConfigIntegrationTests.kt
  buildSrc/build.gradle.kts
  buildSrc/subprojects/jvm/jvm.gradle.kts
  buildSrc/subprojects/jvm/src/main/kotlin/gradlebuild/unittest-and-compile.gradle.kts
  gradle/verification-metadata.xml
  subprojects/docs/docs.gradle
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AvailableJavaHomes.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/ScriptExecuter.groovy
  subprojects/platform-play/src/testFixtures/groovy/org/gradle/play/integtest/fixtures/DistributionTestExecHandleBuilder.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/ApplicationPluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecDebugIntegrationTest.groovy
Labels: @dev-productivity, a:chore, from:member

#13782 Introduce a component selection descriptor factory
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultDependencyManagementServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementBuildScopeServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/DefaultConfigurationResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/dependencysubstitution/DefaultDependencySubstitution.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/dependencysubstitution/DefaultDependencySubstitutionApplicator.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/DefaultArtifactDependencyResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/CachingComponentSelectionDescriptorFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ComponentResultSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ComponentSelectionDescriptorFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ComponentSelectionReasonSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/DefaultResolutionResultBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/DependencyResultSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/StreamingResolutionResultBuilder.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/dependencysubstitution/DefaultDependencyResolveDetailsSpec.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/dependencysubstitution/DefaultDependencySubstitutionSpec.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/DependencyGraphBuilderTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ComponentResultSerializerTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ComponentSelectionReasonSerializerTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/DependencyResultSerializerTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/StreamingResolutionResultBuilderTest.groovy
  subprojects/dependency-management/src/testFixtures/groovy/org/gradle/api/internal/artifacts/DependencyManagementTestUtil.groovy
  subprojects/dependency-management/src/testFixtures/groovy/org/gradle/api/internal/artifacts/TestComponentDescriptorFactory.groovy
Labels: @jvm, from:member

#13801 Ensure configuration cache fingerprint resources are always disposed of
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/DefaultInstantExecution.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/fingerprint/InstantExecutionCacheFingerprintController.kt
Labels: @configuration-cache, a:bug, from:member, in:configuration-cache

#13802 Remove `@Ignore` from fixed transform action test
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionDependencyResolutionIntegrationTest.groovy
Labels: @configuration-cache, a:chore, from:member, in:configuration-cache

#13806 Ensure configuration cache fingerprint resources are always disposed of
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/DefaultInstantExecution.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/fingerprint/InstantExecutionCacheFingerprintController.kt
Labels: @configuration-cache, a:chore, from:member, in:configuration-cache

#13790 Update test to work with configuration cache with JDK9+
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationSignatureCheckIntegTest.groovy
Labels: @core, a:chore, from:member

#13789 Do not reference project during task execution in a test
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/execution/JavaModuleExecutionIntegrationTest.groovy
Labels: @core, a:chore, from:member

#13775 Add javadoc comments to classes in samples with javadocs
  subprojects/docs/src/snippets/signing/maven-publish/groovy/src/main/java/Sample.java
  subprojects/docs/src/snippets/signing/maven-publish/kotlin/src/main/java/Sample.java
Labels: @core, from:member, in:core

#13805 Bump native-platform: use new macOS watcher, take 2
  subprojects/distributions-dependencies/distributions-dependencies.gradle.kts
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/FileSystemWatchingHelper.java
  subprojects/language-scala/src/integTest/groovy/org/gradle/language/scala/CachedPlatformScalaCompileIntegrationTest.groovy
Labels: @execution, from:member

#13796 Ensure isolated daemons are stopped for plugin builds in testkit tests
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/GradleRunnerPluginClasspathInjectionIntegrationTest.groovy
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/fixtures/PluginUnderTest.groovy
Labels: @execution, from:member

#13798 Add without_test_code attribute to Eclipse project dependencies
  subprojects/ide/src/integTest/resources/org/gradle/plugins/ide/eclipse/EclipseIntegrationTest/canCreateAndDeleteMetaData/expectedFiles/commonClasspath.xml
  subprojects/ide/src/integTest/resources/org/gradle/plugins/ide/eclipse/EclipseIntegrationTest/canCreateAndDeleteMetaData/expectedFiles/webAppJava6Classpath.xml
  subprojects/ide/src/integTest/resources/org/gradle/plugins/ide/eclipse/EclipseIntegrationTest/canCreateAndDeleteMetaData/expectedFiles/webserviceClasspath.xml
  subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/internal/EclipsePluginConstants.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/internal/ProjectDependencyBuilder.java
Labels: @core, from:member

#13804 Fix project dependency metadata
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/DependencySubstitutionRulesIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/local/model/DefaultProjectDependencyMetadata.java
Labels: @jvm, a:bug, from:member, in:dependency-management

#13792 Fix NPE when a failure appears on a different selector
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/platforms/EnforcedPlatformIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/EdgeState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/SelectorState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/selectors/ResolvableSelectorState.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/selectors/TestModuleSelectorState.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/selectors/TestProjectSelectorState.groovy
Labels: a:bug, from:member

#13787 Disable build scans when using configuration caching and an incompatible plugin version
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
  subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/legacy/BuildScanEndOfBuildNotifierIntegrationTest.groovy
  subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/legacy/LegacyGradleEnterpriseCheckInConfigCachingIntegTest.groovy
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/impl/legacy/LegacyGradleEnterprisePluginCheckInService.java
Labels: from:member

#13825 Handle corner cases for excludes
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/excludes/factories/NormalizingExcludeFactory.java
Labels: @jvm, from:member, in:dependency-management

#13826 Clear enterprise plugin service ref before saving adapter to cache
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/tasks/SnapshotTaskInputsOperationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/internal/enterprise/core/GradleEnterprisePluginAdapter.java
  subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/GradleEnterprisePluginCheckInFixture.groovy
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/impl/DefaultGradleEnterprisePluginAdapter.java
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/impl/legacy/LegacyGradleEnterprisePluginCheckInService.java
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/InstantExecutionState.kt
Labels: from:member

#13777 Do not use deprecated method in Kotlin sample
  subprojects/docs/src/samples/templates/kotlin-utilities-library/src/main/kotlin/org/gradle/sample/utilities/SplitUtils.kt
Labels: @core, from:member, in:core

#13799 Change MultiTestRunner name pattern
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractMultiTestRunner.java
Labels: from:member

#13814 Add an ignored test that asserts for credentials not being serialized to configuration cache
  subprojects/model-core/src/integTest/groovy/org/gradle/api/provider/CredentialsProviderIntegrationTest.groovy
Labels: @core, from:member, in:core

#13829 Bump docker plugin version and remove JDK restriction from smoke test
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ArtifactoryAndDockerSmokeTest.groovy
Labels: @core, a:chore, from:member, in:core

#13834 Change name of watchFs tests without dependencies
  .teamcity/Gradle_Check/model/CIBuildModel.kt
Labels: @execution, from:member

#13822 Fix race conditions in credentials providers when evaluated during execution
  subprojects/model-core/src/integTest/groovy/org/gradle/api/provider/CredentialsProviderIntegrationTest.groovy
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/CredentialsProviderFactory.java
Labels: @core, a:bug, from:member, in:core

#13839 Some configuration cache doc refinements
  subprojects/docs/src/docs/userguide/img/configuration-cache-effect.gif
  subprojects/docs/src/docs/userguide/img/configuration-cache/problems-report.png
  subprojects/docs/src/docs/userguide/img/configuration-cache/running-help.gif
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
Labels: @configuration-cache

#13842 Hide `runToCompletion` behind `run(Write|Read)Operation`
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/DefaultInstantExecution.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/InstantExecutionState.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/coroutines/RunToCompletion.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/Running.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/TaskNodeCodec.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/jos/ObjectInputStreamAdapter.kt
  subprojects/instant-execution/src/test/kotlin/org/gradle/instantexecution/fingerprint/InstantExecutionFingerprintCheckerTest.kt
  subprojects/instant-execution/src/test/kotlin/org/gradle/instantexecution/serialization/codecs/AbstractUserTypeCodecTest.kt
Labels: @configuration-cache, from:member, in:configuration-cache

#13849 Do not auto apply plugins when loading build configuration from cache
  subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/GradleEnterprisePluginConfigurationCachingIntegrationTest.groovy
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/InstantExecutionHost.kt
Labels: from:member

#13832 Add empty output dirs always as output
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/changedetection/state/UpToDateIntegTest.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/impl/OutputFilterUtil.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/impl/OutputFilterUtilTest.groovy
Labels: @execution, from:member

#13776 Improve code around file system watching
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java
  subprojects/core/src/testFixtures/groovy/org/gradle/api/internal/file/TestFiles.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/FileSystemWatchingHandler.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/AbstractDelegatingVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/DefaultFileSystemWatchingHandler.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/LocationsUpdatedByCurrentBuild.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingNotSupportedFileSystemWatchingHandler.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/DefaultFileSystemWatchingHandlerTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/NonWatchingVirtualFileSystemTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingNotSupportedFileSystemWatchingHandlerTest.groovy
  subprojects/launcher/src/main/java/org/gradle/launcher/exec/InProcessBuildActionExecuter.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunner.java
  subprojects/launcher/src/test/groovy/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunnerTest.groovy
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/VirtualFileSystem.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultVirtualFileSystem.java
  subprojects/snapshots/src/test/groovy/org/gradle/internal/vfs/impl/AbstractVirtualFileSystemTest.groovy
Labels: @execution, from:member

#13828 Cleanup build scan publishing logic
  .teamcity/Gradle_Check/configurations/GradleBuildConfigurationDefaults.kt
  buildSrc/subprojects/profiling/src/main/kotlin/gradlebuild/buildscan.gradle.kts
  gradle/verification-metadata.xml
  settings.gradle.kts
Labels: @dev-productivity, a:chore, from:member

#13813 Fix UpdateBranchStatus and clean up githubToken parameter
  .teamcity/Gradle_Check/configurations/StagePasses.kt
  .teamcity/common/performance-test-extensions.kt
  .teamcityTest/Gradle_Check_Tests/CIConfigIntegrationTests.kt
  .teamcityTest/Gradle_Check_Tests/PerformanceTestBuildTypeTest.kt
  buildSrc/subprojects/build-update-utils/src/main/kotlin/gradlebuild/buildutils/tasks/UpdateBranchStatus.kt
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild/performance/reporter/DefaultPerformanceReporter.groovy
  buildSrc/subprojects/performance-testing/src/main/kotlin/gradlebuild/performance/PerformanceTestPlugin.kt
Labels: @dev-productivity, a:chore, from:member

#13860 Search for daemon crash logs in more places
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/daemon/DaemonLogsAnalyzer.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/AbstractGradleExecuter.java
Labels: @execution

#13865 Remove SlackReporter
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/AbstractCrossVersionGradleInternalPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/AbstractCrossVersionGradleProfilerPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/SlackReporter.groovy
Labels: @execution

#13863 Do not log environment to debug log
  subprojects/core/src/main/java/org/gradle/process/internal/DefaultExecHandle.java
Labels: from:member

#13858 Avoid zipping empty directory
  buildSrc/subprojects/buildquality/src/main/kotlin/gradlebuild/ci-reporting.gradle.kts
Labels: @dev-productivity, a:chore, from:member

#13877 Increase daemon idle timeout in DaemonLifecycleSpec
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/DaemonLifecycleSpec.groovy
Labels: @dev-productivity, from:member

#13880 Expose start param to enterprise plugin
  subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/GradleEnterprisePluginConfigurationCachingIntegrationTest.groovy
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/GradleEnterprisePluginBuildState.java
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/impl/DefaultGradleEnterprisePluginBuildState.java
Labels: from:member

#13827 Run watchFs tests without isolated daemons
  gradle/verification-metadata.xml
  subprojects/distributions-dependencies/distributions-dependencies.gradle.kts
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/GradleContextualExecuter.java
Labels: @execution, from:member

#13881 Do not log environment variables when debug logging is enabled
  subprojects/core/src/main/java/org/gradle/process/internal/DefaultExecHandle.java
  subprojects/docs/src/docs/release/notes.md
Labels: from:member

#13884 Add a linebreak in the example for `Provider.zip`
  subprojects/docs/src/docs/release/notes.md
Labels: from:member

#13836 Make `InstantExecutionCacheFingerprintWriter` thread-safe
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/fingerprint/InstantExecutionCacheFingerprintWriter.kt
Labels: @configuration-cache, a:bug, from:member, in:configuration-cache

#13889 Split file system watching integration tests
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/AbstractFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesBetweenBuildsFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesByGradleFileWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesDuringTheBuildFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/EnableFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/FileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/SymlinkFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/WatchedDirectoriesFileSystemWatchingIntegrationTest.groovy
Labels: @execution, from:member

#13885 Make `InstantExecutionCacheFingerprintWriter` thread-safe
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/DefaultInstantExecution.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/fingerprint/InstantExecutionCacheFingerprintWriter.kt
Labels: @configuration-cache, a:bug, from:member, in:configuration-cache

#13899 Don't delay writing input files to the config cache fingerprint
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/fingerprint/InstantExecutionCacheFingerprintWriter.kt
Labels: @configuration-cache, a:bug, from:member, in:configuration-cache

#13897 Upgradle to latest nightly for latest fs watching changes
  gradle/wrapper/gradle-wrapper.properties
Labels: @execution, from:member

#13900 Write configuration cache problems report to root project's buildDir
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionProblemReportingIntegrationTest.groovy
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/InstantExecutionReport.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/problems/InstantExecutionProblems.kt
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/instantexecution/InstantExecutionProblemsFixture.groovy
Labels: @configuration-cache, a:feature, from:member, in:configuration-cache

#13883 Enable console tests with watchFs
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/taskgrouping/AbstractConsoleCompositeBuildGroupedTaskFunctionalTest.groovy
Labels: @execution, from:member

#13906 Mention order independence of manifest normalization
  subprojects/docs/src/docs/release/notes.md
Labels: from:member

#13898 Hide test logs in Teamcity
  .teamcity/Gradle_Check/configurations/BaseGradleBuildType.kt
  .teamcity/Gradle_Check/projects/RootProject.kt
  .teamcity/common/extensions.kt
Labels: @dev-productivity, from:member

#13876 Add codeowners for release notes
  .github/CODEOWNERS
Labels: from:member

#13911 jonnybbb/gradle-enterprise-3.4-part-1
  subprojects/core/src/main/java/org/gradle/plugin/management/internal/autoapply/AutoAppliedGradleEnterprisePlugin.java
  subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/legacy/LegacyGradleEnterpriseCheckInConfigCachingIntegTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/BuildScanPluginSmokeTest.groovy
Labels: from:member

#13923 Add instructions to build distro from source in CONTRIBUTING
  CONTRIBUTING.md
Labels: a:chore, from:member

#13794 Fix infinite resolution
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/DependencyGraphBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ModuleResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ResolveState.java
Labels: @jvm, from:member, in:dependency-management

#13924 Simplify `reentrant` codec
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/Combinators.kt
Labels: @configuration-cache, a:performance-issue, from:member, in:configuration-cache

#13920 Enable partial invalidation always
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuter.java
  subprojects/core/src/main/java/org/gradle/cache/internal/DefaultFileContentCacheFactory.java
  subprojects/core/src/main/java/org/gradle/execution/ProjectExecutionServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuterTest.groovy
  subprojects/core/src/test/groovy/org/gradle/cache/internal/DefaultFileContentCacheFactoryTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/WorkExecutorTestFixture.java
  subprojects/execution/src/integTest/groovy/org/gradle/internal/execution/IncrementalExecutionIntegrationTest.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/OutputChangeListener.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/UnitOfWork.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/BroadcastChangingOutputsStep.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/BroadcastChangingOutputsStepTest.groovy
  subprojects/snapshots/src/integTest/groovy/org/gradle/internal/vfs/VirtualFileSystemPartialInvalidationIntegrationTest.groovy
Labels: @execution, from:member

#13909 Add test for using local artifact repositories with fs watching
  subprojects/file-watching/file-watching.gradle.kts
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/WatchedDirectoriesFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java
Labels: @execution, from:member

#13904 Remove CMD_LINE_ARGS in bat script to avoid leaking credentials
  gradlew.bat
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/ApplicationIntegrationSpec.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/ApplicationPluginIntegrationTest.groovy
  subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/windowsStartScript.txt
  subprojects/plugins/src/test/groovy/org/gradle/api/internal/plugins/WindowsStartScriptGeneratorTest.groovy
Labels: from:member

#13942 Use 'UNKNOWN' when git information is not available
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/gradlebuild/versioning/BuildVersionPlugin.kt
Labels: @dev-productivity

#13707 Update tested AGP versions
  gradle/dependency-management/agp-versions.properties
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerJavaCachingSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerKotlinCachingSmokeTest.groovy
Labels: a:chore, from:member

#13950 Add documentation for change in classpath normalization
  subprojects/core-api/src/main/java/org/gradle/api/tasks/Classpath.java
  subprojects/core-api/src/main/java/org/gradle/api/tasks/ClasspathNormalizer.java
  subprojects/docs/src/docs/userguide/authoring-builds/more_about_tasks.adoc
Labels: a:chore, from:member, in:core

#13944 Enable two more fs watching tests on Windows
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/WatchedDirectoriesFileSystemWatchingIntegrationTest.groovy
Labels: @execution, from:member

#13956 Add failure condition to detect potential credentials leaks
  .teamcity/common/extensions.kt
  .teamcityTest/Gradle_Check_Tests/CIConfigIntegrationTests.kt
Labels: @core, from:member, in:core

#13922 Limit env variables propagated
  buildSrc/subprojects/jvm/src/main/kotlin/gradlebuild/propagated-env-variables.kt
  buildSrc/subprojects/jvm/src/main/kotlin/gradlebuild/unittest-and-compile.gradle.kts
  subprojects/internal-testing/src/test/groovy/org/gradle/infra/EnvironmentVariablesPropagationTest.groovy
Labels: from:member

#13716 Update gradle-module-metadata-latest-specification.md
  subprojects/docs/src/docs/design/gradle-module-metadata-latest-specification.md
Labels: from:contributor

#13571 Remove public modifier from Groovy Plugin Gradle init templates
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/plugin/groovy/Plugin.groovy.template
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/plugin/groovy/spock/PluginFunctionalTest.groovy.template
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/plugin/groovy/spock/PluginTest.groovy.template
Labels: from:contributor

#13964 Do not output environment variable values to debug log
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/exec/EstablishBuildEnvironment.java
Labels: @core, from:member, in:core

#13583 Use dumb terminal settings as a backup
  subprojects/native/src/main/java/org/gradle/internal/nativeintegration/console/NativePlatformConsoleDetector.java
  subprojects/native/src/test/groovy/org/gradle/internal/nativeintegration/console/NativePlatformConsoleDetectorTest.groovy
Labels: from:contributor

#13967 PluginContainer supports id-based plugins if those use injection
  subprojects/core/src/main/java/org/gradle/api/internal/plugins/DefaultPluginContainer.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/plugins/DefaultPluginContainerTest.groovy
  subprojects/core/src/test/groovy/org/gradle/testfixtures/CustomPluginWithInjection.groovy
  subprojects/core/src/test/resources/META-INF/gradle-plugins/org.gradle.custom-plugin-with-injection.properties
Labels: @jvm, from:member

#13963 Add distribution size tests
  .teamcity/Gradle_Check/configurations/Gradleception.kt
  gradle/wrapper/gradle-wrapper.properties
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/AllDistributionIntegrationSpec.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/BinDistributionIntegrationSpec.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DistributionIntegrationSpec.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DistributionIntegritySpec.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DocsDistributionIntegrationSpec.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/SrcDistributionIntegrationSpec.groovy
Labels: @dev-productivity, from:member

#13973 Expose "What is Gradle?" section in user manual ToC
  subprojects/docs/src/main/resources/header.html
Labels: from:member, in:docs

#13947 Move Kotlin DSL specific build logic to buildSrc plugins
  buildSrc/subprojects/kotlin-dsl/kotlin-dsl.gradle.kts
  buildSrc/subprojects/kotlin-dsl/src/main/kotlin/gradlebuild/kotlin-dsl-compiler-embeddable.gradle.kts
  buildSrc/subprojects/kotlin-dsl/src/main/kotlin/gradlebuild/kotlin-dsl-dependencies-embedded.gradle.kts
  buildSrc/subprojects/kotlin-dsl/src/main/kotlin/gradlebuild/kotlin-dsl-plugin-extensions.gradle.kts
  buildSrc/subprojects/kotlin-dsl/src/main/kotlin/gradlebuild/kotlindsl/compiler/tasks/CheckKotlinCompilerEmbeddableDependencies.kt
  buildSrc/subprojects/kotlin-dsl/src/main/kotlin/gradlebuild/kotlindsl/compiler/tasks/PatchKotlinCompilerEmbeddable.kt
  buildSrc/subprojects/kotlin-dsl/src/main/kotlin/gradlebuild/kotlindsl/generator/tasks/CodeGenerationTask.kt
  buildSrc/subprojects/kotlin-dsl/src/main/kotlin/gradlebuild/kotlindsl/generator/tasks/GenerateKotlinDependencyExtensions.kt
  buildSrc/subprojects/kotlin-dsl/src/main/kotlin/gradlebuild/kotlindsl/generator/tasks/GenerateKotlinDslPluginsExtensions.kt
  buildSrc/subprojects/uber-plugins/uber-plugins.gradle.kts
  subprojects/kotlin-compiler-embeddable/kotlin-compiler-embeddable.gradle.kts
  subprojects/kotlin-dsl-plugins/kotlin-dsl-plugins.gradle.kts
  subprojects/kotlin-dsl/kotlin-dsl.gradle.kts
Labels: @dev-productivity, from:member, in:gradle-build
