Repository gradle/gradle, pull requests merged in 2020-06, with the labels that each got.

#13263 Refine TAPI model
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/DistributionTest.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/DistributionTestingPlugin.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/shared-configuration.kt
  buildSrc/subprojects/plugins/src/main/kotlin/gradlebuild/publish-public-libraries.gradle.kts
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/IntegrationTestBuildContext.java
  subprojects/plugin-development/plugin-development.gradle.kts
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/impldeps/GradleImplDepsCompatibilityIntegrationTest.groovy
  subprojects/tooling-api/tooling-api.gradle.kts
Labels: @dev-productivity, a:chore, from:member

#13295 Add remote projects as inputs to smoke test
  subprojects/smoke-test/smoke-test.gradle.kts
Labels: @dev-productivity, a:chore, from:member

#13285 Link to file-system watching blog post
  subprojects/docs/src/docs/release/notes.md
Labels: @build-cache, from:member

#13308 Temporarily unpublish android sample
  subprojects/docs/docs.gradle
Labels: a:chore, from:member, in:gradle-build

#13283 Move common file archive classes to the files module
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/ZipHasher.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/ClasspathWalker.java
  subprojects/files/src/main/java/org/gradle/api/internal/file/archive/ZipEntry.java
  subprojects/files/src/main/java/org/gradle/api/internal/file/archive/ZipInput.java
  subprojects/files/src/main/java/org/gradle/api/internal/file/archive/impl/FileZipInput.java
  subprojects/files/src/main/java/org/gradle/api/internal/file/archive/impl/JdkZipEntry.java
  subprojects/files/src/main/java/org/gradle/api/internal/file/archive/impl/StreamZipInput.java
  subprojects/files/src/main/java/org/gradle/internal/file/FileException.java
  subprojects/files/src/test/groovy/org/gradle/api/internal/file/archive/impl/FileZipInputTest.groovy
Labels: a:chore, from:member, in:core

#13297 Migrate to JUnit5 Vintage
  buildSrc/subprojects/configuration/src/main/kotlin/org/gradle/gradlebuild/BuildEnvironment.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/IntegrationTestsPlugin.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/shared-configuration.kt
  buildSrc/subprojects/plugins/plugins.gradle.kts
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/gradlebuild/unittestandcompile/UnitTestAndCompilePlugin.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/performance/PerformanceTestPlugin.kt
  gradle/dependencies.gradle
  gradle/verification-metadata.xml
  subprojects/docs/docs.gradle
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/AbstractRealLifeAndroidBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidBuildSlowPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/inception/GradleInceptionPerformanceTest.groovy
  subprojects/soak/soak.gradle.kts
  subprojects/test-kit/test-kit.gradle.kts
  subprojects/testing-jvm/testing-jvm.gradle.kts
Labels: from:member

#13238 Fix disabling of incremental scala compilation
  subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/ZincScalaCompiler.java
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/ForceScalaCompileIntegrationTest.groovy
Labels: @jvm, from:member, in:jvm-ecosystem, in:scala-plugin

#13305 Move archive operations to their own service
  subprojects/core-api/src/main/java/org/gradle/api/file/ArchiveOperations.java
  subprojects/core-api/src/main/java/org/gradle/api/file/ProjectLayout.java
  subprojects/core/src/integTest/groovy/org/gradle/api/file/ArchiveOperationsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/file/ProjectLayoutIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/file/DefaultArchiveOperations.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/DefaultProjectLayout.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/BuildScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/WorkerSharedProjectScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/DefaultProjectLayoutTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/DefaultProjectTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/util/TestUtil.groovy
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/extending-gradle/custom_gradle_types.adoc
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionIntegrationTest.groovy
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/Codecs.kt
  subprojects/model-core/src/main/java/org/gradle/internal/isolated/IsolationScheme.java
Labels: @configuration-cache, from:member, in:core

#13299 Add support for capabilities substitutions
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildDeclaredSubstitutionsIntegrationTest.groovy
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/CompositeBuildServices.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/IncludedBuildDependencySubstitutionsBuilder.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/VariantSelectionDetails.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/VariantsDependencySubstitutionRulesIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationContainer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/CapabilityNotationParserFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/dependencysubstitution/DefaultDependencySubstitutions.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolutionstrategy/DefaultResolutionStrategy.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/EdgeState.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/DefaultModuleComponentSelector.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/local/model/DefaultProjectComponentSelector.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/dependencysubstitution/DefaultDependencySubstitutionsSpec.groovy
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/internal/resolve/JvmLibraryResolveContext.java
Labels: @jvm, from:member, in:dependency-management

#13253 Use org.gradle.api.credentials.PasswordCredentials internally
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/HttpResource.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/HttpServer.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishHttpIntegTest.groovy
  subprojects/resources-http/src/main/java/org/gradle/internal/authentication/DefaultBasicAuthentication.java
  subprojects/resources-http/src/main/java/org/gradle/internal/authentication/DefaultDigestAuthentication.java
  subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/HttpProxySettings.java
  subprojects/resources-http/src/test/groovy/org/gradle/internal/resource/transport/http/HttpClientConfigurerTest.groovy
  subprojects/resources-http/src/test/groovy/org/gradle/internal/resource/transport/http/ntlm/NTLMCredentialsTest.groovy
  subprojects/resources-s3/src/main/java/org/gradle/internal/resource/transport/aws/s3/S3Client.java
  subprojects/resources-sftp/src/main/java/org/gradle/internal/resource/transport/sftp/SftpClientFactory.java
  subprojects/resources-sftp/src/main/java/org/gradle/internal/resource/transport/sftp/SftpConnectorFactory.java
  subprojects/resources-sftp/src/main/java/org/gradle/internal/resource/transport/sftp/SftpHost.java
  subprojects/resources-sftp/src/main/java/org/gradle/internal/resource/transport/sftp/SftpResource.java
  subprojects/resources-sftp/src/main/java/org/gradle/internal/resource/transport/sftp/SftpResourceAccessor.java
  subprojects/resources-sftp/src/main/java/org/gradle/internal/resource/transport/sftp/SftpResourceLister.java
  subprojects/resources-sftp/src/main/java/org/gradle/internal/resource/transport/sftp/SftpResourceUploader.java
  subprojects/resources-sftp/src/test/groovy/org/gradle/internal/resource/transport/sftp/SftpClientFactoryTest.groovy
Labels: @core, a:chore, from:member, in:core

#13300 Refactor `GenerateModuleMetadata` toward compatibility with the configuration cache
  subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultImmutableAttributesFactory.java
  subprojects/core/src/main/java/org/gradle/internal/hash/DefaultChecksumService.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/projectmodule/DefaultProjectDependencyPublicationResolver.java
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/GradleModuleMetadataWriter.java
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/metadata/ComponentData.java
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/metadata/GradleModuleMetadataWriter.java
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/metadata/InvalidPublicationChecker.java
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/metadata/JsonWriterScope.java
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/metadata/ModuleMetadataJsonWriter.java
  subprojects/publish/src/main/java/org/gradle/api/publish/tasks/GenerateModuleMetadata.java
  subprojects/publish/src/test/groovy/org/gradle/api/publish/internal/metadata/GradleModuleMetadataWriterTest.groovy
Labels: @configuration-cache, a:feature, from:member, in:configuration-cache

#13319 Rework configuration cache build options
  subprojects/build-events/src/integTest/groovy/org/gradle/build/event/BuildEventsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/services/BuildServiceIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/StartParameterInternal.java
  subprojects/core/src/main/java/org/gradle/initialization/StartParameterBuildOptions.java
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
  subprojects/docs/src/snippets/configurationCache/testKit/groovy/src/test/groovy/org/example/BuildLogicFunctionalTest.groovy
  subprojects/docs/src/snippets/configurationCache/testKit/kotlin/src/test/kotlin/org/example/BuildLogicFunctionalTest.kt
  subprojects/instant-execution/src/crossVersionTest/groovy/org/gradle/instantexecution/InstantExecutionCacheCrossVersionTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/AbstractInstantExecutionIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionClassLoaderCachingIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionEnablingIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionGroovyIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionProblemReportingIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionToolingApiInvocationIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/inputs/undeclared/AbstractUndeclaredBuildInputsIntegrationTest.groovy
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/initialization/InstantExecutionStartParameter.kt
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/InstantExecutionRunner.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/InstantExecutionGradleExecuter.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/instantexecution/InstantExecutionProblemsFixture.groovy
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/action/BuildActionSerializer.java
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/FasterIncrementalAndroidBuildsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaInstantExecutionPerformanceTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildInstantExecutionSmokeTest.groovy
Labels: from:member, in:configuration-cache

#13332 Reenable configuration cache performance test
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaInstantExecutionPerformanceTest.groovy
Labels: @configuration-cache, a:chore, from:member

#13321 Fix flaky InstantExecutionCacheCleanupIntegrationTest
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionCacheCleanupIntegrationTest.groovy
Labels: @configuration-cache, from:member

#13301 Small performance improvements
  subprojects/base-services/src/main/java/org/gradle/internal/resources/AbstractTrackedResourceLock.java
  subprojects/base-services/src/main/java/org/gradle/internal/resources/DefaultResourceLockCoordinationService.java
  subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java
Labels: @build-cache, @core, from:contributor

#13345 Round of documentation and fixes on core plugins for configuration caching
  subprojects/core/src/integTest/groovy/org/gradle/caching/configuration/internal/BuildCacheCompositeConfigurationIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/configuration/ExecuteUserLifecycleListenerBuildOperationIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/configuration/project/LifecycleProjectEvaluatorIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/BuildInitializationBuildOperationsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/CalculateTaskGraphBuildOperationIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/PropertiesLoaderIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/buildsrc/DisallowBuildSrcAsNameIntegTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/plugin/ScriptPluginClassLoadingIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/process/internal/CancellationIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/util/VersionNumberIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/ApplicationIntegrationSpec.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/ExecIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/environment/BuildEnvironmentIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/language/java/JavaCompilerContinuousIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/language/java/JavaComponentCompilerDaemonReuseIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/language/java/plugins/JavaLanguagePluginIntegrationTest.groovy
  subprojects/language-jvm/src/testFixtures/groovy/org/gradle/api/tasks/compile/AbstractCompilerContinuousIntegrationTest.groovy
  subprojects/language-jvm/src/testFixtures/groovy/org/gradle/api/tasks/compile/AbstractCompilerDaemonReuseIntegrationTest.groovy
  subprojects/language-jvm/src/testFixtures/groovy/org/gradle/api/tasks/compile/AbstractComponentCompilerDaemonReuseIntegrationTest.groovy
  subprojects/language-jvm/src/testFixtures/groovy/org/gradle/integtests/language/AbstractJvmLanguageIncrementalBuildIntegrationTest.groovy
  subprojects/language-jvm/src/testFixtures/groovy/org/gradle/integtests/language/AbstractJvmLanguageIntegrationTest.groovy
  subprojects/language-jvm/src/testFixtures/groovy/org/gradle/integtests/language/AbstractJvmPluginLanguageIntegrationTest.groovy
  subprojects/language-scala/src/integTest/groovy/org/gradle/language/scala/JointScalaLangIntegrationTest.groovy
  subprojects/language-scala/src/integTest/groovy/org/gradle/language/scala/ScalaCompilerContinuousIntegrationTest.groovy
  subprojects/language-scala/src/integTest/groovy/org/gradle/language/scala/ScalaComponentCompilerDaemonReuseIntegrationTest.groovy
  subprojects/language-scala/src/integTest/groovy/org/gradle/language/scala/ScalaLanguageIncrementalBuildIntegrationTest.groovy
  subprojects/language-scala/src/integTest/groovy/org/gradle/language/scala/ScalaLanguageIntegrationTest.groovy
  subprojects/language-scala/src/integTest/groovy/org/gradle/language/scala/plugins/ScalaLanguagePluginIntegrationTest.groovy
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/jvm/AbstractConsoleJvmTestWorkerFunctionalTest.groovy
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/jvm/ConsoleTestNGUnsupportedTestWorkerFunctionalTest.groovy
  subprojects/model-core/src/integTest/groovy/org/gradle/api/provider/AbstractPropertyLanguageInterOpIntegrationTest.groovy
  subprojects/model-core/src/integTest/groovy/org/gradle/api/provider/PropertyIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/ApplicationPluginConfigurationIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/ApplicationPluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/ApplicationPluginUnixShellsIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/DistributionPluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecDebugIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecWithExecutableJarIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecWithLongCommandLineIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/bundling/WarTaskIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/PluginsComponentReportIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/AbstractJavaCompileAvoidanceIntegrationSpec.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/AbstractJavaGroovyCompileAvoidanceIntegrationSpec.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/BasicJavaCompilerIntegrationSpec.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/fixtures/AbstractJavaTestFixturesIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/tasks/bundling/War.java
  subprojects/testing-base/src/integTest/groovy/org/gradle/testing/TestExecutionBuildOperationsIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/IncrementalTestIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestOutputListenerIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestTaskIntegrationTest.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerExecutorErrorHandlingIntegrationTest.groovy
Labels: @configuration-cache, from:member

#13340 Update list of install tasks
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/gradlebuild/versioning/BuildVersionPlugin.kt
Labels: @dev-productivity, from:member

#13349 Extract serializable `ModuleMetadata` model from `ModuleMetadataJsonWriter`
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/metadata/GradleModuleMetadataWriter.java
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/metadata/ModuleMetadata.java
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/metadata/ModuleMetadataBuilder.java
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/metadata/ModuleMetadataJsonWriter.java
  subprojects/publish/src/test/groovy/org/gradle/api/publish/internal/metadata/GradleModuleMetadataWriterTest.groovy
Labels: @configuration-cache, a:chore, from:member, in:dependency-management

#13306 Round both lastModified for CommonFileSystemTest
  subprojects/native/src/test/groovy/org/gradle/internal/nativeintegration/filesystem/CommonFileSystemTest.groovy
  subprojects/native/src/test/groovy/org/gradle/internal/nativeintegration/filesystem/services/NativePlatformBackedFileMetadataAccessorTest.groovy
Labels: from:member

#13324 Prefer watching roots of nested builds
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultIncludedBuild.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultIncludedBuildRegistry.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultNestedBuild.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultRootBuildState.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/RootOfNestedBuildTree.java
  subprojects/composite-builds/src/test/groovy/org/gradle/composite/internal/DefaultIncludedBuildRegistryTest.groovy
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradleLauncher.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradleLauncherFactory.java
  subprojects/core/src/main/java/org/gradle/initialization/GradleLauncher.java
  subprojects/core/src/main/java/org/gradle/internal/build/BuildAddedListener.java
  subprojects/core/src/main/java/org/gradle/internal/build/BuildState.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemBuildLifecycleListener.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java
  subprojects/core/src/main/java/org/gradle/testfixtures/internal/ProjectBuilderImpl.java
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/VirtualFileSystemRetentionIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/WatchingAwareVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/NonWatchingVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystemTest.groovy
Labels: @build-cache, from:member

#13359 Don't unpack embeddable Kotlin compiler
  subprojects/kotlin-compiler-embeddable/kotlin-compiler-embeddable.gradle.kts
Labels: @build-cache, @dev-productivity, from:member

#13348 Fix snippet references in user guide
  subprojects/docs/README.md
  subprojects/docs/src/docs/userguide/authoring-builds/ant.adoc
  subprojects/docs/src/docs/userguide/authoring-builds/build_lifecycle.adoc
  subprojects/docs/src/docs/userguide/authoring-builds/logging.adoc
  subprojects/docs/src/docs/userguide/authoring-builds/more_about_tasks.adoc
  subprojects/docs/src/docs/userguide/authoring-builds/multi_project_builds.adoc
  subprojects/docs/src/docs/userguide/authoring-builds/potential_traps.adoc
  subprojects/docs/src/docs/userguide/authoring-builds/tutorial_using_tasks.adoc
  subprojects/docs/src/docs/userguide/authoring-builds/working_with_files.adoc
  subprojects/docs/src/docs/userguide/authoring-builds/writing_build_scripts.adoc
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/declaring_dependencies.adoc
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/viewing_debugging_dependencies.adoc
  subprojects/docs/src/docs/userguide/dep-man/04-modeling-features/artifact_transforms.adoc
  subprojects/docs/src/docs/userguide/dep-man/05-multirepo-environment/composite_builds.adoc
  subprojects/docs/src/docs/userguide/dep-man/06-publishing/publishing_customization.adoc
  subprojects/docs/src/docs/userguide/dep-man/06-publishing/publishing_signing.adoc
  subprojects/docs/src/docs/userguide/dep-man/06-publishing/signing_plugin.adoc
  subprojects/docs/src/docs/userguide/extending-gradle/custom_plugins.adoc
  subprojects/docs/src/docs/userguide/extending-gradle/custom_tasks.adoc
  subprojects/docs/src/docs/userguide/extending-gradle/lazy_configuration.adoc
  subprojects/docs/src/docs/userguide/jvm/java_testing.adoc
  subprojects/docs/src/docs/userguide/legacy/software_model.adoc
  subprojects/docs/src/docs/userguide/legacy/software_model_extend.adoc
  subprojects/docs/src/docs/userguide/migration/migrating_from_maven.adoc
  subprojects/docs/src/docs/userguide/native/native_software.adoc
  subprojects/docs/src/docs/userguide/reference/command_line_interface.adoc
  subprojects/docs/src/docs/userguide/reference/gradle_wrapper.adoc
  subprojects/docs/src/docs/userguide/running-builds/build_environment.adoc
  subprojects/docs/src/docs/userguide/running-builds/init_scripts.adoc
  subprojects/docs/src/docs/userguide/running-builds/intro_multi_project_builds.adoc
Labels: a:bug, from:member, in:docs

#13343 Upgrade Gradle Enterprise Gradle plugin to 3.3.4
  buildSrc/subprojects/profiling/profiling.gradle.kts
  settings.gradle.kts
  subprojects/core/src/main/java/org/gradle/plugin/management/internal/autoapply/AutoAppliedGradleEnterprisePlugin.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/BuildScanPluginSmokeTest.groovy
Labels: from:member

#13356 Let Exec and JavaExec tasks work with configuration caching
  subprojects/build-cache-http/src/integTest/groovy/org/gradle/caching/http/internal/HttpBuildCacheServiceIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/GroovyApplicationInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/JavaApplicationInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/JavaLibraryInitIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/AbstractExecutionResultExecTaskIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedTaskExecutionIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskTimeoutIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/console/AbstractExecOutputIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/process/internal/CancellationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/tasks/AbstractExecTask.java
  subprojects/core/src/main/java/org/gradle/api/tasks/JavaExec.java
  subprojects/core/src/main/java/org/gradle/process/internal/AbstractExecHandleBuilder.java
  subprojects/core/src/main/java/org/gradle/process/internal/DefaultExecHandleBuilder.java
  subprojects/core/src/main/java/org/gradle/process/internal/DefaultExecSpec.java
  subprojects/core/src/main/java/org/gradle/process/internal/DefaultJavaExecSpec.java
  subprojects/core/src/main/java/org/gradle/process/internal/JavaExecHandleBuilder.java
  subprojects/core/src/main/java/org/gradle/process/internal/ProcessArgumentsSpec.java
  subprojects/core/src/main/java/org/gradle/process/internal/ProcessStreamsSpec.java
  subprojects/core/src/test/groovy/org/gradle/api/tasks/ExecTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/ExecIntegrationTest.groovy
  subprojects/integ-test/src/integTest/resources/org/gradle/integtests/ExecIntegrationTest/shared/src/main/java/org/gradle/TestMain.java
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/BuildEnvironmentIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/ApplicationPluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/ApplicationPluginUnixShellsIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecDebugIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecWithExecutableJarIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecWithLongCommandLineIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaCrossCompilationIntegrationTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginSmokeTest.groovy
Labels: @configuration-cache, from:member, in:core

#13368 Fix the Antlr task for the configuration cache
  subprojects/antlr/src/integTest/groovy/org/gradle/api/plugins/antlr/IncrementalAntlrTaskIntegrationTest.groovy
  subprojects/antlr/src/main/java/org/gradle/api/plugins/antlr/AntlrTask.java
  subprojects/antlr/src/main/java/org/gradle/api/plugins/antlr/internal/AntlrSpecFactory.java
  subprojects/antlr/src/test/groovy/org/gradle/api/plugins/antlr/internal/AntlrSpecFactoryTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractProjectRelocationIntegrationTest.groovy
Labels: @configuration-cache, from:member, in:antlr-plugin

#13342 Introduce stale bot configuration
  .github/stale.yml
Labels: @jvm, from:member

#13374 Let the `java-gradle-plugin` plugin work with configuration caching
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/GroovyGradlePluginInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/JavaGradlePluginInitIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/WellBehavedPluginTest.groovy
  subprojects/kotlin-dsl/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/KotlinSettingsScriptIntegrationTest.kt
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/impldeps/GradleImplDepsPublishingIntegrationTest.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/plugins/JavaGradlePluginPluginIntegrationTest.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/plugins/JavaGradlePluginPluginPublishingIntegrationTest.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/plugins/JavaGradlePluginPluginTestKitSetupIntegrationTest.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidatePluginsIntegrationTest.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidateTaskPropertiesIntegrationTest.groovy
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/plugins/JavaGradlePluginPlugin.java
  subprojects/plugin-development/src/test/groovy/org/gradle/plugin/devel/plugins/JavaGradlePluginPluginTest.groovy
  subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/repository/AuthenticatedPluginRepositorySpec.groovy
  subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/repository/ResolvingFromMultipleCustomPluginRepositorySpec.groovy
  subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/repository/ResolvingFromSingleCustomPluginRepositorySpec.groovy
  subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/use/SettingsScriptPluginIntegrationSpec.groovy
Labels: from:member, in:configuration-cache, in:plugin-development

#13352 Add support for classpath hashing of zips nested in directories
  subprojects/core/src/integTest/groovy/org/gradle/normalization/ConfigureRuntimeClasspathNormalizationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/classpath/impl/ClasspathFingerprintingStrategy.java
Labels: a:feature, from:member, in:core

#13328 Move classes from changedetection to common modules
  subprojects/core/core.gradle.kts
  subprojects/core/src/main/java/org/gradle/execution/ProjectExecutionServices.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/classpath/ClasspathResourceFilters.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/classpath/impl/DefaultClasspathFingerprinter.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java
  subprojects/core/src/main/java/org/gradle/normalization/internal/DefaultRuntimeClasspathNormalization.java
  subprojects/core/src/main/java/org/gradle/normalization/internal/RuntimeClasspathNormalizationInternal.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/changedetection/state/DefaultResourceSnapshotterCacheServiceTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/fingerprint/classpath/impl/DefaultClasspathFingerprinterTest.groovy
  subprojects/normalization-java/normalization-java.gradle.kts
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/AbiExtractingClasspathResourceHasher.java
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/CachingResourceHasher.java
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/ConfigurableNormalizer.java
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/IgnoringResourceEntryFilter.java
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/IgnoringResourceFilter.java
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/ManifestFileZipEntryHasher.java
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/MetaInfAwareClasspathResourceHasher.java
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/PropertiesFileZipEntryHasher.java
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/PropertyResourceBundleFallbackCharset.java
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/RegularFileHasher.java
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/ResourceEntryFilter.java
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/ResourceFilter.java
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/ResourceHasher.java
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/ResourceSnapshotterCacheService.java
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/RuntimeClasspathResourceHasher.java
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/ZipEntryContext.java
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/ZipEntryHasher.java
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/ZipHasher.java
  subprojects/normalization-java/src/main/java/org/gradle/internal/fingerprint/classpath/impl/ClasspathFingerprintingStrategy.java
  subprojects/normalization-java/src/test/groovy/org/gradle/api/internal/changedetection/state/CachingResourceHasherTest.groovy
  subprojects/normalization-java/src/test/groovy/org/gradle/api/internal/changedetection/state/ManifestFileZipEntryHasherTest.groovy
  subprojects/normalization-java/src/test/groovy/org/gradle/api/internal/changedetection/state/MetaInfAwareClasspathResourceHasherTest.groovy
  subprojects/normalization-java/src/test/groovy/org/gradle/api/internal/changedetection/state/PropertiesFileZipEntryHasherTest.groovy
  subprojects/normalization-java/src/test/groovy/org/gradle/api/internal/changedetection/state/PropertyResourceBundleFallbackCharsetTest.groovy
  subprojects/normalization-java/src/test/groovy/org/gradle/api/internal/changedetection/state/ZipHasherTest.groovy
Labels: a:chore, from:member, in:core

#13365 Fix class cast exception when release flag is not a string
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompilerArgumentsBuilder.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/JavaCompilerArgumentsBuilderTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/BasicJavaCompilerIntegrationSpec.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/JvmPluginsHelper.java
Labels: @jvm, a:bug, from:member, in:jvm-ecosystem

#13350 Improve tracking of unattached dependencies
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/platforms/JavaPlatformResolveIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/EdgeState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ModuleResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/NodeState.java
Labels: @jvm, from:member, in:dependency-management

#13371 Make `GenerateModuleMetadata` compatible with the configuration cache
  subprojects/instant-execution/instant-execution.gradle.kts
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionPublishingIntegrationTest.groovy
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/UnsupportedTypesCodecs.kt
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/metadata/GradleModuleMetadataWriter.java
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/metadata/ModuleMetadataJsonWriter.java
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/metadata/ModuleMetadataSpec.java
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/metadata/ModuleMetadataSpecBuilder.java
  subprojects/publish/src/main/java/org/gradle/api/publish/tasks/GenerateModuleMetadata.java
Labels: @configuration-cache, a:feature, from:member, in:configuration-cache, in:publishing-plugin

#13383 Make the Application plugin work with the configuration cache
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginDependenciesIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/internal/scopeids/ScopeIdsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/normalization/ConfigureRuntimeClasspathNormalizationIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/process/internal/ErrorInWorkerSocketIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/ApplicationIntegrationSpec.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/WellBehavedPluginTest.groovy
  subprojects/javascript/src/integTest/groovy/org/gradle/plugins/javascript/rhino/RhinoPluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/ApplicationPluginConfigurationIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/ApplicationPluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/ApplicationPluginUnixShellsIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/AbstractJavaCompileAvoidanceIntegrationSpec.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/BasicJavaCompilerIntegrationSpec.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/ApplicationPlugin.java
Labels: @configuration-cache, from:member, in:application-plugin

#13388 Bump smoke tested errorprone plugin from 1.1.1 to 1.2.1
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ThirdPartyPluginsSmokeTest.groovy
Labels: @configuration-cache, from:member

#13384 Reduce likeliness of a fluke with configuration cache cleanup test
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionCacheCleanupIntegrationTest.groovy
  subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/ConcurrentTestUtil.groovy
Labels: from:member, in:configuration-cache

#13387 Rewrite JavaProcessStackTracesMonitor in Java
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/lifecycle/LifecyclePlugin.kt
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/timeout/IntegrationTestTimeoutInterceptor.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/timeout/JavaProcessStackTracesMonitor.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/timeout/JavaProcessStackTracesMonitor.java
  subprojects/internal-integ-testing/src/test/groovy/org/gradle/integtests/fixtures/timeout/JavaProcessStackTracesMonitorSpec.groovy
Labels: @dev-productivity, a:bug, from:member

#13379 Fix wording for stale comments
  .github/stale.yml
Labels: @jvm

#13378 Fix missing-project bug with configuration caching
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/InstantExecutionState.kt
  subprojects/instant-execution/src/test/kotlin/org/gradle/instantexecution/FillTheProjectGapsTest.kt
Labels: a:bug, from:member, in:configuration-cache

#13399 Update smoke tested AGP versions
  gradle/dependency-management/agp-versions.properties
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerJavaCachingSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerKotlinCachingSmokeTest.groovy
Labels: @configuration-cache, a:chore

#13293 Fix whitespace error in gradlew unix start script
  subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
Labels: @jvm, a:bug, from:contributor, in:jvm-ecosystem, in:modular-java

#13406 Refine docs tests
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/gradlebuild/unittestandcompile/UnitTestAndCompilePlugin.kt
  gradle/verification-metadata.xml
  subprojects/docs/docs.gradle
Labels: @dev-productivity, from:member

#13425 Rewrite @Unroll tests
  subprojects/launcher/src/test/groovy/org/gradle/launcher/cli/BuildActionSerializerTest.groovy
Labels: @dev-productivity, from:member

#13423 Ignore some tests under vfsRetentionTest
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/DependenciesAttributesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationSignatureCheckIntegTest.groovy
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/taskgrouping/rich/RichConsoleCompositeBuildGroupedTaskFunctionalTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/groovy/GroovyJavaLibraryInteractionIntegrationTest.groovy
Labels: @dev-productivity, @execution, a:chore, from:member

#13335 Keep old project root directories around
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/VirtualFileSystemRetentionIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/SnapshotWatchedDirectoryFinder.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/SnapshotWatchedDirectoryFinderTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystemTest.groovy
Labels: @execution, from:member

#13432 Add fs watching CI builds without dependencies
  .teamcity/Gradle_Check/configurations/FunctionalTest.kt
  .teamcity/Gradle_Check/model/CIBuildModel.kt
Labels: @execution, from:member

#13391 Make `GenerateMavenPom` compatible with the configuration cache
  subprojects/base-services/src/main/java/org/gradle/internal/serialization/Cached.java
  subprojects/base-services/src/main/java/org/gradle/internal/serialization/Transient.java
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionPublishingIntegrationTest.groovy
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/ProjectSchemaAccessorsIntegrationTest.kt
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/SamplesMavenPublishIntegrationTest.groovy
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/tasks/MavenPomFileGenerator.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/tasks/AbstractPublishToMaven.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/tasks/GenerateMavenPom.java
  subprojects/publish/src/main/java/org/gradle/api/publish/tasks/GenerateModuleMetadata.java
Labels: @configuration-cache, a:feature, from:member, in:configuration-cache

#13412 More configuration cache documentation
  subprojects/docs/README.md
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
  subprojects/docs/src/docs/userguide/troubleshooting.adoc
  subprojects/docs/src/docsTest/java/org/gradle/docs/samples/ExemplarExternalSamplesFunctionalTest.java
  subprojects/docs/src/main/resources/header.html
  subprojects/docs/src/snippets/configurationCache/noProblem/groovy/build.gradle
  subprojects/docs/src/snippets/configurationCache/noProblem/groovy/gradle.properties
  subprojects/docs/src/snippets/configurationCache/noProblem/groovy/settings.gradle
  subprojects/docs/src/snippets/configurationCache/noProblem/tests/configurationCacheNoProblem.sample.conf
  subprojects/docs/src/snippets/configurationCache/noProblem/tests/load.out
  subprojects/docs/src/snippets/configurationCache/noProblem/tests/store.out
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/logging/ConfigurationCacheOutputNormalizer.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/logging/GradleWelcomeOutputNormalizer.groovy
Labels: @configuration-cache, from:member

#13434 Rename VfsRetention -> FileSystemWatching
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/shared-configuration.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/lifecycle/LifecyclePlugin.kt
  buildSrc/subprojects/profiling/src/main/kotlin/org/gradle/gradlebuild/profiling/buildscan/BuildScanPlugin.kt
  subprojects/core/src/integTest/groovy/org/gradle/api/AbstractDomainObjectContainerIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/internal/operations/logging/LoggingBuildOperationProgressIntegTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/DependenciesAttributesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationIntegrityCheckIntegTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationSignatureCheckIntegTest.groovy
  subprojects/docs/src/docs/userguide/running-builds/gradle_daemon.adoc
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/FileSystemWatchingIntegrationTest.groovy
  subprojects/internal-integ-testing/src/integTest/groovy/org/gradle/integtests/fixtures/executer/InProcessGradleExecuterIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractIntegrationTest.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/FileSystemWatchingFixture.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/FileSystemWatchingHelper.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/ToBeFixedForFileSystemWatching.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/ToBeFixedForFileSystemWatchingExtension.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/ToBeFixedForFileSystemWatchingRule.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/FileSystemWatchingGradleExecuter.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/GradleContextualExecuter.java
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginGradlePluginCrossVersionSmokeTest.kt
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginTest.kt
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/precompiled/AbstractPrecompiledScriptPluginTest.kt
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/taskgrouping/rich/RichConsoleCompositeBuildGroupedTaskFunctionalTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/groovy/GroovyJavaLibraryInteractionIntegrationTest.groovy
  subprojects/snapshots/src/integTest/groovy/org/gradle/internal/vfs/VirtualFileSystemPartialInvalidationIntegrationTest.groovy
  subprojects/soak/src/integTest/groovy/org/gradle/vfs/FileSystemWatchingSoakTest.groovy
Labels: @execution, from:member

#13411 Fix Windows JVM crash when file-system watching is enabled
  gradle/dependencies.gradle
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/DependenciesAttributesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationIntegrityCheckIntegTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationSignatureCheckIntegTest.groovy
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/taskgrouping/rich/RichConsoleCompositeBuildGroupedTaskFunctionalTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/groovy/GroovyJavaLibraryInteractionIntegrationTest.groovy
Labels: @execution

#13435 Instrument `Spec<T>` lambdas for compatibility with the configuration cache
  subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingTransformer.java
  subprojects/core/src/test/groovy/org/gradle/internal/classpath/DefaultCachedClasspathTransformerTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionIntegrationTest.groovy
Labels: @configuration-cache, from:member, in:configuration-cache

#13443 Enhance user messages when using the configuration cache
  subprojects/instant-execution-report/src/main/kotlin/InstantExecutionReportPage.kt
  subprojects/instant-execution-report/src/main/kotlin/Main.kt
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionProblemReportingIntegrationTest.groovy
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/DefaultInstantExecution.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/InstantExecutionCacheAction.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/InstantExecutionException.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/InstantExecutionReport.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/problems/InstantExecutionProblems.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/problems/ProblemsSummary.kt
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/instantexecution/InstantExecutionProblemsFixture.groovy
Labels: from:member, in:configuration-cache

#13430 Update NameMatcher test condition to pass with JDK15
  subprojects/core/src/test/groovy/org/gradle/util/NameMatcherTest.java
Labels: @core, from:member, in:core

#13397 Make `PublishToMavenRepository` compatible with the configuration cache
  buildSrc/subprojects/plugins/src/main/kotlin/gradlebuild/publish-public-libraries.gradle.kts
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultDependencyManagementServices.java
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionPublishingIntegrationTest.groovy
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/WorkNodeCodec.kt
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/AbstractMavenPublishJavaIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenGradleModuleMetadataPublishIntegrationTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishArtifactCustomizationIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishBasicIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishCoordinatesIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishCustomComponentIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishIdentifierValidationIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishIssuesIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishLoggingIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishMultiProjectIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishPomCustomizationIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishPomCustomizationKotlinDslIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishPomPackagingIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/SamplesMavenPublishIntegrationTest.groovy
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/artifact/SingleOutputTaskMavenArtifact.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/DefaultMavenPublication.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publisher/MavenNormalizedPublication.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publisher/MavenRemotePublisher.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/tasks/PublishToMavenRepository.java
  subprojects/maven/src/test/groovy/org/gradle/api/publish/maven/internal/publication/DefaultMavenPublicationTest.groovy
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/PublishOperation.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildInstantExecutionSmokeTest.groovy
Labels: @configuration-cache, a:feature, from:member, in:configuration-cache

#13489 Fix Java attribute describer when category is missing
  subprojects/core/src/main/java/org/gradle/api/internal/artifacts/JavaEcosystemAttributesDescriber.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/artifacts/JavaEcosystemAttributesDescriberTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/util/AttributeTestUtil.groovy
Labels: @jvm, a:bug, from:member, in:jvm-ecosystem

#13502 Make test in WarTaskIntegrationTest properly isolated
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/bundling/WarTaskIntegrationTest.groovy
Labels: from:member

#13495 Don't rely on the artifact's existence to decide whether it should be published
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/JavaCompileOnlyDependencyIntegrationTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishIdentifierValidationIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishResolvedVersionsJavaIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/SamplesMavenPublishIntegrationTest.groovy
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/DefaultMavenPublication.java
  subprojects/maven/src/test/groovy/org/gradle/api/publish/maven/internal/publication/DefaultMavenPublicationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/DistributionPluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/fixtures/AbstractJavaTestFixturesIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlatformPlugin.java
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesCustomExternalTaskIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesCustomPluginIntegrationTest.groovy
Labels: @configuration-cache, from:member, in:configuration-cache, in:publishing-plugin

#13518 Review core plugins for compatibility with the configuration cache
  subprojects/platform-base/src/main/java/org/gradle/language/base/plugins/LifecycleBasePlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/BasePlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaBasePlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java
Labels: @configuration-cache, from:member, in:configuration-cache, in:core

#13534 Review more tests for compatibility with the configuration cache
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/LambdaInputsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/plugin/ScriptPluginClassLoadingIntegrationTest.groovy
  subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/repository/ResolvingSnapshotFromPluginRepositorySpec.groovy
  subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/repository/ResolvingWithPluginManagementSpec.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/JavaPluginIntegrationTest.groovy
Labels: @configuration-cache, a:chore, from:member, in:configuration-cache

#13527 User better APIs in build logic
  buildSrc/subprojects/docs/src/main/groovy/org/gradle/gradlebuild/docs/GradleUserManualPlugin.java
  buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/integrationtests/DistributionTest.kt
  buildSrc/subprojects/kotlin-dsl/src/main/kotlin/build/CheckKotlinCompilerEmbeddableDependencies.kt
  buildSrc/subprojects/kotlin-dsl/src/main/kotlin/plugins/kotlin-dsl-plugin-bundle.gradle.kts
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/GradleDistributionsPlugin.kt
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/ShadedJar.kt
  buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/ShadedJarPlugin.kt
  buildSrc/subprojects/performance/src/main/groovy/org/gradle/testing/performance/generator/tasks/NativeProjectWithDepsGeneratorTask.groovy
  buildSrc/subprojects/plugins/src/main/kotlin/gradlebuild/publish-public-libraries.gradle.kts
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/gradlebuild/unittestandcompile/UnitTestAndCompilePlugin.kt
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  subprojects/docs/docs.gradle
  subprojects/docs/src/snippets/buildCache/cacheable-bundle-task/groovy/build.gradle
  subprojects/docs/src/snippets/buildCache/cacheable-bundle-task/kotlin/build.gradle.kts
  subprojects/internal-android-performance-testing/internal-android-performance-testing.gradle.kts
Labels: @dev-productivity, from:member, in:gradle-build

#13517 Style the configuration cache problems report
  subprojects/instant-execution-report/README.md
  subprojects/instant-execution-report/src/main/kotlin/InstantExecutionReportPage.kt
  subprojects/instant-execution-report/src/main/kotlin/Main.kt
  subprojects/instant-execution-report/src/main/kotlin/elmish/View.kt
  subprojects/instant-execution-report/src/main/resources/configuration-cache-report-data.js
  subprojects/instant-execution-report/src/main/resources/configuration-cache-report-logo.png
  subprojects/instant-execution-report/src/main/resources/configuration-cache-report.css
  subprojects/instant-execution-report/src/main/resources/configuration-cache-report.html
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/InstantExecutionReport.kt
Labels: from:member, in:configuration-cache

#13525 Update tested AGP versions
  gradle/dependency-management/agp-versions.properties
Labels: a:chore, from:member

#13533 Capture `Jar` manifest generator in the configuration cache
  subprojects/core/src/main/java/org/gradle/api/internal/AbstractTask.java
  subprojects/core/src/main/java/org/gradle/api/internal/lambdas/SerializableLambdas.java
  subprojects/ear/src/main/java/org/gradle/plugins/ear/Ear.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/GeneratedSingletonFileTree.java
  subprojects/instant-execution/instant-execution.gradle.kts
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionJavaIntegrationTest.groovy
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/Codecs.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/FileTreeCodec.kt
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/tasks/Jar.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/WarPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/tasks/bundling/War.java
Labels: @configuration-cache, a:feature, from:member, in:configuration-cache, in:core

#13545 Let the configuration cache report be a self contained file
  .teamcity/subprojects.json
  buildSrc/subprojects/uber-plugins/src/main/kotlin/gradlebuild/internal/kotlin-js.gradle.kts
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
  subprojects/instant-execution-report/README.md
  subprojects/instant-execution-report/instant-execution-report.gradle.kts
  subprojects/instant-execution-report/src/main/kotlin/InstantExecutionReportPage.kt
  subprojects/instant-execution-report/src/main/kotlin/Main.kt
  subprojects/instant-execution-report/src/main/kotlin/elmish/View.kt
  subprojects/instant-execution-report/src/main/resources/configuration-cache-report.css
  subprojects/instant-execution-report/src/test/groovy/StagedDevelopmentReportTest.groovy
  subprojects/instant-execution-report/src/test/resources/configuration-cache-report-data.js
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/InstantExecutionReport.kt
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/instantexecution/InstantExecutionProblemsFixture.groovy
Labels: @configuration-cache, from:member

#13549 Gracefully handle when file-events library can't be loaded
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DarwinFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/LinuxFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WindowsFileWatcherRegistryFactory.java
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/inputs/undeclared/UndeclaredBuildInputsTestKitInjectedJavaPluginIntegrationTest.groovy
Labels: @execution, from:member

#13540 [docs] Fix Project Properties misprint
  subprojects/docs/src/docs/userguide/reference/command_line_interface.adoc
Labels: from:contributor

#13355 Fix docs: custom plugin user guide
  subprojects/docs/src/docs/userguide/extending-gradle/custom_plugins.adoc
Labels: @core, from:contributor

#13553 Review tests for compatibility with the configuration cache
  subprojects/core/src/integTest/groovy/org/gradle/JansiEndUserIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/SettingsPluginIntegrationSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/JavaExecJavaVersionIntegrationSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/console/AbstractExecOutputIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/InitScriptIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/FileSystemWatchingIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/javadoc/JavadocWorkAvoidanceIntegrationTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/AbstractMavenPublishJavaIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenGradleModuleMetadataPublishIntegrationTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishBasicIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishCustomComponentIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishJavaIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishJavaPlatformIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishLoggingIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishPomPackagingJavaIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishSnapshotIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishWarProjectIntegTest.groovy
  subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/use/NonDeclarativePluginUseIntegrationSpec.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/bundling/WarTaskIntegrationTest.groovy
  subprojects/tooling-api/src/integTest/groovy/org/gradle/integtests/tooling/SamplesToolingApiIntegrationTest.groovy
Labels: @configuration-cache, a:chore, from:member, in:configuration-cache

#13559 Polish file-system watching not supported messages
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/NonWatchingVirtualFileSystem.java
Labels: @execution, from:member

#13560 Consistently use file system
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/lifecycle/LifecyclePlugin.kt
  subprojects/core/src/integTest/groovy/org/gradle/api/AbstractDomainObjectContainerIntegrationTest.groovy
  subprojects/docs/src/docs/userguide/reference/command_line_interface.adoc
  subprojects/docs/src/docs/userguide/running-builds/build_environment.adoc
  subprojects/docs/src/docs/userguide/running-builds/gradle_daemon.adoc
  subprojects/docs/src/snippets/native-binaries/google-test/groovy/libs/googleTest/1.7.0/include/gtest/internal/gtest-filepath.h
  subprojects/file-watching/file-watching.gradle.kts
  subprojects/internal-integ-testing/src/integTest/groovy/org/gradle/integtests/fixtures/executer/InProcessGradleExecuterIntegrationTest.groovy
  subprojects/performance/src/templates/native-dependents-resources/googleTest/libs/googleTest/1.7.0/include/gtest/internal/gtest-filepath.h
Labels: @execution, from:member

#13409 Fix Java version parsing for early access versions
  subprojects/files/src/main/java/org/gradle/api/internal/file/archive/impl/FileZipInput.java
Labels: @core, from:member, in:core

#13562 Review tests for compatibility with the configuration cache
  subprojects/core/src/integTest/groovy/org/gradle/api/PluginApplicationErrorIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/internal/classpath/BuildScriptClasspathIntegrationSpec.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ArtifactSelectionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ExternalModuleVariantsIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/ArtifactCollectionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationSignatureWriteIntegTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationWritingIntegTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaAnnotationProcessingCompileAvoidanceIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/javadoc/JavadocWorkAvoidanceIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/tasks/javadoc/Javadoc.java
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishArtifactCustomizationIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishMultiProjectIntegTest.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/impldeps/GradleImplDepsPublishingIntegrationTest.groovy
  subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/use/PostPluginResolutionFailuresIntegrationSpec.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/integtests/ScalaAnnotationProcessingIntegrationTest.groovy
  subprojects/tooling-api/src/integTest/groovy/org/gradle/integtests/tooling/ToolingApiIntegrationTest.groovy
Labels: @configuration-cache, a:chore, from:member, in:configuration-cache

#13557 Init git repo in integration tests
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/IsolatedAntBuilderMemoryLeakIntegrationTest.groovy
  subprojects/internal-integ-testing/internal-integ-testing.gradle.kts
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractIntegrationSpec.groovy
Labels: @dev-productivity, from:member

#13564 Some more configuration cache documentation refinements
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
  subprojects/docs/src/snippets/configurationCache/problemsGroovy/tests/load.out
  subprojects/docs/src/snippets/configurationCache/problemsGroovy/tests/store.out
  subprojects/docs/src/snippets/configurationCache/problemsKotlin/tests/load.out
  subprojects/docs/src/snippets/configurationCache/problemsKotlin/tests/store.out
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/InstantExecutionState.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/SystemPropertyAccessListener.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/initialization/InstantExecutionProblemsListener.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/Logging.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/TaskReferenceCodec.kt
Labels: @configuration-cache, from:member

#13144 Add retries for SocketException
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/transport/NetworkingIssueVerifier.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/ErrorHandlingModuleComponentRepositoryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/transport/NetworkOperationBackOffAndRetryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/transport/NetworkingIssueVerifierTest.groovy
Labels: @core, from:contributor

#13107 Add credentials providers for Password and AWS credentials
  subprojects/core-api/src/main/java/org/gradle/api/internal/credentials/CredentialsProviderFactory.java
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/credentials/CredentialsProviderIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/credentials/GradlePropertiesCredentialsProviderFactory.java
  subprojects/core/src/main/java/org/gradle/api/internal/credentials/package-info.java
  subprojects/core/src/main/java/org/gradle/internal/artifacts/repositories/AuthenticationSupportedInternal.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/BuildScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/ProjectScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/credentials/GradlePropertiesCredentialsProviderFactoryTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultDependencyManagementServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/AbstractAuthenticationSupportedRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/AuthenticationSupporter.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultBaseRepositoryFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultIvyArtifactRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultMavenArtifactRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultMavenLocalArtifactRepository.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/AbstractAuthenticationSupportedRepositoryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/DefaultBaseRepositoryFactoryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/DefaultIvyArtifactRepositoryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/DefaultMavenArtifactRepositoryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/DefaultMavenLocalRepositoryTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyPublishHttpIntegTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/IvyHttpPublishIntegrationTest.groovy
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/tasks/PublishToIvyRepository.java
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishHttpIntegTest.groovy
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/tasks/PublishToMavenRepository.java
  subprojects/resources-s3/src/integTest/groovy/org/gradle/integtests/resource/s3/maven/MavenPublishS3IntegrationTest.groovy
  subprojects/resources-s3/src/main/java/org/gradle/internal/resource/transport/aws/s3/S3ConnectorFactory.java
Labels: @core, from:member, in:core

#13570 Review tests for compatibility with the configuration cache
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/ClasspathDependenciesAttributesIntegrationTest.groovy
  subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/use/PluginUseClassLoadingIntegrationSpec.groovy
  subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/use/RuleSourcePluginUseIntegrationSpec.groovy
  subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/use/VersionInSettingsPluginUseIntegrationTest.groovy
Labels: @configuration-cache, a:chore, from:member, in:configuration-cache

#13565 Improve configuration cache support for Java serialization
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/SerializableWriteObjectCodec.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/SerializableWriteReplaceCodec.kt
  subprojects/instant-execution/src/test/kotlin/org/gradle/instantexecution/serialization/codecs/SerializableBeanCodecTest.kt
Labels: @configuration-cache, a:feature, from:member, in:configuration-cache

#13264 Update project-reports plugin to lazily register tasks
  subprojects/diagnostics/src/main/java/org/gradle/api/plugins/ProjectReportsPlugin.java
Labels: @core, from:contributor

#13579 Improve documentation and code for FileTimeStampInspectors
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/BuildSessionScopeFileTimeStampInspector.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/FileTimeStampInspector.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/GradleUserHomeScopeFileTimeStampInspector.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/BuildSessionScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GradleUserHomeScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java
Labels: @execution, from:member

#13587 Mark credentials as Optional in ivy and maven repositories
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/tasks/PublishToIvyRepository.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/tasks/PublishToMavenRepository.java
Labels: @core, from:member, in:core

#13580 Fix inconsistent resolution ordering
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ConcurrentDerivationStrategyIntegTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/DefaultComponentMetadataProcessor.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/WrappingComponentMetadataContext.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/LenientPlatformResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractLazyModuleComponentResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractModuleComponentResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractMutableModuleComponentResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractRealisedModuleComponentResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ModuleComponentResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/VariantMetadataRules.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ivy/DefaultIvyModuleResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ivy/RealisedIvyModuleResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/maven/DefaultMavenModuleResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/maven/RealisedMavenModuleResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/caching/ComponentMetadataRuleExecutor.java
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/external/model/DefaultMavenModuleResolveMetadataTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/external/model/DependencyConstraintMetadataRulesTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/external/model/VariantFilesMetadataRulesTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/resolve/caching/ComponentMetadataRuleExecutorTest.groovy
Labels: @jvm, a:bug, from:member, in:dependency-management

#13592 Revert "Use Stat in FileTimeStampInspector"
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/BuildSessionScopeFileTimeStampInspector.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/FileTimeStampInspector.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/GradleUserHomeScopeFileTimeStampInspector.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/BuildSessionScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GradleUserHomeScopeServices.java
Labels: @execution, from:member

#13591 Don't cache `readResolve` methods when writing to the configuration cache
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/MethodCache.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/SerializableWriteObjectCodec.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/SerializableWriteReplaceCodec.kt
Labels: @configuration-cache, a:performance-issue, from:member, in:configuration-cache

#13595 Fix TestNG support for the configuration cache
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/JavaApplicationInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/JavaLibraryInitIntegrationTest.groovy
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/jvm/AbstractConsoleJvmTestWorkerFunctionalTest.groovy
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/jvm/ConsoleTestNGUnsupportedTestWorkerFunctionalTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/JavaPluginTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/tasks/testing/TestTest.groovy
  subprojects/testing-base/src/integTest/groovy/org/gradle/testing/TestExecutionBuildOperationsIntegrationTest.groovy
  subprojects/testing-base/src/testFixtures/groovy/org/gradle/testing/AbstractTestFrameworkIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/IncrementalTestIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestOutputListenerIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestingIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/fixture/AbstractJvmFailFastIntegrationSpec.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/fixture/AbstractTestFilteringIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/SampleTestNGIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGClassIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGConsoleLoggingIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGFailFastIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGFailurePolicyIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGFilteringIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGGroupByInstancesIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGGroupByInstancesNotSupportedIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGJdkNavigationIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGLoggingOutputCaptureIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGParallelSuiteIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGPreserveOrderIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGPreserveOrderNotSupportedIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGProducesOldReportsIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGStaticLoggingIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGSuiteInitialisationIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGSuiteIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGTestFrameworkIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGUpToDateCheckIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGXmlResultAndHtmlReportIntegrationTest.groovy
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/TestClassLoaderFactory.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGTestFramework.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/testng/TestNGOptions.java
  subprojects/testing-jvm/src/test/groovy/org/gradle/api/internal/tasks/testing/testng/TestNGTestFrameworkTest.groovy
Labels: @configuration-cache, from:member, in:testing

#13599 Update tested AGP versions
  gradle/dependency-management/agp-versions.properties
Labels: a:chore, from:member

#13600 Remove patches
  .teamcity/Gradle_Check/configurations/BaseGradleBuildType.kt
  .teamcity/Gradle_Check/patches/buildTypes/Gradle_Check_Instant_20_bucket1.kts
  .teamcity/Gradle_Check/patches/buildTypes/Gradle_Check_Instant_20_bucket31.kts
  .teamcity/Gradle_Check/patches/buildTypes/Gradle_Check_Instant_20_bucket45.kts
  .teamcity/Gradle_Check/patches/projects/Gradle_Check_Quick_2.kts
  .teamcity/Gradle_Check/patches/projects/Gradle_Check_deferred_tests.kts
  .teamcity/Gradle_Promotion/patches/vcsRoots/0974a0e7-3f2f-4c3f-a185-aded6ac045ff.kts
  .teamcity/Gradle_Promotion/patches/vcsRoots/e4bc6ac6-ab3f-4459-b4c4-7d6ba6e2cbf6.kts
  .teamcity/Gradle_Promotion/vcsRoots/Gradle_Promotion_GradlePromotionBranches.kt
  .teamcity/Gradle_Promotion/vcsRoots/Gradle_Promotion__master_.kt
Labels: @dev-productivity, a:chore, from:member

#13603 Remove @ToBeFixed on SamplesJavaTestingIntegrationTest for TestNG
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/java/SamplesJavaTestingIntegrationTest.groovy
Labels: a:chore, from:member

#13589 Let configuration cache fail eagerly on `java.io.Externalizable` types
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/Codecs.kt
Labels: @configuration-cache, a:feature, from:member, in:configuration-cache

#13605 Fix PlayTestPlugin now that Test.classpath has no convention mapping
  subprojects/platform-play/src/integTest/groovy/org/gradle/play/integtest/PlayTestApplicationIntegrationTest.groovy
  subprojects/platform-play/src/main/java/org/gradle/play/plugins/PlayTestPlugin.java
  subprojects/platform-play/src/test/groovy/org/gradle/play/plugins/PlayTestPluginTest.groovy
Labels: from:member, in:play

#13612 Review :buildInit tests for the configuration cache
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/BuildInitPluginIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/MavenConversionIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/internal/WrapperPluginAutoApplyActionIntegTest.groovy
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
Labels: @configuration-cache, from:member, in:build-init-plugin

#13618 Use BuildActionRunner for file system watching bookkeeping
  subprojects/core/src/integTest/groovy/org/gradle/internal/operations/logging/LoggingBuildOperationProgressIntegTest.groovy
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java
  subprojects/core/src/test/groovy/org/gradle/internal/service/scopes/VirtualFileSystemServicesTest.groovy
  subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/legacy/BuildScanEndOfBuildNotifierIntegrationTest.groovy
  subprojects/launcher/launcher.gradle.kts
  subprojects/launcher/src/main/java/org/gradle/launcher/exec/BuildOutcomeReportingBuildActionRunner.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/ContinuousBuildActionExecuter.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunner.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/LauncherServices.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/SessionFailureReportingActionExecuter.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/SessionScopeBuildActionExecuter.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/SetupLoggingActionExecuter.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/SubscribableBuildActionExecuter.java
  subprojects/launcher/src/test/groovy/org/gradle/tooling/internal/provider/ContinuousBuildActionExecuterTest.groovy
  subprojects/launcher/src/test/groovy/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunnerTest.groovy
  subprojects/launcher/src/test/groovy/org/gradle/tooling/internal/provider/SubscribableBuildActionExecuterSpec.groovy
Labels: @execution, from:member

#13632 Disable file system watching when native integration is disabled
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java
  subprojects/native/src/main/java/org/gradle/internal/nativeintegration/NativeCapabilities.java
  subprojects/native/src/main/java/org/gradle/internal/nativeintegration/services/NativeServices.java
Labels: @execution, from:member

#13631 Upgradle to latest nightly
  gradle/wrapper/gradle-wrapper.properties
Labels: @jvm, from:member
