Repository gradle/gradle, pull requests merged in 2020-09, with the labels that each got.

#14355 Fold CatchExceptionStep into ExecuteStep
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/ExecutionGradleServices.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuterTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultDependencyManagementServices.java
  subprojects/execution/src/integTest/groovy/org/gradle/internal/execution/IncrementalExecutionIntegrationTest.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CancelExecutionStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CatchExceptionStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ExecuteStep.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CatchExceptionStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/ExecuteStepTest.groovy
  subprojects/internal-integ-testing/src/integTest/groovy/org/gradle/integtests/fixtures/executer/IgnoreKotlinCompilerWarningIntegrationTest.groovy
Labels: @execution

#14337 Remove redundant cross-configuration from kotlinDsl multiproject snippet
  subprojects/docs/docs.gradle
  subprojects/docs/src/snippets/kotlinDsl/multiProjectBuild/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/multiProjectBuild/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/multiProjectBuild/tests/build.sample.conf
  subprojects/docs/src/snippets/kotlinDsl/multiProjectBuild/tests/multi-project-build.sample.conf
Labels: @idiomatic, from:member, in:docs

#14357 Test testing snippets in both Groovy and Kotlin DSLs
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/java/SamplesJavaTestingIntegrationTest.groovy
Labels: @core, @idiomatic, a:chore, from:member, in:core

#14360 Compile-only API dependencies can be declared for JVM libraries
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/img/java-library-ignore-deprecated-main.dot
  subprojects/docs/src/docs/userguide/img/java-library-ignore-deprecated-main.png
  subprojects/docs/src/docs/userguide/img/java-library-ignore-deprecated-test.png
  subprojects/docs/src/docs/userguide/jvm/building_java_projects.adoc
  subprojects/docs/src/docs/userguide/jvm/java_library_plugin.adoc
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/maven/MavenJavaModule.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyPublishJavaIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/AbstractMavenPublishJavaIntegTest.groovy
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/internal/precompiled/PrecompiledGroovyPluginsPlugin.java
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/plugins/JavaGradlePluginPlugin.java
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaLibraryFeatureCompilationIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaLibraryOutgoingVariantsIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/dependencies/JavaConfigurationSetupIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/internal/tasks/DefaultSourceSet.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/JvmPluginsHelper.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmVariantBuilder.java
  subprojects/plugins/src/main/java/org/gradle/api/tasks/SourceSet.java
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/JavaLibraryPluginTest.groovy
Labels: @idiomatic, @jvm, a:feature, from:member, in:jvm-ecosystem

#14321 Enhance template engine in BultInit plugin to be usable for generating samples
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/BasicProjectGenerator.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/BuildConverter.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/BuildScriptBuilder.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/BuildScriptBuilderFactory.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/CompositeProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/CppProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/GitAttributesGenerator.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/GitIgnoreGenerator.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/InitSettings.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/LanguageSpecificAdaptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/ProjectLayoutSetupRegistry.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/ResourceDirsGenerator.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/SimpleGlobalFilesBuildSettingsDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/SimpleTemplateOperation.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/SwiftProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/TemplateFactory.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/TemplateOperationFactory.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/TemplateValue.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/maven/Maven2Gradle.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/maven/PomProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/services/BuildInitServices.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/services/ProjectLayoutSetupRegistryFactory.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/tasks/InitBuild.java
  subprojects/build-init/src/test/groovy/org/gradle/buildinit/plugins/internal/AbstractBuildScriptBuilderTest.groovy
  subprojects/build-init/src/test/groovy/org/gradle/buildinit/plugins/internal/BuildScriptBuilderGroovyTest.groovy
  subprojects/build-init/src/test/groovy/org/gradle/buildinit/plugins/internal/BuildScriptBuilderKotlinTest.groovy
  subprojects/build-init/src/test/groovy/org/gradle/buildinit/plugins/internal/GitIgnoreGeneratorTest.groovy
  subprojects/build-init/src/test/groovy/org/gradle/buildinit/plugins/internal/ProjectLayoutSetupRegistrySpec.groovy
  subprojects/build-init/src/test/groovy/org/gradle/buildinit/plugins/internal/TemplateFactoryTest.groovy
  subprojects/build-init/src/test/groovy/org/gradle/buildinit/plugins/internal/TemplateOperationFactorySpec.groovy
  subprojects/build-init/src/test/groovy/org/gradle/buildinit/plugins/internal/maven/MavenProjectsCreatorSpec.groovy
Labels: @idiomatic, from:member, in:build-init-plugin, in:docs

#14359 Remove cross-configuration from tutorial/projectReports snippet
  subprojects/docs/src/snippets/tutorial/projectReports/groovy/api/build.gradle
  subprojects/docs/src/snippets/tutorial/projectReports/groovy/build.gradle
  subprojects/docs/src/snippets/tutorial/projectReports/groovy/settings.gradle
  subprojects/docs/src/snippets/tutorial/projectReports/groovy/webapp/build.gradle
  subprojects/docs/src/snippets/tutorial/projectReports/tests/propertyListReport.sample.conf
  subprojects/docs/src/snippets/tutorial/projectReports/tests/taskHelp.sample.conf
Labels: @idiomatic, from:member, in:docs

#14351 Move `JavaExec.mainClass` convention test to the `plugins` module
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/AbstractConfigurationCacheIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheJavaIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractIntegrationSpec.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecMainClassIntegrationTest.groovy
Labels: @configuration-cache, a:chore, from:member, in:configuration-cache

#14353 Fix verb form in configuration cache docs
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
Labels: @configuration-cache, a:bug, from:member, in:configuration-cache

#14368 Remove cross-configuration using project() {} from code snippets
  subprojects/docs/src/docs/userguide/authoring-builds/more_about_tasks.adoc
  subprojects/docs/src/docs/userguide/native/building_cpp_projects.adoc
  subprojects/docs/src/docs/userguide/native/building_swift_projects.adoc
  subprojects/docs/src/docs/userguide/native/native_software.adoc
  subprojects/docs/src/snippets/cpp/basic/groovy/build.gradle
  subprojects/docs/src/snippets/cpp/basic/groovy/common/build.gradle
  subprojects/docs/src/snippets/cpp/basic/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/cpp/basic/kotlin/common/build.gradle.kts
  subprojects/docs/src/snippets/native-binaries/multi-project/groovy/build.gradle
  subprojects/docs/src/snippets/native-binaries/multi-project/groovy/exe/build.gradle
  subprojects/docs/src/snippets/native-binaries/multi-project/groovy/lib/build.gradle
  subprojects/docs/src/snippets/swift/basic/groovy/build.gradle
  subprojects/docs/src/snippets/swift/basic/groovy/common/build.gradle
  subprojects/docs/src/snippets/swift/basic/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/swift/basic/kotlin/common/build.gradle.kts
  subprojects/docs/src/snippets/tasks/accessUsingPath/groovy/build.gradle
  subprojects/docs/src/snippets/tasks/accessUsingPath/groovy/project-a/build.gradle
  subprojects/docs/src/snippets/tasks/accessUsingPath/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/tasks/accessUsingPath/kotlin/project-a/build.gradle.kts
Labels: @idiomatic, from:member, in:docs

#14369 Remove unneeded uses of allprojects from documentation snippets
  subprojects/docs/src/snippets/dependencyManagement/artifactTransforms-incremental/groovy/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/artifactTransforms-incremental/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/artifactTransforms-relocate/groovy/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/artifactTransforms-relocate/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/artifactTransforms-unzip/groovy/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/artifactTransforms-unzip/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/java-feature-variant/incompatible-variants/groovy/build.gradle
  subprojects/docs/src/snippets/java-feature-variant/incompatible-variants/groovy/producer/build.gradle
  subprojects/docs/src/snippets/java-feature-variant/incompatible-variants/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/java-feature-variant/incompatible-variants/kotlin/producer/build.gradle.kts
  subprojects/docs/src/snippets/java-feature-variant/requiring-features/groovy/build.gradle
  subprojects/docs/src/snippets/java-feature-variant/requiring-features/groovy/producer/build.gradle
  subprojects/docs/src/snippets/java-feature-variant/requiring-features/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/java-feature-variant/requiring-features/kotlin/producer/build.gradle.kts
Labels: @idiomatic, from:member, in:docs

#14373 Add execution team as code owners for related projects
  .github/CODEOWNERS
Labels: @execution, from:member

#14370 Only run InProcessGradleExecuterIntegrationTest for embedded executor
  subprojects/internal-integ-testing/src/integTest/groovy/org/gradle/integtests/fixtures/executer/InProcessGradleExecuterIntegrationTest.groovy
Labels: @execution, from:member

#14364 Remove ToBeFixedForFileSystemWatching annotation
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractIntegrationTest.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/ToBeFixedForFileSystemWatching.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/ToBeFixedForFileSystemWatchingExtension.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/ToBeFixedForFileSystemWatchingRule.groovy
Labels: @execution, from:member

#14372 Mention file system watching becoming production ready
  subprojects/docs/src/docs/release/notes.md
Labels: @execution, from:member

#14371 Replace subprojects {} construct with convention plugins in dependency alignment snippet
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-dependencyAlignmentWithPlatform/groovy/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-dependencyAlignmentWithPlatform/groovy/buildSrc/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-dependencyAlignmentWithPlatform/groovy/buildSrc/src/main/groovy/myproject.java-library-conventions.gradle
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-dependencyAlignmentWithPlatform/groovy/buildSrc/src/main/groovy/myproject.publishing-conventions.gradle
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-dependencyAlignmentWithPlatform/groovy/core/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-dependencyAlignmentWithPlatform/groovy/lib/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-dependencyAlignmentWithPlatform/groovy/platform/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-dependencyAlignmentWithPlatform/groovy/utils/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-dependencyAlignmentWithPlatform/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-dependencyAlignmentWithPlatform/kotlin/buildSrc/build.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-dependencyAlignmentWithPlatform/kotlin/buildSrc/src/main/kotlin/myproject.java-library-conventions.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-dependencyAlignmentWithPlatform/kotlin/buildSrc/src/main/kotlin/myproject.publishing-conventions.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-dependencyAlignmentWithPlatform/kotlin/core/build.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-dependencyAlignmentWithPlatform/kotlin/lib/build.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-dependencyAlignmentWithPlatform/kotlin/platform/build.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-dependencyAlignmentWithPlatform/kotlin/utils/build.gradle.kts
Labels: @idiomatic, from:member, in:docs

#14366 Improve verbose VFS logging
  subprojects/docs/src/docs/userguide/running-builds/build_environment.adoc
  subprojects/docs/src/docs/userguide/running-builds/gradle_daemon.adoc
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesDuringTheBuildFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/EnableFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/FileSystemWatchingFixture.groovy
  subprojects/soak/src/integTest/groovy/org/gradle/vfs/FileSystemWatchingSoakTest.groovy
Labels: @execution, from:member

#14376 Change a Kotlin source file in incremental Santa Tracker Kotlin performance tests
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/AndroidTestProject.groovy
Labels: @execution, from:member

#14365 Do not show corss-configuration and legacy plugin application syntax in Groovy primer page
  subprojects/docs/src/docs/userguide/api/groovy_build_script_primer.adoc
Labels: @idiomatic, from:member, in:docs

#14318 Remove unreferenced maven pom generation snippet
  subprojects/docs/src/snippets/maven-publish/pomGeneration/groovy/build.gradle
  subprojects/docs/src/snippets/maven-publish/pomGeneration/groovy/settings.gradle
  subprojects/docs/src/snippets/maven-publish/pomGeneration/tests/publishingMavenGeneratePom.out
  subprojects/docs/src/snippets/maven-publish/pomGeneration/tests/publishingMavenGeneratePom.sample.conf
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/SamplesMavenPublishIntegrationTest.groovy
Labels: @core, @idiomatic, a:chore, from:member, in:core

#14356 Use subst to avoid long path issue for windows performance test
  .teamcity/Gradle_Check/configurations/IndividualPerformanceScenarioWorkers.kt
  .teamcity/Gradle_Util_Performance/buildTypes/AdHocPerformanceScenario.kt
  .teamcity/common/Os.kt
  .teamcity/common/performance-test-extensions.kt
Labels: @dev-productivity, from:member

#14383 Make custom keystore compatible with real-world HTTPS server
  .gitattributes
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/keystore/TestKeyStore.groovy
  subprojects/internal-integ-testing/src/main/resources/test-key-store/trustStore-adoptopenjdk-8.bin
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingJavaPerformanceTest.groovy
Labels: @dev-productivity, from:member

#14379 Add test for continuous build with file system watching
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ContinuousBuildFileWatchingIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/FileSystemWatchingFixture.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/FileSystemWatchingHelper.java
Labels: @execution, from:member

#14392 Log file system changes only when there is an effect on the VFS
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/EventLoggingFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/FileSystemWatchingSettingsFinalizedBuildOperationIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
Labels: @execution, from:member

#14390 Introduce file system watching debug flag
  subprojects/core/src/main/java/org/gradle/api/internal/StartParameterInternal.java
  subprojects/core/src/main/java/org/gradle/initialization/StartParameterBuildOptions.java
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/EnableFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DefaultFileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/BuildLifecycleAwareVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingNotSupportedVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingNotSupportedVirtualFileSystemTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystemTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/FileSystemWatchingFixture.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/FileSystemWatchingHelper.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/daemon/AbstractDaemonFixture.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/daemon/DaemonFixture.java
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/action/BuildActionSerializer.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunner.java
  subprojects/launcher/src/test/groovy/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunnerTest.groovy
  subprojects/soak/src/integTest/groovy/org/gradle/vfs/FileSystemWatchingSoakTest.groovy
Labels: @execution, from:member

#14400 Remove limitation on SUBST drives
  subprojects/docs/src/docs/userguide/running-builds/gradle_daemon.adoc
Labels: @execution, from:member

#14399 Remove daemon log size limitation
  subprojects/core/src/integTest/groovy/org/gradle/internal/operations/logging/LoggingBuildOperationProgressIntegTest.groovy
  subprojects/docs/src/docs/userguide/running-builds/gradle_daemon.adoc
Labels: @execution, from:member

#14394 Lint multiproject docs links
  subprojects/docs/src/docs/userguide/authoring-builds/multi_project_builds.adoc
  subprojects/docs/src/docs/userguide/migration/migrating_from_maven.adoc
Labels: @idiomatic, from:member, in:docs

#14397 Allow running performance tests without DB connection
  .teamcity/Gradle_Check/configurations/TestPerformanceTest.kt
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/common/performance-test-extensions.kt
  .teamcityTest/Gradle_Check_Tests/PerformanceTestBuildTypeTest.kt
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild/performance/tasks/PerformanceTest.groovy
  buildSrc/subprojects/performance-testing/src/main/kotlin/gradlebuild/performance/PerformanceTestPlugin.kt
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/AbstractAndroidStudioMockupCrossVersionPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/AbstractCrossBuildPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/AbstractCrossVersionGradleInternalPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/AbstractCrossVersionGradleProfilerPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/AbstractGradleVsMavenPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/AbstractToolingApiCrossVersionPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/BaseCrossBuildResultsStore.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/CrossVersionResultsStore.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/EmptyPerformanceTestHistory.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/NoResultsStore.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/PerformanceDatabase.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/ResultsStoreHelper.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/WritableResultsStore.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/AbstractReportGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/DefaultReportGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/PerformanceFlakinessDataProvider.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/TestPageGenerator.java
  subprojects/internal-performance-testing/src/test/groovy/org/gradle/performance/fixture/GradleInternalCrossVersionPerformanceTestRunnerTest.groovy
Labels: @dev-productivity, @execution

#14362 Persist distributed performance test result
  buildSrc/subprojects/performance-testing/src/main/kotlin/gradlebuild/performance/PerformanceTestPlugin.kt
Labels: @dev-productivity, from:member

#14406 Improve test for ad-hoc performance tests
  .teamcity/Gradle_Check/configurations/TestPerformanceTest.kt
Labels: @execution, from:member

#14142 Add support for ignored dependencies in lock state
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/DependencyLockingHandler.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/locking/AbstractLockingIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/locking/AbstractValidatingLockingIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/DependencyLockingProvider.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/DependencyLockingState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/LockEntryFilter.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/locking/DefaultDependencyLockingHandler.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/locking/DefaultDependencyLockingProvider.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/locking/DefaultDependencyLockingState.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/locking/DependencyLockingArtifactVisitor.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/locking/LockEntryFilterFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/locking/NoOpDependencyLockingProvider.java
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/local/model/RootLocalComponentMetadataTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/locking/DefaultDependencyLockingProviderTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/locking/DependencyLockingArtifactVisitorTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/locking/LockEntryFilterFactoryTest.groovy
Labels: @jvm, from:member, in:dependency-management

#14407 Fail build on empty source directory cache miss
  buildSrc/subprojects/jvm/src/main/kotlin/gradlebuild/unittest-and-compile.gradle.kts
Labels: from:member

#14402 Improve assertions for EventLoggingFileSystemWatchingIntegrationTest
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/EnableFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/EventLoggingFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/LoggingFileSystemWatchingIntegrationTest.groovy
Labels: @execution, from:member

#14349 Do not reach out to subprojects directly for test results aggregation in snippet
  subprojects/docs/src/docs/userguide/jvm/java_testing.adoc
  subprojects/docs/src/snippets/testing/testReport/groovy/build.gradle
  subprojects/docs/src/snippets/testing/testReport/groovy/buildSrc/build.gradle
  subprojects/docs/src/snippets/testing/testReport/groovy/buildSrc/src/main/groovy/myproject.java-conventions.gradle
  subprojects/docs/src/snippets/testing/testReport/groovy/core/build.gradle
  subprojects/docs/src/snippets/testing/testReport/groovy/util/build.gradle
  subprojects/docs/src/snippets/testing/testReport/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/testing/testReport/kotlin/buildSrc/build.gradle.kts
  subprojects/docs/src/snippets/testing/testReport/kotlin/buildSrc/src/main/kotlin/myproject.java-conventions.gradle.kts
  subprojects/docs/src/snippets/testing/testReport/kotlin/core/build.gradle.kts
  subprojects/docs/src/snippets/testing/testReport/kotlin/util/build.gradle.kts
  subprojects/docs/src/snippets/testing/testReport/readme.xml
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/java/SamplesJavaTestingIntegrationTest.groovy
Labels: @idiomatic, from:member, in:docs

#14381 Do not reach out to subprojects directly for Swift test results aggregation in snippet
  subprojects/docs/src/docs/userguide/native/swift_testing.adoc
  subprojects/docs/src/snippets/swift/testReport/groovy/build.gradle
  subprojects/docs/src/snippets/swift/testReport/groovy/buildSrc/build.gradle
  subprojects/docs/src/snippets/swift/testReport/groovy/buildSrc/src/main/groovy/myproject.xctest-conventions.gradle
  subprojects/docs/src/snippets/swift/testReport/groovy/core/build.gradle
  subprojects/docs/src/snippets/swift/testReport/groovy/util/build.gradle
  subprojects/docs/src/snippets/swift/testReport/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/swift/testReport/kotlin/buildSrc/build.gradle.kts
  subprojects/docs/src/snippets/swift/testReport/kotlin/buildSrc/src/main/kotlin/myproject.xctest-conventions.gradle.kts
  subprojects/docs/src/snippets/swift/testReport/kotlin/core/build.gradle.kts
  subprojects/docs/src/snippets/swift/testReport/kotlin/util/build.gradle.kts
  subprojects/docs/src/snippets/swift/testReport/readme.xml
Labels: @idiomatic, from:member, in:docs

#14289 Convert performance tests to Gradle profiler
  buildSrc/subprojects/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild.performance-templates.gradle
  gradle/verification-metadata.xml
  subprojects/build-scan-performance/src/performanceTest/groovy/org/gradle/performance/BuildScanPluginPerformanceTest.groovy
  subprojects/build-scan-performance/src/testFixtures/groovy/org/gradle/performance/AbstractBuildScanPluginPerformanceTest.groovy
  subprojects/build-scan-performance/src/testFixtures/groovy/org/gradle/performance/fixture/BuildScanPerformanceTestRunner.groovy
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/internal-performance-testing/build.gradle.kts
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/AbstractCrossBuildPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/AbstractCrossVersionGradleInternalPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/AbstractCrossVersionGradleProfilerPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/AbstractGradleVsMavenPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/AbstractToolingApiCrossVersionPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/AbstractCrossBuildPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/AbstractGradleProfilerBuildExperimentRunner.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/BuildExperimentListener.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/BuildExperimentListenerAdapter.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/BuildExperimentSpec.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/CompositeBuildExperimentListener.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/CrossBuildGradleInternalPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/CrossBuildGradleProfilerPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleBuildExperimentRunner.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleBuildExperimentSpec.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleInternalBuildExperimentRunner.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleInternalCrossVersionPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleVsMavenBuildExperimentRunner.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleVsMavenPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/MavenBuildExperimentRunner.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/MavenBuildExperimentSpec.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/mutator/AbstractFileChangeMutator.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/mutator/AbstractGroovySourceFileMutator.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/mutator/ApplyAbiChangeToGroovySourceFileMutator.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/mutator/ApplyChangeToNativeSourceFileMutator.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/mutator/ApplyNonAbiChangeToGroovySourceFileMutator.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/DefaultReportGenerator.java
  subprojects/internal-performance-testing/src/test/groovy/org/gradle/performance/fixture/GradleInternalCrossVersionPerformanceTestRunnerTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/experiment/maven/JavaTestGradleVsMavenPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/FasterIncrementalAndroidBuildsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/AbstractTaskOutputCachingPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingJavaPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ParallelDownloadsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/inception/BuildSrcApiChangePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/inception/GradleBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaABIChangePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaCleanAssemblePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationCachePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaNonABIChangePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaTestChangePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/RealWorldNativePluginPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftBuildPerformanceTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy
Labels: @dev-productivity, @execution, from:member

#14421 Do not use dedicated gradle home for samples
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/tests/check.sample.conf
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/tests/sanityCheck.conf
  subprojects/docs/src/samples/build-organization/publishing-convention-plugins/tests/publish.sample.conf
  subprojects/docs/src/samples/build-organization/publishing-convention-plugins/tests/sanityCheck.sample.conf
  subprojects/docs/src/samples/credentials-handling/pass-credentials-to-external-tool-via-stdin/tests/commandLineCredentials.sample.conf
  subprojects/docs/src/samples/credentials-handling/pass-credentials-to-external-tool-via-stdin/tests/sanityCheck.sample.conf
  subprojects/docs/src/samples/credentials-handling/publishing-credentials/tests/publishCommandLineCredentials.sample.conf
  subprojects/docs/src/samples/credentials-handling/publishing-credentials/tests/sanityCheck.sample.conf
Labels: @dev-productivity, from:member

#14395 Promote property to configure AdoptOpenJdk server
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/install/internal/AdoptOpenJdkRemoteBinary.java
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/toolchain/install/internal/AdoptOpenJdkRemoteBinaryTest.groovy
Labels: @jvm, from:member

#14423 Improve name matching
  subprojects/core/src/main/java/org/gradle/util/NameMatcher.java
  subprojects/core/src/test/groovy/org/gradle/util/NameMatcherTest.groovy
Labels: @core, @idiomatic, from:member

#14345 Refine Windows performance builds
  .teamcity/Gradle_Check/configurations/BuildDistributions.kt
  .teamcity/Gradle_Check/configurations/BuildJavaVersions.kt
  .teamcity/Gradle_Check/configurations/CompileAll.kt
  .teamcity/Gradle_Check/configurations/FunctionalTest.kt
  .teamcity/Gradle_Check/configurations/Gradleception.kt
  .teamcity/Gradle_Check/configurations/IndividualPerformanceScenarioWorkers.kt
  .teamcity/Gradle_Check/configurations/SanityCheck.kt
  .teamcity/Gradle_Check/configurations/SmokeTests.kt
  .teamcity/Gradle_Check/configurations/StagePasses.kt
  .teamcity/Gradle_Check/configurations/TestPerformanceTest.kt
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/Gradle_Util/buildTypes/WarmupEc2Agent.kt
  .teamcity/Gradle_Util_Performance/buildTypes/AdHocPerformanceScenario.kt
  .teamcity/Gradle_Util_Performance/buildTypes/AdHocPerformanceTestCoordinator.kt
  .teamcity/common/Os.kt
  .teamcity/common/performance-test-extensions.kt
Labels: @dev-productivity, a:chore, from:member

#14426 Move project layout documentation into dedicated multi-project section
  subprojects/docs/src/docs/userguide/authoring-builds/build_lifecycle.adoc
  subprojects/docs/src/docs/userguide/authoring-builds/multi-project/fine_tuning_project_layout.adoc
  subprojects/docs/src/docs/userguide/userguide_single.adoc
  subprojects/docs/src/main/resources/header.html
  subprojects/docs/src/snippets/multiproject/customLayout/groovy/settings.gradle
  subprojects/docs/src/snippets/multiproject/customLayout/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/multiproject/standardLayouts/groovy/settings.gradle
  subprojects/docs/src/snippets/multiproject/standardLayouts/kotlin/settings.gradle.kts
Labels: @idiomatic, from:member, in:docs

#14435 Make scala incremental analysis configurations resolve early
  subprojects/scala/src/integTest/groovy/org/gradle/scala/ScalaConcurrencyIntegrationTest.groovy
  subprojects/scala/src/main/java/org/gradle/api/plugins/scala/ScalaBasePlugin.java
Labels: a:bug, from:member, in:scala-plugin

#14422 Prevent buildSrc build from hanging when included build is substituted as a dependency
  subprojects/core/src/integTest/groovy/org/gradle/initialization/buildsrc/BuildSrcIncludedBuildIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/composite/internal/IncludedBuildControllers.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GradleScopeServices.java
Labels: @idiomatic

#14440 Configure lifecycle tasks for all projects without filtering subprojects
  buildSrc/subprojects/jvm/src/main/kotlin/gradlebuild/unittest-and-compile.gradle.kts
  buildSrc/subprojects/lifecycle/src/main/kotlin/gradlebuild/lifecycle.gradle.kts
  buildSrc/subprojects/uber-plugins/src/main/kotlin/gradlebuild/ci-lifecycle.gradle.kts
  buildSrc/subprojects/uber-plugins/src/main/kotlin/gradlebuild/java-library.gradle.kts
Labels: @idiomatic, from:member, in:gradle-build

#14358 Do not reach out to subprojects directly for test results aggregation in snippet - use new JVM APIs
  subprojects/docs/src/snippets/testing/testReport/groovy/build.gradle
  subprojects/docs/src/snippets/testing/testReport/groovy/buildSrc/src/main/groovy/myproject.java-conventions.gradle
  subprojects/docs/src/snippets/testing/testReport/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/testing/testReport/kotlin/buildSrc/src/main/kotlin/myproject.java-conventions.gradle.kts
Labels: @idiomatic, from:member, in:docs

#14443 Treat empty selected documentation chapter as index.html
  subprojects/docs/src/main/resources/footer.html
Labels: a:bug, from:member, in:docs

#14449 Some configuration cache problem reporting improvements
  subprojects/base-services/src/main/java/org/gradle/internal/file/RelativeFilePathResolver.java
  subprojects/configuration-cache-report/src/main/kotlin/ConfigurationCacheReportPage.kt
  subprojects/configuration-cache-report/src/main/kotlin/Main.kt
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheGroovyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheJacocoIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheProblemReportingIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheScriptTaskDefinitionIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheUnsupportedTypesIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsDynamicGroovyBuildScriptBlockIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsDynamicGroovyBuildScriptIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsDynamicGroovyBuildScriptPluginIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsDynamicGroovyBuildSrcIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsDynamicGroovyScriptPluginIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsDynamicGroovySettingsScriptIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsJavaBuildSrcIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsJavaLambdaBuildSrcIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsKotlinBuildScriptIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsKotlinBuildScriptPluginIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsKotlinBuildScriptPluginsBlockIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsKotlinBuildSrcIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsKotlinScriptPluginIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsKotlinSettingsScriptIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsStaticGroovyBuildSrcIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsTestKitInjectedJavaPluginIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheReport.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ProblemsSummary.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/PropertyProblem.kt
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/DefaultTaskCacheabilityResolver.java
  subprojects/core/src/main/java/org/gradle/configuration/internal/UserCodeApplicationContext.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/BaseDirFileResolverTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/DefaultTaskCacheabilityResolverTest.groovy
  subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/OutgoingVariantsReportTask.java
  subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/internal/text/DefaultTextReportBuilder.java
  subprojects/diagnostics/src/test/groovy/org/gradle/api/reporting/components/internal/SourceSetRendererTest.groovy
  subprojects/diagnostics/src/test/groovy/org/gradle/api/tasks/diagnostics/internal/text/DefaultTextReportBuilderTest.groovy
  subprojects/docs/src/snippets/configurationCache/problemsGroovy/tests/fail.out
  subprojects/docs/src/snippets/configurationCache/problemsGroovy/tests/load.out
  subprojects/docs/src/snippets/configurationCache/problemsGroovy/tests/store.out
  subprojects/docs/src/snippets/configurationCache/problemsKotlin/tests/fail.out
  subprojects/docs/src/snippets/configurationCache/problemsKotlin/tests/load.out
  subprojects/docs/src/snippets/configurationCache/problemsKotlin/tests/store.out
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/AbstractBaseDirFileResolver.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/AbstractFileResolver.java
  subprojects/resources/src/main/java/org/gradle/internal/resource/UriTextResource.java
  subprojects/resources/src/test/groovy/org/gradle/internal/resource/UriTextResourceTest.groovy
Labels: @configuration-cache

#14453 Rename creating_multi_project_builds page to multi_project_builds for backwards compatibility
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/SimpleGlobalFilesBuildSettingsDescriptor.java
  subprojects/docs/src/docs/userguide/authoring-builds/authoring_maintainable_build_scripts.adoc
  subprojects/docs/src/docs/userguide/authoring-builds/build_lifecycle.adoc
  subprojects/docs/src/docs/userguide/authoring-builds/multi-project/multi_project_builds.adoc
  subprojects/docs/src/docs/userguide/authoring-builds/plugins.adoc
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/declaring_dependencies.adoc
  subprojects/docs/src/docs/userguide/migration/migrating_from_ant.adoc
  subprojects/docs/src/docs/userguide/migration/migrating_from_maven.adoc
  subprojects/docs/src/docs/userguide/running-builds/intro_multi_project_builds.adoc
  subprojects/docs/src/docs/userguide/userguide_single.adoc
  subprojects/docs/src/main/resources/header.html
  subprojects/docs/src/samples/generated/groovy-library/README.adoc
  subprojects/docs/src/samples/generated/java-library/README.adoc
  subprojects/docs/src/samples/generated/kotlin-library/README.adoc
  subprojects/docs/src/samples/generated/scala-library/README.adoc
Labels: @idiomatic, from:member

#14457 Remove link to "Guides landing page" from nav bar
  subprojects/docs/src/main/resources/header.html
Labels: @idiomatic, from:member, in:docs

#14444 Fix Tooling API compatibility
  subprojects/tooling-api/src/integTest/groovy/org/gradle/integtests/tooling/ToolingApiJdkCompatibilityTest.groovy
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/loader/DefaultToolingImplementationLoader.java
Labels: @idiomatic, a:regression, from:member, in:tooling-api

#14448 Fail when using both toolchain and compatibility
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileToolchainIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaBasePlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/DefaultJavaPluginConvention.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/DefaultJavaPluginExtension.java
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/DefaultJavaPluginConventionTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/JavaBasePluginTest.groovy
Labels: @jvm, from:member, in:jvm-ecosystem

#14462 Remove as many links to guides as possible
  buildSrc/subprojects/documentation/src/main/groovy/gradlebuild/docs/GradleUserManualPlugin.java
  subprojects/base-services/src/main/java/org/gradle/api/internal/DocumentationRegistry.java
  subprojects/base-services/src/test/groovy/org/gradle/api/internal/DocumentationRegistryTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/BuildInitPluginIntegrationTest.groovy
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/BasicProjectGenerator.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/JvmGradlePluginProjectInitDescriptor.java
  subprojects/docs/src/docs/userguide/api/kotlin_dsl.adoc
  subprojects/docs/src/docs/userguide/authoring-builds/authoring_maintainable_build_scripts.adoc
  subprojects/docs/src/docs/userguide/authoring-builds/tutorial_using_tasks.adoc
  subprojects/docs/src/docs/userguide/core-plugins/plugin_reference.adoc
  subprojects/docs/src/docs/userguide/getting_started.adoc
  subprojects/docs/src/docs/userguide/installation.adoc
  subprojects/docs/src/docs/userguide/jvm/building_java_projects.adoc
  subprojects/docs/src/docs/userguide/migration/migrating_from_ant.adoc
  subprojects/docs/src/docs/userguide/migration/migrating_from_maven.adoc
  subprojects/docs/src/docs/userguide/native/building_cpp_projects.adoc
  subprojects/docs/src/docs/userguide/native/building_swift_projects.adoc
  subprojects/docs/src/docs/userguide/userguide.adoc
  subprojects/docs/src/docs/userguide/what_is_gradle.adoc
Labels: @idiomatic, from:member, in:docs

#14438 Migrate TAPI performance tests to use the Gradle profiler infrastructure
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild.performance-templates.gradle
  subprojects/internal-android-performance-testing/build.gradle.kts
  subprojects/internal-android-performance-testing/src/main/java/org/gradle/performance/android/SyncAction.java
  subprojects/internal-performance-testing/src/integTest/groovy/org/gradle/performance/fixture/IdProviderAndroidStudioMockupPerformanceTest.groovy
  subprojects/internal-performance-testing/src/integTest/groovy/org/gradle/performance/fixture/IdProviderToolingApiPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/AbstractAndroidStudioMockupCrossVersionPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/AbstractToolingApiCrossVersionPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/AbstractBuildExperimentRunner.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/CrossVersionPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/DurationMeasurementImpl.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleBuildExperimentRunner.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleBuildExperimentSpec.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleInvocationSpec.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/JfrProfiler.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/NoopProfiler.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/OperationTimer.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/Profiler.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/ToolingApiInvocation.java
  subprojects/performance/build.gradle.kts
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidStudioMockupPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/DeprecationCreationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIDEModelPerformanceTest.groovy
Labels: @execution, from:member

#14470 Fix build scan performance test
  gradle/verification-metadata.xml
  subprojects/build-scan-performance/build.gradle.kts
  subprojects/build-scan-performance/src/performanceTest/groovy/org/gradle/performance/BuildScanPluginPerformanceTest.groovy
  subprojects/build-scan-performance/src/testFixtures/groovy/org/gradle/performance/AbstractBuildScanPluginPerformanceTest.groovy
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleBuildExperimentRunner.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleInvocationSpec.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/MavenBuildExperimentRunner.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy
Labels: @dev-productivity, from:member

#14468 Make new JVM APIs internal for 6.7
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/compile/JavaModuleCrossCompileIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/jvm/BucketOfDependenciesIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/jvm/GeneratedSourcesDirectorySetContributorIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/jvm/JavaLibraryOutgoingElementsBuilderIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/jvm/JvmVariantBuilderIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaBasePlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaLibraryPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JvmEcosystemPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/AbstractConfigurationBuilder.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmEcosystemAttributesDetails.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmLanguageGeneratedSourceDirectoryBuilder.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmLanguageSourceDirectoryBuilder.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmPluginExtension.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmPluginServices.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmVariantBuilder.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/JvmEcosystemAttributesDetails.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/JvmEcosystemUtilities.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/JvmLanguageGeneratedSourceDirectoryBuilder.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/JvmLanguageSourceDirectoryBuilder.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/JvmModelingServices.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/JvmPluginExtension.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/JvmPluginServices.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/JvmVariantBuilder.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/JvmVariantBuilderInternal.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/OutgoingElementsBuilder.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/ResolvableConfigurationBuilder.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/package-info.java
  subprojects/scala/src/main/java/org/gradle/api/plugins/scala/ScalaBasePlugin.java
Labels: @jvm, from:member, in:jvm-ecosystem

#14472 Sample showing how conventions can be shared between buildSrc and the main build
  subprojects/docs/build.gradle
  subprojects/docs/src/samples/build-organization/sharing-convention-plugins-with-build-logic/README.adoc
  subprojects/docs/src/samples/build-organization/sharing-convention-plugins-with-build-logic/groovy/application/build.gradle
  subprojects/docs/src/samples/build-organization/sharing-convention-plugins-with-build-logic/groovy/build-conventions/build.gradle
  subprojects/docs/src/samples/build-organization/sharing-convention-plugins-with-build-logic/groovy/build-conventions/settings.gradle
  subprojects/docs/src/samples/build-organization/sharing-convention-plugins-with-build-logic/groovy/build-conventions/src/main/groovy/myproject.java-conventions.gradle
  subprojects/docs/src/samples/build-organization/sharing-convention-plugins-with-build-logic/groovy/buildSrc/build.gradle
  subprojects/docs/src/samples/build-organization/sharing-convention-plugins-with-build-logic/groovy/buildSrc/src/main/groovy/myproject.greeting.gradle
  subprojects/docs/src/samples/build-organization/sharing-convention-plugins-with-build-logic/groovy/buildSrc/src/main/java/com/example/GreetingTask.java
  subprojects/docs/src/samples/build-organization/sharing-convention-plugins-with-build-logic/groovy/list/build.gradle
  subprojects/docs/src/samples/build-organization/sharing-convention-plugins-with-build-logic/groovy/settings.gradle
  subprojects/docs/src/samples/build-organization/sharing-convention-plugins-with-build-logic/groovy/utilities/build.gradle
  subprojects/docs/src/samples/build-organization/sharing-convention-plugins-with-build-logic/kotlin/application/build.gradle.kts
  subprojects/docs/src/samples/build-organization/sharing-convention-plugins-with-build-logic/kotlin/build-conventions/build.gradle.kts
  subprojects/docs/src/samples/build-organization/sharing-convention-plugins-with-build-logic/kotlin/build-conventions/settings.gradle.kts
  subprojects/docs/src/samples/build-organization/sharing-convention-plugins-with-build-logic/kotlin/build-conventions/src/main/kotlin/myproject.java-conventions.gradle.kts
  subprojects/docs/src/samples/build-organization/sharing-convention-plugins-with-build-logic/kotlin/buildSrc/build.gradle.kts
  subprojects/docs/src/samples/build-organization/sharing-convention-plugins-with-build-logic/kotlin/buildSrc/src/main/java/com/example/GreetingTask.java
  subprojects/docs/src/samples/build-organization/sharing-convention-plugins-with-build-logic/kotlin/buildSrc/src/main/kotlin/myproject.greeting.gradle.kts
  subprojects/docs/src/samples/build-organization/sharing-convention-plugins-with-build-logic/kotlin/list/build.gradle.kts
  subprojects/docs/src/samples/build-organization/sharing-convention-plugins-with-build-logic/kotlin/settings.gradle.kts
  subprojects/docs/src/samples/build-organization/sharing-convention-plugins-with-build-logic/kotlin/utilities/build.gradle.kts
  subprojects/docs/src/samples/build-organization/sharing-convention-plugins-with-build-logic/tests/check.sample.conf
  subprojects/docs/src/samples/build-organization/sharing-convention-plugins-with-build-logic/tests/greet.out
  subprojects/docs/src/samples/build-organization/sharing-convention-plugins-with-build-logic/tests/run.out
  subprojects/docs/src/samples/templates/gradle-plugin-in-java/src/test/java/com/example/plugin/GreetingPluginTest.java
Labels: @idiomatic, a:sample, in:docs

#14460 Restore backwards compatibility for Tooling API build actions
  buildSrc/subprojects/jvm/src/main/kotlin/gradlebuild/jvm/extension/UnitTestAndCompileExtension.kt
  buildSrc/subprojects/packaging/src/main/kotlin/gradlebuild/shaded-jar.gradle.kts
  subprojects/base-services/src/main/java/org/gradle/internal/time/DefaultCountdownTimer.java
  subprojects/tooling-api/build.gradle.kts
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r56/ParameterizedLoadCompositeEclipseModels.java
  subprojects/tooling-api/src/integTest/groovy/org/gradle/integtests/tooling/ToolingApiJdkCompatibilityTest.groovy
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/adapter/ProtocolToModelAdapter.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/adapter/TypeInspector.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/DefaultBuildActionExecuter.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/DefaultGradleConnector.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/DefaultPhasedActionResultListener.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/DefaultProjectConnection.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/DefaultTestLauncher.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/async/DefaultAsyncConsumerActionExecutor.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/connection/LazyConsumerActionExecutor.java
Labels: @core, from:member, in:tooling-api

#14475 Build init and sample - naming new option and release notes
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/BuildInitInteractiveIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/BuildInitPluginIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/MultiProjectJvmApplicationInitIntegrationTest.groovy
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/JvmProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/modifiers/ModularizationOption.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/tasks/InitBuild.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/samples/readme-templates/common-body.adoc.template
  subprojects/docs/src/samples/readme-templates/common-summary.adoc.template
  subprojects/docs/src/samples/readme-templates/multi-common-body.adoc.template
  subprojects/docs/src/samples/readme-templates/multi-common-summary.adoc.template
  subprojects/launcher/src/main/resources/release-features.txt
Labels: @idiomatic, from:member, in:build-init-plugin, in:docs

#14485 Tweak sections on 'sample index' and 'gradle init'
  subprojects/docs/src/docs/release/notes.md
Labels: @idiomatic, from:member

#14463 Upgrade tested AGP versions
  gradle/dependency-management/agp-versions.properties
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerJavaCachingSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerKotlinCachingSmokeTest.groovy
Labels: a:chore, from:member

#14478 Mention configuration cache improvements in release notes
  subprojects/docs/src/docs/release/notes.md
Labels: @configuration-cache, from:member

#14487 Improve linking between 'init projects', 'samples' and 'user manual'
  buildSrc/subprojects/build-init-samples/src/main/kotlin/gradlebuild/generate-samples.gradle.kts
  subprojects/base-services/src/main/java/org/gradle/api/internal/DocumentationRegistry.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/BasicProjectGenerator.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/BuildInitializer.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/CompositeProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/CppProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/JvmGradlePluginProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/JvmProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/LanguageLibraryProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/LanguageSpecificAdaptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/LanguageSpecificProjectGenerator.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/ProjectGenerator.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/SwiftProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/maven/PomProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/model/Description.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/modifiers/ComponentType.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/services/ProjectLayoutSetupRegistryFactory.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/tasks/InitBuild.java
  subprojects/build-init/src/test/groovy/org/gradle/buildinit/tasks/InitBuildSpec.groovy
  subprojects/docs/src/docs/userguide/jvm/building_java_projects.adoc
  subprojects/docs/src/docs/userguide/reference/command_line_interface.adoc
  subprojects/docs/src/main/resources/header.html
  subprojects/docs/src/samples/readme-templates/application-summary.adoc.template
  subprojects/docs/src/samples/readme-templates/library-summary.adoc.template
  subprojects/docs/src/samples/readme-templates/multi-common-summary.adoc.template
  subprojects/docs/src/samples/readme-templates/native-application-summary.adoc.template
  subprojects/docs/src/samples/readme-templates/native-library-summary.adoc.template
Labels: @idiomatic, in:build-init-plugin, in:docs

#14492 Allow remote build cache to continue on error with secret toggle
  subprojects/build-cache-http/src/integTest/groovy/org/gradle/caching/http/internal/HttpBuildCacheServiceErrorHandlingIntegrationTest.groovy
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/DefaultBuildCacheController.java
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/service/BaseBuildCacheServiceHandle.java
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/service/OpFiringBuildCacheServiceHandle.java
  subprojects/build-cache/src/test/groovy/org/gradle/caching/internal/controller/DefaultBuildCacheControllerTest.groovy
  subprojects/core/src/main/java/org/gradle/caching/internal/services/BuildCacheControllerFactory.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/HttpBuildCacheServer.groovy
Labels: @execution, from:member

#14466 Introduce a lazy GUtil version of elvis
  subprojects/base-services/src/main/java/org/gradle/util/GUtil.java
  subprojects/core/src/main/java/org/gradle/api/internal/artifacts/publish/ArchivePublishArtifact.java
  subprojects/core/src/main/java/org/gradle/api/internal/artifacts/publish/DecoratingPublishArtifact.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProjectRegistry.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/artifacts/publish/DecoratingPublishArtifactTest.groovy
  subprojects/language-java/src/main/java/org/gradle/external/javadoc/internal/JavadocExecHandleBuilder.java
  subprojects/platform-jvm/src/main/java/org/gradle/api/java/archives/internal/DefaultManifestMergeSpec.java
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/internal/AbstractNativeComponentSpec.java
  subprojects/platform-native/src/testFixtures/groovy/org/gradle/nativeplatform/fixtures/AvailableToolChains.java
  subprojects/platform-play/src/main/java/org/gradle/play/internal/PlayPlatformResolver.java
Labels: @jvm, a:bug, from:member

#14479 Fix handling of deleted files when using verification
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationIntegrityCheckIntegTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationWritingIntegTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/WritableArtifactCacheLockingManager.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/DependencyVerifyingModuleComponentRepository.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/cache/CachingIntegrationFixture.groovy
Labels: @jvm, a:bug, from:member, in:dependency-management

#14276 Keep Kotlin compiler environment alive for a huge performance boost
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/BuildServices.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/KotlinCompilerContextDisposer.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/KotlinCompiler.kt
Labels: a:performance-issue, from:member, in:kotlin-dsl

#14496 Use JUnit 4 for testing
  buildSrc/subprojects/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
Labels: @dev-productivity, from:member

#14508 Add infrastructure to run split performance tests
  .teamcity/Gradle_Check/configurations/PerformanceTest.kt
  .teamcity/Gradle_Check/configurations/PerformanceTestsPass.kt
  .teamcity/Gradle_Check/model/BucketProvider.kt
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/Gradle_Check/model/PerformanceTestBucketProvider.kt
  .teamcity/Gradle_Check/projects/PerformanceTestProject.kt
  .teamcity/Gradle_Check/projects/RootProject.kt
  .teamcity/Gradle_Check/projects/StageProject.kt
Labels: @execution

#14514 Fix typo for daemon memory in generated `gradle.properties`
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/generator/FileContentGenerator.groovy
Labels: @execution

#14507 Put test split files in test-splits dir
  .teamcity/Gradle_Check/model/BucketProvider.kt
  buildSrc/subprojects/integration-testing/src/main/kotlin/gradlebuild/integrationtests/BuildBucketProvider.kt
Labels: @dev-productivity, from:member

#14506 Re-enable DeprecationCreationPerformanceTest and use new API
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/DeprecationCreationPerformanceTest.groovy
  subprojects/performance/src/templates/generateLotsOfDeprecationWarnings/build.gradle
Labels: @dev-productivity, a:chore, from:member

#14502 Mention Kotlin DSL script compilation performance improvements in release notes
  subprojects/docs/src/docs/release/notes.md
Labels: from:member, in:kotlin-dsl

#14510 Mark provider for use at configuration time
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileToolchainIntegrationTest.groovy
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainQueryService.java
Labels: @jvm, from:member, in:jvm-ecosystem

#14505 Select methods instead of filtering for them
  .teamcity/pom.xml
  buildSrc/subprojects/build-platform/build.gradle.kts
  buildSrc/subprojects/performance-testing/src/test/groovy/gradlebuild/performance/PerformanceTestIntegrationTest.groovy
  gradle/verification-metadata.xml
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/docs/src/samples/java/jvm-multi-project-with-additional-test-types/groovy/buildSrc/src/main/groovy/myproject.java-conventions.gradle
  subprojects/docs/src/samples/java/jvm-multi-project-with-additional-test-types/kotlin/buildSrc/src/main/kotlin/myproject.java-conventions.gradle.kts
  subprojects/docs/src/samples/java/jvm-multi-project-with-code-coverage/groovy/buildSrc/src/main/groovy/myproject.java-conventions.gradle
  subprojects/docs/src/samples/java/jvm-multi-project-with-code-coverage/kotlin/buildSrc/src/main/kotlin/myproject.java-conventions.gradle.kts
  subprojects/docs/src/samples/java/jvm-multi-project-with-toolchains/groovy/buildSrc/src/main/groovy/myproject.java-conventions.gradle
  subprojects/docs/src/samples/java/jvm-multi-project-with-toolchains/kotlin/buildSrc/src/main/kotlin/myproject.java-conventions.gradle.kts
  subprojects/docs/src/samples/java/modules-multi-project-with-integration-tests/groovy/buildSrc/src/main/groovy/myproject.java-conventions.gradle
  subprojects/docs/src/samples/java/modules-multi-project-with-integration-tests/kotlin/buildSrc/src/main/kotlin/myproject.java-conventions.gradle.kts
  subprojects/docs/src/samples/java/modules-multi-project/groovy/buildSrc/src/main/groovy/myproject.java-conventions.gradle
  subprojects/docs/src/samples/java/modules-multi-project/kotlin/buildSrc/src/main/kotlin/myproject.java-conventions.gradle.kts
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/junitplatform/JUnitPlatformTestRewriter.groovy
  subprojects/internal-integ-testing/src/test/groovy/org/gradle/test/fixtures/junitplatform/JUnitPlatformTestRewriterTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/test/JavaModuleBackboxTestExcutionIntegrationTest.groovy
  subprojects/logging/build.gradle.kts
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/jvm/ConsoleJUnitPlatformTestWorkerFunctionalTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/TestRetryPluginSmokeTest.groovy
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcher.java
  subprojects/testing-base/src/test/groovy/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcherTest.groovy
  subprojects/testing-junit-platform/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestClassProcessor.java
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junit/JUnitClassLevelFilteringIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformFailFastIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformFilteringIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformNestedPatternMatchingIntegrationTest.groovy
  subprojects/testing-jvm/src/testFixtures/groovy/org/gradle/testing/fixture/JUnitCoverage.groovy
Labels: from:member, in:testing

#14518 Adapt java cross compilation test to use toolchains
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaCrossCompilationIntegrationTest.groovy
Labels: @jvm, from:member, in:jvm-ecosystem

#14525 Donat/fix tapi jdk compat test
  subprojects/tooling-api/src/integTest/groovy/org/gradle/integtests/tooling/ToolingApiClientJdkCompatibilityTest.groovy
Labels: from:member, in:testing

#14494 Split documentation samples tests across several test runners
  subprojects/docs/README.md
  subprojects/docs/build.gradle
  subprojects/docs/src/docsTest/java/org/gradle/docs/samples/BaseSamplesTest.java
  subprojects/docs/src/docsTest/java/org/gradle/docs/samples/Bucket1SnippetsTest.java
  subprojects/docs/src/docsTest/java/org/gradle/docs/samples/Bucket2SnippetsTest.java
  subprojects/docs/src/docsTest/java/org/gradle/docs/samples/Bucket3SnippetsTest.java
  subprojects/docs/src/docsTest/java/org/gradle/docs/samples/ExemplarExternalSamplesFunctionalTest.java
  subprojects/docs/src/docsTest/java/org/gradle/docs/samples/IntegrationTestSamplesExecutor.java
  subprojects/docs/src/docsTest/java/org/gradle/docs/samples/IntegrationTestSamplesRunner.java
  subprojects/docs/src/docsTest/java/org/gradle/docs/samples/PartitioningSamplesRunner.java
  subprojects/docs/src/docsTest/java/org/gradle/docs/samples/SamplesTest.java
Labels: @dev-productivity, a:chore, from:member

#14524 Restore Kotlin DSL subproject editing in IDEA
  subprojects/kotlin-compiler-embeddable/build.gradle.kts
  subprojects/kotlin-dsl/build.gradle.kts
Labels: a:chore, in:kotlin-dsl

#14527 Ensure `ConfigurationCacheClassLoaderScopeRegisteryListener` is always disposed of
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheBuildScopeListenerManagerAction.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheClassLoaderScopeRegistryListener.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheServices.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultConfigurationCache.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/ConfigurationCacheBuildEnablement.kt
Labels: @configuration-cache, a:bug, from:member, in:configuration-cache

#14532 Improve multi project docs
  subprojects/docs/src/docs/userguide/authoring-builds/multi-project/multi_project_builds.adoc
  subprojects/docs/src/docs/userguide/authoring-builds/multi-project/multi_project_configuration_and_execution.adoc
  subprojects/docs/src/docs/userguide/running-builds/intro_multi_project_builds.adoc
  subprojects/docs/src/main/resources/header.html
  subprojects/docs/src/snippets/multiproject/multiple-subprojects/groovy/settings.gradle
  subprojects/docs/src/snippets/multiproject/multiple-subprojects/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/multiproject/multiple-subprojects/tests/test.sample.conf
Labels: @idiomatic, from:member, in:docs

#14539 Restrict Java toolchain download to secure URIs
  subprojects/docs/src/docs/userguide/jvm/toolchains.adoc
  subprojects/platform-jvm/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainDownloadIntegrationTest.groovy
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/install/internal/AdoptOpenJdkDownloader.java
Labels: @jvm, from:member, in:jvm-ecosystem

#14543 Remove outdated performance test description
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/inception/BuildSrcApiChangePerformanceTest.groovy
Labels: a:chore, from:member

#14545 Add experimental projects for the new performance test infrastructure
  .teamcity/Gradle_Check/configurations/PerformanceTest.kt
  .teamcity/Gradle_Check/model/FunctionalTestBucketProvider.kt
  .teamcity/Gradle_Check/model/PerformanceTestBucketProvider.kt
  .teamcity/Gradle_Check/model/bucket-extensions.kt
  .teamcity/Gradle_Check/projects/FunctionalTestProject.kt
  .teamcity/Gradle_Check/projects/PerformanceTestProject.kt
  .teamcity/Gradle_Check/projects/RootProject.kt
  .teamcity/Gradle_Check/projects/StageProject.kt
  .teamcity/Gradle_Check/settings.kts
  .teamcity/performance-test-runtimes.csv
  .teamcity/performance-tests-ci.json
  .teamcityTest/Gradle_Check_Tests/CIConfigIntegrationTests.kt
Labels: @execution

#14535 Let `GeneratePrecompiledScriptPluginAccessors` dispose of `ProjectBuilder` services
  subprojects/base-services/src/main/java/org/gradle/internal/work/DefaultWorkerLeaseService.java
  subprojects/core/src/main/java/org/gradle/testfixtures/internal/ProjectBuilderImpl.java
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/tasks/GeneratePrecompiledScriptPluginAccessors.kt
Labels: a:performance-issue, from:member, in:kotlin-dsl

#14544 Set Kotlin API version to `1.3` in Kotlin DSL script templates
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinBuildScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinInitScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinSettingsScript.kt
Labels: from:member, in:kotlin-dsl

#14547 Drop KotlinCachingSmokeTest
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinCachingSmokeTest.groovy
Labels: a:chore, from:member

#14546 Configure build cache for TC process killing steps
  .teamcity/Gradle_Check/configurations/GradleBuildConfigurationDefaults.kt
  .teamcity/Gradle_Check/configurations/IndividualPerformanceScenarioWorkers.kt
  .teamcity/Gradle_Check/configurations/PerformanceTest.kt
  .teamcity/common/extensions.kt
  .teamcityTest/Gradle_Check_Tests/ApplyDefaultConfigurationTest.kt
Labels: @dev-productivity, from:member

#14542 Upgrade jacoco to latest 0.8.6 and re-enable its tests on JDK15
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheJacocoIntegrationTest.groovy
  subprojects/docs/src/docs/dsl/org.gradle.testing.jacoco.plugins.JacocoPluginExtension.xml
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
  subprojects/docs/src/snippets/testing/jacoco-quickstart/groovy/build.gradle
  subprojects/docs/src/snippets/testing/jacoco-quickstart/kotlin/build.gradle.kts
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractProjectRelocationIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractTaskRelocationIntegrationTest.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoCachingIntegrationTest.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoPluginIntegrationTest.groovy
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoPlugin.java
  subprojects/jacoco/src/test/groovy/org/gradle/internal/jacoco/JacocoAgentJarTest.groovy
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/JacocoIntegrationTest.kt
  subprojects/reporting/src/integTest/groovy/org/gradle/api/reporting/plugins/BuildDashboardPluginIntegrationTest.groovy
Labels: @core, from:member, in:core

#14551 Smoke test Kotlin 1.4.10
  subprojects/docs/src/docs/userguide/compatibility.adoc
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
Labels: a:chore, from:member

#14550 Make toolchain detection more resilient
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/OsXInstallationSupplier.java
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/toolchain/internal/OsXInstallationSupplierTest.groovy
Labels: @jvm, from:member, in:jvm-ecosystem

#14567 Cache detected java installations
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainQueryService.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/SharedJavaInstallationRegistry.java
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/toolchain/internal/SharedJavaInstallationRegistryTest.groovy
Labels: @jvm, from:member

#14574 Simplify `ProblemsListener` structure
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheServices.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/SystemPropertyAccessListener.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/ConfigurationCacheProblemsListener.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/DefaultInjectedClasspathInstrumentationStrategy.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ConfigurationCacheProblems.kt
Labels: @configuration-cache, a:chore, from:member, in:configuration-cache

#14575 Remove unused `ProjectFinder` methods
  subprojects/core/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/ProjectFinder.java
  subprojects/core/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/UnknownProjectFinder.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/DefaultProjectFinder.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GradleScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/ProjectScopeServices.java
Labels: @configuration-cache, a:chore, from:member, in:core

#14557 Increase heap size for ScriptCachingIntegrationTest
  subprojects/soak/src/integTest/kotlin/org/gradle/kotlin/dsl/caching/ScriptCachingIntegrationTest.kt
Labels: @dev-productivity, a:bug, from:member

#14576 Prove queried value source providers can be captured by tasks
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOptionsIntegrationTest.groovy
Labels: @configuration-cache, a:chore, from:member, in:configuration-cache

#14581 Add `@ServiceScope` annotations to services used by `ConfigurationCacheState`
  subprojects/build-events/src/main/java/org/gradle/internal/build/event/BuildEventListenerRegistryInternal.java
  subprojects/core/src/main/java/org/gradle/caching/configuration/internal/BuildCacheConfigurationInternal.java
  subprojects/core/src/main/java/org/gradle/internal/cleanup/BuildOutputCleanupRegistry.java
  subprojects/core/src/main/java/org/gradle/internal/enterprise/core/GradleEnterprisePluginManager.java
Labels: @configuration-cache, a:chore, from:member, in:configuration-cache

#14569 Make toolchain download use proper filename for progress logging
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/install/internal/AdoptOpenJdkDownloader.java
Labels: @jvm, from:member

#14573 Simplify work output snapshotting
  subprojects/build-cache-base/src/main/java/org/gradle/caching/internal/CacheableEntity.java
  subprojects/build-cache-base/src/main/java/org/gradle/caching/internal/origin/OriginMetadataFactory.java
  subprojects/build-cache/src/test/groovy/org/gradle/caching/internal/origin/OriginMetadataFactoryTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuter.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/DefaultCacheableOutputFilePropertySpec.java
  subprojects/core/src/main/java/org/gradle/execution/ProjectExecutionServices.java
  subprojects/core/src/main/java/org/gradle/internal/execution/DefaultOutputSnapshotter.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/ExecutionGradleServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuterTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultDependencyManagementServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactoryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/WorkExecutorTestFixture.java
  subprojects/execution/src/integTest/groovy/org/gradle/internal/execution/IncrementalExecutionIntegrationTest.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/OutputSnapshotter.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/UnitOfWork.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/BroadcastChangingOutputsStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CacheStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CaptureStateBeforeExecutionStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CleanupOutputsStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CreateOutputsStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/SnapshotOutputsStep.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/BroadcastChangingOutputsStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CacheStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CaptureStateBeforeExecutionStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CleanupOutputsStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CreateOutputsStepTest.groovy
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/AccessorsClassPath.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/GradleScopeServices.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/PluginAccessorsClassPath.kt
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/CompositeFileSystemSnapshot.java
Labels: @execution, from:member

#14591 Prepare release for new performance test infrastructure
  .teamcity/Gradle_Check/configurations/PerformanceTest.kt
  .teamcity/Gradle_Check/configurations/PerformanceTestsPass.kt
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/Gradle_Check/model/FunctionalTestBucketProvider.kt
  .teamcity/Gradle_Check/model/PerformanceTestBucketProvider.kt
  .teamcity/Gradle_Check/model/bucket-extensions.kt
  .teamcity/Gradle_Check/projects/FunctionalTestProject.kt
  .teamcity/Gradle_Check/projects/PerformanceTestProject.kt
  .teamcity/Gradle_Check/projects/RootProject.kt
  .teamcity/Gradle_Check/projects/StageProject.kt
  .teamcity/Gradle_Check/settings.kts
  .teamcity/performance-test-runtimes.csv
  .teamcity/performance-tests-ci.json
  .teamcityTest/Gradle_Check_Tests/CIConfigIntegrationTests.kt
Labels: @execution, from:member

#14579 Move probe service to global scope
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/internal/services/PlatformJvmServices.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaInstallationProbe.java
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/toolchain/internal/JavaInstallationProbeTest.groovy
Labels: @jvm, from:member

#14589 Cross-version test kotlin-dsl plugin with kotlin 1.4
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginGradlePluginCrossVersionSmokeTest.kt
Labels: from:member, in:kotlin-dsl

#14590 Upgrade jmh plugin to 0.5.2
  buildSrc/subprojects/build-platform/build.gradle.kts
  gradle/verification-metadata.xml
  subprojects/base-services/build.gradle.kts
Labels: @configuration-cache, from:member, in:gradle-build

#14592 Fix typo in kotlin-dsl IDE resolver logs location
  subprojects/docs/src/docs/userguide/api/kotlin_dsl.adoc
Labels: from:member, in:docs, in:kotlin-dsl

#14595 Let conf cache smoke test prove `:confCache:embeddedIntegTest` is supported
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildConfigurationCacheSmokeTest.groovy
Labels: @configuration-cache, a:chore, from:member, in:configuration-cache

#14596 Use the same `AbsolutePathFileCollectionFingerprinter` for all task inputs
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintController.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintWriter.kt
Labels: @configuration-cache, a:chore, from:member, in:configuration-cache

#14601 Upgrade gradle-profiler and remove hacky maven home setting
  gradle/verification-metadata.xml
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/AbstractGradleVsMavenPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/CrossVersionPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/MavenBuildExperimentRunner.java
Labels: from:member

#14604 Make 'compileOnly' extend 'compileOnlyApi'
  subprojects/docs/src/docs/userguide/img/java-configurations.dot
  subprojects/docs/src/docs/userguide/img/java-configurations.png
  subprojects/docs/src/docs/userguide/img/java-library-ignore-deprecated-main.dot
  subprojects/docs/src/docs/userguide/img/java-library-ignore-deprecated-main.png
  subprojects/plugins/src/integTest/groovy/org/gradle/java/dependencies/JavaConfigurationSetupIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/JvmPluginsHelper.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmVariantBuilder.java
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/JavaLibraryPluginTest.groovy
Labels: @jvm, from:member, in:dependency-management, in:jvm-ecosystem

#14610 Re-enable TestDataGeneratorTest
  subprojects/internal-performance-testing/src/test/groovy/org/gradle/performance/ResultSpecification.groovy
  subprojects/internal-performance-testing/src/test/groovy/org/gradle/performance/results/TestDataGeneratorTest.groovy
Labels: @execution, from:member

#14614 Only create scenario pages for executed scenarios
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/AbstractReportGenerator.java
Labels: @execution, from:member

#14615 Fix AdHoc performance tests on Teamcity
  .teamcity/Gradle_Util_Performance/buildTypes/AdHocPerformanceScenario.kt
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleBuildExperimentRunner.java
Labels: @execution, from:member

#14499 Improve documentation around Services and Service scopes
  subprojects/base-annotations/src/main/java/org/gradle/internal/service/scopes/EventScope.java
  subprojects/base-annotations/src/main/java/org/gradle/internal/service/scopes/Scope.java
  subprojects/base-annotations/src/main/java/org/gradle/internal/service/scopes/ServiceScope.java
  subprojects/base-services/src/main/java/org/gradle/internal/service/scopes/AbstractPluginServiceRegistry.java
  subprojects/base-services/src/main/java/org/gradle/internal/service/scopes/PluginServiceRegistry.java
  subprojects/base-services/src/main/java/org/gradle/internal/service/scopes/Scopes.java
Labels: a:chore, from:member

#14119 Drop support for TLSv1.0 and TLSv1.1
  subprojects/build-cache-http/src/integTest/groovy/org/gradle/caching/http/internal/HttpBuildCacheServiceTest.groovy
  subprojects/build-cache-http/src/main/java/org/gradle/caching/http/internal/DefaultHttpBuildCacheServiceFactory.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/http/DeprecatedTLSVersionDependencyResolutionIntegrationTest.groovy
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/running-builds/build_environment.adoc
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/keystore/TestKeyStore.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/BlockingHttpServer.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/BlockingHttpsServer.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/HttpServerFixture.groovy
  subprojects/resources-http/src/integTest/groovy/org/gradle/internal/resource/transport/http/CookieHeaderTest.groovy
  subprojects/resources-http/src/integTest/groovy/org/gradle/internal/resource/transport/http/HttpClientConfigurerIntegrationTest.groovy
  subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/HttpClientConfigurer.java
  subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/HttpClientHelper.java
  subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/HttpConnectorFactory.java
  subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/HttpResourcesPluginServiceRegistry.java
  subprojects/resources-http/src/test/groovy/org/gradle/internal/resource/transport/http/DeprecatedTLSVersionTest.groovy
  subprojects/resources-http/src/test/groovy/org/gradle/internal/resource/transport/http/HttpClientHelperTest.groovy
  subprojects/resources-http/src/test/groovy/org/gradle/internal/resource/transport/http/HttpClientHelperTimeoutTest.groovy
Labels: from:member

#14617 Link default excludes deprecation to upgrading guide
  subprojects/core-api/src/main/java/org/gradle/api/tasks/util/internal/PatternSpecFactory.java
  subprojects/snapshots/src/integTest/groovy/org/gradle/internal/vfs/DefaultExcludesIntegrationTest.groovy
Labels: @execution, from:member

#14619 Fix differential flame graph generation for performance ad-hoc tests
  .teamcity/Gradle_Util_Performance/buildTypes/AdHocPerformanceScenario.kt
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/AbstractBuildExperimentRunner.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleBuildExperimentRunner.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/JfrDifferentialFlameGraphGenerator.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/JfrToStacksConverter.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/MavenBuildExperimentRunner.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/ProfilerFlameGraphGenerator.java
Labels: @execution, from:member

#14621 Fix test performance ad-hoc test
  .teamcity/Gradle_Check/configurations/TestPerformanceTest.kt
Labels: @execution, from:member

#14625 Convert BuildScanPluginPerformanceTest to new performance test infrastructure
  subprojects/build-scan-performance/build.gradle.kts
  subprojects/build-scan-performance/src/performanceTest/groovy/org/gradle/performance/BuildScanPluginPerformanceTest.groovy
Labels: @execution, from:member

#14629 Add PerformanceTestIdProvider to AbstractBuildScanPluginPerformanceTest
  subprojects/build-scan-performance/src/testFixtures/groovy/org/gradle/performance/AbstractBuildScanPluginPerformanceTest.groovy
Labels: @execution, from:member

#14521 Remove old deprecation API
  subprojects/logging/src/main/java/org/gradle/util/DeprecationLogger.java
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/DeprecationCreationPerformanceTest.groovy
Labels: @dev-productivity, from:member

#14630 Let the jacoco plugin work with the configuration cache
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheJacocoIntegrationTest.groovy
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractProjectRelocationIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractTaskRelocationIntegrationTest.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoCachingIntegrationTest.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoPluginIntegrationTest.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoPluginMultiVersionIntegrationTest.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoVersionCompatibilityIntegrationTest.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/rules/JacocoPluginCoverageVerificationCompatibleVersionIntegTest.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/rules/JacocoPluginCoverageVerificationIntegrationTest.groovy
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoPlugin.java
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoPluginExtension.java
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoTaskExtension.java
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/tasks/JacocoCoverageVerification.java
  subprojects/jacoco/src/test/groovy/org/gradle/testing/jacoco/plugins/JacocoTaskExtensionSpec.groovy
Labels: @configuration-cache, from:member, in:jacoco-plugin

#14626 Minor refinements in configuration cache docs
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
Labels: @configuration-cache, from:member, in:docs

#14603 Stabilize test setup with toolchains
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractSampleIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/java/SamplesJavaTestingIntegrationTest.groovy
Labels: @jvm, from:member, in:jvm-ecosystem

#14640 Fix ordering issues with artifact transforms loaded from the configuration cache
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheDependencyResolutionIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/ArtifactCollectionCodec.kt
  subprojects/core/src/main/java/org/gradle/api/internal/initialization/RootScriptDomainObjectContext.java
  subprojects/core/src/testFixtures/groovy/org/gradle/api/tasks/TasksWithInputsAndOutputs.groovy
Labels: @configuration-cache, from:member

#14643 Explicitly keep Kotlin compiler environment alive when compiling buildscripts
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/KotlinCompiler.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/codegen/GradleApiExtensionsTest.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/provider/KotlinScriptClassPathProviderTest.kt
Labels: @idiomatic, a:performance-issue, from:member, in:kotlin-dsl

#14644 Fix failure attribution for performance tests when a performance test is retried
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild/performance/tasks/PerformanceTest.groovy
  buildSrc/subprojects/performance-testing/src/main/kotlin/gradlebuild/performance/PerformanceTestPlugin.kt
Labels: @execution, from:member

#14650 Remove -Dorg.gradle.internal.tasks.createops from our builds
  .teamcity/common/extensions.kt
  .teamcityTest/Gradle_Check_Tests/ApplyDefaultConfigurationTest.kt
  .teamcityTest/Gradle_Check_Tests/PerformanceTestBuildTypeTest.kt
Labels: @dev-productivity, from:member

#14645 Add --profiler option to performance test tasks
  .teamcity/Gradle_Util_Performance/buildTypes/AdHocPerformanceScenario.kt
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild/performance/tasks/PerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/AbstractBuildExperimentRunner.java
Labels: @execution, from:member

#14651 Fix incremental annotation processing when type isn't top level
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/AggregatingProcessingStrategy.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/ElementUtils.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/processing/AggregatingProcessorTest.groovy
Labels: @jvm, from:member, in:jvm-ecosystem

#14656 Add a task to read the performance test times from the performance database (intent number 2)
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild/performance/tasks/PerformanceTest.groovy
  buildSrc/subprojects/performance-testing/src/main/kotlin/gradlebuild/performance/PerformanceTestPlugin.kt
  subprojects/build-scan-performance/src/testFixtures/groovy/org/gradle/performance/fixture/BuildScanPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/CrossBuildPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/CrossVersionPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleVsMavenPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/TestScenarioSelector.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/AbstractWritableResultsStore.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/AllResultsStore.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/BaseCrossBuildResultsStore.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/CompositeResultsStore.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/CrossVersionPerformanceTestHistory.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/CrossVersionResultsStore.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/NoResultsStore.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/OperatingSystem.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/PerformanceDatabase.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/PerformanceExperiment.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/PerformanceScenario.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/PerformanceTestResult.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/PerformanceTestRuntimesGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/ResultsStore.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/ScenarioBuildResultData.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/DefaultPerformanceExecutionDataProvider.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/DefaultPerformanceFlakinessDataProvider.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/FlakinessDetectionPerformanceExecutionDataProvider.java
  subprojects/internal-performance-testing/src/test/groovy/org/gradle/performance/ResultSpecification.groovy
  subprojects/internal-performance-testing/src/test/groovy/org/gradle/performance/results/CompositeResultsStoreTest.groovy
  subprojects/internal-performance-testing/src/test/groovy/org/gradle/performance/results/CrossBuildResultsStoreTest.groovy
  subprojects/internal-performance-testing/src/test/groovy/org/gradle/performance/results/CrossVersionResultsStoreTest.groovy
  subprojects/internal-performance-testing/src/test/groovy/org/gradle/performance/results/TestDataGeneratorTest.groovy
Labels: @execution, from:member

#14653 Replace UUID with a fixed string in generated build files
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild/performance/generator/tasks/AbstractProjectGeneratorTask.groovy
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild/performance/generator/tasks/CppMultiProjectGeneratorTask.groovy
Labels: @execution, from:member

#14647 Refine Jacoco plugin support for the configuration cache
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/docs/src/docs/dsl/org.gradle.testing.jacoco.plugins.JacocoPluginExtension.xml
  subprojects/docs/src/docs/userguide/core-plugins/jacoco_plugin.adoc
  subprojects/docs/src/snippets/testing/jacoco-quickstart/groovy/build.gradle
  subprojects/docs/src/snippets/testing/jacoco-quickstart/kotlin/build.gradle.kts
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoPluginMultiVersionIntegrationTest.groovy
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoPlugin.java
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoPluginExtension.java
  subprojects/logging/src/main/java/org/gradle/internal/deprecation/DeprecationMessageBuilder.java
Labels: @configuration-cache, from:member, in:jacoco-plugin

#14628 Let checkstyle, pmd and codenarc plugins work with the configuration cache
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/PmdPluginIncrementalAnalysisIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginClasspathIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginMultiProjectTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginVersionIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcCompilationClasspathIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcPluginIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcPluginVersionIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/pmd/PmdPluginAuxclasspathIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/pmd/PmdPluginDependenciesIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/pmd/PmdPluginSubtypeParamIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/pmd/PmdPluginVersionIntegrationTest.groovy
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CheckstylePlugin.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CodeNarcPlugin.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/Pmd.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdExtension.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdPlugin.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/PmdInvoker.groovy
  subprojects/code-quality/src/test/groovy/org/gradle/api/plugins/quality/PmdPluginTest.groovy
  subprojects/docs/src/docs/dsl/org.gradle.api.plugins.quality.Pmd.xml
  subprojects/docs/src/docs/dsl/org.gradle.api.plugins.quality.PmdExtension.xml
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
  subprojects/docs/src/snippets/codeQuality/codeQuality/groovy/build.gradle
  subprojects/docs/src/snippets/codeQuality/codeQuality/kotlin/build.gradle.kts
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/IsolatedAntBuilderMemoryLeakIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractProjectRelocationIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/WellBehavedPluginTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesCodeQualityIntegrationTest.groovy
Labels: @configuration-cache, from:member, in:checkstyle-plugin, in:codenarc-plugin, in:pmd-plugin

#14658 Always run flakiness detection
  .teamcity/Gradle_Check/configurations/PerformanceTest.kt
  .teamcity/Gradle_Check/configurations/PerformanceTestsPass.kt
  .teamcity/Gradle_Check/configurations/StagePasses.kt
  .teamcity/Gradle_Check/model/PerformanceTestBucketProvider.kt
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild/performance/tasks/PerformanceTest.groovy
Labels: @execution, from:member

#14661 Use all history for flakiness report when none is found for commitId
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/FlakinessDetectionPerformanceExecutionDataProvider.java
Labels: @execution, from:member

#14663 Cleanup whole `perf-results` before copying the artifacts
  .teamcity/Gradle_Check/configurations/PerformanceTestsPass.kt
Labels: @execution, from:member

#14667 Rebaseline performance tests where Kotlin compilation speeds improved
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/inception/BuildSrcApiChangePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaFirstUsePerformanceTest.groovy
Labels: from:member

#14665 Run slow performance tests for flakiness detection
  .teamcity/Gradle_Check/model/PerformanceTestBucketProvider.kt
Labels: @execution, from:member

#14668 PerformanceExecutionDataProvider again uses real Git commit ID
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/PerformanceExecutionDataProvider.java
Labels: @dev-productivity, from:member

#14666 Read performance data from generated JSON file
  .teamcity/Gradle_Check/model/PerformanceTestBucketProvider.kt
  .teamcity/Gradle_Check/projects/RootProject.kt
  .teamcity/performance-test-runtimes.csv
  .teamcity/performance-test-runtimes.json
Labels: @execution, from:member

#14664 Fix reproduction instructions in performance report
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/BaseCrossBuildResultsStore.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/CrossBuildPerformanceTestHistory.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/CrossVersionPerformanceTestHistory.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/EmptyPerformanceTestHistory.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/NoResultsStore.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/PerformanceExperiment.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/PerformanceTestHistory.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/AbstractTablePageGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/TestPageGenerator.java
  subprojects/internal-performance-testing/src/test/groovy/org/gradle/performance/ResultSpecification.groovy
Labels: @execution, from:member

#14670 Fix wrong replacedBy in Report
  subprojects/reporting/src/main/java/org/gradle/api/reporting/Report.java
Labels: @execution, from:member

#14672 Address review feedback for performance test changes
  .teamcity/performance-test-runtimes.json
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/AbstractWritableResultsStore.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/AbstractWritableResultsStore.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/AllResultsStore.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/CompositeResultsStore.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/NoResultsStore.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/PerformanceScenarioRuntimes.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/PerformanceTestRuntimesGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/ResultsStore.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/TestProjectRuntime.groovy
Labels: @dev-productivity, from:member

#14679 Lock only once when dispatching messages
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/DefaultDaemonConnection.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/DefaultIncomingConnectionHandler.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/IncomingConnectionHandler.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/SynchronizedDispatchConnection.java
  subprojects/launcher/src/test/groovy/org/gradle/launcher/daemon/server/DefaultDaemonConnectionTest.groovy
Labels: @execution, from:member

#14677 Set thread name for DaemonConnectionBackedEventConsumer.ForwardEvents
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/exec/DaemonConnectionBackedEventConsumer.java
Labels: @execution, from:member

#14682 Remove unused `FileAccessTracker.markAccessed(Collection)` method
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/filestore/TwoStageArtifactIdentifierFileStore.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resource/cached/TwoStageExternalResourceFileStore.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/filestore/TwoStageArtifactIdentifierFileStoreTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/resource/cached/TwoStageExternalResourceFileStoreTest.groovy
  subprojects/files/src/main/java/org/gradle/internal/file/FileAccessTracker.java
  subprojects/files/src/main/java/org/gradle/internal/file/impl/SingleDepthFileAccessTracker.java
  subprojects/files/src/test/groovy/org/gradle/internal/file/impl/SingleDepthFileAccessTrackerTest.groovy
Labels: @execution

#14671 Use name given to a build by includeBuild() for IDE import to avoid duplicates
  subprojects/ide/src/crossVersionTest/groovy/org/gradle/plugins/ide/tooling/r68/CompositeBuildModuleNamesCrossVersionSpec.groovy
  subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/configurer/DefaultUniqueProjectNameProvider.java
Labels: @idiomatic, a:bug, from:member, in:composite-builds, in:eclipse-plugin, in:idea-plugin

#14627 Avoid construction of full component metadata for included projects
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultIncludedBuild.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/WellBehavedPluginTest.groovy
Labels: @idiomatic, from:member, in:composite-builds, in:dependency-management

#14686 Add windows and macOS performance tests
  .teamcity/Gradle_Check/configurations/PerformanceTest.kt
  .teamcity/Gradle_Check/configurations/PerformanceTestsPass.kt
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/Gradle_Check/model/PerformanceTestBucketProvider.kt
  .teamcity/Gradle_Check/model/PerformanceTestCoverage.kt
  .teamcity/Gradle_Check/model/bucket-extensions.kt
  .teamcity/Gradle_Check/projects/PerformanceTestProject.kt
  .teamcityTest/Gradle_Check_Tests/PerformanceTestBuildTypeTest.kt
Labels: @execution, from:member

#14588 Move immutable transform outputs under common parent directory
  gradle/verification-metadata.xml
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/CacheLayout.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformationWorkspace.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/ImmutableTransformationWorkspaceProvider.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/MutableTransformationWorkspaceProvider.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationStep.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationWorkspaceProvider.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/CacheLayoutTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactoryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/TestTransformationWorkspaceProvider.java
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/MavenBuildExperimentRunner.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/GradleProfilerReporter.java
Labels: @execution, from:member

#14636 Rename method for clarity
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultBuildableCompositeBuildContext.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/IncludedBuildDependencySubstitutionsBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultGlobalDependencyResolutionRules.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/dependencysubstitution/DefaultDependencySubstitutions.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/dependencysubstitution/DependencySubstitutionRules.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolutionstrategy/DefaultResolutionStrategy.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/locking/DefaultDependencyLockingProvider.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/dependencysubstitution/DefaultDependencySubstitutionsSpec.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/locking/DefaultDependencyLockingProviderTest.groovy
Labels: @jvm, from:member, in:dependency-management

#14688 Write performance runtime for all operating systems to json file
  .teamcity/performance-test-runtimes.json
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/AbstractWritableResultsStore.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/AllResultsStore.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/CompositeResultsStore.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/NoResultsStore.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/PerformanceExperimentOnOs.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/PerformanceTestRuntimesGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/ResultsStore.java
Labels: @execution, from:member
