Repository gradle/gradle, pull requests merged in 2020-08, with the labels that each got.

#13991 Avoid intermediate collections computing the relevant fields of a class
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/beans/BeanSchema.kt
Labels: @configuration-cache, a:performance-issue, from:member, in:configuration-cache

#13986 Add classpath annotation to JacocoReport.
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/tasks/JacocoReportBase.java
Labels: @execution

#13987 Propagate sdkman candidates directory to tests
  buildSrc/subprojects/jvm/src/main/kotlin/gradlebuild/propagated-env-variables.kt
Labels: @jvm, from:member

#14007 Fix path separator for toolchain soak test
  subprojects/soak/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainDownloadSoakTest.groovy
Labels: @jvm, from:member

#13995 Handle PlaceholderAssertionError in ShortExceptionFormatter
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/logging/ShortExceptionFormatter.java
  subprojects/testing-base/src/test/groovy/org/gradle/api/internal/tasks/testing/logging/ShortExceptionFormatterTest.groovy
Labels: @jvm, a:bug, from:member, in:testing

#14011 Preserve causes of custom AssertionError
  subprojects/messaging/src/main/java/org/gradle/internal/serialize/ExceptionPlaceholder.java
  subprojects/messaging/src/main/java/org/gradle/internal/serialize/PlaceholderAssertionError.java
  subprojects/messaging/src/test/groovy/org/gradle/internal/serialize/MessageTest.groovy
Labels: @jvm, from:member, in:core

#14012 Convert NameMatcherTest to Spock test
  subprojects/core/src/test/groovy/org/gradle/util/NameMatcherTest.groovy
  subprojects/core/src/test/groovy/org/gradle/util/NameMatcherTest.java
Labels: @idiomatic, a:chore, from:member, in:testing

#14021 Lock in build cache performance improvements
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingJavaPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingNativePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingSwiftPerformanceTest.groovy
Labels: @execution, from:member

#14014 Upgradle and use compatible test distribution plugin
  buildSrc/subprojects/jvm/jvm.gradle.kts
  gradle/verification-metadata.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: @execution, from:member

#14025 Upgrade test-retry plugin to 1.1.7
  buildSrc/subprojects/build-platform/build-platform.gradle.kts
  gradle/verification-metadata.xml
Labels: @dev-productivity, from:member

#14028 Reduce window for marking issues as stale
  .github/stale.yml
Labels: from:member

#14027 Use gradle profiler for first use performance tests
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleProfilerBuildExperimentRunner.java
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaFirstUsePerformanceTest.groovy
Labels: @execution, from:member

#13921 Improve the throwable cycle detection
  subprojects/messaging/src/main/java/org/gradle/internal/serialize/ExceptionPlaceholder.java
  subprojects/messaging/src/main/java/org/gradle/internal/serialize/TopLevelExceptionPlaceholder.java
Labels: @jvm, from:member, in:core

#14015 Let precompiled Kotlin script plugins apply plugin relying on `providers.gradleProperty`
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradlePropertiesController.java
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/precompiled/PrecompiledScriptPluginAccessorsTest.kt
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/tasks/GeneratePrecompiledScriptPluginAccessors.kt
Labels: @configuration-cache, a:bug, from:member, in:configuration-cache, in:kotlin-dsl

#14032 Do not handle RuntimeException specifically
  subprojects/build-operations/src/main/java/org/gradle/internal/operations/BuildOperationInvocationException.java
  subprojects/build-operations/src/main/java/org/gradle/internal/operations/DefaultBuildOperationRunner.java
  subprojects/messaging/src/main/java/org/gradle/internal/event/AbstractBroadcastDispatch.java
Labels: @execution

#13520 Eclipse API for unresolved dependencies
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DistributionIntegrationSpec.groovy
  subprojects/ide/src/crossVersionTest/groovy/org/gradle/plugins/ide/tooling/r67/ToolingApiEclipseModelUnresolvedDependenciesCrossVersionSpec.groovy
  subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/UnresolvedLibrary.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/internal/EclipseDependenciesCreator.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/EclipseModelBuilder.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/eclipse/DefaultEclipseComponentSelector.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/eclipse/DefaultEclipseExternalDependency.java
  subprojects/ide/src/test/groovy/org/gradle/plugins/ide/internal/tooling/eclipse/EclipseModelBuilderDependenciesTest.groovy
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/connection/HasCompatibilityMapping.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/converters/EclipseExternalDependencyUnresolvedMixin.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/model/ComponentSelector.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/model/eclipse/EclipseExternalDependency.java
Labels: from:contributor

#14038 Allow build operations to throw checked exceptions
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/DefaultBuildCacheController.java
  subprojects/build-operations/src/main/java/org/gradle/internal/operations/BuildOperationRunner.java
  subprojects/build-operations/src/main/java/org/gradle/internal/operations/BuildOperationWorker.java
  subprojects/build-operations/src/main/java/org/gradle/internal/operations/CallableBuildOperation.java
  subprojects/build-operations/src/main/java/org/gradle/internal/operations/DefaultBuildOperationRunner.java
  subprojects/build-operations/src/main/java/org/gradle/internal/operations/RunnableBuildOperation.java
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CacheTaskArchiveErrorIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/CleanupStaleOutputsExecuter.java
Labels: @execution

#14029 Refactor BuildOperationRunner
  subprojects/base-services/src/main/java/org/gradle/internal/operations/DelegatingBuildOperationExecutor.java
  subprojects/build-operations/src/main/java/org/gradle/internal/operations/DefaultBuildOperationRunner.java
  subprojects/core/src/main/java/org/gradle/internal/operations/DefaultBuildOperationExecutor.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/CrossBuildSessionScopeServices.java
  subprojects/internal-integ-testing/src/integTest/groovy/org/gradle/integtests/fixtures/executer/IgnoreKotlinCompilerWarningIntegrationTest.groovy
Labels: @execution

#14040 Mention file systems supported for file system watching
  subprojects/docs/src/docs/userguide/running-builds/gradle_daemon.adoc
Labels: @execution

#14036 Not retry PerformanceTest
  buildSrc/subprojects/jvm/src/main/kotlin/gradlebuild/unittest-and-compile.gradle.kts
  buildSrc/subprojects/performance-testing/performance-testing.gradle.kts
  buildSrc/subprojects/performance-testing/src/main/kotlin/gradlebuild/performance/PerformanceTestPlugin.kt
  buildSrc/subprojects/performance-testing/src/test/groovy/gradlebuild/performance/PerformanceTestIntegrationTest.groovy
Labels: from:member

#13972 Protect ProgressLogEventGenerator#onComplete() against NPEs
  subprojects/logging/src/main/java/org/gradle/internal/logging/sink/ProgressLogEventGenerator.java
Labels: @core, from:contributor

#14016 Only watch project directories by default
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/SymlinkFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/WatchedDirectoriesFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/SnapshotCollectingDiffListener.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/CheckIfNonEmptySnapshotVisitor.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DarwinFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DefaultFileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/LinuxFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/SnapshotWatchedDirectoryFinder.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WatchableHierarchies.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WindowsFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/BuildLifecycleAwareVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingNotSupportedVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystemTest.groovy
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/AbstractCompleteFileSystemLocationSnapshot.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/AbstractIncompleteSnapshotWithChildren.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/CompleteDirectorySnapshot.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/FileSystemNode.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/ReadOnlyFileSystemNode.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SnapshotHierarchy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SnapshotUtil.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultSnapshotHierarchy.java
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/AbstractCompleteSnapshotWithoutChildrenTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/AbstractIncompleteSnapshotWithChildrenTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/AbstractSnapshotWithChildrenTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/CompleteDirectorySnapshotTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/vfs/impl/DefaultSnapshotHierarchyTest.groovy
Labels: @execution, from:member

#13996 Use 64 kB buffer size for Windows file events
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WindowsFileWatcherRegistryFactory.java
Labels: @execution, from:member

#13823 Avoid recursion when computing dependents
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java
Labels: @jvm, a:bug, from:member, in:jvm-ecosystem

#13833 Classes to be compiled should only include classes with sources
  buildSrc/subprojects/basics/src/main/kotlin/gradlebuild/basics/extension/BuildJvms.kt
  subprojects/language-java/language-java.gradle.kts
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/AggregatingProcessingStrategy.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/ElementUtils.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/processing/AggregatingProcessorTest.groovy
Labels: @jvm, a:bug, from:member

#14099 Deprecate older toolchain APIs
  subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/javadoc/Javadoc.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/platform/JavaPlatform.java
Labels: @jvm, from:member

#14102 Prove config cache is invalidated upon change to script of included build
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionIncludedBuildChangesIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionScriptChangesIntegrationTest.groovy
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/fixtures/ScriptChangeFixture.groovy
Labels: @configuration-cache, from:member, in:composite-builds, in:configuration-cache

#14078 Move file system watching logging to build operations
  subprojects/file-watching/file-watching.gradle.kts
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/BuildOperationsFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesDuringTheBuildFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/BuildFinishedFileSystemWatchingBuildOperationType.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/BuildLifecycleAwareVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/BuildStartedFileSystemWatchingBuildOperationType.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/FileSystemWatchingStatistics.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/DefaultFileSystemWatchingStatistics.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingNotSupportedVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingNotSupportedVirtualFileSystemTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystemTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/FileSystemWatchingFixture.groovy
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunner.java
  subprojects/launcher/src/test/groovy/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunnerTest.groovy
  subprojects/soak/src/integTest/groovy/org/gradle/vfs/FileSystemWatchingSoakTest.groovy
Labels: @execution, from:member

#14109 Fix incremental annotation processing
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/IsolatingIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/IncrementalResultStoringCompiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/RecompilationNotNecessary.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/SelectiveCompiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/DefaultIncrementalCompileResult.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/IncrementalCompilationResult.java
Labels: @jvm, from:contributor, in:jvm-ecosystem

#14110 Update tested AGP versions
  gradle/dependency-management/agp-versions.properties
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerJavaCachingSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerKotlinCachingSmokeTest.groovy
Labels: @configuration-cache, a:chore, from:member

#14124 Fix missing reference in composite build user guide
  buildSrc/subprojects/documentation/src/main/groovy/gradlebuild/docs/GradleUserManualPlugin.java
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/declaring_repositories.adoc
Labels: a:regression, from:member, in:docs

#14089 Update "State of support in popular annotation processors"
  subprojects/docs/src/docs/userguide/jvm/java_plugin.adoc
Labels: from:contributor

#14112 Configure binary-compatibility plugin classpath without using subprojects {}
  buildSrc/subprojects/basics/src/main/kotlin/gradlebuild/minify.gradle.kts
  buildSrc/subprojects/binary-compatibility/src/main/groovy/gradlebuild.binary-compatibility.gradle
  buildSrc/subprojects/binary-compatibility/src/main/groovy/gradlebuild/binarycompatibility/transforms/FindGradleJars.groovy
  buildSrc/subprojects/uber-plugins/src/main/kotlin/gradlebuild/kotlin-library.gradle.kts
  subprojects/architecture-test/architecture-test.gradle.kts
  subprojects/distributions-full/distributions-full.gradle.kts
Labels: from:member

#14126 Fix missing category attribute on plugin classpath
  subprojects/core/src/main/java/org/gradle/api/internal/initialization/DefaultScriptHandler.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/PluginVariantResolveIntegrationTest.groovy
Labels: @jvm, a:bug, from:member

#14121 Update jquery to 3.5.1
  gradle/verification-metadata.xml
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/reporting/dependencies/HtmlDependencyReportTaskIntegrationTest.groovy
  subprojects/diagnostics/src/main/java/org/gradle/api/reporting/dependencies/internal/ProjectPageRenderer.java
  subprojects/docs/docs.gradle
  subprojects/internal-performance-testing/internal-performance-testing.gradle.kts
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/AbstractReportGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/HtmlPageGenerator.java
  subprojects/reporting/reporting.gradle.kts
Labels: from:member

#14113 Capture file system watching statistics as custom values in build scans
  buildSrc/subprojects/profiling/src/main/kotlin/gradlebuild/buildscan.gradle.kts
Labels: @execution, from:member

#14120 Remove old analytics code
  subprojects/messaging/src/main/java/org/gradle/internal/serialize/ExceptionPlaceholder.java
Labels: @dev-productivity, from:member

#14101 Limit the number of directories to watch
  subprojects/core/src/integTest/groovy/org/gradle/internal/operations/logging/LoggingBuildOperationProgressIntegTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/BuildOperationsFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/WatchedDirectoriesFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DarwinFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DefaultFileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/LinuxFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WatchableHierarchies.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WindowsFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/FileSystemWatchingStatistics.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/DefaultFileSystemWatchingStatistics.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdaterTest.groovy
Labels: @execution, from:member

#14058 Compose build operation executor
  subprojects/base-services/src/main/java/org/gradle/internal/operations/BuildOperationExecutor.java
  subprojects/build-operations/src/main/java/org/gradle/internal/operations/BuildOperationRunner.java
  subprojects/build-operations/src/main/java/org/gradle/internal/operations/BuildOperationState.java
  subprojects/build-operations/src/main/java/org/gradle/internal/operations/BuildOperationWorker.java
  subprojects/build-operations/src/main/java/org/gradle/internal/operations/DefaultBuildOperationRunner.java
  subprojects/build-operations/src/test/groovy/org/gradle/internal/operations/DefaultBuildOperationRunnerTest.groovy
  subprojects/core/src/main/java/org/gradle/internal/operations/DefaultBuildOperationExecutor.java
  subprojects/core/src/main/java/org/gradle/internal/operations/UnmanagedBuildOperationWrapper.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/CrossBuildSessionScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/internal/operations/DefaultBuildOperationExecutorParallelExecutionTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/operations/DefaultBuildOperationExecutorTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/operations/DefaultBuildOperationQueueTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/operations/MaxWorkersTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/internal/operations/TestBuildOperationExecutor.java
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/CommandLineToolInvocationWorker.java
Labels: @execution, from:member

#14136 Enable configuration cache space usage analysis
  subprojects/instant-execution/src/integTest/groovy/org/gradle/instantexecution/InstantExecutionDebugLogIntegrationTest.groovy
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/DefaultInstantExecution.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/InstantExecutionState.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/Codec.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/Contexts.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/Logging.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/beans/BeanPropertyReader.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/beans/BeanPropertyWriter.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/BindingsBackedCodec.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/TaskNodeCodec.kt
  subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/WorkNodeCodec.kt
  subprojects/instant-execution/src/test/kotlin/org/gradle/instantexecution/fingerprint/InstantExecutionFingerprintCheckerTest.kt
  subprojects/instant-execution/src/test/kotlin/org/gradle/instantexecution/serialization/codecs/AbstractUserTypeCodecTest.kt
Labels: @configuration-cache, a:feature, from:member, in:configuration-cache

#14081 Fix Core Plugins Leaking ProjectInternal
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/diagnostics/src/main/java/org/gradle/api/plugins/HelpTasksPlugin.java
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoPlugin.java
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/plugins/NativeComponentModelPlugin.java
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/plugins/NativeComponentPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/distribution/plugins/DistributionPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaBasePlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaLibraryDistributionPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java
  subprojects/reporting/src/main/java/org/gradle/api/plugins/ReportingBasePlugin.java
Labels: from:member

#14150 Avoid corruption of surrogate pairs in CopySpec filtering
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/FilterChain.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/copy/FilterChainTest.java
Labels: @core, from:contributor

#14176 Let `ConfigurableFileCollection#setFrom()` clear the collection
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/DefaultConfigurableFileCollection.java
  subprojects/file-collections/src/test/groovy/org/gradle/api/internal/file/collections/DefaultConfigurableFileCollectionSpec.groovy
Labels: @core, a:regression, from:member

#14164 Cleanup build-init subproject
  subprojects/build-init/src/main/groovy/org/gradle/buildinit/plugins/internal/maven/Maven2Gradle.groovy
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/BuildInitPlugin.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/WrapperPlugin.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/BuildScriptBuilder.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/CompositeProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/ConditionalTemplateOperation.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/CppApplicationProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/CppLibraryProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/GitAttributesGenerator.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/GroovyApplicationProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/JavaApplicationProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/JavaProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/JvmGradlePluginProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/KotlinApplicationProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/ProjectLayoutSetupRegistry.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/ResourceDirsGenerator.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/SimpleTemplateOperation.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/SwiftApplicationProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/SwiftLibraryProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/SwiftProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/maven/Dependency.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/maven/ExternalDependency.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/maven/Maven2Gradle.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/maven/MavenProjectsCreator.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/maven/PomProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/maven/ProjectDependency.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/modifiers/BuildInitTestFramework.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/services/BuildInitServices.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/services/ProjectLayoutSetupRegistryFactory.java
Labels: from:member, in:build-init-plugin

#14180 Add watched hierarchies as custom value to build scans
  buildSrc/subprojects/profiling/src/main/kotlin/gradlebuild/buildscan.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
Labels: @execution, from:member

#14170 Improve performance of updating the watched hierarchies when using hierarchical watchers
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WatchedHierarchies.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/WatchedHierarchiesTest.groovy
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/AbstractCompleteFileSystemLocationSnapshot.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/AbstractIncompleteSnapshotWithChildren.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/ReadOnlyFileSystemNode.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SnapshotHierarchy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultSnapshotHierarchy.java
  subprojects/snapshots/src/test/groovy/org/gradle/internal/vfs/impl/DefaultSnapshotHierarchyTest.groovy
Labels: @execution, from:member

#14095 Use separate file-events library
  buildSrc/subprojects/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
  gradle/verification-metadata.xml
  subprojects/core/core.gradle.kts
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java
  subprojects/distributions-dependencies/distributions-dependencies.gradle.kts
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DistributionIntegrationSpec.groovy
  subprojects/file-watching/file-watching.gradle.kts
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DarwinFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/LinuxFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WindowsFileWatcherRegistryFactory.java
  subprojects/native/native.gradle.kts
  subprojects/native/src/main/java/org/gradle/internal/nativeintegration/NativeCapabilities.java
  subprojects/native/src/main/java/org/gradle/internal/nativeintegration/services/NativeServices.java
Labels: @execution, from:member

#14182 Kill leaking processes on all OSes after the build
  .teamcity/Gradle_Check/configurations/GradleBuildConfigurationDefaults.kt
  .teamcityTest/Gradle_Check_Tests/ApplyDefaultConfigurationTest.kt
Labels: @core, in:core, in:gradle-build

#14191 Allow configuring the maximum number of hierarchies to watch
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/WatchedDirectoriesFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DarwinFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DefaultFileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/LinuxFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WatchableHierarchies.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WindowsFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/BuildLifecycleAwareVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingNotSupportedVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingNotSupportedVirtualFileSystemTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystemTest.groovy
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunner.java
  subprojects/launcher/src/test/groovy/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunnerTest.groovy
Labels: @execution, from:member

#14167 Remove a few samples that are not referenced anywhere
  subprojects/docs/src/snippets/multiproject/addSpecifics/groovy/bluewhale/.ignore-me
  subprojects/docs/src/snippets/multiproject/addSpecifics/groovy/build.gradle
  subprojects/docs/src/snippets/multiproject/addSpecifics/groovy/krill/.ignore-me
  subprojects/docs/src/snippets/multiproject/addSpecifics/groovy/settings.gradle
  subprojects/docs/src/snippets/tasks/customTaskUsingConvention/groovy/build.gradle
  subprojects/docs/src/snippets/tasks/customTaskUsingConvention/groovy/settings.gradle
  subprojects/docs/src/snippets/tasks/incrementalBuild-inputsAndOutputs/groovy/build.gradle
  subprojects/docs/src/snippets/tasks/incrementalBuild-inputsAndOutputs/groovy/mountains.xml
  subprojects/docs/src/snippets/tasks/incrementalBuild-inputsAndOutputs/groovy/settings.gradle
  subprojects/docs/src/snippets/tasks/incrementalBuild-noInputsAndOutputs/groovy/build.gradle
  subprojects/docs/src/snippets/tasks/incrementalBuild-noInputsAndOutputs/groovy/mountains.xml
  subprojects/docs/src/snippets/tasks/incrementalBuild-noInputsAndOutputs/groovy/settings.gradle
  subprojects/docs/src/snippets/tutorial/archiveContent/groovy/build.gradle
  subprojects/docs/src/snippets/tutorial/archiveContent/groovy/settings.gradle
  subprojects/docs/src/snippets/tutorial/rerun/groovy/README.md
  subprojects/docs/src/snippets/tutorial/rerun/groovy/build.gradle
  subprojects/docs/src/snippets/tutorial/rerun/groovy/settings.gradle
  subprojects/docs/src/snippets/tutorial/selectProject/groovy/subdir/build.gradle
  subprojects/docs/src/snippets/tutorial/selectProject/groovy/subdir/myproject.gradle
  subprojects/docs/src/snippets/tutorial/selectProject/groovy/subdir/settings.gradle
Labels: from:member

#14190 Simplify dependency management of JUnit Jupiter
  buildSrc/subprojects/build-platform/build-platform.gradle.kts
  buildSrc/subprojects/packaging/packaging.gradle.kts
  buildSrc/subprojects/performance-testing/performance-testing.gradle.kts
  gradle/verification-metadata.xml
Labels: a:chore, from:member

#14161 Do not use subprojects {} construct in cleanup plugin
  build.gradle.kts
  buildSrc/subprojects/cleanup/src/main/kotlin/gradlebuild/cleanup.gradle.kts
  buildSrc/subprojects/cleanup/src/main/kotlin/gradlebuild/cleanup/services/CachesCleaner.kt
  buildSrc/subprojects/cleanup/src/main/kotlin/gradlebuild/cleanup/services/DaemonTracker.kt
  buildSrc/subprojects/cleanup/src/main/kotlin/gradlebuild/root-cleanup.gradle.kts
  buildSrc/subprojects/integration-testing/src/main/kotlin/gradlebuild/distribution-testing.gradle.kts
  buildSrc/subprojects/integration-testing/src/main/kotlin/gradlebuild/integrationtests/tasks/DistributionTest.kt
  buildSrc/subprojects/uber-plugins/src/main/kotlin/gradlebuild/java-library.gradle.kts
Labels: @core, from:member, in:core, in:gradle-build

#14189 Move promotionBuild task creation to publish-public-libraries plugin
  buildSrc/subprojects/lifecycle/src/main/kotlin/gradlebuild/lifecycle.gradle.kts
  buildSrc/subprojects/publishing/src/main/kotlin/gradlebuild/publish-public-libraries.gradle.kts
Labels: @core, in:core, in:gradle-build

#14187 Configure soakTest lifecycle task in soak subproject
  buildSrc/subprojects/lifecycle/src/main/kotlin/gradlebuild/lifecycle.gradle.kts
  subprojects/soak/soak.gradle.kts
Labels: @core, in:core, in:gradle-build

#14202 Do not kill processes on CI using clean task
  build.gradle.kts
  buildSrc/subprojects/cleanup/src/main/kotlin/gradlebuild/cleanup.gradle.kts
  buildSrc/subprojects/cleanup/src/main/kotlin/gradlebuild/root-cleanup.gradle.kts
  buildSrc/subprojects/uber-plugins/src/main/kotlin/gradlebuild/java-library.gradle.kts
Labels: @core, in:core, in:gradle-build

#14201 Fix volatile test name
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/reproducibility/FailOnDynamicVersionsResolveIntegrationTest.groovy
Labels: @dev-productivity, a:bug, from:member

#13992 Fixed worker leaking its classpath to compilation classpath in ZincSc…
  subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/ZincScalaCompiler.java
  subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/ZincScalaCompilerFacade.java
  subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/ZincScalaCompilerFactory.java
  subprojects/language-scala/src/main/java/org/gradle/language/scala/internal/toolchain/DefaultScalaToolProvider.java
  subprojects/language-scala/src/main/java/org/gradle/language/scala/tasks/PlatformScalaCompile.java
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/ZincScalaCompilerIntegrationTest.groovy
  subprojects/scala/src/main/java/org/gradle/api/internal/tasks/scala/ScalaCompilerFactory.java
Labels: @jvm, from:contributor, in:jvm-ecosystem, in:scala-plugin

#14203 Fix kebab-case name matching
  subprojects/core/src/main/java/org/gradle/util/NameMatcher.java
  subprojects/core/src/test/groovy/org/gradle/util/NameMatcherTest.groovy
Labels: a:regression, from:member

#14204 Use `*-conventions` name pattern for precompiled convention plugins in samples
  subprojects/docs/src/samples/build-organization/multi-project-with-precompiled-script-plugins/README.adoc
  subprojects/docs/src/samples/build-organization/multi-project-with-precompiled-script-plugins/groovy/internal-module/build.gradle
  subprojects/docs/src/samples/build-organization/multi-project-with-precompiled-script-plugins/groovy/library-a/build.gradle
  subprojects/docs/src/samples/build-organization/multi-project-with-precompiled-script-plugins/groovy/library-b/build.gradle
  subprojects/docs/src/samples/build-organization/multi-project-with-precompiled-script-plugins/kotlin/internal-module/build.gradle.kts
  subprojects/docs/src/samples/build-organization/multi-project-with-precompiled-script-plugins/kotlin/library-a/build.gradle.kts
  subprojects/docs/src/samples/build-organization/multi-project-with-precompiled-script-plugins/kotlin/library-b/build.gradle.kts
  subprojects/docs/src/samples/build-organization/precompiled-script-plugin/README.adoc
  subprojects/docs/src/samples/build-organization/precompiled-script-plugin/groovy/consumer-service/build.gradle
  subprojects/docs/src/samples/build-organization/precompiled-script-plugin/kotlin/consumer-service/build.gradle.kts
  subprojects/docs/src/samples/templates/precompiled-script-plugin-groovy/src/main/groovy/com.example.java-conventions.gradle
  subprojects/docs/src/samples/templates/precompiled-script-plugin-groovy/src/main/groovy/com.example.library-conventions.gradle
  subprojects/docs/src/samples/templates/precompiled-script-plugin-groovy/src/main/groovy/com.example.service-conventions.gradle
  subprojects/docs/src/samples/templates/precompiled-script-plugin-groovy/src/test/groovy/com/example/JavaConventionPluginTest.groovy
  subprojects/docs/src/samples/templates/precompiled-script-plugin-groovy/src/test/groovy/com/example/LibraryPluginTest.groovy
  subprojects/docs/src/samples/templates/precompiled-script-plugin-groovy/src/test/groovy/com/example/ServicePluginTest.groovy
  subprojects/docs/src/samples/templates/precompiled-script-plugin-kotlin/src/main/kotlin/com.example.java-conventions.gradle.kts
  subprojects/docs/src/samples/templates/precompiled-script-plugin-kotlin/src/main/kotlin/com.example.library-conventions.gradle.kts
  subprojects/docs/src/samples/templates/precompiled-script-plugin-kotlin/src/main/kotlin/com.example.service-conventions.gradle.kts
  subprojects/docs/src/samples/templates/precompiled-script-plugin-kotlin/src/test/kotlin/com/example/JavaConventionPluginTest.kt
  subprojects/docs/src/samples/templates/precompiled-script-plugin-kotlin/src/test/kotlin/com/example/LibraryPluginTest.kt
  subprojects/docs/src/samples/templates/precompiled-script-plugin-kotlin/src/test/kotlin/com/example/ServicePluginTest.kt
Labels: @core, a:sample, from:member, in:core, in:docs

#14206 Enable FilePropertyFactory to be used with configuration cache
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/DefaultFilePropertyFactory.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/PropertyHost.java
Labels: @jvm, from:member

#14212 Update some DSL syntax used in init templates
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/BuildScriptBuilder.java
  subprojects/build-init/src/test/groovy/org/gradle/buildinit/plugins/internal/BuildScriptBuilderGroovyTest.groovy
  subprojects/build-init/src/test/groovy/org/gradle/buildinit/plugins/internal/BuildScriptBuilderKotlinTest.groovy
Labels: from:member, in:build-init-plugin

#14209 Apply project naming conventions to javadoc
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/DependencyHandler.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/idea/model/IdeaProject.java
Labels: from:member

#14210 Always create a subproject when initialising a new Gradle project
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/AbstractInitIntegrationSpec.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/BasicTypeInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/BuildInitInteractiveIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/BuildInitPluginIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/CppApplicationInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/CppLibraryInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/GroovyApplicationInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/GroovyGradlePluginInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/GroovyLibraryInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/JavaApplicationInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/JavaGradlePluginInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/JavaLibraryInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/KotlinApplicationInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/KotlinGradlePluginInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/KotlinLibraryInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/ScalaLibraryInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/SwiftApplicationInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/SwiftLibraryInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/WindowsSwiftApplicationInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/WindowsSwiftInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/WindowsSwiftLibraryInitIntegrationTest.groovy
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/BasicProjectGenerator.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/BuildScriptBuilder.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/CppProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/InitSettings.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/LanguageSpecificAdaptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/ResourceDirsGenerator.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/SimpleGlobalFilesBuildSettingsDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/SwiftProjectInitDescriptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/TemplateFactory.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/modifiers/ComponentType.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/tasks/InitBuild.java
  subprojects/build-init/src/test/groovy/org/gradle/buildinit/plugins/internal/BuildScriptBuilderGroovyTest.groovy
  subprojects/build-init/src/test/groovy/org/gradle/buildinit/plugins/internal/BuildScriptBuilderKotlinTest.groovy
  subprojects/build-init/src/test/groovy/org/gradle/buildinit/plugins/internal/TemplateFactoryTest.groovy
  subprojects/build-init/src/test/groovy/org/gradle/buildinit/tasks/InitBuildSpec.groovy
  subprojects/build-init/src/testFixtures/groovy/org/gradle/buildinit/plugins/fixtures/ScriptDslFixture.groovy
Labels: from:member, in:build-init-plugin

#14188 Generalize heuristic for using display names in XML reports
  subprojects/internal-testing/src/main/groovy/org/gradle/integtests/fixtures/JUnitTestClassExecutionResult.groovy
  subprojects/internal-testing/src/main/groovy/org/gradle/integtests/fixtures/JUnitXmlTestExecutionResult.groovy
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/junit/result/JUnitXmlResultWriter.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/junit/result/TestClassResult.java
  subprojects/testing-base/src/test/groovy/org/gradle/api/internal/tasks/testing/junit/result/JUnitXmlResultWriterSpec.groovy
  subprojects/testing-junit-platform/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestExecutionListener.java
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/fixture/JUnitMultiVersionIntegrationSpec.groovy
Labels: @jvm, a:regression, from:member, in:testing

#14230 Refurbish precompiled script plugins in buildSrc sample
  subprojects/docs/docs.gradle
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/README.adoc
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/groovy/internal-module/build.gradle
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/groovy/library-a/README.md
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/groovy/library-a/build.gradle
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/groovy/library-b/README.md
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/groovy/library-b/build.gradle
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/groovy/settings.gradle
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/kotlin/internal-module/build.gradle.kts
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/kotlin/library-a/README.md
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/kotlin/library-a/build.gradle.kts
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/kotlin/library-b/README.md
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/kotlin/library-b/build.gradle.kts
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/kotlin/settings.gradle.kts
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/tests/check.sample.conf
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/tests/sanityCheck.conf
  subprojects/docs/src/samples/build-organization/multi-project-with-precompiled-script-plugins/README.adoc
  subprojects/docs/src/samples/templates/precompiled-script-plugin-groovy/build.gradle
  subprojects/docs/src/samples/templates/precompiled-script-plugin-kotlin/build.gradle.kts
Labels: @core, a:sample, from:member, in:core

#14231 Rename com.example.some-convention plugins to myproject.some-convention for consistency in samples
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/README.adoc
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/groovy/internal-module/build.gradle
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/groovy/library-a/build.gradle
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/groovy/library-b/build.gradle
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/kotlin/internal-module/build.gradle.kts
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/kotlin/library-a/build.gradle.kts
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/kotlin/library-b/build.gradle.kts
  subprojects/docs/src/samples/build-organization/precompiled-script-plugin/README.adoc
  subprojects/docs/src/samples/build-organization/precompiled-script-plugin/groovy/consumer-service/build.gradle
  subprojects/docs/src/samples/build-organization/precompiled-script-plugin/kotlin/consumer-service/build.gradle.kts
  subprojects/docs/src/samples/templates/precompiled-script-plugin-groovy/src/main/groovy/myproject.java-conventions.gradle
  subprojects/docs/src/samples/templates/precompiled-script-plugin-groovy/src/main/groovy/myproject.library-conventions.gradle
  subprojects/docs/src/samples/templates/precompiled-script-plugin-groovy/src/main/groovy/myproject.service-conventions.gradle
  subprojects/docs/src/samples/templates/precompiled-script-plugin-groovy/src/test/groovy/com/example/JavaConventionPluginTest.groovy
  subprojects/docs/src/samples/templates/precompiled-script-plugin-groovy/src/test/groovy/com/example/LibraryPluginTest.groovy
  subprojects/docs/src/samples/templates/precompiled-script-plugin-groovy/src/test/groovy/com/example/ServicePluginTest.groovy
  subprojects/docs/src/samples/templates/precompiled-script-plugin-kotlin/src/main/kotlin/myproject.java-conventions.gradle.kts
  subprojects/docs/src/samples/templates/precompiled-script-plugin-kotlin/src/main/kotlin/myproject.library-conventions.gradle.kts
  subprojects/docs/src/samples/templates/precompiled-script-plugin-kotlin/src/main/kotlin/myproject.service-conventions.gradle.kts
  subprojects/docs/src/samples/templates/precompiled-script-plugin-kotlin/src/test/kotlin/com/example/JavaConventionPluginTest.kt
  subprojects/docs/src/samples/templates/precompiled-script-plugin-kotlin/src/test/kotlin/com/example/LibraryPluginTest.kt
  subprojects/docs/src/samples/templates/precompiled-script-plugin-kotlin/src/test/kotlin/com/example/ServicePluginTest.kt
Labels: @core, a:sample, from:member, in:core

#14233 Serialize `ProviderBackedFileCollection`'s provider to the config cache
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/AbstractConfigurationCacheIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOptionsIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/ConfigurableFileCollectionCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/FileCollectionCodec.kt
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskDependencyInferenceIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformWithFileInputsIntegrationTest.groovy
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/ProviderBackedFileCollection.java
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy
Labels: @configuration-cache, a:bug, from:member, in:configuration-cache

#14229 Fix outgoing edge reference counting
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/constraints/DependencyConstraintsBugsIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/NodeState.java
  subprojects/dependency-management/src/testFixtures/groovy/org/gradle/integtests/fixtures/publish/ModuleVersionSpec.groovy
Labels: @jvm, a:bug, from:member, in:dependency-management

#14251 Fix missing gradle profiler report
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/AbstractCrossVersionGradleProfilerPerformanceTest.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/GradleProfilerReporter.java
Labels: @dev-productivity, a:bug, from:member

#14244 Fix embedded test running for projects applying the 'kotlin-dsl' plugin
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/MavenConversionIntegrationTest.groovy
  subprojects/core/src/crossVersionTest/groovy/org/gradle/testfixtures/ProjectBuilderCrossVersionIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/ApplyPluginIntegSpec.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/DependencyClassPathProvider.java
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/CustomPluginIntegrationTest.groovy
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/GradleApiExtensionsIntegrationTest.kt
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/GradleKotlinDslIntegrationTest.kt
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/JacocoIntegrationTest.kt
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/PrecompiledScriptPluginIntegrationTest.kt
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/ProjectSchemaAccessorsIntegrationTest.kt
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/ProjectSchemaLambdaAccessorsIntegrationTest.kt
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginGradlePluginCrossVersionSmokeTest.kt
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginTest.kt
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/precompiled/AbstractPrecompiledScriptPluginTest.kt
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/precompiled/PrecompiledScriptPluginAccessorsTest.kt
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/plugins/PrecompiledGroovyPluginsIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesCustomExternalTaskIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesCustomPluginIntegrationTest.groovy
Labels: @dev-productivity, in:gradle-build, in:kotlin-dsl

#14261 Point userguide section about integration tests to a sample
  subprojects/docs/src/docs/userguide/authoring-builds/organizing_gradle_projects.adoc
  subprojects/docs/src/snippets/organizingGradleProjects/separatedTestTypes/groovy/build.gradle
  subprojects/docs/src/snippets/organizingGradleProjects/separatedTestTypes/groovy/gradle/integration-test.gradle
  subprojects/docs/src/snippets/organizingGradleProjects/separatedTestTypes/groovy/settings.gradle
  subprojects/docs/src/snippets/organizingGradleProjects/separatedTestTypes/groovy/src/integTest/java/DefaultFileReaderIntegrationTest.java
  subprojects/docs/src/snippets/organizingGradleProjects/separatedTestTypes/groovy/src/main/java/DefaultFileReader.java
  subprojects/docs/src/snippets/organizingGradleProjects/separatedTestTypes/groovy/src/main/java/FileReader.java
  subprojects/docs/src/snippets/organizingGradleProjects/separatedTestTypes/groovy/src/main/java/StringUtils.java
  subprojects/docs/src/snippets/organizingGradleProjects/separatedTestTypes/groovy/src/test/java/StringUtilsTest.java
  subprojects/docs/src/snippets/organizingGradleProjects/separatedTestTypes/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/organizingGradleProjects/separatedTestTypes/kotlin/gradle/integration-test.gradle.kts
  subprojects/docs/src/snippets/organizingGradleProjects/separatedTestTypes/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/organizingGradleProjects/separatedTestTypes/kotlin/src/integTest/java/DefaultFileReaderIntegrationTest.java
  subprojects/docs/src/snippets/organizingGradleProjects/separatedTestTypes/kotlin/src/main/java/DefaultFileReader.java
  subprojects/docs/src/snippets/organizingGradleProjects/separatedTestTypes/kotlin/src/main/java/FileReader.java
  subprojects/docs/src/snippets/organizingGradleProjects/separatedTestTypes/kotlin/src/main/java/StringUtils.java
  subprojects/docs/src/snippets/organizingGradleProjects/separatedTestTypes/kotlin/src/test/java/StringUtilsTest.java
  subprojects/docs/src/snippets/organizingGradleProjects/separatedTestTypes/tests/integrationTestSourceSetAndTask.sample.conf
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/organizinggradleprojects/SamplesOrganizingGradleProjectsIntegrationTest.groovy
Labels: @core, from:member, in:core, in:docs

#14207 Use kebab case for project names in user manual
  subprojects/docs/src/docs/userguide/authoring-builds/more_about_tasks.adoc
  subprojects/docs/src/docs/userguide/authoring-builds/multi_project_builds.adoc
  subprojects/docs/src/docs/userguide/authoring-builds/plugins.adoc
  subprojects/docs/src/docs/userguide/reference/command_line_interface.adoc
  subprojects/docs/src/snippets/multiproject/dependencies-messagesHack/groovy/a-producer/build.gradle
  subprojects/docs/src/snippets/multiproject/dependencies-messagesHack/groovy/settings.gradle
  subprojects/docs/src/snippets/multiproject/dependencies-messagesHack/kotlin/a-producer/build.gradle.kts
  subprojects/docs/src/snippets/multiproject/dependencies-messagesHack/kotlin/settings.gradle.kts
Labels: from:member

#14266 Do not depend on baseline version in jar names for binary compatibility check
  buildSrc/subprojects/binary-compatibility/src/main/groovy/gradlebuild.binary-compatibility.gradle
  buildSrc/subprojects/binary-compatibility/src/main/groovy/gradlebuild/binarycompatibility/transforms/FindGradleJars.groovy
  buildSrc/subprojects/lifecycle/src/main/kotlin/gradlebuild/lifecycle.gradle.kts
Labels: a:bug, from:member, in:gradle-build

#14271 Kill leaked processes from previous builds for non-test CI jobs
  .teamcity/Gradle_Check/configurations/GradleBuildConfigurationDefaults.kt
  .teamcityTest/Gradle_Check_Tests/ApplyDefaultConfigurationTest.kt
Labels: @core, from:member, in:core, in:gradle-build

#14265 De-incubate file system watching
  subprojects/core/src/integTest/groovy/org/gradle/api/SettingsPluginIntegrationSpec.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/StartParameterInternal.java
  subprojects/core/src/main/java/org/gradle/initialization/StartParameterBuildOptions.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java
  subprojects/docs/src/docs/userguide/running-builds/build_environment.adoc
  subprojects/docs/src/docs/userguide/running-builds/gradle_daemon.adoc
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/EnableFileSystemWatchingIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/ProjectLoadingIntegrationTest.java
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/action/BuildActionSerializer.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunner.java
  subprojects/launcher/src/test/groovy/org/gradle/launcher/cli/BuildActionSerializerTest.groovy
  subprojects/logging/src/main/java/org/gradle/internal/deprecation/DeprecationLogger.java
  subprojects/logging/src/main/java/org/gradle/internal/deprecation/DeprecationMessageBuilder.java
  subprojects/logging/src/test/groovy/org/gradle/internal/deprecation/DeprecationMessagesTest.groovy
Labels: @execution, from:member

#14286 Set Kotlin language version to `1.3` in Kotlin DSL script templates
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinBuildScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinInitScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinSettingsScript.kt
Labels: a:feature, from:member, in:kotlin-dsl

#14275 Document naming recommendations
  subprojects/docs/src/docs/userguide/authoring-builds/multi_project_builds.adoc
  subprojects/docs/src/docs/userguide/reference/command_line_interface.adoc
Labels: from:member

#14260 Add a section about configuration sharing in multi-project builds
  subprojects/docs/src/docs/userguide/authoring-builds/multi_project_builds.adoc
  subprojects/docs/src/docs/userguide/running-builds/intro_multi_project_builds.adoc
  subprojects/docs/src/snippets/multiproject/basic-multiproject/groovy/app/build.gradle
  subprojects/docs/src/snippets/multiproject/basic-multiproject/groovy/app/src/main/java/com/example/Hello.java
  subprojects/docs/src/snippets/multiproject/basic-multiproject/groovy/settings.gradle
  subprojects/docs/src/snippets/multiproject/basic-multiproject/kotlin/app/build.gradle.kts
  subprojects/docs/src/snippets/multiproject/basic-multiproject/kotlin/app/src/main/java/com/example/Hello.java
  subprojects/docs/src/snippets/multiproject/basic-multiproject/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/multiproject/basic-multiproject/tests/projects.out
  subprojects/docs/src/snippets/multiproject/basic-multiproject/tests/run.out
  subprojects/docs/src/snippets/multiproject/basic-multiproject/tests/test.sample.conf
Labels: @core, from:member, in:core, in:docs

#14259 Update user manual to communicate that having subprojects is the default
  subprojects/docs/src/docs/userguide/authoring-builds/organizing_gradle_projects.adoc
  subprojects/docs/src/docs/userguide/reference/directory_layout.adoc
  subprojects/docs/src/docs/userguide/reference/gradle_wrapper.adoc
Labels: from:member, in:docs

#14282 Update project dependencies section in multiproject documentation
  subprojects/docs/src/docs/userguide/authoring-builds/multi_project_builds.adoc
  subprojects/docs/src/snippets/multiproject/dependencies-java/groovy/api/build.gradle
  subprojects/docs/src/snippets/multiproject/dependencies-java/groovy/build.gradle
  subprojects/docs/src/snippets/multiproject/dependencies-java/groovy/buildSrc/build.gradle
  subprojects/docs/src/snippets/multiproject/dependencies-java/groovy/buildSrc/settings.gradle
  subprojects/docs/src/snippets/multiproject/dependencies-java/groovy/buildSrc/src/main/groovy/myproject.java-conventions.gradle
  subprojects/docs/src/snippets/multiproject/dependencies-java/groovy/services/person-service/build.gradle
  subprojects/docs/src/snippets/multiproject/dependencies-java/groovy/shared/build.gradle
  subprojects/docs/src/snippets/multiproject/dependencies-java/kotlin/api/build.gradle.kts
  subprojects/docs/src/snippets/multiproject/dependencies-java/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/multiproject/dependencies-java/kotlin/buildSrc/build.gradle.kts
  subprojects/docs/src/snippets/multiproject/dependencies-java/kotlin/buildSrc/settings.gradle.kts
  subprojects/docs/src/snippets/multiproject/dependencies-java/kotlin/buildSrc/src/main/kotlin/myproject.java-conventions.gradle.kts
  subprojects/docs/src/snippets/multiproject/dependencies-java/kotlin/services/person-service/build.gradle.kts
  subprojects/docs/src/snippets/multiproject/dependencies-java/kotlin/shared/build.gradle.kts
  subprojects/docs/src/snippets/multiproject/dependencies-java/tests/multitestingBuild.sample.conf
  subprojects/docs/src/snippets/multiproject/dependencies-java/tests/multitestingBuildDependents.sample.conf
  subprojects/docs/src/snippets/multiproject/dependencies-java/tests/multitestingBuildNeeded.sample.conf
  subprojects/docs/src/snippets/multiproject/dependencies-javaWithCustomConf/groovy/api/build.gradle
  subprojects/docs/src/snippets/multiproject/dependencies-javaWithCustomConf/groovy/build.gradle
  subprojects/docs/src/snippets/multiproject/dependencies-javaWithCustomConf/groovy/buildSrc/build.gradle
  subprojects/docs/src/snippets/multiproject/dependencies-javaWithCustomConf/groovy/buildSrc/settings.gradle
  subprojects/docs/src/snippets/multiproject/dependencies-javaWithCustomConf/groovy/buildSrc/src/main/groovy/myproject.java-conventions.gradle
  subprojects/docs/src/snippets/multiproject/dependencies-javaWithCustomConf/groovy/services/person-service/build.gradle
  subprojects/docs/src/snippets/multiproject/dependencies-javaWithCustomConf/groovy/services/person-service/src/main/java/org/gradle/sample/services/PersonService.java
  subprojects/docs/src/snippets/multiproject/dependencies-javaWithCustomConf/groovy/shared/build.gradle
  subprojects/docs/src/snippets/multiproject/dependencies-javaWithCustomConf/kotlin/api/build.gradle.kts
  subprojects/docs/src/snippets/multiproject/dependencies-javaWithCustomConf/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/multiproject/dependencies-javaWithCustomConf/kotlin/buildSrc/build.gradle.kts
  subprojects/docs/src/snippets/multiproject/dependencies-javaWithCustomConf/kotlin/buildSrc/settings.gradle.kts
  subprojects/docs/src/snippets/multiproject/dependencies-javaWithCustomConf/kotlin/buildSrc/src/main/kotlin/myproject.java-conventions.gradle.kts
  subprojects/docs/src/snippets/multiproject/dependencies-javaWithCustomConf/kotlin/services/person-service/build.gradle.kts
  subprojects/docs/src/snippets/multiproject/dependencies-javaWithCustomConf/kotlin/services/person-service/src/main/java/org/gradle/sample/services/PersonService.java
  subprojects/docs/src/snippets/multiproject/dependencies-javaWithCustomConf/kotlin/shared/build.gradle.kts
  subprojects/docs/src/snippets/multiproject/dependencies-javaWithCustomConf/tests/javaWithCustomConf.sample.conf
  subprojects/docs/src/snippets/multiproject/flat/groovy/dolphin/.ignore-me
  subprojects/docs/src/snippets/multiproject/flat/groovy/master/build.gradle
  subprojects/docs/src/snippets/multiproject/flat/groovy/master/settings.gradle
  subprojects/docs/src/snippets/multiproject/flat/groovy/shark/.ignore-me
Labels: @core, from:member, in:core, in:docs

#14281 Update project dependencies code snippet to not use subprojects {} construct
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/declaring_dependencies.adoc
  subprojects/docs/src/snippets/dependencyManagement/declaringDependencies-projectDependencies/groovy/api/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/declaringDependencies-projectDependencies/groovy/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/declaringDependencies-projectDependencies/groovy/utils/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/declaringDependencies-projectDependencies/groovy/web-service/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/declaringDependencies-projectDependencies/kotlin/api/build.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/declaringDependencies-projectDependencies/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/declaringDependencies-projectDependencies/kotlin/utils/build.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/declaringDependencies-projectDependencies/kotlin/web-service/build.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/declaringDependencies-projectDependencies/tests/assemble.out
  subprojects/docs/src/snippets/dependencyManagement/declaringDependencies-projectDependencies/tests/project-dependencies.sample.conf
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/dependencymanagement/SamplesDeclaringDependenciesIntegrationTest.groovy
Labels: @core, from:member, in:core, in:docs

#14283 Introduce snapshotting service for TD to use
  subprojects/enterprise/enterprise.gradle.kts
  subprojects/enterprise/src/integTest/groovy/org/gradle/internal/snapshot/SnapshottingServiceIntegrationTest.groovy
  subprojects/enterprise/src/main/java/org/gradle/internal/snapshot/Snapshot.java
  subprojects/enterprise/src/main/java/org/gradle/internal/snapshot/SnapshottingService.java
  subprojects/enterprise/src/main/java/org/gradle/internal/snapshot/impl/DefaultSnapshottingService.java
  subprojects/enterprise/src/main/java/org/gradle/internal/snapshot/impl/SnapshottingServices.java
  subprojects/enterprise/src/main/resources/META-INF/services/org.gradle.internal.service.scopes.PluginServiceRegistry
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/FileSystemAccess.java
Labels: from:member

#14290 Move multi-project execution sections from authoring to executing page
  subprojects/docs/src/docs/userguide/authoring-builds/build_lifecycle.adoc
  subprojects/docs/src/docs/userguide/authoring-builds/multi_project_builds.adoc
  subprojects/docs/src/docs/userguide/running-builds/intro_multi_project_builds.adoc
  subprojects/docs/src/snippets/multiproject/partialTasks/groovy/bluewhale/build.gradle
  subprojects/docs/src/snippets/multiproject/partialTasks/groovy/build.gradle
  subprojects/docs/src/snippets/multiproject/partialTasks/groovy/krill/build.gradle
  subprojects/docs/src/snippets/multiproject/partialTasks/groovy/settings.gradle
  subprojects/docs/src/snippets/multiproject/partialTasks/groovy/tropicalfish/build.gradle
  subprojects/docs/src/snippets/multiproject/partialTasks/kotlin/bluewhale/build.gradle.kts
  subprojects/docs/src/snippets/multiproject/partialTasks/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/multiproject/partialTasks/kotlin/krill/build.gradle.kts
  subprojects/docs/src/snippets/multiproject/partialTasks/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/multiproject/partialTasks/kotlin/tropicalfish/build.gradle.kts
  subprojects/docs/src/snippets/multiproject/partialTasks/tests/multiprojectPartialTasks.out
  subprojects/docs/src/snippets/multiproject/partialTasks/tests/multiprojectPartialTasks.sample.conf
  subprojects/docs/src/snippets/multiproject/partialTasks/tests/multiprojectPartialTasksNotQuiet.out
  subprojects/docs/src/snippets/multiproject/partialTasks/tests/multiprojectPartialTasksNotQuiet.sample.conf
Labels: @core, from:member, in:core, in:docs

#14295 Remove cross-configuration with war webapps snippet and user guide section
  subprojects/docs/src/docs/userguide/authoring-builds/multi_project_builds.adoc
  subprojects/docs/src/snippets/multiproject/dependencies-webDist/groovy/build.gradle
  subprojects/docs/src/snippets/multiproject/dependencies-webDist/groovy/date/src/main/java/org/gradle/sample/DateServlet.java
  subprojects/docs/src/snippets/multiproject/dependencies-webDist/groovy/date/src/main/webapp/web.xml
  subprojects/docs/src/snippets/multiproject/dependencies-webDist/groovy/hello/src/main/java/org/gradle/sample/HelloServlet.java
  subprojects/docs/src/snippets/multiproject/dependencies-webDist/groovy/hello/src/main/webapp/web.xml
  subprojects/docs/src/snippets/multiproject/dependencies-webDist/groovy/settings.gradle
  subprojects/docs/src/snippets/multiproject/dependencies-webDist/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/multiproject/dependencies-webDist/kotlin/date/src/main/java/org/gradle/sample/DateServlet.java
  subprojects/docs/src/snippets/multiproject/dependencies-webDist/kotlin/date/src/main/webapp/web.xml
  subprojects/docs/src/snippets/multiproject/dependencies-webDist/kotlin/hello/src/main/java/org/gradle/sample/HelloServlet.java
  subprojects/docs/src/snippets/multiproject/dependencies-webDist/kotlin/hello/src/main/webapp/web.xml
  subprojects/docs/src/snippets/multiproject/dependencies-webDist/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/multiproject/dependencies-webDist/tests/webdist.sample.conf
Labels: @core, from:member, in:core, in:docs

#14296 Recommend convention plugins over subprojects{} in Using Gradle Plugins section
  subprojects/docs/src/docs/userguide/authoring-builds/plugins.adoc
  subprojects/docs/src/snippets/plugins/multiproject/groovy/project/build.gradle
  subprojects/docs/src/snippets/plugins/multiproject/groovy/project/hello-a/build.gradle
  subprojects/docs/src/snippets/plugins/multiproject/groovy/project/hello-b/build.gradle
  subprojects/docs/src/snippets/plugins/multiproject/groovy/project/settings.gradle
  subprojects/docs/src/snippets/plugins/multiproject/kotlin/project/build.gradle.kts
  subprojects/docs/src/snippets/plugins/multiproject/kotlin/project/hello-a/build.gradle.kts
  subprojects/docs/src/snippets/plugins/multiproject/kotlin/project/hello-b/build.gradle.kts
  subprojects/docs/src/snippets/plugins/multiproject/kotlin/project/settings.gradle.kts
Labels: @core, from:member, in:core, in:docs

#14301 Let `JavaExec#mainClass` convention be computed lazily
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheJavaIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/tasks/JavaExec.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/OrElseProvider.java
Labels: @configuration-cache, a:feature, from:member, in:configuration-cache

#14308 Polish `:configuration-cache`
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheJavaIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheHost.kt
Labels: @configuration-cache, a:chore, from:member, in:configuration-cache

#14303 Add verbose VFS logging
  subprojects/core/src/main/java/org/gradle/api/internal/StartParameterInternal.java
  subprojects/core/src/main/java/org/gradle/initialization/StartParameterBuildOptions.java
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesDuringTheBuildFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/EnableFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/BuildLifecycleAwareVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingNotSupportedVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingNotSupportedVirtualFileSystemTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystemTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/FileSystemWatchingFixture.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/FileSystemWatchingHelper.java
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/action/BuildActionSerializer.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunner.java
  subprojects/launcher/src/test/groovy/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunnerTest.groovy
Labels: @execution

#14315 Update ivy-publish snippet to use convention plugins instead of cross-configuration
  subprojects/docs/src/docs/userguide/dep-man/06-publishing/publishing_ivy.adoc
  subprojects/docs/src/snippets/ivy-publish/java-multi-project/groovy/build.gradle
  subprojects/docs/src/snippets/ivy-publish/java-multi-project/groovy/buildSrc/build.gradle
  subprojects/docs/src/snippets/ivy-publish/java-multi-project/groovy/buildSrc/src/main/groovy/myproject.publishing-conventions.gradle
  subprojects/docs/src/snippets/ivy-publish/java-multi-project/groovy/project1/build.gradle
  subprojects/docs/src/snippets/ivy-publish/java-multi-project/groovy/project2/build.gradle
  subprojects/docs/src/snippets/ivy-publish/java-multi-project/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/ivy-publish/java-multi-project/kotlin/buildSrc/build.gradle.kts
  subprojects/docs/src/snippets/ivy-publish/java-multi-project/kotlin/buildSrc/src/main/kotlin/myproject.publishing-conventions.gradle.kts
  subprojects/docs/src/snippets/ivy-publish/java-multi-project/kotlin/project1/build.gradle.kts
  subprojects/docs/src/snippets/ivy-publish/java-multi-project/kotlin/project2/build.gradle.kts
  subprojects/docs/src/snippets/ivy-publish/java-multi-project/tests/publish-multi-project.sample.conf
Labels: @core, from:member, in:core, in:docs

#14316 Update Groovy snippets to use convention plugins instead of cross-configuration
  subprojects/docs/src/docs/userguide/jvm/groovy_plugin.adoc
  subprojects/docs/src/snippets/groovy/compilationAvoidance/groovy/ast-transformation-consumer/build.gradle
  subprojects/docs/src/snippets/groovy/compilationAvoidance/groovy/ast-transformation/build.gradle
  subprojects/docs/src/snippets/groovy/compilationAvoidance/groovy/build.gradle
  subprojects/docs/src/snippets/groovy/compilationAvoidance/kotlin/ast-transformation-consumer/build.gradle.kts
  subprojects/docs/src/snippets/groovy/compilationAvoidance/kotlin/ast-transformation-consumer/src/main/groovy/Main.groovy
  subprojects/docs/src/snippets/groovy/compilationAvoidance/kotlin/ast-transformation/build.gradle.kts
  subprojects/docs/src/snippets/groovy/compilationAvoidance/kotlin/ast-transformation/src/main/groovy/MyASTTransformation.groovy
  subprojects/docs/src/snippets/groovy/compilationAvoidance/kotlin/ast-transformation/src/main/groovy/MyAnnotation.groovy
  subprojects/docs/src/snippets/groovy/compilationAvoidance/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/groovy/incrementalCompilation/groovy/app/build.gradle
  subprojects/docs/src/snippets/groovy/incrementalCompilation/groovy/build.gradle
  subprojects/docs/src/snippets/groovy/incrementalCompilation/groovy/buildSrc/build.gradle
  subprojects/docs/src/snippets/groovy/incrementalCompilation/groovy/buildSrc/src/main/groovy/myproject.groovy-conventions.gradle
  subprojects/docs/src/snippets/groovy/incrementalCompilation/groovy/library/build.gradle
  subprojects/docs/src/snippets/groovy/incrementalCompilation/kotlin/app/build.gradle.kts
  subprojects/docs/src/snippets/groovy/incrementalCompilation/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/groovy/incrementalCompilation/kotlin/buildSrc/build.gradle.kts
  subprojects/docs/src/snippets/groovy/incrementalCompilation/kotlin/buildSrc/src/main/kotlin/myproject.groovy-conventions.gradle.kts
  subprojects/docs/src/snippets/groovy/incrementalCompilation/kotlin/library/build.gradle.kts
Labels: @core, @idiomatic, from:member, in:core, in:docs

#14138 RepositoryContentDescriptor: support for version ranges when including/excluding by version
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ExclusiveRepositoryContentFilteringIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/RepositoryContentFilteringIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultDependencyManagementServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/AbstractArtifactRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/AbstractAuthenticationSupportedRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/AbstractResolutionAwareArtifactRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultBaseRepositoryFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultIvyArtifactRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultMavenArtifactRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultMavenLocalArtifactRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultMavenRepositoryContentDescriptor.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultRepositoryContentDescriptor.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/AbstractAuthenticationSupportedRepositoryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/DefaultBaseRepositoryFactoryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/DefaultIvyArtifactRepositoryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/DefaultMavenArtifactRepositoryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/DefaultMavenLocalRepositoryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/DefaultRepositoryContentDescriptorTest.groovy
Labels: @jvm, from:contributor, in:dependency-management

#14285 Move initialization of available included builds to before buildSrc is executed
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildBuildSrcBuildOperationsIntegrationTest.groovy
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildOperationsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/BuildInitializationBuildOperationsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/LoadBuildStructureBuildOperationIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/buildsrc/BuildSrcBuildOperationsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/buildsrc/BuildSrcIncludedBuildIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/internal/operations/notify/BuildOperationNotificationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/configuration/BuildTreePreparingProjectsPreparer.java
  subprojects/core/src/main/java/org/gradle/configuration/DefaultProjectsPreparer.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradleLauncher.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradleLauncherFactory.java
  subprojects/core/src/main/java/org/gradle/internal/operations/trace/BuildOperationRecord.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/BuildScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/configuration/DefaultProjectsPreparerTest.groovy
  subprojects/core/src/test/groovy/org/gradle/initialization/DefaultGradleLauncherSpec.groovy
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/AbstractConsoleBuildPhaseFunctionalTest.groovy
  subprojects/logging/src/main/java/org/gradle/internal/logging/console/BuildStatusRenderer.java
  subprojects/logging/src/main/java/org/gradle/internal/logging/console/ProgressBar.java
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r25/BuildProgressCrossVersionSpec.groovy
  subprojects/version-control/src/integTest/groovy/org/gradle/vcs/internal/SourceDependencyBuildOperationIntegrationTest.groovy
Labels: from:member

#14309 Inject project dir rather than accessing project object
  subprojects/plugins/src/test/groovy/org/gradle/api/tasks/testing/testng/TestNGOptionsTest.groovy
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGTestFramework.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/testng/TestNGOptions.java
  subprojects/testing-jvm/src/test/groovy/org/gradle/api/internal/tasks/testing/testng/TestNGTestClassProcessorTest.groovy
Labels: a:bug, from:member, in:testing

#13759 Change std:cpp17 to std:c++17 for LanguageStandard
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/visualstudio/AbstractVisualStudioProjectIntegrationTest.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/visualstudio/VisualStudioSoftwareModelSingleProjectIntegrationTest.groovy
  subprojects/ide-native/src/main/java/org/gradle/ide/visualstudio/internal/VisualStudioTargetBinary.java
Labels: @core, from:contributor

#14320 Remove unreferenced swift snippet
  subprojects/docs/src/snippets/swift/basicTest/groovy/build.gradle
  subprojects/docs/src/snippets/swift/basicTest/groovy/settings.gradle
  subprojects/docs/src/snippets/swift/basicTest/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/swift/basicTest/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/swift/basicTest/tests/applySwiftPlugin.sample.conf
Labels: @core, @idiomatic, a:chore, from:member, in:core

#14323 Pull authoring multi project builds topic to its own section in docs nav menu
  subprojects/docs/src/main/resources/header.html
Labels: @idiomatic, from:member, in:docs

#14322 Fix documentation navigation menu highlighting
  subprojects/docs/src/main/resources/footer.html
Labels: @idiomatic, a:bug, from:member, in:docs

#14317 Change maven-publishing/multiple-publications to maven-publishing/customize-identity snippet
  subprojects/docs/src/docs/userguide/dep-man/06-publishing/publishing_maven.adoc
  subprojects/docs/src/snippets/maven-publish/customize-identity/groovy/library/build.gradle
  subprojects/docs/src/snippets/maven-publish/customize-identity/groovy/settings.gradle
  subprojects/docs/src/snippets/maven-publish/customize-identity/kotlin/library/build.gradle.kts
  subprojects/docs/src/snippets/maven-publish/customize-identity/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/maven-publish/customize-identity/tests/publish-customize-identity.sample.conf
  subprojects/docs/src/snippets/maven-publish/multiple-publications/groovy/build.gradle
  subprojects/docs/src/snippets/maven-publish/multiple-publications/groovy/output/project1.pom.xml
  subprojects/docs/src/snippets/maven-publish/multiple-publications/groovy/output/project2-api.pom.xml
  subprojects/docs/src/snippets/maven-publish/multiple-publications/groovy/output/project2-impl.pom.xml
  subprojects/docs/src/snippets/maven-publish/multiple-publications/groovy/settings.gradle
  subprojects/docs/src/snippets/maven-publish/multiple-publications/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/maven-publish/multiple-publications/kotlin/output/project1.pom.xml
  subprojects/docs/src/snippets/maven-publish/multiple-publications/kotlin/output/project2-api.pom.xml
  subprojects/docs/src/snippets/maven-publish/multiple-publications/kotlin/output/project2-impl.pom.xml
  subprojects/docs/src/snippets/maven-publish/multiple-publications/kotlin/settings.gradle.kts
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/SamplesMavenPublishIntegrationTest.groovy
Labels: @core, @idiomatic, from:member, in:core, in:docs

#14195 Allow running performance tests on Windows
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild.performance-templates.gradle
  buildSrc/subprojects/performance-testing/src/main/groovy/gradlebuild/performance/generator/tasks/RemoteProject.groovy
  buildSrc/subprojects/performance-testing/src/main/kotlin/gradlebuild/performance/PerformanceTestPlugin.kt
  buildSrc/subprojects/performance-testing/src/main/kotlin/gradlebuild/performance/tasks/BuildCommitDistribution.kt
  buildSrc/subprojects/performance-testing/src/main/kotlin/gradlebuild/performance/tasks/DetermineBaselines.kt
  buildSrc/subprojects/performance-testing/src/test/kotlin/gradlebuild/performance/tasks/DetermineBaselinesTest.kt
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/AbstractRealLifeAndroidBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidStudioMockupPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingJavaPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingNativePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingSwiftPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ArchiveTreePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ExcludeRuleMergingPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/IdeIntegrationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/LargeDependencyGraphPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ParallelDownloadsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/RichConsolePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/TaskCreationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/VerboseTestOutputPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/WorkerApiPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaABIChangePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaCleanAssemblePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaDependencyReportPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaFirstUsePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaNonABIChangePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaTasksPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaTestChangePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaUpToDatePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/kotlindsl/GradleKotlinDslBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/kotlindsl/KotlinDslVsGroovyDslPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeBuildDependentsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeCleanBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/RealWorldNativePluginPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftCleanBuildPerformanceTest.groovy
Labels: @execution, from:member

#14333 Recommend convention plugins to share input normalization config
  subprojects/docs/src/docs/userguide/authoring-builds/more_about_tasks.adoc
Labels: @idiomatic, from:member, in:docs

#14311 Capture only the names used in manifests as inputs
  buildSrc/subprojects/basics/src/main/kotlin/gradlebuild/basics/tasks/ClasspathManifest.kt
  buildSrc/subprojects/packaging/src/main/kotlin/gradlebuild/packaging/tasks/PluginsManifest.kt
Labels: @core, @execution, from:member

#14341 Use new file system watching properties
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: @execution, from:member

#14326 Add missing `@Nullable` annotations to `o.g.util.VersionNumber`
  subprojects/core/src/main/java/org/gradle/util/VersionNumber.java
Labels: @core, a:chore, from:member

#14325 Enable incremental Kotlin compilation in the Gradle build
  buildSrc/build.gradle.kts
  buildSrc/subprojects/uber-plugins/src/main/kotlin/gradlebuild/kotlin-library.gradle.kts
Labels: a:chore, from:member, in:gradle-build

#14344 Do not drop the VFS on CI
  .teamcity/common/extensions.kt
  .teamcityTest/Gradle_Check_Tests/ApplyDefaultConfigurationTest.kt
  .teamcityTest/Gradle_Check_Tests/PerformanceTestBuildTypeTest.kt
Labels: @execution, from:member

#14340 List all content filtering options
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/declaring_repositories.adoc
Labels: @jvm, from:member, in:dependency-management, in:docs

#14348 Improve configuration cache invalidation tests
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildSrcChangesIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIncludedBuildChangesIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheScriptChangesIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/fixtures/BuildLogicChangeFixture.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/fixtures/ScriptChangeFixture.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/FileCollectionCodec.kt
Labels: @configuration-cache, a:chore, from:member, in:configuration-cache

#14352 Reduce garbage of `ClasspathManifest` and `PluginsManifest`
  buildSrc/subprojects/basics/src/main/kotlin/gradlebuild/basics/tasks/ClasspathManifest.kt
  buildSrc/subprojects/packaging/src/main/kotlin/gradlebuild/packaging/tasks/PluginsManifest.kt
Labels: a:chore, from:member, in:gradle-build

#14342 Followup on VFS properties
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesDuringTheBuildFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/EnableFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/logging/src/main/java/org/gradle/internal/deprecation/DeprecationMessageBuilder.java
Labels: @execution, from:member
