Repository gradle/gradle, pull requests merged in 2021-12, with the labels that each got.

#19176 Merge release
  released-versions.json
Labels: @dev-productivity

#19180 Make DefaultGradlePropertiesLoaderTest more precise
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheCompositeBuildsIntegrationTest.groovy
  subprojects/core/src/test/groovy/org/gradle/initialization/DefaultGradlePropertiesLoaderTest.groovy
Labels: @configuration-cache

#19185 Add test for config cache defect related to system properties from included build
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheGradlePropertiesIntegrationTest.groovy
Labels: @configuration-cache

#19191 Update wrapper to latest nightly
  gradle/wrapper/gradle-wrapper.properties
Labels: @configuration-cache

#18525 Introduce resolution strategy to deactivate global substitution rules
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/ResolutionStrategy.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/DependencyResolveRulesDisableGlobalDependencySubstitutionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolutionstrategy/DefaultResolutionStrategy.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolutionstrategy/DefaultResolutionStrategySpec.groovy
  subprojects/docs/src/docs/dsl/org.gradle.api.artifacts.ResolutionStrategy.xml
  subprojects/docs/src/docs/userguide/authoring-builds/software-product/composite_builds.adoc
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-deactivateGlobalSubstitution/groovy/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-deactivateGlobalSubstitution/groovy/module-a/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-deactivateGlobalSubstitution/groovy/settings.gradle
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-deactivateGlobalSubstitution/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-deactivateGlobalSubstitution/kotlin/module-a/build.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-deactivateGlobalSubstitution/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-deactivateGlobalSubstitution/tests/resolve.out
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-deactivateGlobalSubstitution/tests/resolve.sample.conf
Labels: in:dependency-resolution

#19200 Add reproducer for config cache failure using Kotlin lambda to configure enterprise plugin
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheEnterprisePluginIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractIntegrationSpec.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/configurationcache/ConfigurationCacheProblemsFixture.groovy
Labels: @configuration-cache

#19099 Ensure only a single test suite / project can use any given test type
  subprojects/core-api/src/main/java/org/gradle/api/attributes/TestSuiteType.java
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/OutgoingVariantsReportTaskIntegrationTest.groovy
  subprojects/docs/src/docs/userguide/jvm/jvm_test_suite_plugin.adoc
  subprojects/docs/src/samples/incubating/java/jvm-multi-project-with-code-coverage-standalone/groovy/code-coverage-report/build.gradle
  subprojects/docs/src/samples/incubating/java/jvm-multi-project-with-code-coverage-standalone/kotlin/code-coverage-report/build.gradle.kts
  subprojects/docs/src/samples/incubating/java/jvm-multi-project-with-test-aggregation-standalone/groovy/test-results/build.gradle
  subprojects/docs/src/samples/incubating/java/jvm-multi-project-with-test-aggregation-standalone/kotlin/test-results/build.gradle.kts
  subprojects/docs/src/snippets/testing/test-suite-configure-type/groovy/build.gradle
  subprojects/docs/src/snippets/testing/test-suite-configure-type/kotlin/build.gradle.kts
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoAggregationIntegrationTest.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoPluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/JvmTestSuitePluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/TestReportAggregationPluginIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JvmTestSuitePlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/JvmTestSuite.java
Labels: a:feature, @core, in:test-suites

#19198 Remove incorrent documentation about finalizer tasks
  subprojects/docs/src/docs/userguide/authoring-builds/more_about_tasks.adoc
Labels: @execution, in:documentation

#19208 Improve GitHub actions
  .github/workflows/contributor-pr.yml
  gradle/verification-metadata.xml
  settings.gradle.kts
Labels: @dev-productivity

#19221 Upgrade protobuf plugin smoke test version
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ProtobufPluginSmokeTest.groovy
Labels: @execution

#19188 Ensure set of attributes is unique amongst all consumable configurations in a project
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/ExclusiveVariantsIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/StronglyTypedConfigurationAttributesResolveIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/ConfigurationInternal.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
Labels: @core, in:test-suites

#19210 Disable file system watching when unable to detect unsupported file systems
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DarwinFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DefaultFileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/LinuxFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WatchableHierarchies.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WindowsFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/WatchableFileSystemDetector.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/DefaultWatchableFileSystemDetector.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingNotSupportedVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/DefaultWatchableFileSystemDetectorTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystemTest.groovy
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunner.java
  subprojects/launcher/src/test/groovy/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunnerTest.groovy
Labels: @execution, in:virtual-file-system

#19240 Move org.jetbrains.teamcity:server-api to test scope
  .teamcity/pom.xml
Labels: @dev-productivity

#19238 Update upgrading guide after deprecation of `Provider#forUseAtConfigurationTime`
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/AbstractMinimalProvider.java
Labels: @configuration-cache

#19239 Smoke test Kotlin 1.6.10-RC
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/KotlinGradlePluginVersions.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
Labels: @configuration-cache

#19253 Add reproducer for `taskProvider.map { ... }` configuration cache bug
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskDependencyInferenceIntegrationTest.groovy
Labels: @configuration-cache

#19040 Add descriptions to additional subprojects
  subprojects/platform-base/build.gradle.kts
  subprojects/platform-jvm/build.gradle.kts
  subprojects/plugins/build.gradle.kts
Labels: a:documentation

#18790 Make Test Suites automatically configure idea test sources
  subprojects/docs/src/docs/dsl/org.gradle.plugins.ide.idea.model.IdeaModule.xml
  subprojects/ide/build.gradle.kts
  subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/idea/IdeaSourceDirTypesIntegrationTests.groovy
  subprojects/ide/src/main/java/org/gradle/plugins/ide/idea/IdeaPlugin.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/idea/model/IdeaModule.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/IdeaModelBuilder.java
  subprojects/ide/src/test/groovy/org/gradle/plugins/ide/idea/model/IdeaModelTest.groovy
  subprojects/ide/src/testFixtures/groovy/org/gradle/plugins/ide/fixtures/IdeaModuleFixture.groovy
Labels: @core, in:test-suites

#19261 Don't tag CACHE_MISS for commit distribution build
  build-logic/basics/src/main/kotlin/gradlebuild/basics/BuildParams.kt
  build-logic/performance-testing/src/main/kotlin/gradlebuild/performance/tasks/BuildCommitDistribution.kt
  build-logic/profiling/src/main/kotlin/gradlebuild.buildscan.gradle.kts
Labels: @dev-productivity

#19182 Don't delegate visitCollection -> visitGenericFileTree
  subprojects/core/src/main/java/org/gradle/api/internal/file/archive/AbstractArchiveFileTree.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/archive/AbstractArchiveFileTreeTest.groovy
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/DirectoryFileTree.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/FileTreeAdapter.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/FilteredMinimalFileTree.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/GeneratedSingletonFileTree.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/MinimalFileTree.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/SingleIncludePatternFileTree.java
  subprojects/file-collections/src/test/groovy/org/gradle/api/internal/file/collections/DirectoryFileTreeTest.groovy
  subprojects/file-collections/src/test/groovy/org/gradle/api/internal/file/collections/FilteredMinimalFileTreeTest.groovy
  subprojects/file-collections/src/test/groovy/org/gradle/api/internal/file/collections/GeneratedSingletonFileTreeSpec.groovy
  subprojects/file-collections/src/test/groovy/org/gradle/api/internal/file/collections/SingleIncludePatternFileTreeSpec.groovy
Labels: @execution

#19268 Correct minor grammar mistakes in Configuration Cache docs
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
Labels: in:documentation

#19256 Fix deprecation warning in cross-version-tests due to test options configuration order
  build-logic/integration-testing/src/main/kotlin/gradlebuild.cross-version-tests.gradle.kts
Labels: in:building-gradle, @core, in:deprecation-logging, in:test-suites

#19267 Fix links to JVM Test Suite and feature lifecycle in samples.
  subprojects/docs/src/samples/build-organization/publishing-convention-plugins/README.adoc
  subprojects/docs/src/samples/incubating/build-organization/publishing-convention-plugins/README.adoc
  subprojects/docs/src/samples/incubating/java/jvm-multi-project-with-additional-test-types/README.adoc
  subprojects/docs/src/samples/incubating/java/modules-multi-project-with-integration-tests/README.adoc
  subprojects/docs/src/samples/java/modules-multi-project-with-integration-tests/README.adoc
Labels: @core, in:test-suites, in:documentation

#18865 Support version catalogs in `classpath`
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/DependencyHandler.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/DefaultDependencyHandler.java
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/ScriptHandlerScope.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/ScriptHandlerScopeTest.kt
Labels: in:dependency-version-catalog

#19274 Fix incremental compilation for classes with $ in name
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractJavaGroovyIncrementalCompilationSupport.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractSourceIncrementalCompilationIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/FileNameDerivingClassNameConverter.java
Labels: @execution

#19084 Documentation layout update
  subprojects/docs/src/docs/css/base.css
  subprojects/docs/src/docs/css/manual.css
  subprojects/docs/src/docs/stylesheets/dslHtml.xsl
  subprojects/docs/src/docs/stylesheets/userGuideHtmlCommon.xsl
  subprojects/docs/src/main/resources/footer.html
  subprojects/docs/src/main/resources/header.html
Labels: @core

#19272 Re-enable disable performance tests
  .teamcity/performance-tests-ci.json
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ArchiveTreePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIDEModelPerformanceTest.groovy
Labels: @core

#19281 Add description for plugin-use project
  subprojects/plugin-use/build.gradle.kts
Labels: @core, in:documentation

#19255 Watch watchable hierarchies on Linux
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdaterTest.groovy
Labels: @execution

#19285 Upgrade ASM to 9.2 in the Gradle distribution
  subprojects/distributions-dependencies/build.gradle.kts
Labels: a:chore, in:building-gradle, @configuration-cache

#19269 Update Configuration Cache docs to cover new approach to input tracking
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintWriter.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/PropertyProblem.kt
  subprojects/docs/src/docs/userguide/img/configuration-cache/inputs-report.png
  subprojects/docs/src/docs/userguide/img/configuration-cache/problems-report.png
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
  subprojects/docs/src/snippets/configurationCache/problemsFixed/groovy/build.gradle
  subprojects/docs/src/snippets/configurationCache/problemsFixed/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/configurationCache/problemsFixedReuse/groovy/dest/keep.txt
  subprojects/docs/src/snippets/configurationCache/problemsGroovy/groovy/dest/keep.txt
  subprojects/docs/src/snippets/valueProviders/envVarsDo/groovy/build.gradle
  subprojects/docs/src/snippets/valueProviders/envVarsDo/groovy/settings.gradle
  subprojects/docs/src/snippets/valueProviders/envVarsDo/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/valueProviders/envVarsDo/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/valueProviders/envVarsDont/groovy/build.gradle
  subprojects/docs/src/snippets/valueProviders/envVarsDont/groovy/settings.gradle
  subprojects/docs/src/snippets/valueProviders/envVarsDont/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/valueProviders/envVarsDont/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/valueProviders/envVarsSysPropsDo/groovy/build.gradle
  subprojects/docs/src/snippets/valueProviders/envVarsSysPropsDo/groovy/settings.gradle
  subprojects/docs/src/snippets/valueProviders/envVarsSysPropsDo/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/valueProviders/envVarsSysPropsDo/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/valueProviders/envVarsSysPropsDont/groovy/build.gradle
  subprojects/docs/src/snippets/valueProviders/envVarsSysPropsDont/groovy/settings.gradle
  subprojects/docs/src/snippets/valueProviders/envVarsSysPropsDont/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/valueProviders/envVarsSysPropsDont/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/valueProviders/gradlePropsDo/groovy/build.gradle
  subprojects/docs/src/snippets/valueProviders/gradlePropsDo/groovy/gradle.properties
  subprojects/docs/src/snippets/valueProviders/gradlePropsDo/groovy/settings.gradle
  subprojects/docs/src/snippets/valueProviders/gradlePropsDo/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/valueProviders/gradlePropsDo/kotlin/gradle.properties
  subprojects/docs/src/snippets/valueProviders/gradlePropsDo/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/valueProviders/gradlePropsDont/groovy/build.gradle
  subprojects/docs/src/snippets/valueProviders/gradlePropsDont/groovy/gradle.properties
  subprojects/docs/src/snippets/valueProviders/gradlePropsDont/groovy/settings.gradle
  subprojects/docs/src/snippets/valueProviders/gradlePropsDont/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/valueProviders/gradlePropsDont/kotlin/gradle.properties
  subprojects/docs/src/snippets/valueProviders/gradlePropsDont/kotlin/settings.gradle.kts
Labels: @configuration-cache

#19241 Revised plan for usage checks for verification variants
  subprojects/core-api/src/main/java/org/gradle/api/attributes/Category.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/ConfigurationInternal.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/OutgoingVariantsReportTaskIntegrationTest.groovy
  subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/OutgoingVariantsReportTask.java
  subprojects/docs/src/docs/userguide/dep-man/04-modeling-features/variant_attributes.adoc
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/InspectsOutgoingVariants.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyPublishJavaIntegTest.groovy
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publication/DefaultIvyPublication.java
  subprojects/ivy/src/test/groovy/org/gradle/api/publish/ivy/internal/publication/DefaultIvyPublicationTest.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoPluginIntegrationTest.groovy
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoPlugin.java
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishJavaIntegTest.groovy
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/DefaultMavenPublication.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/validation/MavenPublicationErrorChecker.java
  subprojects/maven/src/test/groovy/org/gradle/api/publish/maven/internal/publication/DefaultMavenPublicationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/JavaPluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/JvmTestSuitePluginIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JvmTestSuitePlugin.java
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/PublicationInternal.java
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/validation/PublicationErrorChecker.java
Labels: in:publishing-plugins, @core, in:test-suites

#19290 Remove dummy buckets & fix Kotlin deprecation warnings
  .teamcity/src/main/kotlin/common/VersionedSettingsBranch.kt
  .teamcity/src/main/kotlin/common/extensions.kt
  .teamcity/src/main/kotlin/common/performance-test-extensions.kt
  .teamcity/src/main/kotlin/configurations/FlakyTestQuarantine.kt
  .teamcity/src/main/kotlin/model/CIBuildModel.kt
  .teamcity/src/main/kotlin/model/FunctionalTestBucketGenerator.kt
  .teamcity/src/main/kotlin/model/GradleSubprojectProvider.kt
  .teamcity/src/main/kotlin/model/PerformanceTestBucketProvider.kt
  .teamcity/src/main/kotlin/model/PerformanceTestSpec.kt
  .teamcity/src/main/kotlin/model/bucket-extensions.kt
  .teamcity/src/main/kotlin/projects/FunctionalTestProject.kt
  .teamcity/src/main/kotlin/projects/StageProject.kt
Labels: @dev-productivity

#19307 Use async-profiler by default in ad-hoc performance tests
  .teamcity/src/main/kotlin/util/AdHocPerformanceScenario.kt
Labels: @execution

#19309 Smoke test Kotlin 1.6.10
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/KotlinGradlePluginVersions.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
Labels: @configuration-cache

#19278 Handle moved hierarchies for non-hierarchical watchers as well
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesBetweenBuildsFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DarwinFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/LinuxFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WindowsFileWatcherRegistryFactory.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdaterTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidStudioMockupPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingJavaPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingNativePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingSwiftPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ArchiveTreePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/DeprecationCreationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ExcludeRuleMergingPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/IdeIntegrationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/LargeDependencyGraphPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ParallelDownloadsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/RichConsolePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/TaskCreationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/VerboseTestOutputPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaCleanAssemblePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationCachePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaDependencyReportPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaFirstUsePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIDEModelPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIncrementalExecutionPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaTasksPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeBuildDependentsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeCleanBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/RealWorldNativePluginPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftCleanBuildPerformanceTest.groovy
Labels: @execution

#19313 Accept performance regression
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidStudioMockupPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingJavaPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingNativePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingSwiftPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ArchiveTreePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/DeprecationCreationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ExcludeRuleMergingPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/IdeIntegrationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/LargeDependencyGraphPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ParallelDownloadsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/RichConsolePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/TaskCreationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/VerboseTestOutputPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaCleanAssemblePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationCachePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaDependencyReportPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaFirstUsePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIDEModelPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIncrementalExecutionPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaTasksPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeBuildDependentsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeCleanBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/RealWorldNativePluginPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftCleanBuildPerformanceTest.groovy
Labels: @execution

#19015 Allow applying plugins with matching versions
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/plugins/LocalPluginResolution.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/use/AlreadyOnClasspathPluginUseIntegrationTest.groovy
  subprojects/plugin-use/src/main/java/org/gradle/plugin/internal/PluginUsePluginServiceRegistry.java
  subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java
  subprojects/plugin-use/src/main/java/org/gradle/plugin/use/resolve/internal/AlreadyOnClasspathPluginResolver.java
  subprojects/plugin-use/src/main/java/org/gradle/plugin/use/resolve/internal/ArtifactRepositoriesPluginResolver.java
  subprojects/plugin-use/src/main/java/org/gradle/plugin/use/resolve/internal/ClassPathPluginResolution.java
  subprojects/plugin-use/src/main/java/org/gradle/plugin/use/resolve/internal/PluginResolution.java
  subprojects/plugin-use/src/main/java/org/gradle/plugin/use/tracker/internal/PluginVersionTracker.java
Labels: a:feature, in:plugin-management, @core, in:dependency-version-catalog

#19322 Move upgrade guide note on `forUseAtConfigurationTime` to the right section
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
Labels: @configuration-cache, in:documentation

#19251 Add failing test for #16774
  subprojects/build-events/src/integTest/groovy/org/gradle/build/event/BuildEventsIntegrationTest.groovy
Labels: @configuration-cache, in:build-services

#19321 Refactor `BuildServiceProvider` in preparation for disallowing access from unrelated tasks
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/EventFiringTaskExecuter.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/ExecuteTaskBuildOperationDetails.java
  subprojects/core/src/main/java/org/gradle/api/services/internal/BuildServiceProvider.java
  subprojects/core/src/main/java/org/gradle/api/services/internal/BuildServiceRegistryInternal.java
  subprojects/core/src/main/java/org/gradle/api/services/internal/DefaultBuildServicesRegistry.java
  subprojects/core/src/main/java/org/gradle/api/services/internal/package-info.java
Labels: a:chore, @configuration-cache

#19273 Force the build timestamp to include the time if testing samples/snippets in docs
  build-logic/module-identity/src/main/kotlin/gradlebuild.module-identity.gradle.kts
  build-logic/module-identity/src/main/kotlin/gradlebuild/identity/provider/BuildTimestampValueSource.kt
Labels: in:documentation

#18867 Documentation: enhance IvyVariantDerivationRule to avoid project references
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-ivyMetadataRule/groovy/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-ivyMetadataRule/kotlin/build.gradle.kts
Labels: @core, in:component-metadata-rules, a:documentation

#18715 Use the file resolver in LazyPublishArtifact
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultDependencyManagementServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/LazyPublishArtifact.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/PublishArtifactNotationParserFactory.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationContainerTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationSpec.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/dsl/PublishArtifactNotationParserFactoryTest.groovy
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/ear/src/main/java/org/gradle/plugins/ear/EarPlugin.java
  subprojects/language-native/src/main/java/org/gradle/language/cpp/plugins/CppLibraryPlugin.java
  subprojects/maven/src/test/groovy/org/gradle/api/publish/maven/internal/artifact/MavenArtifactNotationParserFactoryTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/distribution/plugins/DistributionPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/WarPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/DefaultJavaPluginExtension.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/JvmPluginsHelper.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmVariantBuilder.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/NebulaPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/PlayPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/SpringBootPluginSmokeTest.groovy
Labels: @core

#19330 Add mention of Test Source detection in IDEA (issue 18723) to release notes.
  subprojects/docs/src/docs/release/notes.md
Labels: @core, in:test-suites, in:documentation

#19317 Use newer native platform version
  subprojects/distributions-dependencies/build.gradle.kts
Labels: @execution

#19356 Remove wrong `@` from doNotTrackState in documentation
  subprojects/docs/src/docs/userguide/authoring-builds/more_about_tasks.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
Labels: @execution

#19358 Document `Task#usesService` requirement for constraining concurrent access to services
  subprojects/core-api/src/main/java/org/gradle/api/Task.java
  subprojects/core-api/src/main/java/org/gradle/api/services/BuildServiceRegistration.java
  subprojects/docs/src/docs/dsl/org.gradle.api.Task.xml
  subprojects/docs/src/docs/userguide/extending-gradle/build_services.adoc
Labels: @configuration-cache, in:build-services, a:documentation

#19357 Backport pullRequest build feature in #19101
  .teamcity/src/main/kotlin/configurations/BaseGradleBuildType.kt
  .teamcity/src/main/kotlin/configurations/GradleBuildConfigurationDefaults.kt
  .teamcity/src/main/kotlin/configurations/SanityCheck.kt
Labels: @dev-productivity

#18949 Change to ADOPTIUM vendor for JDK
  .teamcity/src/main/kotlin/common/Jvm.kt
  .teamcity/src/main/kotlin/common/JvmCategory.kt
  .teamcity/src/main/kotlin/common/JvmVendor.kt
  .teamcity/src/main/kotlin/common/JvmVersion.kt
  .teamcity/src/main/kotlin/common/Os.kt
  .teamcity/src/test/kotlin/ApplyDefaultConfigurationTest.kt
  .teamcity/src/test/kotlin/PerformanceTestBuildTypeTest.kt
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
Labels: @dev-productivity

#19359 Fix incremental compilation for JDK8u301
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/FileTimeStampInspector.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/GradleUserHomeScopeFileTimeStampInspector.java
Labels: @execution

#19380 Add _Configuration Cache improvements_ section to release notes
  subprojects/docs/src/docs/release/notes.md
Labels: @configuration-cache

#19280 Promote _Shared Build Services_ API
  subprojects/core-api/src/main/java/org/gradle/api/invocation/Gradle.java
  subprojects/core-api/src/main/java/org/gradle/api/services/BuildService.java
  subprojects/core-api/src/main/java/org/gradle/api/services/BuildServiceParameters.java
  subprojects/core-api/src/main/java/org/gradle/api/services/BuildServiceRegistration.java
  subprojects/core-api/src/main/java/org/gradle/api/services/BuildServiceRegistry.java
  subprojects/core-api/src/main/java/org/gradle/api/services/BuildServiceSpec.java
  subprojects/core-api/src/main/java/org/gradle/api/services/package-info.java
  subprojects/core/src/main/java/org/gradle/api/services/internal/DefaultBuildServicesRegistry.java
Labels: @configuration-cache, in:build-services

#19385 Ignore flaky IsolatedProjectsToolingApiParallelConfigurationIntegrationTest
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/isolated/IsolatedProjectsToolingApiParallelConfigurationIntegrationTest.groovy
Labels: @dev-productivity

#19386 Ignore flaky BuildScriptCompileAvoidanceIntegrationTest
  subprojects/kotlin-dsl/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/BuildScriptCompileAvoidanceIntegrationTest.kt
Labels: @dev-productivity

#19243 Update sourceSetOutput example to use Provider
  subprojects/plugins/src/main/java/org/gradle/api/tasks/SourceSetOutput.java
Labels: @core

#19384 Move `botGradleGitHubToken` into environment variable
  .teamcity/src/main/kotlin/promotion/PublishGradleDistribution.kt
Labels: @dev-productivity

#19388 Remove spotless plugin
  build-logic/build-platform/build.gradle.kts
  build-logic/buildquality/build.gradle.kts
  build-logic/buildquality/src/main/kotlin/gradlebuild.spotless.gradle.kts
  build-logic/root-build/build.gradle.kts
  build-logic/uber-plugins/src/main/kotlin/gradlebuild.java-library.gradle.kts
Labels: @dev-productivity

#19377 Update gradle-profiler to 0.17.0-alpha12
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleBuildExperimentRunner.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/MavenBuildExperimentRunner.java
Labels: @execution

#19398 Move bot-gradle token to BasePromotionBuildType
  .teamcity/src/main/kotlin/promotion/BasePromotionBuildType.kt
  .teamcity/src/main/kotlin/promotion/PublishGradleDistribution.kt
Labels: @execution

#18904 Fix ordering problems with clean tasks
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/CompositeBuildClassPathInitializer.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultBuildController.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultIncludedBuildTaskGraph.java
  subprojects/composite-builds/src/test/groovy/org/gradle/composite/internal/DefaultIncludedBuildTaskGraphTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/OrdinalNodeCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/TaskInAnotherBuildCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/TaskNodeCodec.kt
  subprojects/core/src/integTest/groovy/org/gradle/api/AbstractCommandLineOrderTaskIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/DestroyerTaskCommandLineOrderIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/ProducerTaskCommandLineOrderIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskParametersIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/composite/internal/BuildTreeWorkGraphController.java
  subprojects/core/src/main/java/org/gradle/composite/internal/TaskIdentifier.java
  subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java
  subprojects/core/src/main/java/org/gradle/execution/plan/ExecutionPlan.java
  subprojects/core/src/main/java/org/gradle/execution/plan/LocalTaskNode.java
  subprojects/core/src/main/java/org/gradle/execution/plan/OrdinalNode.java
  subprojects/core/src/main/java/org/gradle/execution/plan/OrdinalNodeAccess.java
  subprojects/core/src/main/java/org/gradle/execution/plan/TaskInAnotherBuild.java
  subprojects/core/src/main/java/org/gradle/execution/plan/TaskNode.java
  subprojects/core/src/main/java/org/gradle/execution/plan/TaskNodeDependencyResolver.java
  subprojects/core/src/main/java/org/gradle/execution/plan/TaskNodeFactory.java
  subprojects/core/src/main/java/org/gradle/internal/build/BuildWorkGraphController.java
  subprojects/core/src/main/java/org/gradle/internal/build/DefaultBuildWorkGraphController.java
  subprojects/core/src/main/java/org/gradle/internal/build/ExportedTaskNode.java
  subprojects/core/src/test/groovy/org/gradle/execution/plan/DefaultExecutionPlanParallelTest.groovy
  subprojects/core/src/test/groovy/org/gradle/execution/plan/DefaultExecutionPlanTest.groovy
  subprojects/core/src/test/groovy/org/gradle/execution/plan/TaskNodeFactoryTest.groovy
  subprojects/tooling-api-builders/src/main/java/org/gradle/tooling/internal/provider/runner/TestExecutionBuildConfigurationAction.java
Labels: a:bug, @core, in:scheduler

#19397 Let undeclared build service usage nag point to the upgrade guide
  subprojects/core/src/integTest/groovy/org/gradle/api/services/BuildServiceIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/services/internal/BuildServiceProviderNagger.java
  subprojects/docs/src/docs/userguide/extending-gradle/build_services.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/snippets/plugins/buildService/groovy/buildSrc/src/main/java/DownloadPlugin.java
  subprojects/docs/src/snippets/plugins/buildService/kotlin/buildSrc/src/main/java/DownloadPlugin.java
Labels: @configuration-cache, in:build-services

#19374 Track external processes launched through Java/Groovy API
  build-logic/basics/src/main/kotlin/gradlebuild/basics/BuildEnvironment.kt
  gradle/wrapper/gradle-wrapper.properties
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheExternalProcessInstrumentationIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheExternalProcessIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/fixtures/ExternalProcessFixture.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/InstrumentedInputAccessListener.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/ConfigurationCacheProblemsListener.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/Workarounds.kt
  subprojects/core/src/integTest/groovy/org/gradle/api/SettingsScriptExecutionIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/ExternalProcessStartedListener.java
  subprojects/core/src/main/java/org/gradle/groovy/scripts/DefaultScript.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/Instrumented.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingTransformer.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/BuildScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GradleUserHomeScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/ProjectScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/session/BuildSessionScopeServices.java
  subprojects/core/src/main/java/org/gradle/process/internal/DefaultExecActionFactory.java
  subprojects/core/src/main/java/org/gradle/process/internal/DefaultExecHandle.java
  subprojects/core/src/main/java/org/gradle/process/internal/ExecFactory.java
  subprojects/core/src/main/java/org/gradle/process/internal/worker/DefaultWorkerProcess.java
  subprojects/core/src/test/groovy/org/gradle/internal/classpath/DefaultCachedClasspathTransformerTest.groovy
  subprojects/core/src/test/groovy/org/gradle/process/internal/DefaultExecActionFactoryTest.groovy
  subprojects/core/src/test/groovy/org/gradle/process/internal/DefaultExecHandleSpec.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/api/internal/file/TestFiles.java
  subprojects/core/src/testFixtures/groovy/org/gradle/process/ShellScript.groovy
  subprojects/model-core/src/integTest/groovy/org/gradle/api/provider/ProcessOutputProviderIntegrationTest.groovy
  subprojects/process-services/src/main/java/org/gradle/process/internal/ExecHandleListener.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/WorkerDaemonServer.java
Labels: @configuration-cache

#19387 Shorten vendor name for Adoptiumopenjdk
  .teamcity/src/main/kotlin/common/JvmVendor.kt
  .teamcity/src/main/kotlin/model/CIBuildModel.kt
Labels: @dev-productivity

#19405 Mark flaky tests
  subprojects/core/src/integTest/groovy/org/gradle/api/DestroyerTaskCommandLineOrderIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/internal/deployment/JavaApplicationDeploymentIntegrationTest.groovy
Labels: @dev-productivity

#19391 Add missing botGradleGitHubToken and GRADLE_ENTERPRISE_ACCESS_KEY to release6x
  .teamcity/src/main/kotlin/promotion/BasePromotionBuildType.kt
  .teamcity/src/main/kotlin/promotion/PublishGradleDistribution.kt
Labels: @dev-productivity

#19399 Add additional tests for file change detection from timestamp
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/changedetection/state/UpToDateIntegTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/changedetection/state/BuildSessionScopeFileTimeStampInspectorTest.groovy
Labels: @execution

#19404 Track FileInputStream as input
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOptionsIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/InstrumentedInputAccessListener.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/UndeclaredBuildInputListener.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintController.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintWriter.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/Workarounds.kt
  subprojects/core/src/main/java/org/gradle/internal/classpath/Instrumented.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingTransformer.java
  subprojects/core/src/test/groovy/org/gradle/internal/classpath/DefaultCachedClasspathTransformerTest.groovy
Labels: @configuration-cache

#19411 Mention _Shared Build Services_ as a promoted feature in the release notes
  subprojects/docs/src/docs/release/notes.md
Labels: @configuration-cache

#19413 Pin setup-java to v2
  .github/workflows/codeql-analysis.yml
Labels: in:building-gradle

#19410 Merge release
  subprojects/core/src/integTest/groovy/org/gradle/api/DestroyerTaskCommandLineOrderIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/services/BuildServiceIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/services/internal/BuildServiceProviderNagger.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultResolvedDependency.java
  subprojects/docs/src/docs/userguide/extending-gradle/build_services.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/snippets/plugins/buildService/groovy/buildSrc/src/main/java/DownloadPlugin.java
  subprojects/docs/src/snippets/plugins/buildService/kotlin/buildSrc/src/main/java/DownloadPlugin.java
  subprojects/plugins/src/integTest/groovy/org/gradle/internal/deployment/JavaApplicationDeploymentIntegrationTest.groovy
Labels: @dev-productivity

#19415 Fix flakiness in destroyer command line ordering test
  subprojects/core/src/integTest/groovy/org/gradle/api/DestroyerTaskCommandLineOrderIntegrationTest.groovy
Labels: a:bug

#19412 Make `expectDocumentedDeprecationWarning` less error-prone
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/ExclusiveVariantsIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/AbstractGradleExecuter.java
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestTaskIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testsuites/TestSuitesIntegrationTest.groovy
Labels: a:chore

#19420 Mention Task.usesService requirement in BuildServiceSpec.maxParallelUsages
  subprojects/core-api/src/main/java/org/gradle/api/services/BuildServiceRegistration.java
  subprojects/core-api/src/main/java/org/gradle/api/services/BuildServiceSpec.java
Labels: a:documentation

#19051 Specify gradlew Linux start script line ending in generated .gitattributes
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/GitAttributesGenerator.java
Labels: in:build-init-plugin

#19233 Docs - Small improvement to supported custom Attribute types
  subprojects/docs/src/docs/userguide/dep-man/04-modeling-features/variant_attributes.adoc
Labels: in:dependency-declarations

#18754 Check if the sourceSetDir is null. Use empty set instead.
  subprojects/antlr/src/main/java/org/gradle/api/plugins/antlr/internal/AntlrSpecFactory.java
  subprojects/antlr/src/test/groovy/org/gradle/api/plugins/antlr/internal/AntlrSpecFactoryTest.groovy
Labels: in:antlr-plugin

#19431 Enforce naming pattern for version catalogs
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/CatalogPluginsKotlinDSLIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/TomlDependenciesExtensionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/VersionCatalogExtensionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/internal/management/DefaultVersionCatalogBuilderContainer.java
  subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/platforms.adoc
  subprojects/docs/src/snippets/dependencyManagement/catalogs-settings/groovy/settings.gradle
  subprojects/docs/src/snippets/dependencyManagement/catalogs-settings/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/catalogs-toml/groovy/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/catalogs-toml/groovy/settings.gradle
  subprojects/docs/src/snippets/dependencyManagement/catalogs-toml/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/catalogs-toml/kotlin/settings.gradle.kts
Labels: in:dependency-version-catalog

#19438 Rebaseline failing performance tests
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationCachePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIncrementalExecutionPerformanceTest.groovy
Labels: @dev-productivity

#19441 Rebaseline two scenarios
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidStudioMockupPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingJavaPerformanceTest.groovy
Labels: @dev-productivity

#19260 Fix for binary store errors caused by corner cases of conflict resolution
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/capabilities/CapabilitiesRulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/ComponentReplacementIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/DependencyGraphBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/EdgeState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ModuleResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/NodeState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ResolutionConflictTracker.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/SelectorState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/conflicts/ConflictContainer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/conflicts/ConflictHandler.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/conflicts/DefaultCapabilitiesConflictHandler.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/conflicts/DefaultConflictHandler.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/conflicts/PotentialConflictFactory.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/conflicts/ConflictContainerTest.groovy
Labels: @core

#19454 Merge release to master
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/ExternalModuleDependencyBundle.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/MinimalExternalModuleDependency.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/VersionCatalog.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/VersionCatalogsExtension.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/DependencyHandler.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/ExternalModuleDependencyVariantSpec.java
  subprojects/core-api/src/main/java/org/gradle/api/attributes/Usage.java
  subprojects/core-api/src/main/java/org/gradle/api/initialization/dsl/VersionCatalogBuilder.java
  subprojects/core-api/src/main/java/org/gradle/api/initialization/resolve/MutableVersionCatalogContainer.java
  subprojects/core-api/src/main/java/org/gradle/api/provider/ProviderConvertible.java
  subprojects/core/src/main/java/org/gradle/api/internal/FeaturePreviews.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/capabilities/CapabilitiesRulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/AbstractVersionCatalogIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/KotlinDslVersionCatalogExtensionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/ComponentReplacementIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementBuildScopeServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/DefaultArtifactDependencyResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/DependencyGraphBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/EdgeState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ModuleResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/NodeState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ResolutionConflictTracker.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/SelectorState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/conflicts/ConflictContainer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/conflicts/ConflictHandler.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/conflicts/DefaultCapabilitiesConflictHandler.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/conflicts/DefaultConflictHandler.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/conflicts/PotentialConflictFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/management/DefaultDependencyResolutionManagement.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/management/DefaultVersionCatalogBuilderContainer.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/conflicts/ConflictContainerTest.groovy
  subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/platforms.adoc
  subprojects/docs/src/snippets/dependencyManagement/catalogs-javaPlatformCatalog/groovy/consumer/settings.gradle
  subprojects/docs/src/snippets/dependencyManagement/catalogs-javaPlatformCatalog/kotlin/consumer/settings.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/catalogs-javaPlatformUsage/groovy/settings.gradle
  subprojects/docs/src/snippets/dependencyManagement/catalogs-javaPlatformUsage/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/catalogs-settings/groovy/settings.gradle
  subprojects/docs/src/snippets/dependencyManagement/catalogs-settings/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/catalogs-toml/groovy/buildSrc/settings.gradle
  subprojects/docs/src/snippets/dependencyManagement/catalogs-toml/groovy/settings.gradle
  subprojects/docs/src/snippets/dependencyManagement/catalogs-toml/kotlin/buildSrc/settings.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/catalogs-toml/kotlin/settings.gradle.kts
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/FeaturePreviewsFixture.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidStudioMockupPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ExcludeRuleMergingPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaFirstUsePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIDEModelPerformanceTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/catalog/VersionCatalogResolveIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/catalog/CatalogPluginExtension.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/catalog/VersionCatalogPlugin.java
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testsuites/TestSuitesDependenciesIntegrationTest.groovy
Labels: @dev-productivity

#19455 Increase timeout to 180 min for FlakyTestQuarantine builds
  .teamcity/src/main/kotlin/configurations/FlakyTestQuarantine.kt
Labels: @dev-productivity

#19462 Use new VCS roots
  .teamcity/src/main/kotlin/common/extensions.kt
  .teamcity/src/main/kotlin/configurations/GradleBuildConfigurationDefaults.kt
Labels: @dev-productivity
