Repository gradle/gradle, pull requests merged in 2021-09, with the labels that each got.

#18063 Do not start watching unsupported file system
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/WatchedDirectoriesFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DefaultFileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WatchableHierarchies.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystemTest.groovy
  subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/file/TestNameTestDirectoryProvider.java
Labels: @execution

#17861 Disable incremental Kotlin compiler when running on Java 17
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradlePropertiesLoader.java
Labels: @core

#18162 Keep test distribution plugin compatible with untracked task properties
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/PropertyVisitor.java
Labels: @execution

#18169 Add a small note to the clean-up local cache directory part in user m…
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/build-cache/build_cache.adoc
Labels: @execution

#18180 Upgrade tested AGP versions
  gradle/dependency-management/agp-versions.properties
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerCachingSmokeTest.groovy
Labels: in:android-support, @configuration-cache

#18181 Upgradlew to latest nightly
  gradle/wrapper/gradle-wrapper.properties
Labels: in:building-gradle, @configuration-cache

#18145 Improve Provider/Property javadoc
  subprojects/core-api/src/main/java/org/gradle/api/file/DirectoryProperty.java
  subprojects/core-api/src/main/java/org/gradle/api/file/RegularFileProperty.java
  subprojects/core-api/src/main/java/org/gradle/api/provider/Property.java
  subprojects/core-api/src/main/java/org/gradle/api/provider/Provider.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/DefaultFilePropertyFactory.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/DefaultProperty.java
  subprojects/model-core/src/test/groovy/org/gradle/api/internal/provider/DefaultPropertyTest.groovy
Labels: a:documentation

#18194 Remove `GradleKotlinDslBuildPerformanceTest`
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/kotlindsl/GradleKotlinDslBuildPerformanceTest.groovy
Labels: a:chore

#18190 Unignore or remove @Ignored tests
  subprojects/language-native/src/integTest/groovy/org/gradle/language/AbstractNativeLanguageIncrementalBuildIntegrationTest.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/language/AbstractNativeLanguageIntegrationTest.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/language/objectivec/ObjectiveCLanguageIncrementalBuildIntegrationTest.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/language/rc/WindowsResourcesIntegrationTest.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/language/swift/SwiftIncrementalBuildIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/CancellationContinuousIntegrationTest.groovy
Labels: @dev-productivity

#18157 Split GradleBuildConfigurationCacheSmokeTest and increase parallelism
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractGradleBuildConfigurationCacheSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildBinaryDistributionConfigurationCacheSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildCheckBinaryCompatibilityConfigurationCacheSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildCodeQualityConfigurationCacheSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildConfigurationCacheSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildCrossVersionTestConfigurationCacheSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildDocumentationConfigurationCacheSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildIntegTestConfigurationCacheSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildSmokeTestConfigurationCacheSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildSoakTestConfigurationCacheSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildUnitTestConfigurationCacheSmokeTest.groovy
Labels: @dev-productivity

#18204 Fix GradleBuildJvmSpec & remove non-LTS Java versions from start parameter
  .teamcity/src/main/kotlin/common/JvmVersion.kt
  .teamcity/src/test/kotlin/ApplyDefaultConfigurationTest.kt
  .teamcity/src/test/kotlin/PerformanceTestBuildTypeTest.kt
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractGradleceptionSmokeTest.groovy
Labels: @dev-productivity

#18210 Improve failure message for failure.assertHas{Description,Cause}
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/OutputScrapingExecutionFailure.java
  subprojects/internal-integ-testing/src/test/groovy/org/gradle/integtests/fixtures/executer/OutputScrapingExecutionFailureTest.groovy
Labels: @execution

#17658 Catch and log exceptions thrown by toString when printing properties
  subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/internal/PropertyReportRenderer.java
  subprojects/diagnostics/src/test/groovy/org/gradle/api/tasks/diagnostics/internal/PropertyReportRendererTest.groovy
  subprojects/diagnostics/src/test/groovy/org/gradle/api/tasks/diagnostics/internal/PropertyReportRendererTest.java
Labels: @core

#18172 Add more tests for untracked task properties
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/UntrackedPropertiesIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/DefaultTypeMetadataStore.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformValuesInjectionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementGlobalScopeServices.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CaptureStateAfterExecutionStepTest.groovy
  subprojects/model-core/src/test/groovy/org/gradle/internal/reflect/validation/ValidationMessageCheckerTest.groovy
  subprojects/model-core/src/testFixtures/groovy/org/gradle/internal/reflect/validation/ValidationMessageChecker.groovy
Labels: @execution

#18220 Remove unnecessary adapter methods
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/PropertyVisitor.java
Labels: @execution

#18217 Re-split quick cross version tests
  .teamcity/src/main/kotlin/model/CIBuildModel.kt
  .teamcity/src/main/kotlin/model/FunctionalTestBucketProvider.kt
  .teamcity/src/test/kotlin/CIConfigIntegrationTests.kt
Labels: @dev-productivity

#18254 Invalidate the VFS for untracked task outputs
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/UntrackedPropertiesIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/TaskExecution.java
Labels: @execution

#18231 Add Copy. ignoreExistingContentInDestinationDir()
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyPermissionsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopySpecIntegrationSpec.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/TaskExecution.java
  subprojects/core/src/main/java/org/gradle/api/tasks/Copy.java
  subprojects/docs/src/docs/dsl/org.gradle.api.tasks.Copy.xml
  subprojects/docs/src/docs/userguide/authoring-builds/working_with_files.adoc
  subprojects/docs/src/snippets/files/deployWarWithCopy/groovy/build.gradle
  subprojects/docs/src/snippets/files/deployWarWithCopy/groovy/settings.gradle
  subprojects/docs/src/snippets/files/deployWarWithCopy/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/files/deployWarWithCopy/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/files/deployWarWithCopy/tests/deployWarWithCopy.sample.conf
  subprojects/docs/src/snippets/files/installExecutable/groovy/build.gradle
  subprojects/docs/src/snippets/files/installExecutable/groovy/settings.gradle
  subprojects/docs/src/snippets/files/installExecutable/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/files/installExecutable/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/files/installExecutable/tests/installExecutable.sample.conf
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy
Labels: @execution

#18222 Fix functional tests generated by build-init to be rerunnable
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/GroovyGradlePluginInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/JavaGradlePluginInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/KotlinGradlePluginInitIntegrationTest.groovy
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/plugin/groovy/spock/PluginFunctionalTest.groovy.template
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/plugin/java/junit/PluginFunctionalTest.java.template
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/plugin/kotlin/kotlintest/PluginFunctionalTest.kt.template
Labels: in:build-init-plugin, a:bug

#18184 Let `sanityCheck` work with the configuration cache enabled
  build-logic-commons/code-quality/src/main/kotlin/gradlebuild.code-quality.gradle.kts
  build-logic-commons/code-quality/src/main/kotlin/gradlebuild/classycle/tasks/Classycle.kt
  build-logic/build-platform/build.gradle.kts
  build-logic/documentation/src/main/groovy/gradlebuild/docs/GradleJavadocsPlugin.java
  gradle/verification-metadata.xml
  subprojects/docs/src/snippets/developingPlugins/publishingPlugins/groovy/build.gradle
  subprojects/docs/src/snippets/developingPlugins/publishingPlugins/kotlin/build.gradle.kts
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildCheckBinaryCompatibilityConfigurationCacheSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildCodeQualityConfigurationCacheSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildSanityCheckConfigurationCacheSmokeTest.groovy
Labels: in:building-gradle, @configuration-cache

#18278 Update SnapshotTaskInputsBuildOperationResult to convey new attributes, and do not visit empty directories when the strategy doesn't care
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/tasks/SnapshotTaskInputsOperationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/SnapshotTaskInputsBuildOperationResult.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/SnapshotTaskInputsBuildOperationType.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/TaskExecution.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/SnapshotTaskInputsBuildOperationResultTest.groovy
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/FingerprintingStrategy.java
Labels: @execution

#18268 modify the variable name specification to Camel-Case
  subprojects/core/src/main/java/org/gradle/groovy/scripts/DefaultScript.java
Labels: a:chore

#18286 Refine non-empty directory error messages
  build-logic/buildquality/src/main/kotlin/gradlebuild.ci-reporting.gradle.kts
Labels: @dev-productivity

#18309 Stricter gradleception CC smoke tests
  build-logic/build-platform/build.gradle.kts
  build-logic/performance-testing/src/main/groovy/gradlebuild/performance/generator/tasks/RemoteProject.groovy
  build-logic/performance-testing/src/main/kotlin/gradlebuild/performance/tasks/BuildCommitDistribution.kt
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractGradleBuildConfigurationCacheSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildSanityCheckConfigurationCacheSmokeTest.groovy
Labels: in:building-gradle, @configuration-cache

#18297 Add documentation and release notes for Untracked
  subprojects/core-api/src/main/java/org/gradle/api/tasks/Untracked.java
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyPermissionsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopySpecIntegrationSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/UnreadableCopyDestinationFixture.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/TaskExecution.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/authoring-builds/more_about_tasks.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/snippets/tasks/incrementalBuild-incrementalBuildAdvanced/groovy/build.gradle
  subprojects/docs/src/snippets/tasks/incrementalBuild-incrementalBuildAdvanced/groovy/buildSrc/src/main/java/org/example/GitClone.java
  subprojects/docs/src/snippets/tasks/incrementalBuild-incrementalBuildAdvanced/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/tasks/incrementalBuild-incrementalBuildAdvanced/kotlin/buildSrc/src/main/java/org/example/GitClone.java
  subprojects/docs/src/snippets/tasks/incrementalBuild-incrementalBuildAdvanced/tests/incrementalBuildGitClone.sample.conf
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy
Labels: @execution

#18300 Add IgnoreEmptyDirectories to task inputs.
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/tasks/JacocoMerge.java
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/tasks/JacocoReportBase.java
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/DefaultPrecompiledScriptPluginsSupport.kt
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/tasks/CompilePrecompiledScriptPluginPlugins.kt
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/tasks/ExtractPrecompiledScriptPluginPlugins.kt
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/tasks/GeneratePrecompiledScriptPluginAccessors.kt
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/tasks/GenerateScriptPluginAdapters.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/resolver/FindGradleSources.kt
  subprojects/language-java/src/main/java/org/gradle/external/javadoc/MinimalJavadocOptions.java
Labels: @execution

#18205 Probe watched locations
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/BuildInitPluginIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultConfigurationCache.kt
  subprojects/core/src/integTest/groovy/org/gradle/process/internal/CancellationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/execution/plan/ValuedVfsHierarchy.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java
  subprojects/file-watching/build.gradle.kts
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesBetweenBuildsFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesDuringTheBuildFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/WatchedDirectoriesFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherProbeRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/SnapshotCollectingDiffListener.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/CheckIfNonEmptySnapshotVisitor.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DarwinFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DefaultFileWatcherProbeRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DefaultFileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/LinuxFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/SnapshotWatchedDirectoryFinder.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WatchableHierarchies.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WatchedHierarchies.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WindowsFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/DefaultFileSystemWatchingStatistics.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/LocationsWrittenByCurrentBuild.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/WatchedHierarchiesTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/SnapshotWatchedDirectoryFinderTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystemTest.groovy
  subprojects/files/src/main/java/org/gradle/internal/file/DefaultFileHierarchySet.java
  subprojects/files/src/main/java/org/gradle/internal/file/FileHierarchySet.java
  subprojects/files/src/test/groovy/org/gradle/internal/file/DefaultFileHierarchySetTest.groovy
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunner.java
  subprojects/launcher/src/test/groovy/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunnerTest.groovy
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/impl/DefaultFileSystemLocationFingerprint.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/AbstractFileSystemLocationSnapshot.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/AbstractIncompleteFileSystemNode.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/AbstractListChildMap.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/ChildMap.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/DirectorySnapshot.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/EmptyChildMap.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/ReadOnlyFileSystemNode.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SingletonChildMap.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SnapshotHierarchy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultSnapshotHierarchy.java
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/AbstractFileSystemNodeWithChildrenTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/DirectoryNodeTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/vfs/impl/DefaultSnapshotHierarchyTest.groovy
  subprojects/snapshots/src/testFixtures/groovy/org/gradle/internal/snapshot/TestSnapshotFixture.groovy
Labels: @execution

#18318 Multi-framework coverage for test-suites
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testsuites/TestSuitesTestFrameworkIntegrationTest.groovy
Labels: @core

#18333 Avoid the use of tasks.matching in gradle/gradle build-logic
  build-logic-commons/code-quality/src/main/kotlin/gradlebuild.code-quality.gradle.kts
Labels: @core

#18330 Update to latest nightly
  gradle/wrapper/gradle-wrapper.properties
Labels: @core

#18337 Upgrade spotless to 5.15.1
  build-logic/build-platform/build.gradle.kts
  gradle/verification-metadata.xml
Labels: in:building-gradle, @configuration-cache

#18331 Fail when stating unreadable files
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/UntrackedPropertiesIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/TaskExecution.java
  subprojects/native/src/main/java/org/gradle/internal/nativeintegration/filesystem/jdk7/NioFileMetadataAccessor.java
  subprojects/native/src/main/java/org/gradle/internal/nativeintegration/filesystem/services/FallbackFileMetadataAccessor.java
  subprojects/native/src/main/java/org/gradle/internal/nativeintegration/filesystem/services/NativePlatformBackedFileMetadataAccessor.java
  subprojects/native/src/test/groovy/org/gradle/internal/nativeintegration/filesystem/services/AbstractFileMetadataAccessorTest.groovy
Labels: @execution

#18332 Code cleanup around file system watching
  subprojects/core/src/main/java/org/gradle/internal/file/DefaultReservedFileSystemLocationRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DefaultFileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WatchableHierarchies.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/LocationsWrittenByCurrentBuild.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/WatchedHierarchiesTest.groovy
  subprojects/files/src/main/java/org/gradle/internal/file/DefaultFileHierarchySet.java
  subprojects/files/src/main/java/org/gradle/internal/file/FileHierarchySet.java
  subprojects/files/src/test/groovy/org/gradle/internal/file/FileHierarchySetTest.groovy
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/DefaultGlobalCacheLocations.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SnapshotHierarchy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/VirtualFileSystem.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultSnapshotHierarchy.java
  subprojects/snapshots/src/test/groovy/org/gradle/internal/vfs/impl/DefaultSnapshotHierarchyTest.groovy
Labels: @execution

#18334 De-incubate DisableCachingByDefault
  subprojects/core-api/src/main/java/org/gradle/work/DisableCachingByDefault.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/build-cache/build_cache.adoc
Labels: @execution

#18345 Move Santa Tracker smoke tests to separate santaTrackerSmokeTest task
  .teamcity/src/main/kotlin/common/JvmCategory.kt
  .teamcity/src/main/kotlin/model/CIBuildModel.kt
  subprojects/smoke-test/build.gradle.kts
Labels: in:building-gradle, @configuration-cache

#18360 Disable TaskTimeoutIntegrationTest for noDaemon runner
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskTimeoutIntegrationTest.groovy
Labels: @dev-productivity

#18315 Refine test dir cleanup actions
  build-logic/buildquality/src/main/kotlin/gradlebuild.ci-reporting.gradle.kts
Labels: @dev-productivity

#18257 Move artifactType attribute to the public API
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/LocalFileDependencyBackedArtifactSetCodec.kt
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/type/ArtifactTypeDefinition.java
  subprojects/core/src/main/java/org/gradle/api/internal/artifacts/ArtifactAttributes.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/DefaultDependencyHandler.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/type/DefaultArtifactTypeRegistry.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/DefaultArtifactTransformsTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/type/DefaultArtifactTypeRegistryTest.groovy
  subprojects/language-native/src/main/java/org/gradle/language/cpp/internal/DefaultCppBinary.java
  subprojects/language-native/src/main/java/org/gradle/language/cpp/internal/DefaultCppLibrary.java
  subprojects/language-native/src/main/java/org/gradle/language/plugins/NativeBasePlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java
Labels: @core

#18320 Non-inheritance of dependencies for test-suites
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testsuites/TestSuitesDependenciesIntegrationTest.groovy
Labels: @core

#18148 Upgrade embedded Kotlin version to 1.5.31
  build-logic-commons/code-quality/build.gradle.kts
  build-logic-commons/gradle-plugin/build.gradle.kts
  build-logic/basics/src/main/kotlin/gradlebuild/basics/accessors/accessors.kt
  build-logic/basics/src/main/kotlin/gradlebuild/basics/util/KotlinSourceParser.kt
  build-logic/build-platform/build.gradle.kts
  build-logic/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
  build-logic/kotlin-dsl/src/main/kotlin/gradlebuild.kotlin-dsl-dependencies-embedded.gradle.kts
  gradle/verification-metadata.xml
  gradle/wrapper/gradle-wrapper.properties
  subprojects/base-services-groovy/src/main/java/org/gradle/groovy/scripts/internal/AbstractScriptTransformer.java
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/library-versions.properties
  subprojects/core-api/src/main/java/org/gradle/api/AntBuilder.java
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/AllDistributionIntegrationSpec.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/BinDistributionIntegrationSpec.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DistributionIntegritySpec.groovy
  subprojects/docs/src/docs/userguide/compatibility.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/docsTest/java/org/gradle/docs/samples/BaseSamplesTest.java
  subprojects/docs/src/samples/build-organization/structuring-software-projects/groovy/platforms/plugins-platform/build.gradle
  subprojects/docs/src/samples/build-organization/structuring-software-projects/kotlin/platforms/plugins-platform/build.gradle.kts
  subprojects/docs/src/snippets/java/toolchain-kotlin/groovy/build.gradle
  subprojects/docs/src/snippets/java/toolchain-kotlin/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/androidBuild/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/androidSingleBuild/kotlin/build.gradle.kts
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/NestedInputKotlinImplementationTrackingIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/logging/EmbeddedKotlinOutputNormalizer.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/KotlinGradlePluginVersions.groovy
  subprojects/kotlin-dsl-plugins/build.gradle.kts
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/ClassBytesRepository.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/KotlinCompiler.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/resolver/KotlinBuildScriptModelRepositoryTest.kt
  subprojects/reporting/src/main/java/org/gradle/api/reporting/internal/SimpleReport.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractAndroidSantaTrackerSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidCommunityPluginsSmokeTest.groovy
Labels: in:kotlin-dsl, @configuration-cache

#18362 Use template methods instead of calling super
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdater.java
Labels: @execution

#18377 Fix contributor list
  subprojects/docs/src/docs/release/notes.md
Labels: @execution

#18293 Capture project input normalization rules in configuration cache
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/CachedProjectState.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ProblemReportingCrossProjectModelAccess.kt
  subprojects/core/src/integTest/groovy/org/gradle/normalization/ConfigureRuntimeClasspathNormalizationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProject.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/ProjectInternal.java
  subprojects/core/src/main/java/org/gradle/normalization/internal/DefaultInputNormalizationHandler.java
  subprojects/core/src/main/java/org/gradle/normalization/internal/DefaultRuntimeClasspathNormalization.java
  subprojects/core/src/main/java/org/gradle/normalization/internal/InputNormalizationHandlerInternal.java
  subprojects/core/src/main/java/org/gradle/normalization/internal/RuntimeClasspathNormalizationInternal.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/DefaultProjectTest.groovy
  subprojects/core/src/test/groovy/org/gradle/normalization/internal/DefaultRuntimeClasspathNormalizationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformInputArtifactIntegrationTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildCrossVersionTestConfigurationCacheSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildIntegTestConfigurationCacheSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildSanityCheckConfigurationCacheSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildSmokeTestConfigurationCacheSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildSoakTestConfigurationCacheSmokeTest.groovy
Labels: @configuration-cache

#18379 Update docs to highlight normalization support in configuration cache
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
Labels: @configuration-cache

#18385 Let :docs:dslHtml work with the configuration cache
  build-logic/documentation/src/main/groovy/gradlebuild/docs/Docbook2Xhtml.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildDocumentationConfigurationCacheSmokeTest.groovy
Labels: @configuration-cache

#18340 Move handling of hierarchical watchers to HierarchicalFileWatcherUpdater
  subprojects/docs/src/docs/userguide/running-builds/gradle_daemon.adoc
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/BuildOperationsFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/LoggingFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DefaultFileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/SnapshotCollectingDiffListener.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WindowsFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingNotSupportedVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdaterTest.groovy
  subprojects/files/src/main/java/org/gradle/internal/file/FileHierarchySet.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/FileSystemWatchingFixture.groovy
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/FileSystemNode.java
Labels: @execution

#18326 Update the Javadoc for all new test suite related classes
  subprojects/docs/src/docs/dsl/org.gradle.api.tasks.testing.Test.xml
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JvmTestSuitePlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/ComponentDependencies.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/JvmComponentDependencies.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/JvmTestSuite.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/JvmTestSuiteTarget.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmComponentDependencies.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java
  subprojects/testing-base/src/main/java/org/gradle/testing/base/TestSuite.java
  subprojects/testing-base/src/main/java/org/gradle/testing/base/TestSuiteTarget.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java
Labels: @core

#18393 Use kotlinOptions.kotlinJavaToolchain instead of jdkHome
  build-logic/uber-plugins/src/main/kotlin/gradlebuild.kotlin-library.gradle.kts
Labels: in:building-gradle, @configuration-cache

#18361 Be more silent for watching errors
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WatchableHierarchies.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/WatchMode.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
Labels: @execution

#18383 Announce support for JDK17
  build-logic/build-platform/build.gradle.kts
  build-logic/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/library-versions.properties
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/compatibility.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/samples/groovy/library-publishing/groovy/my-library/build.gradle
  subprojects/docs/src/samples/groovy/library-publishing/kotlin/my-library/build.gradle.kts
  subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/AbstractSourcesAndJavadocJarsIntegrationTest.groovy
  subprojects/model-core/src/test/groovy/org/gradle/model/NodeBackedModelMapSpec.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/tasks/GroovyRuntimeTest.groovy
  subprojects/plugins/src/testFixtures/groovy/org/gradle/api/tasks/compile/AbstractCompileTest.groovy
  subprojects/scala/src/test/groovy/org/gradle/api/tasks/scala/ScalaCompileTest.groovy
  subprojects/scala/src/test/groovy/org/gradle/api/tasks/scala/ScalaDocSpec.groovy
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/enduser/GradleRunnerConsoleInputEndUserIntegrationTest.groovy
Labels: @core

#18389 Fix #18388: TestNG support for test-suites
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/JvmTestSuite.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/fixture/TestNGCoverage.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGConsoleLoggingIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGFailurePolicyIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGLoggingOutputCaptureIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGSuiteInitialisationIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGUpToDateCheckIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testsuites/TestSuitesTestFrameworkIntegrationTest.groovy
Labels: @core

#18391 Add Javadoc for useSpock and useKotlinTest methods
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/JvmTestSuite.java
Labels: @core

#18400 Let Kotlin tasks implicitly use the configured java toolchain
  build-logic/uber-plugins/src/main/kotlin/gradlebuild.kotlin-library.gradle.kts
Labels: in:building-gradle, @configuration-cache

#18401 Pass --no-configuration-cache to all managed TeamCity gradle build types
  .teamcity/src/main/kotlin/common/extensions.kt
  .teamcity/src/test/kotlin/ApplyDefaultConfigurationTest.kt
  .teamcity/src/test/kotlin/PerformanceTestBuildTypeTest.kt
Labels: in:building-gradle, @configuration-cache

#18406 Update to latest 7.3 nightly
  gradle/wrapper/gradle-wrapper.properties
Labels: @core

#18403 Switch CI pipeline to test with Java 17 instead of Java 16
  .teamcity/src/main/kotlin/common/JvmCategory.kt
  .teamcity/src/main/kotlin/common/JvmVersion.kt
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradlePropertiesLoader.java
Labels: @core

#18396 Exclude javadoc/sources jar from DistributionTest classpath
  build-logic/integration-testing/src/main/kotlin/gradlebuild/integrationtests/tasks/DistributionTest.kt
Labels: @dev-productivity

#18423 Fix failed tests after upgrading to JDK 17
  .teamcity/src/test/kotlin/ApplyDefaultConfigurationTest.kt
  .teamcity/src/test/kotlin/PerformanceTestBuildTypeTest.kt
Labels: @dev-productivity

#18421 Split CatalogPluginsKotlinDSLIntegrationTest
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/CatalogPluginApplyKotlinDSLIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/CatalogPluginsKotlinDSLIntegrationTest.groovy
Labels: @dev-productivity

#18442 Print descendants in TestFile.assertDoesNotExist
  subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/file/TestFile.java
Labels: @dev-productivity

#18399 Capture dropping state in the VFS because probes didn't trigger
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/BuildOperationsFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/BuildFinishedFileSystemWatchingBuildOperationType.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
Labels: @execution

#18448 Remove SecurityManagerIntegrationTest
  subprojects/testing-base/src/integTest/groovy/org/gradle/testing/SecurityManagerIntegrationTest.groovy
Labels: @dev-productivity

#18447 Fix failed tests after upgrading to JDK 17
  .teamcity/src/test/kotlin/ApplyDefaultConfigurationTest.kt
  .teamcity/src/test/kotlin/PerformanceTestBuildTypeTest.kt
Labels: @dev-productivity

#18445 Fix some tasks in :docs for the configuration cache
  build-logic/documentation/src/main/groovy/gradlebuild/docs/DecorateReleaseNotes.java
  build-logic/documentation/src/main/groovy/gradlebuild/docs/GenerateDocInfo.java
  subprojects/docs/README.md
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildDocumentationConfigurationCacheSmokeTest.groovy
Labels: in:building-gradle, @configuration-cache

#18443 Polish 7.3 release notes
  subprojects/docs/src/docs/release/notes.md
  subprojects/launcher/src/main/resources/release-features.txt
Labels: @core

#18459 Exclude javadoc jar from DistributionTest classpath
  build-logic/integration-testing/src/main/kotlin/gradlebuild/integrationtests/tasks/DistributionTest.kt
Labels: @dev-productivity

#18457 Revert to TD Gradle plugin to v2.2
  build-logic/build-platform/build.gradle.kts
  settings.gradle.kts
Labels: @dev-productivity

#18455 Clarify impact of enforcedPlatform
  subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/platforms.adoc
Labels: @core

#18462 Use trademark note around Build Scan
  subprojects/docs/src/docs/stylesheets/userGuideHtmlCommon.xsl
  subprojects/docs/src/docs/userguide/userguide.adoc
  subprojects/docs/src/main/resources/footer.html
Labels: @core

#18420 Split PrecompiledScriptPluginAccessorsTest
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/precompiled/PrecompiledScriptPluginAccessorDeprecationWarningsTest.kt
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/precompiled/PrecompiledScriptPluginAccessorSettingEvaluationTest.kt
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/precompiled/PrecompiledScriptPluginAccessorsTest.kt
Labels: @dev-productivity

#18335 First pass at DSL documentation for test suites
  subprojects/docs/src/docs/dsl/dsl.xml
  subprojects/docs/src/docs/dsl/org.gradle.api.plugins.jvm.JvmTestSuite.xml
  subprojects/docs/src/docs/dsl/org.gradle.api.plugins.jvm.JvmTestSuiteTarget.xml
  subprojects/docs/src/docs/dsl/org.gradle.testing.base.TestSuite.xml
  subprojects/docs/src/docs/dsl/org.gradle.testing.base.TestSuiteTarget.xml
  subprojects/docs/src/docs/dsl/org.gradle.testing.base.TestingExtension.xml
  subprojects/docs/src/docs/userguide/authoring-builds/test_kit.adoc
  subprojects/docs/src/docs/userguide/core-plugins/plugin_reference.adoc
  subprojects/docs/src/docs/userguide/developing-plugins/testing_gradle_plugins.adoc
  subprojects/docs/src/docs/userguide/jvm/java_testing.adoc
  subprojects/docs/src/docs/userguide/jvm/jvm_test_suite_plugin.adoc
  subprojects/docs/src/docs/userguide/jvm/test_suite_plugin.adoc
  subprojects/docs/src/snippets/testing/test-suite-configure-default-suite/groovy/build.gradle
  subprojects/docs/src/snippets/testing/test-suite-configure-default-suite/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/testing/test-suite-configure-source-dir/groovy/build.gradle
  subprojects/docs/src/snippets/testing/test-suite-configure-source-dir/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/testing/test-suite-configure-suite-dependencies/groovy/build.gradle
  subprojects/docs/src/snippets/testing/test-suite-configure-suite-dependencies/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/testing/test-suite-plugin/groovy/build.gradle
  subprojects/docs/src/snippets/testing/test-suite-plugin/groovy/src/integrationTest/java/it/IntegrationTest.java
  subprojects/docs/src/snippets/testing/test-suite-plugin/groovy/src/main/java/org/gradle/MyMain.java
  subprojects/docs/src/snippets/testing/test-suite-plugin/groovy/src/test/java/example/UnitTest.java
  subprojects/docs/src/snippets/testing/test-suite-plugin/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/testing/test-suite-plugin/kotlin/src/integrationTest/java/it/IntegrationTest.java
  subprojects/docs/src/snippets/testing/test-suite-plugin/kotlin/src/main/java/org/gradle/MyMain.java
  subprojects/docs/src/snippets/testing/test-suite-plugin/kotlin/src/test/java/example/UnitTest.java
  subprojects/docs/src/snippets/testing/test-suite-plugin/tests/checkTaskOutput.out
  subprojects/docs/src/snippets/testing/test-suite-plugin/tests/checkTaskOutput.sample.conf
Labels: @core

#18347 Scala Toolchains: Configure `-target` compiler flag
  subprojects/scala/build.gradle.kts
  subprojects/scala/src/integTest/groovy/org/gradle/integtests/fixtures/ScalaCoverage.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/AbstractToolchainZincScalaCompileIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/BasicZincScalaCompilerIntegrationTest.groovy
  subprojects/scala/src/main/java/org/gradle/api/plugins/scala/ScalaBasePlugin.java
  subprojects/scala/src/main/java/org/gradle/api/tasks/ScalaRuntime.java
  subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaCompile.java
  subprojects/scala/src/main/java/org/gradle/api/tasks/scala/internal/ScalaCompileOptionsConfigurer.java
  subprojects/scala/src/main/java/org/gradle/api/tasks/scala/internal/ScalaRuntimeHelper.java
  subprojects/scala/src/main/java/org/gradle/language/scala/tasks/AbstractScalaCompile.java
  subprojects/scala/src/test/groovy/org/gradle/api/tasks/ScalaRuntimeTest.groovy
  subprojects/scala/src/test/groovy/org/gradle/api/tasks/scala/internal/ScalaRuntimeHelperTest.groovy
  subprojects/scala/src/test/groovy/org/gradle/scala/compile/internal/ScalaCompileOptionsConfigurerTest.groovy
Labels: @core

#18472 Disable the configuration cache for buildCommitDistribution
  build-logic/performance-testing/src/main/kotlin/gradlebuild/performance/tasks/BuildCommitDistribution.kt
Labels: in:building-gradle, @configuration-cache

#18468 Ignore registrations for BuildOutputCleanupRegistry after finalization
  subprojects/core/src/integTest/groovy/org/gradle/api/ConfigurationOnDemandIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/internal/cleanup/DefaultBuildOutputCleanupRegistry.java
  subprojects/core/src/test/groovy/org/gradle/internal/cleanup/DefaultBuildOutputCleanupRegistryTest.groovy
Labels: @execution

#18451 Capture working dir early
  subprojects/internal-testing/src/main/groovy/org/gradle/testfixtures/internal/NativeServicesTestFixture.java
Labels: @dev-productivity

#18481 Clarify configuration cache ide support in docs
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
Labels: @configuration-cache

#18485 Ensure listener installed by configuration cache is always disposed of
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultConfigurationCache.kt
Labels: @configuration-cache

#18484 Fix BuildOperationTrace with debug on Java 8
  subprojects/core/src/integTest/groovy/org/gradle/initialization/BuildInitializationBuildOperationsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/internal/operations/logging/LoggingBuildOperationProgressIntegTest.groovy
  subprojects/logging/src/main/java/org/gradle/internal/logging/slf4j/OutputEventListenerBackedLoggerContext.java
  subprojects/soak/src/integTest/kotlin/org/gradle/kotlin/dsl/caching/ScriptCachingIntegrationTest.kt
Labels: @dev-productivity
