Repository gradle/gradle, pull requests merged in 2021-10, with the labels that each got.

#18505 Clarify that scaladoc support is not available
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/jvm/scala_plugin.adoc
Labels: in:scala-plugin, @core

#18507 Update wrapper to latest nightly from master
  gradle/wrapper/gradle-wrapper.properties
Labels: @configuration-cache

#18248 Handle scaladoc for Scala3
  gradle/verification-metadata.xml
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/jvm/scala_plugin.adoc
  subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/idea/IdeaIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/scaladoc/ScalaDocIntegrationTest.groovy
  subprojects/scala/src/main/java/org/gradle/api/tasks/ScalaRuntime.java
  subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaDoc.java
  subprojects/scala/src/main/java/org/gradle/api/tasks/scala/internal/GenerateScaladoc.java
  subprojects/scala/src/main/java/org/gradle/api/tasks/scala/internal/ScaladocParameters.java
  subprojects/scala/src/test/groovy/org/gradle/api/plugins/scala/ScalaPlugin3Test.groovy
  subprojects/scala/src/test/groovy/org/gradle/api/plugins/scala/ScalaPluginTest.groovy
  subprojects/scala/src/test/groovy/org/gradle/api/tasks/ScalaRuntimeTest.groovy
Labels: @core

#18533 Let CodeQL workflow disable the configuration cache
  .github/workflows/codeql-analysis.yml
Labels: in:building-gradle, @configuration-cache

#18279 Add restrictions to precompiled plugins so they can't conflict with core plugins
  subprojects/docs/src/docs/userguide/developing-plugins/custom_plugins.adoc
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/PrecompiledScriptPluginIntegrationTest.kt
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/DefaultPrecompiledScriptPluginsSupport.kt
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/plugins/PrecompiledGroovyPluginsIntegrationTest.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/TaskFromPluginValidationIntegrationTest.groovy
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/internal/precompiled/PrecompiledGroovyPluginsPlugin.java
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/internal/precompiled/PrecompiledGroovyScript.java
Labels: @core

#18825 Write `gradleProperty` and `environmentVariable` inputs only once to the configuration cache fingerprint
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOptionsIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultConfigurationCache.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprint.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintChecker.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintController.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintWriter.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/PropertyProblem.kt
  subprojects/core/src/main/java/org/gradle/initialization/GradlePropertiesController.java
Labels: @configuration-cache
