Repository gradle/gradle, pull requests merged in 2021-08, with the labels that each got.

#17761 Migrate publishing to repo.grdev.net
  .teamcity/src/main/kotlin/common/extensions.kt
  build-logic/publishing/src/main/kotlin/gradlebuild.publish-public-libraries.gradle.kts
  gradle.properties
Labels: @dev-productivity

#17915 Publish to repo.grdev.net (Backport to 6.x)
  .teamcity/src/main/kotlin/configurations/BaseGradleBuildType.kt
  .teamcity/src/main/kotlin/promotion/BasePromotionBuildType.kt
  buildSrc/build.gradle.kts
  buildSrc/settings.gradle.kts
  buildSrc/subprojects/basics/src/main/kotlin/gradlebuild.repositories.gradle.kts
  buildSrc/subprojects/publishing/src/main/kotlin/gradlebuild.publish-public-libraries.gradle.kts
  gradle/verification-keyring.gpg
Labels: @dev-productivity

#17928 Add more debug logs around caching and VFS invalidation
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/BuildCacheStep.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WatchedHierarchies.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultSnapshotHierarchy.java
Labels: @execution

#17929 Remove unused field in WatchingVirtualFileSystem
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystemTest.groovy
Labels: @execution

#17931 Polish `SourceDistributionProvider`
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/resolver/SourceDistributionProvider.kt
Labels: @configuration-cache, a:chore

#17935 Polish `ConfigurationCacheFingerprintChecker`
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintChecker.kt
Labels: @configuration-cache, a:chore

#17938 Make `zipTree(provider)` compatible with the configuration cache
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/file/DefaultFileOperations.java
  subprojects/core/src/main/java/org/gradle/api/internal/lambdas/SerializableLambdas.java
Labels: @configuration-cache

#17930 Don't lose task dependencies when zipping against provider with no dependencies
  subprojects/model-core/src/integTest/groovy/org/gradle/api/provider/ProviderIntegrationTest.groovy
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/ValueSupplier.java
Labels: @configuration-cache

#17913 Prepare 6.9.1 bugfix release
  released-versions.json
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  version.txt
Labels: @execution

#17898 Add full compile classpath of a sourceset to PMD's auxclasspath
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/pmd/PmdPluginAuxclasspathIntegrationTest.groovy
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdPlugin.java
Labels: @core

#17944 Backport: Don't lose task dependencies when zipping against provider with no dependencies
  subprojects/model-core/src/integTest/groovy/org/gradle/api/provider/ProviderIntegrationTest.groovy
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/ValueSupplier.java
Labels: @configuration-cache

#17922 Fix renaming project directory causing lost file system notifications on Windows
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesBetweenBuildsFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DarwinFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DefaultFileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/LinuxFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WindowsFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystemTest.groovy
Labels: @execution

#17834 Catch exception if settings not available
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationSpec.groovy
Labels: @dev-productivity

#17941 Use newer native platform version (Backport to 6.x)
  gradle/verification-metadata.xml
  subprojects/distributions-dependencies/build.gradle.kts
Labels: @execution

#17943 Backport: Let configuration cache ignore convention values of incompatible type
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheConventionMappingIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/beans/BeanPropertyWriter.kt
Labels: @configuration-cache

#17852 Add Maven Relocation section to "Maven Publish Plugin" userguide
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/dep-man/04-modeling-features/component_capabilities.adoc
  subprojects/docs/src/docs/userguide/dep-man/06-publishing/publishing_maven.adoc
  subprojects/docs/src/snippets/maven-publish/specify-relocation/groovy/library/build.gradle
  subprojects/docs/src/snippets/maven-publish/specify-relocation/groovy/settings.gradle
  subprojects/docs/src/snippets/maven-publish/specify-relocation/kotlin/library/build.gradle.kts
  subprojects/docs/src/snippets/maven-publish/specify-relocation/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/maven-publish/specify-relocation/tests/publish-specify-relocation.sample.conf
Labels: 🌱 onboarding, @support

#17952 Compile everything in compileAllProduction
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
Labels: @dev-productivity

#17957 Merge release into master
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/pmd/PmdPluginAuxclasspathIntegrationTest.groovy
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdPlugin.java
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/file/DefaultFileOperations.java
  subprojects/core/src/main/java/org/gradle/api/internal/lambdas/SerializableLambdas.java
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesBetweenBuildsFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DarwinFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DefaultFileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/LinuxFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WindowsFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystemTest.groovy
Labels: @configuration-cache

#17725 Fix wrong metadata cache version in `dependency_resolution` page
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/dependency_resolution.adoc
Labels: 🌱 onboarding, @support

#17995 Rebaseline performance tests where baseline versions are missing
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/AndroidIncrementalExecutionPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/inception/BuildSrcApiChangePerformanceTest.groovy
Labels: @dev-productivity

#12816 Run JVM test classes in a reproducible order
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/DefaultTestOrderingIntegrationTest.groovy
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/detection/DefaultTestClassScanner.java
Labels: in:testing

#17864 Let Kotlin DSL precompiled scripts support work without a configuration task
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/initialization/loadercache/ClassLoadersCachingIntegrationTest.groovy
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/PrecompiledScriptPluginIntegrationTest.kt
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/DefaultPrecompiledScriptPluginsSupport.kt
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/tasks/ConfigurePrecompiledScriptDependenciesResolver.kt
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/tasks/SharedAccessorsPackageAware.kt
Labels: in:kotlin-dsl, @configuration-cache

#17876 Normalize `java.io.tmpdir` in TAPI tests.
  .teamcity/src/main/kotlin/model/FunctionalTestBucketGenerator.kt
  .teamcity/test-buckets.json
  subprojects/core/src/integTest/groovy/org/gradle/NativeServicesIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/AbstractGradleExecuter.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/GradleExecuter.java
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r22/ClientShutdownCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r64/DaemonReuseCrossVersionSpec.groovy
Labels: @dev-productivity

#18023 Treat pre test as master/release
  buildSrc/subprojects/performance-testing/src/main/kotlin/gradlebuild/performance/tasks/DetermineBaselines.kt
Labels: @dev-productivity

#17953 Backport to 6.9: Fix renaming project directory causing lost file system notifications on Windows
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesBetweenBuildsFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DarwinFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DefaultFileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/LinuxFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WindowsFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystemTest.groovy
Labels: @execution

#18008 Don't read the whole distribution into memory
  subprojects/tooling-api/src/integTest/groovy/org/gradle/integtests/tooling/ToolingApiRemoteIntegrationTest.groovy
Labels: @dev-productivity

#17748 Restore full incrementality for Micronaut annotation processor
  subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/ApiGroovyCompiler.java
  subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/GroovyRecompilationSpecProvider.java
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/AggregatingIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/IsolatingIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/BaseJavaClassChangeIncrementalCompilationIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/GroovyJavaJointIncrementalCompilationIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/processing/AnnotationProcessingData.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/CurrentCompilation.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/DefaultSourceFileClassNameConverter.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/FileNameDerivingClassNameConverter.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/JavaRecompilationSpecProvider.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/PreviousCompilation.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/RecompilationSpec.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/SourceFileChangeProcessor.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/SourceFileClassNameConverter.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/WellKnownSourceFileClassNameConverter.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisTest.groovy
  subprojects/language-java/src/testFixtures/groovy/org/gradle/language/fixtures/AnnotationProcessorFixture.groovy
  subprojects/language-java/src/testFixtures/groovy/org/gradle/language/fixtures/HelperProcessorFixture.groovy
  subprojects/language-java/src/testFixtures/groovy/org/gradle/language/fixtures/ServiceRegistryProcessorFixture.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesJavaIncrementalAnnotationProcessingIntegrationTest.groovy
Labels: @execution

#18040 Add Stefan Oehme as contributor
  subprojects/docs/src/docs/release/notes.md
Labels: @execution

#18048 Fix warnings in `UpdateInitPluginTemplateVersionFile`
  build-logic/build-update-utils/src/main/kotlin/gradlebuild/buildutils/tasks/UpdateInitPluginTemplateVersionFile.kt
Labels: a:chore

#17789 Improve comparing fingerprint strategies in DefaultCurrentFileCollectionFingerprint
  subprojects/execution/src/main/java/org/gradle/internal/execution/history/impl/DefaultExecutionHistoryStore.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/history/impl/FileCollectionFingerprintSerializer.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/history/impl/SerializableFileCollectionFingerprint.java
  subprojects/execution/src/testFixtures/groovy/org/gradle/internal/execution/TestExecutionHistoryStore.java
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/CurrentFileCollectionFingerprint.java
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/FileCollectionFingerprint.java
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/impl/AbstractFingerprintingStrategy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/impl/DefaultCurrentFileCollectionFingerprint.java
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/impl/EmptyCurrentFileCollectionFingerprint.java
Labels: @execution

#18059 Fix VCS root id in pull request feature
  .teamcity/src/main/kotlin/configurations/GradleBuildConfigurationDefaults.kt
  .teamcity/src/main/kotlin/configurations/SanityCheck.kt
Labels: @dev-productivity

#18061 Use credentials defined in Root project
  .teamcity/src/main/kotlin/promotion/PromotionProject.kt
Labels: @dev-productivity

#18043 Re-enable config cache smoke tests
  subprojects/jvm-services/build.gradle.kts
  subprojects/jvm-services/src/main/java/org/gradle/internal/jvm/inspection/JvmInstallationMetadata.java
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/DefaultPrecompiledScriptPluginsSupport.kt
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractGradleceptionSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildConfigurationCacheSmokeTest.groovy
Labels: @configuration-cache

#17757 Remove usage of legacy JUnit 4 rules in Spock examples
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.build-logic.groovy-dsl-gradle-plugin.gradle.kts
  build-logic/binary-compatibility/src/test/groovy/gradlebuild/binarycompatibility/AcceptedApiChangesJsonFileManagerTest.groovy
  build-logic/binary-compatibility/src/test/groovy/gradlebuild/binarycompatibility/PublicAPIRulesTest.groovy
  build-logic/build-update-utils/src/test/groovy/gradlebuild/buildutils/tasks/UpdateReleasedVersionsIntegrationTest.groovy
  build-logic/documentation/src/test/groovy/gradlebuild/docs/model/SimpleClassMetaDataRepositoryTest.groovy
  subprojects/build-init/src/test/groovy/org/gradle/buildinit/plugins/internal/SimpleTemplateOperationSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/testfixtures/ProjectBuilderEndUserIntegrationTest.groovy
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/groovy/buildSrc/build.gradle
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/groovy/buildSrc/src/test/groovy/com/example/JavaConventionPluginTest.groovy
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/groovy/buildSrc/src/test/groovy/com/example/LibraryPluginTest.groovy
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/groovy/buildSrc/src/test/groovy/com/example/PluginTest.groovy
  subprojects/docs/src/samples/build-organization/publishing-convention-plugins/groovy/convention-plugins/build.gradle
  subprojects/docs/src/samples/build-organization/publishing-convention-plugins/groovy/convention-plugins/src/test/groovy/com/myorg/JavaConventionPluginTest.groovy
  subprojects/docs/src/samples/build-organization/publishing-convention-plugins/groovy/convention-plugins/src/test/groovy/com/myorg/LibraryPluginTest.groovy
  subprojects/docs/src/samples/build-organization/publishing-convention-plugins/groovy/convention-plugins/src/test/groovy/com/myorg/PluginTest.groovy
  subprojects/docs/src/samples/build-organization/publishing-convention-plugins/groovy/convention-plugins/src/test/groovy/com/myorg/ServicePluginTest.groovy
  subprojects/docs/src/snippets/configurationCache/testKit/groovy/build.gradle
  subprojects/docs/src/snippets/configurationCache/testKit/groovy/src/test/groovy/org/example/BuildLogicFunctionalTest.groovy
  subprojects/docs/src/snippets/developingPlugins/testingPlugins/groovy/url-verifier-plugin/build.gradle
  subprojects/docs/src/snippets/developingPlugins/testingPlugins/groovy/url-verifier-plugin/src/functionalTest/groovy/org/myorg/UrlVerifierPluginFunctionalTest.groovy
  subprojects/docs/src/snippets/developingPlugins/testingPlugins/kotlin/url-verifier-plugin/build.gradle.kts
  subprojects/docs/src/snippets/developingPlugins/testingPlugins/kotlin/url-verifier-plugin/src/functionalTest/groovy/org/myorg/UrlVerifierPluginFunctionalTest.groovy
  subprojects/ide/src/test/groovy/org/gradle/plugins/ide/eclipse/model/internal/SourceFoldersCreatorTest.groovy
  subprojects/internal-performance-testing/src/integTest/groovy/org/gradle/performance/fixture/MavenDownloaderTest.groovy
  subprojects/java-compiler-plugin/src/test/groovy/com/gradle/internal/compiler/java/AbstractCompilerPluginTest.groovy
  subprojects/java-compiler-plugin/src/test/groovy/com/gradle/internal/compiler/java/listeners/ConstantsCollectorTest.groovy
  subprojects/jvm-services/src/test/groovy/org/gradle/internal/jvm/inspection/CachingJvmMetadataDetectorTest.groovy
  subprojects/jvm-services/src/test/groovy/org/gradle/internal/jvm/inspection/DefaultJvmMetadataDetectorTest.groovy
  subprojects/launcher/src/test/groovy/org/gradle/launcher/cli/WelcomeMessageActionTest.groovy
  subprojects/normalization-java/src/test/groovy/org/gradle/api/internal/changedetection/state/LineEndingNormalizingFileSystemLocationSnapshotHasherTest.groovy
  subprojects/normalization-java/src/test/groovy/org/gradle/api/internal/changedetection/state/LineEndingNormalizingInputStreamHasherTest.groovy
  subprojects/normalization-java/src/test/groovy/org/gradle/api/internal/changedetection/state/LineEndingNormalizingResourceHasherTest.groovy
  subprojects/normalization-java/src/test/groovy/org/gradle/api/internal/changedetection/state/MetaInfAwareClasspathResourceHasherTest.groovy
  subprojects/normalization-java/src/test/groovy/org/gradle/api/internal/changedetection/state/PropertiesFileAwareClasspathResourceHasherTest.groovy
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/toolchain/install/internal/AdoptOpenJdkDownloaderTest.groovy
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/toolchain/install/internal/AdoptOpenJdkRemoteBinaryTest.groovy
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/toolchain/install/internal/DefaultJavaToolchainProvisioningServiceTest.groovy
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/toolchain/install/internal/JdkCacheDirectoryTest.groovy
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/toolchain/internal/ToolchainReportRendererTest.groovy
  subprojects/platform-native/src/test/groovy/org/gradle/nativeplatform/internal/modulemap/GenerateModuleMapFileTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractGradleceptionSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/BomSupportPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GrettySmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/JGitPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ThirdPartyGradleModuleMetadataSmokeTest.groovy
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/enduser/GradleRunnerConsoleInputEndUserIntegrationTest.groovy
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/enduser/GradleRunnerConventionalPluginClasspathInjectionEndUserIntegrationTest.groovy
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/enduser/GradleRunnerDefaultTestKitDirIntegrationTest.groovy
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/enduser/GradleRunnerPluginClasspathInjectionEndUserIntegrationTest.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r55/CompositeDeduplicationCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r55/ReservedProjectNamesCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r56/ClosedProjectSubstitutionCrossVersionSpec.groovy
  subprojects/workers/src/test/groovy/org/gradle/workers/internal/DefaultWorkerExecutorParallelTest.groovy
Labels: 🌱 onboarding, @support

#18030 Improve configuration cache invalidation behavior for dynamic versions
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheDependencyResolutionFeaturesIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintWriter.kt
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ivy/IvyDynamicRevisionRemoteResolveIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/CachingModuleComponentRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/ChangingValueDependencyResolutionListener.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/modulecache/dynamicversions/AbstractModuleVersionsCache.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/modulecache/dynamicversions/DefaultCachedModuleVersionList.java
Labels: @configuration-cache

#18077 Let configuration cache support `java-gradle-plugin` projects with dependencies
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/plugins/JavaGradlePluginPlugin.java
Labels: @configuration-cache

#11764 Remove nonexisting entries from classpath
  subprojects/core/src/integTest/groovy/org/gradle/process/internal/worker/DefaultWorkerProcessBuilderTest.groovy
  subprojects/core/src/main/java/org/gradle/process/internal/worker/DefaultWorkerProcessBuilder.java
  subprojects/core/src/test/groovy/org/gradle/process/internal/worker/DefaultWorkerProcessBuilderSpec.groovy
  subprojects/docs/src/docs/release/notes.md
  subprojects/testing-jvm/src/integTest/resources/org/gradle/testing/junit/JUnitIntegrationTest/executesTestsInCorrectEnvironment/build.gradle
Labels: in:jvm-ecosystem

#18067 Use Internal instead of ReplacedBy for stableSources
  subprojects/antlr/src/main/java/org/gradle/api/plugins/antlr/AntlrTask.java
  subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
Labels: @execution

#18083 Make order of registered watchable directories consistent
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/WatchedDirectoriesFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
Labels: @execution

#18094 Use task to promote final backport release
  .teamcity/src/main/kotlin/promotion/PublishRelease.kt
Labels: @dev-productivity

#18100 Fix link to upgrade documentation
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/changedetection/state/TaskCustomTypesInputPropertyIntegrationTest.groovy
  subprojects/model-core/src/main/java/org/gradle/internal/snapshot/impl/SerializedValueSnapshot.java
Labels: @execution

#18102 Document defaults for gradle properties in Build Enviroment page in the user guide
  subprojects/docs/src/docs/userguide/authoring-builds/multi-project/multi_project_configuration_and_execution.adoc
  subprojects/docs/src/docs/userguide/running-builds/build_environment.adoc
  subprojects/docs/src/docs/userguide/running-builds/performance.adoc
Labels: a:documentation

#18112 Improve Either
  subprojects/functional/src/main/java/org/gradle/internal/Either.java
  subprojects/functional/src/test/groovy/org/gradle/internal/EitherTest.groovy
Labels: @execution

#18165 Document exclude potential breaking change
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
Labels: in:dependency-resolution
