Repository gradle/gradle, pull requests merged in 2021-06, with the labels that each got.

#17330 Remove now unused "Won't fix" legend in CC docs
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
Labels: @configuration-cache, a:documentation, in:configuration-cache

#17326 Fix dependency verification downloading bogus files during IDE sync
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationSignatureCheckIntegTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/DefaultModuleComponentArtifactIdentifier.java
Labels: @execution, in:dependency-verification

#17333 Add channel as input to performance test task
  build-logic/performance-testing/src/main/groovy/gradlebuild/performance/tasks/PerformanceTest.groovy
Labels: @dev-productivity

#17087 Deprecate Lambdas as task actions
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/tasks/SnapshotTaskInputsOperationIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedCustomTaskExecutionIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalBuildIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/LambdaInputsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/NestedInputIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/SnapshotTaskInputsBuildOperationResult.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/SnapshotTaskInputsBuildOperationType.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskOutputCachingDisabledReasonCategory.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/ExecuteTaskBuildOperationResult.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/SnapshotTaskInputsBuildOperationResultTest.groovy
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/docs/userguide/troubleshooting/validation_problems.adoc
  subprojects/execution/src/integTest/groovy/org/gradle/internal/execution/IncrementalExecutionIntegrationTest.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/caching/CachingDisabledReasonCategory.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/caching/CachingInputs.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/caching/impl/DefaultCachingStateBuilder.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/caching/impl/LoggingCachingStateBuilder.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/history/changes/DefaultExecutionStateChangeDetector.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/history/changes/ImplementationChanges.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ValidateStep.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/caching/impl/DefaultCachingStateBuilderTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/history/changes/ImplementationChangesTest.groovy
  subprojects/hashing/src/main/java/org/gradle/internal/hash/Hasher.java
  subprojects/hashing/src/main/java/org/gradle/internal/hash/Hashing.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/OutputScrapingExecutionResult.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/problems/ValidationProblemId.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/validation/AbstractValidationProblemBuilder.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/validation/TypeValidationProblemRenderer.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/validation/ValidationProblemBuilder.java
  subprojects/model-core/src/main/java/org/gradle/internal/snapshot/impl/ImplementationSnapshotSerializer.java
  subprojects/model-core/src/test/groovy/org/gradle/internal/reflect/validation/ValidationMessageCheckerTest.groovy
  subprojects/model-core/src/test/groovy/org/gradle/internal/snapshot/impl/SnapshotSerializerTest.groovy
  subprojects/model-core/src/testFixtures/groovy/org/gradle/internal/reflect/validation/ValidationMessageChecker.groovy
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/impl/ImplementationSnapshot.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/impl/KnownImplementationSnapshot.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/impl/LambdaImplementationSnapshot.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/impl/UnknownClassloaderImplementationSnapshot.java
Labels: @execution

#17298 Use composite build for triggers
  .teamcity/src/main/kotlin/configurations/StagePasses.kt
  .teamcity/src/main/kotlin/configurations/VcsTriggers.kt
  .teamcity/src/main/kotlin/projects/GradleBuildToolRootProject.kt
  .teamcity/src/main/kotlin/promotion/PublishGradleDistribution.kt
  .teamcity/src/main/kotlin/promotion/PublishNightlySnapshot.kt
  .teamcity/src/main/kotlin/promotion/StartReleaseCycle.kt
  .teamcity/src/test/kotlin/CIConfigIntegrationTests.kt
  build-logic/build-update-utils/src/main/kotlin/gradlebuild.update-versions.gradle.kts
  build-logic/build-update-utils/src/main/kotlin/gradlebuild/buildutils/tasks/UpdateBranchStatus.kt
Labels: @dev-productivity

#17350 Use kill instead of kill -9 to allow daemon exit gracefully
  .teamcity/src/main/kotlin/common/Os.kt
Labels: @dev-productivity

#17336 Fix broken javadoc link in release notes
  subprojects/docs/src/docs/release/notes.md
Labels: @core

#17366 Fix "Multiple builders are available" when syncing project in IDEA
  subprojects/core/src/main/java/org/gradle/tooling/provider/model/internal/DefaultToolingModelBuilderRegistry.java
Labels: @core

#17371 Poll daemon killing result
  .teamcity/src/main/kotlin/common/Os.kt
Labels: @dev-productivity

#15528 Let `AbstractSmokeTest` detect more deprecation warnings
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/SmokeTestGradleRunner.groovy
Labels: @configuration-cache, in:building-gradle

#17374 Fix invalid attribute usage
  subprojects/docs/src/docs/userguide/build-cache/caching_java_projects.adoc
  subprojects/docs/src/docs/userguide/extending-gradle/worker_api.adoc
Labels: @core, a:documentation

#17356 Rework performance test report model
  .teamcity/src/main/kotlin/configurations/PerformanceTestsPass.kt
  build-logic/performance-testing/src/main/groovy/gradlebuild/performance/ScenarioBuildResultData.groovy
  build-logic/performance-testing/src/main/groovy/gradlebuild/performance/reporter/PerformanceReporter.groovy
  build-logic/performance-testing/src/main/groovy/gradlebuild/performance/tasks/PerformanceTest.groovy
  build-logic/performance-testing/src/main/kotlin/gradlebuild/performance/PerformanceTestPlugin.kt
  build-logic/performance-testing/src/main/kotlin/gradlebuild/performance/tasks/PerformanceTestReport.kt
  subprojects/build-scan-performance/src/testFixtures/groovy/org/gradle/performance/results/BuildScanReportGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/FormatSupport.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/PerformanceReportScenario.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/PerformanceReportScenarioHistoryExecution.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/PerformanceTestExecutionResult.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/ScenarioBuildResultData.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/ScenarioResult.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/AbstractReportGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/AbstractTablePageGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/DefaultPerformanceExecutionDataProvider.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/DefaultPerformanceFlakinessDataProvider.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/DefaultReportGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/FlakinessDetectionPerformanceExecutionDataProvider.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/FlakinessIndexPageGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/FlakinessReportGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/IndexPageGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/PerformanceExecutionDataProvider.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/PerformanceFlakinessDataProvider.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/TestPageGenerator.java
  subprojects/internal-performance-testing/src/test/groovy/org/gradle/performance/results/report/DefaultPerformanceExecutionDataProviderTest.groovy
Labels: @dev-productivity

#17367 Replace HashValue with HashCode
  subprojects/base-services/src/main/java/org/gradle/internal/hash/HashUtil.java
  subprojects/base-services/src/main/java/org/gradle/internal/hash/HashValue.java
  subprojects/base-services/src/test/groovy/org/gradle/internal/hash/HashUtilTest.groovy
  subprojects/base-services/src/test/groovy/org/gradle/internal/hash/HashValueTest.groovy
  subprojects/base-services/src/testFixtures/groovy/org/gradle/internal/hash/TestFileHasher.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheKey.kt
  subprojects/core/src/main/java/org/gradle/groovy/scripts/TextResourceScriptSource.java
  subprojects/core/src/main/java/org/gradle/groovy/scripts/internal/FileCacheBackedScriptClassCompiler.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/caching/CachedDependencyResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/internal/resource/transfer/DefaultCacheAwareExternalResourceAccessor.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/modulecache/ModuleMetadataSerializerTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/resource/transfer/DefaultCacheAwareExternalResourceAccessorTest.groovy
  subprojects/hashing/src/main/java/org/gradle/internal/hash/ChecksumService.java
  subprojects/hashing/src/main/java/org/gradle/internal/hash/HashCode.java
  subprojects/hashing/src/main/java/org/gradle/internal/hash/HashFunction.java
  subprojects/hashing/src/main/java/org/gradle/internal/hash/Hashing.java
  subprojects/hashing/src/main/java/org/gradle/internal/hash/HashingOutputStream.java
  subprojects/hashing/src/test/groovy/org/gradle/internal/hash/HashCodeTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/InProcessGradleExecuter.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/AbstractModule.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/GradleModuleMetadata.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/ivy/IvyFileModule.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/maven/AbstractMavenModule.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/HttpArtifact.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/HttpServer.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/IvyHttpModule.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/vcs/internal/SourceDependencies.groovy
  subprojects/internal-testing/src/main/groovy/org/gradle/integtests/fixtures/UrlValidator.groovy
  subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/file/TestFile.java
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/AccessorFragments.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/codegen/GradleApiExtensionsTest.kt
  subprojects/language-native/src/integTest/groovy/org/gradle/language/objectivec/ObjectiveCLanguageIncrementalBuildIntegrationTest.groovy
  subprojects/language-native/src/main/java/org/gradle/language/cpp/internal/NativeDependencyCache.java
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishHttpIntegTest.groovy
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publisher/AbstractMavenPublisher.java
  subprojects/model-core/src/main/java/org/gradle/internal/snapshot/impl/DefaultValueSnapshotter.java
  subprojects/model-core/src/main/java/org/gradle/internal/snapshot/impl/HashCodeSnapshot.java
  subprojects/model-core/src/main/java/org/gradle/internal/snapshot/impl/SnapshotSerializer.java
  subprojects/model-core/src/test/groovy/org/gradle/internal/snapshot/impl/SnapshotSerializerTest.groovy
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/RuntimeClasspathResourceHasher.java
  subprojects/normalization-java/src/test/groovy/org/gradle/api/internal/changedetection/state/PropertiesFileAwareClasspathResourceHasherTest.groovy
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/internal/CompilerOutputFileNamingScheme.java
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/impldeps/GradleImplDepsConcurrencyIntegrationTest.groovy
  subprojects/resources-gcs/src/integTest/groovy/org/gradle/integtests/resource/gcs/fixtures/GcsServer.groovy
  subprojects/version-control/src/main/java/org/gradle/vcs/internal/services/DefaultVersionControlRepositoryFactory.java
  subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperChecksumVerificationTest.groovy
  subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy
Labels: @execution

#17325 Deprecate relying on equals for up-to-date checks
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/changedetection/state/TaskCustomTypesInputPropertyIntegrationTest.groovy
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/model-core/src/main/java/org/gradle/internal/snapshot/impl/SerializedValueSnapshot.java
Labels: @execution

#17387 Prove init scripts can declare build logic inputs
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheInitScriptsIntegrationTest.groovy
  subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/internal/DefaultGroupTaskReportModel.java
Labels: @configuration-cache, in:configuration-cache

#17389 Disable deprecation warning check for GradleBuildSmokeTest
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildSmokeTest.groovy
Labels: @dev-productivity

#17116 Record origin execution time as execution + output snapshotting time
  subprojects/build-cache-base/src/main/java/org/gradle/caching/internal/origin/OriginMetadata.java
  subprojects/build-cache-base/src/main/java/org/gradle/caching/internal/origin/OriginMetadataFactory.java
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/BuildCacheCommandFactory.java
  subprojects/build-cache/src/test/groovy/org/gradle/caching/internal/origin/OriginMetadataFactoryTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskExecutionContext.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/DefaultTaskExecutionContext.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuter.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/ExecuteTaskBuildOperationResult.java
  subprojects/core/src/main/java/org/gradle/caching/internal/controller/impl/DefaultBuildCacheCommandFactory.java
  subprojects/core/src/test/groovy/org/gradle/caching/internal/controller/impl/DefaultBuildCacheCommandFactoryTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementBuildScopeServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/UnitOfWork.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/history/impl/DefaultPreviousExecutionStateSerializer.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/BuildCacheStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CachingResult.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CancelExecutionStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CaptureStateAfterExecutionStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ExecuteStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ResolveCachingStateStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ResolveInputChangesStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/Result.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/SkipEmptyWorkStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/SkipUpToDateStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/TimeoutStep.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/BuildCacheStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CancelExecutionStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/ExecuteStepTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/OriginFixture.groovy
Labels: @execution

#17385 Set context classloader on created threads explicitly to avoid leak
  subprojects/base-services/src/main/java/org/gradle/internal/concurrent/DefaultExecutorFactory.java
  subprojects/base-services/src/main/java/org/gradle/internal/concurrent/ThreadFactoryImpl.java
Labels: @configuration-cache, in:core

#17398 Improve documentation for building plugins with Kotlin 1.5
  subprojects/docs/src/docs/userguide/troubleshooting/validation_problems.adoc
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/NestedInputKotlinImplementationTrackingIntegrationTest.groovy
Labels: @execution

#17373 Allow custom implementations of PublishArtifact
  subprojects/core-api/src/main/java/org/gradle/api/internal/artifacts/PublishArtifactInternal.java
  subprojects/core/src/main/java/org/gradle/api/internal/artifacts/publish/DecoratingPublishArtifact.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/LazyPublishArtifact.java
  subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyPublishBasicIntegTest.groovy
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/artifact/AbstractIvyArtifact.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/artifact/ArchiveTaskBasedIvyArtifact.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/artifact/DerivedIvyArtifact.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/artifact/FileBasedIvyArtifact.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/artifact/PublishArtifactBasedIvyArtifact.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/artifact/SingleOutputTaskIvyArtifact.java
  subprojects/ivy/src/test/groovy/org/gradle/api/publish/ivy/internal/artifact/IvyArtifactNotationParserFactoryTest.groovy
  subprojects/language-native/src/test/groovy/org/gradle/language/plugins/NativeBasePluginTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishBasicIntegTest.groovy
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/artifact/AbstractMavenArtifact.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/artifact/PublishArtifactBasedMavenArtifact.java
  subprojects/maven/src/test/groovy/org/gradle/api/publish/maven/internal/artifact/MavenArtifactNotationParserFactoryTest.groovy
  subprojects/maven/src/test/groovy/org/gradle/api/publish/maven/internal/publication/DefaultMavenPublicationTest.groovy
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/metadata/ModuleMetadataSpecBuilder.java
Labels: @core

#17400 Note that Project.relativePath may throw IllegalArgumentException
  subprojects/core-api/src/main/java/org/gradle/api/Project.java
Labels: @core, a:documentation

#17406 Fix schedule trigger
  .teamcity/src/main/kotlin/promotion/PublishNightlySnapshot.kt
Labels: @dev-productivity

#17409 Remove now unneeded workaround in :build-logic test
  build-logic/performance-testing/src/test/kotlin/gradlebuild/performance/tasks/DetermineBaselinesTest.kt
Labels: @configuration-cache

#17343 Dependency verification usability improvements
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationSignatureCheckIntegTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationSignatureWriteIntegTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/ChecksumAndSignatureVerificationOverride.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/report/AbstractTextDependencyVerificationReportRenderer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/report/DependencyVerificationReportWriter.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/report/ReportState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/report/VerificationHighLevelErrors.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/writer/WriteDependencyVerificationFile.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/serializer/DependencyVerificationXmlTags.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/serializer/DependencyVerificationsXmlReader.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/serializer/DependencyVerificationsXmlWriter.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/signatures/DefaultSignatureVerificationServiceFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/signatures/SignatureVerificationServiceFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/verifier/DependencyVerificationConfiguration.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/verifier/DependencyVerifierBuilder.java
  subprojects/dependency-management/src/main/resources/org/gradle/schema/dependency-verification-1.1.xsd
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/verification/serializer/DependencyVerificationsXmlReaderTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/verification/serializer/DependencyVerificationsXmlWriterTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/verification/verifier/DependencyVerifierTest.groovy
  subprojects/dependency-management/src/testFixtures/groovy/org/gradle/api/internal/artifacts/verification/DependencyVerificationFixture.groovy
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/dependency_verification.adoc
  subprojects/docs/src/snippets/dependencyManagement/dependencyVerification-disablingVerification/groovy/gradle/verification-metadata.xml
  subprojects/docs/src/snippets/dependencyManagement/dependencyVerification-disablingVerification/kotlin/gradle/verification-metadata.xml
  subprojects/security/src/main/java/org/gradle/security/internal/EmptyPublicKeyService.java
  subprojects/security/src/main/java/org/gradle/security/internal/SecuritySupport.java
  subprojects/security/src/testFixtures/groovy/org/gradle/security/fixtures/SimpleKeyRing.groovy
Labels: @execution, in:dependency-verification

#17414 Add some leniency around time-sensitive test
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/ExecuteStepTest.groovy
Labels: @execution

#17399 Report Groovy classpath inference errors at task execution time
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/JavaApplicationInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/JavaLibraryInitIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheGroovyIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/Codec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/BeanSpecCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/FileCollectionCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/jos/JavaObjectSerializationCodec.kt
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationContainer.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/FailingFileCollection.java
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/GroovyProjectIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/WellBehavedPluginTest.groovy
  subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractCrossTaskIncrementalCompilationIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractCrossTaskIncrementalGroovyCompilationIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/groovy/GroovyBasePluginIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/GroovyBasePlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/JvmPluginsHelper.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmPluginServices.java
  subprojects/plugins/src/main/java/org/gradle/api/tasks/GroovyRuntime.java
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/enduser/GradleRunnerConsoleInputEndUserIntegrationTest.groovy
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/enduser/GradleRunnerSamplesEndUserIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junit/BuildSrcSpockIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/spock/Spock2FilteringIntegrationTest.groovy
Labels: @configuration-cache, in:groovy-plugin

#17418 Let gradlebuild.code-quality plugin not capture a script reference in a property provider
  build-logic-commons/code-quality/src/main/kotlin/gradlebuild.code-quality.gradle.kts
Labels: @configuration-cache

#17421 Reformat `AntlrPlugin`
  subprojects/antlr/src/main/java/org/gradle/api/plugins/antlr/AntlrPlugin.java
  subprojects/antlr/src/main/java/org/gradle/api/plugins/antlr/AntlrTask.java
Labels: @configuration-cache, a:chore

#17403 Report Scala classpath inference errors at task execution time
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/PluginConfigurationAttributesIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/ScalaBasePluginIntegrationTest.groovy
  subprojects/scala/src/main/java/org/gradle/api/tasks/ScalaRuntime.java
Labels: @configuration-cache, in:configuration-cache, in:scala-plugin

#17425 Don't report a missing task graph entry when isolated projects is enabled
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/isolated/IsolatedProjectsToolingApiInvocationIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCache.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheAwareBuildModelController.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheKey.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheServices.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultBuildTreeModelControllerServices.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultConfigurationCache.kt
  subprojects/configuration-cache/src/test/kotlin/org/gradle/configurationcache/ConfigurationCacheKeyTest.kt
  subprojects/core/src/main/java/org/gradle/initialization/ConfigurationCacheAwareBuildModelController.java
  subprojects/core/src/main/java/org/gradle/internal/buildtree/BuildActionModelRequirements.java
  subprojects/core/src/main/java/org/gradle/internal/buildtree/BuildTreeModelControllerServices.java
  subprojects/core/src/main/java/org/gradle/internal/buildtree/QueryModelRequirements.java
  subprojects/core/src/main/java/org/gradle/internal/buildtree/RunTasksRequirements.java
  subprojects/core/src/main/java/org/gradle/testfixtures/internal/ProjectBuilderImpl.java
  subprojects/launcher/src/main/java/org/gradle/launcher/exec/BuildTreeLifecycleBuildActionExecutor.java
Labels: @configuration-cache

#17426 Ignore flaky PropertyKotlinInterOpIntegrationTest
  subprojects/model-core/src/integTest/groovy/org/gradle/api/provider/PropertyKotlinInterOpIntegrationTest.groovy
Labels: @dev-productivity

#17412 Replace task execution listener by simple tasks for code quality build scan data extraction
  build-logic/profiling/src/main/kotlin/gradlebuild.buildscan.gradle.kts
  build-logic/profiling/src/main/kotlin/gradlebuild/buildscan/tasks/ExtractCodeQualityBuildScanData.kt
Labels: @configuration-cache

#17419 Make gradle/shared-with-buildSrc/mirrors.settings.gradle.kts compatible with CC
  gradle/shared-with-buildSrc/mirrors.settings.gradle.kts
Labels: @configuration-cache

#17413 Ignore modified file events for directories on Windows
  gradle/verification-metadata.xml
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/docs/src/docs/userguide/running-builds/gradle_daemon.adoc
Labels: @execution

#17427 Use a plain text keyring
  gradle/verification-keyring.gpg
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: @dev-productivity

#17443 Show all selected executions in performance test report
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/PerformanceReportScenario.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/AbstractTablePageGenerator.java
Labels: @dev-productivity

#17442 Repeat flakiness detection performance build in the same build
  .teamcity/src/main/kotlin/configurations/PerformanceTest.kt
  .teamcity/src/main/kotlin/model/PerformanceTestBucketProvider.kt
Labels: @dev-productivity

#17451 Use 7.0 as first version to run on Java 16
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/BaseGradleRunnerIntegrationTest.groovy
Labels: @dev-productivity

#17449 Add `@ServiceScope` to AsyncIOScopeFactory build scoped service
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/PrecompiledScriptPluginIntegrationTest.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/concurrent/IO.kt
Labels: @configuration-cache, in:kotlin-dsl

#17454 Split ConfigurationCacheIntegrationTest
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheConventionMappingIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheDirIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheJavaSerializationIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheLambdaIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheSupportedTypesIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheTaskSerializationIntegrationTest.groovy
Labels: @configuration-cache, in:configuration-cache

#17455 Split ConfigurationCacheIncludedBuildChangesIntegrationTest
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIncludedBuildInputsChangesIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIncludedBuildLogicChangesIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIncludedBuildScriptChangesIntegrationTest.groovy
Labels: @configuration-cache, in:configuration-cache

#17460 Create a non-blocking seprate CheckLinks job
  .teamcity/src/main/kotlin/configurations/BaseGradleBuildType.kt
  .teamcity/src/main/kotlin/configurations/CheckLinks.kt
  .teamcity/src/main/kotlin/configurations/FunctionalTest.kt
  .teamcity/src/main/kotlin/configurations/PartialTrigger.kt
  .teamcity/src/main/kotlin/configurations/PerformanceTestsPass.kt
  .teamcity/src/main/kotlin/configurations/StagePasses.kt
  .teamcity/src/main/kotlin/model/CIBuildModel.kt
  .teamcity/src/main/kotlin/projects/StageProject.kt
  subprojects/docs/build.gradle
Labels: @dev-productivity

#17392 Adapt input artifact path for filtering transforms
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementGradleUserHomeScopeServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/ImmutableTransformationWorkspaceServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/MutableTransformationWorkspaceServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResult.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationResultSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationWorkspaceServices.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/TestTransformationWorkspaceServices.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/TransformationResultSerializerTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformInvocationTest.groovy
Labels: @execution

#17466 Split CrossTaskIncrementalCompilationIntegrationTest
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractCrossTaskConstantChangesIncrementalCompilationIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractCrossTaskIncrementalCompilationIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractCrossTaskIncrementalCompilationSupport.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/CrossTaskClassChangesIncrementalCompilationIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/CrossTaskConstantChangesIncrementalGroovyCompilationIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/CrossTaskConstantChangesIncrementalJavaCompilationIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/CrossTaskIncrementalGroovyCompilationIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/CrossTaskIncrementalGroovyCompilationUsingClassDirectoryIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/CrossTaskIncrementalJavaCompilationIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/CrossTaskIncrementalJavaCompilationUsingClassDirectoryIntegrationTest.groovy
Labels: @dev-productivity

#17476 Remove commented-out sample for jacoco aggregation of all Test tasks
  subprojects/docs/src/samples/java/jvm-multi-project-with-code-coverage/groovy/buildSrc/src/main/groovy/myproject.java-conventions.gradle
  subprojects/docs/src/samples/java/jvm-multi-project-with-code-coverage/kotlin/buildSrc/src/main/kotlin/myproject.java-conventions.gradle.kts
Labels: @core, a:documentation

#17463 Follow up for HttpHeaderCredentials work
  subprojects/core-api/src/main/java/org/gradle/api/credentials/HttpHeaderCredentials.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/declaring_repositories.adoc
Labels: @core

#17440 Do not initialize FS-watching in CLI and TAPI
  subprojects/build-cache/src/jmh/java/org/gradle/caching/internal/tasks/ChmodBenchmark.java
  subprojects/core/src/main/java/org/gradle/testfixtures/internal/ProjectBuilderImpl.java
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/NoDaemonFilesystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingNotSupportedVirtualFileSystem.java
  subprojects/internal-testing/src/main/groovy/org/gradle/testfixtures/internal/NativeServicesTestFixture.java
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/NativeServicesInitializingAction.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/bootstrap/DaemonMain.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/DefaultConnection.java
  subprojects/native/src/main/java/org/gradle/internal/nativeintegration/services/NativeServices.java
  subprojects/persistent-cache/src/integTest/groovy/org/gradle/cache/internal/DefaultFileLockManagerContentionIntegrationTest.groovy
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/GradleRunnerFileSystemWatchingIntegrationTest.groovy
  subprojects/worker-processes/src/main/java/org/gradle/process/internal/worker/child/SystemApplicationClassLoaderWorker.java
Labels: @execution

#17486 Split MavenPublishResolvedVersionsJavaIntegTest
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishResolvedVersionsJavaIntegTest.groovy
Labels: @dev-productivity

#17485 Split MavenConversionIntegrationTest
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/MavenConversionIntegrationTest.groovy
Labels: @dev-productivity

#17390 Allow HTTP build cache client requests to be redirected
  subprojects/build-cache-http/src/integTest/groovy/org/gradle/caching/http/internal/HttpBuildCacheConfigurationBuildOperationIntegrationTest.groovy
  subprojects/build-cache-http/src/integTest/groovy/org/gradle/caching/http/internal/HttpBuildCacheServiceErrorHandlingIntegrationTest.groovy
  subprojects/build-cache-http/src/integTest/groovy/org/gradle/caching/http/internal/HttpBuildCacheServiceIntegrationTest.groovy
  subprojects/build-cache-http/src/integTest/groovy/org/gradle/caching/http/internal/HttpBuildCacheServiceTest.groovy
  subprojects/build-cache-http/src/main/java/org/gradle/caching/http/HttpBuildCache.java
  subprojects/build-cache-http/src/main/java/org/gradle/caching/http/internal/DefaultHttpBuildCacheServiceFactory.java
  subprojects/build-cache-http/src/main/java/org/gradle/caching/http/internal/HttpBuildCacheService.java
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/service/StoreTarget.java
  subprojects/build-cache/src/test/groovy/org/gradle/caching/internal/controller/service/StoreTargetTest.groovy
  subprojects/docs/src/docs/dsl/org.gradle.caching.http.HttpBuildCache.xml
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/build-cache/build_cache.adoc
  subprojects/docs/src/snippets/buildCache/http-build-cache/groovy/settings.gradle
  subprojects/docs/src/snippets/buildCache/http-build-cache/kotlin/settings.gradle.kts
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/DropConnectionFilter.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/HttpBuildCacheServer.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/HttpServer.groovy
  subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/AllowFollowForMutatingMethodRedirectStrategy.java
  subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/AlwaysFollowAndPreserveMethodRedirectStrategy.java
  subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/DefaultHttpSettings.java
  subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/HttpClientConfigurer.java
  subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/HttpSettings.java
  subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/RedirectVerifyingStrategyDecorator.java
  subprojects/resources-http/src/test/groovy/org/gradle/internal/resource/transport/http/AllowFollowForMutatingMethodRedirectStrategyTest.groovy
  subprojects/resources-http/src/test/groovy/org/gradle/internal/resource/transport/http/AlwaysFollowAndPreserveMethodRedirectStrategyTest.groovy
Labels: @execution, in:build-cache

#17505 Use constant for configuration name
  .teamcity/src/main/kotlin/model/FunctionalTestBucketProvider.kt
Labels: @dev-productivity

#17502 Fix detection of test source sets in IDEA
  build-logic/integration-testing/src/main/kotlin/gradlebuild.test-fixtures.gradle.kts
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
  build-logic/performance-testing/src/main/kotlin/gradlebuild/performance/PerformanceTestPlugin.kt
Labels: @dev-productivity

#17507 Enable debug output in WatchedDirectoriesFileSystemWatchingIntegrationTest
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/WatchedDirectoriesFileSystemWatchingIntegrationTest.groovy
Labels: @execution

#17517 Prepare 7.1.1 bugfix release
  released-versions.json
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/BaseGradleRunnerIntegrationTest.groovy
  version.txt
Labels: @execution

#17518 Fix constant analysis for package-info and module-info
  subprojects/java-compiler-plugin/src/main/java/org/gradle/internal/compiler/java/listeners/constants/ConstantsTreeVisitor.java
  subprojects/java-compiler-plugin/src/test/groovy/com/gradle/internal/compiler/java/AbstractCompilerPluginTest.groovy
  subprojects/java-compiler-plugin/src/test/groovy/com/gradle/internal/compiler/java/listeners/ConstantsCollectorTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractCrossTaskIncrementalJavaCompilationIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/JavaSourceIncrementalCompilationIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysisData.java
Labels: @execution

#17520 Increase scalability of `ConfigurationCacheProblems`
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ConfigurationCacheProblems.kt
Labels: @configuration-cache

#17538 Generate less garbage when writing the configuration cache report
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheReport.kt
Labels: @configuration-cache

#17376 Clarify file system watching enabling
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/EnableFileSystemWatchingIntegrationTest.groovy
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunner.java
Labels: @execution, in:virtual-file-system

#17544 Rebaseline incremental Java compilation tests after Guava upgrade
  .teamcity/performance-tests-ci.json
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIncrementalExecutionPerformanceTest.groovy
Labels: @execution

#17546 Add integration test for overriding SourceTask.getSource()
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/SourceTaskIntegrationTest.groovy
Labels: a:chore, in:core

#17215 Prevent start script code execution in env vars using bash
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/ApplicationIntegrationSpec.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/ApplicationPluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/ApplicationPluginUnixShellsIntegrationTest.groovy
  subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
  subprojects/plugins/src/test/groovy/org/gradle/api/internal/plugins/UnixStartScriptGeneratorTest.groovy
Labels: @core

#17550 Reduce configuration cache report overhead
  subprojects/configuration-cache/build.gradle.kts
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheProblemReportingIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/isolated/IsolatedProjectsToolingApiInvocationIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheException.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheReport.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ConfigurationCacheProblems.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ConfigurationCacheProblemsSummary.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ProblemsSummary.kt
  subprojects/core/src/main/java/org/gradle/internal/buildtree/ProblemReportingBuildActionRunner.java
  subprojects/docs/src/snippets/configurationCache/problemsGroovy/tests/fail.out
  subprojects/docs/src/snippets/configurationCache/problemsGroovy/tests/store.out
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/configurationcache/ConfigurationCacheProblemsFixture.groovy
Labels: @configuration-cache

#17397 Use placeholders for java.lang.StackTraceElement
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AvailableJavaHomes.java
  subprojects/messaging/src/main/java/org/gradle/internal/serialize/ExceptionPlaceholder.java
  subprojects/messaging/src/main/java/org/gradle/internal/serialize/StackTraceElementPlaceholder.java
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/GradleRunnerSupportedBuildJvmIntegrationTest.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r72/JavaVersionCrossVersionTest.groovy
Labels: @core

#17547 Treat non-existing files as regular files when detecting missing task dependencies
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/execution/plan/ExecutionNodeAccessHierarchy.java
  subprojects/core/src/test/groovy/org/gradle/execution/plan/ExecutionNodeAccessHierarchyTest.groovy
Labels: @execution

#17566 Improve disable caching reason on DefaultTask
  subprojects/core/src/main/java/org/gradle/api/DefaultTask.java
Labels: @execution

#17569 Polish `ConfigurationCacheReport`
  subprojects/configuration-cache/build.gradle.kts
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheServices.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ConfigurationCacheProblems.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ConfigurationCacheReport.kt
Labels: @configuration-cache, in:configuration-cache
