Repository gradle/gradle, pull requests merged in 2021-11, with the labels that each got.

#18831 Update test bucket json
  .teamcity/test-buckets.json
Labels: @dev-productivity

#18816 Add additional.gradle.parameters to TeamCity
  .teamcity/src/main/kotlin/common/extensions.kt
  .teamcity/src/main/kotlin/projects/CheckProject.kt
  .teamcity/src/test/kotlin/ApplyDefaultConfigurationTest.kt
  .teamcity/src/test/kotlin/PerformanceTestBuildTypeTest.kt
Labels: @dev-productivity

#18826 Apply dead code elimination to the `configuration-cache-report`
  build-logic/buildquality/src/main/kotlin/gradlebuild.configuration-cache-report.gradle.kts
  build-logic/buildquality/src/main/kotlin/gradlebuild/configcachereport/tasks/MergeReportAssets.kt
  build-logic/uber-plugins/src/main/kotlin/gradlebuild.internal.kotlin-js.gradle.kts
  subprojects/configuration-cache-report/src/main/resources/configuration-cache-report.html
Labels: @configuration-cache

#18679 Replace env var filter with something configuration-cache compatible
  build-logic/jvm/src/main/kotlin/gradlebuild/propagated-env-variables.kt
Labels: @configuration-cache

#18835 Ignore failing tests for Ready for Release stage
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheCompositeBuildsIntegrationTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyPublishCoordinatesIntegTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationCachePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaFirstUsePerformanceTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/groovy/compile/BasicGroovyCompilerIntegrationSpec.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/groovy/compile/GroovyCompilerIntegrationSpec.groovy
Labels: @dev-productivity

#18782 Use @CompileClasspath for PackageListGenerator
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/runtimeshaded/PackageListGenerator.java
Labels: @dev-productivity

#18842 Revert ignored failing tests
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheCompositeBuildsIntegrationTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyPublishCoordinatesIntegTest.groovy
Labels: @dev-productivity

#18845 Smoke test Kotlin 1.6.0-RC2
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/KotlinGradlePluginVersions.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
Labels: @configuration-cache

#18769 Improve dependency verification usage workflow
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
  subprojects/core/src/main/java/org/gradle/internal/xml/SimpleMarkupWriter.java
  subprojects/core/src/test/groovy/org/gradle/internal/xml/SimpleXmlWriterSpec.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/writer/PgpEntry.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/writer/PgpKeyGrouper.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/serializer/DependencyVerificationsXmlReader.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/serializer/DependencyVerificationsXmlWriter.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/verifier/DependencyVerificationConfiguration.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/verifier/DependencyVerifier.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/verifier/DependencyVerifierBuilder.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/writer/PgpKeyGrouperTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/verification/serializer/DependencyVerificationsXmlWriterTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/verification/verifier/DependencyVerifierTest.groovy
Labels: in:dependency-verification

#18711 Add types to tasks task output
  subprojects/core-api/src/main/java/org/gradle/api/reflect/TypeOf.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/taskfactory/TaskIdentity.java
  subprojects/core/src/test/groovy/org/gradle/api/reflect/TypeOfSpec.groovy
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/TaskReportTaskIntegrationTest.groovy
  subprojects/diagnostics/src/main/java/org/gradle/api/plugins/HelpTasksPlugin.java
  subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/ConventionReportTask.java
  subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/TaskReportTask.java
  subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/internal/AggregateMultiProjectTaskReportModel.java
  subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/internal/TaskDetails.java
  subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/internal/TaskDetailsFactory.java
  subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/internal/TaskReportRenderer.java
  subprojects/diagnostics/src/test/groovy/org/gradle/api/tasks/diagnostics/internal/AggregateMultiProjectTaskReportModelTest.groovy
  subprojects/docs/src/docs/dsl/org.gradle.api.tasks.diagnostics.TaskReportTask.xml
Labels: in:reporting-tasks

#18739 Don't reach into other tasks for test assertions.
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testsuites/TestSuitesIntegrationTest.groovy
Labels: in:test-suites

#18764 Add project descriptions to build-init and testing subprojects
  subprojects/build-init/build.gradle.kts
  subprojects/testing-base/build.gradle.kts
  subprojects/testing-junit-platform/build.gradle.kts
  subprojects/testing-jvm/build.gradle.kts
Labels: a:documentation

#18836 Add descriptions to addition parameters and support rerunAllTests
  .teamcity/src/main/kotlin/projects/CheckProject.kt
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
Labels: @dev-productivity

#18783 Ignore directories in fingerprints of FileTrees
  subprojects/core-api/src/main/java/org/gradle/api/tasks/InputDirectory.java
  subprojects/core-api/src/main/java/org/gradle/api/tasks/SkipWhenEmpty.java
  subprojects/core-api/src/main/java/org/gradle/api/tasks/TaskInputs.java
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/AbstractDirectorySensitivityIntegrationSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/AbstractIncrementalTasksIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/SkipWhenEmptyIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/SourceTaskIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskInputFilePropertyRegistration.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskInputs.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/SnapshotTaskInputsBuildOperationResult.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/GetInputFilesVisitor.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/AbstractInputFilePropertyAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/InputDirectoryPropertyAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/tasks/AbstractCopyTask.java
  subprojects/core/src/main/java/org/gradle/execution/ProjectExecutionServices.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/AbstractFileCollectionFingerprinter.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/DefaultFileCollectionSnapshotter.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/FileCollectionFingerprinterRegistrations.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/DefaultEmptySourceTaskSkipperTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuterTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/fingerprint/impl/DefaultFileCollectionSnapshotterTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformationRegistrationFactory.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactoryTest.groovy
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/snippets/tasks/incrementalBuild-incrementalBuildAdvanced/groovy/buildSrc/src/main/java/org/example/Instrument.java
  subprojects/docs/src/snippets/tasks/incrementalBuild-incrementalBuildAdvanced/kotlin/buildSrc/src/main/java/org/example/Instrument.java
  subprojects/execution/src/integTest/groovy/org/gradle/internal/execution/IncrementalExecutionIntegrationTest.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/fingerprint/FileCollectionFingerprinter.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/fingerprint/FileCollectionSnapshotter.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/fingerprint/impl/DefaultInputFingerprinter.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/impl/DefaultOutputSnapshotter.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/fingerprint/impl/DefaultInputFingerprinterTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/impl/DefaultOutputSnapshotterTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/BuildCacheStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/RecordOutputsStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/RemovePreviousOutputsStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/SnapshotterFixture.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/StoreExecutionStateStepTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskUpToDateIntegrationTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractAndroidSantaTrackerSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AsciidoctorPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ProtobufPluginSmokeTest.groovy
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/DirectorySensitivity.java
Labels: @execution

#18861 Improve upgrading doc for file tree/directory handling
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
Labels: @execution

#18869 Merge release into master
  released-versions.json
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/isolated/IsolatedProjectsToolingApiBuildActionIntegrationTest.groovy
  subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/GradleEnterprisePluginCheckInFixture.groovy
  subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/GradleEnterprisePluginEndOfBuildCallbackIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/AggregatingIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java
  subprojects/launcher/src/main/java/org/gradle/launcher/exec/BuildCompletionNotifyingBuildActionRunner.java
  subprojects/launcher/src/main/java/org/gradle/launcher/exec/BuildTreeLifecycleBuildActionExecutor.java
Labels: @dev-productivity

#18873 Update wrapper to latest nightly (for latest cc changes)
  gradle/wrapper/gradle-wrapper.properties
Labels: @configuration-cache

#18884 Ignore flaky `cleans up idle daemons when tooling API session is shut…
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r22/ClientShutdownCrossVersionSpec.groovy
Labels: @dev-productivity

#18885 Fix failing checkstyle test on parallel executer
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginVersionIntegrationTest.groovy
Labels: @dev-productivity

#18883 Merge release into master
  gradle/wrapper/gradle-wrapper.properties
  released-versions.json
Labels: @dev-productivity

#18887 Revert unexpected wrapper change in merge
  gradle/wrapper/gradle-wrapper.properties
Labels: @dev-productivity

#18889 Increase maxRetry from 1 to 2
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
Labels: @dev-productivity

#18891 Declare `PerformanceTest` uses `PerformanceTestService`
  build-logic/performance-testing/src/main/kotlin/gradlebuild/performance/PerformanceTestPlugin.kt
Labels: in:building-gradle, @configuration-cache

#18895 Improve release notes for `@UntrackedTask`
  subprojects/docs/src/docs/release/notes.md
Labels: @execution

#18892 Remove remaining references to `forUseAtConfigurationTime`
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOptionsIntegrationTest.groovy
  subprojects/core-api/src/main/java/org/gradle/api/file/FileContents.java
  subprojects/core-api/src/main/java/org/gradle/api/provider/ProviderFactory.java
  subprojects/dependency-management/src/testFixtures/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformTestFixture.groovy
Labels: @configuration-cache

#18859 Trim down included js library
  subprojects/diagnostics/src/main/resources/org/gradle/api/tasks/diagnostics/htmldependencyreport/jquery.jstree.js
Labels: in:reporting-tasks

#18902 Improve FSW probes description in release notes
  subprojects/docs/src/docs/release/notes.md
Labels: @execution

#18903 Polish `DefaultProject`
  subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProject.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/ProjectIdentifier.java
Labels: a:chore, @configuration-cache

#18905 Fix SnapshotTaskInputsBuildOperationResult.visitInputFileProperties
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/SnapshotTaskInputsBuildOperationResult.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/SnapshotTaskInputsBuildOperationResultTest.groovy
Labels: @execution

#18870 Suggested changes for https://github.com/gradle/gradle/pull/18865
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/DependencyHandler.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/DefaultDependencyHandler.java
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/ScriptHandlerScope.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/delegates/DependencyHandlerDelegate.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/ScriptHandlerScopeTest.kt
Labels: in:kotlin-dsl

#18907 Minor English corrections and improvements to aid readability in the docs
  subprojects/docs/src/docs/userguide/authoring-builds/software-product/structuring_software_products.adoc
Labels: a:documentation

#18924 Revert 18183 Remove special handling of maxParallelForks on AX41
  .teamcity/src/main/kotlin/common/extensions.kt
  build-logic/basics/src/main/kotlin/gradlebuild/basics/BuildEnvironment.kt
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
  build-logic/profiling/src/main/kotlin/gradlebuild.buildscan.gradle.kts
Labels: @dev-productivity

#18886 Exclude src from gradleBuildSmokeTest
  subprojects/smoke-test/build.gradle.kts
Labels: @dev-productivity

#18941 Use relative path sensitivity for Scala sources
  subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java
  subprojects/scala/src/main/java/org/gradle/language/scala/tasks/AbstractScalaCompile.java
Labels: @execution

#18939 Create a new object for visiting unvisited directories
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/SnapshotTaskInputsBuildOperationResult.java
Labels: @execution

#18942 Replace upToDateWhen by doNotTrackState/UntrackedTask
  build-logic/performance-testing/src/main/kotlin/gradlebuild/performance/PerformanceTestPlugin.kt
  build-logic/profiling/src/main/kotlin/gradlebuild/buildscan/tasks/ExtractCodeQualityBuildScanData.kt
  subprojects/diagnostics/src/main/java/org/gradle/api/reporting/dependencies/HtmlDependencyReportTask.java
  subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/BuildEnvironmentReportTask.java
  subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/ConventionReportTask.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/tasks/GenerateIvyDescriptor.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/tasks/GenerateMavenPom.java
  subprojects/model-core/src/test/groovy/org/gradle/internal/reflect/validation/ValidationMessageCheckerTest.groovy
  subprojects/model-core/src/testFixtures/groovy/org/gradle/internal/reflect/validation/ValidationMessageChecker.groovy
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/task/ShowToolchainsTask.java
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidatePluginsIntegrationTest.groovy
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/internal/ValidateAction.java
  subprojects/smoke-test/build.gradle.kts
Labels: @execution

#18958 Set testFilesCleanup.reportOnly for configration-cache
  subprojects/configuration-cache/build.gradle.kts
Labels: @dev-productivity

#18901 Fall back to archive tree empty check when checking for empty sources.
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/SkipWhenEmptyIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/DefaultFileCollectionSnapshotter.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/fingerprint/FileCollectionSnapshotter.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/fingerprint/InputFingerprinter.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/fingerprint/impl/DefaultInputFingerprinter.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/SkipEmptyWorkStep.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/fingerprint/impl/DefaultInputFingerprinterTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CaptureStateBeforeExecutionStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/IdentifyStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/SkipEmptyWorkStepTest.groovy
Labels: @execution

#18961 Upgrade TeamCity DSL version to 2021.2
  .teamcity/pom.xml
Labels: @dev-productivity

#18936 Add method for adding lazy values to AttributeContainer using providers
  build-logic-commons/code-quality/src/main/kotlin/gradlebuild.code-quality.gradle.kts
  build-logic/buildquality/src/main/kotlin/gradlebuild.configuration-cache-report.gradle.kts
  build-logic/buildquality/src/main/kotlin/gradlebuild.incubation-report-aggregation.gradle.kts
  build-logic/buildquality/src/main/kotlin/gradlebuild.incubation-report.gradle.kts
  build-logic/integration-testing/src/main/kotlin/gradlebuild.test-fixtures.gradle.kts
  build-logic/integration-testing/src/main/kotlin/gradlebuild/integrationtests/shared-configuration.kt
  build-logic/jvm/src/main/kotlin/gradlebuild.launchable-jar.gradle.kts
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
  build-logic/packaging/src/main/kotlin/gradlebuild.distributions.gradle.kts
  build-logic/packaging/src/main/kotlin/gradlebuild.shaded-jar.gradle.kts
  build-logic/profiling/src/main/kotlin/gradlebuild.jmh.gradle.kts
  build-logic/publishing/src/main/kotlin/gradlebuild.kotlin-dsl-plugin-bundle.gradle.kts
  build-logic/publishing/src/main/kotlin/gradlebuild.publish-public-libraries.gradle.kts
  subprojects/configuration-cache/build.gradle.kts
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheJavaIntegrationTest.groovy
  subprojects/core-api/src/main/java/org/gradle/api/attributes/AttributeContainer.java
  subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultImmutableAttributes.java
  subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultMutableAttributeContainer.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/attributes/DefaultMutableAttributeContainerTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/LazyAttributesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/constraints/DependencyConstraintsIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/ResolveConfigurationResolutionBuildOperationResult.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/attributes/ImmutableAttributeContainerWithErrorMessage.java
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/samples/build-organization/structuring-software-projects/kotlin/build-logic/commons/src/main/kotlin/com.example.jacoco.gradle.kts
  subprojects/docs/src/samples/build-organization/structuring-software-projects/kotlin/build-logic/report-aggregation/src/main/kotlin/com.example.report-aggregation.gradle.kts
  subprojects/docs/src/samples/java/jvm-multi-project-with-code-coverage/kotlin/buildSrc/src/main/kotlin/myproject.jacoco-aggregation.gradle.kts
  subprojects/docs/src/samples/java/jvm-multi-project-with-code-coverage/kotlin/buildSrc/src/main/kotlin/myproject.java-conventions.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-attributeSubstitutionRule/kotlin/consumer/build.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-ivyMetadataRule/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-metadataRule/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/modelingFeatures-crossProjectPublications-advanced-published/kotlin/buildSrc/src/main/kotlin/com/acme/InstrumentedJarsPlugin.kt
  subprojects/docs/src/snippets/dependencyManagement/modelingFeatures-crossProjectPublications-advanced/kotlin/producer/build.gradle.kts
  subprojects/docs/src/snippets/developingPlugins/pluginWithVariants/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/swift/testReport/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/swift/testReport/kotlin/buildSrc/src/main/kotlin/myproject.xctest-conventions.gradle.kts
  subprojects/docs/src/snippets/testing/testReport/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/testing/testReport/kotlin/buildSrc/src/main/kotlin/myproject.java-conventions.gradle.kts
  subprojects/docs/src/snippets/workerApi/md5ClassloaderIsolation/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/workerApi/md5ProcessIsolation/kotlin/build.gradle.kts
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/PrecompiledScriptPluginIntegrationTest.kt
  subprojects/wrapper/build.gradle.kts
Labels: @core, in:dependency-declarations

#18966 Cleanup unreadable file in SyncTaskIntegrationTest
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy
Labels: @execution

#18938 Enable plugin portal mirrors for integration tests by default
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/PluginVariantResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ResolveConfigurationRepositoriesBuildOperationIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/AbstractVersionCatalogIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/CatalogPluginApplyKotlinDSLIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/CatalogPluginsGroovyDSLIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/CatalogPluginsKotlinDSLIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/TomlDependenciesExtensionIntegrationTest.groovy
  subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/core/BuildScanBuildFailureHintIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/CachedKotlinTaskExecutionIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/NestedInputKotlinImplementationTrackingIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractDependencyResolutionTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractPluginIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/WellBehavedPluginTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/AbstractGradleExecuter.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/GradleExecuter.java
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/JavaExecToolchainIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/JavaToolchainUpToDateIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileToolchainIntegrationTest.groovy
  subprojects/model-core/src/testFixtures/groovy/org/gradle/api/internal/provider/AbstractLanguageInterOpIntegrationTest.groovy
  subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/use/DeployedPortalIntegrationSpec.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesWebQuickstartIntegrationTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/play/integtest/fixtures/external/AbstractMultiVersionPlayExternalContinuousBuildIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestTaskToolchainIntegrationTest.groovy
Labels: @dev-productivity

#18983 Remove timeout limitation for FlakyTest build
  .teamcity/src/main/kotlin/util/RerunFlakyTest.kt
Labels: @dev-productivity

#18981 Fix UndefinedBuildExecutionIntegrationTest
  subprojects/core/src/integTest/groovy/org/gradle/api/UndefinedBuildExecutionIntegrationTest.groovy
Labels: @dev-productivity

#18989 Ignore native directory in UndefinedBuildExecutionIntegrationTest
  subprojects/core/src/integTest/groovy/org/gradle/api/UndefinedBuildExecutionIntegrationTest.groovy
Labels: @dev-productivity

#18985 Notify VFS when creating manifest
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/GeneratedSingletonFileTree.java
  subprojects/file-collections/src/test/groovy/org/gradle/api/internal/file/collections/GeneratedSingletonFileTreeSpec.groovy
Labels: @execution

#18834 Outputs from Test tasks are exposed as variants to dependency management
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/ConfigurationPublications.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/type/ArtifactTypeDefinition.java
  subprojects/core-api/src/main/java/org/gradle/api/attributes/Category.java
  subprojects/core-api/src/main/java/org/gradle/api/attributes/DocsType.java
  subprojects/core-api/src/main/java/org/gradle/api/attributes/Sources.java
  subprojects/core-api/src/main/java/org/gradle/api/attributes/TestType.java
  subprojects/core-api/src/main/java/org/gradle/api/attributes/Usage.java
  subprojects/core-api/src/main/java/org/gradle/api/attributes/Verification.java
  subprojects/core/src/integTest/groovy/org/gradle/api/NamedDomainObjectCollectionSchemaIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultImmutableAttributes.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/LazyAttributesIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationPublications.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/DefaultIvyArtifactName.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationPublicationsTest.groovy
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/OutgoingVariantsReportTaskIntegrationTest.groovy
  subprojects/docs/src/samples/build-organization/structuring-software-projects/groovy/aggregation/test-coverage/build.gradle
  subprojects/docs/src/samples/build-organization/structuring-software-projects/groovy/build-logic/report-aggregation/src/main/groovy/com.example.report-aggregation.gradle
  subprojects/docs/src/samples/build-organization/structuring-software-projects/kotlin/aggregation/test-coverage/build.gradle.kts
  subprojects/docs/src/samples/build-organization/structuring-software-projects/kotlin/build-logic/commons/src/main/kotlin/com.example.jacoco.gradle.kts
  subprojects/docs/src/samples/build-organization/structuring-software-projects/kotlin/build-logic/report-aggregation/src/main/kotlin/com.example.report-aggregation.gradle.kts
  subprojects/docs/src/samples/java/jvm-multi-project-with-code-coverage/groovy/buildSrc/src/main/groovy/myproject.jacoco-aggregation.gradle
  subprojects/docs/src/samples/java/jvm-multi-project-with-code-coverage/groovy/buildSrc/src/main/groovy/myproject.java-conventions.gradle
  subprojects/docs/src/samples/java/jvm-multi-project-with-code-coverage/kotlin/buildSrc/src/main/kotlin/myproject.jacoco-aggregation.gradle.kts
  subprojects/docs/src/samples/java/jvm-multi-project-with-code-coverage/kotlin/buildSrc/src/main/kotlin/myproject.java-conventions.gradle.kts
  subprojects/docs/src/samples/java/jvm-multi-project-with-code-coverage/tests/testTask.out
  subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/file/TestFile.java
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoPluginIntegrationTest.groovy
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoPlugin.java
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/JavaPluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/JvmTestSuitePluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaLibraryConsumptionIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaLibraryCrossProjectTargetJvmVersionIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JvmTestSuitePlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/JvmTestSuite.java
Labels: in:test-suites

#18994 Use `server-api` as dependency
  .teamcity/pom.xml
Labels: @dev-productivity

#18995 Rebaseline TaskOutputCachingJavaPerformanceTest
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingJavaPerformanceTest.groovy
Labels: @dev-productivity

#18997 Disable stacktrace checking for TestVerificationFailureHandlingIntegr…
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestVerificationFailureHandlingIntegrationTest.groovy
Labels: @dev-productivity

#18504 Re-enable `in-memory script class loading cache releases memory of unused entries`
  subprojects/soak/src/integTest/kotlin/org/gradle/kotlin/dsl/caching/ScriptCachingIntegrationTest.kt
Labels: @dev-productivity

#18980 Fix leftover operation files in CC tests
  subprojects/configuration-cache/build.gradle.kts
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/fixtures/ToolingApiBackedGradleExecuter.groovy
Labels: @dev-productivity

#18863 Document dependency verification update process
  gradle/verification-metadata.xml
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/dependency_verification.adoc
Labels: in:dependency-verification

#18890 Document corner case
  subprojects/docs/src/docs/userguide/build-cache/build_cache.adoc
Labels: in:build-cache, a:documentation

#18937 Avoid unnecessary Gradleception builds
  .teamcity/src/main/kotlin/configurations/Gradleception.kt
Labels: @dev-productivity

#18959 Fix broken link in userguide
  subprojects/docs/src/docs/userguide/dep-man/06-publishing/publishing_maven.adoc
Labels: a:documentation

#19005 Clarify the role of Java Serialization in CC
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
Labels: @configuration-cache

#19000 Smoke test Kotlin 1.6.0
  subprojects/docs/src/docs/userguide/compatibility.adoc
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/KotlinGradlePluginVersions.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
Labels: @configuration-cache

#18925 Upgrade tested AGP versions
  gradle/dependency-management/agp-versions.properties
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerCachingSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy
Labels: @configuration-cache

#19039 Document `@ConfigurationCacheTest`
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/configurationcache/ConfigurationCacheTest.java
Labels: a:chore

#19022 Rename overloaded attribute method to remove ambiguity from extension method
  subprojects/core-api/src/main/java/org/gradle/api/attributes/AttributeContainer.java
  subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultImmutableAttributes.java
  subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultMutableAttributeContainer.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/attributes/DefaultMutableAttributeContainerTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/LazyAttributesIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/ResolveConfigurationResolutionBuildOperationResult.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/attributes/ImmutableAttributeContainerWithErrorMessage.java
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JvmTestSuitePlugin.java
Labels: @core, in:test-suites

#19045 Rebaseline performance tests onto nightly.
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidStudioMockupPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingNativePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingSwiftPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ArchiveTreePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/DeprecationCreationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ExcludeRuleMergingPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/IdeIntegrationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/LargeDependencyGraphPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ParallelDownloadsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/RichConsolePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/TaskCreationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/VerboseTestOutputPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaCleanAssemblePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationCachePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaDependencyReportPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaFirstUsePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIDEModelPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIncrementalExecutionPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaTasksPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeBuildDependentsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeCleanBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/RealWorldNativePluginPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftCleanBuildPerformanceTest.groovy
Labels: @core, in:test-suites

#19049 Rebaseline JavaFirstUsePerformanceTest
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaFirstUsePerformanceTest.groovy
Labels: @dev-productivity

#19053 Slightly increase memory for soak test
  subprojects/soak/src/integTest/kotlin/org/gradle/kotlin/dsl/caching/ScriptCachingIntegrationTest.kt
Labels: @dev-productivity

#18972 Fix Gradle 7 upgrade minor issues
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
Labels: a:documentation

#19055 Rebasline all performance tests
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidStudioMockupPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingJavaPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingNativePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingSwiftPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ArchiveTreePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/DeprecationCreationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ExcludeRuleMergingPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/IdeIntegrationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/LargeDependencyGraphPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ParallelDownloadsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/RichConsolePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/TaskCreationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/VerboseTestOutputPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaCleanAssemblePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationCachePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaDependencyReportPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIDEModelPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIncrementalExecutionPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaTasksPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeBuildDependentsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeCleanBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/RealWorldNativePluginPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftCleanBuildPerformanceTest.groovy
Labels: @dev-productivity

#18982 Document Toolchain precedence
  subprojects/docs/src/docs/userguide/jvm/toolchains.adoc
Labels: in:toolchains

#19036 Follow up on dependency verification update in release notes
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/dependency_verification.adoc
Labels: in:dependency-verification

#19035 Input artifact should only be an incremental input
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformInputArtifactIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java
  subprojects/dependency-management/src/testFixtures/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformTestFixture.groovy
Labels: @execution

#19061 Improve performance of JavaPlugin by avoiding requerying main sourceset
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java
Labels: @core, in:test-suites

#19021 Centralize build parameters
  build-logic/basics/src/main/kotlin/gradlebuild/basics/BuildEnvironment.kt
  build-logic/basics/src/main/kotlin/gradlebuild/basics/BuildParams.kt
  build-logic/basics/src/main/kotlin/gradlebuild/basics/kotlindsl/kotlin-dsl-upstream-candidates.kt
  build-logic/integration-testing/src/main/kotlin/gradlebuild/integrationtests/shared-configuration.kt
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
  build-logic/module-identity/src/main/kotlin/gradlebuild.module-identity.gradle.kts
  build-logic/packaging/src/main/kotlin/gradlebuild.install.gradle.kts
  build-logic/performance-testing/src/main/kotlin/gradlebuild/performance/PerformanceTestPlugin.kt
  build-logic/profiling/src/main/kotlin/gradlebuild.buildscan.gradle.kts
Labels: @dev-productivity

#19105 Archive HTML reports for flaky tests without leftover
  build-logic/buildquality/src/main/kotlin/gradlebuild/testcleanup/TestFilesCleanupService.kt
  build-logic/buildquality/src/test/kotlin/gradlebuild/testcleanup/TestFilesCleanupServiceTest.kt
Labels: @dev-productivity

#19108 Replace -highly experimental- with -experimental- in CC doc warning
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
Labels: @configuration-cache, in:documentation

#18988 Upgrade to newer version of santa tracker
  build-logic/performance-testing/src/main/groovy/gradlebuild.performance-templates.gradle
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/AndroidIncrementalExecutionPerformanceTest.groovy
  subprojects/smoke-test/build.gradle.kts
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerCachingSmokeTest.groovy
Labels: @execution

#19118 Don't collect configuration cache diagnostics after the report has been written
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultConfigurationCache.kt
  subprojects/core/src/main/java/org/gradle/internal/classpath/Instrumented.java
Labels: @configuration-cache

#19079 Add Gradle properties files to the configuration cache fingerprint
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOptionsIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheDependencyResolutionIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheGradlePropertiesIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheInitScriptsIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/isolated/IsolatedProjectsFixture.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/isolated/IsolatedProjectsToolingApiBuildActionIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprint.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintChecker.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintController.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintWriter.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/ConfigurationCacheStartParameter.kt
  subprojects/core-api/src/main/java/org/gradle/api/internal/properties/GradleProperties.java
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedTaskIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalBuildIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalInputsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalTaskInputsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskParametersIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradleProperties.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradlePropertiesController.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradlePropertiesLoader.java
  subprojects/core/src/main/java/org/gradle/initialization/ProjectPropertySettingBuildLoader.java
  subprojects/core/src/main/java/org/gradle/initialization/SettingsFactory.java
  subprojects/core/src/main/java/org/gradle/initialization/SystemPropertySettingGradlePropertiesLoader.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/BuildScopeServices.java
  subprojects/core/src/main/java/org/gradle/testfixtures/internal/TestBuildScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/initialization/DefaultGradlePropertiesLoaderTest.java
  subprojects/core/src/test/groovy/org/gradle/initialization/ProjectPropertySettingBuildLoaderTest.groovy
  subprojects/core/src/test/groovy/org/gradle/initialization/SettingsFactoryTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/artifactreuse/AliasedArtifactResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/caching/CachedMissingModulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ivy/IvyCustomStatusLatestVersionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ivy/IvyDynamicRevisionRemoteResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ivy/IvyModuleResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenPomPackagingResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenSnapshotResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/platforms/NativeAlignmentWithJavaPlatformResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/ComponentMetadataRulesCachingIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/suppliers/DynamicRevisionRemoteResolveWithMetadataSupplierIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIncrementalIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformInputArtifactIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformWithDependenciesIntegrationTest.groovy
  subprojects/dependency-management/src/testFixtures/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformTestFixture.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/language/swift/SwiftIncrementalCompileIntegrationTest.groovy
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/LauncherServices.java
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishIssuesIntegTest.groovy
Labels: @configuration-cache

#19086 Simplify `ProjectPropertySettingBuildLoader#CachingPropertyApplicator`
  subprojects/core/src/main/java/org/gradle/initialization/ProjectPropertySettingBuildLoader.java
Labels: a:chore

#19106 Fix flaky TestLauncherCrossVersionSpec
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r26/TestLauncherCrossVersionSpec.groovy
Labels: @dev-productivity

#19110 Re-enable ArtifactTransformCachingIntegrationTest for configuration caching
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
Labels: @dev-productivity

#19067 Fix multiple annotation processing issues discovered by Micronaut
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/AbstractIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/AggregatingIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/IsolatingIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/IncrementalResultStoringCompiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java
Labels: in:annotation-processing

#19111 Refine configuration-cache report after the addition of configuration inputs
  subprojects/configuration-cache-report/src/main/kotlin/ConfigurationCacheReportPage.kt
  subprojects/configuration-cache-report/src/main/kotlin/Main.kt
  subprojects/configuration-cache-report/src/main/kotlin/elmish/View.kt
  subprojects/configuration-cache-report/src/main/resources/configuration-cache-report.css
  subprojects/configuration-cache-report/src/test/resources/configuration-cache-report-data.js
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ConfigurationCacheProblems.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ConfigurationCacheReport.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/HtmlReportWriter.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/JsonModelWriter.kt
Labels: in:configuration-cache, @configuration-cache

#19119 Revert pull request #18729 for 7.4
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/ArtifactCollectionCodec.kt
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/ArtifactCollection.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/ArtifactCollectionResultProviderIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/UnpackingVisitor.java
  subprojects/file-collections/src/test/groovy/org/gradle/api/internal/file/collections/UnpackingVisitorTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/OutputScrapingExecutionResult.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/SmokeTestGradleRunner.groovy
Labels: @configuration-cache

#19062 Deprecate creating a tar tree without a backing file
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/SkipWhenEmptyIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/bundling/ArchiveIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/file/DefaultFileOperations.java
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskUpToDateIntegrationTest.groovy
Labels: @execution

#19091 Upgrade gretty for Smoke tests to 4.0.0
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GrettySmokeTest.groovy
Labels: @execution

#19092 Fix DependencyVerifier verification-metadata key comparison
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/verifier/DependencyVerifier.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/verifier/DependencyVerifierBuilder.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/verification/verifier/DependencyVerifierTest.groovy
Labels: in:dependency-verification

#19054 Add a flaky test quarantine job
  .teamcity/src/main/kotlin/configurations/FlakyTestQuarantine.kt
  .teamcity/src/main/kotlin/model/CIBuildModel.kt
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
Labels: @dev-productivity

#19125 Pass -PcommitId=HEAD when installing dogfood-second
  .teamcity/src/main/kotlin/configurations/Gradleception.kt
Labels: @dev-productivity

#19101 Enable pull request feature for all build types
  .teamcity/src/main/kotlin/common/Os.kt
  .teamcity/src/main/kotlin/common/extensions.kt
  .teamcity/src/main/kotlin/configurations/BaseGradleBuildType.kt
  .teamcity/src/main/kotlin/configurations/GradleBuildConfigurationDefaults.kt
  .teamcity/src/main/kotlin/configurations/SanityCheck.kt
  .teamcity/src/main/kotlin/configurations/SmokeTests.kt
  .teamcity/src/main/kotlin/model/CIBuildModel.kt
Labels: @dev-productivity

#19128 Only run continuous TAPI test on Gradle 3.0+
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r26/TestLauncherCrossVersionSpec.groovy
Labels: @dev-productivity

#19133 Prepare `DefaultGradlePropertiesLoader` to capture more configuration cache inputs
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradlePropertiesLoader.java
  subprojects/core/src/main/java/org/gradle/initialization/ProjectPropertySettingBuildLoader.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/Instrumented.java
  subprojects/core/src/test/groovy/org/gradle/initialization/DefaultGradlePropertiesLoaderTest.java
Labels: @configuration-cache

#19139 Introduce org.gradle.initialization.Environment build service
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultBuildModelControllerServices.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/services/Environment.kt
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradlePropertiesLoader.java
  subprojects/core/src/main/java/org/gradle/initialization/Environment.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/BuildScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/initialization/DefaultGradlePropertiesLoaderTest.groovy
  subprojects/core/src/test/groovy/org/gradle/initialization/DefaultGradlePropertiesLoaderTest.java
Labels: @configuration-cache

#19129 Smoke test CC with KGP and AGP only on versions with zero CC problems
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerCachingSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginAndroidGroovyDSLSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginAndroidKotlinDSLSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginSmokeTest.groovy
Labels: @configuration-cache

#19145 Use unified commit id for all Gradleception builds
  .teamcity/src/main/kotlin/configurations/Gradleception.kt
Labels: @dev-productivity

#19150 Create build scans for kill process steps
  .teamcity/src/main/kotlin/common/extensions.kt
  .teamcity/src/test/kotlin/PerformanceTestBuildTypeTest.kt
Labels: @dev-productivity

#19161 Merge release into master
  released-versions.json
  subprojects/docs/src/docs/release/notes.md
  version.txt
Labels: @dev-productivity

#19149 Fix issues in flaky test quarantine builds
  .teamcity/src/main/kotlin/configurations/FlakyTestQuarantine.kt
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
Labels: @dev-productivity

#19127 Accept KotlinJsIrLink cache miss
  build-logic/profiling/src/main/kotlin/gradlebuild.buildscan.gradle.kts
Labels: @dev-productivity

#19162 Mark a flaky test
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginTest.kt
Labels: @dev-productivity

#19164 Rebaseline JavaIncrementalExecutionPerformanceTest
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIncrementalExecutionPerformanceTest.groovy
Labels: @dev-productivity

#19163 Remark ArtifactTransformCachingIntegrationTest as flaky
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
Labels: @dev-productivity

#19121 Replay ignored hierarchies when enabling watching
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WatchableHierarchies.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdaterTest.groovy
  subprojects/files/src/main/java/org/gradle/internal/file/FileHierarchySet.java
Labels: @execution

#19096 Update attributes used for verification task output
  subprojects/core-api/src/main/java/org/gradle/api/attributes/Category.java
  subprojects/core-api/src/main/java/org/gradle/api/attributes/DocsType.java
  subprojects/core-api/src/main/java/org/gradle/api/attributes/TestSuiteName.java
  subprojects/core-api/src/main/java/org/gradle/api/attributes/TestSuiteTargetName.java
  subprojects/core-api/src/main/java/org/gradle/api/attributes/TestSuiteType.java
  subprojects/core-api/src/main/java/org/gradle/api/attributes/Usage.java
  subprojects/core-api/src/main/java/org/gradle/api/attributes/VerificationType.java
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/OutgoingVariantsReportTaskIntegrationTest.groovy
  subprojects/docs/src/docs/userguide/dep-man/04-modeling-features/variant_attributes.adoc
  subprojects/docs/src/samples/build-organization/structuring-software-projects/groovy/build-logic/report-aggregation/src/main/groovy/com.example.report-aggregation.gradle
  subprojects/docs/src/samples/build-organization/structuring-software-projects/kotlin/build-logic/report-aggregation/src/main/kotlin/com.example.report-aggregation.gradle.kts
  subprojects/docs/src/samples/java/jvm-multi-project-with-code-coverage/groovy/buildSrc/src/main/groovy/myproject.jacoco-aggregation.gradle
  subprojects/docs/src/samples/java/jvm-multi-project-with-code-coverage/kotlin/buildSrc/src/main/kotlin/myproject.jacoco-aggregation.gradle.kts
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoAggregationIntegrationTest.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoPluginIntegrationTest.groovy
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoCoverageReport.java
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoPlugin.java
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoReportAggregationPlugin.java
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/JavaPluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/JvmTestSuitePluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/TestReportAggregationPluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaLibraryCrossProjectTargetJvmVersionIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JvmTestSuitePlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/TestReportAggregationPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/JvmTestSuite.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/AggregateTestReport.java
Labels: a:feature, @core, in:test-suites

#19172 Capture Gradle property defining system properties and environment variables in the configuration cache fingerprint
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheGradlePropertiesIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultConfigurationCache.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/extensions/MapExtensions.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprint.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintChecker.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintWriter.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/services/Environment.kt
  subprojects/core-api/src/main/java/org/gradle/api/internal/properties/GradleProperties.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradleProperties.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradlePropertiesController.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradlePropertiesLoader.java
  subprojects/core/src/main/java/org/gradle/initialization/Environment.java
  subprojects/core/src/main/java/org/gradle/initialization/GradlePropertiesController.java
  subprojects/core/src/main/java/org/gradle/initialization/ProjectPropertySettingBuildLoader.java
  subprojects/core/src/main/java/org/gradle/initialization/SettingsFactory.java
  subprojects/core/src/main/java/org/gradle/testfixtures/internal/TestBuildScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/initialization/DefaultGradlePropertiesLoaderTest.groovy
Labels: @configuration-cache

#18955 Document missing start parameters and add shorthands for others.
  subprojects/docs/src/docs/userguide/reference/command_line_interface.adoc
Labels: in:console, a:documentation
