Repository gradle/gradle, pull requests merged in 2021-07, with the labels that each got.

#17578 Let FileCollection ElementsProvider expose a changing execution time value when appropriate
  subprojects/file-collections/src/integTest/groovy/org/gradle/api/file/FileCollectionIntegrationTest.groovy
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/AbstractFileCollection.java
Labels: @configuration-cache, in:core

#17545 Check if the autoprovisioned JDK can satisfy toolchain spec early
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/install/internal/AdoptOpenJdkRemoteBinary.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/install/internal/DefaultJavaToolchainProvisioningService.java
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/toolchain/install/internal/DefaultJavaToolchainProvisioningServiceTest.groovy
Labels: @core

#17585 Let collection properties backed by providers expose a changing execution time value when appropriate
  build-logic/performance-testing/src/main/groovy/gradlebuild.performance-templates.gradle
  gradle/dependency-management/agp-versions.properties
  subprojects/docs/src/docs/userguide/compatibility.adoc
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java
  subprojects/smoke-test/build.gradle.kts
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerCachingSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy
Labels: @configuration-cache, in:core

#17605 Rebaseline ArchiveTreePerformanceTest
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ArchiveTreePerformanceTest.groovy
Labels: @execution

#17591 Turn `:data-structures` into `:functional`
  .github/CODEOWNERS
  .idea/inspectionProfiles/Gradle.xml
  .teamcity/subprojects.json
  settings.gradle.kts
  subprojects/base-services/src/main/java/org/gradle/internal/UncheckedException.java
  subprojects/configuration-cache/build.gradle.kts
  subprojects/core/build.gradle.kts
  subprojects/data-structures/build.gradle.kts
  subprojects/dependency-management/build.gradle.kts
  subprojects/diagnostics/build.gradle.kts
  subprojects/ear/build.gradle.kts
  subprojects/execution/build.gradle.kts
  subprojects/functional/build.gradle.kts
  subprojects/functional/src/main/java/org/gradle/internal/Either.java
  subprojects/functional/src/main/java/org/gradle/internal/Try.java
  subprojects/functional/src/main/java/org/gradle/internal/collect/PersistentList.java
  subprojects/functional/src/main/java/org/gradle/internal/io/IoConsumer.java
  subprojects/functional/src/main/java/org/gradle/internal/io/IoFunction.java
  subprojects/functional/src/main/java/org/gradle/internal/io/IoPredicate.java
  subprojects/functional/src/main/java/org/gradle/internal/io/IoSupplier.java
  subprojects/functional/src/main/java/org/gradle/internal/io/package-info.java
  subprojects/functional/src/main/java/org/gradle/internal/lazy/Lazy.java
  subprojects/functional/src/main/java/org/gradle/internal/lazy/LockingLazy.java
  subprojects/functional/src/main/java/org/gradle/internal/lazy/SynchronizedLazy.java
  subprojects/functional/src/main/java/org/gradle/internal/lazy/UnsafeLazy.java
  subprojects/functional/src/main/java/org/gradle/internal/package-info.java
  subprojects/functional/src/main/java/org/gradle/internal/serialization/Cached.java
  subprojects/functional/src/main/java/org/gradle/internal/serialization/Transient.java
  subprojects/functional/src/test/groovy/org/gradle/internal/TryTest.groovy
  subprojects/functional/src/test/groovy/org/gradle/internal/collect/PersistentListTest.groovy
  subprojects/functional/src/test/groovy/org/gradle/internal/io/AbstractIoTest.groovy
  subprojects/functional/src/test/groovy/org/gradle/internal/io/IoConsumerTest.groovy
  subprojects/functional/src/test/groovy/org/gradle/internal/io/IoFunctionTest.groovy
  subprojects/functional/src/test/groovy/org/gradle/internal/io/IoPredicateTest.groovy
  subprojects/functional/src/test/groovy/org/gradle/internal/io/IoSupplierTest.groovy
  subprojects/functional/src/test/groovy/org/gradle/internal/lazy/LazyTest.groovy
  subprojects/kotlin-dsl-provider-plugins/build.gradle.kts
  subprojects/kotlin-dsl/build.gradle.kts
  subprojects/maven/build.gradle.kts
  subprojects/model-core/build.gradle.kts
  subprojects/platform-jvm/build.gradle.kts
  subprojects/publish/build.gradle.kts
  subprojects/tooling-api-builders/build.gradle.kts
Labels: @execution

#17608 Wait longer for the configuration cache report thread to finish
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ConfigurationCacheReport.kt
Labels: @configuration-cache, in:configuration-cache

#17597 Replace dev12 mirror with repo.grdev.net
  .teamcity/src/main/kotlin/common/extensions.kt
  .teamcity/src/main/kotlin/configurations/GradleBuildConfigurationDefaults.kt
  .teamcity/src/test/kotlin/CIConfigIntegrationTests.kt
  build-logic/jvm/src/main/kotlin/gradlebuild/jvm/argumentproviders/CiEnvironmentProvider.kt
  gradle/shared-with-buildSrc/mirrors.settings.gradle.kts
Labels: @dev-productivity

#17617 Fix error message if Java 9+ JRE is used for compilation instead of JDK
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JdkTools.java
Labels: @core

#17620 Upgradle idea-ext plugin to 1.0.1
  build-logic/build-platform/build.gradle.kts
  gradle/verification-metadata.xml
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildExternalPluginsValidationSmokeTest.groovy
Labels: @execution

#17568 Validate DisableCachingByDefault annotation
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.build-logic.kotlin-dsl-gradle-plugin.gradle.kts
  build-logic/buildquality/src/main/kotlin/gradlebuild.task-properties-validation.gradle.kts
  build-logic/publishing/src/main/kotlin/gradlebuild.kotlin-dsl-plugin-bundle.gradle.kts
  subprojects/docs/src/docs/userguide/troubleshooting/validation_problems.adoc
  subprojects/execution/src/main/java/org/gradle/internal/execution/impl/DefaultWorkValidationContext.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/resolver/FindGradleSources.java
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/resolver/FindGradleSources.kt
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/DefaultTypeValidationContext.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/problems/ValidationProblemId.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/validation/TypeValidationProblem.java
  subprojects/model-core/src/test/groovy/org/gradle/internal/reflect/validation/ValidationMessageCheckerTest.groovy
  subprojects/model-core/src/testFixtures/groovy/org/gradle/internal/reflect/validation/ValidationMessageChecker.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/AbstractPluginValidationIntegrationSpec.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidatePluginsIntegrationTest.groovy
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/internal/ValidateAction.java
Labels: @execution

#17636 Disable ArtifactTransformCachingIntegrationTest only for ConfigCache executer
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
Labels: @dev-productivity

#17642 Clarify that collections of files are accepted for SkipWhenEmpty and PathSensitive
  subprojects/docs/src/docs/userguide/authoring-builds/more_about_tasks.adoc
Labels: @execution

#17629 Cap number of reported configuration cache problems
  subprojects/configuration-cache-report/src/main/kotlin/ConfigurationCacheReportPage.kt
  subprojects/configuration-cache-report/src/main/kotlin/Main.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ConfigurationCacheProblems.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ConfigurationCacheProblemsSummary.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ConfigurationCacheReport.kt
  subprojects/core/src/main/java/org/gradle/api/internal/StartParameterInternal.java
Labels: @configuration-cache, in:configuration-cache

#17599 Use archunit freezing rules to accept violations
  build-logic/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
  subprojects/architecture-test/build.gradle.kts
  subprojects/architecture-test/src/changes/archunit_store/599bf77e-e598-4e41-bbc4-47951bba0c0f
  subprojects/architecture-test/src/changes/archunit_store/b422a7b8-e77b-4a79-934b-70b4cfd5eebd
  subprojects/architecture-test/src/changes/archunit_store/stored.rules
  subprojects/architecture-test/src/test/java/org/gradle/architecture/test/ArchUnitFixture.java
  subprojects/architecture-test/src/test/java/org/gradle/architecture/test/FreezeInstructionsPrintingArchRule.java
  subprojects/architecture-test/src/test/java/org/gradle/architecture/test/KotlinCompatibilityTest.java
  subprojects/architecture-test/src/test/java/org/gradle/architecture/test/TempDirectoryCreationControlTest.java
  subprojects/distributions-dependencies/build.gradle.kts
Labels: @dev-productivity

#17655 Update Android sample to not require custom resolution strategy for the plugin
  subprojects/docs/src/samples/android-application/groovy/app/build.gradle
  subprojects/docs/src/samples/android-application/groovy/settings.gradle
  subprojects/docs/src/samples/android-application/kotlin/app/build.gradle.kts
  subprojects/docs/src/samples/android-application/kotlin/settings.gradle.kts
Labels: @core, a:documentation

#17637 Remove bintray repo from santaTracker
  build-logic/performance-testing/src/main/groovy/gradlebuild.performance-templates.gradle
  gradle/shared-with-buildSrc/mirrors.settings.gradle.kts
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/KotlinDslTestUtil.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/RepoScriptBlockUtil.groovy
  subprojects/smoke-test/build.gradle.kts
Labels: @dev-productivity

#17635 A trivial fix of StringIndexOutOfBoundsException produced by a initialization script starts with dot
  subprojects/core/src/integTest/groovy/org/gradle/api/InitScriptExecutionIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/groovy/scripts/TextResourceScriptSource.java
Labels: a:chore

#17640 Enable stricter task validation for the Gradle build
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.build-logic.kotlin-dsl-gradle-plugin.gradle.kts
  build-logic/binary-compatibility/src/main/groovy/gradlebuild/binarycompatibility/CleanAcceptedApiChanges.groovy
  build-logic/binary-compatibility/src/main/groovy/gradlebuild/binarycompatibility/transforms/ExplodeZipAndFindJars.groovy
  build-logic/binary-compatibility/src/main/groovy/gradlebuild/binarycompatibility/transforms/FindGradleClasspath.groovy
  build-logic/binary-compatibility/src/main/groovy/gradlebuild/binarycompatibility/transforms/FindGradleJars.groovy
  build-logic/build-init-samples/src/main/kotlin/gradlebuild/samples/tasks/GenerateSample.kt
  build-logic/build-update-utils/src/main/kotlin/gradlebuild/buildutils/tasks/CheckSubprojectsInfo.kt
  build-logic/build-update-utils/src/main/kotlin/gradlebuild/buildutils/tasks/GenerateSubprojectsInfo.kt
  build-logic/build-update-utils/src/main/kotlin/gradlebuild/buildutils/tasks/SubprojectsInfo.kt
  build-logic/build-update-utils/src/main/kotlin/gradlebuild/buildutils/tasks/UpdateAgpVersions.kt
  build-logic/build-update-utils/src/main/kotlin/gradlebuild/buildutils/tasks/UpdateInitPluginTemplateVersionFile.kt
  build-logic/build-update-utils/src/main/kotlin/gradlebuild/buildutils/tasks/UpdateReleasedVersions.kt
  build-logic/buildquality/src/main/kotlin/gradlebuild.task-properties-validation.gradle.kts
  build-logic/buildquality/src/main/kotlin/gradlebuild/configcachereport/tasks/VerifyDevWorkflow.kt
  build-logic/buildquality/src/main/kotlin/gradlebuild/quickcheck/tasks/QuickCheckTask.kt
  build-logic/cleanup/src/main/kotlin/gradlebuild/cleanup/tasks/KillLeakingJavaProcesses.kt
  build-logic/integration-testing/src/main/kotlin/gradlebuild/integrationtests/tasks/DistributionTest.kt
  build-logic/kotlin-dsl/src/main/kotlin/gradlebuild/kotlindsl/compiler/tasks/CheckKotlinCompilerEmbeddableDependencies.kt
  build-logic/kotlin-dsl/src/main/kotlin/gradlebuild/kotlindsl/generator/tasks/CodeGenerationTask.kt
  build-logic/kotlin-dsl/src/main/kotlin/gradlebuild/kotlindsl/generator/tasks/GenerateKotlinDependencyExtensions.kt
  build-logic/kotlin-dsl/src/main/kotlin/gradlebuild/kotlindsl/generator/tasks/GenerateKotlinDslPluginsExtensions.kt
  build-logic/module-identity/src/main/kotlin/gradlebuild/identity/tasks/BuildReceipt.kt
  build-logic/packaging/src/main/kotlin/gradlebuild/run/tasks/RunEmbeddedGradle.kt
  build-logic/packaging/src/main/kotlin/gradlebuild/shade/tasks/ShadedJar.kt
  build-logic/packaging/src/main/kotlin/gradlebuild/shade/transforms/ShadeClasses.kt
  build-logic/performance-testing/src/main/groovy/gradlebuild/performance/generator/tasks/AbstractProjectGeneratorTask.groovy
  build-logic/performance-testing/src/main/groovy/gradlebuild/performance/generator/tasks/BuildBuilderGenerator.groovy
  build-logic/performance-testing/src/main/groovy/gradlebuild/performance/generator/tasks/CppMultiProjectGeneratorTask.groovy
  build-logic/performance-testing/src/main/groovy/gradlebuild/performance/generator/tasks/JavaExecProjectGeneratorTask.groovy
  build-logic/performance-testing/src/main/groovy/gradlebuild/performance/generator/tasks/KtsProjectGeneratorTask.groovy
  build-logic/performance-testing/src/main/groovy/gradlebuild/performance/generator/tasks/MonolithicNativeProjectGeneratorTask.groovy
  build-logic/performance-testing/src/main/groovy/gradlebuild/performance/generator/tasks/NativeProjectGeneratorTask.groovy
  build-logic/performance-testing/src/main/groovy/gradlebuild/performance/generator/tasks/NativeProjectWithDepsGeneratorTask.groovy
  build-logic/performance-testing/src/main/groovy/gradlebuild/performance/generator/tasks/ProjectGeneratorTask.groovy
  build-logic/performance-testing/src/main/groovy/gradlebuild/performance/generator/tasks/RemoteProject.groovy
  build-logic/performance-testing/src/main/groovy/gradlebuild/performance/generator/tasks/TemplateProjectGeneratorTask.groovy
  build-logic/performance-testing/src/main/groovy/gradlebuild/performance/tasks/RebaselinePerformanceTests.groovy
  build-logic/performance-testing/src/main/kotlin/gradlebuild/performance/tasks/BuildCommitDistribution.kt
  build-logic/performance-testing/src/main/kotlin/gradlebuild/performance/tasks/DetermineBaselines.kt
  build-logic/performance-testing/src/main/kotlin/gradlebuild/performance/tasks/PerformanceTestReport.kt
  build-logic/profiling/src/main/kotlin/gradlebuild/buildscan/tasks/ExtractCodeQualityBuildScanData.kt
  build-logic/profiling/src/main/kotlin/gradlebuild/jmh/tasks/JmhHTMLReport.kt
  build-logic/publishing/src/main/kotlin/gradlebuild.kotlin-dsl-plugin-bundle.gradle.kts
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/UnzipTransform.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/resolver/FindGradleSources.java
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/resolver/FindGradleSources.kt
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/internal/ValidateAction.java
Labels: @execution

#17664 Upgrade to newer Gradle profiler snapshot
  gradle/verification-metadata.xml
  subprojects/distributions-dependencies/build.gradle.kts
Labels: @execution

#17258 Update Android plugin version in GMM test
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ThirdPartyGradleModuleMetadataSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/consumer/android-app/build.gradle.kts
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/consumer/android-kotlin-app/build.gradle.kts
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/producer/android-kotlin-library/build.gradle.kts
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/producer/android-library-single-variant/build.gradle.kts
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/producer/android-library/build.gradle.kts
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/producer/kotlin-multiplatform-android-library/build.gradle.kts
Labels: @core

#17668 Enable mirror on EC2 as well
  gradle/shared-with-buildSrc/mirrors.settings.gradle.kts
Labels: @dev-productivity

#17557 Add transitive implementation dependencies to the PMD auxclasspath
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/pmd/PmdPluginAuxclasspathIntegrationTest.groovy
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdPlugin.java
  subprojects/docs/src/docs/userguide/core-plugins/pmd_plugin.adoc
Labels: @core

#17687 Publish module for functional project
  subprojects/functional/build.gradle.kts
Labels: @execution, a:chore

#17648 Use line ending normalization for JavaCompile tasks
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/authoring-builds/more_about_tasks.adoc
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileLineEndingSensitivityIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingJavaPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationCachePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIncrementalExecutionPerformanceTest.groovy
Labels: @execution, a:feature, in:java-plugins

#17688 Provide more context around Kotlin DSL script class loading failures
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/execution/CompiledScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/execution/Interpreter.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/KotlinScriptEvaluator.kt
  subprojects/kotlin-dsl/src/testFixtures/kotlin/org/gradle/kotlin/dsl/fixtures/SimplifiedKotlinScriptEvaluator.kt
Labels: @configuration-cache, in:kotlin-dsl

#17686 Fix `kotlin-dsl` plugin version used in `build-logic-commons/code-quality`
  build-logic-commons/code-quality/build.gradle.kts
Labels: @configuration-cache

#17700 Revert "Update groovy from 3.0.7 to 3.0.8"
  build-logic/build-platform/build.gradle.kts
  subprojects/docs/src/samples/groovy/library-publishing/kotlin/my-library/build.gradle.kts
Labels: @core, in:core

#17710 Fix flaky ThirdPartyGradleModuleMetadataSmokeTest
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ThirdPartyGradleModuleMetadataSmokeTest.groovy
Labels: @dev-productivity

#17693 Split DeferredTaskDefinitionIntegrationTest
  subprojects/core/src/integTest/groovy/org/gradle/api/HttpScriptPluginIntegrationSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/AbstractDeferredTaskDefinitionIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/DeferredTaskConfigurationIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/DeferredTaskCreationIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/DeferredTaskDefinitionIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/DeferredTaskFailureIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/DeferredTaskOverwritingIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/buildsrc/BuildSrcBuildOperationsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/process/internal/RemoteProcess.java
Labels: @dev-productivity

#17694 Further split DomainObjectIntegrationTest
  subprojects/core/src/integTest/groovy/org/gradle/api/AbstractMutatingDomainObjectContainerInHookIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/AbstractMutationFailureDomainObjectContainerIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/AbstractQueryAndMutationDomainObjectContainerIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/AbstractQueryDomainObjectContainerIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/MutationFailureFromConfigureEachDomainObjectContainerIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/MutationFailureFromMatchingConfigureEachDomainObjectContainerIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/MutationFailureFromProviderConfigureDomainObjectContainerIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/MutationFailureFromProviderConfigureRealizedDomainObjectContainerIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/MutationFailureFromRegisterDomainObjectContainerIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/MutationFailureFromWithTypeConfigureEachDomainObjectContainerIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/NamedDomainObjectContainerIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/QueryAndMutateFromAllDomainObjectContainerIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/QueryAndMutateFromCreateDomainObjectContainerIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/QueryAndMutateFromGetByNameDomainObjectContainerIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/QueryAndMutateFromWithTypeAllDomainObjectContainerIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/QueryAndMutateFromWithTypeGetByNameDomainObjectContainerIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/TaskContainerIntegrationTest.groovy
Labels: @dev-productivity

#17698 Upgrade `asm` version to `9.2`
  build-logic/build-platform/build.gradle.kts
Labels: @configuration-cache

#17692 Increase client VM heap for build scan performance
  gradle/verification-metadata.xml
  subprojects/build-scan-performance/build.gradle.kts
  subprojects/build-scan-performance/src/performanceTest/groovy/org/gradle/performance/BuildScanPluginPerformanceTest.groovy
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/AbstractCrossBuildPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/CrossVersionPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleBuildExperimentRunner.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleBuildExperimentSpec.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleInvocationSpec.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleVsMavenPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/InvocationSpec.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/JavaTestProject.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/MavenInvocationSpec.groovy
Labels: @dev-productivity

#17696 Rebaseline all performance tests
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidStudioMockupPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingJavaPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingNativePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingSwiftPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ArchiveTreePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/DeprecationCreationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ExcludeRuleMergingPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/IdeIntegrationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/LargeDependencyGraphPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ParallelDownloadsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/RichConsolePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/TaskCreationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/VerboseTestOutputPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/WorkerApiPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaCleanAssemblePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationCachePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaDependencyReportPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaFirstUsePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIDEModelPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIncrementalExecutionPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaTasksPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/kotlindsl/GradleKotlinDslBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeBuildDependentsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeCleanBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/RealWorldNativePluginPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftCleanBuildPerformanceTest.groovy
Labels: @execution

#17718 Fix flaky can lint Santa-Tracker
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy
Labels: @dev-productivity

#17712 Update Groovy to 3.0.8 for JDK17 support
  build-logic/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
  gradle/verification-metadata.xml
  subprojects/docs/src/docs/userguide/compatibility.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/samples/groovy/library-publishing/groovy/my-library/build.gradle
  subprojects/docs/src/samples/groovy/library-publishing/kotlin/my-library/build.gradle.kts
  subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/AbstractSourcesAndJavadocJarsIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/DefaultGradleDistribution.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/DefaultOutputDirSelector.groovy
  subprojects/model-core/src/testFixtures/groovy/org/gradle/internal/reflect/validation/ValidationMessageChecker.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/tasks/GroovyRuntimeTest.groovy
Labels: @core

#17721 Only initialize JANSI when native services are enabled
  subprojects/native/src/main/java/org/gradle/internal/nativeintegration/services/NativeServices.java
Labels: @execution

#17728 Increase memory for architecture tests
  subprojects/architecture-test/build.gradle.kts
Labels: @dev-productivity

#17715 Fix incremental annotation processing for package info files
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/AbstractIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/AggregatingIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/RecompilationSpec.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/WellKnownSourceFileClassNameConverter.java
  subprojects/language-java/src/testFixtures/groovy/org/gradle/language/fixtures/AnnotationProcessorFixture.groovy
  subprojects/language-java/src/testFixtures/groovy/org/gradle/language/fixtures/PackageInfoGeneratedClassProcessorFixture.groovy
Labels: @execution

#17674 Stop throwing exceptions from isPresent() of the Provider.zip() result
  subprojects/model-core/src/integTest/groovy/org/gradle/api/provider/ProviderIntegrationTest.groovy
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/BiProvider.java
Labels: @core

#17724 Remove unused partial invalidation method on GradleExecuter
  subprojects/core/src/integTest/groovy/org/gradle/internal/operations/logging/LoggingBuildOperationProgressIntegTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/AbstractGradleExecuter.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/GradleExecuter.java
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/m8/ToolingApiLoggingCrossVersionSpec.groovy
Labels: @execution

#17737 Remove maxParallelForks=16 when testDistribution enabled
  .teamcity/src/main/kotlin/configurations/FunctionalTest.kt
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
Labels: @dev-productivity

#17582 Make configuration cache reports content addressable
  subprojects/configuration-cache/build.gradle.kts
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheProblemReportingIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ConfigurationCacheProblems.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ConfigurationCacheReport.kt
  subprojects/hashing/src/main/java/org/gradle/internal/hash/Hashing.java
  subprojects/hashing/src/main/java/org/gradle/internal/hash/HashingOutputStream.java
Labels: @configuration-cache, in:configuration-cache

#17741 Update PMD to latest 6.36.0
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/Pmd.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdExtension.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdPlugin.java
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
Labels: @core

#17753 Support tests that need -XstartOnFirstThread
  subprojects/docs/src/docs/release/notes.md
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestWorker.java
Labels: @core, a:feature

#17739 Pass Java installations to TAPI toolchain tests
  subprojects/tooling-api/src/integTest/groovy/org/gradle/integtests/tooling/ToolingApiClientJdkCompatibilityTest.groovy
Labels: @dev-productivity

#17695 Split VersionRangeResolveIntegrationTest
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/AbstractVersionRangeResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/VersionRangeResolvePairIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/VersionRangeResolvePreferPairIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/VersionRangeResolveRejectPairIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/ComponentReplacementIntegrationTest.groovy
Labels: @dev-productivity

#17764 Upgrade to newer native platform version
  build-logic/profiling/src/main/kotlin/gradlebuild.jmh.gradle.kts
  subprojects/distributions-dependencies/build.gradle.kts
Labels: @execution

#17747 Unignore passing tests
  subprojects/build-cache/src/integTest/groovy/org/gradle/caching/local/internal/DirectoryBuildCacheCleanupIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/file/ArchiveOperationsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/ExecutionResultExecTaskDeprecationIntegrationTest.groovy
  subprojects/core/src/test/groovy/org/gradle/process/internal/DefaultExecHandleSpec.groovy
Labels: @core

#17766 Minor cleanup in TestWorker
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestWorker.java
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestingIntegrationTest.groovy
Labels: @core, a:chore

#17770 Let configuration cache preserve TreeMap comparator
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheSupportedTypesIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/CollectionCodecs.kt
Labels: @configuration-cache

#17775 Disable file system watching on FAT
  subprojects/docs/src/docs/userguide/running-builds/gradle_daemon.adoc
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/DefaultWatchableFileSystemDetector.java
Labels: @execution

#17776 Restore support for Kotlin 1.3.72
  subprojects/docs/src/docs/userguide/compatibility.adoc
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/KotlinGradlePluginVersions.groovy
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginGradlePluginCrossVersionSmokeTest.kt
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginSmokeTest.groovy
Labels: @configuration-cache

#17672 Add an option to escape backslash when doing Copy.expand
  subprojects/core-api/src/main/java/org/gradle/api/file/ContentFilterable.java
  subprojects/core-api/src/main/java/org/gradle/api/file/CopySpec.java
  subprojects/core-api/src/main/java/org/gradle/api/file/ExpandDetails.java
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/file/DefaultFileOperations.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/CopyActionExecuter.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/CopyFileVisitorImpl.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/CopySpecActionImpl.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/CopySpecBackedCopyActionProcessingStream.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/CopySpecWrapper.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultFileCopyDetails.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DelegatingCopySpecInternal.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/FileCopier.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/FilterChain.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/NormalizingCopyActionDecorator.java
  subprojects/core/src/main/java/org/gradle/api/tasks/AbstractCopyTask.java
  subprojects/core/src/main/java/org/gradle/api/tasks/bundling/AbstractArchiveTask.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/WorkerSharedProjectScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/DefaultFileOperationsTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/copy/CopyActionExecuterTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/copy/CopyFileVisitorImplTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/copy/CopySpecActionImplTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/copy/CopySpecBackedCopyActionProcessingStreamTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/copy/DefaultCopySpecTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/copy/DuplicateHandlingCopyActionExecutorTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/copy/FilterChainTest.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/copy/SyncCopyActionDecoratorTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/api/internal/file/TestFiles.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/kotlin-dsl/src/integTest/kotlin/org/gradle/kotlin/dsl/codegen/ApiTypeProviderTest.kt
Labels: @core

#17740 Re-use fingerprints from execution history when possible
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/AbsolutePathFileCollectionFingerprinter.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/AbstractFileCollectionFingerprinter.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/FileCollectionFingerprinterRegistrations.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/FingerprinterRegistration.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/IgnoredPathFileCollectionFingerprinter.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/NameOnlyFileCollectionFingerprinter.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/RelativePathFileCollectionFingerprinter.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuterTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/fingerprint/impl/AbsolutePathFileCollectionFingerprinterTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformer.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactoryTest.groovy
  subprojects/execution/src/integTest/groovy/org/gradle/internal/execution/IncrementalExecutionIntegrationTest.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/fingerprint/FileCollectionFingerprinter.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/fingerprint/InputFingerprinter.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/fingerprint/impl/DefaultInputFingerprinter.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/history/impl/DefaultExecutionHistoryStore.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/history/impl/FileCollectionFingerprintSerializer.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/history/impl/SerializableFileCollectionFingerprint.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CaptureStateBeforeExecutionStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/IdentifyStep.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/fingerprint/impl/DefaultInputFingerprinterTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/history/changes/ClasspathCompareStrategyTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/history/changes/FingerprintCompareStrategyTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/history/changes/NonIncrementalInputChangesTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/history/impl/FileCollectionFingerprintSerializerTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CaptureStateBeforeExecutionStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/IdentifyStepTest.groovy
  subprojects/execution/src/testFixtures/groovy/org/gradle/internal/execution/TestExecutionHistoryStore.java
  subprojects/normalization-java/src/main/java/org/gradle/internal/fingerprint/classpath/impl/ClasspathFingerprintingStrategy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/FileCollectionFingerprint.java
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/FingerprintingStrategy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/impl/AbsolutePathFingerprintingStrategy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/impl/AbstractFingerprintingStrategy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/impl/DefaultCurrentFileCollectionFingerprint.java
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/impl/EmptyCurrentFileCollectionFingerprint.java
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/impl/IgnoredPathFingerprintingStrategy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/impl/NameOnlyFingerprintingStrategy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/impl/RelativePathFingerprintingStrategy.java
Labels: @execution

#17782 Serialize Scala incremental compiler options to the configuration cache
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractProjectRelocationIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractTaskRelocationIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/ForkCapableRelocationIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/integtests/ScalaProjectIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/CachedScalaCompileIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/ForceScalaCompileIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/IncrementalScalaCompileIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/ScalaIncrementalCompileIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/UpToDateScalaCompileIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/ZincScalaCompilerIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/scaladoc/ScalaDocIntegrationTest.groovy
  subprojects/scala/src/main/java/org/gradle/language/scala/tasks/BaseScalaCompileOptions.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/play/integtest/external/PlayExternalContinuousBuildIntegrationTest.groovy
Labels: @configuration-cache

#17714 Discard the object body when doing metadata request to S3
  subprojects/resources-s3/src/main/java/org/gradle/internal/resource/transport/aws/s3/S3ResourceConnector.java
Labels: @core

#17781 Remove Kotlin JPMS workaround for Java 16
  subprojects/base-services/src/main/java/org/gradle/internal/jvm/JpmsConfiguration.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/configuration/DaemonParameters.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ThirdPartyGradleModuleMetadataSmokeTest.groovy
Labels: @core

#17791 Rebaseline all performance tests
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidStudioMockupPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingJavaPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingNativePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingSwiftPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ArchiveTreePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/DeprecationCreationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ExcludeRuleMergingPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/IdeIntegrationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/LargeDependencyGraphPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ParallelDownloadsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/RichConsolePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/TaskCreationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/VerboseTestOutputPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/WorkerApiPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaCleanAssemblePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationCachePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaDependencyReportPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaFirstUsePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIDEModelPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIncrementalExecutionPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaTasksPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/kotlindsl/GradleKotlinDslBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeBuildDependentsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeCleanBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/RealWorldNativePluginPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftCleanBuildPerformanceTest.groovy
Labels: @execution

#17794 Refine mirror settings
  .teamcity/src/main/kotlin/common/extensions.kt
  .teamcity/src/test/kotlin/ApplyDefaultConfigurationTest.kt
  .teamcity/src/test/kotlin/PerformanceTestBuildTypeTest.kt
  gradle/shared-with-buildSrc/mirrors.settings.gradle.kts
Labels: @dev-productivity

#17787 Polish release notes for 7.2
  subprojects/docs/src/docs/release/notes.md
  subprojects/launcher/src/main/resources/release-features.txt
Labels: @core

#17790 Fix flakiness in Santa Tracker smoke test
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractAndroidSantaTrackerSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractGradleceptionSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/SmokeTestGradleRunner.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/WithPluginValidation.groovy
Labels: @execution

#17780 Enable nagging for deprecated methods
  subprojects/core/src/main/java/org/gradle/api/tasks/bundling/AbstractArchiveTask.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginSmokeTest.groovy
Labels: @core

#17788 Add a parameter to control TD partition size
  .teamcity/src/main/kotlin/configurations/FunctionalTest.kt
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
Labels: @dev-productivity

#17393 Expose capability in resolved variant for artifact collection
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/ArtifactCollectionCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/transform/CalculateArtifactsCodec.kt
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/capabilities/CapabilitiesRulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/capabilities/PublishedCapabilitiesIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/ConfigurationInternal.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationPublications.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultVariant.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ArtifactCollectingVisitor.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/DefaultLenientConfiguration.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ResolvedArtifactCollectingVisitor.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ResolvedFilesCollectingVisitor.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/moduleconverter/DefaultLocalComponentMetadataBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/ArtifactBackedResolvedVariant.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/ArtifactVisitor.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/DefaultArtifactSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/LocalFileDependencyBackedArtifactSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/query/DefaultArtifactResolutionQuery.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/result/DefaultResolvedArtifactResult.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/result/DefaultResolvedVariantResult.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformedProjectArtifactSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformingAsyncArtifactListener.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/DefaultConfigurationMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ImmutableCapabilities.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/local/model/BuildableLocalComponentMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/local/model/DefaultLocalComponentMetadata.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/TestArtifactSet.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationSpec.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/moduleconverter/DefaultLocalComponentMetadataBuilderTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/ArtifactBackedResolvedVariantTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/LocalFileDependencyBackedArtifactSetTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/TransformingAsyncArtifactListenerTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/local/model/DefaultLocalComponentMetadataTest.groovy
Labels: @core, in:dependency-resolution

#17804 Mark groovy and scala plugins as supported with the configuration cache
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
  subprojects/scala/src/integTest/groovy/org/gradle/scala/ScalaPluginIntegrationTest.groovy
Labels: @configuration-cache

#17665 Upgrade tested AGP versions
  gradle/dependency-management/agp-versions.properties
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerCachingSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ThirdPartyGradleModuleMetadataSmokeTest.groovy
Labels: @configuration-cache

#17809 Simplify ClasspathHasher hierarchy
  subprojects/core/src/main/java/org/gradle/api/internal/initialization/loadercache/CompileClasspathHasher.java
  subprojects/core/src/main/java/org/gradle/api/internal/initialization/loadercache/DefaultClasspathHasher.java
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/BuildServices.kt
Labels: @execution

#17823 Add --illegal-access=permit to Kotlin compiler daemon on JDK16
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ThirdPartyGradleModuleMetadataSmokeTest.groovy
Labels: @dev-productivity

#17818 Fix incremental scala compilation
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/ScalaIncrementalCompileIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/ZincScalaCompilerIntegrationTest.groovy
  subprojects/scala/src/main/java/org/gradle/api/internal/tasks/scala/ZincScalaCompiler.java
Labels: @core

#17842 Fix incorrect toUpperCase
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
Labels: @dev-productivity

#17843 Merge distinct Scala incremental compiler test files
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/IncrementalScalaCompileIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/ScalaIncrementalCompileIntegrationTest.groovy
Labels: @core

#17845 Fix scala incremental compilation
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/ScalaIncrementalCompileIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/ZincScalaCompilerIntegrationTest.groovy
  subprojects/scala/src/main/java/org/gradle/api/internal/tasks/scala/ZincScalaCompiler.java
Labels: @core

#17850 Fix warnings in `build-logic`
  build-logic/binary-compatibility/src/main/kotlin/gradlebuild/binarycompatibility/sources/SourcesRepository.kt
  build-logic/documentation/src/test/groovy/gradlebuild/docs/UserGuideTransformTaskTest.groovy
  build-logic/module-identity/src/main/kotlin/gradlebuild/identity/extension/ReleasedVersionsDetails.kt
Labels: @configuration-cache

#17856 Add --illegal-access=permit to Kotlin compiler daemon on JDK16
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ThirdPartyGradleModuleMetadataSmokeTest.groovy
Labels: @dev-productivity

#17840 Fix variant capabilities information exposed through ArtifactViews
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/CapabilitiesCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/LocalFileDependencyBackedArtifactSetCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/transform/CalculateArtifactsCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/transform/TransformedArtifactCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/transform/TransformedProjectArtifactSetCodec.kt
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/moduleconverter/DefaultLocalComponentMetadataBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/ArtifactBackedResolvedVariant.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/DefaultArtifactSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/LocalFileDependencyBackedArtifactSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/ResolvedVariant.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ComponentState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/AbstractTransformedArtifactSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformedVariantFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformedExternalArtifactSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformedProjectArtifactSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformingAsyncArtifactListener.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ImmutableCapabilities.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ImmutableCapability.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/DefaultArtifactSetTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/TransformingAsyncArtifactListenerTest.groovy
Labels: in:dependency-resolution

#17862 Test coverage for variant capability information for artifact results
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/capabilities/CapabilitiesRulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/capabilities/PublishedCapabilitiesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy
Labels: in:dependency-resolution

#17866 Remove unused imports
  .teamcity/src/main/kotlin/util/WarmupEc2Agent.kt
Labels: @dev-productivity

#17863 Let configuration cache preserve iteration order of HashMap instances
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheSupportedTypesIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/CollectionCodecs.kt
Labels: @configuration-cache, in:configuration-cache

#17430 Document version catalog improvements
  subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/platforms.adoc
  subprojects/docs/src/snippets/dependencyManagement/catalogs-settings/groovy/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/catalogs-settings/groovy/settings.gradle
  subprojects/docs/src/snippets/dependencyManagement/catalogs-settings/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/catalogs-settings/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/catalogs-settings/tests/resolve.sample.conf
  subprojects/docs/src/snippets/dependencyManagement/catalogs-settings/tests/sanityCheck.sample.conf
  subprojects/docs/src/snippets/dependencyManagement/catalogs-toml/groovy/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/catalogs-toml/groovy/gradle/libs.versions.toml
  subprojects/docs/src/snippets/dependencyManagement/catalogs-toml/groovy/gradle/test-libs.versions.toml
  subprojects/docs/src/snippets/dependencyManagement/catalogs-toml/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/catalogs-toml/kotlin/gradle/libs.versions.toml
  subprojects/docs/src/snippets/dependencyManagement/catalogs-toml/kotlin/gradle/test-libs.versions.toml
  subprojects/docs/src/snippets/java/toolchain-task/groovy/build.gradle
  subprojects/docs/src/snippets/java/toolchain-task/kotlin/build.gradle.kts
Labels: in:dependency-version-catalog

#17702 Make CHAMP collections available to the Gradle runtime
  build-logic/basics/src/main/kotlin/gradlebuild.repositories.gradle.kts
  build-logic/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
  gradle/verification-metadata.xml
  subprojects/configuration-cache/build.gradle.kts
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ConfigurationCacheProblems.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ConfigurationCacheProblemsSummary.kt
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DistributionIntegrationSpec.groovy
Labels: @configuration-cache

#17881 Let configuration cache ignore convention values of incompatible type
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheConventionMappingIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/beans/BeanPropertyWriter.kt
Labels: @configuration-cache

#17891 Add IgnoreEmptyDirectories to SkipWhenEmpty inputs
  subprojects/language-native/src/main/java/org/gradle/language/assembler/tasks/Assemble.java
  subprojects/language-native/src/main/java/org/gradle/language/nativeplatform/tasks/AbstractNativeCompileTask.java
  subprojects/language-native/src/main/java/org/gradle/language/nativeplatform/tasks/UnexportMainSymbol.java
  subprojects/language-native/src/main/java/org/gradle/language/rc/tasks/WindowsResourceCompile.java
  subprojects/language-native/src/main/java/org/gradle/language/swift/tasks/SwiftCompile.java
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/tasks/AbstractLinkTask.java
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/tasks/CreateStaticLibrary.java
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/internal/precompiled/CompileGroovyScriptPluginsTask.java
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/internal/precompiled/ExtractPluginRequestsTask.java
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/internal/precompiled/GeneratePluginAdaptersTask.java
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/ValidatePlugins.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/TestReport.java
Labels: @execution

#17894 Remove ellipses from documentation titles
  subprojects/docs/src/main/resources/header.html
Labels: @execution

#17895 Ignore some failing build-init tests
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/BuildInitPluginIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/UndefinedBuildExecutionIntegrationTest.groovy
Labels: @dev-productivity

#17836 Finalize build output cleanup registry before starting task execution
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/AbstractIncludedBuildController.java
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheBuild.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheHost.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/core/src/main/java/org/gradle/internal/build/BuildLifecycleController.java
  subprojects/core/src/main/java/org/gradle/internal/build/BuildWorkGraph.java
  subprojects/core/src/main/java/org/gradle/internal/build/DefaultBuildLifecycleController.java
  subprojects/core/src/main/java/org/gradle/internal/build/DefaultBuildWorkGraph.java
  subprojects/core/src/main/java/org/gradle/internal/buildtree/DefaultBuildTreeWorkPreparer.java
  subprojects/core/src/main/java/org/gradle/internal/cleanup/DefaultBuildOutputCleanupRegistry.java
  subprojects/core/src/test/groovy/org/gradle/internal/cleanup/DefaultBuildOutputCleanupRegistryTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/test/fixtures/AbstractProjectBuilderSpec.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/BuildOutputCleanupRegistry.java
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/ParallelStaleOutputIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/WellBehavedPluginTest.groovy
Labels: @execution
