Repository gradle/gradle, pull requests merged in 2021-04, with the labels that each got.

#16685 Let versions and bundles use nested accessors
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/TomlDependenciesExtensionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/VersionCatalogExtensionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/AbstractExternalDependencyFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/DefaultDependenciesAccessors.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/LibrariesSourceGenerator.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/catalog/LibrariesSourceGeneratorTest.groovy
Labels: @execution, a:bug, in:dependency-version-catalog

#16690 Improve error reporting in version catalogs
  subprojects/core/src/main/java/org/gradle/api/internal/catalog/parser/TomlCatalogFileParser.java
  subprojects/core/src/main/java/org/gradle/api/internal/catalog/problems/DefaultCatalogProblemBuilder.java
  subprojects/core/src/main/java/org/gradle/api/internal/catalog/problems/VersionCatalogProblem.java
  subprojects/core/src/main/java/org/gradle/api/internal/catalog/problems/VersionCatalogProblemBuilder.java
  subprojects/core/src/main/java/org/gradle/api/internal/catalog/problems/VersionCatalogProblemId.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/catalog/parser/TomlCatalogFileParserTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/api/internal/catalog/problems/VersionCatalogErrorMessages.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/api/internal/catalog/problems/VersionCatalogProblemTestFor.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/TomlDependenciesExtensionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/DefaultVersionCatalogBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/LibrariesSourceGenerator.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/catalog/DefaultVersionCatalogBuilderTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/catalog/LibrariesSourceGeneratorTest.groovy
  subprojects/docs/src/docs/userguide/troubleshooting/version_catalog_problems.adoc
  subprojects/problems/src/main/java/org/gradle/problems/StandardSeverity.java
  subprojects/problems/src/main/java/org/gradle/problems/internal/RenderingUtils.java
Labels: @execution, in:dependency-version-catalog

#16625 Support pluginManagement block in precompiled Groovy settings plugins
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/plugins/PluginBuildsIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/SettingsInternal.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultSettings.java
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/plugins/PrecompiledGroovyPluginsIntegrationTest.groovy
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/internal/precompiled/CompileGroovyScriptPluginsTask.java
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/internal/precompiled/ExtractPluginRequestsTask.java
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/internal/precompiled/FirstPassPrecompiledScript.java
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/internal/precompiled/FirstPassPrecompiledScriptRunner.java
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/internal/precompiled/GeneratePluginAdaptersTask.java
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/internal/precompiled/PrecompiledGroovyPluginsPlugin.java
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/internal/precompiled/PrecompiledGroovyScript.java
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/internal/precompiled/PrecompiledScriptTarget.java
Labels: @idiomatic, a:bug

#16699 Add template for version 7 upgrade guide
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/main/resources/header.html
Labels: @core

#16700 Improve suppressed deprecation warnings message
  subprojects/logging/src/integTest/groovy/org/gradle/DeprecationHandlingIntegrationTest.groovy
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/LoggingDeprecatedFeatureHandler.java
  subprojects/logging/src/test/groovy/org/gradle/internal/deprecation/DeprecationLoggerTest.groovy
Labels: @core

#16680 Let config cache serialization honor convention mapping
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/beans/BeanPropertyWriter.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/beans/BeanSchema.kt
  subprojects/model-core/src/main/java/org/gradle/internal/instantiation/generator/AsmBackedClassGenerator.java
Labels: @configuration-cache, in:configuration-cache

#16711 Remove temporary config cache relocator rule
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/runtimeshaded/ImplementationDependencyRelocator.java
Labels: @configuration-cache, a:chore, in:configuration-cache

#16715 Upgraded tested AGP version
  gradle/dependency-management/agp-versions.properties
Labels: @configuration-cache

#16703 Add configuration cache smoke tests for gradle/gradle local dev workflows
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildConfigurationCacheSmokeTest.groovy
Labels: @configuration-cache

#16031 Nest composite build operations when loading builds from the configuration cache
  subprojects/configuration-cache/build.gradle.kts
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheCompositeBuildsIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheProblemReportingIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheHost.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/core/src/main/java/org/gradle/configuration/BuildOperationFiringProjectsPreparer.java
  subprojects/core/src/main/java/org/gradle/initialization/NotifyingBuildLoader.java
  subprojects/core/src/main/java/org/gradle/initialization/buildsrc/BuildSourceBuilder.java
  subprojects/core/src/main/java/org/gradle/initialization/buildsrc/BuildSrcUpdateFactory.java
  subprojects/core/src/main/java/org/gradle/internal/operations/trace/BuildOperationRecord.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/BuildScopeServices.java
Labels: @configuration-cache, a:feature, in:composite-builds

#16720 Let ManagedPropertyName not hold a reference to its owner
  subprojects/model-core/src/main/java/org/gradle/internal/instantiation/generator/ManagedObjectFactory.java
Labels: @configuration-cache, in:configuration-model

#16742 Fix JDK16 flakiness in BuildScriptCompileAvoidanceIntegrationTest
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginTest.kt
  subprojects/kotlin-dsl/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/BuildScriptCompileAvoidanceIntegrationTest.kt
  subprojects/kotlin-dsl/src/testFixtures/kotlin/org/gradle/kotlin/dsl/fixtures/AbstractKotlinIntegrationTest.kt
Labels: @core, in:testing

#16738 Upgrade tested AGP version
  gradle/dependency-management/agp-versions.properties
Labels: @configuration-cache

#16746 Restore ktlint task dependencies
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.build-logic.kotlin-dsl-gradle-plugin.gradle.kts
  build-logic/uber-plugins/src/main/kotlin/gradlebuild.internal.kotlin-js.gradle.kts
  build-logic/uber-plugins/src/main/kotlin/gradlebuild.kotlin-library.gradle.kts
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/kotlin-dsl/src/integTest/kotlin/org/gradle/kotlin/dsl/fixtures/GradleApiExtensionsFixture.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/AccessorsClassPath.kt
Labels: @configuration-cache, in:gradle-build

#16736 Clarify example in multi-project docs
  subprojects/docs/src/snippets/multiproject/customLayout/groovy/settings.gradle
Labels: @core, a:documentation

#16718 Let the configuration cache serialization support URL instances
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/UrlCodec.kt
Labels: @configuration-cache, in:configuration-cache

#16762 Let CC report input properties declared as SourceDirectorySet
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheUnsupportedTypesIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/beans/BeanSchema.kt
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/tasks/CompilePrecompiledScriptPluginPlugins.kt
Labels: @configuration-cache, in:configuration-cache

#16747 Remove master subdirectory as project root from IDE tests
  subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/eclipse/EclipseIntegrationTest.groovy
  subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/eclipse/EclipseMultiModuleIntegrationTest.groovy
  subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/idea/IdeaIntegrationTest.groovy
  subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/idea/IdeaMultiModuleIntegrationTest.groovy
  subprojects/ide/src/integTest/resources/org/gradle/plugins/ide/eclipse/EclipseIntegrationTest/canCreateAndDeleteMetaData/build.gradle
  subprojects/ide/src/integTest/resources/org/gradle/plugins/ide/eclipse/EclipseIntegrationTest/canCreateAndDeleteMetaData/master/settings.gradle
  subprojects/ide/src/integTest/resources/org/gradle/plugins/ide/eclipse/EclipseIntegrationTest/canCreateAndDeleteMetaData/settings.gradle
Labels: @core, in:testing

#16348 Make IDEA convention mapping behave more intuitively
  subprojects/ide/src/main/java/org/gradle/plugins/ide/idea/IdeaPlugin.java
  subprojects/ide/src/test/groovy/org/gradle/plugins/ide/idea/IdeaPluginTest.groovy
Labels: in:idea-plugin

#16734 Deprecate getMain/setMain in JavaExec task
  subprojects/core-api/src/main/java/org/gradle/process/JavaExecSpec.java
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/ExecutionResultJavaExecTaskIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/JavaExecJavaVersionIntegrationSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskTimeoutIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/console/AbstractExecOutputIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/process/internal/CancellationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/process/internal/DefaultJavaExecSpec.java
  subprojects/core/src/main/java/org/gradle/process/internal/JavaExecHandleBuilder.java
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/snippets/kotlinDsl/configuring-tasks-spring-boot/groovy/build.gradle
  subprojects/docs/src/snippets/kotlinDsl/configuring-tasks-spring-boot/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/tutorial/groovyScope/groovy/build.gradle
  subprojects/docs/src/snippets/tutorial/groovyScope/kotlin/build.gradle.kts
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/ExecIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/tasks/JavaExec.java
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/BuildEnvironmentIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecDebugIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecWithLongCommandLineIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/AbstractJavaCompileAvoidanceIntegrationSpec.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/FreefairAspectJPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GrettySmokeTest.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerExecutorServicesIntegrationTest.groovy
Labels: @core

#16759 Deprecate Exec.getExecResult which is replaced by getExecutionResult
  subprojects/core/src/main/java/org/gradle/api/tasks/AbstractExecTask.java
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/ExecIntegrationTest.groovy
Labels: @core

#16764 Deprecate replaced getters/setters in Report
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginVersionIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcPluginIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcPluginVersionIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcRelocationIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/pmd/PmdPluginVersionIntegrationTest.groovy
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/CheckstyleInvoker.groovy
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/CodeNarcInvoker.groovy
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/PmdInvoker.groovy
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/plugins/ProjectReportsPluginIntegrationSpec.groovy
  subprojects/diagnostics/src/main/java/org/gradle/api/reporting/dependencies/HtmlDependencyReportTask.java
  subprojects/docs/src/docs/dsl/org.gradle.api.reporting.Report.xml
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/samples/build-organization/structuring-software-projects/groovy/build-logic/report-aggregation/src/main/groovy/com.example.report-aggregation.gradle
  subprojects/docs/src/samples/build-organization/structuring-software-projects/kotlin/build-logic/report-aggregation/src/main/kotlin/com.example.report-aggregation.gradle.kts
  subprojects/docs/src/samples/java/jvm-multi-project-with-code-coverage/groovy/buildSrc/src/main/groovy/myproject.jacoco-aggregation.gradle
  subprojects/docs/src/samples/java/jvm-multi-project-with-code-coverage/kotlin/buildSrc/src/main/kotlin/myproject.jacoco-aggregation.gradle.kts
  subprojects/docs/src/snippets/codeQuality/codeQuality/groovy/build.gradle
  subprojects/docs/src/snippets/codeQuality/codeQuality/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/swift/testReport/groovy/buildSrc/src/main/groovy/myproject.xctest-conventions.gradle
  subprojects/docs/src/snippets/swift/testReport/kotlin/buildSrc/src/main/kotlin/myproject.xctest-conventions.gradle.kts
  subprojects/docs/src/snippets/testing/jacoco-quickstart/groovy/build.gradle
  subprojects/docs/src/snippets/testing/jacoco-quickstart/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/testing/testReport/groovy/buildSrc/src/main/groovy/myproject.java-conventions.gradle
  subprojects/docs/src/snippets/testing/testReport/kotlin/buildSrc/src/main/kotlin/myproject.java-conventions.gradle.kts
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoPluginMultiVersionIntegrationTest.groovy
  subprojects/jacoco/src/main/java/org/gradle/internal/jacoco/AntJacocoReport.java
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoPlugin.java
  subprojects/plugins/src/test/groovy/org/gradle/api/tasks/testing/TestTaskSpec.groovy
  subprojects/reporting/src/integTest/groovy/org/gradle/api/reporting/internal/TaskReportContainerIntegTest.groovy
  subprojects/reporting/src/integTest/groovy/org/gradle/api/reporting/plugins/BuildDashboardPluginIntegrationTest.groovy
  subprojects/reporting/src/main/java/org/gradle/api/reporting/ConfigurableReport.java
  subprojects/reporting/src/main/java/org/gradle/api/reporting/DirectoryReport.java
  subprojects/reporting/src/main/java/org/gradle/api/reporting/GenerateBuildDashboard.java
  subprojects/reporting/src/main/java/org/gradle/api/reporting/Report.java
  subprojects/reporting/src/main/java/org/gradle/api/reporting/ReportContainer.java
  subprojects/reporting/src/main/java/org/gradle/api/reporting/internal/BuildDashboardGenerator.java
  subprojects/reporting/src/main/java/org/gradle/api/reporting/internal/DefaultReportContainer.java
  subprojects/reporting/src/main/java/org/gradle/api/reporting/internal/SimpleReport.java
  subprojects/reporting/src/main/java/org/gradle/api/reporting/internal/TaskGeneratedSingleDirectoryReport.java
  subprojects/reporting/src/test/groovy/org/gradle/api/reporting/GenerateBuildDashboardSpec.groovy
  subprojects/reporting/src/test/groovy/org/gradle/api/reporting/internal/BuildDashboardGeneratorSpec.groovy
  subprojects/testing-base/src/main/java/org/gradle/api/tasks/testing/AbstractTestTask.java
  subprojects/testing-base/src/testFixtures/groovy/org/gradle/testing/AbstractTestFrameworkIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/IncrementalTestIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestReportIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestTaskIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGProducesOldReportsIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/resources/org/gradle/testing/cucumberjvm/CucumberJVMReportIntegrationTest/testReportingSupportsCucumberStepsWithSlashes/build.gradle
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGTestFramework.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/testng/TestNGOptions.java
Labels: @core

#16810 Add ApiClassExtractor to configuration hash of AbiExtractingClasspathResourceHasher
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/AbiExtractingClasspathResourceHasher.java
  subprojects/normalization-java/src/main/java/org/gradle/internal/normalization/java/ApiClassExtractor.java
  subprojects/normalization-java/src/test/groovy/org/gradle/api/internal/changedetection/state/AbiExtractingClasspathResourceHasherTest.groovy
Labels: @execution

#16758 Deprecate getters/setters replaced with properties in compile tasks
  subprojects/core-api/src/main/java/org/gradle/api/file/SourceDirectorySet.java
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedTaskActionIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/file/DefaultSourceDirectorySet.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/DirectoryOutputArtifactIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/VariantAwareResolutionWithConfigurationAttributesIntegrationTest.groovy
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/snippets/antMigration/importBuild/groovy/build.gradle
  subprojects/docs/src/snippets/antMigration/importBuild/kotlin/build.gradle.kts
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/JavaCompileOnlyDependencyIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/StaleOutputHistoryLossIntegrationTest.groovy
  subprojects/integ-test/src/integTest/resources/org/gradle/integtests/ProjectLayoutIntegrationTest/canUseANonStandardBuildDir/build.gradle
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoCachingIntegrationTest.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoReportRelocationIntegrationTest.groovy
  subprojects/language-jvm/src/main/java/org/gradle/api/tasks/compile/AbstractCompile.java
  subprojects/plugins/src/integTest/groovy/org/gradle/groovy/GroovyBasePluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/AbstractJavaGroovyCompileAvoidanceIntegrationSpec.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmLanguageGeneratedSourceDirectoryBuilder.java
  subprojects/plugins/src/main/java/org/gradle/api/tasks/SourceSetOutput.java
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestTaskRelocationIntegrationTest.groovy
Labels: @core

#16761 Deprecate replaced getters/setters in CompileOptions
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/CompileOptions.java
Labels: @core

#16750 Deprecate getMainClassName/setMainClassName in CreateStartScripts task
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/ApplicationPluginIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/jvm/application/tasks/CreateStartScripts.java
Labels: @core

#16827 Add ApiClassExtractor to configuration hash of AbiExtractingClasspathResourceHasher
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/AbiExtractingClasspathResourceHasher.java
  subprojects/normalization-java/src/main/java/org/gradle/internal/normalization/java/ApiClassExtractor.java
  subprojects/normalization-java/src/test/groovy/org/gradle/api/internal/changedetection/state/AbiExtractingClasspathResourceHasherTest.groovy
Labels: @execution

#16825 Backport file leak fixes
  buildSrc/subprojects/binary-compatibility/src/main/groovy/gradlebuild/binarycompatibility/transforms/ExplodeZipAndFindJars.groovy
  subprojects/base-services/src/main/java/org/gradle/util/GUtil.java
  subprojects/core/src/main/java/org/gradle/api/internal/classpath/DefaultModuleRegistry.java
  subprojects/files/src/main/java/org/gradle/api/internal/file/archive/ZipEntry.java
  subprojects/files/src/main/java/org/gradle/api/internal/file/archive/impl/FileZipInput.java
  subprojects/files/src/main/java/org/gradle/api/internal/file/archive/impl/JdkZipEntry.java
  subprojects/files/src/main/java/org/gradle/api/internal/file/archive/impl/StreamZipInput.java
  subprojects/native/src/main/java/org/gradle/internal/nativeintegration/jansi/JansiBootPathConfigurer.java
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/MetaInfAwareClasspathResourceHasher.java
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/PropertiesFileAwareClasspathResourceHasher.java
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/RuntimeClasspathResourceHasher.java
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/ZipHasher.java
  subprojects/normalization-java/src/test/groovy/org/gradle/api/internal/changedetection/state/MetaInfAwareClasspathResourceHasherTest.groovy
  subprojects/normalization-java/src/test/groovy/org/gradle/api/internal/changedetection/state/PropertiesFileAwareClasspathResourceHasherTest.groovy
Labels: @execution

#16818 Let instrumenting transformer use the cross version file locking protocol
  subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingClasspathFileTransformer.java
Labels: @configuration-cache, in:configuration-cache

#16830 Add nagging for AbstractTestTask deprecations
  subprojects/docs/src/docs/dsl/org.gradle.api.tasks.testing.AbstractTestTask.xml
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoPluginMultiVersionIntegrationTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/tasks/testing/TestReportTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/tasks/testing/TestTest.groovy
  subprojects/testing-base/src/main/java/org/gradle/api/tasks/testing/AbstractTestTask.java
  subprojects/testing-base/src/testFixtures/groovy/org/gradle/testing/AbstractTestFrameworkIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestReportIntegrationTest.groovy
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java
Labels: @core

#16833 Replace upgrade guide sections with pointers to DSL reference for deprecations where possible
  subprojects/core-api/src/main/java/org/gradle/api/file/SourceDirectorySet.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/DefaultSourceDirectorySet.java
  subprojects/core/src/main/java/org/gradle/api/tasks/AbstractExecTask.java
  subprojects/docs/src/docs/dsl/org.gradle.jvm.application.tasks.CreateStartScripts.xml
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/ExecIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/tasks/JavaExec.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/CompileOptions.java
  subprojects/language-jvm/src/main/java/org/gradle/api/tasks/compile/AbstractCompile.java
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/ApplicationPluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/jvm/application/tasks/CreateStartScripts.java
  subprojects/reporting/src/main/java/org/gradle/api/reporting/ConfigurableReport.java
  subprojects/reporting/src/main/java/org/gradle/api/reporting/internal/SimpleReport.java
Labels: @core

#16826 Upgrade to latest wrapper
  gradle/wrapper/gradle-wrapper.properties
Labels: @execution

#16828 Add ApiClassExtractor to configuration hash of AbiExtractingClasspathResourceHasher (Bugfix 7.0.1)
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/AbiExtractingClasspathResourceHasher.java
  subprojects/normalization-java/src/main/java/org/gradle/internal/normalization/java/ApiClassExtractor.java
  subprojects/normalization-java/src/test/groovy/org/gradle/api/internal/changedetection/state/AbiExtractingClasspathResourceHasherTest.groovy
Labels: @execution

#16835 Backport fix for kotlin-jvm and java-gradle-plugin interactions with configuration cache enabled
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractProjectRelocationIntegrationTest.groovy
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/plugins/JavaGradlePluginPlugin.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginSmokeTest.groovy
Labels: @configuration-cache, in:plugin-development

#16848 Create tmp directory for {Groovy,Java}Compile at execution time
  subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
Labels: @execution

#16831 Fix checking for build cache miss
  build-logic/profiling/src/main/kotlin/gradlebuild.buildscan.gradle.kts
Labels: @dev-productivity

#16832 Fix and unignore javaCompile integration test on non-Windows systems
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy
Labels: @core

#16855 Set JAVA_HOME for PerformanceTestsPass job
  .teamcity/src/main/kotlin/configurations/PerformanceTestsPass.kt
Labels: @dev-productivity

#16741 Let configuration cache honour `--project-cache-dir`
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheRepository.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultConfigurationCache.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintController.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/ConfigurationCacheStartParameter.kt
  subprojects/core/src/integTest/groovy/org/gradle/initialization/InternalGradleFailuresIntegrationTest.groovy
Labels: @configuration-cache, in:configuration-cache

#16847 Fix native tests on Ubuntu 20.04
  subprojects/language-native/src/integTest/groovy/org/gradle/language/cpp/CppToolChainChangesIntegrationTest.groovy
  subprojects/language-native/src/testFixtures/groovy/org/gradle/language/swift/AbstractSwiftComponentIntegrationTest.groovy
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/gcc/metadata/GccMetadataProvider.java
  subprojects/platform-native/src/testFixtures/groovy/org/gradle/nativeplatform/fixtures/AbstractInstalledToolChainIntegrationSpec.groovy
  subprojects/testing-native/src/integTest/groovy/org/gradle/nativeplatform/test/xctest/AbstractSwiftXCTestComponentWithTestedComponentIntegrationTest.groovy
Labels: @dev-productivity

#16860 Add all ConfigCache tests trigger
  .teamcity/src/main/kotlin/model/CIBuildModel.kt
  .teamcity/src/main/kotlin/projects/StageProject.kt
Labels: @dev-productivity

#16838 Backport configuration cache fix for :processDebugAndroidTestManifest incorrectness in Android builds
  gradle/dependency-management/agp-versions.properties
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/PublishArtifactLocalArtifactMetadataCodec.kt
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/AndroidGradlePluginVersions.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidPluginsSmokeTest.groovy
Labels: @configuration-cache, in:core

#16861 Ignore failing test on mac os
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy
Labels: @core

#16834 Backport #15738 to Gradle 6.9
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementGradleUserHomeScopeServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/ImmutableTransformationWorkspaceServices.java
Labels: @execution

#16817 Replace AtomicReference by volatile field
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DefaultFileWatcherRegistry.java
Labels: @execution

#16870 Only consider successful tasks for cache misses
  build-logic/profiling/src/main/kotlin/gradlebuild.buildscan.gradle.kts
Labels: @dev-productivity

#16876 Wait for changes in Daemon executor as well
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/DaemonGradleExecuter.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/InProcessGradleExecuter.java
Labels: @dev-productivity

#16770 Report configuration cache problems for tasks from included builds
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildParallelIntegrationTest.groovy
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildTaskDependencyIntegrationTest.groovy
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultIncludedBuildController.java
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheProblemReportingIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheProblemsListenerManagerAction.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheServices.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultConfigurationCache.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/ConfigurationCacheBuildEnablement.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/ConfigurationCacheProblemsListener.kt
  subprojects/core/src/main/java/org/gradle/internal/buildtree/BuildTreeScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/BuildScopeServices.java
  subprojects/dependency-management/src/testFixtures/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformTestFixture.groovy
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/DefaultPrecompiledScriptPluginsSupport.kt
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/ConfigurationTimeBarrier.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/DefaultConfigurationTimeBarrier.java
Labels: @configuration-cache, in:configuration-cache

#16878 Revert "Ignore CppIncrementalBuildIntegrationTest for now"
  subprojects/language-native/src/integTest/groovy/org/gradle/language/cpp/CppIncrementalBuildIntegrationTest.groovy
Labels: @dev-productivity

#16726 Add more logging around starting and stopping file system watching
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DefaultFileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/soak/src/integTest/groovy/org/gradle/vfs/FileSystemWatchingSoakTest.groovy
Labels: @execution

#16889 Change version to `6.9` instead of `6.9.0`
  version.txt
Labels: @configuration-cache, a:chore, in:building-gradle

#16883 Unify trove4j version in build
  build-logic/dependency-modules/src/main/kotlin/gradlebuild.dependency-modules.gradle.kts
  build-logic/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
  gradle/verification-metadata.xml
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/internal-android-performance-testing/build.gradle.kts
Labels: @dev-productivity

#16890 Backport JDK16 support using toolchains to 6.9
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/groovy/buildSrc/src/test/groovy/com/example/JavaConventionPluginTest.groovy
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/kotlin/buildSrc/src/test/kotlin/com/example/JavaConventionPluginTest.kt
  subprojects/docs/src/samples/build-organization/publishing-convention-plugins/groovy/convention-plugins/src/test/groovy/com/myorg/JavaConventionPluginTest.groovy
  subprojects/docs/src/samples/build-organization/publishing-convention-plugins/kotlin/convention-plugins/src/test/kotlin/com/myorg/JavaConventionPluginTest.kt
  subprojects/java-compiler-plugin/src/main/java/org/gradle/internal/compiler/java/ClassNameCollector.java
  subprojects/java-compiler-plugin/src/main/java/org/gradle/internal/compiler/java/IncrementalCompileTask.java
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileToolchainIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/BaseJavaSourceIncrementalCompilationIntegrationTest.groovy
Labels: @core

#16537 Fix potential `NoClassDefFoundError`
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/annotations/impl/DefaultTypeAnnotationMetadataStore.java
Labels: @execution

#16894 Backport `--project-cache-dir` configuration cache fix to 7.0.1
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheRepository.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultConfigurationCache.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintController.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/ConfigurationCacheStartParameter.kt
  subprojects/core/src/integTest/groovy/org/gradle/initialization/InternalGradleFailuresIntegrationTest.groovy
Labels: @configuration-cache, a:feature, in:configuration-cache

#16795 Dependency upgrades
  gradle/verification-keyring.gpg
  gradle/verification-metadata.xml
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/BinDistributionIntegrationSpec.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DistributionIntegritySpec.groovy
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/swift/SwiftDepsHandler.java
Labels: @core, in:building-gradle

#16895 Backport `--project-cache-dir` configuration cache fix to 6.x
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheRepository.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultConfigurationCache.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintController.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/ConfigurationCacheStartParameter.kt
  subprojects/core/src/integTest/groovy/org/gradle/initialization/InternalGradleFailuresIntegrationTest.groovy
Labels: @configuration-cache, a:feature, in:configuration-cache

#16903 Fix reading the timestamp for BuildSessionScopeFileTimeStampInspector
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/BuildSessionScopeFileTimeStampInspector.java
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/FileTimeStampInspector.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/FileSystemWatchingHelper.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/DaemonGradleExecuter.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/InProcessGradleExecuter.java
Labels: @execution

#16920 Re-enable native tests
  subprojects/language-native/src/testFixtures/groovy/org/gradle/language/swift/AbstractSwiftComponentIntegrationTest.groovy
  subprojects/platform-native/src/integTest/groovy/org/gradle/nativeplatform/NativePlatformSamplesIntegrationTest.groovy
Labels: @dev-productivity

#16864 Upgrade tested AGP version
  gradle/dependency-management/agp-versions.properties
Labels: @configuration-cache

#16912 Prove task problems from included builds are reported correctly
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheProblemReportingIntegrationTest.groovy
Labels: @configuration-cache, a:chore, in:configuration-cache

#16914 Merge release into master
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultConfigurationCache.kt
  subprojects/core/src/integTest/groovy/org/gradle/initialization/InternalGradleFailuresIntegrationTest.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/language/cpp/CppIncrementalBuildIntegrationTest.groovy
Labels: @configuration-cache, a:chore

#16899 Fail gracefully when filesystems can't be listed
  gradle/verification-metadata.xml
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WatchableHierarchies.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/DefaultWatchableFileSystemDetector.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/DefaultWatchableFileSystemDetectorTest.groovy
Labels: @execution

#16749 Make JacocoCoverageVerification cacheable
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoCachingIntegrationTest.groovy
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/tasks/JacocoCoverageVerification.java
Labels: @execution

#16941 Adjust @ToBeFixedForCC for swift tests
  subprojects/language-native/src/integTest/groovy/org/gradle/language/swift/AbstractSwiftIntegrationTest.groovy
  subprojects/language-native/src/testFixtures/groovy/org/gradle/language/swift/AbstractSwiftComponentIntegrationTest.groovy
  subprojects/platform-native/src/integTest/groovy/org/gradle/nativeplatform/NativePlatformSamplesIntegrationTest.groovy
Labels: @dev-productivity

#16923 Further split cross version tests
  .teamcity/src/main/kotlin/model/FunctionalTestBucketProvider.kt
Labels: @dev-productivity

#16968 Revert "Ignore CppIncrementalBuildIntegrationTest for now"
  subprojects/language-native/src/integTest/groovy/org/gradle/language/cpp/CppIncrementalBuildIntegrationTest.groovy
Labels: @dev-productivity

#16992 Attempt to fix flaky test for build services classloading reuse
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildServiceIntegrationTest.groovy
Labels: @configuration-cache, in:configuration-cache

#16977 Disable file system watching for builds started by testkit on Windows
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/test-kit/build.gradle.kts
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/GradleRunnerFileSystemWatchingIntegrationTest.groovy
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/GradleRunnerMechanicalFailureIntegrationTest.groovy
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/GradleRunnerSupportedBuildJvmIntegrationTest.groovy
  subprojects/test-kit/src/main/java/org/gradle/testkit/runner/GradleRunner.java
  subprojects/test-kit/src/main/java/org/gradle/testkit/runner/internal/DefaultGradleRunner.java
Labels: @execution

#16970 Use FQCN in validation error messages
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginVersionIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalBuildSymlinkHandlingIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskInputFilePropertiesIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskParametersIntegrationTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/taskfactory/AnnotationProcessingTaskFactoryTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/DefaultTypeMetadataStoreTest.groovy
  subprojects/core/src/test/groovy/org/gradle/execution/plan/TaskNodeFactoryTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
  subprojects/execution/src/integTest/groovy/org/gradle/internal/execution/IncrementalExecutionIntegrationTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/ValidateStepTest.groovy
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/validation/TypeValidationProblemRenderer.java
  subprojects/model-core/src/test/groovy/org/gradle/internal/reflect/annotations/impl/DefaultTypeAnnotationMetadataStoreTest.groovy
  subprojects/model-core/src/testFixtures/groovy/org/gradle/internal/reflect/validation/ValidationMessageDisplayConfiguration.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/PluginUnderTestMetadataIntegrationTest.groovy
  subprojects/plugin-development/src/testFixtures/groovy/org/gradle/plugin/devel/tasks/TaskValidationReportFixture.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/bundling/JarIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/groovy/compile/BasicGroovyCompilerIntegrationSpec.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidCommunityPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildExternalPluginsValidationSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/NodePluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ProguardSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/SpringBootPluginSmokeTest.groovy
Labels: @execution

#16945 Make `PublishToMavenLocal` task compatible with configuration cache
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishSnapshotIntegTest.groovy
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/tasks/PublishToMavenLocal.java
Labels: @configuration-cache, in:publishing-plugins

#17001 Only run the testkit fs watching tests on Gradle 7
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/GradleRunnerFileSystemWatchingIntegrationTest.groovy
Labels: @execution

#17008 Also test shadow plugin version 7.0
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
Labels: @execution

#17023 Fix flaky parallel task execution test
  subprojects/core/src/integTest/groovy/org/gradle/execution/taskgraph/ParallelTaskExecutionIntegrationTest.groovy
Labels: @core

#17012 Fix typo in shared build services docu
  subprojects/docs/src/docs/userguide/extending-gradle/build_services.adoc
Labels: @configuration-cache, a:documentation, in:configuration-cache

#16975 Fix broken link for DSL reference
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/bundling/ArchiveIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DuplicateHandlingCopyActionDecorator.java
Labels: @execution, a:bug, a:documentation

#17015 Fix regression with config_loc existence
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginVersionIntegrationTest.groovy
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/Checkstyle.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CheckstylePlugin.java
Labels: @core

#17020 Add a build step to clean ~/.android before build
  .teamcity/src/main/kotlin/common/extensions.kt
  .teamcity/src/main/kotlin/configurations/GradleBuildConfigurationDefaults.kt
  .teamcity/src/main/kotlin/configurations/PerformanceTest.kt
  .teamcity/src/main/kotlin/configurations/SmokeTests.kt
  .teamcity/src/test/kotlin/PerformanceTestBuildTypeTest.kt
Labels: @dev-productivity

#16957 Version catalog fixes
  subprojects/core/src/main/java/org/gradle/api/internal/artifacts/dependencies/AbstractModuleDependency.java
  subprojects/core/src/main/java/org/gradle/api/internal/catalog/parser/TomlCatalogFileParser.java
  subprojects/core/src/main/java/org/gradle/api/internal/catalog/problems/VersionCatalogProblemId.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/artifacts/dependencies/AbstractModuleDependencySpec.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/api/internal/catalog/problems/VersionCatalogErrorMessages.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/TomlDependenciesExtensionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/VersionCatalogExtensionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenDependencyResolveIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/DefaultVersionCatalogBuilder.java
  subprojects/docs/src/snippets/dependencyManagement/catalogs-toml/groovy/buildSrc/settings.gradle
  subprojects/docs/src/snippets/dependencyManagement/catalogs-toml/kotlin/buildSrc/settings.gradle.kts
Labels: @execution, a:bug

#17030 Document corner case around configuration removal
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
Labels: @core, in:dependency-declarations

#16995 Deprecate code quality plugin configurations for consumption
  subprojects/antlr/src/main/java/org/gradle/api/plugins/antlr/AntlrPlugin.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/AbstractCodeQualityPlugin.java
  subprojects/core-api/src/main/java/org/gradle/internal/deprecation/DeprecatableConfiguration.java
  subprojects/core/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultProjectDependency.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/DeprecatedConfigurationsIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/DefaultArtifactHandler.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/moduleconverter/DefaultLocalComponentMetadataBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractConfigurationMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractVariantBackedConfigurationMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/LazyRuleAwareWithBaseConfigurationMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/local/model/BuildableLocalComponentMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/local/model/DefaultLocalComponentMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/local/model/RootLocalComponentMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/ConfigurationMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/DefaultSelectedByVariantMatchingConfigurationMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/LocalComponentDependencyMetadata.java
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/reporting/dependencies/HtmlDependencyReportTaskIntegrationTest.groovy
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/DependencyReportTaskIntegrationTest.groovy
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/PluginConfigurationAttributesIntegrationTest.groovy
  subprojects/platform-base/src/main/java/org/gradle/language/base/internal/model/DefaultLibraryLocalComponentMetadata.java
Labels: @core

#17036 Set `BUILD_BRANCH` environment variable for all builds
  .teamcity/src/main/kotlin/common/extensions.kt
  .teamcity/src/main/kotlin/common/performance-test-extensions.kt
  .teamcity/src/main/kotlin/configurations/PerformanceTestsPass.kt
Labels: @dev-productivity
