Repository gradle/gradle, pull requests merged in 2021-01, with the labels that each got.

#15651 Fix some assertions not being executed
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/ConfigurationRoleIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/AbstractFileCollection.java
Labels: a:bug, from:member, in:dependency-management

#15582 Update unit tests to be compatible with Spock 2
  subprojects/build-operations/src/test/groovy/org/gradle/internal/operations/DefaultBuildOperationRunnerTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/archive/ZipCopyActionTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/plugins/DefaultObjectConfigurationActionTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/DefaultProjectStateRegistryTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuterTest.groovy
  subprojects/core/src/test/groovy/org/gradle/initialization/layout/BuildLayoutFactoryTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/operations/notify/BuildOperationNotificationBridgeTest.groovy
  subprojects/core/src/test/groovy/org/gradle/util/StdinSwapperTest.groovy
  subprojects/core/src/test/groovy/org/gradle/util/ports/FixedAvailablePortAllocatorTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/dsl/DefaultRepositoryHandlerTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ShortCircuitEmptyConfigurationResolverSpec.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ComponentSelectorSerializerTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/local/model/DefaultLibraryComponentSelectorTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/external/javadoc/internal/JavadocExecHandleBuilderTest.groovy
  subprojects/launcher/src/test/groovy/org/gradle/launcher/continuous/ContinuousIntegrationTestFixtureTest.groovy
  subprojects/logging/src/test/groovy/org/gradle/internal/deprecation/LoggingDeprecatedFeatureHandlerTest.groovy
  subprojects/logging/src/test/groovy/org/gradle/internal/featurelifecycle/FeatureUsageTest.groovy
  subprojects/logging/src/test/groovy/org/gradle/internal/logging/slf4j/OutputEventListenerBackedLoggerTest.groovy
  subprojects/messaging/src/test/groovy/org/gradle/internal/remote/internal/inet/TcpConnectorTest.groovy
  subprojects/model-core/src/test/groovy/org/gradle/model/internal/inspect/ManagedModelInitializerTest.groovy
  subprojects/native/src/test/groovy/org/gradle/internal/nativeintegration/filesystem/jdk7/Jdk7SymlinkTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/kotlindsl/GradleKotlinDslBuildPerformanceTest.groovy
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/internal/resolve/JvmLibraryResolveContextTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/DefaultJavaPluginConventionTest.groovy
  subprojects/process-services/src/test/groovy/org/gradle/process/internal/health/memory/DefaultMemoryManagerTest.groovy
  subprojects/reporting/src/test/groovy/org/gradle/api/reporting/GenerateBuildDashboardSpec.groovy
  subprojects/resources-http/src/test/groovy/org/gradle/internal/resource/transport/http/HttpResponseResourceTest.groovy
  subprojects/resources/src/test/groovy/org/gradle/internal/resource/BuildOperationFiringExternalResourceDecoratorTest.groovy
  subprojects/testing-base/src/test/groovy/org/gradle/api/internal/tasks/testing/results/StateTrackingTestResultProcessorTest.groovy
  subprojects/testing-jvm/src/test/groovy/org/gradle/api/internal/tasks/testing/detection/DefaultTestClassScannerTest.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r51/ProjectConfigurationProgressEventCrossVersionSpec.groovy
  subprojects/tooling-api/src/test/groovy/org/gradle/tooling/internal/consumer/parameters/BuildProgressListenerAdapterForProjectConfigurationOperationsTest.groovy
  subprojects/tooling-api/src/test/groovy/org/gradle/tooling/internal/consumer/parameters/BuildProgressListenerAdapterForTaskOperationsTest.groovy
  subprojects/tooling-api/src/test/groovy/org/gradle/tooling/internal/consumer/parameters/BuildProgressListenerAdapterForTransformOperationsTest.groovy
Labels: @idiomatic, a:chore, from:member

#15685 Make core tests compatible with Spock2
  subprojects/core/src/integTest/groovy/org/gradle/api/file/ProjectLayoutIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/normalization/ConfigureRuntimeClasspathNormalizationIntegrationTest.groovy
Labels: @core, a:chore, from:member

#15688 Make test-kit tests compatible with Spock2
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/GradleRunnerBuildFailureIntegrationTest.groovy
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/GradleRunnerGradleVersionIntegrationTest.groovy
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/GradleRunnerMechanicalFailureIntegrationTest.groovy
Labels: @core, a:chore, from:member

#15683 Make build-cache-http tests compatible with Spock2
  subprojects/build-cache-http/src/integTest/groovy/org/gradle/caching/http/internal/HttpBuildCacheFixture.groovy
  subprojects/build-cache-http/src/integTest/groovy/org/gradle/caching/http/internal/HttpBuildCacheRequestHeadersIntegrationTest.groovy
  subprojects/build-cache-http/src/integTest/groovy/org/gradle/caching/http/internal/HttpBuildCacheServiceErrorHandlingIntegrationTest.groovy
  subprojects/build-cache-http/src/integTest/groovy/org/gradle/caching/http/internal/HttpBuildCacheServiceIntegrationTest.groovy
Labels: @core, a:chore, from:member

#15650 De-incubate dependency management APIs
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/ArtifactSelectionDetails.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/CapabilitiesResolution.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/CapabilityResolutionDetails.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/ComponentMetadataDetails.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/DependencyArtifactSelector.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/DependencyResolveDetails.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/DependencySubstitution.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/DependencySubstitutions.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/DirectDependencyMetadata.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/ModuleDependency.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/ResolutionStrategy.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/VariantSelectionDetails.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/DependencyConstraintHandler.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/DependencyHandler.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/DependencyLockingHandler.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/LockMode.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/repositories/IvyArtifactRepository.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/repositories/MavenArtifactRepository.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/result/ResolutionResult.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/result/ResolvedComponentResult.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/result/ResolvedDependencyResult.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationIntegrityCheckIntegTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationSignatureCheckIntegTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationWritingIntegTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/StartParameterResolutionOverride.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/dependency_verification.adoc
Labels: @jvm, from:member, in:dependency-management

#15684 Make configuration-cache tests compatible with Spock2
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIncludedBuildChangesIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheScriptChangesIntegrationTest.groovy
Labels: @core, a:chore, from:member

#15692 Make platform-base tests compatible with Spock2
  subprojects/platform-base/src/integTest/groovy/org/gradle/language/base/plugins/LifecycleBasePluginIntegrationTest.groovy
Labels: @core, a:chore, from:member

#15691 Make dependency-management tests compatible with Spock2
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ModuleDependencyExcludeResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/PublishedRichVersionConstraintsIntegrationTest.groovy
Labels: @core, a:chore, from:member

#15690 Make testing-jvm tests compatible with Spock2
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/SuiteTimestampIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestOutputListenerIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGSuiteIntegrationTest.groovy
Labels: @core, a:chore, from:member

#15675 Add Revved up by Gradle Enterprise Badge to Readme
  README.md
Labels: a:chore, from:member, in:docs

#15693 Make workers tests compatible with Spock2
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerExecutorIntegrationTest.groovy
Labels: @core, a:chore, from:member

#15541 Remove Distribution.baseName
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/docs/src/docs/dsl/org.gradle.api.distribution.Distribution.xml
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/JavaLibraryDistributionIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/distribution/Distribution.java
  subprojects/plugins/src/main/java/org/gradle/api/distribution/internal/DefaultDistribution.java
  subprojects/plugins/src/test/groovy/org/gradle/api/distribution/plugins/DistributionPluginTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/JavaLibraryDistributionPluginTest.groovy
Labels: @idiomatic, a:chore, from:member

#15699 Deincubate a bunch of lazy configuration APIs
  subprojects/core-api/src/main/java/org/gradle/api/file/Directory.java
  subprojects/core-api/src/main/java/org/gradle/api/file/DirectoryProperty.java
  subprojects/core-api/src/main/java/org/gradle/api/file/FileCollection.java
  subprojects/core-api/src/main/java/org/gradle/api/file/FileSystemLocationProperty.java
  subprojects/core-api/src/main/java/org/gradle/api/provider/HasConfigurableValue.java
  subprojects/core-api/src/main/java/org/gradle/api/provider/HasMultipleValues.java
  subprojects/core-api/src/main/java/org/gradle/api/provider/MapProperty.java
  subprojects/core-api/src/main/java/org/gradle/api/provider/Property.java
  subprojects/core-api/src/main/java/org/gradle/api/provider/Provider.java
  subprojects/docs/src/docs/release/notes.md
Labels: @configuration-cache, a:chore, from:member, in:core

#15687 Make platform-native tests compatible with Spock2
  subprojects/platform-native/src/integTest/groovy/org/gradle/nativeplatform/NativeDependentComponentsIntegrationSpec.groovy
Labels: @core, a:chore, from:member

#15649 Smoke test kotlin 1.4.21
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/KotlinGradlePluginVersions.groovy
Labels: @configuration-cache, a:chore, from:member

#15698 Workaround setup/Before ordering in Spock 2 - file-watching
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ContinuousBuildFileWatchingIntegrationTest.groovy
Labels: @core, a:chore, from:member

#15697 Deincubate FileSystemOperations and ArchiveOperations services
  subprojects/core-api/src/main/java/org/gradle/api/file/ArchiveOperations.java
  subprojects/core-api/src/main/java/org/gradle/api/file/FileSystemOperations.java
  subprojects/docs/src/docs/release/notes.md
Labels: @configuration-cache, a:chore, from:member, in:core

#15700 Make tooling-api tests compatible with Spock2
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r213/ModelsWithGradleProjectCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r213/ModelsWithGradleProjectIdentifierCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r35/BuildProgressCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r40/BuildProgressCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r40/ProjectConfigurationChildrenProgressCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r40/ResolveArtifactsProgressCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r63/DistributionChecksumCrossVersionSpec.groovy
Labels: @core, a:chore, from:member

#15513 Remove deprecated methods from IdeaContentRoot
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
  subprojects/ide/src/crossVersionTest/groovy/org/gradle/plugins/ide/tooling/r22/Idea13ModelCrossVersionSpec.groovy
  subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/idea/DefaultIdeaContentRoot.java
  subprojects/ide/src/test/groovy/org/gradle/plugins/ide/internal/tooling/idea/DefaultIdeaContentRootTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIDEModelPerformanceTest.groovy
  subprojects/tooling-api/src/main/java/org/gradle/tooling/model/idea/IdeaContentRoot.java
Labels: @idiomatic, a:chore, from:member

#15701 Convert RichConsoleStyling trait to a class
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/RemoteDependencyResolveConsoleIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/TransformationLoggingIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/RichConsoleStyling.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/console/AbstractConsoleGroupedTaskFunctionalTest.groovy
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/AbstractConsoleConfigurationProgressFunctionalTest.groovy
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/jvm/AbstractConsoleJvmTestWorkerFunctionalTest.groovy
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/jvm/ConsoleTestNGUnsupportedTestWorkerFunctionalTest.groovy
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/jvm/TestedProjectFixture.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishConsoleIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/fixture/AbstractJvmFailFastIntegrationSpec.groovy
Labels: @core, a:chore, from:member

#15696 Workaround setup/Before ordering in Spock 2
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/DirectoryBuildCacheFixture.groovy
Labels: @core, a:chore, from:member

#15648 Remove deprecated BuildListener.buildStarted(Gradle)
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/build-profile/src/main/java/org/gradle/profile/BuildProfile.java
  subprojects/build-profile/src/main/java/org/gradle/profile/ProfileEventAdapter.java
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildEventsIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheProblemReportingIntegrationTest.groovy
  subprojects/core-api/src/main/java/org/gradle/BuildAdapter.java
  subprojects/core-api/src/main/java/org/gradle/BuildListener.java
  subprojects/core-api/src/main/java/org/gradle/api/invocation/Gradle.java
  subprojects/core-api/src/main/java/org/gradle/internal/InternalBuildAdapter.java
  subprojects/core-api/src/main/java/org/gradle/internal/InternalBuildListener.java
  subprojects/core/src/integTest/groovy/org/gradle/configuration/ExecuteUserLifecycleListenerBuildOperationIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/invocation/BuildStartedDeprecatedIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/configuration/internal/DefaultListenerBuildOperationDecorator.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradleLauncher.java
  subprojects/core/src/main/java/org/gradle/internal/buildevents/BuildLogger.java
  subprojects/core/src/main/java/org/gradle/internal/operations/notify/BuildOperationNotificationBridge.java
  subprojects/core/src/main/java/org/gradle/invocation/DefaultGradle.java
  subprojects/core/src/test/groovy/org/gradle/configuration/internal/DefaultListenerBuildOperationDecoratorTest.groovy
  subprojects/core/src/test/groovy/org/gradle/initialization/DefaultGradleLauncherSpec.groovy
  subprojects/core/src/test/groovy/org/gradle/invocation/DefaultGradleSpec.groovy
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/delegates/GradleDelegate.kt
Labels: @configuration-cache, a:chore, from:member, in:core

#15694 De-incubate dependency management APIs
  subprojects/core-api/src/main/java/org/gradle/StartParameter.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/ComponentVariantIdentifier.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/maven/PomModuleDescriptor.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/repositories/AuthenticationSupported.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/repositories/ExclusiveContentRepository.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/repositories/InclusiveRepositoryContentDescriptor.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/result/ComponentSelectionCause.java
  subprojects/core-api/src/main/java/org/gradle/api/initialization/dsl/ScriptHandler.java
  subprojects/diagnostics/src/main/java/org/gradle/api/plugins/HelpTasksPlugin.java
  subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/OutgoingVariantsReportTask.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/publish/src/main/java/org/gradle/api/publish/Publication.java
Labels: @jvm, in:dependency-management

#15686 De-incubate Javadoc, Sources, and compileOnlyApi related APIs
  subprojects/docs/src/docs/release/notes.md
  subprojects/plugins/src/main/java/org/gradle/api/plugins/FeatureSpec.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPluginExtension.java
  subprojects/plugins/src/main/java/org/gradle/api/tasks/SourceSet.java
Labels: @jvm, from:member

#15689 De-incubate types used in artifact queries
  subprojects/docs/src/docs/release/notes.md
  subprojects/language-java/src/main/java/org/gradle/language/java/artifact/JavadocArtifact.java
  subprojects/platform-base/src/main/java/org/gradle/language/base/artifact/SourcesArtifact.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/JvmLibrary.java
Labels: @jvm, from:member

#15695 De-incubate split-project property of init task
  subprojects/build-init/src/main/java/org/gradle/buildinit/tasks/InitBuild.java
  subprojects/docs/src/docs/release/notes.md
Labels: @idiomatic, from:member, in:build-init-plugin

#15518 Remove deprecated class `UnableToDeleteFileException`
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/core-api/src/main/java/org/gradle/api/file/UnableToDeleteFileException.java
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
Labels: @idiomatic, a:chore, from:member

#15704 Fix worker classpath vs. module path setup
  subprojects/core/src/main/java/org/gradle/process/internal/worker/child/ApplicationClassesInSystemClassLoaderWorkerImplementationFactory.java
  subprojects/platform-play/src/integTest/groovy/org/gradle/play/tasks/PlayRunIntegrationTest.groovy
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/ForkingTestClassProcessor.java
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerDaemonIntegrationTest.groovy
Labels: @jvm, from:member, in:modular-java

#15705 Promote Kotlin DSL members from incubation
  subprojects/docs/src/docs/release/notes.md
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/ArtifactHandlerExtensions.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/ExtensionContainerExtensions.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinSettingsScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/PluginDependenciesSpecExtensions.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/ProjectExtensions.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/ScriptHandlerExtensions.kt
  subprojects/tooling-api/src/main/java/org/gradle/tooling/model/kotlin/dsl/EditorPosition.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/model/kotlin/dsl/EditorReport.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/model/kotlin/dsl/EditorReportSeverity.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/model/kotlin/dsl/KotlinDslModelsParameters.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/model/kotlin/dsl/KotlinDslScriptModel.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/model/kotlin/dsl/KotlinDslScriptsModel.java
Labels: a:chore, from:member, in:kotlin-dsl

#15708 De-incubate `JavaVersion` APIs
  subprojects/base-services/src/main/java/org/gradle/api/JavaVersion.java
  subprojects/base-services/src/test/groovy/org/gradle/api/JavaVersionSpec.groovy
  subprojects/docs/src/docs/release/notes.md
Labels: @jvm, from:member, in:core

#15709 Deincubate JVM testing APIs
  subprojects/docs/src/docs/release/notes.md
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaBasePlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaTestFixturesPlugin.java
  subprojects/testing-base/src/main/java/org/gradle/api/tasks/testing/TestFilter.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java
Labels: @jvm, from:member, in:testing

#15563 Remove deprecated methods from BasePluginConvention
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/docs/src/docs/dsl/org.gradle.api.plugins.BasePluginConvention.xml
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
  subprojects/ear/src/test/groovy/org/gradle/plugins/ear/EarPluginTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/BasePluginConvention.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/DefaultBasePluginConvention.java
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/BasePluginTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/DefaultBasePluginConventionTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/JavaBasePluginTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/JavaPluginTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/WarPluginTest.groovy
Labels: @idiomatic, a:chore, from:member

#15374 Make sure intermediate build operations are emitted
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/DefaultNestedTestSuiteDescriptor.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitSupport.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/junit/result/JUnitXmlResultWriter.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/junit/result/TestReportDataCollector.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java
  subprojects/testing-base/src/test/groovy/org/gradle/api/internal/tasks/testing/logging/FullExceptionFormatterTest.groovy
  subprojects/testing-junit-platform/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestExecutionListener.java
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformIntegrationTest.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/TestLauncherSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r69/TestDisplayNameCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r70/TestDisplayNameCrossVersionSpec.groovy
Labels: @jvm, a:bug, from:member, in:testing

#15623 Drop binary compatibility with Groovy task subclasses statically compiled against Gradle < 5.0
  subprojects/integ-test/src/crossVersionTest/groovy/org/gradle/integtests/StaticGroovyTaskSubclassingBinaryCompatibilityCrossVersionSpec.groovy
Labels: @configuration-cache, a:chore, from:member, in:testing

#15578 Deincubate `ProviderFactory.gradleProperty`, `systemProperty`, `environmentVariable` and `fileContents`
  subprojects/core-api/src/main/java/org/gradle/api/file/FileContents.java
  subprojects/core-api/src/main/java/org/gradle/api/provider/ProviderFactory.java
  subprojects/docs/src/docs/release/notes.md
Labels: @configuration-cache, a:chore, from:member

#15738 Keep transform results in immutable caches in memory between builds
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementGradleUserHomeScopeServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/AbstractRealLifeAndroidBuildPerformanceTest.groovy
Labels: @execution

#15324 Handle exceptions thrown in shutting-down process
  subprojects/core/src/main/java/org/gradle/process/internal/shutdown/ShutdownHooks.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/DaemonRegistryUpdater.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/DefaultIncomingConnectionHandler.java
Labels: @dev-productivity, from:member

#15750 Do not fail build when tasks with missing dependencies run in parallel
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/execution/plan/LocalTaskNodeExecutor.java
Labels: @execution, from:member

#15749 Polish `configuration-cache/build.gradle.kts`
  subprojects/configuration-cache/build.gradle.kts
Labels: @configuration-cache, a:chore, from:member, in:configuration-cache

#15712 Upgrade smoke tested AGP versions
  gradle/dependency-management/agp-versions.properties
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/AndroidGradlePluginVersions.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerJavaCachingSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerKotlinCachingSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginAndroidGroovyDSLSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginAndroidKotlinDSLSmokeTest.groovy
Labels: @configuration-cache, a:chore, from:member

#15765 Fix properties normalization when bad unicode sequences are encountered
  subprojects/core/src/integTest/groovy/org/gradle/normalization/ConfigureRuntimeClasspathNormalizationIntegrationTest.groovy
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/PropertiesFileAwareClasspathResourceHasher.java
  subprojects/normalization-java/src/test/groovy/org/gradle/api/internal/changedetection/state/PropertiesFileAwareClasspathResourceHasherTest.groovy
Labels: @execution, a:bug, from:member, in:core

#15776 Promote `Provider#forUseAtConfigurationTime`
  subprojects/core-api/src/main/java/org/gradle/api/provider/Provider.java
  subprojects/docs/src/docs/release/notes.md
Labels: @configuration-cache, a:chore, from:member, in:core

#15783 Read credentials from env variables
  .teamcity/Gradle_Check/configurations/BaseGradleBuildType.kt
  .teamcity/Gradle_Check/configurations/GradleBuildConfigurationDefaults.kt
  .teamcity/Gradle_Check/configurations/PerformanceTest.kt
  .teamcity/Gradle_Check/configurations/PerformanceTestsPass.kt
  .teamcity/Gradle_Check/configurations/StagePasses.kt
  .teamcity/Gradle_Util_Performance/buildTypes/AdHocPerformanceScenario.kt
  .teamcity/common/BuildCache.kt
  .teamcity/common/performance-test-extensions.kt
  .teamcityTest/Gradle_Check_Tests/ApplyDefaultConfigurationTest.kt
  .teamcityTest/Gradle_Check_Tests/CIConfigIntegrationTests.kt
  .teamcityTest/Gradle_Check_Tests/PerformanceTestBuildTypeTest.kt
  build-logic/build-update-utils/src/main/kotlin/gradlebuild/buildutils/tasks/UpdateBranchStatus.kt
  build-logic/performance-testing/src/main/kotlin/gradlebuild/performance/PerformanceTestPlugin.kt
  build-logic/performance-testing/src/main/kotlin/gradlebuild/performance/tasks/BuildCommitDistribution.kt
  gradle/verification-metadata.xml
  settings.gradle.kts
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/timeout/JavaProcessStackTracesMonitor.java
Labels: from:member

#15784 Avoid scan project directory when publishing artifacts
  .teamcity/common/extensions.kt
  build-logic/buildquality/src/main/kotlin/gradlebuild.ci-reporting.gradle.kts
Labels: @dev-productivity, from:member

#15779 Promote APIs of Scala plugin introduced in 6.x releases
  subprojects/docs/src/docs/release/notes.md
  subprojects/scala/src/main/java/org/gradle/api/plugins/scala/ScalaBasePlugin.java
  subprojects/scala/src/main/java/org/gradle/api/plugins/scala/ScalaPluginExtension.java
  subprojects/scala/src/main/java/org/gradle/api/tasks/scala/IncrementalCompileOptions.java
  subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaCompile.java
  subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaDoc.java
Labels: a:chore, from:member, in:scala-plugin

#15763 De-incubate --watch-fs command-line parameter
  subprojects/core/src/main/java/org/gradle/initialization/StartParameterBuildOptions.java
Labels: @execution, from:member

#15780 Promote minor API additions introduced in 5.1 and 5.2
  subprojects/core-api/src/main/java/org/gradle/api/ProjectConfigurationException.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/plugins/src/main/java/org/gradle/api/tasks/SourceSetOutput.java
  subprojects/test-kit/src/main/java/org/gradle/testkit/runner/GradleRunner.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/events/configuration/ProjectConfigurationProgressEvent.java
Labels: a:chore, from:member, in:core

#15771 Let AGP 7 smoke tests run on CI
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/AndroidGradlePluginVersions.groovy
  subprojects/smoke-test/build.gradle.kts
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerJavaCachingSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerKotlinCachingSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy
Labels: @configuration-cache, a:chore, from:member

#15745 Promote destination/classes directory properties used by compile tasks
  subprojects/core-api/src/main/java/org/gradle/api/file/SourceDirectorySet.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/jvm/groovy_plugin.adoc
  subprojects/docs/src/docs/userguide/jvm/java_plugin.adoc
  subprojects/language-jvm/src/main/java/org/gradle/api/tasks/compile/AbstractCompile.java
Labels: @jvm, from:member

#15777 Promote TaskReportTask.displayGroup
  subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/TaskReportTask.java
  subprojects/docs/src/docs/release/notes.md
Labels: a:chore, from:member, in:core

#15778 Promote APIs of SigningExtension and Sign task
  subprojects/docs/src/docs/release/notes.md
  subprojects/signing/src/main/java/org/gradle/plugins/signing/Sign.java
  subprojects/signing/src/main/java/org/gradle/plugins/signing/SigningExtension.java
Labels: a:chore, from:member, in:signing-plugin

#15758 Ignore missing dependency if there is an explicit ordering
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalBuildIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/execution/plan/LocalTaskNodeExecutor.java
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/ApplicationIntegrationSpec.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/StaleOutputIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/javadoc/JavadocWorkAvoidanceIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/antmigration/SamplesAntImportIntegrationTest.groovy
Labels: @execution, from:member

#15774 Promote BuildInvocationDetails interface
  subprojects/core-api/src/main/java/org/gradle/api/invocation/BuildInvocationDetails.java
  subprojects/docs/src/docs/release/notes.md
Labels: a:chore, from:member, in:core

#15775 Promote TypeOf.getConcreteClass()
  subprojects/core-api/src/main/java/org/gradle/api/reflect/TypeOf.java
  subprojects/docs/src/docs/release/notes.md
Labels: a:chore, from:member, in:core

#15791 Promote all methods of ObjectFactory that are still incubating
  subprojects/core-api/src/main/java/org/gradle/api/model/ObjectFactory.java
  subprojects/docs/src/docs/release/notes.md
Labels: a:chore, from:member, in:core

#15767 Remove deprecated `org.gradle.logging.LoggingManager`
  subprojects/core/src/crossVersionTest/groovy/org/gradle/testfixtures/ProjectBuilderCrossVersionIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/DefaultTask.java
  subprojects/core/src/main/java/org/gradle/api/internal/AbstractTask.java
  subprojects/core/src/main/java/org/gradle/api/internal/TaskInternal.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingTransformer.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuterTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/classpath/DefaultCachedClasspathTransformerTest.groovy
  subprojects/docs/src/snippets/kotlinDsl/interoperability-closure-of/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/plugins/buildscript/groovy/build.gradle
  subprojects/docs/src/snippets/plugins/buildscript/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/plugins/dsl/groovy/build.gradle
  subprojects/docs/src/snippets/plugins/dsl/kotlin/build.gradle.kts
  subprojects/logging/src/main/java/org/gradle/internal/logging/compatbridge/LoggingManagerInternalCompatibilityBridge.java
  subprojects/logging/src/main/java/org/gradle/logging/LoggingManagerInternal.java
  subprojects/logging/src/main/java/org/gradle/logging/ProgressLoggerFactory.java
  subprojects/logging/src/main/java/org/gradle/logging/StandardOutputCapture.java
  subprojects/logging/src/main/java/org/gradle/logging/StyledTextOutputFactory.java
Labels: @configuration-cache, a:chore, from:member

#15798 Promote EAR plugin deployment descriptor generation configuration
  subprojects/docs/src/docs/release/notes.md
  subprojects/ear/src/main/java/org/gradle/plugins/ear/Ear.java
  subprojects/ear/src/main/java/org/gradle/plugins/ear/EarPluginConvention.java
Labels: a:chore, from:member, in:ear-plugin

#15797 Promote Groovy plugin APIs added in 5.x and 6.1
  subprojects/docs/src/docs/release/notes.md
  subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java
  subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompileOptions.java
Labels: a:chore, from:member, in:groovy-plugin

#15793 Promote pluginManagement.plugins { }
  subprojects/core-api/src/main/java/org/gradle/plugin/management/PluginManagementSpec.java
  subprojects/docs/src/docs/release/notes.md
Labels: a:chore, from:member, in:plugin-management

#15790 Promote Worker API
  subprojects/docs/src/docs/release/notes.md
  subprojects/workers/src/main/java/org/gradle/workers/ClassLoaderWorkerSpec.java
  subprojects/workers/src/main/java/org/gradle/workers/ForkingWorkerSpec.java
  subprojects/workers/src/main/java/org/gradle/workers/ProcessWorkerSpec.java
  subprojects/workers/src/main/java/org/gradle/workers/WorkAction.java
  subprojects/workers/src/main/java/org/gradle/workers/WorkParameters.java
  subprojects/workers/src/main/java/org/gradle/workers/WorkQueue.java
  subprojects/workers/src/main/java/org/gradle/workers/WorkerExecutor.java
  subprojects/workers/src/main/java/org/gradle/workers/WorkerSpec.java
Labels: a:chore, from:member, in:workers

#15759 Make it an error to not handle duplicates explicitly
  build-logic/build-platform/build.gradle.kts
  gradle/verification-metadata.xml
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/bundling/ArchiveIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/file/DefaultFileOperations.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/CopyActionExecuter.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DuplicateHandlingCopyActionDecorator.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/FileCopier.java
  subprojects/core/src/main/java/org/gradle/api/tasks/AbstractCopyTask.java
  subprojects/core/src/main/java/org/gradle/api/tasks/bundling/AbstractArchiveTask.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/WorkerSharedProjectScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/DefaultFileOperationsTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/copy/CopyActionExecuterTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/copy/DuplicateHandlingCopyActionExecutorTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/copy/SyncCopyActionDecoratorTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/api/internal/file/TestFiles.java
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/ArchivesContinuousIntegrationTest.groovy
  subprojects/tooling-api/build.gradle.kts
Labels: @execution, a:chore, from:member

#15795 Fix Kotlin compiler warning rewriting when configured to turn warnings to errors
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginTest.kt
  subprojects/kotlin-dsl-plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslCompilerPlugins.kt
Labels: a:regression, from:member, in:kotlin-dsl

#15799 Promote APIs for composite build naming and beforeSettings
  subprojects/core-api/src/main/java/org/gradle/api/initialization/ConfigurableIncludedBuild.java
  subprojects/core-api/src/main/java/org/gradle/api/invocation/Gradle.java
  subprojects/core/src/main/java/org/gradle/api/tasks/GradleBuild.java
  subprojects/docs/src/docs/release/notes.md
Labels: a:chore, from:member, in:composite-builds

#15746 Remove the default `uploadArchives` task
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/projectmodule/ProjectPublicationRegistry.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/ivypublish/package-info.java
  subprojects/docs/src/docs/userguide/authoring-builds/software-product/composite_builds.adoc
  subprojects/docs/src/docs/userguide/authoring-builds/working_with_files.adoc
  subprojects/docs/src/docs/userguide/core-plugins/base_plugin.adoc
  subprojects/docs/src/docs/userguide/core-plugins/distribution_plugin.adoc
  subprojects/docs/src/docs/userguide/dep-man/06-publishing/publishing_ivy.adoc
  subprojects/docs/src/docs/userguide/dep-man/06-publishing/publishing_setup.adoc
  subprojects/docs/src/docs/userguide/dep-man/06-publishing/signing_plugin.adoc
  subprojects/docs/src/docs/userguide/jvm/java_plugin.adoc
  subprojects/docs/src/docs/userguide/legacy/artifact_management.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_4.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
  subprojects/docs/src/snippets/artifacts/uploading/groovy/build.gradle
  subprojects/docs/src/snippets/artifacts/uploading/groovy/settings.gradle
  subprojects/docs/src/snippets/artifacts/uploading/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/artifacts/uploading/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/artifacts/uploading/tests/archiveTaskArtifact.sample.conf
  subprojects/docs/src/snippets/java/quickstart/groovy/build.gradle
  subprojects/docs/src/snippets/java/quickstart/kotlin/build.gradle.kts
  subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/AbstractIvyPublishIntegTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/AbstractLegacyIvyPublishTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/IvyEarProjectPublishIntegrationTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/IvyHttpPublishIntegrationTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/IvyJavaProjectPublishIntegrationTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/IvyLocalPublishIntegrationTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/IvySingleProjectPublishIntegrationTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/IvyVersionRangePublishIntegrationTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/IvyWarProjectPublishIntegrationTest.groovy
  subprojects/ivy/src/testFixtures/groovy/org/gradle/api/publish/ivy/AbstractIvyRemoteLegacyPublishIntegrationTest.groovy
  subprojects/ivy/src/testFixtures/groovy/org/gradle/api/publish/ivy/WithUploadArchives.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/integtests/publish/maven/MavenPomConfigurationPublishIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/internal/plugins/UploadRule.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/BasePlugin.java
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/BasePluginTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesJavaQuickstartIntegrationTest.groovy
  subprojects/signing/src/main/java/org/gradle/plugins/signing/SigningExtension.java
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r112/PublicationsCrossVersionSpec.groovy
Labels: @core, a:chore, from:member, in:core

#15811 Promote classpath normalization of manifest and meta-inf properties
  subprojects/core-api/src/main/java/org/gradle/normalization/MetaInfNormalization.java
  subprojects/core-api/src/main/java/org/gradle/normalization/RuntimeClasspathNormalization.java
  subprojects/docs/src/docs/release/notes.md
Labels: a:chore, from:member, in:core

#15816 Let `GeneratePrecompiledScriptPluginAccessors` fail the build
  build-logic/gradle.properties
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/precompiled/PrecompiledScriptPluginAccessorsTest.kt
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/DefaultPrecompiledScriptPluginsSupport.kt
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/tasks/GeneratePrecompiledScriptPluginAccessors.kt
Labels: @configuration-cache, a:chore, from:member, in:gradle-build, in:kotlin-dsl

#15809 Promote various small API additions introduced in 6.x releases
  subprojects/core-api/src/main/java/org/gradle/api/Generated.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/verification/DependencyVerificationMode.java
  subprojects/core-api/src/main/java/org/gradle/api/provider/Provider.java
  subprojects/core-api/src/main/java/org/gradle/api/provider/ProviderFactory.java
  subprojects/core-api/src/main/java/org/gradle/api/resources/TextResourceFactory.java
  subprojects/core/src/main/java/org/gradle/api/tasks/AbstractExecTask.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/UnresolvedLibrary.java
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/tasks/JacocoReport.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/JavaExec.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/CompileOptions.java
  subprojects/logging/src/main/java/org/gradle/api/logging/configuration/WarningMode.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JvmEcosystemPlugin.java
  subprojects/reporting/src/main/java/org/gradle/api/reporting/Report.java
  subprojects/testing-base/src/main/java/org/gradle/api/tasks/testing/JUnitXmlReport.java
  subprojects/testing-base/src/main/java/org/gradle/api/tasks/testing/TestDescriptor.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/events/OperationCompletionListener.java
Labels: a:chore, from:member, in:core

#15813 Do a simple deduplication when searching for missing task dependencies
  subprojects/core/src/main/java/org/gradle/execution/plan/LocalTaskNodeExecutor.java
Labels: @execution, from:member

#15810 Preserve backward compatibility with plugins compiled with Gradle < 5.0
  subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingTransformer.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GreetingSamplePluginSmokeTest.groovy
Labels: @configuration-cache, a:chore, from:member

#15821 Fix `GradleBuildConfigurationCacheSmokeTest`
  build-logic-commons/gradle.properties
  gradle.properties
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildConfigurationCacheSmokeTest.groovy
Labels: @configuration-cache, a:chore, from:member, in:gradle-build

#15540 Remove legacy toolchain support from jvm tasks
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/docs/src/docs/dsl/org.gradle.api.tasks.javadoc.Javadoc.xml
  subprojects/language-groovy/src/integTest/groovy/org/gradle/language/groovy/GroovyCompileJavaVersionTrackingIntegrationTest.groovy
  subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileJavaVersionIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/language/java/JavaLanguageIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/AbstractJavaToolChain.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/CurrentJvmJavaToolChain.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/JavaHomeBasedJavaToolChain.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/JavaToolChainFactory.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/javadoc/Javadoc.java
  subprojects/language-java/src/main/java/org/gradle/language/java/internal/JavaToolChainServiceRegistry.java
  subprojects/language-java/src/main/java/org/gradle/language/java/plugins/JavaLanguagePlugin.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/AbstractJavaToolChainTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/JavaHomeBasedJavaToolChainTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/tasks/compile/JavaCompileTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/tasks/javadoc/JavadocTest.groovy
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/internal/services/PlatformJvmServices.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/JavaToolchainSpec.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/CurrentJvmToolchainSpec.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/DefaultToolchainSpec.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainInput.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainQueryService.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/SpecificInstallationToolchainSpec.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/ToolchainSpecInternal.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaBasePlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/DefaultJavaPluginConvention.java
Labels: @jvm, from:member

#15831 Follow-up of security fix
  .gitignore
  .idea/codeStyles/Project.xml
  .teamcity/Gradle_Check/configurations/BaseGradleBuildType.kt
  .teamcity/Gradle_Check/configurations/GradleBuildConfigurationDefaults.kt
  .teamcity/Gradle_Check/configurations/PerformanceTest.kt
  .teamcity/Gradle_Check/configurations/StagePasses.kt
  .teamcity/Gradle_Check/configurations/TestPerformanceTest.kt
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  .teamcity/Gradle_Promotion/buildTypes/PublishGradleDistribution.kt
  .teamcity/Gradle_Util/buildTypes/WarmupEc2Agent.kt
  .teamcity/Gradle_Util_Performance/buildTypes/AdHocPerformanceScenario.kt
  .teamcity/common/BuildCache.kt
  .teamcity/common/performance-test-extensions.kt
  .teamcityTest/Gradle_Check_Tests/PerformanceTestBuildTypeTest.kt
  build-logic/lifecycle/src/main/kotlin/gradlebuild.lifecycle.gradle.kts
  gradle/verification-metadata.xml
  settings.gradle.kts
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/timeout/IntegrationTestTimeoutInterceptor.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/timeout/JavaProcessStackTracesMonitor.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/ChainingHttpHandler.java
  subprojects/internal-integ-testing/src/test/groovy/org/gradle/integtests/fixtures/timeout/JavaProcessStackTracesMonitorSpec.groovy
Labels: from:member

#15806 Remove `ValidateTaskProperties`
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidatePluginsIntegrationTest.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidateTaskPropertiesIntegrationTest.groovy
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/plugins/JavaGradlePluginPlugin.java
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/ValidatePlugins.java
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/ValidateTaskProperties.java
  subprojects/plugin-development/src/test/groovy/org/gradle/plugin/devel/plugins/JavaGradlePluginPluginTest.groovy
Labels: @execution, a:chore, from:member

#15764 Fix invalid project identity in publication
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/projectmodule/DefaultProjectDependencyPublicationResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/projectmodule/ProjectDependencyPublicationResolver.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/projectmodule/DefaultProjectDependencyPublicationResolverTest.groovy
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/versionmapping/DefaultVersionMappingStrategy.java
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishMultiProjectIntegTest.groovy
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/versionmapping/DefaultVariantVersionMappingStrategy.java
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/versionmapping/DefaultVersionMappingStrategy.java
Labels: @jvm, from:member, in:publishing-plugin

#15836 Promote dependency locking (command line options)
  subprojects/core/src/main/java/org/gradle/initialization/StartParameterBuildOptions.java
Labels: @jvm, a:chore, in:dependency-management

#15835 Promote dependency verification
  subprojects/core/src/main/java/org/gradle/initialization/StartParameterBuildOptions.java
  subprojects/docs/src/docs/release/notes.md
Labels: @jvm, a:chore, from:member, in:dependency-management

#15832 Promote Pmd and CodeNarc plugin API additions
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CodeNarc.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/Pmd.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdExtension.java
  subprojects/docs/src/docs/release/notes.md
Labels: a:chore, from:member, in:codenarc-plugin, in:pmd-plugin

#15834 Fix umbrella build definition of 'structuring software projects' sample
  subprojects/docs/src/samples/build-organization/structuring-software-projects/groovy/settings.gradle
  subprojects/docs/src/samples/build-organization/structuring-software-projects/kotlin/settings.gradle.kts
  subprojects/docs/src/samples/build-organization/structuring-software-projects/tests/umbrella-build.sample.conf
Labels: from:member, in:composite-builds

#15837 Promote changing the priority of the daemon process
  subprojects/docs/src/docs/release/notes.md
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/configuration/DaemonBuildOptions.java
Labels: @core, a:chore, from:member, in:core

#15814 De-incubate APIs
  subprojects/core-api/src/main/java/org/gradle/api/Task.java
  subprojects/core-api/src/main/java/org/gradle/api/file/FileType.java
  subprojects/core-api/src/main/java/org/gradle/api/model/ReplacedBy.java
  subprojects/core-api/src/main/java/org/gradle/api/reflect/InjectionPointQualifier.java
  subprojects/docs/src/docs/release/notes.md
Labels: @execution, a:chore, from:member

#15845 Add test for stale precompiled script plugin issue
  subprojects/core/src/main/java/org/gradle/testfixtures/internal/ProjectBuilderImpl.java
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/PrecompiledScriptPluginIntegrationTest.kt
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/tasks/GeneratePrecompiledScriptPluginAccessors.kt
Labels: a:bug, from:member, in:kotlin-dsl

#15838 Remove JavaToolChain and JavaPlatform
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/language-java/src/integTest/groovy/org/gradle/language/java/VariantAwareDependencyResolutionSpec.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/AbstractJavaToolChain.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/CurrentJvmJavaToolChain.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
  subprojects/language-java/src/main/java/org/gradle/language/java/internal/JavaToolChainServiceRegistry.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/AbstractJavaToolChainTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/CurrentJvmJavaToolChainTest.groovy
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/internal/DefaultJvmAssembly.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/internal/JavaPlatformResolver.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/internal/JvmAssembly.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/internal/resolve/DefaultJavaPlatformVariantAxisCompatibility.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/internal/services/PlatformJvmServices.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/internal/toolchain/JavaToolChainInternal.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/platform/JavaPlatform.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/platform/internal/DefaultJavaPlatform.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/platform/package-info.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/JavaToolChain.java
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/internal/resolve/DefaultJavaPlatformVariantAxisCompatibilityTest.groovy
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/platform/internal/DefaultJavaPlatformTest.groovy
Labels: @jvm

#15855 De-duplicate nodes when searching for missing dependencies
  subprojects/core/src/main/java/org/gradle/execution/plan/LocalTaskNodeExecutor.java
Labels: @execution, from:member

#15817 Do not register root build substitutions by default
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildDependencyGraphIntegrationTest.groovy
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildIncludeCycleIntegrationTest.groovy
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildRootProjectIntegrationTest.groovy
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultIncludedBuildRegistry.java
  subprojects/core/src/main/java/org/gradle/internal/build/BuildStateRegistry.java
  subprojects/core/src/main/java/org/gradle/internal/composite/ChildBuildRegisteringSettingsLoader.java
  subprojects/docs/src/docs/userguide/authoring-builds/software-product/composite_builds.adoc
Labels: @idiomatic, a:regression, from:member, in:composite-builds

#15865 Update Gradle wrapper to latest nightly
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore, from:member

#15849 Re-enable unconfigured Groovy tests in build-logic project
  build-logic/build-update-utils/build.gradle.kts
  build-logic/cleanup/build.gradle.kts
  build-logic/cleanup/src/test/groovy/gradlebuild/cleanup/services/LeakingProcessKillPatternTest.groovy
Labels: @core, a:chore

#15852 Smoke test Kotlin 1.4.30-RC
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/KotlinGradlePluginVersions.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
Labels: a:chore, from:member

#15833 Fix NPE in Maven2Gradle conversion
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/MavenConversionIntegrationTest.groovy
  subprojects/build-init/src/integTest/resources/org/gradle/buildinit/plugins/MavenConversionIntegrationTest/compilePluginWithoutConfiguration/some-thing/pom.xml
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/maven/Maven2Gradle.java
Labels: a:regression, from:member, in:build-init-plugin

#15869 Upgrade Spock to version 2 in build-logic build
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.build-logic.groovy-dsl-gradle-plugin.gradle.kts
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.build-logic.kotlin-dsl-gradle-plugin.gradle.kts
  build-logic/build-platform/build.gradle.kts
  build-logic/packaging/build.gradle.kts
  gradle/verification-metadata.xml
Labels: @core, a:chore, from:member

#15887 Fix broken links in Kotlin DSL primer
  subprojects/docs/src/docs/userguide/api/kotlin_dsl.adoc
Labels: a:bug, from:member, in:docs

#15863 Groovy and Scala support for central repository declaration
  subprojects/core/src/main/java/org/gradle/initialization/ScriptEvaluatingSettingsProcessor.java
  subprojects/core/src/main/java/org/gradle/initialization/SettingsEvaluatedCallbackFiringSettingsProcessor.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/RepositoriesDeclaredInSettingsIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/GroovyProjectIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/tasks/GroovyRuntime.java
  subprojects/scala/src/integTest/groovy/org/gradle/integtests/ScalaProjectIntegrationTest.groovy
  subprojects/scala/src/main/java/org/gradle/api/tasks/ScalaRuntime.java
  subprojects/scala/src/test/groovy/org/gradle/api/tasks/ScalaRuntimeTest.groovy
Labels: from:member, in:groovy-plugin, in:scala-plugin

#15851 Take filtering into account for missing dependency detection
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java
  subprojects/core/src/main/java/org/gradle/execution/plan/ExecutionNodeAccessHierarchies.java
  subprojects/core/src/main/java/org/gradle/execution/plan/ExecutionNodeAccessHierarchy.java
  subprojects/core/src/main/java/org/gradle/execution/plan/LocalTaskNodeExecutor.java
  subprojects/core/src/main/java/org/gradle/execution/plan/RelatedLocations.java
  subprojects/core/src/main/java/org/gradle/execution/plan/ValuedVfsHierarchy.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GradleScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/execution/plan/DefaultExecutionPlanParallelTest.groovy
  subprojects/core/src/test/groovy/org/gradle/execution/plan/DefaultExecutionPlanTest.groovy
  subprojects/core/src/test/groovy/org/gradle/execution/plan/ExecutionNodeAccessHierarchyTest.groovy
  subprojects/core/src/test/groovy/org/gradle/execution/taskgraph/DefaultTaskExecutionGraphSpec.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/StaleOutputIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/javadoc/JavadocWorkAvoidanceIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/antmigration/SamplesAntImportIntegrationTest.groovy
Labels: @execution, from:member

#15883 Re-enable AGP lint task smoke test
  gradle/dependency-management/agp-versions.properties
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/AndroidGradlePluginVersions.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy
Labels: @execution, from:member

#15878 Update configuration deprecations
  subprojects/core/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultProjectDependency.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/DeprecatedConfigurationsIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultDependencyConstraintSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultDependencySet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/DefaultArtifactHandler.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/LocalComponentDependencyMetadata.java
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/OutgoingVariantsReportTaskIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/dependencies/JavaConfigurationSetupIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaBasePlugin.java
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/JavaLibraryPluginTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/JavaPluginTest.groovy
Labels: a:chore, from:member, in:dependency-management

#15884 Promote incubating methods in ProjectDependency
  subprojects/docs/src/docs/release/notes.md
  subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/ProjectDependency.java
Labels: a:chore, from:member, in:eclipse-plugin

#15841 Promote ComponentSelector in EclipseExternalDependency
  subprojects/docs/src/docs/release/notes.md
  subprojects/tooling-api/src/main/java/org/gradle/tooling/model/ComponentSelector.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/model/eclipse/EclipseExternalDependency.java
Labels: a:chore, from:member, in:tooling-api

#15843 De-incubate more APIs
  subprojects/antlr/src/main/java/org/gradle/api/plugins/antlr/AntlrTask.java
  subprojects/core-api/src/main/java/org/gradle/api/tasks/WorkResult.java
  subprojects/core-api/src/main/java/org/gradle/caching/BuildCacheKey.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
Labels: @execution, a:chore, from:member

#15761 Enable file system watching by default
  subprojects/composite-builds/build.gradle.kts
  subprojects/core/src/main/java/org/gradle/api/internal/StartParameterInternal.java
  subprojects/core/src/main/java/org/gradle/initialization/BuildOptionBuildOperationProgressEventsEmitter.java
  subprojects/core/src/main/java/org/gradle/initialization/StartParameterBuildOptions.java
  subprojects/docs/src/docs/userguide/reference/command_line_interface.adoc
  subprojects/docs/src/docs/userguide/running-builds/build_environment.adoc
  subprojects/docs/src/docs/userguide/running-builds/gradle_daemon.adoc
  subprojects/docs/src/docs/userguide/running-builds/performance.adoc
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/EnableFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/BuildLifecycleAwareVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/VfsLogging.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/WatchLogging.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/WatchMode.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingNotSupportedVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingNotSupportedVirtualFileSystemTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystemTest.groovy
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/action/BuildActionSerializer.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunner.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/LauncherServices.java
  subprojects/launcher/src/test/groovy/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunnerTest.groovy
  subprojects/tooling-api/src/integTest/groovy/org/gradle/integtests/tooling/ToolingApiClasspathIntegrationTest.groovy
Labels: @execution, from:member

#15854 Remove deprecated VFS flags
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/EnableFileSystemWatchingIntegrationTest.groovy
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunner.java
Labels: @execution

#15892 Do not fail if test failure has no exceptions
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/junit/result/JUnitXmlResultWriter.java
  subprojects/testing-base/src/test/groovy/org/gradle/api/internal/tasks/testing/junit/result/JUnitXmlResultWriterSpec.groovy
Labels: from:member, in:testing

#15898 Mention file system watching among the release's features
  subprojects/launcher/src/main/resources/release-features.txt
Labels: @execution, from:member

#15899 Re-enable smoke tests after Spock upgrade
  subprojects/smoke-test/build.gradle.kts
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/play/integtest/external/PlayExternalContinuousBuildIntegrationTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/play/integtest/fixtures/external/AbstractPlayExternalContinuousBuildIntegrationTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerKotlinCachingSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuild.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildConfigurationCacheSmokeTest.groovy
Labels: from:member, in:gradle-build

#15897 Remove no longer needed test workarounds
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/ConfigurationRoleIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/bundling/JavaBundlingResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/capabilities/CapabilitiesUseCasesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/strict/StrictVersionsInPlatformCentricDevelopmentIntegrationTest.groovy
  subprojects/platform-native/src/integTest/groovy/org/gradle/nativeplatform/NativeDependentComponentsIntegrationSpec.groovy
Labels: @core, a:chore, from:member

#15896 Unignore temporarily ignored test
  subprojects/dependency-management/src/crossVersionTest/groovy/org/gradle/integtests/resolve/artifactreuse/SameCacheUsageCrossVersionIntegrationTest.groovy
Labels: @core, a:chore, from:member

#15902 Fix skipping of unrolled test iterations that are unsupported with config cache
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/ToBeFixedForConfigurationCacheExtension.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/UnsupportedWithConfigurationCacheExtension.groovy
Labels: @core, a:chore, from:member

#15846 De-incubate ignoring of empty directories
  subprojects/core-api/src/main/java/org/gradle/api/tasks/IgnoreEmptyDirectories.java
  subprojects/core-api/src/main/java/org/gradle/api/tasks/TaskInputFilePropertyBuilder.java
  subprojects/core-api/src/main/java/org/gradle/normalization/PropertiesFileNormalization.java
  subprojects/core-api/src/main/java/org/gradle/normalization/RuntimeClasspathNormalization.java
  subprojects/docs/src/docs/release/notes.md
Labels: @execution, a:chore, from:member

#15879 Remove 'search-upwards', 'use-empty-settings' and 'master' directory support
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOptionsIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheHost.kt
  subprojects/core-api/src/main/java/org/gradle/StartParameter.java
  subprojects/core-api/src/main/java/org/gradle/initialization/BuildLayoutParameters.java
  subprojects/core-api/src/test/groovy/org/gradle/StartParameterTest.groovy
  subprojects/core-api/src/test/groovy/org/gradle/initialization/BuildLayoutParametersTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/GradleBuildTaskIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/EvaluateSettingsBuildOperationIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/InitScriptIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/LoadBuildStructureBuildOperationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/BuildDefinition.java
  subprojects/core/src/main/java/org/gradle/api/internal/StartParameterInternal.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultSettingsLoader.java
  subprojects/core/src/main/java/org/gradle/initialization/LayoutCommandLineConverter.java
  subprojects/core/src/main/java/org/gradle/initialization/SettingsLocation.java
  subprojects/core/src/main/java/org/gradle/initialization/buildsrc/BuildSourceBuilder.java
  subprojects/core/src/main/java/org/gradle/initialization/layout/BuildLayout.java
  subprojects/core/src/main/java/org/gradle/initialization/layout/BuildLayoutConfiguration.java
  subprojects/core/src/main/java/org/gradle/initialization/layout/BuildLayoutFactory.java
  subprojects/core/src/test/groovy/org/gradle/initialization/LayoutCommandLineConverterTest.groovy
  subprojects/core/src/test/groovy/org/gradle/initialization/layout/BuildLayoutFactoryTest.groovy
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/action/BuildActionSerializer.java
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/converter/BuildLayoutConverter.java
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/converter/LayoutToPropertiesConverter.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/ProviderConnection.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/connection/ProviderOperationParameters.java
  subprojects/launcher/src/test/groovy/org/gradle/launcher/cli/converter/BuildLayoutConverterTest.groovy
  subprojects/launcher/src/test/groovy/org/gradle/launcher/cli/converter/LayoutToPropertiesConverterTest.groovy
  subprojects/plugin-use/src/main/java/org/gradle/plugin/management/internal/autoapply/DefaultAutoAppliedPluginRegistry.java
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r10rc1/PassingCommandLineArgumentsCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r213/ModelsWithGradleProjectCrossVersionSpec.groovy
  subprojects/tooling-api/src/integTest/groovy/org/gradle/integtests/tooling/ConcurrentToolingApiIntegrationSpec.groovy
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/protocol/BuildOperationParametersVersion1.java
  subprojects/tooling-api/src/testFixtures/groovy/org/gradle/integtests/tooling/fixture/ToolingApi.groovy
Labels: a:chore, from:member, in:core

#15885 Promote methods supporting test debugging via the Tooling API
  subprojects/core-api/src/main/java/org/gradle/process/JavaDebugOptions.java
  subprojects/core-api/src/main/java/org/gradle/process/JavaForkOptions.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/tooling-api/src/main/java/org/gradle/tooling/TestLauncher.java
Labels: a:chore, from:member, in:core, in:tooling-api

#15910 Remove "Watching too many directories" from samples output
  subprojects/docs/src/docsTest/java/org/gradle/docs/samples/BaseSamplesTest.java
  subprojects/docs/src/docsTest/java/org/gradle/docs/samples/Bucket1SnippetsTest.java
  subprojects/docs/src/docsTest/java/org/gradle/docs/samples/Bucket2SnippetsTest.java
  subprojects/docs/src/docsTest/java/org/gradle/docs/samples/Bucket3SnippetsTest.java
  subprojects/docs/src/docsTest/java/org/gradle/docs/samples/SamplesTest.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/logging/FileSystemWatchingOutputNormalizer.groovy
Labels: @execution, from:member

#15913 Migrate ReproducibleArchivesInterceptor to MultiTestInterceptor
  subprojects/ear/src/integTest/groovy/org/gradle/plugins/ear/EarPluginIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/archives/ReproducibleArchivesInterceptor.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/archives/ReproducibleArchivesTestExtension.groovy
  subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/file/CleanupTestDirectoryExtension.groovy
Labels: @core, a:chore, from:member

#15859 Make changing default excludes at runtime an error
  subprojects/core-api/src/main/java/org/gradle/api/tasks/util/internal/PatternSpecFactory.java
  subprojects/core-api/src/test/groovy/org/gradle/api/tasks/util/PatternSetTest.groovy
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
  subprojects/snapshots/src/integTest/groovy/org/gradle/internal/vfs/DefaultExcludesIntegrationTest.groovy
Labels: @execution, a:chore, from:member

#15212 Only expire on full metaspace if GC rate is high
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/server/health/gc/GarbageCollectionMonitoringIntegrationTest.groovy
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/health/DaemonMemoryStatus.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/health/LowHeapSpaceDaemonExpirationStrategy.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/health/LowNonHeapDaemonExpirationStrategy.java
  subprojects/launcher/src/test/groovy/org/gradle/launcher/daemon/server/health/DaemonMemoryStatusTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginAndroidGroovyDSLSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginAndroidKotlinDSLSmokeTest.groovy
  subprojects/soak/src/integTest/groovy/org/gradle/launcher/daemon/DaemonPerformanceMonitoringCoverage.groovy
  subprojects/soak/src/integTest/groovy/org/gradle/launcher/daemon/DaemonPerformanceMonitoringSoakTest.groovy
  subprojects/soak/src/testFixtures/groovy/org/gradle/launcher/daemon/fixtures/DaemonMultiJdkIntegrationTest.groovy
Labels: a:chore, a:performance-issue, from:contributor

#15904 Compute precompiled script accessors via nested build
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.build-logic.kotlin-dsl-gradle-plugin.gradle.kts
  build-logic/buildquality/src/main/kotlin/gradlebuild.ci-reporting.gradle.kts
  build-logic/integration-testing/src/main/kotlin/gradlebuild.cross-version-tests.gradle.kts
  build-logic/integration-testing/src/main/kotlin/gradlebuild.test-fixtures.gradle.kts
  build-logic/integration-testing/src/main/kotlin/gradlebuild/integrationtests/shared-configuration.kt
  build-logic/lifecycle/src/main/kotlin/gradlebuild.lifecycle.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  subprojects/base-services/src/integTest/groovy/org/gradle/internal/operations/BuildOperationExecutorIntegrationTest.groovy
  subprojects/base-services/src/main/java/org/gradle/internal/service/DefaultServiceMethodFactory.java
  subprojects/core-api/src/main/java/org/gradle/StartParameter.java
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/GradleBuildTaskIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalBuildIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/configuration/ExecuteUserLifecycleListenerBuildOperationIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/buildsrc/DisallowBuildSrcAsNameIntegTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/internal/operations/logging/LoggingBuildOperationProgressIntegTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/internal/operations/notify/BuildOperationNotificationIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/internal/scopeids/ScopeIdsIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/tasks/GradleBuild.java
  subprojects/core/src/main/java/org/gradle/internal/build/NestedRootBuildRunner.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/DefaultCachedClasspathTransformer.java
  subprojects/core/src/main/java/org/gradle/internal/invocation/GradleBuildController.java
  subprojects/core/src/main/java/org/gradle/testfixtures/internal/ProjectBuilderImpl.java
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/WatchedDirectoriesFileSystemWatchingIntegrationTest.groovy
  subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/idea/IdeaNestedBuildIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/BuildAggregationIntegrationTest.groovy
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/PrecompiledScriptPluginIntegrationTest.kt
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/precompiled/PrecompiledScriptPluginAccessorsTest.kt
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/tasks/GeneratePrecompiledScriptPluginAccessors.kt
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/GradleBuildContinuousIntegrationTest.groovy
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/taskgrouping/AbstractConsoleGradleBuildGroupedTaskFunctionalTest.groovy
  subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java
Labels: @configuration-cache, a:chore, from:member, in:kotlin-dsl

#15847 Promote new toolchain API
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/TaskReportTaskIntegrationTest.groovy
  subprojects/docs/src/docs/release/notes.md
  subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/JavaExec.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/javadoc/Javadoc.java
  subprojects/platform-jvm/src/integTest/groovy/org/gradle/jvm/toolchain/ShowToolchainsIntegrationTest.groovy
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/JavaCompiler.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/JavaInstallationMetadata.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/JavaLanguageVersion.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/JavaLauncher.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/JavaToolchainService.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/JavaToolchainSpec.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/JavadocTool.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/JvmImplementation.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/JvmVendorSpec.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/task/ShowToolchainsTaskConfigurator.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPluginExtension.java
Labels: @jvm, from:member

#15858 Remove ImmutableFileCollection
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/ImmutableFileCollection.java
  subprojects/file-collections/src/test/groovy/org/gradle/api/internal/file/collections/ImmutableFileCollectionTest.groovy
Labels: @execution, a:chore, from:member

#15914 Remove watchFs tests and corresponding infrastructure
  .teamcity/Gradle_Check/model/CIBuildModel.kt
  build-logic/cleanup/src/main/kotlin/gradlebuild/testing/TestType.kt
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
  build-logic/uber-plugins/src/main/kotlin/gradlebuild.ci-lifecycle.gradle.kts
  subprojects/core/src/integTest/groovy/org/gradle/api/AbstractDomainObjectContainerIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/AbstractFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ContinuousBuildFileWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/FileSystemWatchingSettingsFinalizedBuildOperationIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/FileSystemWatchingFixture.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/FileSystemWatchingGradleExecuter.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/GradleContextualExecuter.java
Labels: @execution, from:member

#15911 Do not stop watching on general overflow event
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DefaultFileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
Labels: @execution, from:member

#15931 Move too many directories watching log from warn to info
  subprojects/docs/src/docsTest/java/org/gradle/docs/samples/BaseSamplesTest.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WatchableHierarchies.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/logging/FileSystemWatchingOutputNormalizer.groovy
Labels: @execution, from:member

#15928 Fix fluid dependencies resolve test variants
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/extensions/FluidDependenciesResolveInterceptor.groovy
Labels: @core, a:bug, a:chore, from:member

#15945 Delete TomcatPluginSmokeTest
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/TomcatPluginSmokeTest.groovy
Labels: from:member

#15940 Remove dead code in play tests
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/play/integtest/fixtures/DistributionTestExecHandleBuilder.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/play/integtest/fixtures/external/AbstractPlayExternalContinuousBuildIntegrationTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/play/integtest/fixtures/external/BasicPlayApp.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/play/integtest/fixtures/external/RunningPlayApp.groovy
Labels: from:member

#15930 Cache `GeneratePrecompiledScriptPluginAccessors` in strict mode
  gradle/wrapper/gradle-wrapper.properties
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/tasks/GeneratePrecompiledScriptPluginAccessors.kt
Labels: @configuration-cache, a:feature, from:member, in:kotlin-dsl

#15933 Move `FileAlreadyExistsException` handling to `InstrumentingClasspathFileTransformer`
  subprojects/core/src/main/java/org/gradle/internal/classpath/ClasspathBuilder.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingClasspathFileTransformer.java
Labels: @configuration-cache, a:chore, from:member, in:core

#15943 Allow selecting inherited Spock2 tests via a subclass filter
  subprojects/testing-junit-platform/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestClassProcessor.java
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junit/JUnitClassLevelFilteringIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformFilteringIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/spock/Spock2FilteringIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/spock/Spock2IntegrationSpec.groovy
Labels: @core, from:member, in:testing

#15912 Wait for changes to be picked up in all tests
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/InProcessGradleExecuter.java
Labels: @execution, from:member

#15948 Exit early for FileSystemNode.hasDescendants
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/AbstractIncompleteFileSystemNode.java
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/AbstractIncompleteFileSystemNodeTest.groovy
Labels: @execution

#15951 Fix more broken links in the kotlin-dsl documentation
  subprojects/docs/src/docs/userguide/api/kotlin_dsl.adoc
  subprojects/docs/src/docs/userguide/migration/migrating_from_groovy_to_kotlin_dsl.adoc
Labels: a:bug, from:member, in:docs, in:kotlin-dsl

#15915 External plugin validation
  subprojects/core/src/main/java/org/gradle/api/internal/plugins/DefaultPluginRegistry.java
  subprojects/core/src/main/java/org/gradle/api/internal/plugins/PluginRegistry.java
  subprojects/plugin-development/build.gradle.kts
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidatePluginsIntegrationTest.groovy
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/plugins/ExternalPluginValidationPlugin.java
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/internal/ValidateAction.java
  subprojects/plugin-development/src/main/resources/META-INF/gradle-plugins/org.gradle.validate-external-gradle-plugin.properties
  subprojects/plugin-development/src/testFixtures/groovy/org/gradle/plugin/devel/tasks/TaskValidationReportFixture.groovy
  subprojects/smoke-test/build.gradle.kts
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractPluginValidatingSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AptPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ArtifactoryAndDockerSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AsciidoctorPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/DetektPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ErrorPronePluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/FlywayPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/FreefairAspectJPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleGitPropertiesSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleVersionsPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GrettySmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/JGitPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/JibPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinCompilerPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KtLintPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/LombokPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/MicronautPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/NebulaPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/NodePluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/PlayPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ProtobufPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ShadowPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/SpotBugsPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/SpotlessPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/SpringBootPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/SpringDependencyManagementPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/UndercouchDownloadPluginSmokeTest.groovy
Labels: @execution, a:chore, from:member

#15597 Remove deprecated org.gradle.api.internal.AbstractTask
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/beans/BeanSchema.kt
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/project/taskfactory/TaskFactoryIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskDefinitionIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/DefaultTask.java
  subprojects/core/src/main/java/org/gradle/api/internal/AbstractTask.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/taskfactory/TaskFactory.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskDestroyablesInternal.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskLocalStateInternal.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingBackwardsCompatibilityVisitor.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingTransformer.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/ExecutionGlobalServices.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/AbstractTaskSpec.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/DefaultTaskTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/taskfactory/AnnotationProcessingTaskFactoryTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/taskfactory/TaskFactoryTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/DefaultTypeMetadataStoreTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/classpath/DefaultCachedClasspathTransformerTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/api/tasks/AbstractSpockTaskTest.groovy
  subprojects/integ-test/src/crossVersionTest/groovy/org/gradle/integtests/TaskSubclassingBinaryCompatibilityCrossVersionSpec.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/language/AbstractNativeParallelIntegrationTest.groovy
Labels: @configuration-cache, a:chore, from:member, in:core

#15949 Fix tests using isolated home in no daemon
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/MavenConversionIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/DaemonGradleExecuter.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/NoDaemonGradleExecuter.java
Labels: from:member, in:testing

#15955 Do not concatenate strings in debug and info log messages
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/AbstractCompositeParticipantBuildState.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultIncludedBuildController.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/IncludedBuildDependencySubstitutionsBuilder.java
  subprojects/core/src/main/java/org/gradle/execution/taskgraph/DefaultTaskExecutionGraph.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/client/DaemonClient.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/health/LowMemoryDaemonExpirationStrategy.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/health/gc/GarbageCollectorMonitoringStrategy.java
  subprojects/native/src/main/java/org/gradle/internal/nativeintegration/services/NativeServices.java
  subprojects/plugins/src/main/java/org/gradle/api/tasks/Upload.java
  subprojects/resources-gcs/src/main/java/org/gradle/internal/resource/transport/gcp/gcs/RetryHttpInitializerWrapper.java
Labels: @core, a:chore, from:member

#15963 Expand Spock2 test filtering test coverage
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/spock/Spock2FilteringIntegrationTest.groovy
Labels: @core, from:member

#15702 ProjectReportsPlugin: migrate remaining task to lazy configuration
  subprojects/diagnostics/src/main/java/org/gradle/api/plugins/ProjectReportsPlugin.java
Labels: @core, from:contributor

#15956 Remove deprecated local build cache configuration
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/core-api/src/main/java/org/gradle/caching/configuration/BuildCacheConfiguration.java
  subprojects/core-api/src/main/java/org/gradle/caching/configuration/CompatibilitySupportForBuildCacheConfiguration.java
  subprojects/core/src/integTest/groovy/org/gradle/caching/configuration/internal/BuildCacheConfigurationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/caching/configuration/internal/DefaultBuildCacheConfiguration.java
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/BuildCacheConfigurationExtensions.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/BuildCacheConfigurationExtensionsTest.kt
Labels: @execution, a:chore, from:member

#15960 Update wrapper to the latest nightly
  gradle/wrapper/gradle-wrapper.properties
Labels: @core, from:member

#15965 Flag deprecated AbstractArchiveTask methods to be removed in Gradle 8
  subprojects/core/src/main/java/org/gradle/api/tasks/bundling/AbstractArchiveTask.java
Labels: a:chore, from:member, in:core

#15857 Remove deprecated domain object collection constructors
  subprojects/core/src/main/java/org/gradle/api/internal/DefaultDomainObjectSet.java
  subprojects/core/src/main/java/org/gradle/api/internal/DefaultNamedDomainObjectList.java
  subprojects/core/src/main/java/org/gradle/api/internal/DefaultNamedDomainObjectSet.java
  subprojects/core/src/main/java/org/gradle/api/internal/DefaultPolymorphicDomainObjectContainer.java
  subprojects/core/src/main/java/org/gradle/api/internal/FactoryNamedDomainObjectContainer.java
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
Labels: a:chore, from:member

#15469 Move C++ below dependency management
  subprojects/docs/src/main/resources/header.html
Labels: from:member

#15957 Remove deprecated methods in `JavaCompile`
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/integ-test/src/crossVersionTest/groovy/org/gradle/integtests/TaskSubclassingBinaryCompatibilityCrossVersionSpec.groovy
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
Labels: @execution, a:chore, from:member

#15964 Fix ExternalPluginValidationPlugin to use instrumented script classpath
  subprojects/core/src/main/java/org/gradle/api/internal/initialization/DefaultScriptHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/initialization/ScriptHandlerInternal.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/initialization/DefaultScriptHandlerTest.groovy
  subprojects/plugin-use/src/main/java/org/gradle/plugin/use/internal/DefaultPluginRequestApplicator.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/NebulaPluginsSmokeTest.groovy
Labels: from:member, in:core, in:plugin-development

#15920 Increase file access journal cache size
  subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/DefaultFileAccessTimeJournal.java
Labels: from:contributor

#15818 Fix Kotlin DSL regression via `-XXLanguage:+DisableCompatibilityModeForNewInference`
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/GradleKotlinDslRegressionsTest.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinBuildScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinInitScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinSettingsScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/KotlinDslPluginSupport.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/KotlinCompiler.kt
Labels: @configuration-cache, a:regression, from:member, in:kotlin-dsl

#15968 Remove `ProcessOperations` interface from `DefaultProject`
  subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProject.java
Labels: @configuration-cache, a:chore, from:member, in:core

#15934 Do not fail the build on invalid declared file inputs
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildDependencyGraphIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskExecutionContext.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/DefaultTaskExecutionContext.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuter.java
  subprojects/core/src/main/java/org/gradle/execution/plan/LocalTaskNodeExecutor.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuterTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/test/fixtures/AbstractProjectBuilderSpec.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ProjectDependencyResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformParallelIntegrationTest.groovy
  subprojects/dependency-management/src/testFixtures/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformTestFixture.groovy
  subprojects/docs/src/docs/userguide/compatibility.adoc
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/resolve/ResolveTestFixture.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractAndroidSantaTrackerSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerJavaCachingSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerKotlinCachingSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginAndroidGroovyDSLSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginAndroidKotlinDSLSmokeTest.groovy
Labels: @execution, from:member
