Repository gradle/gradle, pull requests merged in 2022-11, with the labels that each got.

#22568 Split testing-jvm subproject into testing-jvm-infrastructure
  .github/CODEOWNERS
  .teamcity/subprojects.json
  settings.gradle.kts
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DistributionIntegrationSpec.groovy
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/ForkingTestClassProcessor.java
  subprojects/testing-junit-platform/build.gradle.kts
  subprojects/testing-jvm-infrastructure/build.gradle.kts
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junit/AbstractJUnitSpec.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junit/AbstractJUnitTestClassProcessor.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junit/AllExceptIgnoredTestRunnerBuilder.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junit/CategoryFilter.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junit/IgnoredTestDescriptorProvider.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitSpec.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitTestClassExecutor.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitTestClassProcessor.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitTestClassProcessorFactory.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitTestEventAdapter.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junit/TestClassExecutionEventGenerator.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junit/TestClassExecutionListener.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformSpec.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestClassProcessorFactory.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGClassListener.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGConfigurationListener.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGListenerAdapterFactory.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGSpec.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGTestClassProcessor.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGTestResultProcessorAdapter.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNgTestClassProcessorFactory.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/testng/UnrepresentableParameterException.java
  subprojects/testing-jvm-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/junit/IgnoredTestDescriptorProviderTest.groovy
  subprojects/testing-jvm-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/junit/JUnitTestClassProcessorTest.groovy
  subprojects/testing-jvm-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/junit/JUnitTestEventAdapterTest.groovy
  subprojects/testing-jvm-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/junit/TestClassExecutionEventGeneratorTest.groovy
  subprojects/testing-jvm-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/testng/TestNGListenerAdapterFactorySpec.groovy
  subprojects/testing-jvm-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/testng/TestNGTestClassProcessorTest.groovy
  subprojects/testing-jvm-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/testng/TestNGTestResultProcessorAdapterTest.groovy
  subprojects/testing-jvm-infrastructure/src/testFixtures/groovy/org/gradle/api/internal/tasks/testing/junit/JUnitTestClassProcessorData.groovy
  subprojects/testing-jvm-infrastructure/src/testFixtures/groovy/org/gradle/api/internal/tasks/testing/testng/TestNGTestClassProcessorData.groovy
  subprojects/testing-jvm/build.gradle.kts
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/DefaultAggregateTestReport.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitTestFramework.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestFramework.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGTestFramework.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/testng/TestNGOptions.java
Labels: @core

#22569 Update test bucket json
  .teamcity/test-buckets.json
Labels: @dev-productivity

#22573 Add JavaVersion entries up to Java 24
  subprojects/base-services/src/main/java/org/gradle/api/JavaVersion.java
  subprojects/base-services/src/test/groovy/org/gradle/api/JavaVersionSpec.groovy
Labels: a:feature, in:java-plugins

#22584 Remove the CACHE_MISS condition on m1 mac
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.cache-miss-monitor.gradle.kts
Labels: @dev-productivity

#22593 Remove invalid JavaCompile tests
  subprojects/language-java/src/test/groovy/org/gradle/api/tasks/compile/JavaCompileTest.groovy
Labels: in:toolchains

#22586 Add a test fixture for Java toolchains
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginToolchainsIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcPluginToolchainsIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/pmd/PmdPluginToolchainsIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/jvm/JavaToolchainFixture.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/JavaExecToolchainIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/JavaToolchainBuildOperationsIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileToolchainIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/javadoc/JavadocToolchainIntegrationTest.groovy
  subprojects/platform-jvm/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/JavaBasePluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/groovy/compile/AbstractToolchainGroovyCompileIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/AbstractToolchainZincScalaCompileIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/UpToDateScalaCompileIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/scaladoc/ScalaDocIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestTaskToolchainIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestingIntegrationTest.groovy
Labels: in:toolchains

#22583 Do not remove duplicate test framework jars
  subprojects/testing-jvm/src/integTest/resources/org/gradle/testing/junit/JUnitIntegrationTest/executesTestsInCorrectEnvironment/build.gradle
  subprojects/testing-jvm/src/integTest/resources/org/gradle/testing/junit/JUnitIntegrationTest/executesTestsInCorrectEnvironment/src/test/java/org/gradle/OkTest.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/DefaultDistributionModule.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/DistributionModule.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/TestFramework.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/detection/DefaultTestExecuter.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitTestFramework.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestFramework.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGTestFramework.java
Labels: @core

#22599 Merge release into master
  build-logic-commons/gradle-plugin/build.gradle.kts
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.cache-miss-monitor.gradle.kts
  build-logic/build-platform/build.gradle.kts
  released-versions.json
  settings.gradle.kts
  subprojects/base-services/src/main/java/org/gradle/api/JavaVersion.java
  subprojects/base-services/src/test/groovy/org/gradle/api/JavaVersionSpec.groovy
  subprojects/core/src/main/java/org/gradle/plugin/management/internal/autoapply/AutoAppliedGradleEnterprisePlugin.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/BuildScanPluginSmokeTest.groovy
Labels: @dev-productivity

#22595 Allow reseting test framework to same value after setting options
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/AbstractProperty.java
  subprojects/model-core/src/test/groovy/org/gradle/api/internal/provider/DefaultPropertyTest.groovy
  subprojects/model-core/src/testFixtures/groovy/org/gradle/api/internal/provider/AbstractPropertySpec.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestOptionsIntegrationSpec.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestTaskIntegrationTest.groovy
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java
Labels: in:testing, in:test-suites

#22581 Create TestFilterSpec
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/filter/DefaultTestFilter.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/filter/TestFilterSpec.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcher.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/processors/PatternMatchTestClassProcessor.java
  subprojects/testing-base/src/test/groovy/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcherTest.groovy
  subprojects/testing-junit-platform/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestClassProcessor.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junit/AbstractJUnitTestClassProcessor.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitSpec.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitTestClassExecutor.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitTestClassProcessor.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformSpec.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGSpec.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGTestClassProcessor.java
  subprojects/testing-jvm-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/junit/JUnitTestClassProcessorTest.groovy
  subprojects/testing-jvm-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/testng/TestNGTestClassProcessorTest.groovy
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitTestFramework.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestFramework.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGTestFramework.java
Labels: @core

#22558 Add plugins.portal.url.override parameter to promotion builds
  .teamcity/src/main/kotlin/common/extensions.kt
  .teamcity/src/main/kotlin/promotion/BasePublishGradleDistribution.kt
  .teamcity/src/main/kotlin/promotion/StartReleaseCycle.kt
  .teamcity/src/main/kotlin/promotion/StartReleaseCycleTest.kt
  .teamcity/src/test/kotlin/ApplyDefaultConfigurationTest.kt
  .teamcity/src/test/kotlin/PerformanceTestBuildTypeTest.kt
  .teamcity/src/test/kotlin/PromotionProjectTests.kt
Labels: @dev-productivity

#22594 Do not resolve output properties early
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/ResolvingValue.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/TaskExecution.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/DefaultTaskProperties.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/FileParameterUtils.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/OutputFilePropertySpec.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/OutputUnpacker.java
  subprojects/core/src/main/java/org/gradle/execution/plan/LocalTaskNode.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/DefaultDependenciesAccessors.java
  subprojects/execution/src/integTest/groovy/org/gradle/internal/execution/UnitOfWorkBuilder.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/UnitOfWork.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/impl/DefaultOutputSnapshotterTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CaptureStateAfterExecutionStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CleanupStaleOutputsStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CreateOutputsStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/RemovePreviousOutputsStepTest.groovy
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/AccessorsClassPath.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/PluginAccessorsClassPath.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/KotlinScriptEvaluator.kt
Labels: @execution

#19718 Remove flaky annotation for script compilation test
  subprojects/kotlin-dsl/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/BuildScriptCompileAvoidanceIntegrationTest.kt
Labels: flaky-fix-it

#22624 Use Temurin JDK as build JVM on Mac M1
  .teamcity/src/main/kotlin/common/Jvm.kt
  .teamcity/src/main/kotlin/model/CIBuildModel.kt
Labels: @dev-productivity

#22570 Remove classesDirs dependency on DefaultSourceSetOutput
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/DefaultConfigurableFileCollection.java
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/JavaPluginIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/internal/tasks/DefaultSourceSetOutput.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmPluginServices.java
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/jvm/internal/DefaultJvmPluginServicesTest.groovy
Labels: @core

#22640 Change the build so it works when the plugin portal redirects to maven central
  build-logic/settings.gradle.kts
  gradle/verification-metadata.xml
  settings.gradle.kts
Labels: @dev-productivity

#22597 Remove propertyWithDefaultValue method from hierarchy of all property based tests
  subprojects/file-collections/src/test/groovy/org/gradle/api/internal/file/DirectoryPropertyTest.groovy
  subprojects/file-collections/src/test/groovy/org/gradle/api/internal/file/FilePropertyTest.groovy
  subprojects/model-core/src/test/groovy/org/gradle/api/internal/provider/CollectionPropertySpec.groovy
  subprojects/model-core/src/test/groovy/org/gradle/api/internal/provider/DefaultListPropertyTest.groovy
  subprojects/model-core/src/test/groovy/org/gradle/api/internal/provider/DefaultPropertyTest.groovy
  subprojects/model-core/src/test/groovy/org/gradle/api/internal/provider/MapPropertySpec.groovy
  subprojects/model-core/src/testFixtures/groovy/org/gradle/api/internal/provider/PropertySpec.groovy
Labels: in:testing

#22648 Merge release into master
  build-logic/settings.gradle.kts
  released-versions.json
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCachePublishingIntegrationTest.groovy
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/tasks/PublishToMavenRepository.java
  subprojects/resources-s3/src/integTest/groovy/org/gradle/integtests/resource/s3/maven/MavenPublishS3IntegrationTest.groovy
  subprojects/resources-sftp/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishSftpIntegrationTest.groovy
Labels: @dev-productivity

#22652 Remove duplicated `jcenter` block
  build-logic/settings.gradle.kts
Labels: @dev-productivity

#22463 Add dependency verification changes for Gradle 8 to release notes
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/dependency_verification.adoc
Labels: @execution

#22666 Fix wrong build environment documentation on using -P for Gradle properties
  subprojects/docs/src/docs/userguide/running-builds/build_environment.adoc
Labels: a:bug, in:documentation

#22649 Exclude unnecessary expensive tests in FlakyTestQuarantine
  .teamcity/src/main/kotlin/configurations/FlakyTestQuarantine.kt
Labels: @dev-productivity

#22352 Avoid duplicate code in fork options validation
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompileExecutableUtils.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/internal/JavaExecExecutableUtils.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/javadoc/internal/JavadocExecutableUtils.java
  subprojects/language-java/src/test/groovy/org/gradle/api/tasks/JavaExecTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/tasks/compile/JavaCompileTest.groovy
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainQueryService.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/SpecificInstallationToolchainSpec.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/TestExecutableUtils.java
  subprojects/testing-jvm/src/test/groovy/org/gradle/api/tasks/testing/TestTest.groovy
Labels: in:toolchains, in:java-plugins

#22677 Verify TestNG parameters in worker
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGTestClassProcessor.java
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGFailurePolicyIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGGroupByInstancesNotSupportedIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGPreserveOrderNotSupportedIntegrationTest.groovy
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGTestFramework.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java
  subprojects/testing-jvm/src/test/groovy/org/gradle/api/internal/tasks/testing/testng/TestNGTestFrameworkTest.groovy
Labels: @core

#22616 Use withVariantReselection for test report aggregation
  subprojects/docs/src/docs/userguide/jvm/jacoco_report_aggregation_plugin.adoc
  subprojects/docs/src/docs/userguide/jvm/test_report_aggregation_plugin.adoc
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoAggregationIntegrationTest.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoPluginIntegrationTest.groovy
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoPlugin.java
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoReportAggregationPlugin.java
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/JvmTestSuitePluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/TestReportAggregationPluginIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JvmTestSuitePlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/TestReportAggregationPlugin.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/model/eclipse/ClasspathAttribute.java
Labels: @core

#22697 Polish `ScalaBasePlugin`
  subprojects/scala/src/main/java/org/gradle/api/plugins/scala/ScalaBasePlugin.java
Labels: a:chore, @configuration-cache

#22646 fix(file-collections): declare parameter as nullable; #22645
  subprojects/core-api/src/main/java/org/gradle/api/file/DirectoryProperty.java
  subprojects/core-api/src/main/java/org/gradle/api/file/RegularFileProperty.java
  subprojects/core-api/src/main/java/org/gradle/api/provider/ListProperty.java
  subprojects/core-api/src/main/java/org/gradle/api/provider/SetProperty.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/DefaultFilePropertyFactory.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/DefaultListProperty.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/DefaultProperty.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/DefaultSetProperty.java
Labels: from:contributor

#22689 Upgrade wrapper to latest nightly
  gradle/wrapper/gradle-wrapper.properties
  subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy
Labels: a:chore

#22713 Remove public ExternalPluginValidationPlugin
  build-logic-settings/build-logic-settings-plugin/src/main/kotlin/gradlebuild.base.allprojects.settings.gradle.kts
  settings.gradle.kts
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/plugins/ExternalPluginValidationPlugin.java
  subprojects/plugin-development/src/main/resources/META-INF/gradle-plugins/org.gradle.validate-external-gradle-plugin.properties
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractPluginValidatingSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildExternalPluginsValidationSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ProguardSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/WithPluginValidation.groovy
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/validate-external-gradle-plugin.gradle.kts
Labels: @execution

#19965 Use relative paths when comparing outputs
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskParametersIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/TaskExecution.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/OutputNormalizer.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/history/OutputsCleaner.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/history/changes/AbstractFingerprintCompareStrategy.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/history/changes/NormalizedPathChangeDetector.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/history/changes/NormalizedPathFingerprintCompareStrategy.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/history/changes/OutputFileChanges.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/history/impl/DefaultOverlappingOutputDetector.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/history/impl/OutputSnapshotUtil.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/history/changes/OutputFileChangesTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/history/impl/FileSystemSnapshotSerializerTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskUpToDateIntegrationTest.groovy
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SnapshotUtil.java
  subprojects/snapshots/src/testFixtures/groovy/org/gradle/internal/snapshot/TestSnapshotFixture.groovy
Labels: @execution

#22577 Retire additional deprecated worker api objects
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/architecture-test/src/changes/archunit_store/3c3e47be-b5ed-426a-8b9f-cfa00d3b09db
  subprojects/architecture-test/src/changes/archunit_store/provider-task-file-collection.txt
  subprojects/architecture-test/src/changes/archunit_store/provider-task-properties.txt
  subprojects/architecture-test/src/changes/archunit_store/provider-text-resource.txt
  subprojects/architecture-test/src/changes/archunit_store/public-api-mutable-file-collection.txt
  subprojects/architecture-test/src/changes/archunit_store/public-api-mutable-properties.txt
  subprojects/core/src/main/resources/org/gradle/initialization/removed-types.txt
  subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/GroovyCompilerFactory.java
  subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/daemon/DaemonGroovyCompiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/DaemonJavaCompiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/DefaultJavaCompilerFactory.java
  subprojects/language-jvm/src/main/java/org/gradle/api/internal/tasks/compile/daemon/AbstractDaemonCompiler.java
  subprojects/language-jvm/src/main/java/org/gradle/api/internal/tasks/compile/daemon/AbstractIsolatedCompilerWorkerExecutor.java
  subprojects/language-jvm/src/main/java/org/gradle/api/internal/tasks/compile/daemon/ClassloaderIsolatedCompilerWorkerExecutor.java
  subprojects/language-jvm/src/main/java/org/gradle/api/internal/tasks/compile/daemon/CompilerWorkerExecutor.java
  subprojects/language-jvm/src/main/java/org/gradle/api/internal/tasks/compile/daemon/ProcessIsolatedCompilerWorkerExecutor.java
  subprojects/scala/src/main/java/org/gradle/api/internal/tasks/scala/DaemonScalaCompiler.java
  subprojects/scala/src/main/java/org/gradle/api/internal/tasks/scala/ScalaCompilerFactory.java
  subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaCompile.java
  subprojects/workers/src/main/java/org/gradle/workers/ForkMode.java
  subprojects/workers/src/main/java/org/gradle/workers/IsolationMode.java
  subprojects/workers/src/main/java/org/gradle/workers/WorkerConfiguration.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/DefaultWorkerConfiguration.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/IsolatedClassloaderWorkerFactory.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/IsolationMode.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/NoIsolationWorkerFactory.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/WorkerDaemonFactory.java
  subprojects/workers/src/main/java/org/gradle/workers/internal/WorkerFactory.java
  subprojects/workers/src/test/groovy/org/gradle/workers/internal/DefaultWorkerConfigurationTest.groovy
  subprojects/workers/src/test/groovy/org/gradle/workers/internal/DefaultWorkerExecutorTest.groovy
Labels: a:chore, in:workers

#22717 Request vendor for build logic toolchain always
  build-logic-commons/gradle-plugin/src/main/kotlin/common.kt
Labels: @dev-productivity

#22721 Mark two flaky debug tests
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/CommandLineIntegrationSpec.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecDebugIntegrationTest.groovy
Labels: @dev-productivity

#22722 Mark timeout progress cross version tests as @Flaky.
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r40/ArtifactDownloadProgressCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r47/BuildProgressCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r51/ProjectConfigurationProgressEventCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r73/DependencyArtifactDownloadProgressEventCrossVersionTest.groovy
Labels: @dev-productivity

#22338 Add a test case for the BuildService as ValueSource input failure
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildServiceIntegrationTest.groovy
Labels: @configuration-cache

#22728 Allow disordered output for 'groovy_configurationCacheProjectAtExecut…
  subprojects/docs/src/snippets/configurationCache/projectAtExecution/tests/configurationCacheProjectAtExecution.sample.conf
Labels: flaky-fix-it

#22445 Track cross-project model access in `TaskExecutionGraph`
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/isolated/IsolatedProjectsAccessFromGroovyDslIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/CrossProjectConfigurationReportingGradle.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/CrossProjectConfigurationReportingTaskExecutionGraph.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/CrossProjectModelAccessTrackingClosure.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ProblemReportingCrossProjectModelAccess.kt
  subprojects/core/src/main/java/org/gradle/api/internal/project/CrossProjectModelAccess.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultCrossProjectModelAccess.java
  subprojects/core/src/main/java/org/gradle/execution/taskgraph/DefaultTaskExecutionGraph.java
  subprojects/core/src/main/java/org/gradle/execution/taskgraph/TaskExecutionGraphInternal.java
Labels: @configuration-cache

#21838 Isolated projects: track cross-project model access in inherited properties
  build-logic/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/isolated/IsolatedProjectsAccessFromGroovyDslIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/CrossProjectModelAccessTrackingParentDynamicObject.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultBuildModelControllerServices.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DynamicCallProblemReporting.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ProblemReportingCrossProjectModelAccess.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/TrackingDynamicLookupRoutine.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/JsonModelWriter.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ProblemDescription.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/PropertyProblem.kt
  subprojects/configuration-cache/src/test/kotlin/org/gradle/configurationcache/DefaultDynamicCallProblemReportingTest.kt
  subprojects/configuration-cache/src/test/kotlin/org/gradle/configurationcache/TrackingDynamicLookupRoutineTest.kt
  subprojects/core/src/main/java/org/gradle/api/internal/project/CrossProjectModelAccess.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultCrossProjectModelAccess.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultDynamicLookupRoutine.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProject.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/DynamicLookupRoutine.java
  subprojects/core/src/main/java/org/gradle/configuration/DefaultScriptPluginFactory.java
  subprojects/core/src/main/java/org/gradle/configuration/internal/DefaultDynamicCallContextTracker.java
  subprojects/core/src/main/java/org/gradle/configuration/internal/DynamicCallContextTracker.java
  subprojects/core/src/main/java/org/gradle/groovy/scripts/BasicScript.java
  subprojects/core/src/main/java/org/gradle/internal/session/CrossBuildSessionState.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/DefaultProjectSpec.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/DefaultProjectTest.groovy
  subprojects/core/src/test/groovy/org/gradle/configuration/internal/DefaultDynamicCallContextTrackerTest.groovy
  subprojects/core/src/test/groovy/org/gradle/groovy/scripts/DefaultScriptTest.groovy
Labels: @configuration-cache

#22742 Warmup BuildSourceBuilderIntegrationTest to avoid buildSrc lock timeout
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/BuildSourceBuilderIntegrationTest.groovy
Labels: @dev-productivity, flaky-fix-it

#22730 Fix additional sample tests
  subprojects/docs/src/snippets/java-library/module-disabled/tests/buildJavaModule.sample.conf
  subprojects/docs/src/snippets/tasks/addRules/tests/taskRuleDependsOn.sample.conf
Labels: flaky-fix-it

#22763 Cherry-pick dev-prod changes from master
  .teamcity/src/main/kotlin/configurations/FlakyTestQuarantine.kt
  .teamcity/src/main/kotlin/model/FunctionalTestBucketProvider.kt
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/BuildSourceBuilderIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/CommandLineIntegrationSpec.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecDebugIntegrationTest.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r40/ArtifactDownloadProgressCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r47/BuildProgressCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r51/ProjectConfigurationProgressEventCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r73/DependencyArtifactDownloadProgressEventCrossVersionTest.groovy
Labels: @dev-productivity

#22676 Move docs test out of functional test buckets
  .teamcity/pom.xml
  .teamcity/settings.kts
  .teamcity/src/main/kotlin/configurations/ConfigCacheDocsTest.kt
  .teamcity/src/main/kotlin/configurations/DocsTest.kt
  .teamcity/src/main/kotlin/configurations/StagePasses.kt
  .teamcity/src/main/kotlin/model/CIBuildModel.kt
  .teamcity/src/main/kotlin/model/FunctionalTestBucketGenerator.kt
  .teamcity/src/main/kotlin/model/FunctionalTestBucketProvider.kt
  .teamcity/src/main/kotlin/model/GradleSubprojectProvider.kt
  .teamcity/src/main/kotlin/model/bucket-extensions.kt
  .teamcity/src/main/kotlin/projects/StageProject.kt
  .teamcity/src/test/kotlin/CIConfigIntegrationTests.kt
  .teamcity/subprojects.json
  .teamcity/test-buckets.json
  build-logic/build-update-utils/src/main/kotlin/gradlebuild/buildutils/tasks/SubprojectsInfo.kt
  subprojects/docs/build.gradle
  subprojects/docs/src/integTest/placeholder
Labels: @dev-productivity

#22755 Split external process instrumentation tests again
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/AbstractConfigurationCacheExternalProcessInstrumentationInDynamicGroovyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/AbstractProcessIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/ProcessInBuildScriptIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/ProcessInInitScriptIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/ProcessInPluginBuildScriptIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/ProcessInPluginIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/ProcessInTaskIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/AbstractProcessInstrumentationInDynamicGroovyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/AbstractProcessInstrumentationIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/DynamicGroovyPluginMixin.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/Execute1InstanceInstrumentationInDynamicGroovyWithIndyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/Execute1InstanceInstrumentationInDynamicGroovyWithoutIndyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/Execute1QualifiedStaticInstrumentationInDynamicGroovyWithIndyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/Execute1QualifiedStaticInstrumentationInDynamicGroovyWithoutIndyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/Execute1StaticInstrumentationInDynamicGroovyWithIndyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/Execute1StaticInstrumentationInDynamicGroovyWithoutIndyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/Execute3InstanceInstrumentationInDynamicGroovyWithIndyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/Execute3InstanceInstrumentationInDynamicGroovyWithoutIndyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/Execute3QualifiedStaticInstrumentationInDynamicGroovyWithIndyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/Execute3QualifiedStaticInstrumentationInDynamicGroovyWithoutIndyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/Execute3StaticInstrumentationInDynamicGroovyWithIndyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/Execute3StaticInstrumentationInDynamicGroovyWithoutIndyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/ProcessBuilderInstrumentationInDynamicGroovyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/ProcessInstrumentationInJavaIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/ProcessInstrumentationInKotlinIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/ProcessInstrumentationInStaticGroovyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/RuntimeExec1InstrumentationInDynamicGroovyWithIndyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/RuntimeExec1InstrumentationInDynamicGroovyWithoutIndyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/RuntimeExec2InstrumentationInDynamicGroovyWithIndyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/RuntimeExec2InstrumentationInDynamicGroovyWithoutIndyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/RuntimeExec3InstrumentationInDynamicGroovyWithIndyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/RuntimeExec3InstrumentationInDynamicGroovyWithoutIndyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/UnrelatedMethodInstrumentationInDynamicGroovyIntegrationTest.groovy
Labels: flaky-fix-it

#22489 Show all deprecation instances (#16688)
  subprojects/logging/src/integTest/groovy/org/gradle/DeprecationHandlingIntegrationTest.groovy
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/LoggingDeprecatedFeatureHandler.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ArtifactoryAndDockerSmokeTest.groovy
Labels: from:contributor

#22726 Upgradle to latest nightly for relative output changes
  .teamcity/src/main/kotlin/common/performance-test-extensions.kt
  .teamcity/src/main/kotlin/util/AdHocPerformanceScenario.kt
  build-logic/build-init-samples/src/main/kotlin/gradlebuild/generate-samples.gradle.kts
  build-logic/build-init-samples/src/main/kotlin/gradlebuild/samples/SamplesGenerator.kt
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: @dev-productivity

#22778 Add Upgrade Note for Strongly Typed Dependencies in Test Suites
  subprojects/docs/src/docs/userguide/jvm/jvm_test_suite_plugin.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
Labels: in:documentation

#22745 Add further debug info to flaky test output
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractContinuousIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/timeout/JavaProcessStackTracesMonitor.java
Labels: flaky-fix-it

#22785 Merge release into master
  released-versions.json
  subprojects/core/src/integTest/groovy/org/gradle/api/FinalizerTaskIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/execution/plan/FinalizerGroup.java
  subprojects/docs/src/docs/userguide/jvm/jvm_test_suite_plugin.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
Labels: @dev-productivity

#22783 Fix Kotlin DSL plugins block interpreter for plugin requests split on multiple lines
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/execution/PluginsBlockInterpreter.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/execution/PluginsBlockInterpreterTest.kt
Labels: in:kotlin-dsl

#22770 Improve error message when probing toolchain installation fails
  subprojects/core/src/testFixtures/groovy/org/gradle/test/fixtures/AbstractProjectBuilderSpec.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/tasks/JavaExecTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/tasks/compile/JavaCompileTest.groovy
  subprojects/platform-jvm/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainDownloadSpiAuthenticationIntegrationTest.groovy
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainFactory.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainInstantiationResult.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainQueryService.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/install/JdkCacheDirectory.java
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/toolchain/internal/JavaToolchainQueryServiceTest.groovy
  subprojects/testing-jvm/src/test/groovy/org/gradle/api/tasks/testing/TestTest.groovy
Labels: in:toolchains

#22790 Visit nested properties directly while discovering properties
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/AbstractTaskFilePropertyRegistration.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskInputFilePropertyRegistration.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskInputPropertyRegistration.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskInputs.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskOutputFilePropertyRegistration.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskOutputs.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/ResolvingValue.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskPropertyRegistration.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/DefaultTaskProperties.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/AbstractOutputPropertyAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/DestroysPropertyAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/LocalStatePropertyAnnotationHandler.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformationRegistrationFactory.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/model/annotations/AbstractInputFilePropertyAnnotationHandler.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/model/annotations/InputPropertyAnnotationHandler.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/model/annotations/ServiceReferencePropertyAnnotationHandler.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/validation/ValidationProblemPropertyAnnotationHandler.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/StaticValue.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/annotations/NestedBeanAnnotationHandler.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/annotations/NoOpPropertyAnnotationHandler.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/annotations/PropertyAnnotationHandler.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/bean/AbstractNestedRuntimeBeanNode.java
  subprojects/model-core/src/test/groovy/org/gradle/internal/properties/StaticValueTest.groovy
  subprojects/model-core/src/test/groovy/org/gradle/internal/properties/annotations/NestedBeanAnnotationHandlerTest.groovy
Labels: @execution

#22808 Use Java BiFunction instead of custom type
  subprojects/base-services/src/main/java/org/gradle/internal/util/BiFunction.java
  subprojects/model-core/src/test/groovy/org/gradle/internal/instantiation/generator/AsmBackedClassGeneratorDecoratedTest.groovy
Labels: @execution

#22810 Rebaseline performance test
  gradle.properties
Labels: @dev-productivity

#22759 Followup after moving task property exploration around
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/TaskNodeCodec.kt
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/project/taskfactory/TaskPropertyNamingIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskInputFilePropertyRegistration.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskInputs.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/SnapshotTaskInputsBuildOperationResult.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskInputFilePropertyBuilderInternal.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskInputFilePropertyRegistration.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/AbstractFilePropertySpec.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/CompositePropertyVisitor.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/DefaultInputFilePropertySpec.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/DefaultTaskProperties.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/FileParameterUtils.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/FilePropertySpec.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/GetInputFilesVisitor.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/InspectionSchemeFactory.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/ScriptSourceAwareImplementationIdentifier.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/ScriptSourceAwareImplementationResolver.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/classpath/impl/DefaultClasspathFingerprinter.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/classpath/impl/DefaultCompileClasspathFingerprinter.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/AbsolutePathFileCollectionFingerprinter.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/IgnoredPathFileCollectionFingerprinter.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/NameOnlyFileCollectionFingerprinter.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/RelativePathFileCollectionFingerprinter.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/taskfactory/AnnotationProcessingTaskFactoryTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/AbstractTaskInputsAndOutputsTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/DefaultTaskInputsTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/SnapshotTaskInputsBuildOperationResultTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/ScriptSourceAwareImplementationResolverTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/api/internal/tasks/properties/bean/TestImplementationResolver.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformationRegistrationFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/Transformer.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactoryTest.groovy
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/test/impl/DefaultTestTaskPropertiesService.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/FileCollectionFingerprinter.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/FileNormalizationSpec.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/UnitOfWork.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/impl/DefaultFileNormalizationSpec.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/model/InputNormalizer.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/model/OutputNormalizer.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/model/annotations/AbstractInputFilePropertyAnnotationHandler.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/impl/DefaultInputFingerprinterTest.groovy
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/normalization/KotlinCompileClasspathFingerprinter.kt
  subprojects/model-core/src/main/java/org/gradle/internal/properties/PropertyVisitor.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/bean/DefaultPropertyWalker.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/bean/ImplementationResolver.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/bean/RuntimeBeanNodeFactory.java
  subprojects/model-core/src/main/java/org/gradle/util/internal/ConfigureUtil.java
  subprojects/model-core/src/test/groovy/org/gradle/internal/properties/bean/DefaultPropertyWalkerTest.groovy
  subprojects/model-core/src/test/groovy/org/gradle/util/ConfigureUtilTest.groovy
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/FileNormalizer.java
Labels: @execution

#22605 Move SourceSet to :platform-jvm
  build-logic-commons/code-quality-rules/src/main/resources/checkstyle/suppressions.xml
  subprojects/antlr/build.gradle.kts
  subprojects/configuration-cache/build.gradle.kts
  subprojects/core/build.gradle.kts
  subprojects/ivy/build.gradle.kts
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publication/DefaultIvyPublication.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/plugins/IvyPublishPlugin.java
  subprojects/ivy/src/test/groovy/org/gradle/api/publish/ivy/internal/artifact/IvyArtifactNotationParserFactoryTest.groovy
  subprojects/jacoco/build.gradle.kts
  subprojects/kotlin-dsl-plugins/build.gradle.kts
  subprojects/kotlin-dsl-plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/embedded/EmbeddedKotlinPlugin.kt
  subprojects/kotlin-dsl-provider-plugins/build.gradle.kts
  subprojects/kotlin-dsl/build.gradle.kts
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/ProjectExtensionsTest.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/accessors/ProjectAccessorsClassPathTest.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/accessors/tasks/PrintAccessorsTest.kt
  subprojects/kotlin-dsl/src/test/resources/org/gradle/kotlin/dsl/accessors/tasks/PrintAccessors-expected-output.txt
  subprojects/maven/build.gradle.kts
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/DefaultMavenPublication.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/plugins/MavenPublishPlugin.java
  subprojects/maven/src/test/groovy/org/gradle/api/publish/maven/internal/artifact/MavenArtifactNotationParserFactoryTest.groovy
  subprojects/platform-jvm/src/main/java/org/gradle/api/internal/jvm/ClassDirectoryBinaryNamingScheme.java
  subprojects/platform-jvm/src/main/java/org/gradle/api/internal/tasks/DefaultSourceSet.java
  subprojects/platform-jvm/src/main/java/org/gradle/api/internal/tasks/DefaultSourceSetContainer.java
  subprojects/platform-jvm/src/main/java/org/gradle/api/internal/tasks/DefaultSourceSetOutput.java
  subprojects/platform-jvm/src/main/java/org/gradle/api/internal/tasks/JvmConstants.java
  subprojects/platform-jvm/src/main/java/org/gradle/api/tasks/SourceSet.java
  subprojects/platform-jvm/src/main/java/org/gradle/api/tasks/SourceSetContainer.java
  subprojects/platform-jvm/src/main/java/org/gradle/api/tasks/SourceSetOutput.java
  subprojects/platform-jvm/src/test/groovy/org/gradle/api/internal/jvm/ClassDirectoryBinaryNamingSchemeTest.groovy
  subprojects/platform-jvm/src/test/groovy/org/gradle/api/internal/tasks/DefaultSourceSetContainerTest.groovy
  subprojects/platform-jvm/src/test/groovy/org/gradle/api/internal/tasks/DefaultSourceSetTest.groovy
  subprojects/plugins/build.gradle.kts
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlatformPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/PublicationInternal.java
Labels: @core

#22811 Re-enable @Flaky for JavaExecDebugIntegrationTest
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecDebugIntegrationTest.groovy
Labels: @dev-productivity

#22813 Fix flaky DeprecationHandlingIntegrationTest
  subprojects/logging/src/integTest/groovy/org/gradle/DeprecationHandlingIntegrationTest.groovy
Labels: @dev-productivity

#22806 De-Incubate Settings methods
  subprojects/core-api/src/main/java/org/gradle/api/initialization/Settings.java
  subprojects/core-api/src/main/java/org/gradle/api/initialization/resolve/DependencyResolutionManagement.java
  subprojects/core-api/src/main/java/org/gradle/api/initialization/resolve/RulesMode.java
  subprojects/docs/src/docs/release/notes.md
Labels: a:chore

#22829 Add --stacktrace to perf tests
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/CrossVersionPerformanceTestRunner.groovy
Labels: @dev-productivity

#22842 Upgrade springBootApp to use latest spring boot plugin
  build-logic/performance-testing/src/main/groovy/gradlebuild.performance-templates.gradle
Labels: @dev-productivity

#22844 Use partial stack traces as key to identify deprecation messages
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/LoggingDeprecatedFeatureHandler.java
Labels: @dev-productivity

#22851 Capture exceptions thrown in JavaProcessStackTracesMonitor
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/timeout/JavaProcessStackTracesMonitor.java
Labels: @dev-productivity

#22855 Try adaptive maxParallelForks
  .teamcity/src/main/kotlin/common/extensions.kt
  .teamcity/src/main/kotlin/configurations/FunctionalTest.kt
  .teamcity/src/main/kotlin/configurations/GradleBuildConfigurationDefaults.kt
  .teamcity/src/main/kotlin/model/CIBuildModel.kt
  build-logic/basics/src/main/kotlin/gradlebuild/basics/BuildParams.kt
Labels: @dev-productivity

#22835 Make launcher non-optional for GroovyCompile
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/language-groovy/src/integTest/groovy/org/gradle/language/groovy/GroovyCompileJavaVersionTrackingIntegrationTest.groovy
  subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/GroovyCompilerFactory.java
  subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java
  subprojects/language-groovy/src/test/groovy/org/gradle/api/tasks/compile/GroovyCompileTest.groovy
  subprojects/language-groovy/src/testFixtures/groovy/org/gradle/testing/fixture/GroovyCoverage.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/groovy/GroovyCrossCompilationIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/groovy/compile/GroovyCompileOldJavaTargetIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/groovy/compile/GroovyCompileToolchainIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/GroovyBasePlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaBasePlugin.java
Labels: in:toolchains

#22873 Introduce TypeMetadataWalker and use it in PropertyValidationAccess
  subprojects/core/build.gradle.kts
  subprojects/model-core/src/main/java/org/gradle/internal/properties/annotations/AbstractTypeMetadataWalker.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/annotations/DefaultTypeMetadataStore.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/annotations/TypeMetadataWalker.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/bean/AbstractNestedRuntimeBeanNode.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/bean/AbstractPropertyNode.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/bean/IterableRuntimeBeanNode.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/bean/MapRuntimeBeanNode.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/bean/NestedRuntimeBeanNode.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/bean/RuntimeBeanNode.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/bean/RuntimeBeanNodeFactory.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/annotations/PropertyAnnotationMetadata.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/annotations/impl/DefaultPropertyAnnotationMetadata.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/annotations/impl/DefaultTypeAnnotationMetadataStore.java
  subprojects/model-core/src/test/groovy/org/gradle/internal/properties/annotations/AbstractTypeMetadataWalkerTest.groovy
  subprojects/model-core/src/test/groovy/org/gradle/internal/reflect/annotations/impl/DefaultTypeAnnotationMetadataStoreTest.groovy
  subprojects/model-core/src/testFixtures/groovy/org/gradle/internal/reflect/annotations/TestAnnotationHandlingSupport.groovy
  subprojects/persistent-cache/src/testFixtures/groovy/org/gradle/cache/internal/TestCrossBuildInMemoryCacheFactory.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidatePluginsIntegrationTest.groovy
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/internal/PropertyValidationAccess.java
Labels: @execution

#22878 Add detection of broken Javadoc paths to the FindBrokenInternalLinks task
  build-logic/documentation/build.gradle.kts
  build-logic/documentation/src/main/groovy/gradlebuild/docs/FindBrokenInternalLinks.java
  build-logic/documentation/src/main/groovy/gradlebuild/docs/GradleUserManualPlugin.java
  build-logic/documentation/src/test/groovy/gradlebuild/docs/FindBrokenInternalLinksTest.groovy
  subprojects/docs/src/docs/userguide/authoring-builds/more_about_tasks.adoc
  subprojects/docs/src/docs/userguide/build-cache/build_cache.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_5.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/docs/userguide/troubleshooting/validation_problems.adoc
Labels: in:documentation-infrastructure, in:building-gradle

#22883 Recreate "build identified" and "project identified" events when loading from configuration cache
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultIncludedBuild.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultNestedBuild.java
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOperationsIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildTreeStructureIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/CachedBuildState.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/CachedProjectState.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheBuild.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheHost.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheIO.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultConfigurationCache.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/RelevantProjectsRegistry.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/VintageGradleBuild.kt
  subprojects/configuration-cache/src/test/kotlin/org/gradle/configurationcache/FillTheProjectGapsTest.kt
  subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProjectStateRegistry.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/ProjectLifecycleController.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/ProjectState.java
  subprojects/core/src/main/java/org/gradle/initialization/SettingsLocation.java
  subprojects/core/src/main/java/org/gradle/internal/build/NestedBuildState.java
  subprojects/core/src/main/java/org/gradle/internal/model/StateTransitionController.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/BuildScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/SettingsScopeServices.java
  subprojects/core/src/main/java/org/gradle/testfixtures/internal/TestBuildScopeServices.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationIntegrityCheckIntegTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/WellBehavedPluginTest.groovy
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/internal/NativeDependentBinariesResolutionStrategy.java
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/plugins/NativeComponentModelPlugin.java
Labels: in:configuration-cache

#22895 Remove BuildCompletionListener
  subprojects/core/src/main/java/org/gradle/initialization/BuildCompletionListener.java
Labels: a:chore

#22756 Make GUH cleanup frequency configurable via dsl
  subprojects/build-cache/src/integTest/groovy/org/gradle/caching/local/internal/DirectoryBuildCacheCleanupIntegrationTest.groovy
  subprojects/build-cache/src/main/java/org/gradle/caching/local/internal/DirectoryBuildCacheServiceFactory.java
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheRepository.kt
  subprojects/core-api/src/main/java/org/gradle/api/cache/CacheConfigurations.java
  subprojects/core-api/src/main/java/org/gradle/api/cache/CacheResourceConfiguration.java
  subprojects/core-api/src/main/java/org/gradle/api/cache/Cleanup.java
  subprojects/core-api/src/main/java/org/gradle/api/internal/cache/CacheConfigurationsInternal.java
  subprojects/core-api/src/main/java/org/gradle/api/internal/cache/CleanupInternal.java
  subprojects/core-api/src/main/java/org/gradle/api/internal/cache/DefaultCacheCleanup.java
  subprojects/core-api/src/main/java/org/gradle/api/internal/cache/DefaultCleanup.java
  subprojects/core-api/src/main/java/org/gradle/internal/cache/MonitoredCleanupAction.java
  subprojects/core-api/src/main/java/org/gradle/internal/cache/MonitoredCleanupActionDecorator.java
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/cache/CacheConfigurationsIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/cache/DefaultCacheConfigurations.java
  subprojects/core/src/main/java/org/gradle/cache/internal/GradleUserHomeCacheCleanupActionDecorator.java
  subprojects/core/src/main/java/org/gradle/cache/internal/GradleUserHomeCleanupService.java
  subprojects/core/src/main/java/org/gradle/cache/internal/GradleUserHomeCleanupServices.java
  subprojects/core/src/main/java/org/gradle/cache/internal/VersionSpecificCacheCleanupAction.java
  subprojects/core/src/main/java/org/gradle/cache/internal/WrapperDistributionCleanupAction.java
  subprojects/core/src/main/java/org/gradle/initialization/layout/ProjectCacheDir.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/DefaultClasspathTransformerCacheFactory.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GradleUserHomeScopeServices.java
  subprojects/core/src/main/java/org/gradle/testfixtures/internal/TestInMemoryCacheFactory.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/cache/DefaultCacheConfigurationsTest.groovy
  subprojects/core/src/test/groovy/org/gradle/cache/internal/GradleUserHomeCacheCleanupActionDecoratorTest.groovy
  subprojects/core/src/test/groovy/org/gradle/cache/internal/GradleUserHomeCleanupServiceTest.groovy
  subprojects/core/src/test/groovy/org/gradle/cache/internal/VersionSpecificCacheCleanupActionTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/classpath/DefaultCachedClasspathTransformerTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/cache/internal/GradleUserHomeCleanupFixture.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/caching/DefaultArtifactCacheLockingManagerIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementGradleUserHomeScopeServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/DefaultArtifactCaches.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/WritableArtifactCacheLockingManager.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/ImmutableTransformationWorkspaceServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/DependenciesAccessorsWorkspaceProvider.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/DefaultArtifactCacheLockingManagerTest.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/workspace/impl/DefaultImmutableWorkspaceProvider.java
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/cache/GradleUserHomeServices.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/cache/KotlinDslWorkspaceProvider.kt
  subprojects/persistent-cache/src/main/java/org/gradle/cache/CacheBuilder.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/CacheCleanup.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/CleanupFrequency.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/CacheFactory.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/DefaultCacheFactory.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/DefaultCacheRepository.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/DefaultPersistentDirectoryCache.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/DefaultPersistentDirectoryStore.java
  subprojects/persistent-cache/src/test/groovy/org/gradle/cache/internal/DefaultPersistentDirectoryCacheTest.groovy
  subprojects/persistent-cache/src/test/groovy/org/gradle/cache/internal/DefaultPersistentDirectoryStoreTest.groovy
  subprojects/version-control/src/main/java/org/gradle/vcs/internal/services/DefaultVersionControlRepositoryFactory.java
Labels: a:feature

#22898 Fix potential `AssertionError` when a task in an included build is a dependency of multiple finalizer tasks
  subprojects/core/src/main/java/org/gradle/execution/plan/DetermineExecutionPlanAction.java
  subprojects/core/src/test/groovy/org/gradle/execution/plan/DefaultExecutionPlanTest.groovy
Labels: in:scheduler

#22902 Add missing `@UsesNativeServices`
  subprojects/testing-native/src/test/groovy/org/gradle/nativeplatform/test/cpp/internal/DefaultCppTestSuiteTest.groovy
  subprojects/testing-native/src/test/groovy/org/gradle/nativeplatform/test/cunit/CUnitTest.groovy
  subprojects/testing-native/src/test/groovy/org/gradle/nativeplatform/test/internal/DefaultNativeTestSuiteBinarySpecTest.groovy
  subprojects/testing-native/src/test/groovy/org/gradle/nativeplatform/test/plugins/NativeTestingBasePluginTest.groovy
  subprojects/testing-native/src/test/groovy/org/gradle/nativeplatform/test/xctest/internal/DefaultSwiftXCTestSuiteTest.groovy
  subprojects/testing-native/src/test/groovy/org/gradle/nativeplatform/test/xctest/plugins/XCTestConventionPluginTest.groovy
Labels: @dev-productivity

#22861 Removing incubating on a number of methods and types
  subprojects/build-events/src/main/java/org/gradle/build/event/BuildEventsListenerRegistry.java
  subprojects/core-api/src/main/java/org/gradle/api/Task.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/BuildController.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/events/OperationType.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/events/download/FileDownloadFinishEvent.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/events/download/FileDownloadOperationDescriptor.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/events/download/FileDownloadProgressEvent.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/events/download/FileDownloadResult.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/events/download/FileDownloadStartEvent.java
Labels: a:chore

#22894 Update nebula plugins versions for smoke tests
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/BomSupportPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/NebulaPluginsSmokeTest.groovy
Labels: a:chore

#22802 Consider all variants when finding artifact transform chains
  subprojects/base-services/src/main/java/org/gradle/internal/collections/ImmutableFilteredList.java
  subprojects/base-services/src/test/groovy/org/gradle/internal/collections/ImmutableFilteredListTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/LocalFileDependencyBackedArtifactSetCodec.kt
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/DisambiguateArtifactTransformIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ArtifactTransformRegistration.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/AmbiguousTransformException.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/AttributeMatchingVariantSelector.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/ConsumerProvidedVariantFinder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/ConsumerVariantMatchResult.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformationRegistrationFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformedVariantFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultVariantDefinition.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/ImmutableConsumerVariantMatchResult.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/MutableConsumerVariantMatchResult.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/NoMatchConsumerVariantMatchResult.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/SingleMatchConsumerVariantMatchResult.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformedVariant.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/VariantDefinition.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/AmbiguousVariantSelectionException.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/AttributeMatchingVariantSelectorSpec.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/ConsumerProvidedVariantFinderTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/DefaultArtifactTransformsTest.groovy
Labels: @core

#22245 Upgrade embedded Kotlin to 1.7.22
  build-logic-commons/gradle-plugin/build.gradle.kts
  build-logic/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
  build-logic/kotlin-dsl/src/main/kotlin/gradlebuild.kotlin-dsl-dependencies-embedded.gradle.kts
  gradle/verification-metadata.xml
  gradle/wrapper/gradle-wrapper.properties
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/library-versions.properties
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/AllDistributionIntegrationSpec.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/BinDistributionIntegrationSpec.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DistributionIntegritySpec.groovy
  subprojects/docs/src/docs/userguide/compatibility.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/samples/build-organization/structuring-software-projects/groovy/platforms/plugins-platform/build.gradle
  subprojects/docs/src/samples/build-organization/structuring-software-projects/kotlin/platforms/plugins-platform/build.gradle.kts
  subprojects/docs/src/snippets/configurationCache/samConversion/groovy/build.gradle
  subprojects/docs/src/snippets/configurationCache/samConversion/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/androidBuild/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/androidSingleBuild/kotlin/build.gradle.kts
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/NestedInputKotlinImplementationTrackingIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/KotlinGradlePluginVersions.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoKotlinJvmPluginAggregationTest.groovy
  subprojects/kotlin-dsl-plugins/build.gradle.kts
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/codegen/GradleApiExtensionsTest.kt
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
Labels: a:chore, in:kotlin-dsl
