Repository gradle/gradle, pull requests merged in 2022-12, with the labels that each got.

#22923 Fix some edge cases for artifact transforms loaded from the configuration cache
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/LocalFileDependencyBackedArtifactSetCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/transform/CalculateArtifactsCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/transform/TransformedArtifactCodec.kt
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalInputsIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ExtraAttributeDisambiguationIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultResolvableArtifact.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/PreResolvedResolvableArtifact.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/ResolvableArtifact.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/TestArtifactSet.java
Labels: in:configuration-cache

#22924 Upgrade wrapper to the latest nightly
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore, in:building-gradle

#22926 Rebaseline to latest commit
  gradle.properties
Labels: @dev-productivity

#22890 Task dependencies access becomes an error in 8.0 with STABLE_CONFIGURATION_CACHE
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultBuildModelControllerServices.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/StableConfigurationCacheUnsupportedApiManagerAction.kt
  subprojects/core/src/integTest/groovy/org/gradle/api/events/BuildExecutionEventsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/services/BuildServiceIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/services/internal/BuildServiceProviderNagger.java
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskActionIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestEventsIntegrationTest.groovy
Labels: a:chore, in:configuration-cache, in:build-services

#22912 Update test-retry plugin to 1.5.0
  build-logic/build-platform/build.gradle.kts
  gradle/verification-metadata.xml
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/JvmTestExecutionSpec.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestFramework.java
Labels: @core

#22941 Fix some tests to make them configuration cache compatible
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildDeclaredSubstitutionsIntegrationTest.groovy
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildDependencyCapabilitiesResolveIntegrationTest.groovy
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildDependencyCycleIntegrationTest.groovy
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildDependencyGraphIntegrationTest.groovy
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildMinimalConfigurationIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/DependencySubstitutionRulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ProjectDependencyResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/RepositoriesDeclaredInSettingsIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/VariantsDependencySubstitutionRulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/alignment/ForcingPlatformAlignmentTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/TomlDependenciesExtensionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/VersionCatalogExtensionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/constraints/DependencyConstraintsIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ivy/IvyModuleResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenScopesAndProjectDependencySubstitutionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/platforms/EnforcedPlatformIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/DependencyResolveRulesDisableGlobalDependencySubstitutionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/DependencyResolveRulesPreferProjectModulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/strict/StrictVersionConstraintsIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/AbstractExternalDependencyFactory.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/resolve/ResolveTestFixture.groovy
  subprojects/version-control/src/integTest/groovy/org/gradle/vcs/internal/GitVersionSelectionIntegrationTest.groovy
Labels: in:configuration-cache

#22798 Allow cache cleanup to occur at the end of the build session
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/core-api/src/main/java/org/gradle/api/cache/Cleanup.java
  subprojects/core-api/src/main/java/org/gradle/api/internal/cache/CacheConfigurationsInternal.java
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/cache/CacheConfigurationsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/cache/internal/GradleUserHomeCleanupServiceIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/cache/DefaultCacheConfigurations.java
  subprojects/core/src/main/java/org/gradle/cache/internal/GradleUserHomeCleanupService.java
  subprojects/core/src/main/java/org/gradle/cache/internal/GradleUserHomeCleanupServices.java
  subprojects/core/src/main/java/org/gradle/cache/internal/VersionSpecificCacheCleanupAction.java
  subprojects/core/src/main/java/org/gradle/testfixtures/internal/TestInMemoryCacheFactory.java
  subprojects/core/src/test/groovy/org/gradle/cache/internal/GradleUserHomeCleanupServiceTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/cache/internal/GradleUserHomeCleanupFixture.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/caching/DefaultArtifactCacheLockingManagerIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
  subprojects/persistent-cache/src/main/java/org/gradle/cache/CleanupFrequency.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/HasCleanupAction.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/PersistentCache.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/CacheCoordinator.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/CacheFactory.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/CacheVisitor.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/DefaultCacheAccess.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/DefaultCacheFactory.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/DefaultFileLockManager.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/DefaultPersistentDirectoryStore.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/UnusedVersionsCacheCleanup.java
  subprojects/persistent-cache/src/test/groovy/org/gradle/cache/internal/DefaultCacheAccessTest.groovy
  subprojects/persistent-cache/src/test/groovy/org/gradle/cache/internal/DefaultCacheFactoryTest.groovy
Labels: a:feature

#22919 Follow-up for attribute transform work
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/AttributeMatchingVariantSelector.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/ConsumerProvidedVariantFinder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformedVariant.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/DefaultArtifactTransformsTest.groovy
Labels: @core

#22703 Fix ordering for welcome and logging.stacktrace props
  subprojects/docs/src/docs/userguide/running-builds/build_environment.adoc
Labels: from:contributor

#22948 Mark a flaky DependencyArtifactDownloadProgressEventCrossVersionTest
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r73/DependencyArtifactDownloadProgressEventCrossVersionTest.groovy
Labels: @dev-productivity

#22916 Misc deprecation removals
  subprojects/logging/src/main/java/org/gradle/util/TextUtil.java
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/AbstractPluginValidationIntegrationSpec.groovy
Labels: a:chore

#21910 Support Kotlin language/api 1.7 in Kotlin DSL build scripts and plugins
  .teamcity/subprojects.json
  build-logic/kotlin-dsl/src/main/kotlin/gradlebuild.kotlin-dsl-dependencies-embedded.gradle.kts
  gradle/verification-metadata.xml
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/kotlin-dsl-integ-tests/build.gradle.kts
  subprojects/kotlin-dsl-integ-tests/src/crossVersionTest/groovy/org/gradle/kotlin/dsl/plugins/PrecompiledKotlinPluginCrossVersionSpec.groovy
  subprojects/kotlin-dsl-plugins/build.gradle.kts
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginCrossVersionSmokeTest.kt
  subprojects/kotlin-dsl-plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslCompilerPlugins.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinBuildScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinInitScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinSettingsScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/precompile/v1/PrecompiledScriptTemplates.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/KotlinDslPluginSupport.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/KotlinCompiler.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/codegen/GradleApiExtensionsTest.kt
Labels: a:feature, in:kotlin-dsl

#22956 Update wrapper to latest nightly with Kotlin API level 1.7
  build-logic-commons/gradle-plugin/build.gradle.kts
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.code-quality.gradle.kts
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild/StringExtensions.kt
  build-logic/basics/src/main/kotlin/gradlebuild/basics/BuildEnvironment.kt
  build-logic/binary-compatibility/src/main/kotlin/gradlebuild/binarycompatibility/sources/KotlinSourceQueries.kt
  build-logic/build-init-samples/src/main/kotlin/gradlebuild/samples/SamplesGenerator.kt
  build-logic/build-update-utils/src/main/kotlin/gradlebuild.wrapper.gradle.kts
  build-logic/buildquality/src/main/kotlin/gradlebuild.incubation-report-aggregation.gradle.kts
  build-logic/buildquality/src/main/kotlin/gradlebuild.incubation-report.gradle.kts
  build-logic/integration-testing/src/main/kotlin/gradlebuild.cross-version-tests.gradle.kts
  build-logic/integration-testing/src/main/kotlin/gradlebuild/integrationtests/shared-configuration.kt
  build-logic/packaging/src/main/kotlin/gradlebuild.shaded-jar.gradle.kts
  build-logic/performance-testing/src/main/kotlin/gradlebuild/performance/PerformanceTestPlugin.kt
  build-logic/publishing/src/main/kotlin/gradlebuild.kotlin-dsl-plugin-bundle.gradle.kts
  gradle/verification-metadata.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore, in:building-gradle, in:kotlin-dsl

#22958 Fix some tests to make them configuration cache compatible
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/DependencySubstitutionRulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/FlatDirJvmLibraryArtifactResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/JvmLibraryArtifactResolveTestFixture.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/MultiProjectDerivationStrategyIntegTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ProjectDependencyResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/VersionConflictResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/ArtifactDeclarationIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/CrossProjectMultipleVariantSelectionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/MultipleVariantSelectionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/caching/DefaultArtifactCacheLockingManagerIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/compatibility/ArtifactAndClassifierCompatibilityIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/features/FeaturesResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/http/AbstractProxyResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/http/AbstractRedirectResolveBaseIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/http/DeprecatedTLSVersionDependencyResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/http/HttpAuthenticationDependencyResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/http/HttpEncodingDependencyResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ivy/IvyJvmLibraryArtifactResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/BadPomFileResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/ClassifierToVariantResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenComponentMetadataRulesChangingModulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenHttpRepoResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenJvmLibraryArtifactResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenLocalDependencyWithGradleMetadataResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenVersionRangeResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/platforms/JavaPlatformResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/ComponentMetadataRulesChangingModulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/ComponentReplacementIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/DependencyResolveRulesPreferProjectModulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/VariantAttributesRulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/VariantFilesMetadataRulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/resolve/AbstractGenerateGraphTask.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/resolve/ConfigurationCacheCompatibleGenerateGraphTask.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/resolve/GenerateGraphTask.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/resolve/ResolveTestFixture.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/groovy/GroovyJavaLibraryInteractionIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaLibraryCrossProjectTargetJvmVersionIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaLibraryPublishedTargetJvmEnvironmentIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/fixtures/AbstractJavaTestFixturesIntegrationTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/BomSupportPluginsSmokeTest.groovy
Labels: in:configuration-cache

#22946 Link specified as plain text
  subprojects/wrapper-shared/src/main/java/org/gradle/util/internal/ZipSlip.java
  subprojects/wrapper-shared/src/main/java/org/gradle/wrapper/BootstrapMainStarter.java
  subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy
Labels: from:contributor

#22947 Generate commit distributions in build directory
  build-logic/performance-testing/src/main/groovy/gradlebuild/performance/tasks/PerformanceTest.groovy
  build-logic/performance-testing/src/main/kotlin/gradlebuild/performance/PerformanceTestPlugin.kt
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/CommitDistribution.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/IntegrationTestBuildContext.java
Labels: @dev-productivity

#22969 Fix some configuration cache edge cases
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheTaskSerializationIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/ArtifactCollectionCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/ConfigurableFileCollectionCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/FileCollectionCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/ProviderCodecs.kt
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/DependencyHandlerProviderIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/DependencyNotationIntegrationSpec.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/DependencySubstitutionRulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/DirectoryOutputArtifactIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/LazyDownloadsIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ResolveConfigurationDependenciesBuildOperationIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/AddingConfigurationIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/ArtifactDeclarationIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/ConfigurationDefaultsIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/ConfigurationMutationIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/DependencyHandlerApiResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenLocalDependencyWithGradleMetadataResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/ArtifactBackedResolvedVariant.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/ArtifactVisitor.java
  subprojects/file-collections/src/integTest/groovy/org/gradle/api/file/FilePropertyLifecycleIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/resolve/ResolveFailureTestFixture.groovy
Labels: in:configuration-cache

#22974 Remove cygwin gcc from toolchain candidates
  subprojects/platform-native/src/testFixtures/groovy/org/gradle/nativeplatform/fixtures/AvailableToolChains.java
Labels: @dev-productivity

#22950 Prepare for 7.6.1 release
  released-versions.json
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/docs/src/docs/release/notes.md
  version.txt
Labels: a:chore

#22967 Let Kotlin DSL script compilation not fix JVM target to 8
  build-logic-commons/gradle-plugin/build.gradle.kts
  build-logic/kotlin-dsl/src/main/kotlin/gradlebuild.kotlin-dsl-dependencies-embedded.gradle.kts
  gradle/verification-metadata.xml
  gradle/wrapper/gradle-wrapper.properties
  subprojects/docs/src/docs/release/notes.md
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/jvm/JavaClassUtil.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/jvm/JavaClassUtilTest.groovy
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/KotlinDslJvmTargetIntegrationTest.kt
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/ProjectSchemaAccessorsIntegrationTest.kt
  subprojects/kotlin-dsl-plugins/build.gradle.kts
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginCrossVersionSmokeTest.kt
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginTest.kt
  subprojects/kotlin-dsl-plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/precompiled/PrecompiledScriptPlugins.kt
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/DefaultPrecompiledScriptPluginsSupport.kt
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/tasks/CompilePrecompiledScriptPluginPlugins.kt
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/tasks/GeneratePrecompiledScriptPluginAccessors.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinBuildScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinInitScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinSettingsScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/codegen/ApiExtensionsJar.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/execution/Interpreter.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/execution/ResidualProgramCompiler.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/KotlinScriptEvaluator.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/PrecompiledScriptPluginsSupport.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/KotlinCompiler.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/bytecode/AsmExtensions.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/bytecode/GradleJvmVersion.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/accessors/KotlinMetadataIntegrationTest.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/accessors/ProjectAccessorsClassPathTest.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/execution/InterpreterTest.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/execution/TestWithCompiler.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/integration/KotlinScriptCompilerTest.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/normalization/KotlinApiClassExtractorTest.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/support/KotlinCompilerTest.kt
  subprojects/kotlin-dsl/src/testFixtures/kotlin/org/gradle/kotlin/dsl/fixtures/AbstractKotlinIntegrationTest.kt
  subprojects/kotlin-dsl/src/testFixtures/kotlin/org/gradle/kotlin/dsl/fixtures/SimplifiedKotlinScriptEvaluator.kt
  subprojects/kotlin-dsl/src/testFixtures/kotlin/org/gradle/kotlin/dsl/fixtures/bytecode/AsmExtensions.kt
Labels: a:feature, in:kotlin-dsl

#22982 Update wrapper to the latest nightly
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore, in:building-gradle

#22990 Enable load after store on a configuration cache miss by default
  subprojects/build-events/src/integTest/groovy/org/gradle/build/event/BuildEventsIntegrationTest.groovy
  subprojects/build-events/src/integTest/groovy/org/gradle/build/event/InternalBuildOperationEventsIntegrationTest.groovy
  subprojects/configuration-cache/src/crossVersionTest/groovy/org/gradle/configurationcache/ConfigurationCacheCrossVersionTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOperationsIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheCompositeBuildsIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheDependencyResolutionIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheGroovyClosureIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIncompatibleTasksIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheParallelTaskIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheProblemReportingIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCachePublishingIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheScriptTaskDefinitionIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheTaskSerializationIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheUnsupportedTypesIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/isolated/IsolatedProjectsFixture.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/isolated/IsolatedProjectsToolingApiPhasedBuildActionIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheBuildOperations.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/ConfigurationCacheStartParameter.kt
  subprojects/configuration-cache/src/test/kotlin/org/gradle/configurationcache/ConfigurationCacheKeyTest.kt
  subprojects/core/src/integTest/groovy/org/gradle/api/services/BuildServiceIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/services/BuildServiceParallelExecutionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ivy/IvyBrokenDescriptorIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ivy/IvyDescriptorResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ivy/IvyDynamicRevisionRemoteResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ivy/IvyHttpRepoResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ivy/IvyResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenPomResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rocache/AbstractReadOnlyCacheDependencyResolutionTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rocache/StaticVersionsReadOnlyCacheDependencyResolutionTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ConcurrentBuildsArtifactTransformIntegrationTest.groovy
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
  subprojects/docs/src/snippets/configurationCache/topLevel/tests-groovy/notSupported.sample.conf
  subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/GradleEnterprisePluginBackgroundJobExecutorsIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/configurationcache/ConfigurationCacheBuildOperationsFixture.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/configurationcache/ConfigurationCacheFixture.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/configurationcache/ConfigurationCacheTest.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/configurationcache/ConfigurationCacheTestExtension.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/configurationcache/ConfigurationCacheTestInterceptor.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/ConfigurationCacheGradleExecuter.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/DefaultGradleDistribution.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/GradleDistribution.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/InProcessGradleExecuter.java
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/taskgrouping/AbstractLoggingHooksFunctionalTest.groovy
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/DefaultPersistentDirectoryStore.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/TestRetryPluginSmokeTest.groovy
Labels: in:configuration-cache

#23004 Update wrapper to latest nightly
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore, in:building-gradle, @configuration-cache

#22989 Remove CompileView attribute from derived Maven variants
  subprojects/core/src/main/java/org/gradle/api/internal/artifacts/JavaEcosystemSupport.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/artifacts/JavaEcosystemSupportTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/DependenciesAttributesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/bundling/JavaBundlingResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ivy/IvyGradleMetadataRedirectionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenGradleMetadataRedirectionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/VariantAttributesRulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/VariantFilesMetadataRulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationWritingIntegTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/metadata/DefaultMavenImmutableAttributesFactory.java
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/DependencyInsightReportTaskIntegrationTest.groovy
  subprojects/docs/src/snippets/dependencyManagement/inspectingDependencies-dependencyReason/tests/dependencyReasonReport.out
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-declaringCapabilities/tests/dependencyReport.out
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-declaringCapabilities/tests/dependencyReportReplaced.out
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/ivy/IvyFileModule.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/maven/AbstractMavenModule.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaApplicationOutgoingVariantsIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaLibraryCrossProjectTargetJvmVersionIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaLibraryOutgoingVariantsIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaProjectOutgoingVariantsIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/fixtures/AbstractJavaTestFixturesIntegrationTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginSmokeTest.groovy
Labels: a:bug, @core

#23008 Improve accuracy of `ProjectsIdentifiedProgressDetails` events for builds loaded from configuration cache
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOperationsIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildTreeStructureIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/CachedBuildState.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/core/src/integTest/groovy/org/gradle/initialization/BuildInitializationBuildOperationsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/LoadBuildStructureBuildOperationIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/internal/operations/notify/BuildOperationNotificationIntegrationTest.groovy
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/taskgrouping/AbstractLoggingHooksFunctionalTest.groovy
Labels: in:configuration-cache

#22901 Move base plugin to platform-base
  subprojects/core/src/integTest/groovy/org/gradle/api/PluginDetectionIntegrationTest.groovy
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/ear/build.gradle.kts
  subprojects/ear/src/main/java/org/gradle/plugins/ear/EarPlugin.java
  subprojects/ide/src/crossVersionTest/groovy/org/gradle/plugins/ide/tooling/r214/ToolingApEclipseModelNaturesAndBuildCommandsCrossVersionSpec.groovy
  subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/eclipse/EclipseWtpEarProjectIntegrationTest.groovy
  subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/eclipse/EclipseWtpJavaEarSingleProjectIntegrationTest.groovy
  subprojects/platform-base/src/main/java/org/gradle/api/internal/plugins/BuildConfigurationRule.java
  subprojects/platform-base/src/main/java/org/gradle/api/internal/plugins/DefaultArtifactPublicationSet.java
  subprojects/platform-base/src/main/java/org/gradle/api/plugins/BasePlugin.java
  subprojects/platform-base/src/main/java/org/gradle/api/plugins/BasePluginConvention.java
  subprojects/platform-base/src/main/java/org/gradle/api/plugins/BasePluginExtension.java
  subprojects/platform-base/src/main/java/org/gradle/api/plugins/internal/DefaultBasePluginConvention.java
  subprojects/platform-base/src/main/java/org/gradle/api/plugins/internal/DefaultBasePluginExtension.java
  subprojects/platform-base/src/test/groovy/org/gradle/api/internal/plugins/DefaultArtifactPublicationSetTest.groovy
  subprojects/platform-base/src/test/groovy/org/gradle/api/plugins/BasePluginTest.groovy
  subprojects/platform-base/src/test/groovy/org/gradle/api/plugins/DefaultBasePluginConventionTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/internal/plugins/AbstractRule.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaBasePlugin.java
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/JavaBasePluginTest.groovy
  subprojects/signing/build.gradle.kts
Labels: @core

#22992 Remove --no-rebuild command line option
  subprojects/core/src/integTest/groovy/org/gradle/api/ConfigurationOnDemandIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/initialization/StartParameterBuildOptions.java
  subprojects/docs/src/docs/userguide/authoring-builds/organizing_gradle_projects.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/docs/userguide/reference/command_line_interface.adoc
Labels: a:chore, in:console

#23001 Add reproducer test for KT-55065
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/GradleKotlinDslRegressionsTest.kt
Labels: in:kotlin-dsl

#23006 fix issue#22955: Show usage information (e.g. description) when @Option is specified incorrectly on command line
  subprojects/cli/src/main/java/org/gradle/cli/CommandLineParser.java
  subprojects/cli/src/test/groovy/org/gradle/cli/CommandLineParserTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/options/TaskOptionFailureIntegrationTest.groovy
  subprojects/core/src/test/groovy/org/gradle/initialization/ParallelismConfigurationCommandLineConverterTest.groovy
  subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy
Labels: from:contributor

#23015 Set Kotlin API/Language level to 1.5 for the Kotlin DSL
  .teamcity/subprojects.json
  build-logic-commons/gradle-plugin/build.gradle.kts
  build-logic/kotlin-dsl/src/main/kotlin/gradlebuild.kotlin-dsl-dependencies-embedded.gradle.kts
  gradle/verification-metadata.xml
  gradle/wrapper/gradle-wrapper.properties
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/GradleKotlinDslRegressionsTest.kt
  subprojects/kotlin-dsl-plugins/build.gradle.kts
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinCompilerWarningsTest.kt
  subprojects/kotlin-dsl-plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/dsl/ExperimentalCompilerWarningSilencer.kt
  subprojects/kotlin-dsl-plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslCompilerPlugins.kt
  subprojects/kotlin-dsl-plugins/src/test/kotlin/org/gradle/kotlin/dsl/plugins/dsl/ExperimentalCompilerWarningSilencerTest.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinBuildScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinInitScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinSettingsScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/KotlinCompiler.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/codegen/GradleApiExtensionsTest.kt
Labels: in:kotlin-dsl

#23031 Update gradle wrapper for Kotlin language/api 1.5
  gradle/verification-metadata.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore, in:building-gradle

#23042 Fix some issues with discarding project state after storing the configuration cache entry
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultIncludedBuildRegistry.java
  subprojects/composite-builds/src/test/groovy/org/gradle/composite/internal/DefaultIncludedBuildTaskGraphParallelTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheBuild.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheHost.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/CrossProjectConfigurationReportingGradle.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultConfigurationCache.kt
  subprojects/core/src/main/java/org/gradle/api/internal/GradleInternal.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProjectRegistry.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProjectStateRegistry.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/IProjectFactory.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/ProjectFactory.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/ProjectLifecycleController.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/ProjectRegistry.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/ProjectState.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/ProjectStateRegistry.java
  subprojects/core/src/main/java/org/gradle/execution/plan/TaskNodeFactory.java
  subprojects/core/src/main/java/org/gradle/internal/build/AbstractBuildState.java
  subprojects/core/src/main/java/org/gradle/internal/build/BuildLifecycleController.java
  subprojects/core/src/main/java/org/gradle/internal/build/BuildState.java
  subprojects/core/src/main/java/org/gradle/internal/build/BuildWorkGraphController.java
  subprojects/core/src/main/java/org/gradle/internal/build/DefaultBuildLifecycleController.java
  subprojects/core/src/main/java/org/gradle/internal/build/DefaultBuildWorkGraphController.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GradleScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/ServiceRegistryFactory.java
  subprojects/core/src/main/java/org/gradle/invocation/DefaultGradle.java
  subprojects/core/src/main/java/org/gradle/testfixtures/internal/ProjectBuilderImpl.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/DefaultProjectStateRegistryTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/ProjectFactoryTest.groovy
  subprojects/core/src/test/groovy/org/gradle/execution/plan/TaskNodeFactoryTest.groovy
  subprojects/core/src/test/groovy/org/gradle/initialization/DefaultProjectDescriptorRegistryTest.java
  subprojects/core/src/test/groovy/org/gradle/initialization/DefaultProjectDescriptorTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultDependencyManagementServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/PublishArtifactNotationParserFactory.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationContainerTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationSpec.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/dsl/PublishArtifactNotationParserFactoryTest.groovy
Labels: in:configuration-cache

#23044 Fix wrong nightly version comparison
  build-logic/cleanup/src/main/kotlin/gradlebuild/testing/services/BuildBucketProvider.kt
Labels: @dev-productivity

#23039 Mitigate flakiness
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/m9/GradlePropertiesToolingApiCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r40/ResolveArtifactsProgressCrossVersionSpec.groovy
  subprojects/tooling-api/src/integTest/groovy/org/gradle/integtests/tooling/ToolingApiClientJdkCompatibilityTest.groovy
Labels: @dev-productivity

#23048 Update compatibility matrix for Kotlin language 1.5
  subprojects/docs/src/docs/userguide/compatibility.adoc
Labels: in:kotlin-dsl

#23033 Fix remaining configuration cache compatibility issues in docs
  subprojects/docs/src/docs/userguide/core-plugins/project_report_plugin.adoc
  subprojects/docs/src/snippets/tasks/incrementalBuild-customTaskClass/groovy/build.gradle
  subprojects/docs/src/snippets/tasks/incrementalBuild-customTaskClass/groovy/src/headers/headers.txt
  subprojects/docs/src/snippets/tasks/incrementalBuild-customTaskClass/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/tasks/incrementalBuild-customTaskClass/kotlin/src/headers/headers.txt
  subprojects/docs/src/snippets/tasks/incrementalBuild-customTaskClass/tests/build.sample.conf
  subprojects/docs/src/snippets/tasks/incrementalBuild-customTaskClass/tests/removeTempDir.sample.conf
Labels: in:configuration-cache, @configuration-cache, in:documentation

#23024 Fix the issue of provisioning the same toolchain multiple times
  subprojects/jvm-services/src/main/java/org/gradle/jvm/toolchain/internal/JavaInstallationRegistry.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainQueryService.java
  subprojects/soak/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainDownloadComplexProjectSoakTest.groovy
  subprojects/soak/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainDownloadSoakTest.groovy
Labels: in:toolchains

#22954 Refactor dependency management for readability, clarity on theoretical example
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/core_dependency_management.adoc
Labels: a:documentation

#22881 Allow GUH cleanup retention times to be specified as timestamps
  subprojects/build-cache/build.gradle.kts
  subprojects/build-cache/src/main/java/org/gradle/caching/local/internal/DirectoryBuildCacheServiceFactory.java
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheRepository.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/core-api/src/main/java/org/gradle/api/cache/CacheResourceConfiguration.java
  subprojects/core-api/src/main/java/org/gradle/api/internal/cache/CacheConfigurationsInternal.java
  subprojects/core-api/src/main/java/org/gradle/api/internal/cache/CacheResourceConfigurationInternal.java
  subprojects/core-api/src/main/java/org/gradle/api/internal/cache/DefaultCacheCleanupStrategy.java
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/cache/CacheConfigurationsIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/cache/DefaultCacheConfigurations.java
  subprojects/core/src/main/java/org/gradle/cache/internal/GradleUserHomeCleanupService.java
  subprojects/core/src/main/java/org/gradle/cache/internal/VersionSpecificCacheCleanupAction.java
  subprojects/core/src/main/java/org/gradle/initialization/layout/ProjectCacheDir.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/DefaultClasspathTransformerCacheFactory.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GradleUserHomeScopeServices.java
  subprojects/core/src/main/java/org/gradle/testfixtures/internal/TestInMemoryCacheFactory.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/cache/DefaultCacheConfigurationsTest.groovy
  subprojects/core/src/test/groovy/org/gradle/cache/internal/GradleUserHomeCleanupServiceTest.groovy
  subprojects/core/src/test/groovy/org/gradle/cache/internal/VersionSpecificCacheCleanupActionTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/classpath/DefaultCachedClasspathTransformerTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/cache/internal/GradleUserHomeCleanupFixture.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/WritableArtifactCacheLockingManager.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/DefaultArtifactCacheLockingManagerTest.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/workspace/impl/DefaultImmutableWorkspaceProvider.java
  subprojects/functional/src/main/java/org/gradle/internal/time/TimestampSuppliers.java
  subprojects/functional/src/test/groovy/org/gradle/internal/time/TimestampSuppliersTest.groovy
  subprojects/persistent-cache/build.gradle.kts
  subprojects/persistent-cache/src/main/java/org/gradle/cache/CacheBuilder.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/CacheCleanupStrategy.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/CleanupFrequency.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/CacheCleanupExecutor.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/CacheFactory.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/DefaultCacheAccess.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/DefaultCacheFactory.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/DefaultCacheRepository.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/DefaultPersistentDirectoryCache.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/DefaultPersistentDirectoryStore.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/LeastRecentlyUsedCacheCleanup.java
  subprojects/persistent-cache/src/test/groovy/org/gradle/cache/internal/DefaultCacheAccessTest.groovy
  subprojects/persistent-cache/src/test/groovy/org/gradle/cache/internal/DefaultPersistentDirectoryCacheTest.groovy
  subprojects/persistent-cache/src/test/groovy/org/gradle/cache/internal/DefaultPersistentDirectoryStoreTest.groovy
  subprojects/persistent-cache/src/test/groovy/org/gradle/cache/internal/LeastRecentlyUsedCacheCleanupTest.groovy
  subprojects/version-control/build.gradle.kts
  subprojects/version-control/src/main/java/org/gradle/vcs/internal/services/DefaultVersionControlRepositoryFactory.java
Labels: a:feature

#23065 Discard references to Project instances after storing configuration cache entry
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/CrossProjectConfigurationReportingTaskExecutionGraph.kt
  subprojects/core/src/main/java/org/gradle/execution/taskgraph/DefaultTaskExecutionGraph.java
  subprojects/core/src/main/java/org/gradle/execution/taskgraph/TaskExecutionGraphInternal.java
  subprojects/core/src/main/java/org/gradle/internal/build/AbstractBuildState.java
  subprojects/core/src/main/java/org/gradle/internal/cleanup/DefaultBuildOutputCleanupRegistry.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GradleScopeServices.java
  subprojects/core/src/main/java/org/gradle/invocation/DefaultGradle.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationSpec.groovy
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
  subprojects/execution/src/main/java/org/gradle/internal/execution/BuildOutputCleanupRegistry.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/InProcessGradleExecuter.java
  subprojects/messaging/src/main/java/org/gradle/internal/event/AnonymousListenerBroadcast.java
  subprojects/messaging/src/main/java/org/gradle/internal/event/BroadcastDispatch.java
  subprojects/messaging/src/main/java/org/gradle/internal/event/DefaultListenerManager.java
  subprojects/messaging/src/main/java/org/gradle/internal/event/ListenerBroadcast.java
  subprojects/messaging/src/test/groovy/org/gradle/internal/event/BroadcastDispatchTest.groovy
  subprojects/messaging/src/test/groovy/org/gradle/internal/event/DefaultListenerManagerTest.groovy
  subprojects/messaging/src/test/groovy/org/gradle/internal/event/ListenerBroadcastTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/tasks/testing/TestTaskSpec.groovy
  subprojects/testing-base/src/main/java/org/gradle/api/tasks/testing/AbstractTestTask.java
Labels: in:configuration-cache

#23070 Fix test fixture version calculation
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/DefaultGradleDistribution.groovy
Labels: in:configuration-cache

#23050 Do not expose named domain object list
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/platform-jvm/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainDownloadSpiIntegrationTest.groovy
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/JavaToolchainRepositoryHandler.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/DefaultJavaToolchainRepositoryHandler.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/DefaultJavaToolchainResolverRegistry.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainResolverRegistryInternal.java
Labels: in:toolchains

#23060 Update plugin configuration cache compatibility table
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
Labels: a:documentation

#23073 Pass null value to visitNested and remove visitMissingNested in TypeMetadataWalker.InstanceMetadataVisitor
  subprojects/model-core/src/main/java/org/gradle/internal/properties/annotations/AbstractTypeMetadataWalker.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/annotations/TypeMetadataWalker.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/bean/DefaultPropertyWalker.java
  subprojects/model-core/src/test/groovy/org/gradle/internal/properties/annotations/AbstractTypeMetadataWalkerTest.groovy
Labels: @execution

#23077 Change build description
  .teamcity/src/main/kotlin/promotion/PublishNightlySnapshotFromQuickFeedbackStepPromote.kt
Labels: @dev-productivity

#23078 Update wrapper
  gradle/wrapper/gradle-wrapper.properties
Labels: in:building-gradle

#23043 Print more informative warnings when the daemon expires due to memory issues
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/OutputScrapingExecutionResult.java
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/DaemonHealthLoggingIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/server/health/gc/GarbageCollectionMonitoringIntegrationTest.groovy
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/DaemonServices.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/exec/LogAndCheckHealth.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/health/DaemonHealthStats.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/health/DaemonMemoryStatus.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/health/GcThrashingDaemonExpirationStrategy.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/health/HealthExpirationStrategy.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/health/HealthLogger.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/health/LowHeapSpaceDaemonExpirationStrategy.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/health/LowNonHeapDaemonExpirationStrategy.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/health/gc/GarbageCollectionStats.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/health/gc/GarbageCollectorMonitoringStrategy.java
  subprojects/launcher/src/test/groovy/org/gradle/launcher/daemon/server/exec/LogAndCheckHealthTest.groovy
  subprojects/launcher/src/test/groovy/org/gradle/launcher/daemon/server/health/DaemonHealthStatsTest.groovy
  subprojects/launcher/src/test/groovy/org/gradle/launcher/daemon/server/health/DaemonMemoryStatusTest.groovy
  subprojects/launcher/src/test/groovy/org/gradle/launcher/daemon/server/health/GcThrashingDaemonExpirationStrategyTest.groovy
  subprojects/launcher/src/test/groovy/org/gradle/launcher/daemon/server/health/HealthExpirationStrategyTest.groovy
  subprojects/launcher/src/test/groovy/org/gradle/launcher/daemon/server/health/HealthLoggerTest.groovy
  subprojects/launcher/src/test/groovy/org/gradle/launcher/daemon/server/health/LowHeapSpaceDaemonExpirationStrategyTest.groovy
  subprojects/launcher/src/test/groovy/org/gradle/launcher/daemon/server/health/LowNonHeapDaemonExpirationStrategyTest.groovy
  subprojects/launcher/src/test/groovy/org/gradle/launcher/daemon/server/health/gc/GarbageCollectionStatsTest.groovy
  subprojects/soak/src/integTest/groovy/org/gradle/launcher/daemon/DaemonPerformanceMonitoringSoakTest.groovy
Labels: @core

#23108 Rebaseline JavaFirstUsePerformanceTest
  gradle.properties
Labels: @dev-productivity

#23109 Remove "Remote test distribution enabled" log
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
Labels: @dev-productivity

#23056 Fix 'structuring-software-projects' sample
  subprojects/docs/src/samples/build-organization/structuring-software-projects/kotlin/platforms/plugins-platform/build.gradle.kts
Labels: a:documentation

#23047 Smoke test Kotlin 1.8.0-RC
  build-logic/performance-testing/src/main/groovy/gradlebuild.performance-templates.gradle
  subprojects/docs/src/docs/userguide/compatibility.adoc
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/jvm/JavaToolchainBuildOperationsFixture.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/KotlinGradlePluginVersions.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/JavaToolchainBuildOperationsIntegrationTest.groovy
  subprojects/smoke-test/build.gradle.kts
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerCachingSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/android-kotlin-example-kotlin-dsl/app/build.gradle.kts
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/android-kotlin-example-kotlin-dsl/build.gradle.kts
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/android-kotlin-example/app/build.gradle
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/android-kotlin-example/build.gradle
Labels: a:chore

#23063 Add documentation for Gradle User Home cleanup and fix build session issue
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/core-api/src/main/java/org/gradle/api/internal/cache/CacheConfigurationsInternal.java
  subprojects/core-api/src/main/java/org/gradle/api/internal/cache/CacheResourceConfigurationInternal.java
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/cache/CacheConfigurationsCompositeBuildTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/cache/CacheConfigurationsContinuousIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/cache/CacheConfigurationsIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/cache/DefaultCacheConfigurations.java
  subprojects/core/src/main/java/org/gradle/initialization/ScriptEvaluatingSettingsProcessor.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/cache/DefaultCacheConfigurationsTest.groovy
  subprojects/docs/src/docs/dsl/org.gradle.api.initialization.Settings.xml
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/reference/directory_layout.adoc
  subprojects/docs/src/snippets/initScripts/cacheRetention/groovy/build.gradle
  subprojects/docs/src/snippets/initScripts/cacheRetention/groovy/gradleUserHome/init.d/cache-settings.gradle
  subprojects/docs/src/snippets/initScripts/cacheRetention/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/initScripts/cacheRetention/kotlin/gradleUserHome/init.d/cache-settings.gradle.kts
  subprojects/docs/src/snippets/initScripts/cacheRetention/tests-groovy/cacheRetention.sample.conf
  subprojects/docs/src/snippets/initScripts/cacheRetention/tests-kotlin/cacheRetention.sample.conf
  subprojects/docs/src/snippets/initScripts/disableCacheCleanup/groovy/build.gradle
  subprojects/docs/src/snippets/initScripts/disableCacheCleanup/groovy/gradleUserHome/init.d/cache-settings.gradle
  subprojects/docs/src/snippets/initScripts/disableCacheCleanup/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/initScripts/disableCacheCleanup/kotlin/gradleUserHome/init.d/cache-settings.gradle.kts
  subprojects/docs/src/snippets/initScripts/disableCacheCleanup/tests-groovy/cacheRetention.sample.conf
  subprojects/docs/src/snippets/initScripts/disableCacheCleanup/tests-kotlin/cacheRetention.sample.conf
Labels: a:feature

#22985 Update user guides and docs regarding tasks using Java toolchains
  subprojects/docs/README.md
  subprojects/docs/src/docs/userguide/jvm/building_java_projects.adoc
  subprojects/docs/src/docs/userguide/jvm/java_plugin.adoc
  subprojects/docs/src/docs/userguide/jvm/scala_plugin.adoc
  subprojects/docs/src/docs/userguide/jvm/toolchains.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/main/resources/header.html
  subprojects/docs/src/samples/java/jvm-multi-project-with-toolchains/groovy/application/build.gradle
  subprojects/docs/src/samples/java/jvm-multi-project-with-toolchains/groovy/list/build.gradle
  subprojects/docs/src/samples/java/jvm-multi-project-with-toolchains/kotlin/application/build.gradle.kts
  subprojects/docs/src/samples/java/jvm-multi-project-with-toolchains/kotlin/list/build.gradle.kts
  subprojects/docs/src/snippets/java/basic/groovy/build.gradle
  subprojects/docs/src/snippets/java/basic/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/java/preview/groovy/build.gradle
  subprojects/docs/src/snippets/java/preview/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/java/toolchain-basic/groovy/build.gradle
  subprojects/docs/src/snippets/java/toolchain-basic/groovy/settings.gradle
  subprojects/docs/src/snippets/java/toolchain-basic/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/java/toolchain-basic/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/java/toolchain-basic/tests/toolchainBasic.sample.conf
  subprojects/docs/src/snippets/java/toolchain-task/groovy/build.gradle
  subprojects/docs/src/snippets/java/toolchain-task/kotlin/build.gradle.kts
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/ForkOptions.java
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/java/SamplesJavaTestingIntegrationTest.groovy
Labels: in:toolchains, a:documentation

#22809 Fix concurrency issue with ZipFileTree class
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/bundling/ArchiveIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/bundling/ConcurrentArchiveIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/cache/DefaultDecompressionCacheFactory.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/DefaultFileOperations.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/archive/AbstractArchiveFileTree.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/archive/AbstractArchiveFileTreeElement.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/archive/TarFileTree.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/archive/ZipFileTree.java
  subprojects/core/src/main/java/org/gradle/internal/buildtree/BuildTreeScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GradleUserHomeScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/WorkerSharedProjectScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/WorkerSharedUserHomeScopeServices.java
  subprojects/core/src/main/java/org/gradle/testfixtures/internal/TestInMemoryCacheFactory.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/DefaultFileOperationsTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/archive/AbstractArchiveFileTreeSpec.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/archive/AbstractArchiveFileTreeTest.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/archive/TarFileTreeTest.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/archive/ZipFileTreeTest.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/DefaultProjectSpec.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/fingerprint/impl/DefaultFileCollectionSnapshotterTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/api/internal/file/TestFiles.java
  subprojects/core/src/testFixtures/groovy/org/gradle/cache/internal/TestCaches.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/DecompressionCache.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/DecompressionCacheFactory.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/DefaultDecompressionCache.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/scopes/DefaultProjectScopedCache.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/scopes/ProjectScopedCache.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/scopes/ScopedCache.java
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/impldeps/GradleImplDepsCompatibilityIntegrationTest.groovy
  subprojects/scala/src/main/java/org/gradle/api/internal/tasks/scala/ZincScalaCompilerFacade.java
Labels: in:file-tasks

#23085 Add snippets for BuildService implementing OperationCompleteListener
  subprojects/docs/src/docs/userguide/extending-gradle/build_services.adoc
  subprojects/docs/src/snippets/plugins/buildServiceListener/groovy/build.gradle
  subprojects/docs/src/snippets/plugins/buildServiceListener/groovy/buildSrc/build.gradle
  subprojects/docs/src/snippets/plugins/buildServiceListener/groovy/buildSrc/src/main/java/TaskEventsPlugin.java
  subprojects/docs/src/snippets/plugins/buildServiceListener/groovy/buildSrc/src/main/java/TaskEventsService.java
  subprojects/docs/src/snippets/plugins/buildServiceListener/groovy/settings.gradle
  subprojects/docs/src/snippets/plugins/buildServiceListener/tests/registerListener.out
  subprojects/docs/src/snippets/plugins/buildServiceListener/tests/registerListener.sample.conf
Labels: a:documentation

#23146 Move @Flaky annotation to ResolveArtifactsProgressCrossVersionSpec class
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r40/ResolveArtifactsProgressCrossVersionSpec.groovy
Labels: @dev-productivity

#22786 Scala Plugin: remove `ExternalBinariesLookup`
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/ZincScalaCompilerIntegrationTest.groovy
  subprojects/scala/src/main/java/org/gradle/api/internal/tasks/scala/ZincScalaCompiler.java
Labels: from:contributor

#23075 Handle inconsistent vendor info for IBM Semeru runtimes
  subprojects/docs/src/docs/userguide/jvm/toolchains.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/snippets/java/toolchain-filters/groovy/build.gradle
  subprojects/docs/src/snippets/java/toolchain-filters/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/java/toolchain-management/groovy/settings.gradle
  subprojects/docs/src/snippets/java/toolchain-management/kotlin/settings.gradle.kts
  subprojects/jvm-services/src/main/java/org/gradle/internal/jvm/inspection/JvmVendor.java
  subprojects/jvm-services/src/test/groovy/org/gradle/internal/jvm/inspection/DefaultJvmMetadataDetectorTest.groovy
  subprojects/platform-jvm/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainDownloadIntegrationTest.groovy
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/JvmVendorSpec.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainMatcher.java
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/toolchain/internal/JavaToolchainMatcherTest.groovy
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/toolchain/internal/JavaToolchainQueryServiceTest.groovy
  subprojects/soak/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainDownloadComplexProjectSoakTest.groovy
  subprojects/soak/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainDownloadSoakTest.groovy
Labels: in:toolchains

#23118 Let `kotlin-dsl` plugin integrate with Java Toolchains
  build-logic-commons/code-quality-rules/build.gradle.kts
  build-logic-commons/commons/build.gradle.kts
  build-logic-commons/commons/src/main/kotlin/common.kt
  build-logic-commons/commons/src/main/kotlin/gradlebuild.commons.gradle.kts
  build-logic-commons/gradle-plugin/build.gradle.kts
  build-logic-commons/settings.gradle.kts
  build-logic-settings/build-logic-settings-plugin/build.gradle.kts
  build-logic-settings/settings.gradle.kts
  build-logic/kotlin-dsl/src/main/kotlin/gradlebuild.kotlin-dsl-dependencies-embedded.gradle.kts
  build-logic/settings.gradle.kts
  gradle/verification-metadata.xml
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/api/kotlin_dsl.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/KotlinDslJvmTargetIntegrationTest.kt
  subprojects/kotlin-dsl-plugins/build.gradle.kts
  subprojects/kotlin-dsl-plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/base/KotlinDslBasePlugin.kt
  subprojects/kotlin-dsl-plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslCompilerPlugins.kt
  subprojects/kotlin-dsl-plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginOptions.kt
  subprojects/kotlin-dsl-plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/precompiled/PrecompiledScriptPlugins.kt
  subprojects/kotlin-dsl-provider-plugins/build.gradle.kts
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/DefaultPrecompiledScriptPluginsSupport.kt
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/tasks/CompilePrecompiledScriptPluginPlugins.kt
  subprojects/logging/src/main/java/org/gradle/internal/deprecation/DeprecationLogger.java
  subprojects/model-core/src/main/java/org/gradle/internal/instantiation/generator/AbstractClassGenerator.java
  subprojects/model-core/src/test/groovy/org/gradle/internal/instantiation/generator/IdentityClassGenerator.java
Labels: a:feature, in:kotlin-dsl, in:precompiled-script-plugin

#23135 Move PackageListGenerator to build-logic
  build-logic/basics/build.gradle.kts
  build-logic/basics/src/main/kotlin/gradlebuild/basics/tasks/PackageListGenerator.kt
  build-logic/basics/src/test/kotlin/gradlebuild/basics/tasks/PackageListGeneratorIntegrationTest.kt
  build-logic/packaging/src/main/kotlin/gradlebuild.distributions.gradle.kts
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/runtimeshaded/PackageListGenerator.java
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/impldeps/PackageListGeneratorIntegrationTest.groovy
  subprojects/test-kit/build.gradle.kts
Labels: a:chore, in:kotlin-dsl

#23142 Let exceptions thrown by providers bubble up and fail the build
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheSupportedTypesIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/ProviderCodecs.kt
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskParametersIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/locking/AbstractLockingIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/locking/DependencyLockingStrictModeIntegrationTest.groovy
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/DependencyInsightReportTaskIntegrationTest.groovy
  subprojects/docs/src/snippets/java/toolchain-filters/tests/matchingVendorWithCC.out
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileToolchainIntegrationTest.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/swiftpm/SwiftPackageManagerDependencyMappingIntegrationTest.groovy
  subprojects/platform-jvm/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainDownloadSpiIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/catalog/VersionCatalogIntegrationTest.groovy
Labels: @configuration-cache

#23161 Don't store broken file collections to the configuration cache
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/FileCollectionCodec.kt
Labels: @configuration-cache

#23094 Handle inconsistent vendor info for IBM Semeru runtimes (backport)
  subprojects/docs/src/docs/userguide/jvm/toolchains.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/snippets/java/toolchain-filters/groovy/build.gradle
  subprojects/docs/src/snippets/java/toolchain-filters/kotlin/build.gradle.kts
  subprojects/jvm-services/src/main/java/org/gradle/internal/jvm/inspection/JvmVendor.java
  subprojects/jvm-services/src/test/groovy/org/gradle/internal/jvm/inspection/DefaultJvmMetadataDetectorTest.groovy
  subprojects/platform-jvm/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainDownloadIntegrationTest.groovy
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/JvmVendorSpec.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainMatcher.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/install/AdoptOpenJdkRemoteBinary.java
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/toolchain/install/internal/AdoptOpenJdkRemoteBinaryTest.groovy
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/toolchain/internal/JavaToolchainMatcherTest.groovy
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/toolchain/internal/JavaToolchainQueryServiceTest.groovy
Labels: in:toolchains

#23172 Mark `can debug with org.gradle.debug.server=false` flaky
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/CommandLineIntegrationSpec.groovy
Labels: @dev-productivity

#23173 Do not discard build services that are build event listeners after storing configuration cache entry
  subprojects/build-events/src/integTest/groovy/org/gradle/build/event/BuildEventsIntegrationTest.groovy
  subprojects/build-events/src/main/java/org/gradle/internal/build/event/BuildEventListenerRegistryInternal.java
  subprojects/build-events/src/main/java/org/gradle/internal/build/event/DefaultBuildEventsListenerRegistry.java
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheAwareBuildTreeWorkController.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheBuildTreeLifecycleControllerFactory.kt
  subprojects/core/src/integTest/groovy/org/gradle/api/services/BuildServiceIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/services/internal/BuildServiceRegistryInternal.java
  subprojects/core/src/main/java/org/gradle/api/services/internal/DefaultBuildServicesRegistry.java
  subprojects/core/src/main/java/org/gradle/api/services/internal/RegisteredBuildServiceProvider.java
  subprojects/core/src/main/java/org/gradle/internal/build/AbstractBuildState.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GradleScopeServices.java
Labels: @configuration-cache, in:build-services

#23176 Update wrapper to release-nightly
  build-logic-commons/gradle-plugin/build.gradle.kts
  gradle/verification-metadata.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore, in:building-gradle

#23167 Don't store broken `Serializable` objects to the configuration cache
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/extensions/DocumentRegistryExtensions.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/JsonModelWriter.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/BrokenValueCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/jos/JavaObjectSerializationCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/jos/ObjectInputStreamAdapter.kt
  subprojects/configuration-cache/src/test/kotlin/org/gradle/configurationcache/serialization/codecs/JavaObjectSerializationCodecTest.kt
Labels: @configuration-cache

#23122 Partially avoid needing QDox by using -parameters
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
  build-logic/jvm/src/main/kotlin/gradlebuild/jvm/extension/UnitTestAndCompileExtension.kt
  build-logic/uber-plugins/src/main/kotlin/gradlebuild.distribution-module.gradle.kts
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/BinDistributionIntegrationSpec.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DistributionIntegritySpec.groovy
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/codegen/ApiTypeProvider.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/codegen/GradleApiExtensionsTest.kt
Labels: a:feature, in:kotlin-dsl

#23156 Check SerializableLambda parameters for prohibited types in CC storing
  subprojects/configuration-cache/build.gradle.kts
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheLambdaIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/SerializedLambdaParametersCheckingCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/jos/JavaObjectSerializationCodec.kt
Labels: in:configuration-cache, @configuration-cache

#23115 make jvm args lists unmodifiable
  subprojects/core-api/src/main/java/org/gradle/process/JavaForkOptions.java
  subprojects/core/src/main/java/org/gradle/process/internal/JvmOptions.java
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/language-jvm/src/main/java/org/gradle/api/tasks/compile/ProviderAwareCompilerDaemonForkOptions.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/configuration/DaemonJvmOptions.java
  subprojects/launcher/src/test/groovy/org/gradle/launcher/daemon/configuration/DaemonJvmOptionsTest.groovy
Labels: a:bug, in:java-plugins, in:javadoc-task, in:exec-tasks

#23188 Fix potential IllegalStateException when an artifact transform is run while writing a configuration cache entry
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheDependencyResolutionIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/transform/CalculateArtifactsCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/transform/DefaultTransformerCodec.kt
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/ArtifactBackedResolvedVariant.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/BrokenArtifacts.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/BrokenResolvedArtifactSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/EndCollection.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/LocalFileDependencyBackedArtifactSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/ResolvedArtifactSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/AbstractTransformedArtifactSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformedProjectArtifactSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformingAsyncArtifactListener.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/TestArtifactSet.java
Labels: in:configuration-cache, @configuration-cache, in:artifact-transforms

#23143 Better handling of cache configuration mutability
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/core-api/src/main/java/org/gradle/api/internal/cache/CacheConfigurationsInternal.java
  subprojects/core-api/src/main/java/org/gradle/api/internal/cache/CacheResourceConfigurationInternal.java
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/cache/CacheConfigurationsContinuousIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/cache/CacheConfigurationsIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/cache/DefaultCacheConfigurations.java
  subprojects/core/src/main/java/org/gradle/initialization/ScriptEvaluatingSettingsProcessor.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/SettingsScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/cache/DefaultCacheConfigurationsTest.groovy
Labels: a:feature

#23192 Rebaseline to unblock release
  gradle.properties
Labels: @dev-productivity

#23194 Define toolchain download repository for build
  build-logic-commons/settings.gradle.kts
  build-logic-settings/settings.gradle.kts
  build-logic/settings.gradle.kts
  settings.gradle.kts
Labels: a:chore, in:building-gradle, in:toolchains

#23200 Dependency upgrades
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
  subprojects/distributions-dependencies/build.gradle.kts
Labels: a:chore

#23198 Make additionalOptions immutable for Scala compilation
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/ScalaCompileIntegrationTest.groovy
  subprojects/scala/src/main/java/org/gradle/api/tasks/scala/internal/ScalaCompileOptionsConfigurer.java
  subprojects/scala/src/main/java/org/gradle/language/scala/tasks/BaseScalaCompileOptions.java
  subprojects/scala/src/test/groovy/org/gradle/scala/compile/internal/ScalaCompileOptionsConfigurerTest.groovy
Labels: in:scala-plugin

#23205 Log incompatible tasks causing the configuration cache to be discarded
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheProblemReportingIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/ConfigurationCacheProblemsListener.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ConfigurationCacheProblems.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ProblemsListener.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/Codec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/Contexts.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/TaskNodeCodec.kt
  subprojects/configuration-cache/src/test/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintCheckerTest.kt
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/AbstractDependencyVerificationIntegTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationIntegrityCheckIntegTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationSignatureCheckIntegTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/configurationcache/ConfigurationCacheFixture.groovy
Labels: a:feature, in:configuration-cache, @configuration-cache

#23221 Move `BuildServiceRegistry` up to the `Build` service scope
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/BuildScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/ExecutionGradleServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GradleScopeServices.java
Labels: a:chore, @configuration-cache

#23220 Test coverage and minor fixes for serializing Groovy closures to the configuration cache
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheGroovyClosureIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/ClosureCodec.kt
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/CopySpecWrapper.java
  subprojects/docs/src/docs/release/notes.md
Labels: in:configuration-cache, @configuration-cache

#23119 Fix for Incremental compilation with modules
  subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/BaseIncrementalCompilationAfterFailureIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/CrossTaskIncrementalJavaCompilationIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/DefaultJavaCompileSpec.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompileSpec.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JdkJavaCompiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/RecompilationSpec.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/transaction/CompileTransaction.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/reflect/GradleStandardJavaFileManager.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/DefaultJavaCompileSpecTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/incremental/transaction/CompileTransactionTest.groovy
  subprojects/language-jvm/src/main/java/org/gradle/api/internal/tasks/compile/DefaultJvmLanguageCompileSpec.java
  subprojects/language-jvm/src/main/java/org/gradle/api/internal/tasks/compile/JvmLanguageCompileSpec.java
  subprojects/scala/src/main/java/org/gradle/language/scala/tasks/AbstractScalaCompile.java
Labels: @execution

#23218 Fix invalid serialization of dependency management results
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementValueSnapshotterSerializerRegistry.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ModuleVersionIdentifierSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/BuildIdentifierSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/CapabilitySerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ComponentIdentifierSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ComponentSelectionDescriptorSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ComponentSelectionReasonSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ComponentSelectorSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ResolvedComponentResultSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ResolvedVariantResultSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/store/DefaultBinaryStore.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/store/ResolutionResultsStoreFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/metadata/ComponentArtifactIdentifierSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/metadata/ComponentFileArtifactIdentifierSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/metadata/ModuleComponentFileArtifactIdentifierSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/metadata/PublishArtifactLocalArtifactMetadataSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/caching/DesugaringAttributeContainerSerializer.java
  subprojects/messaging/src/main/java/org/gradle/internal/serialize/DefaultSerializerRegistry.java
  subprojects/messaging/src/main/java/org/gradle/internal/serialize/SerializerRegistry.java
Labels: in:dependency-resolution

#23211 Fix issue with ant builder throwing exception on call()
  subprojects/model-core/src/integTest/groovy/org/gradle/internal/extensibility/CallablePropertyIntegrationTest.groovy
  subprojects/model-core/src/main/java/org/gradle/internal/extensibility/MixInClosurePropertiesAsMethodsDynamicObject.java
Labels: a:regression

#23181 Update docs to address cleanup with older versions of Gradle
  subprojects/docs/src/docs/userguide/reference/directory_layout.adoc
  subprojects/docs/src/snippets/initScripts/multiVersionCacheRetention/groovy/build.gradle
  subprojects/docs/src/snippets/initScripts/multiVersionCacheRetention/groovy/gradleUserHome/init.d/cache-settings.gradle
  subprojects/docs/src/snippets/initScripts/multiVersionCacheRetention/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/initScripts/multiVersionCacheRetention/kotlin/gradleUserHome/init.d/cache-settings.gradle.kts
  subprojects/docs/src/snippets/initScripts/multiVersionCacheRetention/tests-groovy/cacheRetention.sample.conf
  subprojects/docs/src/snippets/initScripts/multiVersionCacheRetention/tests-kotlin/cacheRetention.sample.conf
Labels: a:feature, in:documentation

#22199 Add build operation for IdentifyStep
  gradle.properties
  subprojects/core/src/integTest/groovy/org/gradle/internal/operations/notify/BuildOperationNotificationFixture.groovy
  subprojects/core/src/main/java/org/gradle/internal/operations/trace/BuildOperationTrace.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/ExecutionGradleServices.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuterTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementBuildScopeServices.java
  subprojects/execution/src/integTest/groovy/org/gradle/internal/execution/IncrementalExecutionIntegrationTest.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ExecuteStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/IdentifyStep.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/IdentifyStepTest.groovy
  subprojects/tooling-api/src/testFixtures/groovy/org/gradle/integtests/tooling/fixture/ProgressEvents.groovy
Labels: @execution

#23230 Hide timestamp in the cache cleanup API for now
  subprojects/core-api/src/main/java/org/gradle/api/cache/CacheResourceConfiguration.java
  subprojects/core-api/src/main/java/org/gradle/api/internal/cache/CacheResourceConfigurationInternal.java
Labels: a:feature

#23051 Picking up former-missing build scripts
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheMissingScriptIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/fixtures/MissingScriptFixture.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/isolated/IsolatedProjectToolingModelsWithDependencyResolutionIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/isolated/IsolatedProjectsToolingApiBuildActionIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/isolated/IsolatedProjectsToolingApiCompositeBuildsIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/isolated/IsolatedProjectsToolingApiCoupledProjectsIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/isolated/IsolatedProjectsToolingApiIModelQueryIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/isolated/IsolatedProjectsToolingApiParallelConfigurationIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/isolated/IsolatedProjectsToolingApiPhasedBuildActionIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintController.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintWriter.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/ConfigurationCacheProblemsListener.kt
  subprojects/core-api/src/main/java/org/gradle/internal/scripts/DefaultScriptFileResolver.java
  subprojects/core-api/src/main/java/org/gradle/internal/scripts/ScriptFileResolvedListener.java
  subprojects/core-api/src/main/java/org/gradle/vcs/VcsMappings.java
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/initialization/loadercache/ClassLoadersCachingIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/configuration/ScriptPluginFactorySelector.java
  subprojects/core/src/main/java/org/gradle/configuration/project/BuildScriptProcessor.java
  subprojects/core/src/main/java/org/gradle/initialization/DefaultSettings.java
  subprojects/core/src/main/java/org/gradle/initialization/layout/BuildLayoutFactory.java
  subprojects/core/src/main/java/org/gradle/internal/scripts/DefaultScriptFileResolverListeners.java
  subprojects/core/src/main/java/org/gradle/internal/scripts/ScriptFileResolverListeners.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GlobalScopeServices.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractAutoTestedSamplesTest.groovy
Labels: @configuration-cache

#23222 Introduce `FlowScope` API
  subprojects/configuration-cache/build.gradle.kts
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheFlowScopeIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheIO.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultBuildModelControllerServices.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/flow/BuildFlowScope.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/flow/DefaultFlowProviders.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/flow/FlowParametersInstantiator.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/flow/FlowScheduler.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/flow/FlowServicesProvider.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/ProviderCodecs.kt
  subprojects/configuration-cache/src/test/kotlin/org/gradle/configurationcache/serialization/codecs/AbstractUserTypeCodecTest.kt
  subprojects/core-api/src/main/java/org/gradle/api/flow/FlowAction.java
  subprojects/core-api/src/main/java/org/gradle/api/flow/FlowActionSpec.java
  subprojects/core-api/src/main/java/org/gradle/api/flow/FlowParameters.java
  subprojects/core-api/src/main/java/org/gradle/api/flow/FlowProviders.java
  subprojects/core-api/src/main/java/org/gradle/api/flow/FlowScope.java
  subprojects/core-api/src/main/java/org/gradle/api/flow/RequestedTasksResult.java
  subprojects/core-api/src/main/java/org/gradle/api/flow/package-info.java
Labels: in:configuration-model, in:configuration-cache, @configuration-cache

#23239 Document Tooling API compatibility matrix
  subprojects/docs/src/docs/userguide/reference/third_party_integration.adoc
Labels: a:documentation

#23209 Undo type check in BSR#registerIfAbsent()
  subprojects/core/src/integTest/groovy/org/gradle/api/services/BuildServiceIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/services/internal/DefaultBuildServicesRegistry.java
Labels: @configuration-cache

#23252 Make `ArchiveOperations`, `ExecOperations` and `FileSystemOperations` available to flow actions
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheFlowScopeIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/flow/FlowScheduler.kt
  subprojects/core-api/src/main/java/org/gradle/api/flow/FlowAction.java
Labels: @configuration-cache

#23241 Documentation updates
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
Labels: a:documentation

#23259 Ignore missing annotations in `FlowParameters`
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheFlowScopeIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/flow/FlowParametersInstantiator.kt
Labels: @configuration-cache

#23256 Fix issue with ALWAYS cache cleanup not firing on session end
  subprojects/core/src/integTest/groovy/org/gradle/cache/internal/GradleUserHomeCleanupServiceIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/cache/DefaultCacheConfigurations.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/caching/DefaultArtifactCacheLockingManagerIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
Labels: a:bug

#23260 Allow flow actions to use build services registered in any order
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheFlowScopeIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/BuildScopeServices.java
Labels: @configuration-cache

#23265 Include any directory queried via `ConfigurableFileTree` at configuration time in configuration cache fingerprint
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOperationsIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildSrcChangesIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheFileCollectionIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/InstrumentedInputAccessListener.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/UndeclaredBuildInputListener.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintWriter.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/FileCollectionCodec.kt
  subprojects/core/src/main/java/org/gradle/internal/buildtree/BuildTreeScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/Instrumented.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/WorkerSharedProjectScopeServices.java
  subprojects/core/src/testFixtures/groovy/org/gradle/api/internal/file/TestFiles.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/AbstractFileCollection.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/CompositeFileCollection.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/DefaultFileCollectionFactory.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/FileCollectionFactory.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/DefaultConfigurableFileTree.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/FileCollectionObservationListener.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/FileTreeAdapter.java
  subprojects/file-collections/src/test/groovy/org/gradle/api/internal/file/collections/DefaultConfigurableFileTreeTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractIntegrationSpec.groovy
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/DefaultPrecompiledScriptPluginsSupport.kt
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerCachingSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy
Labels: in:configuration-cache, @configuration-cache

#23132 Move incremental build docs to a separate page
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/transform/TransformParameters.java
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyErrorIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/UnreadableCopyDestinationFixture.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/UntrackedTaskIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/TaskExecution.java
  subprojects/docs/src/docs/userguide/authoring-builds/incremental_build.adoc
  subprojects/docs/src/docs/userguide/authoring-builds/more_about_tasks.adoc
  subprojects/docs/src/docs/userguide/authoring-builds/organizing_gradle_projects.adoc
  subprojects/docs/src/docs/userguide/authoring-builds/working_with_files.adoc
  subprojects/docs/src/docs/userguide/build-cache/build_cache.adoc
  subprojects/docs/src/docs/userguide/build-cache/build_cache_concepts.adoc
  subprojects/docs/src/docs/userguide/build-cache/caching_android_projects.adoc
  subprojects/docs/src/docs/userguide/build-cache/common_caching_problems.adoc
  subprojects/docs/src/docs/userguide/core-plugins/base_plugin.adoc
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/dependency_resolution.adoc
  subprojects/docs/src/docs/userguide/dep-man/04-modeling-features/artifact_transforms.adoc
  subprojects/docs/src/docs/userguide/developing-plugins/implementing_gradle_plugins.adoc
  subprojects/docs/src/docs/userguide/extending-gradle/custom_tasks.adoc
  subprojects/docs/src/docs/userguide/jvm/application_plugin.adoc
  subprojects/docs/src/docs/userguide/jvm/building_java_projects.adoc
  subprojects/docs/src/docs/userguide/jvm/toolchains.adoc
  subprojects/docs/src/docs/userguide/migration/migrating_from_ant.adoc
  subprojects/docs/src/docs/userguide/migration/migrating_from_maven.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_4.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_5.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
  subprojects/docs/src/docs/userguide/reference/command_line_interface.adoc
  subprojects/docs/src/docs/userguide/running-builds/performance.adoc
  subprojects/docs/src/docs/userguide/troubleshooting/validation_problems.adoc
  subprojects/docs/src/main/resources/header.html
  subprojects/docs/src/samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/README.adoc
  subprojects/docs/src/snippets/tasks/incrementalBuild-incrementalBuildAdvanced/groovy/build.gradle
  subprojects/docs/src/snippets/tasks/incrementalBuild-incrementalBuildAdvanced/groovy/buildSrc/src/main/java/org/example/GitClone.java
  subprojects/docs/src/snippets/tasks/incrementalBuild-incrementalBuildAdvanced/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/tasks/incrementalBuild-incrementalBuildAdvanced/kotlin/buildSrc/src/main/java/org/example/GitClone.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/caching/CachingDisabledReasonCategory.java
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy
  subprojects/model-core/src/testFixtures/groovy/org/gradle/internal/reflect/validation/ValidationMessageChecker.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/AbstractPluginValidationIntegrationSpec.groovy
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/ValidatePlugins.java
Labels: a:documentation

#23214 Upgrade embedded Kotlin to 1.8.0-RC2 and use language/api 1.8
  build-logic-commons/gradle-plugin/build.gradle.kts
  build-logic/basics/src/main/kotlin/gradlebuild/basics/tasks/PackageListGenerator.kt
  build-logic/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
  build-logic/kotlin-dsl/src/main/kotlin/gradlebuild.kotlin-dsl-dependencies-embedded.gradle.kts
  build-logic/performance-testing/build.gradle.kts
  build-logic/uber-plugins/src/main/kotlin/gradlebuild.kotlin-library.gradle.kts
  gradle.properties
  gradle/verification-metadata.xml
  gradle/wrapper/gradle-wrapper.properties
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/library-versions.properties
  subprojects/configuration-cache/build.gradle.kts
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/api/kotlin_dsl.adoc
  subprojects/docs/src/docs/userguide/compatibility.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/samples/build-organization/structuring-software-projects/groovy/build-logic/android-application/src/main/groovy/com.example.android-application.gradle
  subprojects/docs/src/samples/build-organization/structuring-software-projects/groovy/build-logic/commons/src/main/groovy/com.example.commons.gradle
  subprojects/docs/src/samples/build-organization/structuring-software-projects/groovy/platforms/plugins-platform/build.gradle
  subprojects/docs/src/samples/build-organization/structuring-software-projects/kotlin/build-logic/android-application/src/main/kotlin/com.example.android-application.gradle.kts
  subprojects/docs/src/samples/build-organization/structuring-software-projects/kotlin/build-logic/commons/src/main/kotlin/com.example.commons.gradle.kts
  subprojects/docs/src/samples/build-organization/structuring-software-projects/kotlin/platforms/plugins-platform/build.gradle.kts
  subprojects/docs/src/snippets/configurationCache/samConversion/groovy/build.gradle
  subprojects/docs/src/snippets/configurationCache/samConversion/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/androidBuild/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/androidSingleBuild/kotlin/build.gradle.kts
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/NestedInputKotlinImplementationTrackingIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/KotlinGradlePluginVersions.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoKotlinJvmPluginAggregationTest.groovy
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/GradleKotlinDslRegressionsTest.kt
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/KotlinDslJvmTargetIntegrationTest.kt
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/KotlinDslNullnessIntegrationTest.kt
  subprojects/kotlin-dsl-plugins/build.gradle.kts
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinCompilerWarningsTest.kt
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/precompiled/PrecompiledScriptPluginTemplatesTest.kt
  subprojects/kotlin-dsl-plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslCompilerPlugins.kt
  subprojects/kotlin-dsl/build.gradle.kts
  subprojects/kotlin-dsl/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/KotlinBuildScriptIntegrationTest.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinBuildScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinInitScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinSettingsScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/normalization/KotlinApiClassExtractor.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/KotlinDslPluginSupport.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/KotlinCompiler.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/codegen/GradleApiExtensionsTest.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/support/KotlinCompilerTest.kt
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginSmokeTest.groovy
Labels: a:feature, in:building-gradle, in:kotlin-dsl

#23262 Make `Sign` task compatible with the configuration cache
  subprojects/architecture-test/src/changes/archunit_store/3c3e47be-b5ed-426a-8b9f-cfa00d3b09db
  subprojects/architecture-test/src/changes/archunit_store/provider-task-file-collection.txt
  subprojects/architecture-test/src/changes/archunit_store/provider-task-properties.txt
  subprojects/architecture-test/src/changes/archunit_store/public-api-mutable-file-collection.txt
  subprojects/architecture-test/src/changes/archunit_store/public-api-mutable-properties.txt
  subprojects/architecture-test/src/changes/archunit_store/public-api-mutable-text-resource.txt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/UnsupportedTypesCodecs.kt
  subprojects/functional/src/main/java/org/gradle/internal/serialization/Transient.java
  subprojects/security/build.gradle.kts
  subprojects/security/src/main/java/org/gradle/security/internal/gnupg/GnupgSignatory.java
  subprojects/signing/build.gradle.kts
  subprojects/signing/src/integTest/groovy/org/gradle/plugins/signing/InMemoryPgpSignatoryProviderIntegrationSpec.groovy
  subprojects/signing/src/integTest/groovy/org/gradle/plugins/signing/NoSigningCredentialsIntegrationSpec.groovy
  subprojects/signing/src/integTest/groovy/org/gradle/plugins/signing/SigningClosureBlockIntegrationSpec.groovy
  subprojects/signing/src/integTest/groovy/org/gradle/plugins/signing/SigningConfigurationsIntegrationSpec.groovy
  subprojects/signing/src/integTest/groovy/org/gradle/plugins/signing/SigningConfigurationsWithGpgCmdIntegrationSpec.groovy
  subprojects/signing/src/integTest/groovy/org/gradle/plugins/signing/SigningDistributionsIntegrationSpec.groovy
  subprojects/signing/src/integTest/groovy/org/gradle/plugins/signing/SigningPublicationsIntegrationSpec.groovy
  subprojects/signing/src/integTest/groovy/org/gradle/plugins/signing/SigningSamplesSpec.groovy
  subprojects/signing/src/integTest/groovy/org/gradle/plugins/signing/SigningTasksIntegrationSpec.groovy
  subprojects/signing/src/integTest/groovy/org/gradle/plugins/signing/SigningWithGpgCmdIntegrationSpec.groovy
  subprojects/signing/src/main/java/org/gradle/plugins/signing/Sign.java
  subprojects/signing/src/main/java/org/gradle/plugins/signing/Signature.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildSanityCheckConfigurationCacheSmokeTest.groovy
Labels: in:signing-plugin, @configuration-cache

#23270 Provide information on docs moved to Incremental Build
  subprojects/docs/src/docs/userguide/authoring-builds/more_about_tasks.adoc
Labels: a:documentation

#23254 Move Asciidoc extensions into the project
  .teamcity/subprojects.json
  build-logic/basics/src/main/kotlin/gradlebuild.repositories.gradle.kts
  gradle/verification-metadata.xml
  settings.gradle.kts
  subprojects/docs-asciidoctor-extensions-base/build.gradle.kts
  subprojects/docs-asciidoctor-extensions-base/src/main/java/org/gradle/docs/asciidoctor/GradleDocsAsciidoctorExtensionRegistry.java
  subprojects/docs-asciidoctor-extensions-base/src/main/java/org/gradle/docs/asciidoctor/GuidesContributeIncludeProcessor.java
  subprojects/docs-asciidoctor-extensions-base/src/main/java/org/gradle/docs/asciidoctor/HeaderInjectingPostprocessor.java
  subprojects/docs-asciidoctor-extensions-base/src/main/java/org/gradle/docs/asciidoctor/MetadataDocinfoProcessor.java
  subprojects/docs-asciidoctor-extensions-base/src/main/java/org/gradle/docs/asciidoctor/MultiLanguageSamplesDocinfoProcessor.java
  subprojects/docs-asciidoctor-extensions-base/src/main/java/org/gradle/docs/asciidoctor/NavigationDocinfoProcessor.java
  subprojects/docs-asciidoctor-extensions-base/src/main/java/org/gradle/docs/asciidoctor/SampleIncludeProcessor.java
  subprojects/docs-asciidoctor-extensions-base/src/main/resources/META-INF/services/org.asciidoctor.jruby.extension.spi.ExtensionRegistry
  subprojects/docs-asciidoctor-extensions-base/src/main/resources/multi-language-samples.css
  subprojects/docs-asciidoctor-extensions-base/src/main/resources/multi-language-samples.js
  subprojects/docs-asciidoctor-extensions-base/src/test/groovy/org/gradle/docs/asciidoctor/GuidesContributeIncludeProcessorTest.groovy
  subprojects/docs-asciidoctor-extensions-base/src/test/groovy/org/gradle/docs/asciidoctor/SampleIncludeProcessorTest.groovy
  subprojects/docs-asciidoctor-extensions/build.gradle.kts
  subprojects/docs-asciidoctor-extensions/src/main/java/org/gradle/docs/asciidoctor/GradleDocsHtmlAsciidoctorExtensionRegistry.java
  subprojects/docs-asciidoctor-extensions/src/main/resources/META-INF/services/org.asciidoctor.jruby.extension.spi.ExtensionRegistry
  subprojects/docs/build.gradle
Labels: in:documentation-infrastructure

#23275 Update wrapper to gradle-8.0-20221222145522+0000
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore

#23123 Add instrumenting agent
  .github/CODEOWNERS
  .teamcity/subprojects.json
  build-logic/integration-testing/src/main/kotlin/gradlebuild/integrationtests/model/GradleDistribution.kt
  build-logic/packaging/src/main/kotlin/gradlebuild.distributions.gradle.kts
  build-logic/packaging/src/main/kotlin/gradlebuild/packaging/GradleDistributionSpecs.kt
  settings.gradle.kts
  subprojects/base-services/src/main/java/org/gradle/internal/agents/AgentControl.java
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/AbstractInjectedClasspathInstrumentationStrategy.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/ConfigurationCacheInjectedClasspathInstrumentationStrategy.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/VintageInjectedClasspathInstrumentationStrategy.kt
  subprojects/distributions-basics/build.gradle.kts
  subprojects/distributions-core/build.gradle.kts
  subprojects/distributions-full/build.gradle.kts
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DistributionIntegrationSpec.groovy
  subprojects/distributions-jvm/build.gradle.kts
  subprojects/distributions-native/build.gradle.kts
  subprojects/distributions-publishing/build.gradle.kts
  subprojects/instrumentation-agent/build.gradle.kts
  subprojects/instrumentation-agent/src/integTest/groovy/org/gradle/instrumentation/agent/AgentApplicationTest.groovy
  subprojects/instrumentation-agent/src/main/java/org/gradle/instrumentation/agent/Agent.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/daemon/DaemonContextParser.java
  subprojects/internal-integ-testing/src/test/groovy/org/gradle/integtests/fixtures/daemon/DaemonContextParserTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/SystemClassLoaderTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/DaemonJvmSettingsIntegrationTest.groovy
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/client/DefaultDaemonStarter.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/configuration/BuildProcess.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/configuration/DaemonBuildOptions.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/configuration/DaemonParameters.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/context/DaemonCompatibilitySpec.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/context/DaemonContext.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/context/DaemonContextBuilder.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/context/DefaultDaemonContext.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/DaemonServices.java
  subprojects/launcher/src/test/groovy/org/gradle/launcher/daemon/client/DefaultDaemonConnectorTest.groovy
  subprojects/launcher/src/test/groovy/org/gradle/launcher/daemon/context/DaemonCompatibilitySpecSpec.groovy
  subprojects/launcher/src/test/groovy/org/gradle/launcher/daemon/protocol/DaemonStatusAndErrorReportingTest.groovy
  subprojects/launcher/src/test/groovy/org/gradle/launcher/daemon/registry/DaemonRegistryServicesTest.groovy
  subprojects/launcher/src/test/groovy/org/gradle/launcher/daemon/server/DaemonRegistryUnavailableExpirationStrategyTest.groovy
Labels: @configuration-cache

#23280 Let `signing` plugin publish signatures with configuration caching
  subprojects/signing/src/integTest/groovy/org/gradle/plugins/signing/SigningIntegrationSpec.groovy
  subprojects/signing/src/integTest/groovy/org/gradle/plugins/signing/SigningPublicationsIntegrationSpec.groovy
  subprojects/signing/src/integTest/groovy/org/gradle/plugins/signing/SigningSamplesSpec.groovy
  subprojects/signing/src/main/java/org/gradle/plugins/signing/Sign.java
  subprojects/signing/src/main/java/org/gradle/plugins/signing/Signature.java
  subprojects/signing/src/main/java/org/gradle/plugins/signing/SigningExtension.java
Labels: in:signing-plugin, @configuration-cache

#23284 Fix resolution of dynamic versions with Ivy file repositories and configuration cache
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheDependencyResolutionFeaturesIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/extensions/VirtualFileSystemExtensions.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprint.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintChecker.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintController.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintWriter.kt
  subprojects/configuration-cache/src/test/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintCheckerTest.kt
  subprojects/core/src/testFixtures/groovy/org/gradle/api/internal/file/TestFiles.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ivy/IvyDynamicRevisionMultiRepoResolveIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementBuildScopeServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementGlobalScopeServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/transport/RepositoryTransportFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resource/transport/file/FileTransport.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/transport/RepositoryTransportFactoryTest.groovy
  subprojects/docs/src/docs/release/notes.md
  subprojects/resources/src/main/java/org/gradle/internal/resource/local/DefaultLocallyAvailableExternalResource.java
  subprojects/resources/src/main/java/org/gradle/internal/resource/local/FileResourceConnector.java
  subprojects/resources/src/main/java/org/gradle/internal/resource/local/FileResourceListener.java
  subprojects/resources/src/main/java/org/gradle/internal/resource/local/FileResourceRepository.java
  subprojects/resources/src/main/java/org/gradle/internal/resource/local/LocalFileStandInExternalResource.java
  subprojects/resources/src/main/java/org/gradle/internal/resource/local/LocallyAvailableExternalResource.java
Labels: @configuration-cache, in:dependency-resolution

#23228 Versions catalog: fail fast if an alias contains 'class'
  subprojects/core/src/testFixtures/groovy/org/gradle/api/internal/catalog/problems/VersionCatalogErrorMessages.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/VersionCatalogExtensionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/DefaultVersionCatalogBuilder.java
Labels: from:contributor

#23282 Capture dependency verification fingerprint
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationIntegrityCheckIntegTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationSignatureCheckIntegTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementBuildScopeServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/StartParameterResolutionOverride.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/ChecksumAndSignatureVerificationOverride.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/signatures/DefaultSignatureVerificationServiceFactory.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/ResolveIvyFactoryTest.groovy
Labels: @configuration-cache

#23251 Add documentation about temporary compile outputs
  subprojects/docs/src/docs/userguide/jvm/java_plugin.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
Labels: @execution, a:documentation

#23246 Ensure all version catalog dependency properties are copied
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/ArtifactDeclarationIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/VersionCatalogExtensionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/AbstractExternalModuleDependency.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultExternalModuleDependency.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultMinimalDependency.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultMinimalDependencyVariant.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultMutableMinimalDependency.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultMutableVersionConstraint.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/notations/DependencyNotationParser.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/dependencies/DefaultImmutableVersionConstraintTest.groovy
Labels: a:bug

#23301 Fix `--write-verification-metadata` when configuration cache is enabled
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheDependencyResolutionFeaturesIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultConfigurationCache.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ConfigurationCacheProblems.kt
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/StartParameterResolutionOverride.java
Labels: @configuration-cache, in:dependency-verification

#22462 Use TeamCity's Parallel Testing feature
  .teamcity/src/main/kotlin/common/Os.kt
  .teamcity/src/main/kotlin/configurations/DocsTest.kt
  .teamcity/src/main/kotlin/configurations/FunctionalTest.kt
  .teamcity/src/main/kotlin/model/FunctionalTestBucketGenerator.kt
  .teamcity/src/main/kotlin/model/FunctionalTestBucketProvider.kt
  .teamcity/src/main/kotlin/model/GradleSubprojectProvider.kt
  .teamcity/src/main/kotlin/projects/StageProject.kt
  .teamcity/src/test/kotlin/CIConfigIntegrationTests.kt
  .teamcity/test-buckets.json
Labels: @dev-productivity

#23304 Fix links
  subprojects/docs/src/docs/release/notes.md
Labels: a:documentation

#23308 Backout changes for Codenarc to use worker API
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/architecture-test/src/changes/archunit_store/3c3e47be-b5ed-426a-8b9f-cfa00d3b09db
  subprojects/architecture-test/src/changes/archunit_store/provider-task-file-collection.txt
  subprojects/architecture-test/src/changes/archunit_store/provider-task-properties.txt
  subprojects/architecture-test/src/changes/archunit_store/provider-text-resource.txt
  subprojects/architecture-test/src/changes/archunit_store/public-api-mutable-file-collection.txt
  subprojects/architecture-test/src/changes/archunit_store/public-api-mutable-properties.txt
  subprojects/architecture-test/src/changes/archunit_store/public-api-mutable-text-resource.txt
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcCrossVersionIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcPluginToolchainsIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcPluginVersionIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcTestFixture.groovy
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CodeNarc.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CodeNarcPlugin.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/CodeNarcAction.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/CodeNarcActionParameters.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/CodeNarcInvoker.groovy
  subprojects/docs/src/docs/dsl/org.gradle.api.plugins.quality.CodeNarc.xml
  subprojects/docs/src/docs/release/notes.md
Labels: a:bug, in:codenarc-plugin

#23310 Merge release7x into release
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/ArtifactDeclarationIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/VersionCatalogExtensionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/AbstractExternalModuleDependency.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultExternalModuleDependency.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultMinimalDependency.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultMinimalDependencyVariant.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultMutableMinimalDependency.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultMutableVersionConstraint.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/notations/DependencyNotationParser.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/dependencies/DefaultImmutableVersionConstraintTest.groovy
Labels: a:regression

#23312 Merge release to master
  released-versions.json
  subprojects/architecture-test/src/changes/archunit_store/3c3e47be-b5ed-426a-8b9f-cfa00d3b09db
  subprojects/architecture-test/src/changes/archunit_store/provider-task-file-collection.txt
  subprojects/architecture-test/src/changes/archunit_store/provider-task-properties.txt
  subprojects/architecture-test/src/changes/archunit_store/provider-text-resource.txt
  subprojects/architecture-test/src/changes/archunit_store/public-api-mutable-properties.txt
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcCrossVersionIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcPluginToolchainsIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcPluginVersionIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcTestFixture.groovy
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CodeNarc.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CodeNarcPlugin.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/CodeNarcAction.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/CodeNarcActionParameters.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/CodeNarcInvoker.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/ArtifactDeclarationIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/VersionCatalogExtensionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/AbstractExternalModuleDependency.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultExternalModuleDependency.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultMinimalDependency.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultMinimalDependencyVariant.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultMutableMinimalDependency.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/DefaultMutableVersionConstraint.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/notations/DependencyNotationParser.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/dependencies/DefaultImmutableVersionConstraintTest.groovy
  subprojects/docs/src/docs/dsl/org.gradle.api.plugins.quality.CodeNarc.xml
  subprojects/docs/src/docs/release/notes.md
Labels: a:chore

#22517 added publishToMavenLocal behaviour in docs
  subprojects/docs/src/docs/userguide/dep-man/06-publishing/publishing_maven.adoc
Labels: in:publishing-plugins, a:documentation, from:contributor

#23317 Remove AbstractTask.getOwner() and getProjectUnchecked()
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheServices.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultBuildTreeModelControllerServices.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/TaskExecutionAccessCheckers.kt
  subprojects/core/src/main/java/org/gradle/api/internal/AbstractTask.java
  subprojects/core/src/main/java/org/gradle/api/internal/TaskInternal.java
  subprojects/core/src/main/java/org/gradle/execution/SelectedTaskExecutionAction.java
  subprojects/core/src/main/java/org/gradle/execution/plan/LocalTaskNode.java
  subprojects/core/src/main/java/org/gradle/execution/taskgraph/DefaultTaskExecutionGraph.java
  subprojects/core/src/test/groovy/org/gradle/execution/SelectedTaskExecutionActionTest.groovy
Labels: in:configuration-cache, @configuration-cache

#23319 Wrapper update
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore

#23322 jsoup upgrade
  build-logic/build-platform/build.gradle.kts
  subprojects/distributions-dependencies/build.gradle.kts
Labels: a:chore

#22344 Fix misleading javadoc in Manifest and ManifestMergeSpec
  subprojects/platform-jvm/src/main/java/org/gradle/api/java/archives/Manifest.java
  subprojects/platform-jvm/src/main/java/org/gradle/api/java/archives/ManifestMergeSpec.java
Labels: a:documentation, from:contributor

#23321 Fix user manual links to Incremental Build chapter
  subprojects/docs/README.md
  subprojects/docs/src/docs/userguide/userguide_single.adoc
Labels: a:documentation

#23330 Only require ordinal nodes that are actually depended on
  subprojects/core/src/main/java/org/gradle/execution/plan/DefaultFinalizedExecutionPlan.java
  subprojects/core/src/main/java/org/gradle/execution/plan/OrdinalGroup.java
  subprojects/core/src/main/java/org/gradle/execution/plan/OrdinalNodeAccess.java
Labels: a:bug

#23288 Fix the issue that missing 'archiveName' attribute in eclipse wtp.
  subprojects/architecture-test/src/changes/archunit_store/public-api-mutable-properties.txt
  subprojects/ide/src/integTest/resources/org/gradle/plugins/ide/eclipse/EclipseIntegrationTest/canCreateAndDeleteMetaData/expectedFiles/commonWtpComponent.xml
  subprojects/ide/src/integTest/resources/org/gradle/plugins/ide/eclipse/EclipseIntegrationTest/canCreateAndDeleteMetaData/expectedFiles/webAppJava6WtpComponent.xml
  subprojects/ide/src/integTest/resources/org/gradle/plugins/ide/eclipse/EclipseIntegrationTest/canCreateAndDeleteMetaData/expectedFiles/webserviceWtpComponent.xml
  subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/WbDependentModule.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/internal/WtpComponentFactory.java
  subprojects/ide/src/test/groovy/org/gradle/plugins/ide/eclipse/model/WbDependentModuleTest.groovy
  subprojects/ide/src/test/groovy/org/gradle/plugins/ide/eclipse/model/WtpComponentTest.groovy
  subprojects/ide/src/test/resources/org/gradle/plugins/ide/eclipse/model/customOrgEclipseWstCommonComponent.xml
Labels: from:contributor

#23314 Trim common indent when rendering snippets in docs
  subprojects/docs-asciidoctor-extensions-base/src/main/java/org/gradle/docs/asciidoctor/SampleIncludeProcessor.java
  subprojects/docs-asciidoctor-extensions-base/src/test/groovy/org/gradle/docs/asciidoctor/SampleIncludeProcessorTest.groovy
Labels: in:documentation-infrastructure
