Repository gradle/gradle, pull requests merged in 2022-05, with the labels that each got.

#20613 #20612 remove unmappable character (0x9D)
  subprojects/build-operations/src/main/java/org/gradle/internal/operations/BuildOperationType.java
Labels: from:contributor

#20148 Select artifacts from all available variants
  .teamcity/performance-tests-ci.json
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/LocalFileDependencyBackedArtifactSetCodec.kt
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/derived/DerivedVariantsResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/derived/MultiProjectVariantResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/projectmodule/ProjectArtifactSetResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/projectmodule/ProjectDependencyResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/ArtifactBackedResolvedVariant.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/DefaultArtifactSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/LocalFileDependencyBackedArtifactSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/ResolvedVariant.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/ResolvedVariantSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/AttributeMatchingVariantSelector.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/MetadataSourcedComponentArtifacts.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/maven/RealisedMavenModuleResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/AttributeConfigurationSelector.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/ArtifactBackedResolvedVariantTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/DefaultArtifactSetTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/AttributeMatchingVariantSelectorSpec.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/DefaultArtifactTransformsTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidStudioPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ExcludeRuleMergingPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/LargeDependencyGraphPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIDEModelPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIncrementalExecutionPerformanceTest.groovy
Labels: @core

#20637 Use openjdk for windows performance tests
  .teamcity/src/main/kotlin/common/Os.kt
Labels: @dev-productivity

#20635 Rebaseline two performance scenarios with 1% regression
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaFirstUsePerformanceTest.groovy
Labels: @dev-productivity

#20636 Use openjdk for windows performance tests
  .teamcity/src/main/kotlin/common/Os.kt
Labels: @dev-productivity

#20388 Version catalog builders should not accept multiple `toml` files
  subprojects/core-api/src/main/java/org/gradle/api/initialization/dsl/VersionCatalogBuilder.java
  subprojects/core/src/main/java/org/gradle/api/internal/catalog/problems/VersionCatalogProblemId.java
  subprojects/core/src/testFixtures/groovy/org/gradle/api/internal/catalog/problems/VersionCatalogErrorMessages.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/TomlDependenciesExtensionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/DefaultVersionCatalogBuilder.java
  subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/platforms.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/docs/userguide/troubleshooting/version_catalog_problems.adoc
  subprojects/plugins/src/integTest/groovy/org/gradle/catalog/VersionCatalogResolveIntegrationTest.groovy
Labels: in:dependency-version-catalog, @support

#20634 Restore AllExceptIgnoredTestRunnerBuilder
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/junit/AllExceptIgnoredTestRunnerBuilder.java
Labels: @dev-productivity

#20606 Document using dependency resolution results as task inputs
  subprojects/docs/build.gradle
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/authoring-builds/more_about_tasks.adoc
  subprojects/docs/src/samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/README.adoc
  subprojects/docs/src/samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/common/dependency-reports/src/main/java/com/example/DependencyReportsPlugin.java
  subprojects/docs/src/samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/common/dependency-reports/src/main/java/com/example/GraphResolvedComponents.java
  subprojects/docs/src/samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/common/dependency-reports/src/main/java/com/example/GraphResolvedComponentsAndFiles.java
  subprojects/docs/src/samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/common/dependency-reports/src/main/java/com/example/ListResolvedArtifacts.java
  subprojects/docs/src/samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/groovy/build.gradle
  subprojects/docs/src/samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/groovy/dependency-reports/build.gradle
  subprojects/docs/src/samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/groovy/dependency-reports/settings.gradle
  subprojects/docs/src/samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/groovy/list/build.gradle
  subprojects/docs/src/samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/groovy/settings.gradle
  subprojects/docs/src/samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/groovy/utilities/build.gradle
  subprojects/docs/src/samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/kotlin/build.gradle.kts
  subprojects/docs/src/samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/kotlin/dependency-reports/build.gradle.kts
  subprojects/docs/src/samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/kotlin/dependency-reports/settings.gradle.kts
  subprojects/docs/src/samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/kotlin/list/build.gradle.kts
  subprojects/docs/src/samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/kotlin/settings.gradle.kts
  subprojects/docs/src/samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/kotlin/utilities/build.gradle.kts
  subprojects/docs/src/samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/tests/dependencyReports.sample.conf
  subprojects/docs/src/samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/tests/graphResolvedComponents.out
  subprojects/docs/src/samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/tests/graphResolvedComponentsAndFiles.out
  subprojects/docs/src/samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/tests/listResolvedArtifacts.out
Labels: @configuration-cache

#20589 Make cache-miss-monitor CC compatible
  build-logic-commons/gradle-plugin/src/main/kotlin/CacheMissMonitorBuildService.kt
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.cache-miss-monitor.gradle.kts
Labels: @dev-productivity

#20549 Add public API definition for IntelliJ
  .idea/scopes/Gradle_public_API.xml
  build-logic/basics/src/main/kotlin/gradlebuild/basics/PublicApi.kt
Labels: @execution

#20655 Upgrade CodeNarc to 3.0.1
  build-logic-commons/code-quality-rules/build.gradle.kts
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.code-quality.gradle.kts
  build-logic/build-platform/build.gradle.kts
Labels: @execution

#20664 Make `Transformer<OUT, IN>` lambdas compatible with the configuration cache
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheLambdaIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingTransformer.java
Labels: in:configuration-cache, @configuration-cache

#20669 Fix NPE in build-logic-only build
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.cache-miss-monitor.gradle.kts
Labels: @dev-productivity

#20585 Sort script application operations by start time in IsolatedProjectsToolingApiParallelConfigurationIntegrationTest
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/isolated/IsolatedProjectsFixture.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/isolated/IsolatedProjectsToolingApiParallelConfigurationIntegrationTest.groovy
Labels: flaky-fix-it

#20648 Support building on M1 Mac
  .teamcity/src/main/kotlin/common/Jvm.kt
  .teamcity/src/main/kotlin/common/JvmVendor.kt
  .teamcity/src/main/kotlin/common/Os.kt
  .teamcity/src/main/kotlin/common/extensions.kt
  .teamcity/src/main/kotlin/common/performance-test-extensions.kt
  .teamcity/src/main/kotlin/configurations/FlakyTestQuarantine.kt
  .teamcity/src/main/kotlin/configurations/FunctionalTest.kt
  .teamcity/src/main/kotlin/configurations/GradleBuildConfigurationDefaults.kt
  .teamcity/src/main/kotlin/model/CIBuildModel.kt
  .teamcity/src/main/kotlin/model/FunctionalTestBucketGenerator.kt
  .teamcity/src/main/kotlin/util/AdHocPerformanceScenario.kt
  .teamcity/src/main/kotlin/util/RerunFlakyTest.kt
  .teamcity/test-buckets.json
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/CppApplicationInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/CppLibraryInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/SwiftApplicationInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/SwiftLibraryInitIntegrationTest.groovy
  subprojects/docs/build.gradle
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/visualstudio/NativeIdeSamplesIntegrationTest.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/xcode/AbstractXcodeCppProjectIntegrationTest.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/xcode/XcodeMultipleCppProjectIntegrationTest.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/xcode/XcodeMultipleSwiftProjectIntegrationTest.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/xcode/XcodeSingleCppProjectIntegrationTest.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/xcode/fixtures/AbstractXcodeIntegrationSpec.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/DifferentJnaVersionInPluginIntegrationSpec.groovy
  subprojects/internal-testing/src/main/groovy/org/gradle/util/TestPrecondition.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/language/cpp/CppMissingToolchainIntegrationTest.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/language/cpp/CppToolChainChangesIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/ProcessCrashHandlingIntegrationTest.groovy
  subprojects/platform-native/src/integTest/groovy/org/gradle/nativeplatform/NativeDependentComponentsReportIntegrationTest.groovy
  subprojects/platform-native/src/testFixtures/groovy/org/gradle/nativeplatform/fixtures/AbstractInstalledToolChainIntegrationSpec.groovy
  subprojects/platform-native/src/testFixtures/groovy/org/gradle/nativeplatform/fixtures/AvailableToolChains.java
  subprojects/resources-s3/src/integTest/groovy/org/gradle/integtests/resource/s3/maven/MavenPublishS3IntegrationTest.groovy
  subprojects/tooling-native/src/crossVersionTest/groovy/org/gradle/language/cpp/tooling/r410/CppModelCrossVersionSpec.groovy
  subprojects/tooling-native/src/crossVersionTest/groovy/org/gradle/language/cpp/tooling/r52/CppModelCrossVersionSpec.groovy
Labels: @dev-productivity

#20682 Workaround for srcDistribution causing up-to-date jar tasks
  build-logic/packaging/src/main/kotlin/gradlebuild.distributions.gradle.kts
Labels: @dev-productivity

#20697 Use toolchain for build-logic build
  build-logic-commons/gradle-plugin/src/main/kotlin/common.kt
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.build-logic.groovy-dsl-gradle-plugin.gradle.kts
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.build-logic.kotlin-dsl-gradle-plugin.gradle.kts
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
Labels: @dev-productivity

#20687 Do not store snapshot if tasks changed locations in between
  subprojects/core/src/testFixtures/groovy/org/gradle/api/internal/file/TestFiles.java
  subprojects/core/src/testFixtures/groovy/org/gradle/api/internal/file/TestVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingNotSupportedVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingNotSupportedVirtualFileSystemTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystemTest.groovy
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SnapshotHierarchy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/VfsRelativePath.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/impl/DirectorySnapshotter.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/VirtualFileSystem.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultSnapshotHierarchy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/VersionHierarchy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/VersionHierarchyRoot.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/VfsRootReference.java
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterAsDirectoryWalkerTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterStatisticsTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/vfs/impl/AbstractVirtualFileSystemTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/vfs/impl/DefaultSnapshotHierarchyTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/vfs/impl/VersionHierarchyRootTest.groovy
Labels: @execution

#20703 Update default test libs used by test suites to latest stable versions
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testsuites/TestSuitesIntegrationTest.groovy
Labels: in:test-suites

#20677 Fix #20630: Map Maven compile-scope dependencies to Gradle api configuration
  subprojects/build-init/src/main/java/org/gradleinternal/buildinit/plugins/internal/maven/Maven2Gradle.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/core-plugins/build_init_plugin.adoc
Labels: a:bug, @core

#20710 Merge release into master
  build-logic/packaging/src/main/kotlin/gradlebuild.distributions.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  released-versions.json
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheLambdaIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/isolated/IsolatedProjectsFixture.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/isolated/IsolatedProjectsToolingApiParallelConfigurationIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/AbstractCommandLineOrderTaskIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/DestroyerTaskCommandLineOrderIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java
  subprojects/core/src/main/java/org/gradle/execution/plan/Node.java
  subprojects/core/src/main/java/org/gradle/execution/plan/OrdinalNodeAccess.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingTransformer.java
  subprojects/core/src/test/groovy/org/gradle/execution/plan/DefaultExecutionPlanParallelTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/api/internal/file/TestFiles.java
  subprojects/core/src/testFixtures/groovy/org/gradle/api/internal/file/TestVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingNotSupportedVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingNotSupportedVirtualFileSystemTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystemTest.groovy
  subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/AbstractIdeLifecycleIntegrationTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaFirstUsePerformanceTest.groovy
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SnapshotHierarchy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/VfsRelativePath.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/impl/DirectorySnapshotter.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/VirtualFileSystem.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/AbstractVirtualFileSystem.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultSnapshotHierarchy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/VersionHierarchy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/VersionHierarchyRoot.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/VfsRootReference.java
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterAsDirectoryWalkerTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterStatisticsTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/vfs/impl/AbstractVirtualFileSystemTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/vfs/impl/DefaultSnapshotHierarchyTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/vfs/impl/VersionHierarchyRootTest.groovy
Labels: @dev-productivity

#20711 Split AndroidSantaTrackerSmokeTest & use TeamCity parallel tests
  .teamcity/pom.xml
  .teamcity/src/main/kotlin/configurations/SmokeTests.kt
  .teamcity/src/main/kotlin/model/CIBuildModel.kt
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy
Labels: @dev-productivity

#20714 Update tested AGP versions
  gradle/dependency-management/agp-versions.properties
Labels: @configuration-cache

#20716 Accept CACHE_MISS for compilation tasks on M1 mac
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.cache-miss-monitor.gradle.kts
Labels: @dev-productivity

#20715 Fix sibling versioning for optimistic locking
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/VersionHierarchy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/VersionHierarchyRoot.java
  subprojects/snapshots/src/test/groovy/org/gradle/internal/vfs/impl/AbstractVirtualFileSystemTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/vfs/impl/VersionHierarchyRootTest.groovy
Labels: @execution

#20732 Increase internal socket timeout to 60s
  gradle.properties
Labels: @dev-productivity

#20743 Improve performance of missing dependency detection
  subprojects/core/src/main/java/org/gradle/execution/plan/LocalTaskNodeExecutor.java
Labels: @execution

#20738 Introduce NodeComparator to centralize Node comparisons
  subprojects/composite-builds/src/test/groovy/org/gradle/composite/internal/DefaultIncludedBuildTaskGraphParallelTest.groovy
  subprojects/core/src/main/java/org/gradle/execution/plan/ActionNode.java
  subprojects/core/src/main/java/org/gradle/execution/plan/CreationOrderedNode.java
  subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java
  subprojects/core/src/main/java/org/gradle/execution/plan/LocalTaskNode.java
  subprojects/core/src/main/java/org/gradle/execution/plan/Node.java
  subprojects/core/src/main/java/org/gradle/execution/plan/NodeComparator.java
  subprojects/core/src/main/java/org/gradle/execution/plan/NodeSets.java
  subprojects/core/src/main/java/org/gradle/execution/plan/OrdinalNode.java
  subprojects/core/src/main/java/org/gradle/execution/plan/ResolveMutationsNode.java
  subprojects/core/src/main/java/org/gradle/execution/plan/TaskInAnotherBuild.java
  subprojects/core/src/main/java/org/gradle/execution/plan/TaskNode.java
  subprojects/core/src/test/groovy/org/gradle/execution/plan/DefaultExecutionPlanParallelTest.groovy
  subprojects/core/src/test/groovy/org/gradle/execution/plan/ExecutionNodeAccessHierarchyTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationNode.java
Labels: a:chore, @configuration-cache

#20737 Explicitly set PTS server
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
Labels: @dev-productivity

#20731 Add pgp.mit.edu to default key servers
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/DefaultKeyServers.java
  subprojects/docs/src/docs/release/notes.md
Labels: in:dependency-verification, from:contributor

#20729 No stacktrace check for build-android-app
  subprojects/docs/src/docsTest/java/org/gradle/docs/samples/BaseSamplesTest.java
  subprojects/docs/src/docsTest/java/org/gradle/docs/samples/IntegrationTestSamplesExecutor.java
  subprojects/docs/src/samples/build-organization/structuring-software-projects/tests/build-android-app.sample.conf
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/logging/StackTraceSanitizingOutputNormalizer.groovy
  subprojects/internal-integ-testing/src/test/groovy/org/gradle/integtests/fixtures/logging/StackTraceSanitizingOutputNormalizerTest.groovy
Labels: @dev-productivity

#20756 Add more builds to M1
  .teamcity/src/main/kotlin/common/Os.kt
  .teamcity/src/main/kotlin/common/performance-test-extensions.kt
  .teamcity/src/main/kotlin/model/CIBuildModel.kt
  .teamcity/src/main/kotlin/util/AdHocPerformanceScenario.kt
  .teamcity/src/main/kotlin/util/RerunFlakyTest.kt
  .teamcity/src/main/kotlin/util/UtilPerformanceProject.kt
  .teamcity/src/main/kotlin/util/UtilProject.kt
Labels: @dev-productivity

#20768 Rebaseline performance test with 1% regression
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ArchiveTreePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/TaskCreationPerformanceTest.groovy
Labels: @dev-productivity

#20769 Revert socket timeout increase
  gradle.properties
Labels: @dev-productivity

#20772 Fix regex performance issue in AbstractCheckOrUpdateContributorsInReleaseNotes
  build-logic/build-update-utils/src/main/kotlin/gradlebuild/buildutils/tasks/AbstractCheckOrUpdateContributorsInReleaseNotes.kt
  build-logic/build-update-utils/src/main/kotlin/gradlebuild/buildutils/tasks/UpdateContributorsInReleaseNotes.kt
  subprojects/docs/src/docs/release/notes-template.md
Labels: @dev-productivity

#20771 Rebaseline performance test scenarios after 7.5 release
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidStudioPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingJavaPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingNativePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingSwiftPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/DeprecationCreationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ExcludeRuleMergingPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/IdeIntegrationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/LargeDependencyGraphPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ParallelDownloadsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/RichConsolePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/VerboseTestOutputPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaCleanAssemblePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationCachePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaDependencyReportPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaFirstUsePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIDEModelPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIncrementalExecutionPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaTasksPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeBuildDependentsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeCleanBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/RealWorldNativePluginPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftCleanBuildPerformanceTest.groovy
Labels: @dev-productivity

#20776 Simplify documentation for missing inputs
  subprojects/docs/src/docs/userguide/troubleshooting/validation_problems.adoc
  subprojects/docs/src/snippets/tasks/customTaskWithMissingFileProperty/groovy/build.gradle
  subprojects/docs/src/snippets/tasks/customTaskWithMissingFileProperty/kotlin/build.gradle.kts
Labels: @execution

#20777 Enable configuration caching for newly compatible tasks in the Gradle build
  build-logic-settings/build-logic-settings-plugin/src/main/kotlin/gradlebuild.internal.cc-experiment.settings.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: in:building-gradle, @configuration-cache

#20796 Upgrade test-distribution/test-retry plugin
  build-logic/build-platform/build.gradle.kts
  gradle/verification-metadata.xml
  settings.gradle.kts
Labels: @dev-productivity

#20792 Remove unnecessary empty dir check action
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.code-quality.gradle.kts
Labels: @dev-productivity

#20781 Extract determineExecutionPlan algorithm to a separate class
  subprojects/core/src/integTest/groovy/org/gradle/api/FinalizerTaskIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java
  subprojects/core/src/main/java/org/gradle/execution/plan/DetermineExecutionPlanAction.java
  subprojects/core/src/main/java/org/gradle/execution/plan/OrdinalNodeAccess.java
Labels: @configuration-cache, a:investigation

#20073 Make TestLauncher be able to run tasks along with tests
  subprojects/docs/src/docs/release/notes.md
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/action/BuildActionSerializer.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/action/TestExecutionRequestAction.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/test/ProviderInternalTestExecutionRequest.java
  subprojects/launcher/src/test/groovy/org/gradle/tooling/internal/provider/action/BuildActionSerializerTest.groovy
  subprojects/tooling-api-builders/src/main/java/org/gradle/tooling/internal/provider/runner/TestExecutionBuildConfigurationAction.java
  subprojects/tooling-api-builders/src/test/groovy/org/gradle/tooling/internal/provider/runner/TestExecutionBuildConfigurationActionTest.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r76/TestLauncherTaskExecutionCrossVersionSpec.groovy
  subprojects/tooling-api/src/main/java/org/gradle/tooling/TestLauncher.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/DefaultTestLauncher.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/TestExecutionRequest.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/protocol/test/InternalTestExecutionRequest.java
Labels: @support

#20793 Add 'coverageArch' build scan custom value and FlakyTestQuarantineMacOsM1 build
  .teamcity/src/main/kotlin/common/extensions.kt
  .teamcity/src/main/kotlin/configurations/FlakyTestQuarantine.kt
  .teamcity/src/main/kotlin/configurations/FunctionalTest.kt
  .teamcity/src/main/kotlin/model/CIBuildModel.kt
  .teamcity/src/main/kotlin/util/RerunFlakyTest.kt
Labels: @dev-productivity

#20817 Remove interfaces from list of irrelevant task superclasses
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/beans/BeanSchema.kt
Labels: a:chore, @configuration-cache

#20816 Simplify `DefaultVersionCatalogBuilder` integration with the config cache
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/InstrumentedInputAccessListener.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/UndeclaredBuildInputListener.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintWriter.kt
  subprojects/core/src/main/java/org/gradle/internal/classpath/Instrumented.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/DefaultVersionCatalogBuilder.java
Labels: a:chore, @configuration-cache

#20826 Validate @Input(File(s)) ResolvedArtifactResult as unsupported
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/AbstractInputFilePropertyAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/InputPropertyAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/PropertyAnnotationHandlerSupport.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/DependencyManagementResultsAsInputsIntegrationTest.groovy
  subprojects/docs/src/docs/userguide/troubleshooting/validation_problems.adoc
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/problems/ValidationProblemId.java
  subprojects/model-core/src/testFixtures/groovy/org/gradle/internal/reflect/validation/ValidationMessageChecker.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidatePluginsIntegrationTest.groovy
Labels: in:execution-engine

#20819 Extract registering `javaToolchains` extension to a separate plugin `jvm-toolchains`
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/plugins/ApplyPluginBuildOperationIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/JavaExecToolchainIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaBasePlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JvmToolchainsPlugin.java
  subprojects/plugins/src/main/resources/META-INF/gradle-plugins/org.gradle.jvm-toolchains.properties
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/JvmToolchainsPluginTest.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r51/ProjectConfigurationProgressEventCrossVersionSpec.groovy
Labels: in:jvm-ecosystem, in:toolchains

#20861 Fix version catalog alias snippets
  subprojects/docs/src/snippets/dependencyManagement/catalogs-settings/groovy/settings.gradle
  subprojects/docs/src/snippets/dependencyManagement/catalogs-settings/kotlin/settings.gradle.kts
Labels: from:contributor

#20877 Use `-PrerunAllTests` in RerunFlakyTest builds
  .teamcity/src/main/kotlin/util/RerunFlakyTest.kt
Labels: @dev-productivity

#20580 Re-use Scala compiler between runs
  subprojects/docs/src/docs/release/notes.md
  subprojects/scala/src/main/java/org/gradle/api/internal/tasks/scala/DaemonScalaCompiler.java
  subprojects/scala/src/main/java/org/gradle/api/internal/tasks/scala/MinimalScalaCompileOptions.java
  subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaCompile.java
  subprojects/scala/src/main/java/org/gradle/language/scala/tasks/AbstractScalaCompile.java
  subprojects/scala/src/main/java/org/gradle/language/scala/tasks/BaseScalaCompileOptions.java
  subprojects/scala/src/test/groovy/org/gradle/scala/compile/internal/ScalaCompileOptionsConfigurerTest.groovy
Labels: from:contributor

#20614 Add @DelegatesTo annotation to relevant Closure accepting methods throughout the Gradle API
  subprojects/antlr/src/main/java/org/gradle/api/plugins/antlr/AntlrSourceVirtualDirectory.java
  subprojects/core-api/src/main/java/org/gradle/api/DomainObjectCollection.java
  subprojects/core-api/src/main/java/org/gradle/api/Project.java
  subprojects/core-api/src/main/java/org/gradle/api/Script.java
  subprojects/core-api/src/main/java/org/gradle/api/Task.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/ArtifactRepositoryContainer.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/ComponentSelectionRules.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/ConfigurationContainer.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/ResolvableDependencies.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/ArtifactHandler.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/ComponentMetadataHandler.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/RepositoryHandler.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/result/ResolutionResult.java
  subprojects/core-api/src/main/java/org/gradle/api/file/CopySourceSpec.java
  subprojects/core-api/src/main/java/org/gradle/api/file/CopySpec.java
  subprojects/core-api/src/main/java/org/gradle/api/file/FileTree.java
  subprojects/core-api/src/main/java/org/gradle/api/invocation/Gradle.java
  subprojects/core-api/src/main/java/org/gradle/api/plugins/PluginAware.java
  subprojects/core/src/main/java/org/gradle/configuration/project/ProjectConfigurationActionContainer.java
  subprojects/core/src/main/java/org/gradle/internal/xml/XmlTransformer.java
  subprojects/ear/src/main/java/org/gradle/plugins/ear/EarPluginConvention.java
  subprojects/ear/src/main/java/org/gradle/plugins/ear/descriptor/DeploymentDescriptor.java
  subprojects/ide-native/src/main/java/org/gradle/plugins/ide/internal/generator/PropertyListPersistableConfigurationObject.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/api/XmlFileContentMerger.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/EclipseClasspath.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/EclipseJdt.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/EclipseModel.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/EclipseProject.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/EclipseWtp.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/EclipseWtpComponent.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/EclipseWtpFacet.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/idea/model/IdeaModel.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/idea/model/IdeaModule.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/idea/model/IdeaProject.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/idea/model/IdeaWorkspace.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/generator/PropertiesPersistableConfigurationObject.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/generator/XmlPersistableConfigurationObject.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/javadoc/Javadoc.java
  subprojects/platform-jvm/src/main/java/org/gradle/api/java/archives/Manifest.java
  subprojects/platform-jvm/src/main/java/org/gradle/api/java/archives/ManifestMergeSpec.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/tasks/Jar.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPluginConvention.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPluginExtension.java
  subprojects/plugins/src/main/java/org/gradle/api/tasks/GroovySourceSet.java
  subprojects/plugins/src/main/java/org/gradle/api/tasks/SourceSet.java
  subprojects/plugins/src/main/java/org/gradle/api/tasks/Upload.java
  subprojects/plugins/src/main/java/org/gradle/api/tasks/bundling/War.java
  subprojects/scala/src/main/java/org/gradle/api/tasks/ScalaSourceSet.java
  subprojects/signing/src/main/java/org/gradle/plugins/signing/SigningExtension.java
  subprojects/testing-base/src/main/java/org/gradle/api/tasks/testing/AbstractTestTask.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java
Labels: from:contributor

#20880 Add contributors to release notes
  subprojects/docs/src/docs/release/notes.md
Labels: @execution
