Repository gradle/gradle, pull requests merged in 2022-03, with the labels that each got.

#20064 Fix branch name extraction when channel is adhoc
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/CrossVersionResultsStore.java
Labels: @dev-productivity

#20022 Always capture the file name for artifact transforms
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/AbstractFileCollectionFingerprinter.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/fingerprint/FileCollectionFingerprinter.java
  subprojects/normalization-java/src/main/java/org/gradle/internal/fingerprint/classpath/impl/ClasspathFingerprintingStrategy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/FingerprintingStrategy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/impl/AbsolutePathFingerprintingStrategy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/impl/IgnoredPathFingerprintingStrategy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/impl/NameOnlyFingerprintingStrategy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/impl/RelativePathFingerprintingStrategy.java
Labels: @execution

#20052 Add architecture tests for Provider API usage
  subprojects/architecture-test/build.gradle.kts
  subprojects/architecture-test/src/changes/archunit_store/3c3e47be-b5ed-426a-8b9f-cfa00d3b09db
  subprojects/architecture-test/src/changes/archunit_store/provider-task-file-collection.txt
  subprojects/architecture-test/src/changes/archunit_store/provider-task-properties.txt
  subprojects/architecture-test/src/changes/archunit_store/provider-text-resource.txt
  subprojects/architecture-test/src/changes/archunit_store/public-api-mutable-file-collection.txt
  subprojects/architecture-test/src/changes/archunit_store/public-api-mutable-properties.txt
  subprojects/architecture-test/src/changes/archunit_store/public-api-mutable-text-resource.txt
  subprojects/architecture-test/src/changes/archunit_store/stored.rules
  subprojects/architecture-test/src/test/java/org/gradle/architecture/test/ArchUnitFixture.java
  subprojects/architecture-test/src/test/java/org/gradle/architecture/test/ProviderMigrationArchitectureTest.java
  subprojects/architecture-test/src/test/java/org/gradle/architecture/test/PublicApiAccessTest.java
Labels: @execution

#20072 Use Kotlin 1.7-dev for build-logic
  build-logic-commons/gradle-plugin/build.gradle.kts
  build-logic-commons/settings.gradle.kts
  build-logic/basics/src/main/kotlin/gradlebuild.repositories.gradle.kts
  build-logic/binary-compatibility/src/test/kotlin/gradlebuild/binarycompatibility/AbstractBinaryCompatibilityTest.kt
  build-logic/settings.gradle.kts
  settings.gradle.kts
Labels: @dev-productivity

#20050 Fix inputs of GeneratePluginDescriptors
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/RepositoriesDeclaredInSettingsIntegrationTest.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/plugins/PrecompiledGroovyPluginsIntegrationTest.groovy
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/PluginDeclaration.java
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/GeneratePluginDescriptors.java
Labels: @execution

#20095 Fix os predicate on Windows
  subprojects/wrapper-shared/src/main/java/org/gradle/util/internal/ZipSlip.java
  subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy
Labels: @dev-productivity

#20077 Add info about alias normalization to VersionCatalog javadocs
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/VersionCatalog.java
  subprojects/docs/src/docs/release/notes.md
Labels: in:dependency-version-catalog, a:documentation

#20104 Update test bucket json
  .teamcity/test-buckets.json
Labels: @dev-productivity

#20106 Use String.toLowerCase(Locale.US)
  subprojects/wrapper-shared/src/main/java/org/gradle/util/internal/ZipSlip.java
  subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy
Labels: @dev-productivity

#20107 Auto assign PR to author
  .github/auto_assign.yml
  .github/workflows/auto-assign-pr-to-author.yml
Labels: @dev-productivity

#19908 Filter test tasks by AbstractTestTask instead Test in TestTaskExecutionTracker
  subprojects/tooling-api-builders/src/main/java/org/gradle/tooling/internal/provider/runner/TestTaskExecutionTracker.java
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r75/CustomTestTaskProgressEventCrossVersionTest.groovy
Labels: in:tooling-api

#20037 Upgrade to Spock 2.1
  .gitignore
  build-logic/build-platform/build.gradle.kts
  build-logic/build-update-utils/src/main/kotlin/gradlebuild/buildutils/tasks/UpdateInitPluginTemplateVersionFile.kt
  build-logic/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
  subprojects/architecture-test/build.gradle.kts
  subprojects/architecture-test/src/test/java/org/gradle/architecture/test/ArchUnitFixtureTest.java
  subprojects/base-services/build.gradle.kts
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/library-versions.properties
  subprojects/core/src/integTest/groovy/org/gradle/api/ApplyPluginIntegSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/testfixtures/ProjectBuilderEndUserIntegrationTest.groovy
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DistributionIntegrationSpec.groovy
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/groovy/buildSrc/build.gradle
  subprojects/docs/src/samples/build-organization/publishing-convention-plugins/groovy/convention-plugins/build.gradle
  subprojects/docs/src/snippets/configurationCache/testKit/groovy/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/workingWithDependencies-accessMetadataArtifact/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/developingPlugins/testingPlugins/groovy/url-verifier-plugin/build.gradle
  subprojects/docs/src/snippets/developingPlugins/testingPlugins/kotlin/url-verifier-plugin/build.gradle.kts
  subprojects/docs/src/snippets/testKit/automaticClasspathInjectionCustomTestSourceSet/groovy/build.gradle
  subprojects/docs/src/snippets/testKit/automaticClasspathInjectionCustomTestSourceSet/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/testKit/automaticClasspathInjectionQuickstart/groovy/build.gradle
  subprojects/docs/src/snippets/testKit/automaticClasspathInjectionQuickstart/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/testKit/gradleVersion/groovy/build.gradle
  subprojects/docs/src/snippets/testKit/spockQuickstart/groovy/build.gradle
  subprojects/docs/src/snippets/testKit/testKitFunctionalTestSpockBuildCache/groovy/build.gradle
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/AbstractWritableResultsStore.groovy
  subprojects/language-java/build.gradle.kts
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/AbstractProperty.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/DefaultValueSourceProviderFactory.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/TransformBackedProvider.java
  subprojects/model-core/src/main/java/org/gradle/internal/instantiation/generator/DependencyInjectingInstantiator.java
  subprojects/model-core/src/main/java/org/gradle/internal/isolated/IsolationScheme.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/annotations/impl/DefaultPropertyAnnotationMetadata.java
  subprojects/model-core/src/main/java/org/gradle/model/internal/asm/ClassGeneratorSuffixRegistry.java
  subprojects/native/build.gradle.kts
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/impldeps/BaseGradleImplDepsIntegrationTest.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/plugins/JavaGradlePluginRelocationTest.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/plugins/PrecompiledGroovyPluginsIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/JvmTestSuite.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java
  subprojects/soak/build.gradle.kts
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/enduser/GradleRunnerConsoleInputEndUserIntegrationTest.groovy
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/enduser/GradleRunnerConventionalPluginClasspathInjectionEndUserIntegrationTest.groovy
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/enduser/GradleRunnerDefaultTestKitDirIntegrationTest.groovy
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/enduser/GradleRunnerMiscEndUserIntegrationTest.groovy
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/enduser/GradleRunnerPluginClasspathInjectionEndUserIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junit/BuildSrcSpockIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/spock/Spock2IntegrationSpec.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testsuites/TestSuitesIntegrationTest.groovy
Labels: @execution

#20094 Include subprojects in subprojects.json but not in test-buckets.json
  .teamcity/src/main/kotlin/model/FunctionalTestBucketGenerator.kt
  .teamcity/src/main/kotlin/model/FunctionalTestBucketProvider.kt
  .teamcity/test-buckets.json
Labels: @dev-productivity

#20111 Ignore "java.awt.headless" in the configuration cache
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/InstrumentedInputAccessListener.kt
Labels: @configuration-cache

#20114 Don't store build listeners registered by buildSrc to the config cache
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildServiceIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
Labels: in:configuration-cache, @configuration-cache

#20112 Update docs re: executing tasks in included builds
  subprojects/docs/src/samples/build-organization/composite-builds/basic/README.adoc
Labels: @core, in:documentation

#20119 Merge release to master
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildServiceIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/InstrumentedInputAccessListener.kt
  subprojects/plugin-use/src/main/java/org/gradle/plugin/use/resolve/internal/PluginArtifactRepositoriesProvider.java
  subprojects/tooling-api-builders/src/main/java/org/gradle/tooling/internal/provider/runner/TestTaskExecutionTracker.java
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r75/CustomTestTaskProgressEventCrossVersionTest.groovy
Labels: @dev-productivity

#20122 Remove "execute from Finder" test
  subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperIntegrationTest.groovy
Labels: @dev-productivity

#20128 Ensure headless status in test
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsIntegrationTest.groovy
Labels: @configuration-cache

#20127 Turn `BeanCodec` into an object
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/BeanCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/ClosureCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/ProviderCodecs.kt
Labels: @configuration-cache

#20143 Rebasline SwiftCleanBuildPerformanceTest
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftCleanBuildPerformanceTest.groovy
Labels: @dev-productivity

#19819 Clear no longer pending constraints always
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/DirectDependencyMetadata.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/DependencySubstitutionRulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/platforms/JavaPlatformResolveIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/NodeState.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/maven/AbstractMavenModule.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/maven/DelegatingMavenModule.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/maven/MavenModule.groovy
Labels: in:dependency-resolution

#20154 Add test for convention properties + mapping to `null`
  subprojects/model-core/src/test/groovy/org/gradle/api/internal/provider/DefaultPropertyTest.groovy
Labels: @execution

#20129 Treat abstract Groovy classes with no fields as `Managed` types
  subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingTransformer.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformValuesInjectionIntegrationTest.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/AllDistributionIntegrationSpec.groovy
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/resolver/KotlinBuildScriptModelRequest.kt
  subprojects/model-core/src/main/java/org/gradle/internal/instantiation/generator/AbstractClassGenerator.java
  subprojects/model-core/src/main/java/org/gradle/internal/instantiation/generator/AsmBackedClassGenerator.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/ClassDetails.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/MutableClassDetails.java
  subprojects/model-core/src/main/java/org/gradle/model/internal/asm/AsmClassGeneratorUtils.java
  subprojects/model-core/src/main/java/org/gradle/model/internal/asm/BytecodeFragment.java
  subprojects/model-core/src/main/java/org/gradle/model/internal/asm/MethodVisitorScope.java
Labels: @configuration-cache

#20161 Simplify `AsmBackedClassGenerator`
  subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingTransformer.java
  subprojects/model-core/src/main/java/org/gradle/internal/instantiation/generator/AbstractClassGenerator.java
  subprojects/model-core/src/main/java/org/gradle/internal/instantiation/generator/AsmBackedClassGenerator.java
  subprojects/model-core/src/main/java/org/gradle/model/internal/asm/MethodVisitorScope.java
Labels: @configuration-cache

#20168 Rebaseline TaskOutputCachingJavaPerformanceTest
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingJavaPerformanceTest.groovy
Labels: @dev-productivity

#19835 Implement logging of abbreviation resolve
  subprojects/core/src/integTest/groovy/org/gradle/execution/TaskNameMatchingIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/execution/taskpath/ProjectNameMatchingIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/execution/DefaultTaskSelector.java
  subprojects/core/src/main/java/org/gradle/execution/taskpath/ProjectFinderByTaskPath.java
  subprojects/docs/src/docs/userguide/reference/command_line_interface.adoc
Labels: in:logging, a:feature, in:invoking-gradle

#19910 Make Signing plugin more Kotlin friendly
  subprojects/signing/src/integTest/groovy/org/gradle/plugins/signing/SigningClosureBlockIntegrationSpec.groovy
  subprojects/signing/src/integTest/groovy/org/gradle/plugins/signing/SigningIntegrationSpec.groovy
  subprojects/signing/src/main/java/org/gradle/plugins/signing/SigningExtension.java
Labels: in:signing-plugin

#20069 Use worker api and toolchains for checkstyle
  build-logic/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
  subprojects/base-services/build.gradle.kts
  subprojects/code-quality/build.gradle.kts
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginToolchainsIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginVersionIntegrationTest.groovy
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/Checkstyle.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CheckstylePlugin.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/AntWorkAction.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/CheckstyleAction.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/CheckstyleActionParameters.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/CheckstyleInvoker.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/project/antbuilder/AntBuilderDelegate.java
  subprojects/dependency-management/build.gradle.kts
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/report/HtmlDependencyVerificationReportRendererTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/runtimeshaded/RuntimeShadedJarCreatorTest.groovy
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DistributionIntegrationSpec.groovy
  subprojects/docs/src/docs/release/notes.md
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/impldeps/GradleImplDepsShadingIssuesIntegrationTest.groovy
  subprojects/resources-http/build.gradle.kts
  subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/ApacheDirectoryListingParser.java
Labels: @execution

#20067 Move TestFilesCleanupService to build-logic-commons
  build-logic-commons/code-quality/src/main/kotlin/gradlebuild.ci-reporting.gradle.kts
  build-logic-commons/code-quality/src/main/kotlin/gradlebuild/testcleanup/TestFilesCleanupRootPlugin.kt
  build-logic-commons/code-quality/src/main/kotlin/gradlebuild/testcleanup/TestFilesCleanupService.kt
  build-logic-commons/code-quality/src/main/kotlin/gradlebuild/testcleanup/extension/TestFileCleanUpExtension.kt
  build-logic-commons/code-quality/src/main/kotlin/gradlebuild/testcleanup/extension/TestFilesCleanupBuildServiceRootExtension.kt
  build-logic-commons/code-quality/src/main/kotlin/gradlebuild/testcleanup/extension/TestFilesCleanupProjectState.kt
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.build-logic.groovy-dsl-gradle-plugin.gradle.kts
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.build-logic.kotlin-dsl-gradle-plugin.gradle.kts
  build-logic/buildquality/src/main/kotlin/gradlebuild.configure-ci-artifacts.gradle.kts
  build-logic/buildquality/src/main/kotlin/gradlebuild/testcleanup/TestFilesCleanupRootPlugin.kt
  build-logic/uber-plugins/src/main/kotlin/gradlebuild.java-library.gradle.kts
Labels: @dev-productivity

#20171 Rebaseline RealLifeAndroidStudioPerformanceTest
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidStudioPerformanceTest.groovy
Labels: @dev-productivity

#20181 Fix missing trace.json
  build-logic-commons/code-quality/src/main/kotlin/gradlebuild/testcleanup/TestFilesCleanupRootPlugin.kt
Labels: @dev-productivity

#20023 Add perf test for large android build configuration time
  .teamcity/performance-test-durations.json
  .teamcity/performance-tests-ci.json
  build-logic/performance-testing/src/main/groovy/gradlebuild.performance-templates.gradle
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/AndroidTestProject.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidBuildPerformanceTest.groovy
Labels: @configuration-cache

#20190 Skip constructors when isolating managed types
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformValuesInjectionIntegrationTest.groovy
  subprojects/model-core/src/main/java/org/gradle/internal/instantiation/ManagedTypeFactory.java
  subprojects/model-core/src/main/java/org/gradle/internal/instantiation/generator/AsmBackedClassGenerator.java
  subprojects/model-core/src/main/java/org/gradle/internal/instantiation/generator/DefaultInstantiatorFactory.java
  subprojects/model-core/src/test/groovy/org/gradle/internal/instantiation/generator/ManagedTypeFactoryTest.groovy
  subprojects/model-core/src/test/groovy/org/gradle/internal/snapshot/impl/DefaultIsolatableFactoryTest.groovy
Labels: @configuration-cache

#20201 Replace stale baselines
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidStudioMockupPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingJavaPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ExcludeRuleMergingPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaFirstUsePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIDEModelPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIncrementalExecutionPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaTasksPerformanceTest.groovy
Labels: @dev-productivity

#20204 Synchronize build service registrations
  subprojects/core/src/main/java/org/gradle/api/services/internal/DefaultBuildServicesRegistry.java
Labels: @configuration-cache

#20202 Reduce visibility of ManagedTypeFactory
  subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingTransformer.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformValuesInjectionIntegrationTest.groovy
  subprojects/jvm-services/src/main/java/org/gradle/internal/jvm/inspection/MetadataProbe.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/model/NamedObjectInstantiator.java
  subprojects/model-core/src/main/java/org/gradle/internal/instantiation/generator/AsmBackedClassGenerator.java
  subprojects/model-core/src/main/java/org/gradle/internal/instantiation/generator/DefaultInstantiatorFactory.java
  subprojects/model-core/src/main/java/org/gradle/model/internal/asm/ClassVisitorScope.java
  subprojects/model-core/src/main/java/org/gradle/model/internal/asm/MethodVisitorScope.java
  subprojects/model-core/src/test/groovy/org/gradle/internal/snapshot/impl/DefaultIsolatableFactoryTest.groovy
Labels: a:chore, @configuration-cache

#20200 Fix ConcurrentModificationException in DefaultSerializerRegistry
  subprojects/messaging/src/main/java/org/gradle/internal/serialize/DefaultSerializerRegistry.java
  subprojects/messaging/src/test/groovy/org/gradle/internal/serialize/DefaultSerializerRegistrySpec.groovy
Labels: @execution

#19170 Fix ConcurrentModificationException in DefaultSerializerRegistry
  subprojects/messaging/src/main/java/org/gradle/internal/serialize/DefaultSerializerRegistry.java
  subprojects/messaging/src/test/groovy/org/gradle/internal/serialize/DefaultSerializerRegistrySpec.groovy
Labels: a:bug

#20211 Merge release
  released-versions.json
  version.txt
Labels: @dev-productivity

#20185 Merge build-logic-commons modules
  build-logic-commons/code-quality-rules/build.gradle.kts
  build-logic-commons/code-quality/build.gradle.kts
  build-logic-commons/gradle-plugin/build.gradle.kts
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.build-logic.groovy-dsl-gradle-plugin.gradle.kts
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.build-logic.kotlin-dsl-gradle-plugin.gradle.kts
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.cache-miss-monitor.gradle.kts
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.ci-reporting.gradle.kts
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.code-quality.gradle.kts
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.ktlint.gradle.kts
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild/classycle/extension/ClassycleExtension.kt
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild/classycle/tasks/Classycle.kt
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild/testcleanup/TestFilesCleanupRootPlugin.kt
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild/testcleanup/TestFilesCleanupService.kt
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild/testcleanup/extension/TestFileCleanUpExtension.kt
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild/testcleanup/extension/TestFilesCleanupBuildServiceRootExtension.kt
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild/testcleanup/extension/TestFilesCleanupProjectState.kt
  build-logic-commons/settings.gradle.kts
  build-logic-settings/allprojects-plugin/build.gradle.kts
  build-logic-settings/build-logic-settings-plugin/build.gradle.kts
  build-logic-settings/build-logic-settings-plugin/src/main/kotlin/gradlebuild.base.allprojects.settings.gradle.kts
  build-logic-settings/build-logic-settings-plugin/src/main/kotlin/gradlebuild.internal.cc-experiment.settings.gradle.kts
  build-logic-settings/build-logic-settings-plugin/src/main/kotlin/gradlebuild.internal.testfiltering.settings.gradle.kts
  build-logic-settings/cc-experiment-plugin/build.gradle.kts
  build-logic-settings/settings.gradle.kts
  build-logic-settings/testfiltering-plugin/build.gradle.kts
Labels: @dev-productivity

#20212 Rebaseline JavaIncrementalExecutionPerformanceTest
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIncrementalExecutionPerformanceTest.groovy
Labels: @dev-productivity

#20213 Rebaseline JavaFirstUsePerformanceTest
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaFirstUsePerformanceTest.groovy
Labels: @dev-productivity

#20216 Disable flaky config time perf test for largeAndroidBuild2
  .teamcity/performance-tests-ci.json
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidBuildPerformanceTest.groovy
Labels: @configuration-cache

#20217 Add Jonathan as contributor for #19170
  subprojects/docs/src/docs/release/notes.md
Labels: @execution

#20215 Cherry-pick two non-production changes to `release`
  build-logic/basics/src/main/kotlin/gradlebuild/basics/BuildParams.kt
  build-logic/jvm/src/main/kotlin/gradlebuild/propagated-env-variables.kt
  build-logic/uber-plugins/src/main/kotlin/gradlebuild.internal.kotlin-js.gradle.kts
  subprojects/language-native/src/integTest/groovy/org/gradle/language/swift/SwiftIncrementalBuildIntegrationTest.groovy
Labels: @dev-productivity

#20208 Synchronize build service registrations
  subprojects/core/src/main/java/org/gradle/api/services/internal/DefaultBuildServicesRegistry.java
Labels: @configuration-cache

#20206 Modify Signature task keying
  subprojects/signing/src/integTest/groovy/org/gradle/plugins/signing/SigningPublicationsIntegrationSpec.groovy
  subprojects/signing/src/main/java/org/gradle/plugins/signing/Sign.java
  subprojects/signing/src/main/java/org/gradle/plugins/signing/Signature.java
  subprojects/signing/src/test/groovy/org/gradle/plugins/signing/SigningTasksSpec.groovy
Labels: in:signing-plugin, a:bug

#20207 Move task ordinal inheritance later during graph calculation
  subprojects/core/src/integTest/groovy/org/gradle/api/DestroyerTaskCommandLineOrderIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/ProducerTaskCommandLineOrderIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java
  subprojects/core/src/main/java/org/gradle/execution/plan/TaskNode.java
Labels: @core, a:regression

#20188 Support constraint without version in GMM
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/DependenciesAttributesIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/DefaultDependencyConstraintHandler.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/GradleModuleMetadataParser.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/notations/DependencyConstraintNotationParser.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/GradleModuleMetadataParserTest.groovy
Labels: in:gradle-module-metadata

#20227 Avoid creating InstallSamples tasks at configuration phase
  subprojects/docs/build.gradle
Labels: @dev-productivity

#20226 Upgrade gradle profiler to 0.18.0
  subprojects/distributions-dependencies/build.gradle.kts
Labels: @execution

#20172 Fix issues when GPG command is used
  subprojects/docs/src/docs/userguide/dep-man/06-publishing/signing_plugin.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/security/src/main/java/org/gradle/plugins/signing/signatory/Signatory.java
  subprojects/security/src/main/java/org/gradle/security/internal/gnupg/GnupgSettings.java
  subprojects/signing/src/integTest/groovy/org/gradle/plugins/signing/GpgCmdFixture.groovy
  subprojects/signing/src/integTest/groovy/org/gradle/plugins/signing/SigningWithGpgCmdIntegrationSpec.groovy
Labels: in:signing-plugin, a:feature

#20225 Merge release into master
  released-versions.json
  subprojects/core/src/integTest/groovy/org/gradle/api/DestroyerTaskCommandLineOrderIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/ProducerTaskCommandLineOrderIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java
  subprojects/core/src/main/java/org/gradle/execution/plan/TaskNode.java
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesByGradleFileWatchingIntegrationTest.groovy
Labels: @dev-productivity

#20177 Update Groovy to 3.0.10
  build-logic/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/library-versions.properties
  subprojects/docs/src/docs/userguide/compatibility.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/samples/groovy/library-publishing/groovy/my-library/build.gradle
  subprojects/docs/src/samples/groovy/library-publishing/kotlin/my-library/build.gradle.kts
  subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/AbstractSourcesAndJavadocJarsIntegrationTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/tasks/GroovyRuntimeTest.groovy
Labels: @core

#20235 Rebaseline performance tests
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/DeprecationCreationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeCleanBuildPerformanceTest.groovy
Labels: @dev-productivity

#20186 Upgrade tested AGP versions
  gradle/dependency-management/agp-versions.properties
  subprojects/docs/src/docs/userguide/compatibility.adoc
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerCachingSmokeTest.groovy
Labels: @configuration-cache

#20230 Remove missed incubating annotations
  released-versions.json
  subprojects/core-api/src/main/java/org/gradle/plugin/use/PluginDependency.java
  subprojects/core-api/src/main/java/org/gradle/plugin/use/PluginDependencySpec.java
Labels: in:dependency-version-catalog

#20229 Bump commons-io version to 2.11.0
  subprojects/base-services/src/test/groovy/org/gradle/util/internal/GFileUtilsTest.groovy
  subprojects/build-cache-packaging/src/main/java/org/gradle/caching/internal/packaging/impl/TarBuildCacheEntryPacker.java
  subprojects/core/src/main/java/org/gradle/process/internal/streams/SafeStreams.java
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/LineEndingNormalizingInputStreamHasher.java
Labels: a:chore

#19500 Extend `PropertyReportTask` to allow specifying which property to query
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/PropertyReportTaskIntegrationTest.groovy
  subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/PropertyReportTask.java
  subprojects/diagnostics/src/test/groovy/org/gradle/api/tasks/diagnostics/PropertyReportTaskTest.groovy
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/reference/command_line_interface.adoc
  subprojects/docs/src/snippets/tutorial/projectReports/tests/propertyReport.out
  subprojects/docs/src/snippets/tutorial/projectReports/tests/propertyReport.sample.conf
Labels: @support

#20219 Make precompiled script plugin compilation compatible with the configuration cache
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/InstrumentedInputAccessListener.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/UndeclaredBuildInputListener.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintWriter.kt
  subprojects/core/src/main/java/org/gradle/internal/classpath/Instrumented.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/classpath/ClasspathFingerprinter.java
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/JacocoIntegrationTest.kt
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/PrecompiledScriptPluginIntegrationTest.kt
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/precompiled/PrecompiledScriptPluginAccessorDeprecationWarningsTest.kt
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/precompiled/PrecompiledScriptPluginAccessorSettingEvaluationTest.kt
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/precompiled/PrecompiledScriptPluginAccessorsTest.kt
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/precompiled/PrecompiledScriptPluginTemplatesTest.kt
  subprojects/kotlin-dsl-plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/precompiled/PrecompiledScriptPlugins.kt
  subprojects/kotlin-dsl-provider-plugins/build.gradle.kts
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/DefaultPrecompiledScriptPluginsSupport.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/PrecompiledScriptPluginsSupport.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/ImplicitImports.kt
Labels: a:feature, @configuration-cache

#20237 Remove eagerly created tasks
  build-logic/jvm/src/main/kotlin/gradlebuild.api-parameter-names-index.gradle.kts
  build-logic/publishing/src/main/kotlin/gradlebuild.kotlin-dsl-plugin-bundle.gradle.kts
Labels: @dev-productivity

#20252 Use CompileClasspath normalization for GenerateLanguageAnnotations
  build-logic/integration-testing/src/main/kotlin/gradlebuild/integrationtests/tasks/GenerateLanguageAnnotations.kt
Labels: @dev-productivity

#20251 Merge release into master
  released-versions.json
  subprojects/core-api/src/main/java/org/gradle/plugin/use/PluginDependency.java
  subprojects/core-api/src/main/java/org/gradle/plugin/use/PluginDependencySpec.java
Labels: @dev-productivity

#20220 DirectoryProperty.files should resolve files relative to the base directory
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/DefaultFilePropertyFactory.java
  subprojects/file-collections/src/test/groovy/org/gradle/api/internal/file/DefaultFilePropertyFactoryTest.groovy
  subprojects/file-collections/src/test/groovy/org/gradle/api/internal/file/DirectoryPropertyTest.groovy
  subprojects/file-collections/src/test/groovy/org/gradle/api/internal/file/FilePropertyTest.groovy
  subprojects/file-collections/src/test/groovy/org/gradle/api/internal/file/FileSystemPropertySpec.groovy
Labels: @execution

#20256 Smoke test Kotlin 1.6.20-RC2
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/KotlinGradlePluginVersions.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/WithKotlinDeprecations.groovy
Labels: @configuration-cache

#20257 Clarify that build services must implement an interface, not extend a class
  subprojects/docs/src/docs/userguide/extending-gradle/build_services.adoc
Labels: @core, in:documentation

#20263 Add details/result to configuration cache load/store build operations
  subprojects/configuration-cache/build.gradle.kts
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOperationsIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheBuildOperations.kt
  subprojects/enterprise-operations/src/main/java/org/gradle/internal/configurationcache/ConfigurationCacheLoadBuildOperationType.java
  subprojects/enterprise-operations/src/main/java/org/gradle/internal/configurationcache/ConfigurationCacheStoreBuildOperationType.java
Labels: @configuration-cache

#20281 Fix comment in PerformanceTestDirectoryProvider
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/PerformanceTestDirectoryProvider.groovy
Labels: @dev-productivity

#20280 Only publish test files to TeamCity upon failures
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild/testcleanup/TestFilesCleanupService.kt
  build-logic/buildquality/src/test/kotlin/gradlebuild/testcleanup/TestFilesCleanupServiceTest.kt
Labels: @dev-productivity

#20279 Use Kotlin 1.6.20-RC2 for build
  build-logic-commons/gradle-plugin/build.gradle.kts
  build-logic-commons/settings.gradle.kts
  build-logic/basics/src/main/kotlin/gradlebuild.repositories.gradle.kts
  build-logic/binary-compatibility/src/test/kotlin/gradlebuild/binarycompatibility/AbstractBinaryCompatibilityTest.kt
  build-logic/build-platform/build.gradle.kts
  build-logic/settings.gradle.kts
  settings.gradle.kts
Labels: @dev-productivity

#20298 Rebaseline LargeDependencyGraphPerformanceTest
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/LargeDependencyGraphPerformanceTest.groovy
Labels: @dev-productivity

#20287 Fix issue with mustRunAfter and ordinal node dependencies
  subprojects/core/src/integTest/groovy/org/gradle/api/DestroyerTaskCommandLineOrderIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/ProducerTaskCommandLineOrderIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java
  subprojects/core/src/main/java/org/gradle/execution/plan/OrdinalNode.java
  subprojects/core/src/main/java/org/gradle/execution/plan/OrdinalNodeAccess.java
Labels: a:bug, in:scheduler

#20187 Add threads configuration option to Pmd
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/pmd/PmdPluginVersionIntegrationTest.groovy
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/Pmd.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdExtension.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdPlugin.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/PmdInvoker.groovy
  subprojects/code-quality/src/test/groovy/org/gradle/api/plugins/quality/PmdPluginTest.groovy
  subprojects/docs/src/docs/dsl/org.gradle.api.plugins.quality.Pmd.xml
  subprojects/docs/src/docs/dsl/org.gradle.api.plugins.quality.PmdExtension.xml
Labels: in:pmd-plugin

#20304 Merge release into master
  released-versions.json
  subprojects/core/src/integTest/groovy/org/gradle/api/DestroyerTaskCommandLineOrderIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/ProducerTaskCommandLineOrderIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java
  subprojects/core/src/main/java/org/gradle/execution/plan/OrdinalNode.java
  subprojects/core/src/main/java/org/gradle/execution/plan/OrdinalNodeAccess.java
Labels: @dev-productivity

#20277 Move configuration-cache-report to a separate repository
  .teamcity/subprojects.json
  .teamcity/test-buckets.json
  build-logic/basics/src/main/kotlin/gradlebuild.repositories.gradle.kts
  build-logic/buildquality/src/main/kotlin/gradlebuild.configuration-cache-report.gradle.kts
  build-logic/buildquality/src/main/kotlin/gradlebuild/configcachereport/tasks/MergeReportAssets.kt
  build-logic/buildquality/src/main/kotlin/gradlebuild/configcachereport/tasks/VerifyDevWorkflow.kt
  build-logic/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
  build-logic/uber-plugins/src/main/kotlin/gradlebuild.internal.kotlin-js.gradle.kts
  settings.gradle.kts
  subprojects/configuration-cache-report/README.md
  subprojects/configuration-cache-report/build.gradle.kts
  subprojects/configuration-cache-report/src/main/kotlin/ConfigurationCacheReportPage.kt
  subprojects/configuration-cache-report/src/main/kotlin/Main.kt
  subprojects/configuration-cache-report/src/main/kotlin/data/ListExtensions.kt
  subprojects/configuration-cache-report/src/main/kotlin/data/Trie.kt
  subprojects/configuration-cache-report/src/main/kotlin/elmish/Component.kt
  subprojects/configuration-cache-report/src/main/kotlin/elmish/View.kt
  subprojects/configuration-cache-report/src/main/kotlin/elmish/tree/TreeView.kt
  subprojects/configuration-cache-report/src/main/resources/configuration-cache-report-logo.png
  subprojects/configuration-cache-report/src/main/resources/configuration-cache-report.css
  subprojects/configuration-cache-report/src/main/resources/configuration-cache-report.html
  subprojects/configuration-cache-report/src/test/resources/configuration-cache-report-data.js
  subprojects/configuration-cache/build.gradle.kts
Labels: @dev-productivity

#20306 Support running configuration-cache-report as included build
  subprojects/configuration-cache/build.gradle.kts
Labels: @dev-productivity

#20308 Update default Checkstyle version to latest 8.x release
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CheckstylePlugin.java
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
Labels: in:checkstyle-plugin

#18098 Fix performance at scale of IterationOrderRetainingSetElementSource#add
  subprojects/core/src/main/java/org/gradle/api/internal/collections/IterationOrderRetainingSetElementSource.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/collections/IterationOrderRetainingSetElementSourceTest.groovy
  subprojects/docs/src/docs/release/notes.md
Labels: @core

#20295 Fix issue with deadlocking between test task and dependency resolution
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/processors/TestMainAction.java
  subprojects/testing-base/src/test/groovy/org/gradle/api/internal/tasks/testing/processors/TestMainActionTest.groovy
Labels: in:testing, a:bug

#20115 Allow for adding dependencies to a test suites' annotationProcessor configuration in the suite's dependencies block
  subprojects/docs/src/docs/userguide/jvm/jvm_test_suite_plugin.adoc
  subprojects/docs/src/snippets/testing/test-suite-configure-suite-dependencies/groovy/build.gradle
  subprojects/docs/src/snippets/testing/test-suite-configure-suite-dependencies/kotlin/build.gradle.kts
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/JvmComponentDependencies.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmComponentDependencies.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testsuites/TestSuitesDependenciesIntegrationTest.groovy
Labels: @core, in:test-suites

#20321 Mark one ArtifactTransformCachingIntegrationTest as @Flaky
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
Labels: @dev-productivity

#20324 Remove test filtering plugin
  build-logic-settings/build-logic-settings-plugin/src/main/kotlin/gradlebuild.internal.testfiltering.settings.gradle.kts
  settings.gradle.kts
Labels: a:chore

#20311 Fix windows script return code
  build-logic/jvm/src/main/kotlin/gradlebuild.launchable-jar.gradle.kts
  build-logic/jvm/src/main/kotlin/gradlebuild/startscript/tasks/GradleStartScriptGenerator.kt
  subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/windowsStartScript.txt
  subprojects/plugins/src/test/groovy/org/gradle/api/internal/plugins/WindowsStartScriptGeneratorTest.groovy
Labels: windows

#19966 Any options set on a javadoc task will now be included in the task uptodate check
  subprojects/language-java/src/integTest/groovy/org/gradle/javadoc/JavadocIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/external/javadoc/CoreJavadocOptions.java
  subprojects/language-java/src/main/java/org/gradle/external/javadoc/StandardJavadocDocletOptions.java
  subprojects/language-java/src/main/java/org/gradle/external/javadoc/internal/JavadocOptionFile.java
Labels: @core, in:javadoc-task
