Repository gradle/gradle, pull requests merged in 2022-10, with the labels that each got.

#22285 Update test bucket json
  .teamcity/test-buckets.json
Labels: @dev-productivity

#22303 Remove some complexity of the generated Java multi-project build
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/generator/FileContentGenerator.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/generator/GroovyDslFileContentGenerator.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/generator/KotlinDslFileContentGenerator.groovy
  subprojects/plugins/src/main/java/org/gradle/api/tasks/SourceSetOutput.java
Labels: @core

#22242 Ensure project builder properly creates root project so it is closed …
  subprojects/core/src/test/groovy/org/gradle/api/internal/AbstractTaskSpec.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/artifacts/dependencies/DefaultProjectDependencyTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/test/fixtures/AbstractProjectBuilderSpec.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/util/TestUtil.groovy
  subprojects/diagnostics/src/test/groovy/org/gradle/api/plugins/HelpTasksPluginSpec.groovy
  subprojects/diagnostics/src/test/groovy/org/gradle/api/tasks/diagnostics/BuildEnvironmentReportTaskTest.groovy
  subprojects/diagnostics/src/test/groovy/org/gradle/api/tasks/diagnostics/ProjectReportTaskTest.groovy
  subprojects/ide/src/test/groovy/org/gradle/plugins/ide/idea/IdeaPluginTest.groovy
  subprojects/ide/src/test/groovy/org/gradle/plugins/ide/idea/model/IdeaModuleTest.groovy
  subprojects/ide/src/test/groovy/org/gradle/plugins/ide/idea/model/IdeaProjectTest.groovy
  subprojects/ide/src/test/groovy/org/gradle/plugins/ide/internal/tooling/GradleProjectBuilderTest.groovy
  subprojects/ide/src/test/groovy/org/gradle/plugins/ide/internal/tooling/ProjectPublicationsBuilderTest.groovy
  subprojects/ide/src/test/groovy/org/gradle/plugins/ide/internal/tooling/eclipse/EclipseModelBuilderDependenciesTest.groovy
  subprojects/ide/src/test/groovy/org/gradle/plugins/ide/internal/tooling/eclipse/EclipseModelBuilderTest.groovy
  subprojects/ide/src/test/groovy/org/gradle/plugins/ide/internal/tooling/eclipse/RunBuildDependenciesTaskBuilderTest.groovy
  subprojects/ide/src/test/groovy/org/gradle/plugins/ide/internal/tooling/idea/IdeaModelBuilderTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/distribution/plugins/DistributionPluginTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/JavaLibraryDistributionPluginTest.groovy
  subprojects/scala/src/test/groovy/org/gradle/api/tasks/ScalaRuntimeTest.groovy
Labels: @core

#22301 Fix regression with missing owner information from artifacts
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenPomResolveIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/query/DefaultArtifactResolutionQuery.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/ExternalResourceResolverDescriptorParseContext.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/query/DefaultArtifactResolutionQueryTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/SpringBootPluginSmokeTest.groovy
Labels: @core

#22306 Rebaseline performance tests
  gradle.properties
Labels: @dev-productivity

#21888 Allow disabling of cleanup for all caches in Gradle user home
  subprojects/build-cache/src/integTest/groovy/org/gradle/caching/local/internal/DirectoryBuildCacheCleanupIntegrationTest.groovy
  subprojects/build-cache/src/main/java/org/gradle/caching/local/internal/DirectoryBuildCacheServiceFactory.java
  subprojects/build-cache/src/test/groovy/org/gradle/caching/local/internal/DirectoryBuildCacheServiceFactoryTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheRepository.kt
  subprojects/core/src/main/java/org/gradle/cache/internal/GradleUserHomeCacheCleanupActionDecorator.java
  subprojects/core/src/main/java/org/gradle/cache/internal/GradleUserHomeCleanupService.java
  subprojects/core/src/main/java/org/gradle/cache/internal/GradleUserHomeCleanupServices.java
  subprojects/core/src/main/java/org/gradle/cache/internal/MonitoredCleanupAction.java
  subprojects/core/src/main/java/org/gradle/cache/internal/MonitoredCleanupActionDecorator.java
  subprojects/core/src/main/java/org/gradle/cache/internal/VersionSpecificCacheCleanupAction.java
  subprojects/core/src/main/java/org/gradle/cache/internal/WrapperDistributionCleanupAction.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/DefaultClasspathTransformerCacheFactory.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GradleUserHomeScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/session/BuildSessionScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/cache/internal/GradleUserHomeCacheCleanupActionDecoratorTest.groovy
  subprojects/core/src/test/groovy/org/gradle/cache/internal/GradleUserHomeCleanupServiceTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/classpath/DefaultCachedClasspathTransformerTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/cache/internal/CacheCleanupEnablementFixture.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/caching/DefaultArtifactCacheLockingManagerIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementGradleUserHomeScopeServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/DefaultArtifactCaches.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/WritableArtifactCacheLockingManager.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/ImmutableTransformationWorkspaceServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/DependenciesAccessorsWorkspaceProvider.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/DefaultArtifactCacheLockingManagerTest.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/workspace/impl/DefaultImmutableWorkspaceProvider.java
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/cache/GradleUserHomeServices.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/cache/KotlinDslWorkspaceProvider.kt
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/BuildOperationCleanupActionDecorator.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/CleanupActionDecorator.java
  subprojects/version-control/src/main/java/org/gradle/vcs/internal/services/DefaultVersionControlRepositoryFactory.java
  subprojects/version-control/src/main/java/org/gradle/vcs/internal/services/VersionControlServices.java
Labels: a:feature

#22256 Try to mitigate performance regression in IdeIntegrationPerformanceTest
  gradle.properties
  subprojects/base-services/src/main/java/org/gradle/internal/service/DefaultServiceRegistry.java
  subprojects/core/src/main/java/org/gradle/internal/xml/XmlTransformer.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/DefaultComponentGraphResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/resolver/ArtifactSelector.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/resolver/DefaultArtifactSelector.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/generator/JavaTestProjectGenerator.groovy
Labels: @core

#22321 Make customizingResolution-deactivateGlobalSubstitution CC-compatible
  subprojects/docs/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-deactivateGlobalSubstitution/groovy/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-deactivateGlobalSubstitution/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-deactivateGlobalSubstitution/tests/resolve.out
Labels: @configuration-cache

#22261 Improve output of integration tests failing check for "output contains string" tests
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/OutputScrapingExecutionResult.java
  subprojects/internal-integ-testing/src/test/groovy/org/gradle/integtests/fixtures/executer/OutputScrapingExecutionResultTest.groovy
Labels: @dev-productivity, @execution

#22312 verification-metadata Trust.Reasons and Checksum.Reasons
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationSignatureCheckIntegTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationSignatureWriteIntegTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationWritingIntegTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/writer/WriteDependencyVerificationFile.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/model/Checksum.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/serializer/DependencyVerificationsXmlReader.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/serializer/DependencyVerificationsXmlWriter.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/verifier/DependencyVerificationConfiguration.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/verifier/DependencyVerifierBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/verifier/MissingSignature.java
  subprojects/dependency-management/src/main/resources/org/gradle/schema/dependency-verification-1.2.xsd
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/verification/serializer/DependencyVerificationsXmlReaderTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/verification/serializer/DependencyVerificationsXmlWriterTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/verification/verifier/DependencyVerifierTest.groovy
  subprojects/dependency-management/src/testFixtures/groovy/org/gradle/api/internal/artifacts/verification/DependencyVerificationFixture.groovy
Labels: from:contributor

#22210 Display artifacts from performance test dependencies
  .teamcity/src/main/kotlin/projects/StageProject.kt
Labels: @dev-productivity

#22316 Avoid volatile writes from Atomics default values
  subprojects/base-services/src/main/java/org/gradle/internal/time/MonotonicClock.java
  subprojects/build-cache/src/jmh/java/org/gradle/caching/internal/tasks/ChmodBenchmark.java
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheClassLoaderCachingIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/cache/internal/DefaultGeneratedGradleJarCacheIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultRealizableTaskCollection.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/FileParameterUtils.java
  subprojects/core/src/test/groovy/org/gradle/testfixtures/ProjectBuilderTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/store/ResolutionResultsStoreFactory.java
  subprojects/dependency-management/src/test/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformInvocationTest.groovy
  subprojects/file-collections/src/test/groovy/org/gradle/api/internal/file/collections/DirectoryWalkerTest.groovy
  subprojects/file-collections/src/test/groovy/org/gradle/api/internal/file/collections/GeneratedSingletonFileTreeTest.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DefaultFileWatcherRegistry.java
  subprojects/functional/src/test/groovy/org/gradle/internal/DeferrableTest.groovy
  subprojects/functional/src/test/groovy/org/gradle/internal/lazy/LazyTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/ToBeFixedForConfigurationCacheExtension.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/AbstractBuildExperimentRunner.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/AbstractTablePageGenerator.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/DefaultInMemoryCacheDecoratorFactory.java
  subprojects/platform-jvm/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainIntegrationTest.groovy
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/impl/DirectorySnapshotter.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/impl/FileSystemSnapshotFilter.java
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterAsDirectoryWalkerTest.groovy
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/junit/result/AggregateTestResultsProvider.java
Labels: @execution, from:contributor

#22360 Fix CC compatibility of the MapProperty
  subprojects/model-core/src/integTest/groovy/org/gradle/api/provider/MapPropertyIntegrationTest.groovy
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/MapCollectors.java
Labels: @configuration-cache

#22177 Make changing the testing framework after setting options an error
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/JvmTestSuitePluginIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestOptionsIntegrationSpec.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestTaskIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junit/JUnitCategoriesIntegrationSpec.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testsuites/JUnitOptionsIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testsuites/TestSuitesIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/resources/org/gradle/testing/junit/JUnitCategoriesIntegrationSpec/reExecutesWhenPropertyIsChanged/src/integTest/java/org/gradle/CategoryA.java
  subprojects/testing-jvm/src/integTest/resources/org/gradle/testing/junit/JUnitCategoriesIntegrationSpec/reExecutesWhenPropertyIsChanged/src/integTest/java/org/gradle/CategoryB.java
  subprojects/testing-jvm/src/integTest/resources/org/gradle/testing/junit/JUnitCategoriesIntegrationSpec/reExecutesWhenPropertyIsChanged/src/integTest/java/org/gradle/SomeTestClass.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java
Labels: in:test-suites

#22364 Derived sources and javadoc jars should have a jar artifactType
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/derived/JvmDerivedVariantsIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/JavaEcosystemVariantDerivationStrategy.java
Labels: @core

#22373 Bump wrapper
  gradle/wrapper/gradle-wrapper.properties
Labels: @core

#22372 Merge release into master
  .teamcity/src/main/kotlin/common/JvmCategory.kt
  .teamcity/src/main/kotlin/model/CIBuildModel.kt
  released-versions.json
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/derived/JvmDerivedVariantsIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/JavaEcosystemVariantDerivationStrategy.java
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/reporting/model/ModelReportIntegrationTest.groovy
  subprojects/docs/build.gradle
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/groovy/buildSrc/build.gradle
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/kotlin/buildSrc/build.gradle.kts
  subprojects/docs/src/samples/build-organization/publishing-convention-plugins/groovy/convention-plugins/build.gradle
  subprojects/docs/src/samples/build-organization/publishing-convention-plugins/kotlin/convention-plugins/build.gradle.kts
  subprojects/docs/src/samples/incubating/build-organization/publishing-convention-plugins/groovy/convention-plugins/build.gradle
  subprojects/docs/src/samples/incubating/build-organization/publishing-convention-plugins/kotlin/convention-plugins/build.gradle.kts
  subprojects/docs/src/snippets/signing/maven-publish/groovy/src/main/java/Sample.java
  subprojects/docs/src/snippets/signing/maven-publish/kotlin/src/main/java/Sample.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/AbstractGradleExecuter.java
  subprojects/internal-testing/src/main/groovy/org/gradle/util/TestPrecondition.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyPublishValidationIntegTest.groovy
  subprojects/model-groovy/src/integTest/groovy/org/gradle/model/dsl/internal/transform/ModelDslRuleDetectionIntegrationSpec.groovy
  subprojects/platform-base/src/integTest/groovy/org/gradle/language/base/ComponentModelReportIntegrationTest.groovy
  subprojects/platform-base/src/integTest/groovy/org/gradle/language/base/InternalViewsSampleIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/DefaultTestOrderingIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junit/JUnitLoggingOutputCaptureIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGLoggingOutputCaptureIntegrationTest.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/m8/ToolingApiLoggingCrossVersionSpec.groovy
Labels: @core

#22350 Fix an inconsistency in toolchain docs
  subprojects/docs/src/docs/userguide/jvm/toolchains.adoc
Labels: from:contributor

#22377 Update gradle-profiler to 0.19.0 and Android Studio to 2022.1.1.12
  build-logic/performance-testing/src/main/kotlin/gradlebuild/performance/PerformanceTestPlugin.kt
  gradle/verification-metadata.xml
  subprojects/distributions-dependencies/build.gradle.kts
Labels: @execution

#22381 Try latest version of exclude-rule build and unignore tests
  build-logic/performance-testing/src/main/groovy/gradlebuild.performance-templates.gradle
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ExcludeRuleMergingPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/LargeDependencyGraphPerformanceTest.groovy
Labels: @core

#22357 Disable stacktraces by default for integration tests
  subprojects/build-cache-http/src/integTest/groovy/org/gradle/caching/http/internal/HttpBuildCacheServiceErrorHandlingIntegrationTest.groovy
  subprojects/build-cache-http/src/integTest/groovy/org/gradle/caching/http/internal/HttpBuildCacheServiceIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/UndefinedBuildExecutionIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/file/ProjectLayoutIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CacheTaskArchiveErrorIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/InternalGradleFailuresIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/TomlDependenciesExtensionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/VersionCatalogExtensionIntegrationTest.groovy
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/HelpTaskIntegrationTest.groovy
  subprojects/docs/src/docsTest/java/org/gradle/docs/samples/IntegrationTestSamplesExecutor.java
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskErrorExecutionIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/AbstractGradleExecuter.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/GradleExecuter.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/OutputScrapingExecutionFailure.java
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/GradleKotlinDslIntegrationTest.kt
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/StacktraceIntegrationTest.groovy
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/taskgrouping/rich/RichConsoleBasicGroupedTaskLoggingFunctionalTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/dependencies/JavaConfigurationSetupIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestInputAnnotationFailuresIntegrationTest.groovy
  subprojects/wrapper-shared/src/integTest/groovy/org/gradle/integtests/ZipSlipIntegrationTest.groovy
Labels: @execution

#22387 Exclude merge simplification
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/excludes/factories/Intersections.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/excludes/factories/ExcludeTestSupport.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/excludes/factories/NormalizingExcludeFactoryTest.groovy
  subprojects/dependency-management/src/testFixtures/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/excludes/factories/ExcludeJsonLogToCode.groovy
Labels: in:dependency-resolution

#22402 Prompt for a reason when accepting all changes on the binary compatibility report
  build-logic/binary-compatibility/src/main/groovy/gradlebuild/EnrichedReportRenderer.groovy
Labels: in:building-gradle

#22415 Update tested AGP versions
  gradle/dependency-management/agp-versions.properties
Labels: a:chore

#22390 Avoid mutating forking options in JavaCompile
  subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/DefaultGroovyJavaJointCompileSpecFactory.java
  subprojects/language-groovy/src/test/groovy/org/gradle/api/internal/tasks/compile/DefaultGroovyJavaJointCompileSpecFactoryTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileToolchainIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/AbstractJavaCompileSpecFactory.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/CommandLineJavaCompileSpec.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/CommandLineJavaCompiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/DaemonJavaCompiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/DefaultJavaCompileSpecFactory.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/ForkingJavaCompileSpec.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/DefaultJavaCompilerFactoryTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/tasks/compile/JavaCompileTest.groovy
  subprojects/scala/src/main/java/org/gradle/api/internal/tasks/scala/DefaultScalaJavaJointCompileSpecFactory.java
  subprojects/scala/src/test/groovy/org/gradle/api/internal/tasks/scala/DefaultScalaJavaJointCompileSpecFactoryTest.groovy
Labels: in:toolchains

#22430 Mark GradleRunnerFileSystemWatchingIntegrationTest as @LocalOnly
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/GradleRunnerFileSystemWatchingIntegrationTest.groovy
Labels: @dev-productivity

#22417 Disable PTS for architecture tests
  build-logic/buildquality/build.gradle.kts
  build-logic/buildquality/src/main/kotlin/gradlebuild.arch-test.gradle.kts
  subprojects/architecture-test/build.gradle.kts
Labels: @dev-productivity

#22418 Enable PTS for remaining "normal" tests
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
Labels: @dev-productivity

#22431 Make JavaExecDebugIntegrationTest only run on local executors
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecDebugIntegrationTest.groovy
Labels: @dev-productivity

#22434 Cherry-pick annotation based TD selection to `release`
  .teamcity/src/main/kotlin/model/FunctionalTestBucketGenerator.kt
  .teamcity/test-buckets.json
  build-logic/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/BuildOperationsFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesBetweenBuildsFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesByGradleFileWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesDuringTheBuildFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ContinuousBuildFileWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/EnableFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/FileSystemWatchingSettingsFinalizedBuildOperationIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/LoggingFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/NoDaemonFilesystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/SymlinkFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/WatchedDirectoriesFileSystemWatchingIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecDebugIntegrationTest.groovy
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/GradleRunnerFileSystemWatchingIntegrationTest.groovy
Labels: @dev-productivity

#21332 Fix some typos in upgrading_version_7.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
Labels: from:contributor

#22420 Upgrade tested AGP versions
  gradle/dependency-management/agp-versions.properties
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerCachingSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginAndroidGroovyDSLSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginAndroidKotlinDSLSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/WithReportDeprecations.groovy
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/android-kotlin-example-kotlin-dsl/app/build.gradle.kts
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/android-kotlin-example-kotlin-dsl/app/src/main/AndroidManifest.xml
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/android-kotlin-example/app/build.gradle
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/android-kotlin-example/app/src/main/AndroidManifest.xml
Labels: a:chore

#21846 Fix maven-publish integration tests under configuration cache
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractIntegrationSpec.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/AbstractMavenPublishJavaIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishBasicIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishBuildOperationIntegrationTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishDependenciesIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishFeaturesJavaIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishFeaturesJavaPluginIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishJavaIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishMultiProjectIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishVersionRangeIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/SamplesMavenPublishIntegrationTest.groovy
Labels: @configuration-cache

#22449 Avoid setting release flag for Java compiler when toolchains are used
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
  subprojects/language-java/src/test/groovy/org/gradle/api/tasks/compile/JavaCompileTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/JavaBasePluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/BasicJavaCompilerIntegrationSpec.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/CommandLineJavaCompilerForExecutableIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/CommandLineJavaCompilerIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/InProcessJavaCompilerIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/JavaCompilerIntegrationSpec.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/daemon/DaemonJavaCompilerIntegrationTest.groovy
Labels: in:toolchains

#22459 Use `promoteFinalRelease` task in backport release
  .teamcity/src/main/kotlin/common/VersionedSettingsBranch.kt
  .teamcity/src/main/kotlin/promotion/PublishRelease.kt
Labels: @dev-productivity

#22322 Make duplicate publication check configuration cache compatible
  subprojects/docs/build.gradle
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publisher/IvyDuplicatePublicationTracker.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publisher/MavenDuplicatePublicationTracker.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/tasks/AbstractPublishToMaven.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/tasks/PublishToMavenLocal.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/tasks/PublishToMavenRepository.java
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/validation/DuplicatePublicationTracker.java
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/validation/PublicationWithProject.java
Labels: @configuration-cache

#22414 Improve 7.6 release notes
  CONTRIBUTING.md
  subprojects/docs/src/docs/release/notes.md
  subprojects/launcher/src/main/resources/release-features.txt
Labels: a:documentation

#22472 Align JavaVersion format with official Java versioning
  subprojects/base-services/src/main/java/org/gradle/api/JavaVersion.java
  subprojects/base-services/src/test/groovy/org/gradle/api/JavaVersionSpec.groovy
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/ide/src/test/groovy/org/gradle/plugins/ide/internal/tooling/idea/IdeaModelBuilderTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileToolchainIntegrationTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/JavaPluginTest.groovy
Labels: in:toolchains

#22473 Fix handling native file watching thread exiting because of error
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherRegistryFactory.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DefaultFileWatcherRegistry.java
Labels: @execution

#22477 Add comments about the `test-class-data.json` file
  .teamcity/src/main/kotlin/model/FunctionalTestBucketGenerator.kt
Labels: @dev-productivity

#22499 Smoke test Kotlin 1.7.20
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/KotlinGradlePluginVersions.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
Labels: a:chore

#22500 Don't run Gradleception on shared host
  .teamcity/src/main/kotlin/configurations/Gradleception.kt
Labels: @dev-productivity

#22498 Filter legacy source set dependency for classes dirs
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/DefaultConfigurableFileCollection.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/AbstractTaskDependencyContainerVisitingContext.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/tasks/FailureCollectingTaskDependencyResolveContext.java
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/JavaPluginIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/internal/tasks/DefaultSourceSetOutput.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmPluginServices.java
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/JavaPluginTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/jvm/internal/DefaultJvmPluginServicesTest.groovy
Labels: a:regression

#22542 Remove single performance scenario baseline
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaFirstUsePerformanceTest.groovy
Labels: a:chore

#22556 Fix adding bundles via DependencyHandler#addProvider
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/TomlDependenciesExtensionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/DefaultDependencyHandler.java
Labels: a:bug, in:dependency-version-catalog, in:dependency-declarations

#22546 ci: update github actions
  .github/workflows/codeql-analysis.yml
  .github/workflows/contributor-pr.yml
  .github/workflows/stale-issue.yml
Labels: from:contributor

#22108 Toolchain based configuration and execution of standard Java tasks
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AvailableJavaHomes.java
  subprojects/internal-testing/src/main/groovy/org/gradle/util/TestPrecondition.groovy
  subprojects/language-groovy/src/test/groovy/org/gradle/api/internal/tasks/compile/DefaultGroovyJavaJointCompileSpecFactoryTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/JavaExecToolchainIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/JavaToolchainBuildOperationsIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileToolchainIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/javadoc/JavadocToolchainIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/AbstractJavaCompileSpecFactory.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/JavaExec.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/javadoc/Javadoc.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/DefaultJavaCompileSpecFactoryTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/tasks/compile/JavaCompileTest.groovy
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/CurrentJvmToolchainSpec.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchain.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainFactory.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainInput.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainQueryService.java
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/toolchain/internal/JavaToolchainQueryServiceTest.groovy
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/toolchain/internal/JavaToolchainTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/JavaBasePluginIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/ApplicationPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/GroovyBasePlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaBasePlugin.java
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/JavaBasePluginTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/tasks/testing/TestTest.groovy
  subprojects/scala/src/main/java/org/gradle/api/plugins/scala/ScalaBasePlugin.java
  subprojects/scala/src/test/groovy/org/gradle/api/internal/tasks/scala/DefaultScalaJavaJointCompileSpecFactoryTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestTaskToolchainIntegrationTest.groovy
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java
  subprojects/testing-jvm/src/test/groovy/org/gradle/api/tasks/testing/TestTest.groovy
Labels: in:toolchains
