Repository gradle/gradle, pull requests merged in 2022-09, with the labels that each got.

#21782 Update test bucket json
  .teamcity/test-buckets.json
Labels: @dev-productivity

#21776 Remove deprecated-hidden NamedDomainObjectContainer.invoke Kotlin extension
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/NamedDomainObjectContainerExtensions.kt
Labels: a:chore, in:kotlin-dsl

#21770 Mention warnings that were turned to errors previously
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
Labels: @execution

#17699 Let eclipse-wtp remove the "jst.utility" facet in ejb modules
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/EclipseWtpFacet.java
  subprojects/ide/src/test/groovy/org/gradle/plugins/ide/eclipse/EclipseWtpPluginTest.groovy
Labels: in:eclipse-plugin, from:contributor

#21773 Remove deprecated members of the internal PrecompiledScriptPluginsSupport
  build-logic-commons/gradle-plugin/build.gradle.kts
  build-logic/kotlin-dsl/src/main/kotlin/gradlebuild.kotlin-dsl-dependencies-embedded.gradle.kts
  gradle/verification-metadata.xml
  subprojects/kotlin-dsl-plugins/build.gradle.kts
  subprojects/kotlin-dsl-plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/precompiled/PrecompiledScriptPlugins.kt
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/DefaultPrecompiledScriptPluginsSupport.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/PrecompiledScriptPluginsSupport.kt
Labels: a:chore, in:kotlin-dsl

#21827 Use a serializable spec to become CC friendly
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/options/OptionReader.java
Labels: @configuration-cache

#21836 Completely disallow injecting transform input artifact as java.io.File
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/transform/InputArtifact.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformValuesInjectionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformer.java
Labels: @execution

#21746 Simplify state capture during execution
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/TaskExecution.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/UnitOfWork.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CaptureStateAfterExecutionStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CaptureStateBeforeExecutionStep.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CaptureStateAfterExecutionStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CaptureStateBeforeExecutionStepTest.groovy
Labels: @execution

#21757 Turn validation warning into error: missing task dependency
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/tasks/TaskCacheabilityReasonIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/execution/plan/MissingTaskDependencyDetector.java
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/StaleOutputIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/ExecutionFailure.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/validation/ValidationProblem.java
  subprojects/language-java/src/integTest/groovy/org/gradle/javadoc/JavadocWorkAvoidanceIntegrationTest.groovy
  subprojects/model-core/src/testFixtures/groovy/org/gradle/integtests/fixtures/ExecutionOptimizationDeprecationFixture.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/antmigration/SamplesAntImportIntegrationTest.groovy
Labels: @execution

#21829 Make generated-file-dependencies snippet configuration cache compatible (#21799)
  subprojects/docs/build.gradle
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/snippets/artifacts/generatedFileDependencies/groovy/build.gradle
  subprojects/docs/src/snippets/artifacts/generatedFileDependencies/kotlin/build.gradle.kts
Labels: from:contributor, cc-hackathon-2022

#21850 Off-by-one error on Windows path length checks
  subprojects/core/src/main/java/org/gradle/process/internal/util/LongCommandLineDetectionUtil.java
Labels: from:contributor

#21789 Remove version catalog naming pattern
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/VersionCatalogExtensionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/internal/management/DefaultVersionCatalogBuilderContainer.java
  subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/platforms.adoc
Labels: in:dependency-version-catalog, @support

#21761 Make snippets java/basic, tutorial/taskOnlyIf work with configuration ...caching
  subprojects/docs/build.gradle
  subprojects/docs/src/snippets/java/basic/groovy/build.gradle
  subprojects/docs/src/snippets/java/basic/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/tutorial/taskOnlyIf/groovy/build.gradle
  subprojects/docs/src/snippets/tutorial/taskOnlyIf/kotlin/build.gradle.kts
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/java/SamplesJavaTestingIntegrationTest.groovy
Labels: @configuration-cache

#21866 Align Kotlin snippet with the Groovy version
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-attributeSubstitutionRule/kotlin/consumer/build.gradle.kts
Labels: @configuration-cache, in:documentation

#21852 Adjust the configureTaskUsingProjectProperty sample for configuration cache
  subprojects/docs/build.gradle
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/snippets/tutorial/configureTaskUsingProjectProperty/groovy/build.gradle
  subprojects/docs/src/snippets/tutorial/configureTaskUsingProjectProperty/kotlin/build.gradle.kts
Labels: @configuration-cache, from:contributor, cc-hackathon-2022

#21873 Adjust the snippets/testing/test-suite-multi-configure-each sample for configuration cache
  subprojects/docs/build.gradle
  subprojects/docs/src/snippets/testing/test-suite-multi-configure-each/groovy/build.gradle
Labels: from:contributor, cc-hackathon-2022

#21791 Remove deprecated AntlrSourceVirtualDirectory & AntlrSourceVirtualDirectoryImpl
  subprojects/antlr/src/integTest/groovy/org/gradle/api/plugins/antlr/AntlrPluginIntegrationTest.groovy
  subprojects/antlr/src/main/java/org/gradle/api/plugins/antlr/AntlrPlugin.java
  subprojects/antlr/src/main/java/org/gradle/api/plugins/antlr/AntlrSourceDirectorySet.java
  subprojects/antlr/src/main/java/org/gradle/api/plugins/antlr/AntlrSourceVirtualDirectory.java
  subprojects/antlr/src/main/java/org/gradle/api/plugins/antlr/internal/AntlrSourceVirtualDirectoryImpl.java
  subprojects/antlr/src/test/groovy/org/gradle/api/plugins/antlr/AntlrPluginTest.groovy
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/model-core/src/main/java/org/gradle/internal/extensibility/DefaultConvention.java
  subprojects/model-core/src/test/groovy/org/gradle/internal/extensibility/DefaultConventionTest.groovy
Labels: a:chore, in:antlr-plugin

#21855 CCH22-19: Adjust the snippets/java/customDirs sample for cc #21816
  subprojects/docs/build.gradle
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/snippets/java/customDirs/groovy/build.gradle
  subprojects/docs/src/snippets/java/customDirs/kotlin/build.gradle.kts
Labels: from:contributor, cc-hackathon-2022

#21869 Make snippets/buildCache/cacheable-bundle-task compatible with the co…
  subprojects/docs/build.gradle
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/snippets/buildCache/cacheable-bundle-task/groovy/build.gradle
  subprojects/docs/src/snippets/buildCache/cacheable-bundle-task/kotlin/build.gradle.kts
Labels: from:contributor, cc-hackathon-2022

#21413 Revert "Ignore failing CC smoke test for 7.5.1"
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildSanityCheckConfigurationCacheSmokeTest.groovy
Labels: a:chore, in:configuration-cache, @configuration-cache

#21904 De-incubate getThreads for Pmd task and extension
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/Pmd.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdExtension.java
Labels: @execution

#21854 Adjust the snippets/testing/test-suite-multi-configure-each-matching …
  subprojects/docs/build.gradle
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/snippets/testing/test-suite-multi-configure-each-matching/groovy/build.gradle
Labels: from:contributor, cc-hackathon-2022

#21844 Update the providers-property-convention snippets to be cc compatible
  subprojects/docs/build.gradle
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/snippets/providers/propertyConvention/groovy/build.gradle
  subprojects/docs/src/snippets/providers/propertyConvention/kotlin/build.gradle.kts
Labels: from:contributor, cc-hackathon-2022

#21906 De-incubate SyncSpec
  subprojects/core-api/src/main/java/org/gradle/api/file/SyncSpec.java
Labels: @execution

#21893 CCH22-13: Adjust the snippets/dependencyManagement/managingTransitiveDependencies-excludeForConfiguration sample for configuration cache
  subprojects/docs/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-excludeForConfiguration/groovy/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-excludeForConfiguration/kotlin/build.gradle.kts
Labels: from:contributor

#21696 Disambiguate in precedence order when considering extra attributes
  subprojects/dependency-management/src/crossVersionTest/groovy/org/gradle/integtests/resolve/GradleMetadataJavaLibraryCrossVersionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/attributes/DefaultAttributesSchema.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/AttributeSelectionSchema.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/MultipleCandidateMatcher.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/attributes/DefaultAttributesSchemaTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/model/AttributePrecedenceSchemaAttributeMatcherTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/model/ComponentAttributeMatcherTest.groovy
  subprojects/docs/src/docs/userguide/dep-man/04-modeling-features/variant_attributes.adoc
Labels: @core

#21896 Make incremental task snippet CC compatible
  subprojects/docs/build.gradle
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/snippets/tasks/incrementalTask/groovy/build.gradle
  subprojects/docs/src/snippets/tasks/incrementalTask/kotlin/build.gradle.kts
Labels: from:contributor

#21709 Ignore progress events in ProjectBuilder
  subprojects/base-services/src/main/java/org/gradle/internal/operations/BuildOperationProgressEventEmitter.java
  subprojects/base-services/src/main/java/org/gradle/internal/operations/DefaultBuildOperationProgressEventEmitter.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GlobalScopeServices.java
  subprojects/core/src/main/java/org/gradle/testfixtures/internal/NoOpBuildOperationProgressEventEmitter.java
  subprojects/core/src/main/java/org/gradle/testfixtures/internal/ProjectBuilderImpl.java
  subprojects/core/src/main/java/org/gradle/testfixtures/internal/TestGlobalScopeServices.java
  subprojects/logging/src/test/groovy/org/gradle/internal/deprecation/LoggingDeprecatedFeatureHandlerTest.groovy
Labels: in:testing

#21721 Fix some JDK 19 related issues
  build-logic/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
  subprojects/base-services/src/main/java/org/gradle/api/JavaVersion.java
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/pmd/AbstractPmdPluginVersionIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/pmd/PmdPluginAuxclasspathIntegrationTest.groovy
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdPlugin.java
  subprojects/docs/src/docs/userguide/compatibility.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/DefaultGradleDistribution.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/LoggingHandler.groovy
  subprojects/internal-testing/src/main/groovy/org/gradle/util/TestPrecondition.groovy
  subprojects/language-groovy/src/integTest/groovy/org/gradle/groovy/GroovyDocOptionsIntegrationTest.groovy
  subprojects/language-groovy/src/main/java/org/gradle/api/tasks/javadoc/Groovydoc.java
  subprojects/language-groovy/src/testFixtures/groovy/org/gradle/testing/fixture/GroovyCoverage.groovy
  subprojects/messaging/src/test/groovy/org/gradle/internal/remote/internal/inet/MultiChoiceAddressTest.groovy
  subprojects/test-kit/build.gradle.kts
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/GradleRunnerArgumentsIntegrationTest.groovy
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/GradleRunnerGradleVersionIntegrationTest.groovy
  subprojects/test-kit/src/testFixtures/groovy/org/gradle/testkit/runner/BaseGradleRunnerIntegrationTest.groovy
  subprojects/testing-jvm/build.gradle.kts
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/spock/Spock2IntegrationSpec.groovy
Labels: @core, in:invoking-gradle

#21874 Make java fixtures snippet CC compatible
  subprojects/docs/build.gradle
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/snippets/java/fixtures/groovy/lib/build.gradle
  subprojects/docs/src/snippets/java/fixtures/kotlin/lib/build.gradle.kts
Labels: from:contributor, cc-hackathon-2022

#21840 Make fileCollections snippets compatible with configuration cache (#21814)
  subprojects/docs/build.gradle
  subprojects/docs/src/snippets/files/fileCollections/groovy/build.gradle
  subprojects/docs/src/snippets/files/fileCollections/kotlin/build.gradle.kts
Labels: from:contributor, cc-hackathon-2022

#21723 Clean up MultipleCandidateMatcher
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/attributes/DefaultAttributesSchema.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/AttributeSelectionSchema.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/AttributeSelectionUtils.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/ComponentAttributeMatcher.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/MultipleCandidateMatcher.java
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/model/ComponentAttributeMatcherTest.groovy
Labels: @core

#21947 Update wrapper to latest release nightly
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore

#21940 Remove unused content in InputFinterprinter
  subprojects/execution/src/main/java/org/gradle/internal/execution/fingerprint/InputFingerprinter.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/fingerprint/impl/DefaultInputFingerprinter.java
Labels: @execution

#21939 Lift access to project to configuration phase
  subprojects/docs/build.gradle
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/snippets/testing/test-suite-multi-configure-each-extracted/groovy/build.gradle
Labels: from:contributor, cc-hackathon-2022

#21917 Relax ZipSlip check
  subprojects/wrapper-shared/src/main/java/org/gradle/util/internal/ZipSlip.java
  subprojects/wrapper-shared/src/test/groovy/org/gradle/util/internal/ZipSlipTest.groovy
  subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy
Labels: in:file-tasks, @support

#21849 Use fixed timestamps in Minify transform
  build-logic/basics/src/main/kotlin/gradlebuild/basics/classanalysis/AnalyzeAndShade.kt
  subprojects/docs/src/docs/release/notes.md
Labels: from:contributor

#21925 Smoke test Kotlin 1.7.20-RC
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/KotlinGradlePluginVersions.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginSmokeTest.groovy
Labels: a:chore, @support

#21552 Update dependency locking docs
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/dep-man/02-declaring-dependency-versions/dependency_locking.adoc
Labels: from:contributor

#20310 Add default toolchains for MacOS.
  subprojects/docs/src/docs/userguide/native/native_software.adoc
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/gcc/AbstractGccCompatibleToolChain.java
  subprojects/platform-native/src/test/groovy/org/gradle/nativeplatform/toolchain/internal/gcc/AbstractGccCompatibleToolChainTest.groovy
Labels: in:native-platform, @core, from:contributor

#21198 support for --export-keys without --write-verification-metadata
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationSignatureCheckIntegTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationSignatureWriteIntegTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/StartParameterResolutionOverride.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/writer/WriteDependencyVerificationFile.java
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/dependency_verification.adoc
Labels: from:contributor

#21697 Create compile elements
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildDependencyGraphIntegrationTest.groovy
  subprojects/core-api/src/main/java/org/gradle/api/attributes/CompileView.java
  subprojects/core/src/integTest/groovy/org/gradle/api/NamedDomainObjectCollectionSchemaIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/artifacts/JavaEcosystemAttributesDescriber.java
  subprojects/core/src/main/java/org/gradle/api/internal/artifacts/JavaEcosystemSupport.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/artifacts/BundlingRulesTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/artifacts/JavaEcosystemAttributesDescriberTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/artifacts/JavaEcosystemSupportTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/PluginVariantResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/CrossProjectMultipleVariantSelectionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/DependenciesAttributesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/bundling/JavaBundlingResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ivy/IvyGradleMetadataRedirectionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenGradleMetadataRedirectionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/platforms/JavaPlatformResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/platforms/NativeAlignmentWithJavaPlatformResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/VariantAttributesRulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/VariantFilesMetadataRulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationWritingIntegTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/metadata/DefaultMavenImmutableAttributesFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/metadata/MavenImmutableAttributesFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/JavaEcosystemVariantDerivationStrategy.java
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/model/JavaEcosystemAttributeMatcherTest.groovy
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/DependencyInsightReportTaskIntegrationTest.groovy
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/DependencyInsightReportVariantDetailsIntegrationTest.groovy
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/OutgoingVariantsReportTaskIntegrationTest.groovy
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/ResolvableConfigurationsReportTaskIntegrationTest.groovy
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-metadataRule/tests/failRuntimeClasspathResolve.out
  subprojects/docs/src/snippets/dependencyManagement/inspectingDependencies-dependencyReason/tests/dependencyReasonReport.out
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-declaringCapabilities/tests/dependencyReport.out
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-declaringCapabilities/tests/dependencyReportReplaced.out
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/ivy/IvyFileModule.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/maven/AbstractMavenModule.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/maven/MavenJavaModule.groovy
  subprojects/ivy/src/testFixtures/groovy/org/gradle/api/publish/ivy/AbstractIvyRemoteLegacyPublishIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/groovy/GroovyJavaLibraryInteractionIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaApplicationOutgoingVariantsIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaLibraryConsumptionIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaLibraryCrossProjectTargetJvmVersionIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaLibraryOutgoingVariantsIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaLibraryPublishedTargetJvmVersionIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaProjectOutgoingVariantsIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/fixtures/AbstractJavaTestFixturesIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmEcosystemAttributesDetails.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmPluginServices.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmVariantBuilder.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/JvmEcosystemAttributesDetails.java
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/JavaBasePluginTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/jvm/internal/DefaultJvmPluginServicesTest.groovy
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/java-library-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-library-1.0.module
Labels: @core

#21405 macOS M1 toolchain integration for aarch64
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/CppApplicationInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/SwiftApplicationInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/SwiftLibraryInitIntegrationTest.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/xcode/AbstractXcodeCppProjectIntegrationTest.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/xcode/XcodeCompositeBuildIntegrationTest.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/xcode/XcodeMultipleCppProjectIntegrationTest.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/xcode/XcodeMultipleSwiftProjectIntegrationTest.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/xcode/XcodeSingleCppProjectIntegrationTest.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/xcode/XcodeSingleSwiftProjectIntegrationTest.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/xcode/fixtures/AbstractXcodeIntegrationSpec.groovy
  subprojects/ide-native/src/main/java/org/gradle/ide/xcode/tasks/GenerateXcodeProjectFileTask.java
  subprojects/ide-native/src/main/resources/org/gradle/ide/xcode/tasks/internal/default.xcsettings
  subprojects/ide-native/src/testFixtures/groovy/org/gradle/ide/xcode/fixtures/ProjectFile.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/DifferentJnaVersionInPluginIntegrationSpec.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/language/cpp/CppMissingToolchainIntegrationTest.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/language/objectivec/MixedObjectiveCIntegrationTest.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/language/swift/SwiftIncrementalCppInteroperabilityIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/ProcessCrashHandlingIntegrationTest.groovy
  subprojects/platform-native/src/integTest/groovy/org/gradle/nativeplatform/NativeDependentComponentsReportIntegrationTest.groovy
  subprojects/platform-native/src/integTest/groovy/org/gradle/nativeplatform/SharedLibrarySoNameIntegrationTest.groovy
  subprojects/platform-native/src/integTest/groovy/org/gradle/nativeplatform/sourceset/SourceSetLinkDependenciesIntegrationTest.groovy
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/MachineArchitecture.java
  subprojects/platform-native/src/test/groovy/org/gradle/nativeplatform/toolchain/internal/gcc/AbstractGccCompatibleToolChainTest.groovy
  subprojects/platform-native/src/testFixtures/groovy/org/gradle/nativeplatform/fixtures/AvailableToolChains.java
  subprojects/resources-s3/src/integTest/groovy/org/gradle/integtests/resource/s3/maven/MavenPublishS3IntegrationTest.groovy
  subprojects/tooling-native/src/crossVersionTest/groovy/org/gradle/language/cpp/tooling/r410/CppModelCrossVersionSpec.groovy
  subprojects/tooling-native/src/crossVersionTest/groovy/org/gradle/language/cpp/tooling/r52/CppModelCrossVersionSpec.groovy
Labels: @core

#21944 Simplify FileSystemAccess API
  subprojects/build-cache-packaging/src/test/groovy/org/gradle/caching/internal/packaging/impl/AbstractTarBuildCacheEntryPackerSpec.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/extensions/VirtualFileSystemExtensions.kt
  subprojects/core/src/main/java/org/gradle/cache/internal/DefaultFileContentCacheFactory.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/DefaultCachedClasspathTransformer.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/DefaultFileCollectionSnapshotter.java
  subprojects/core/src/test/groovy/org/gradle/cache/internal/DefaultFileContentCacheFactoryTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java
  subprojects/enterprise/src/main/java/org/gradle/internal/snapshot/impl/DefaultSnapshottingService.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/history/impl/DefaultOutputFilesRepositoryTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/history/impl/OutputSnapshotUtilTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/classpath/CachingClassSetAnalyzer.java
  subprojects/language-native/src/main/java/org/gradle/language/nativeplatform/internal/incremental/DefaultSourceIncludesResolver.java
  subprojects/language-native/src/main/java/org/gradle/language/nativeplatform/internal/incremental/IncrementalCompileFilesFactory.java
  subprojects/language-native/src/test/groovy/org/gradle/language/nativeplatform/internal/incremental/IncrementalCompileProcessorTest.groovy
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/FileSystemAccess.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java
  subprojects/snapshots/src/test/groovy/org/gradle/internal/fingerprint/impl/PathNormalizationStrategyTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/FileSystemSnapshotFilterTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/vfs/impl/AbstractFileSystemAccessTest.groovy
Labels: @execution

#21843 Report deprecations for deprecated members from the org.gradle.util package
  subprojects/build-init/build.gradle.kts
  subprojects/build-scan-performance/build.gradle.kts
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedLineEndingSensitivityIntegrationSpec.groovy
  subprojects/core/src/main/java/org/gradle/util/DistributionLocator.java
  subprojects/core/src/main/java/org/gradle/util/NameMatcher.java
  subprojects/core/src/main/java/org/gradle/util/NameValidator.java
  subprojects/core/src/main/java/org/gradle/util/RelativePathUtil.java
  subprojects/core/src/main/java/org/gradle/util/VersionNumber.java
  subprojects/core/src/main/java/org/gradle/util/WrapUtil.java
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/integ-test/build.gradle.kts
  subprojects/kotlin-dsl-integ-tests/build.gradle.kts
  subprojects/logging/build.gradle.kts
  subprojects/logging/src/main/java/org/gradle/api/internal/DocumentationRegistry.java
  subprojects/logging/src/main/java/org/gradle/internal/deprecation/DeprecationLogger.java
  subprojects/logging/src/main/java/org/gradle/internal/deprecation/DeprecationMessageBuilder.java
  subprojects/logging/src/main/java/org/gradle/internal/jvm/UnsupportedJavaRuntimeException.java
  subprojects/logging/src/main/java/org/gradle/util/CollectionUtils.java
  subprojects/logging/src/main/java/org/gradle/util/GFileUtils.java
  subprojects/logging/src/main/java/org/gradle/util/GUtil.java
  subprojects/logging/src/main/java/org/gradle/util/GradleVersion.java
  subprojects/logging/src/main/java/org/gradle/util/SingleMessageLogger.java
  subprojects/logging/src/main/java/org/gradle/util/TextUtil.java
  subprojects/logging/src/main/java/org/gradle/util/internal/DefaultGradleVersion.java
  subprojects/logging/src/test/groovy/org/gradle/api/internal/DocumentationRegistryTest.groovy
  subprojects/logging/src/test/groovy/org/gradle/util/GradleVersionTest.groovy
  subprojects/model-core/src/main/java/org/gradle/util/ClosureBackedAction.java
  subprojects/model-core/src/main/java/org/gradle/util/ConfigureUtil.java
  subprojects/resources/build.gradle.kts
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ArtifactoryAndDockerSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/NebulaPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/PlayPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/WithAndroidDeprecations.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/WithKotlinDeprecations.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/WithReportDeprecations.groovy
  subprojects/test-kit/build.gradle.kts
  subprojects/tooling-api/build.gradle.kts
  subprojects/tooling-api/src/integTest/groovy/org/gradle/integtests/tooling/ToolingApiClasspathIntegrationTest.groovy
Labels: a:chore, @support

#21915 Update master wrapper to latest nightly
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: a:chore

#21223 Let the Tooling API control system properties contributed from the client-side
  subprojects/docs/src/docs/release/notes.md
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/configuration/DaemonParameters.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/ConnectionOperationParameters.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/DaemonBuildActionExecuter.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/ProviderConnection.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/SystemPropertySetterExecuter.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/connection/ProviderOperationParameters.java
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r76/SystemPropertyPropagationCrossVersionTest.groovy
  subprojects/tooling-api/src/main/java/org/gradle/tooling/ConfigurableLauncher.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/LongRunningOperation.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/AbstractLongRunningOperation.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/parameters/ConsumerOperationParameters.java
Labels: @support

#21946 Move cleaning stale outputs to execution engine (take 2)
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/TaskExecution.java
  subprojects/core/src/main/java/org/gradle/execution/ProjectExecutionServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/ExecutionGradleServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementBuildScopeServices.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/UnitOfWork.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CleanupStaleOutputsStep.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CleanupStaleOutputsStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/StepSpec.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/StaleOutputIntegrationTest.groovy
Labels: @execution

#21931 Simplify deferred execution in execution engine
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/CacheableInvocation.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationNode.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformationStep.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformerInvocationFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformingAsyncArtifactListener.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/CacheableInvocationTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/ConsumerProvidedVariantFinderTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactoryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/TransformingAsyncArtifactListenerTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformInvocationTest.groovy
  subprojects/execution/src/integTest/groovy/org/gradle/internal/execution/IncrementalExecutionIntegrationTest.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/DeferredExecutionHandler.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/ExecutionEngine.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/impl/DefaultExecutionEngine.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/DeferredExecutionAwareStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/IdentifyStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/IdentityCacheStep.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/IdentityCacheStepTest.groovy
  subprojects/functional/src/main/java/org/gradle/internal/Deferrable.java
  subprojects/functional/src/main/java/org/gradle/internal/Try.java
  subprojects/functional/src/test/groovy/org/gradle/internal/DeferrableTest.groovy
Labels: @execution

#21604 Ensure deprecation warning includes the word deprecation
  subprojects/core/src/integTest/groovy/org/gradle/api/services/BuildServiceIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/ExclusiveVariantsIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/ParallelStaleOutputIntegrationTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyPublishBasicIntegTest.groovy
  subprojects/logging/src/main/java/org/gradle/internal/deprecation/DeprecationLogger.java
  subprojects/logging/src/main/java/org/gradle/internal/deprecation/DeprecationMessageBuilder.java
  subprojects/logging/src/main/java/org/gradle/internal/deprecation/DeprecationTimeline.java
  subprojects/logging/src/test/groovy/org/gradle/internal/deprecation/DeprecationMessagesTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishBasicIntegTest.groovy
  subprojects/model-core/src/integTest/groovy/org/gradle/api/provider/ProviderConventionMappingIntegrationTest.groovy
  subprojects/model-core/src/testFixtures/groovy/org/gradle/internal/reflect/validation/ValidationMessageChecker.groovy
  subprojects/plugins/src/main/java/org/gradle/api/internal/java/usagecontext/ConfigurationVariantMapping.java
Labels: a:chore

#21887 Use `projectLayout` instead of `project`
  subprojects/docs/build.gradle
  subprojects/docs/src/snippets/buildCache/cacheable-bundle/groovy/build.gradle
  subprojects/docs/src/snippets/buildCache/cacheable-bundle/kotlin/build.gradle.kts
Labels: from:contributor, cc-hackathon-2022

#21211 Configure Kotlin IO action timeout via system property
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/concurrent/BuildServices.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/concurrent/DefaultAsyncIOScopeFactoryTest.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/concurrent/JavaSystemPropertiesAsyncIOScopeSettingsTest.kt
Labels: a:feature, in:kotlin-dsl, from:contributor

#21994 Let checkstyle allow nested blocks in switch case
  build-logic-commons/code-quality-rules/src/main/resources/checkstyle/checkstyle.xml
Labels: a:chore, in:building-gradle

#21992 Adjust snippet for cc
  subprojects/docs/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-conditionalSubstitutionRule/groovy/consumer/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-conditionalSubstitutionRule/kotlin/consumer/build.gradle.kts
Labels: in:documentation, from:contributor, cc-hackathon-2022

#21831 Update japicmp-gradle-plugin to 0.4.1
  build-logic/binary-compatibility/src/main/groovy/gradlebuild.binary-compatibility.gradle
  build-logic/binary-compatibility/src/main/groovy/gradlebuild/binarycompatibility/BinaryCompatibilityHelper.groovy
  build-logic/binary-compatibility/src/test/kotlin/gradlebuild/binarycompatibility/AbstractBinaryCompatibilityTest.kt
  build-logic/build-platform/build.gradle.kts
  build-logic/buildquality/build.gradle.kts
  build-logic/buildquality/src/main/kotlin/gradlebuild.configure-ci-artifacts.gradle.kts
  build-logic/uber-plugins/build.gradle.kts
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildSanityCheckConfigurationCacheSmokeTest.groovy
Labels: @core

#21977 Make task preCompileJsps compatible with configuration cache
  subprojects/docs/build.gradle
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/snippets/dependencyManagement/definingUsingConfigurations-custom/groovy/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/definingUsingConfigurations-custom/kotlin/build.gradle.kts
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/dependencymanagement/SamplesDefiningUsingConfigurationsIntegrationTest.groovy
Labels: in:documentation, from:contributor, cc-hackathon-2022

#22003 Do not resolve FileCollections in non-file task inputs
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/InputParameterUtils.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/DefaultTaskInputsTest.groovy
Labels: @execution

#21952 Finalize `ProjectLayout.buildDirectory` when writing to the configuration cache
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheLifecyclePluginIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
Labels: in:configuration-cache, @configuration-cache

#21996 Let `ValueSnapshotter` handle instances of `OpaqueComponentIdentifier`
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheDependencyResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementValueSnapshotterSerializerRegistry.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ComponentIdentifierSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/metadata/ComponentFileArtifactIdentifierSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/local/model/ComponentFileArtifactIdentifier.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ComponentIdentifierSerializerTest.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/SrcDistributionIntegrationSpec.groovy
  subprojects/tooling-api/src/main/java/org/gradle/tooling/events/task/internal/DefaultTaskOperationDescriptor.java
Labels: @configuration-cache, in:dependency-resolution, in:input-normalization

#21960 Fix Configuration Cache in archivesChangedBaseName
  subprojects/docs/build.gradle
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/snippets/files/archivesChangedBaseName/groovy/build.gradle
  subprojects/docs/src/snippets/files/archivesChangedBaseName/kotlin/build.gradle.kts
Labels: in:documentation, from:contributor, cc-hackathon-2022

#21343 Fix inefficient `Optional.orElse` usage by Cpp and Swift plugins
  subprojects/language-native/src/main/java/org/gradle/language/cpp/plugins/CppApplicationPlugin.java
  subprojects/language-native/src/main/java/org/gradle/language/cpp/plugins/CppLibraryPlugin.java
  subprojects/language-native/src/main/java/org/gradle/language/swift/plugins/SwiftApplicationPlugin.java
  subprojects/language-native/src/main/java/org/gradle/language/swift/plugins/SwiftLibraryPlugin.java
  subprojects/testing-native/src/main/java/org/gradle/nativeplatform/test/cpp/plugins/CppUnitTestPlugin.java
Labels: from:contributor

#22022 Fix wrong psoutput cleanup code
  build-logic/cleanup/src/main/java/gradlebuild/cleanup/services/KillLeakingJavaProcesses.java
Labels: @dev-productivity

#22019 Warn explicitly if performance base version is wrong
  build-logic/performance-testing/src/main/kotlin/gradlebuild/performance/tasks/BuildCommitDistribution.kt
Labels: @dev-productivity

#22009 Fail if executable does not exist
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
  subprojects/language-java/src/test/groovy/org/gradle/api/tasks/compile/JavaCompileTest.groovy
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java
  subprojects/testing-jvm/src/test/groovy/org/gradle/api/tasks/testing/TestTest.groovy
Labels: in:java-plugins

#22029 Remove AntlrSourceVirtualDirectory.xml DSL documentation
  subprojects/docs/src/docs/dsl/org.gradle.api.plugins.antlr.AntlrSourceVirtualDirectory.xml
Labels: a:chore, in:antlr-plugin

#22011 Ensure `ProgressLoggingFixture` build service is fully initialized
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/ProgressLoggingFixture.groovy
Labels: in:testing, a:chore, in:building-gradle, @configuration-cache

#21986 Required fixes for future Groovy 4 compatibility
  subprojects/code-quality/build.gradle.kts
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcPluginVersionIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcRelocationIntegrationTest.groovy
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/PmdInvoker.groovy
  subprojects/code-quality/src/testFixtures/groovy/org/gradle/quality/integtest/fixtures/CodeNarcCoverage.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/VariantAwareResolutionWithConfigurationAttributesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/IvySpecificComponentMetadataRulesIntegrationTest.groovy
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/PropertyReportTaskIntegrationTest.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/AllDistributionIntegrationSpec.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DocsDistributionIntegrationSpec.groovy
  subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/AbstractSourcesAndJavadocJarsIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/PluginConfigurationAttributesIntegrationTest.groovy
  subprojects/internal-testing/src/main/groovy/org/gradle/util/TestPrecondition.groovy
  subprojects/launcher/src/test/groovy/org/gradle/launcher/cli/WelcomeMessageActionTest.groovy
  subprojects/model-core/src/main/java/org/gradle/internal/metaobject/BeanDynamicObject.java
  subprojects/model-core/src/test/groovy/org/gradle/api/internal/provider/CollectionPropertySpec.groovy
  subprojects/model-core/src/test/groovy/org/gradle/api/internal/provider/MapPropertySpec.groovy
  subprojects/model-core/src/test/groovy/org/gradle/internal/instantiation/generator/AsmBackedClassGeneratorTest.java
  subprojects/model-core/src/test/groovy/org/gradle/internal/reflect/ClassInspectorTest.groovy
  subprojects/model-core/src/test/groovy/org/gradle/internal/reflect/JavaPropertyReflectionUtilTest.groovy
  subprojects/model-core/src/test/groovy/org/gradle/internal/reflect/PropertyAccessorTypeTest.groovy
  subprojects/model-core/src/test/groovy/org/gradle/model/internal/manage/binding/DefaultStructBindingsStoreTest.groovy
  subprojects/model-core/src/testFixtures/groovy/org/gradle/api/internal/provider/PropertySpec.groovy
  subprojects/model-core/src/testFixtures/groovy/org/gradle/api/internal/provider/ProviderTestUtil.java
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/AbstractPluginValidationIntegrationSpec.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/JvmTestSuite.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java
  subprojects/reporting/src/integTest/groovy/org/gradle/api/reporting/plugins/BuildDashboardPluginIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/SamplesCodeQualityIntegrationTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleVersionsPluginSmokeTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/fixture/JUnitMultiVersionIntegrationSpec.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testsuites/TestSuitesIntegrationTest.groovy
  subprojects/testing-jvm/src/testFixtures/groovy/org/gradle/api/internal/tasks/testing/junit/JUnitTestClassProcessorData.groovy
  subprojects/testing-jvm/src/testFixtures/groovy/org/gradle/testing/fixture/JUnitCoverage.groovy
Labels: in:groovy-plugin, in:groovy-dsl, @core

#22032 Fix Configuration Cache in kotlinDsl multiProjectBuild sample.
  subprojects/docs/build.gradle
  subprojects/docs/src/snippets/kotlinDsl/multiProjectBuild/kotlin/build.gradle.kts
Labels: in:documentation, from:contributor, cc-hackathon-2022

#22024 Mark some failing native tests on mac m1
  subprojects/language-native/src/integTest/groovy/org/gradle/language/nativeplatform/NativeLanguageSamplesIntegrationTest.groovy
  subprojects/platform-native/src/integTest/groovy/org/gradle/nativeplatform/BinaryFlavorsIntegrationTest.groovy
  subprojects/platform-native/src/integTest/groovy/org/gradle/nativeplatform/LibraryApiDependenciesIntegrationTest.groovy
  subprojects/platform-native/src/integTest/groovy/org/gradle/nativeplatform/LibraryBinariesIntegrationTest.groovy
  subprojects/platform-native/src/integTest/groovy/org/gradle/nativeplatform/LibraryDependenciesIntegrationTest.groovy
  subprojects/platform-native/src/integTest/groovy/org/gradle/nativeplatform/NativePlatformSamplesIntegrationTest.groovy
  subprojects/platform-native/src/integTest/groovy/org/gradle/nativeplatform/PrebuiltLibrariesIntegrationTest.groovy
  subprojects/testing-native/src/integTest/groovy/org/gradle/nativeplatform/test/xctest/XCTestTestFrameworkIntegrationTest.groovy
Labels: @dev-productivity

#22045 Bump version for removing validation warnings to 9.0
  subprojects/core/src/main/java/org/gradle/execution/DefaultWorkValidationWarningRecorder.java
  subprojects/core/src/main/java/org/gradle/execution/plan/DefaultNodeValidator.java
  subprojects/model-core/src/testFixtures/groovy/org/gradle/internal/reflect/validation/ValidationMessageChecker.groovy
Labels: @execution

#22025 Improve visiting properties in the execution engine
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintWriter.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/TaskNodeCodec.kt
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/project/taskfactory/TaskPropertyNamingIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskInputs.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/StaticValue.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/TaskExecution.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/CompositePropertyVisitor.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/DefaultInputFilePropertySpec.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/DefaultTaskProperties.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/FileParameterUtils.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/GetInputFilesVisitor.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/InputFilePropertySpec.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/PropertyValue.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/PropertyVisitor.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/AbstractInputFilePropertyAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/NestedBeanAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/bean/AbstractNestedRuntimeBeanNode.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/bean/NestedRuntimeBeanNode.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/DefaultWorkInputListeners.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/DefaultTaskInputsTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/DefaultPropertyWalkerTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/api/internal/file/TestFiles.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformationRegistrationFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/DefaultDependenciesAccessors.java
  subprojects/enterprise/build.gradle.kts
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/test/impl/DefaultTestTaskPropertiesService.java
  subprojects/execution/src/integTest/groovy/org/gradle/internal/execution/IncrementalExecutionIntegrationTest.groovy
  subprojects/execution/src/integTest/groovy/org/gradle/internal/execution/UnitOfWorkBuilder.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/UnitOfWork.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/WorkInputListener.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/WorkInputListeners.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/fingerprint/InputFingerprinter.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/fingerprint/impl/DefaultInputFingerprinter.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/history/changes/DefaultIncrementalInputProperties.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/impl/DefaultOutputSnapshotter.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/BuildCacheStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CaptureStateAfterExecutionStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CaptureStateBeforeExecutionStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CleanupStaleOutputsStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CreateOutputsStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/RemovePreviousOutputsStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ResolveChangesStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/SkipEmptyWorkStep.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/fingerprint/impl/DefaultInputFingerprinterTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/impl/DefaultOutputSnapshotterTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CaptureStateAfterExecutionStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CleanupStaleOutputsStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CreateOutputsStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/RemovePreviousOutputsStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/SkipEmptyWorkStepTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/validation/package-info.java
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/AccessorsClassPath.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/PluginAccessorsClassPath.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/KotlinScriptEvaluator.kt
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/continuous/AccumulateBuildInputsListener.java
  subprojects/launcher/src/test/groovy/org/gradle/tooling/internal/provider/continuous/ContinuousBuildActionExecutorTest.groovy
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/FileCollectionFingerprint.java
Labels: @execution

#22035 fix(cch22-7): `snippets/dependencyManagement/customizingResolution-classifierSubstitutionRule` sample for configuration cache
  subprojects/docs/build.gradle
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/resolution_rules.adoc
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-classifierSubstitutionRule/groovy/consumer/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-classifierSubstitutionRule/groovy/lib/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-classifierSubstitutionRule/kotlin/consumer/build.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-classifierSubstitutionRule/kotlin/lib/build.gradle.kts
Labels: from:contributor, cc-hackathon-2022

#22017 Fix Configuration Cache in disablingVerification sample.
  subprojects/docs/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/dependencyVerification-disablingVerification/groovy/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/dependencyVerification-disablingVerification/kotlin/build.gradle.kts
Labels: in:documentation, from:contributor, cc-hackathon-2022

#22069 Upgradle to latest nightly
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: @execution

#22070 Merge release into master
  subprojects/core/src/integTest/groovy/org/gradle/api/FinalizerTaskIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java
  subprojects/core/src/main/java/org/gradle/execution/plan/DefaultFinalizedExecutionPlan.java
  subprojects/core/src/main/java/org/gradle/execution/plan/DetermineExecutionPlanAction.java
  subprojects/core/src/main/java/org/gradle/execution/plan/ExecutionPlan.java
  subprojects/core/src/main/java/org/gradle/execution/plan/FinalizerGroup.java
  subprojects/core/src/main/java/org/gradle/execution/plan/HasFinalizers.java
  subprojects/core/src/main/java/org/gradle/execution/plan/Node.java
  subprojects/core/src/main/java/org/gradle/execution/plan/NodeGroup.java
  subprojects/core/src/main/java/org/gradle/execution/plan/TaskNode.java
  subprojects/core/src/test/groovy/org/gradle/execution/plan/DefaultExecutionPlanParallelTest.groovy
  subprojects/core/src/test/groovy/org/gradle/execution/plan/DefaultExecutionPlanTest.groovy
  subprojects/docs/src/docs/userguide/authoring-builds/working_with_files.adoc
Labels: @execution

#22020 Support skipping all dependency builds
  .teamcity/src/main/kotlin/common/extensions.kt
  .teamcity/src/main/kotlin/common/performance-test-extensions.kt
  .teamcity/src/main/kotlin/configurations/GradleBuildConfigurationDefaults.kt
  .teamcity/src/main/kotlin/configurations/TestPerformanceTest.kt
  .teamcity/src/main/kotlin/projects/CheckProject.kt
Labels: @dev-productivity

#22077 Fix performance baseline display
  .teamcity/src/main/kotlin/configurations/PerformanceTestsPass.kt
Labels: @dev-productivity

#22026 Disable stacktrace check for MavenPublishS3ErrorsIntegrationTest
  subprojects/resources-s3/src/integTest/groovy/org/gradle/integtests/resource/s3/maven/MavenPublishS3ErrorsIntegrationTest.groovy
Labels: @dev-productivity

#21920 Deprecate the DependencyFactory class for removal in Gradle 8.0.
  subprojects/core/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/DependencyFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/notations/DependencyNotationParser.java
  subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/resolver/IdeDependencySet.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GrettySmokeTest.groovy
Labels: @core

#22039 Adjust snippet for configuration cache
  subprojects/docs/build.gradle
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-capabilitySubstitutionRule/groovy/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-capabilitySubstitutionRule/kotlin/build.gradle.kts
Labels: in:documentation, from:contributor, cc-hackathon-2022

#22074 Configuration Cache fix for managingTransitiveDependencies
  subprojects/docs/build.gradle
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-excludeForDependency/groovy/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-excludeForDependency/kotlin/build.gradle.kts
Labels: in:documentation, from:contributor, cc-hackathon-2022

#22059 Speculative fix for Configuration Cache in java7CrossCompilation sample
  subprojects/docs/build.gradle
  subprojects/docs/src/snippets/java/crossCompilation/groovy/build.gradle
  subprojects/docs/src/snippets/java/crossCompilation/kotlin/build.gradle.kts
Labels: in:documentation, from:contributor, cc-hackathon-2022

#22079 CompileAllProduction -> CompileAll
  .teamcity/src/main/kotlin/common/extensions.kt
  .teamcity/src/main/kotlin/common/performance-test-extensions.kt
  .teamcity/src/main/kotlin/configurations/CompileAll.kt
  .teamcity/src/main/kotlin/configurations/GradleBuildConfigurationDefaults.kt
  .teamcity/src/main/kotlin/configurations/Gradleception.kt
  .teamcity/src/main/kotlin/model/CIBuildModel.kt
  .teamcity/src/main/kotlin/util/RerunFlakyTest.kt
Labels: @dev-productivity

#22096 Merge release into master
  released-versions.json
  subprojects/core/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/DependencyFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/notations/DependencyNotationParser.java
  subprojects/docs/src/docs/userguide/authoring-builds/more_about_tasks.adoc
  subprojects/docs/src/docs/userguide/reference/command_line_interface.adoc
  subprojects/docs/src/docs/userguide/running-builds/build_environment.adoc
  subprojects/docs/src/docs/userguide/running-builds/file_system_watching.adoc
  subprojects/docs/src/docs/userguide/running-builds/gradle_daemon.adoc
  subprojects/docs/src/main/resources/header.html
  subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/resolver/IdeDependencySet.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GrettySmokeTest.groovy
Labels: @dev-productivity

#22049 Remove `decorate*Exception` from `UnitOfWork`
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyErrorIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyPermissionsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopySpecIntegrationSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/UnreadableCopyDestinationFixture.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/UntrackedTaskIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/TaskExecution.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/UnitOfWork.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CaptureStateAfterExecutionStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CaptureStateBeforeExecutionStep.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CaptureStateAfterExecutionStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CaptureStateBeforeExecutionStepTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy
  subprojects/logging/src/main/java/org/gradle/internal/deprecation/DocumentedFailure.java
Labels: @execution

#22099 Reduce number of file changes for soak test on macOS
  subprojects/soak/src/integTest/groovy/org/gradle/vfs/FileSystemWatchingSoakTest.groovy
Labels: @execution

#22038 Adjust snippets for configuration cache
  subprojects/docs/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-ivyMetadataRule/groovy/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-ivyMetadataRule/kotlin/build.gradle.kts
Labels: in:documentation, from:contributor, cc-hackathon-2022

#22102 Improve Deferrable
  subprojects/functional/src/main/java/org/gradle/internal/Deferrable.java
  subprojects/functional/src/test/groovy/org/gradle/internal/DeferrableTest.groovy
Labels: @execution

#22104 Restore TAPI compatibility with Java 6 and old Gradle versions
  subprojects/base-services/src/main/java/org/gradle/util/internal/TextUtil.java
  subprojects/build-option/build.gradle.kts
  subprojects/build-option/src/main/java/org/gradle/internal/buildoption/Origin.java
  subprojects/logging/src/main/java/org/gradle/internal/deprecation/DeprecatedFeatureUsage.java
  subprojects/logging/src/main/java/org/gradle/internal/logging/LoggingConfigurationBuildOptions.java
Labels: a:bug, in:tooling-api

#22036 Adds support for EnableExternalDTDLoad property to Checkstyle Plugin
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginExternalDTDOptionIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginMultiProjectTest.groovy
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/Checkstyle.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CheckstyleExtension.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CheckstylePlugin.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/CheckstyleInvocationException.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/CheckstyleInvoker.groovy
  subprojects/docs/src/docs/dsl/org.gradle.api.plugins.quality.Checkstyle.xml
  subprojects/docs/src/docs/dsl/org.gradle.api.plugins.quality.CheckstyleExtension.xml
  subprojects/docs/src/docs/release/notes.md
Labels: @core

#22118 Clean up downloaded JDKs after test
  subprojects/soak/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainDownloadSoakTest.groovy
Labels: @dev-productivity

#22115 Upgrade smoke tested AGP versions
  gradle/dependency-management/agp-versions.properties
Labels: a:chore, in:building-gradle

#22087 Ignore missing roots when fingerprinting
  subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/DefaultFileCollectionSnapshotter.java
  subprojects/core/src/test/groovy/org/gradle/internal/fingerprint/impl/AbsolutePathFileCollectionFingerprinterTest.groovy
  subprojects/language-native/src/test/groovy/org/gradle/language/assembler/tasks/AssemblerTest.groovy
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/impl/AbsolutePathFingerprintingStrategy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/impl/IgnoredPathFingerprintingStrategy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/impl/MissingRootAndDuplicateIgnoringFileSystemSnapshotVisitor.java
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/impl/NameOnlyFingerprintingStrategy.java
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/impl/RelativePathFingerprintingStrategy.java
  subprojects/snapshots/src/test/groovy/org/gradle/internal/fingerprint/impl/BrokenSymlinkNormalizationStrategyTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/fingerprint/impl/PathNormalizationStrategyTest.groovy
Labels: @execution

#22123 Add Java Toolchain SPI information and example
  subprojects/docs/src/docs/release/notes.md
Labels: @support

#22114 Revert compileElements
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildDependencyGraphIntegrationTest.groovy
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/Dependencies.java
  subprojects/core-api/src/main/java/org/gradle/api/attributes/CompileView.java
  subprojects/core/src/integTest/groovy/org/gradle/api/NamedDomainObjectCollectionSchemaIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/artifacts/JavaEcosystemAttributesDescriber.java
  subprojects/core/src/main/java/org/gradle/api/internal/artifacts/JavaEcosystemSupport.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/artifacts/BundlingRulesTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/artifacts/JavaEcosystemAttributesDescriberTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/artifacts/JavaEcosystemSupportTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/PluginVariantResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/CrossProjectMultipleVariantSelectionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/DependenciesAttributesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/bundling/JavaBundlingResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ivy/IvyGradleMetadataRedirectionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenGradleMetadataRedirectionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/platforms/JavaPlatformResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/platforms/NativeAlignmentWithJavaPlatformResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/VariantAttributesRulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/VariantFilesMetadataRulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationWritingIntegTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/metadata/DefaultMavenImmutableAttributesFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/metadata/MavenImmutableAttributesFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/JavaEcosystemVariantDerivationStrategy.java
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/model/JavaEcosystemAttributeMatcherTest.groovy
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/DependencyInsightReportTaskIntegrationTest.groovy
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/DependencyInsightReportVariantDetailsIntegrationTest.groovy
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/OutgoingVariantsReportTaskIntegrationTest.groovy
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/ResolvableConfigurationsReportTaskIntegrationTest.groovy
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/jvm/jvm_test_suite_plugin.adoc
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-metadataRule/tests/failRuntimeClasspathResolve.out
  subprojects/docs/src/snippets/dependencyManagement/inspectingDependencies-dependencyReason/tests/dependencyReasonReport.out
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-declaringCapabilities/tests/dependencyReport.out
  subprojects/docs/src/snippets/dependencyManagement/managingTransitiveDependencies-declaringCapabilities/tests/dependencyReportReplaced.out
  subprojects/docs/src/snippets/testing/test-suite-configure-suite-dependencies-project/groovy/build.gradle
  subprojects/docs/src/snippets/testing/test-suite-configure-suite-dependencies-project/kotlin/build.gradle.kts
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/ivy/IvyFileModule.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/maven/AbstractMavenModule.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/maven/MavenJavaModule.groovy
  subprojects/ivy/src/testFixtures/groovy/org/gradle/api/publish/ivy/AbstractIvyRemoteLegacyPublishIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/ProjectInternalViewDependencyIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/groovy/GroovyJavaLibraryInteractionIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaApplicationOutgoingVariantsIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaLibraryConsumptionIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaLibraryCrossProjectTargetJvmVersionIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaLibraryOutgoingVariantsIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaLibraryPublishedTargetJvmVersionIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaProjectOutgoingVariantsIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/fixtures/AbstractJavaTestFixturesIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmComponentDependencies.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmEcosystemAttributesDetails.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmPluginServices.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmVariantBuilder.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/JvmEcosystemAttributesDetails.java
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/JavaBasePluginTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/jvm/internal/DefaultJvmPluginServicesTest.groovy
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/java-library-1.0.module
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/gmm-example/expected-metadata/kotlin-library-1.0.module
Labels: @core

#22109 Add documentation for --continue option
  subprojects/docs/src/docs/userguide/jvm/jacoco_report_aggregation_plugin.adoc
  subprojects/docs/src/docs/userguide/jvm/test_report_aggregation_plugin.adoc
  subprojects/docs/src/docs/userguide/reference/command_line_interface.adoc
Labels: @core

#22130 Cast to workaround GROOVY-10765
  subprojects/execution/src/integTest/groovy/org/gradle/internal/execution/UnitOfWorkBuilder.groovy
Labels: @core

#21938 Add documentation for -- delimiter in command line
  subprojects/cli/src/main/java/org/gradle/cli/CommandLineParser.java
  subprojects/cli/src/test/groovy/org/gradle/cli/CommandLineParserTest.groovy
  subprojects/docs/src/docs/userguide/extending-gradle/custom_tasks.adoc
  subprojects/docs/src/docs/userguide/reference/command_line_interface.adoc
  subprojects/launcher/build.gradle.kts
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/cli/TaskOptionsSpec.groovy
  subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy
Labels: @core

#21999 Fix init script snippets under config cache
  subprojects/docs/build.gradle
  subprojects/docs/src/snippets/initScripts/configurationInjection/groovy/build.gradle
  subprojects/docs/src/snippets/initScripts/configurationInjection/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/initScripts/plugins/groovy/build.gradle
  subprojects/docs/src/snippets/initScripts/plugins/kotlin/build.gradle.kts
Labels: @configuration-cache, in:documentation

#22141 Let init incubating mode generate included build logic build in `build-logic`
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/MultiProjectJvmApplicationInitIntegrationTest.groovy
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/LanguageSpecificAdaptor.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/SimpleGlobalFilesBuildSettingsDescriptor.java
  subprojects/docs/src/docs/release/notes.md
Labels: in:build-init-plugin, a:feature

#22149 Fix expected deprecation message
  subprojects/soak/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainDownloadSoakTest.groovy
Labels: in:toolchains

#22129 Let configuration cache errors surface to the top
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheDependencyResolutionFailuresIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheDependencyResolutionIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheProblemReportingIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheException.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ProblemsListener.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/beans/BeanPropertyWriter.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/CachedEnvironmentStateCodec.kt
Labels: in:configuration-cache, @configuration-cache

#22151 Fix getter generation for String constant fields
  subprojects/core/src/main/java/org/gradle/initialization/MixInLegacyTypesClassLoader.java
  subprojects/core/src/test/groovy/org/gradle/initialization/MixInLegacyTypesClassLoaderTest.groovy
Labels: in:groovy-dsl, @core

#21988 Fix maven conditional publishing snippets
  subprojects/docs/src/snippets/maven-publish/conditional-publishing/groovy/build.gradle
  subprojects/docs/src/snippets/maven-publish/conditional-publishing/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/maven-publish/publish-artifact/kotlin/build.gradle.kts
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/SamplesMavenPublishIntegrationTest.groovy
Labels: in:publishing-plugins, @configuration-cache, in:documentation

#22133 Upgrade CodeNarc to 3.1.0
  build-logic-commons/code-quality-rules/build.gradle.kts
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.code-quality.gradle.kts
  build-logic/build-platform/build.gradle.kts
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CodeNarcPlugin.java
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/snippets/codeQuality/codeQuality/groovy/build.gradle
  subprojects/docs/src/snippets/codeQuality/codeQuality/kotlin/build.gradle.kts
Labels: in:codenarc-plugin, @core

#21965 Make `tasks/incrementalBuild-customTaskClass` snippets compatible with configuration cache
  subprojects/docs/build.gradle
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/authoring-builds/more_about_tasks.adoc
  subprojects/docs/src/snippets/tasks/incrementalBuild-customTaskClass/groovy/build.gradle
  subprojects/docs/src/snippets/tasks/incrementalBuild-customTaskClass/groovy/buildSrc/src/main/java/org/example/ProcessTemplates.java
  subprojects/docs/src/snippets/tasks/incrementalBuild-customTaskClass/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/tasks/incrementalBuild-customTaskClass/kotlin/buildSrc/src/main/java/org/example/ProcessTemplates.java
  subprojects/docs/src/snippets/tasks/incrementalBuild-customTaskClass/tests/customTaskClassWithInputOutputAnnotationsUpToDateWithCC.out
  subprojects/docs/src/snippets/tasks/incrementalBuild-customTaskClass/tests/customTaskClassWithInputOutputAnnotationsUpToDateWithoutCC.out
  subprojects/docs/src/snippets/tasks/incrementalBuild-customTaskClass/tests/customTaskClassWithInputOutputAnnotationsWithCC.sample.conf
  subprojects/docs/src/snippets/tasks/incrementalBuild-customTaskClass/tests/customTaskClassWithInputOutputAnnotationsWithoutCC.sample.conf
Labels: in:documentation, from:contributor, cc-hackathon-2022

#22156 Require exclusive access to build agent host for performance tests
  .teamcity/src/main/kotlin/common/extensions.kt
  .teamcity/src/main/kotlin/common/performance-test-extensions.kt
  .teamcity/src/main/kotlin/configurations/Gradleception.kt
  .teamcity/src/main/kotlin/configurations/SmokeTests.kt
  .teamcity/src/main/kotlin/promotion/BasePromotionBuildType.kt
Labels: @dev-productivity

#22160 Upgrade `release` wrapper to latest nightly
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore

#22162 Relax assertion in FileSystemWatchingSoakTest
  subprojects/soak/src/integTest/groovy/org/gradle/vfs/FileSystemWatchingSoakTest.groovy
Labels: @execution

#22164 Fix default baseline for adhoc performance test
  .teamcity/src/main/kotlin/util/AdHocPerformanceScenario.kt
Labels: @dev-productivity

#22037 Adjust snippets for configuration cache
  subprojects/docs/build.gradle
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-metadataRule/groovy/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-metadataRule/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-metadataRule/tests/componentMetadataRules.sample.conf
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-metadataRule/tests/failRuntimeClasspathResolve.out
Labels: in:documentation, from:contributor, cc-hackathon-2022

#22042 Fix tutorial snippets with configuration cache
  subprojects/docs/build.gradle
  subprojects/docs/src/snippets/tasks/customTaskWithFileProperty/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/tasks/customTaskWithMissingFileProperty/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/tutorial/configureObject/groovy/build.gradle
  subprojects/docs/src/snippets/tutorial/configureObject/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/tutorial/configureObject/tests/configureObject.out
  subprojects/docs/src/snippets/tutorial/configureObjectUsingScript/groovy/build.gradle
  subprojects/docs/src/snippets/tutorial/configureObjectUsingScript/groovy/other.gradle
  subprojects/docs/src/snippets/tutorial/configureObjectUsingScript/tests/configureObjectUsingScript.out
  subprojects/docs/src/snippets/tutorial/extraProperties/groovy/build.gradle
  subprojects/docs/src/snippets/tutorial/extraProperties/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/tutorial/mkdirTrap/groovy/build.gradle
  subprojects/docs/src/snippets/tutorial/mkdirTrap/kotlin/build.gradle.kts
Labels: @configuration-cache, in:documentation

#22142 Allow checking if Java installation matches current JVM
  subprojects/language-groovy/src/test/groovy/org/gradle/api/internal/tasks/compile/DefaultGroovyJavaJointCompileSpecFactoryTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/AbstractJavaCompileSpecFactory.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/DefaultJavaCompileSpecFactoryTest.groovy
  subprojects/platform-jvm/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainIntegrationTest.groovy
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/JavaInstallationMetadata.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchain.java
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/toolchain/internal/JavaToolchainTest.groovy
  subprojects/scala/src/test/groovy/org/gradle/api/internal/tasks/scala/DefaultScalaJavaJointCompileSpecFactoryTest.groovy
  subprojects/scala/src/test/groovy/org/gradle/scala/compile/internal/ScalaCompileOptionsConfigurerTest.groovy
Labels: in:toolchains

#21595 Docs: update unavailable task property annotations in the runtime API
  subprojects/docs/src/docs/userguide/authoring-builds/more_about_tasks.adoc
Labels: @support, from:contributor

#22166 Update santa tracker version
  build-logic/performance-testing/src/main/groovy/gradlebuild.performance-templates.gradle
  subprojects/smoke-test/build.gradle.kts
Labels: @execution

#22158 Upgrade the spock version used in samples/snippets
  build-logic/build-update-utils/src/main/kotlin/gradlebuild/buildutils/tasks/UpdateInitPluginTemplateVersionFile.kt
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/library-versions.properties
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/groovy/buildSrc/build.gradle
  subprojects/docs/src/samples/build-organization/publishing-convention-plugins/groovy/convention-plugins/build.gradle
  subprojects/docs/src/snippets/configurationCache/testKit/groovy/build.gradle
  subprojects/docs/src/snippets/developingPlugins/testingPlugins/groovy/url-verifier-plugin/build.gradle
  subprojects/docs/src/snippets/developingPlugins/testingPlugins/kotlin/url-verifier-plugin/build.gradle.kts
Labels: @core, in:testing-testng

#22157 Choose correct spock version based on bundled Groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java
Labels: @core, in:test-suites

#22094 Allow Provider#zip combiner to return null
  subprojects/core-api/src/main/java/org/gradle/api/provider/Provider.java
  subprojects/core-api/src/main/java/org/gradle/api/provider/ProviderFactory.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/DefaultProjectLayoutTest.groovy
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/BiProvider.java
  subprojects/model-core/src/test/groovy/org/gradle/api/internal/provider/DefaultProviderFactoryTest.groovy
  subprojects/model-core/src/test/groovy/org/gradle/api/internal/provider/WithSideEffectProviderTest.groovy
Labels: @core

#22174 Update the spock version used in additional samples/snippets
  subprojects/docs/src/snippets/testKit/automaticClasspathInjectionCustomTestSourceSet/groovy/build.gradle
  subprojects/docs/src/snippets/testKit/automaticClasspathInjectionCustomTestSourceSet/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/testKit/automaticClasspathInjectionQuickstart/groovy/build.gradle
  subprojects/docs/src/snippets/testKit/automaticClasspathInjectionQuickstart/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/testKit/gradleVersion/groovy/build.gradle
  subprojects/docs/src/snippets/testKit/spockQuickstart/groovy/build.gradle
  subprojects/docs/src/snippets/testKit/testKitFunctionalTestSpockBuildCache/groovy/build.gradle
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/spock/Spock2IntegrationSpec.groovy
Labels: in:testing, @core, in:documentation

#22150 Switch to JDK 19 for CI
  .teamcity/src/main/kotlin/common/JvmCategory.kt
  .teamcity/src/main/kotlin/common/JvmVersion.kt
  .teamcity/src/test/kotlin/ApplyDefaultConfigurationTest.kt
  .teamcity/src/test/kotlin/PerformanceTestBuildTypeTest.kt
Labels: @core

#22193 Update to ArchUnit 1.0.0-rc1
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
  subprojects/architecture-test/build.gradle.kts
  subprojects/architecture-test/src/test/java/org/gradle/architecture/test/ArchUnitFixture.java
  subprojects/architecture-test/src/test/java/org/gradle/architecture/test/ArchUnitFixtureTest.java
  subprojects/architecture-test/src/test/java/org/gradle/architecture/test/FreezeInstructionsPrintingArchRule.java
  subprojects/architecture-test/src/test/java/org/gradle/architecture/test/ProviderMigrationArchitectureTest.java
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/internal-architecture-testing/src/main/java/org/gradle/internal/architecture/PackageCycleTest.java
Labels: @dev-productivity

#22195 Update Sentry Android plugin and use AGP 7.3.0 in samples and Android perf tests
  build-logic/performance-testing/src/main/groovy/gradlebuild.performance-templates.gradle
  subprojects/docs/src/samples/android-application/groovy/app/build.gradle
  subprojects/docs/src/samples/android-application/kotlin/app/build.gradle.kts
  subprojects/docs/src/samples/build-organization/structuring-software-projects/groovy/platforms/plugins-platform/build.gradle
  subprojects/docs/src/samples/build-organization/structuring-software-projects/kotlin/platforms/plugins-platform/build.gradle.kts
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidCommunityPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginSmokeTest.groovy
Labels: @execution

#22152 Introduce `Failure#assertHasFirstCause`
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheDependencyResolutionFailuresIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/AbstractFailure.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/ExecutionFailure.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/InProcessGradleExecuter.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/OutputScrapingExecutionFailure.java
Labels: a:chore, @configuration-cache

#22170 Fix Checkstyle plugin test to be CC compatible
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/WellBehavedPluginTest.groovy
Labels: in:checkstyle-plugin

#21764 Simplify testing validation problems
  subprojects/model-core/src/test/groovy/org/gradle/internal/reflect/validation/ValidationMessageCheckerTest.groovy
  subprojects/model-core/src/testFixtures/groovy/org/gradle/internal/reflect/validation/ValidationMessageChecker.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidatePluginsIntegrationTest.groovy
Labels: @execution

#22178 Refactor tests to run with both Groovy 3 and Groovy 4
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/GroovyGradlePluginInitIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/SettingsIncludeManyIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ivy/ComponentSelectionRulesErrorHandlingIntegTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/IsolatedAntBuilderMemoryLeakIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractIntegrationSpec.groovy
  subprojects/model-groovy/src/integTest/groovy/org/gradle/model/dsl/ModelMapDslIntegrationTest.groovy
Labels: in:testing, in:groovy-dsl, @core

#22191 Separate promoteMilestone and promoteReleaseMilestone
  .teamcity/src/main/kotlin/common/VersionedSettingsBranch.kt
  .teamcity/src/main/kotlin/promotion/PublishRelease.kt
  .teamcity/src/test/kotlin/PromotionProjectTests.kt
Labels: @dev-productivity

#22203 Reproduce regression when resolving artifacts with forced serialization
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/caching/ForceRealizedMetadataIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/derived/DerivedVariantsResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/resolver/DefaultArtifactSelector.java
Labels: @core

#22098 Fix attribute bug for component metadata rules
  subprojects/core-api/src/main/java/org/gradle/api/attributes/AttributeContainer.java
  subprojects/core/src/main/java/org/gradle/api/internal/attributes/AbstractAttributeContainer.java
  subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultImmutableAttributesFactory.java
  subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultMutableAttributeContainer.java
  subprojects/core/src/main/java/org/gradle/api/internal/attributes/HierarchicalAttributeContainer.java
  subprojects/core/src/main/java/org/gradle/api/internal/attributes/ImmutableAttributesFactory.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/attributes/DefaultAttributeContainerTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/attributes/DefaultMutableAttributeContainerTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/attributes/HierarchicalAttributeContainerTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/VariantAttributesRulesIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/ResolveConfigurationResolutionBuildOperationResult.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/metadata/DefaultMavenImmutableAttributesFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/ComponentMetadataDetailsAdapter.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/VariantMetadataAdapter.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractLazyModuleComponentResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/LazyRuleAwareWithBaseConfigurationMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/VariantMetadataRules.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/VariantAttributesRules.java
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/external/model/AbstractDependencyMetadataRulesTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/external/model/VariantFilesMetadataRulesTest.groovy
  subprojects/dependency-management/src/testFixtures/groovy/org/gradle/integtests/fixtures/publish/RemoteRepositorySpec.groovy
Labels: @core

#22163 Add missed dsl html for ProcessResources task
  subprojects/docs/src/docs/dsl/dsl.xml
  subprojects/docs/src/docs/dsl/org.gradle.language.jvm.tasks.ProcessResources.xml
Labels: @support

#22194 Allow selecting more testJavaVendors
  build-logic/basics/src/main/kotlin/gradlebuild/basics/BuildParams.kt
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
Labels: @dev-productivity

#21321 Automatically set SystemRoot environment variable for TestKit on Windows
  subprojects/docs/src/docs/release/notes.md
  subprojects/test-kit/src/main/java/org/gradle/testkit/runner/internal/DefaultGradleRunner.java
Labels: from:contributor

#22202 Store `IntersectionPatternSet` to the configuration cache fully
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheProcessResourcesIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/PatternSetCodec.kt
Labels: in:configuration-cache, @configuration-cache

#22208 More Groovy 4 safe changes
  subprojects/code-quality/src/testFixtures/groovy/org/gradle/quality/integtest/fixtures/CodeNarcCoverage.groovy
  subprojects/docs/src/snippets/codeQuality/codeQuality/groovy/build.gradle
  subprojects/docs/src/snippets/codeQuality/codeQuality/kotlin/build.gradle.kts
Labels: in:testing, in:groovy-dsl, @core

#22213 Future-facing Groovy 4 compatibility changes
  build-logic/buildquality/build.gradle.kts
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
  subprojects/core/src/main/java/org/gradle/initialization/DefaultGradleApiSpecProvider.java
  subprojects/language-groovy/src/testFixtures/groovy/org/gradle/testing/fixture/GroovyCoverage.groovy
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/PropertyAccessorType.java
  subprojects/plugins/src/integTest/groovy/org/gradle/groovy/compile/BasicGroovyCompilerIntegrationSpec.groovy
Labels: in:groovy-dsl, @core

#22204 Fix classes dirs regression
  build-logic/integration-testing/src/main/kotlin/gradlebuild.test-fixtures.gradle.kts
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildPluginDevelopmentIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/CalculateTaskGraphBuildOperationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/artifacts/publish/AbstractPublishArtifact.java
  subprojects/docs/src/samples/incubating/java/modules-multi-project-with-integration-tests/tests/runTask.out
  subprojects/docs/src/samples/java/modules-multi-project-with-integration-tests/tests/runTask.out
  subprojects/docs/src/samples/java/modules-multi-project/tests/runTask.out
  subprojects/docs/src/snippets/developingPlugins/conventionOverConfiguration/tests/deploy.out
  subprojects/ear/src/test/groovy/org/gradle/plugins/ear/EarPluginTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/JavaPluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/jvm/GeneratedSourcesDirectorySetContributorIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/internal/tasks/DefaultSourceSetOutput.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/JvmPluginsHelper.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmLanguageGeneratedSourceDirectoryBuilder.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmLanguageSourceDirectoryBuilder.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmPluginServices.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/JvmLanguageSourceDirectoryBuilder.java
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/ApplicationPluginTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/GroovyPluginTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/JavaBasePluginTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/JavaPluginTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/WarPluginTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/jvm/internal/DefaultJvmPluginServicesTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/jvm/internal/SourceDirectorySetJvmPluginServicesTest.groovy
  subprojects/scala/src/test/groovy/org/gradle/api/plugins/scala/Scala3PluginTest.groovy
  subprojects/scala/src/test/groovy/org/gradle/api/plugins/scala/ScalaPluginTest.groovy
Labels: @core

#21877 ProviderFactory: add gradlePropertiesPrefixedBy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintWriter.kt
  subprojects/core-api/src/main/java/org/gradle/api/provider/ProviderFactory.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/DefaultProviderFactory.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/sources/GradlePropertiesPrefixedByValueSource.java
Labels: a:feature, in:configuration-model, in:provider-api, from:contributor

#22223 Enable annotation-based local/remote test runner selection for `file-watching`
  build-logic/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/BuildOperationsFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesBetweenBuildsFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesByGradleFileWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ChangesDuringTheBuildFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ContinuousBuildFileWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/EnableFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/FileSystemWatchingSettingsFinalizedBuildOperationIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/LoggingFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/NoDaemonFilesystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/SymlinkFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/WatchedDirectoriesFileSystemWatchingIntegrationTest.groovy
Labels: @dev-productivity

#22219 Simplify execution engine steps
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementBuildScopeServices.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/ExecutionEngine.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/impl/DefaultExecutionEngine.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/AfterExecutionResult.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/AssignWorkspaceStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/BeforeExecutionContext.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/BuildCacheStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CachingContext.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CachingResult.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CaptureStateAfterExecutionStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CaptureStateBeforeExecutionStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ChangingOutputsContext.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ExecuteStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ExecutionRequestContext.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/IdentifyStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/IdentityContext.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/IncrementalChangesContext.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/InputChangesContext.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/LoadPreviousExecutionStateStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/PreviousExecutionContext.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ResolveCachingStateStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ResolveChangesStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ResolveInputChangesStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/Result.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/SkipEmptyWorkStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/SkipUpToDateStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/UpToDateResult.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ValidateStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ValidationFinishedContext.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/WorkspaceContext.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/AssignWorkspaceStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/BuildCacheStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CancelExecutionStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CaptureStateAfterExecutionStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CaptureStateBeforeExecutionStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CleanupStaleOutputsStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/ContextInsensitiveStepSpec.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CreateOutputsStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/ExecuteStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/IdentifyStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/IdentityCacheStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/RecordOutputsStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/RemovePreviousOutputsStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/RemoveUntrackedExecutionStateStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/ResolveCachingStateStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/ResolveChangesStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/ResolveInputChangesStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/SkipEmptyWorkStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/SkipUpToDateStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/StepSpec.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/StoreExecutionStateStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/TimeoutStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/ValidateStepTest.groovy
Labels: @execution

#22226 Make invalid toolchain spec deprecation lazy
  subprojects/platform-jvm/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainSpecIntegrationTest.groovy
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainQueryService.java
Labels: in:toolchains

#22221 Add link from the programmatic dependency resolution result doc to the task inputs doc
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/dependency_resolution.adoc
Labels: a:documentation

#22222 Finalize toolchain spec properties when resolving a toolchain
  subprojects/platform-jvm/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainIntegrationTest.groovy
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/CurrentJvmToolchainSpec.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/DefaultToolchainSpec.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainQueryService.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainSpecInternal.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/SpecificInstallationToolchainSpec.java
Labels: in:toolchains

#17123 Remove deprecated AbstractArchiveTask methods
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/architecture-test/src/changes/archunit_store/3c3e47be-b5ed-426a-8b9f-cfa00d3b09db
  subprojects/architecture-test/src/changes/archunit_store/provider-task-file-collection.txt
  subprojects/architecture-test/src/changes/archunit_store/provider-task-properties.txt
  subprojects/architecture-test/src/changes/archunit_store/provider-text-resource.txt
  subprojects/architecture-test/src/changes/archunit_store/public-api-mutable-file-collection.txt
  subprojects/architecture-test/src/changes/archunit_store/public-api-mutable-properties.txt
  subprojects/architecture-test/src/changes/archunit_store/public-api-mutable-text-resource.txt
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheConventionMappingIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/bundling/ArchiveIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/tasks/bundling/AbstractArchiveTask.java
  subprojects/core/src/testFixtures/groovy/org/gradle/api/tasks/bundling/AbstractArchiveTaskTest.groovy
  subprojects/docs/src/docs/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.xml
  subprojects/docs/src/docs/dsl/org.gradle.api.tasks.bundling.Tar.xml
  subprojects/docs/src/docs/dsl/org.gradle.api.tasks.bundling.War.xml
  subprojects/docs/src/docs/dsl/org.gradle.api.tasks.bundling.Zip.xml
  subprojects/docs/src/docs/dsl/org.gradle.plugins.ear.Ear.xml
  subprojects/docs/src/snippets/kotlinDsl/multiProjectBuild/kotlin/build.gradle.kts
  subprojects/performance/src/templates/archivePerformanceProject/build.gradle
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/PlayPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ShadowPluginSmokeTest.groovy
Labels: @core

#21488 Add the service to run jobs in the background thread pool instead of "execution phase started" callback.
  subprojects/base-services/src/main/java/org/gradle/internal/concurrent/ManagedExecutorImpl.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/BuildStateFactory.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultRootBuildState.java
  subprojects/composite-builds/src/test/groovy/org/gradle/composite/internal/DefaultIncludedBuildRegistryTest.groovy
  subprojects/composite-builds/src/test/groovy/org/gradle/composite/internal/DefaultRootBuildStateTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/tasks/SnapshotTaskInputsOperationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/internal/buildtree/ExecutionPhaseNotifyingBuildTreeWorkExecutor.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/Instrumented.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentedListenerHolder.java
  subprojects/core/src/main/java/org/gradle/internal/enterprise/core/GradleEnterprisePluginAdapter.java
  subprojects/core/src/main/java/org/gradle/internal/enterprise/core/GradleEnterprisePluginManager.java
  subprojects/core/src/test/groovy/org/gradle/internal/classpath/InstrumentedTest.groovy
  subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/GradleEnterprisePluginBackgroundJobExecutorsIntegrationTest.groovy
  subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/GradleEnterprisePluginCheckInFixture.groovy
  subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/GradleEnterprisePluginExecutionPhaseStartedCallbackIntegrationTest.groovy
  subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/GradleEnterprisePluginRequiredServicesIntegrationTest.groovy
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/GradleEnterprisePluginBackgroundJobExecutors.java
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/GradleEnterprisePluginRequiredServices.java
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/GradleEnterprisePluginService.java
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/impl/DefaultGradleEnterprisePluginAdapter.java
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/impl/DefaultGradleEnterprisePluginBackgroundJobExecutors.java
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/impl/DefaultGradleEnterprisePluginRequiredServices.java
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/impl/GradleEnterprisePluginServices.java
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/impl/legacy/LegacyGradleEnterprisePluginCheckInService.java
  subprojects/enterprise/src/test/groovy/org/gradle/internal/enterprise/impl/DefaultGradleEnterprisePluginBackgroundJobExecutorsTest.groovy
Labels: @configuration-cache

#22257 Fix ParallelDownloadsPerformanceTest
  build-logic/performance-testing/src/main/groovy/gradlebuild.performance-templates.gradle
Labels: @dev-productivity

#22258 Document corner case issue for incrementality
  subprojects/docs/src/docs/userguide/jvm/java_plugin.adoc
Labels: in:java-plugins, a:documentation
