Repository gradle/gradle, pull requests merged in 2022-01, with the labels that each got.

#19475 Allow Gradle Enterprise plugin to start external processes
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/Workarounds.kt
Labels: @configuration-cache

#19477 Allow Gradle Enterprise to read the keys file
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/Workarounds.kt
Labels: @configuration-cache

#19104 Re-enable thread dump on Linux
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/ChainingHttpHandler.java
Labels: @dev-productivity

#19486 Fix typo in CC section of release notes
  subprojects/docs/src/docs/release/notes.md
Labels: @configuration-cache

#19496 Resolve opened file path before notifying configuration cache listener
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheProblemReportingIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/internal/classpath/Instrumented.java
  subprojects/core/src/test/groovy/org/gradle/internal/classpath/InstrumentedTest.groovy
  subprojects/internal-testing/src/main/groovy/org/gradle/util/SetSystemProperties.java
Labels: @configuration-cache

#19476 Only display the build scan hint when the Gradle Enterprise plugin is not applied
  subprojects/core/src/main/java/org/gradle/internal/buildevents/BuildExceptionReporter.java
  subprojects/core/src/main/java/org/gradle/internal/buildevents/BuildLogger.java
  subprojects/core/src/main/java/org/gradle/internal/buildevents/BuildLoggerFactory.java
  subprojects/core/src/test/groovy/org/gradle/internal/buildevents/BuildExceptionReporterTest.groovy
  subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/core/BuildScanBuildFailureHintIntegrationTest.groovy
  subprojects/launcher/src/main/java/org/gradle/launcher/exec/BuildOutcomeReportingBuildActionRunner.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/LauncherServices.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/SessionFailureReportingActionExecuter.java
Labels: a:bug, in:build-scan

#19502 Group configuration cache inputs by type in the report
  subprojects/configuration-cache-report/src/main/kotlin/ConfigurationCacheReportPage.kt
  subprojects/configuration-cache-report/src/main/kotlin/Main.kt
  subprojects/configuration-cache-report/src/main/kotlin/data/Trie.kt
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOptionsIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheValueSourceIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintWriter.kt
Labels: @configuration-cache

#19433 prevent excluding JUnit Platform tests with non-standard `TestSource`
  subprojects/testing-junit-platform/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestClassProcessor.java
  subprojects/testing-jvm/build.gradle.kts
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformFilteringIntegrationTest.groovy
  subprojects/testing-jvm/src/testFixtures/groovy/org/gradle/testing/fixture/JUnitCoverage.groovy
Labels: in:testing, in:testing-junit5

#19506 Polish configuration cache report
  subprojects/configuration-cache-report/src/main/kotlin/ConfigurationCacheReportPage.kt
  subprojects/configuration-cache-report/src/main/kotlin/elmish/View.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintWriter.kt
Labels: @configuration-cache

#19510 Use neutral square icon for configuration cache inputs in the report
  subprojects/configuration-cache-report/src/main/kotlin/ConfigurationCacheReportPage.kt
  subprojects/configuration-cache-report/src/main/kotlin/Main.kt
Labels: @configuration-cache

#19514 Include display name of Describable ValueSources in the configuration cache report
  build-logic/module-identity/src/main/kotlin/gradlebuild/identity/provider/BuildTimestampFromBuildReceiptValueSource.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintWriter.kt
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/DefaultValueSourceProviderFactory.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/ValueSourceProviderFactory.java
  subprojects/model-core/src/test/groovy/org/gradle/api/internal/provider/DefaultValueSourceProviderFactoryTest.groovy
Labels: @configuration-cache

#19508 First draft of release notes
  subprojects/docs/src/docs/release/notes.md
Labels: @core

#19527 Bump safe log4j to 2.17.1
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ScriptDependencyResolveIntegrationTest.groovy
  subprojects/logging/src/main/java/org/gradle/internal/logging/util/Log4jBannedVersion.java
  subprojects/scala/src/integTest/groovy/org/gradle/scala/ScalaPluginIntegrationTest.groovy
Labels: in:logging, in:scala-plugin

#19533 Merge release
  released-versions.json
  subprojects/base-services/src/main/java/org/gradle/api/internal/NullableTransformer.java
  subprojects/core-api/src/main/java/org/gradle/api/file/ContentFilterable.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ScriptDependencyResolveIntegrationTest.groovy
  subprojects/docs/src/docs/userguide/jvm/jvm_test_suite_plugin.adoc
  subprojects/docs/src/main/resources/header.html
  subprojects/docs/src/snippets/files/copy/kotlin/build.gradle.kts
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/GradleKotlinDslIntegrationTest.groovy
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoTaskExtension.java
  subprojects/kotlin-dsl/src/integTest/kotlin/org/gradle/kotlin/dsl/support/KotlinScriptCompilerIntegrationTest.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/ContentFilterableExtensions.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/KotlinCompiler.kt
  subprojects/logging/src/main/java/org/gradle/internal/logging/util/Log4jBannedVersion.java
  subprojects/scala/src/integTest/groovy/org/gradle/scala/ScalaPluginIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testsuites/TestSuitesIntegrationTest.groovy
Labels: @dev-productivity

#19535 Rename READY_FOR_MERGE to PULL_REQUEST_FEEDBACK
  .teamcity/src/main/kotlin/configurations/FlakyTestQuarantine.kt
  .teamcity/src/main/kotlin/model/CIBuildModel.kt
  .teamcity/src/test/kotlin/PerformanceTestBuildTypeTest.kt
Labels: @dev-productivity

#18415 Fix for #11036 – Provide messages for null pointer exceptions when map property literals contain `null`
  subprojects/docs/src/docs/release/notes.md
  subprojects/model-core/src/integTest/groovy/org/gradle/api/provider/MapPropertyIntegrationTest.groovy
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/ValidatingMapEntryCollector.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/ValidatingValueCollector.java
  subprojects/model-core/src/test/groovy/org/gradle/api/internal/provider/MapPropertySpec.groovy
Labels: @core

#19537 Split large process instrumentation tests
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/AbstractConfigurationCacheExternalProcessIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/AbstractConfigurationCacheProcessInstrumentationIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheExternalProcessInBuildScriptIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheExternalProcessInInitScriptIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheExternalProcessInPluginBuildScriptIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheExternalProcessInPluginIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheExternalProcessInTaskIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheExternalProcessInstrumentationInDynamicGroovyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheExternalProcessInstrumentationInJavaIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheExternalProcessInstrumentationInKotlinIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheExternalProcessInstrumentationInStaticGroovyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheExternalProcessInstrumentationIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheExternalProcessIntegrationTest.groovy
Labels: @configuration-cache

#19541 Rename convention plugin to io.github.gradle
  gradle/verification-metadata.xml
  settings.gradle.kts
Labels: @dev-productivity

#19543 Add descriptions to internal subprojects
  subprojects/internal-android-performance-testing/build.gradle.kts
  subprojects/internal-build-reports/build.gradle.kts
  subprojects/internal-integ-testing/build.gradle.kts
  subprojects/internal-performance-testing/build.gradle.kts
  subprojects/internal-testing/build.gradle.kts
Labels: @dev-productivity

#19546 Fix IndexOutOfBoundsException when invalidating
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/VfsRelativePath.java
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/VfsRelativePathTest.groovy
Labels: @execution

#19414 Improve SmokeContinuousIntegrationTest
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeContinuousBuildIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/internal/operations/notify/BuildOperationNotificationContinuousBuildIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/internal/scopeids/ContinuousScopeIdsIntegrationTest.groovy
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/ContinuousBuildFileWatchingIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractContinuousIntegrationTest.groovy
  subprojects/language-jvm/src/testFixtures/groovy/org/gradle/api/tasks/compile/AbstractCompilerContinuousIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/ArchivesContinuousIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/BuildSessionServiceReuseContinuousIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/BuildSrcContinuousIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/CancellationContinuousIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/ChangesDuringBuildContinuousIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/ContinuousBuildCancellationIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/ContinuousBuildChangeReportingIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/ContinuousBuildGateIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/ContinuousWorkerDaemonServiceIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/DeploymentContinuousBuildIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/GradleBuildContinuousIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/MultiProjectContinuousIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/SimpleJavaContinuousIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/SmokeContinuousIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/jdk7/SymlinkContinuousIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/internal/deployment/JavaApplicationDeploymentIntegrationTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/play/integtest/external/PlayExternalContinuousBuildIntegrationTest.groovy
Labels: @execution

#19536 Fix wrong breaking change sections
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
Labels: @dev-productivity

#19557 Fix broken Kotlin DSL model builders cross version tests
  subprojects/kotlin-dsl-tooling-builders/src/crossVersionTest/groovy/org/gradle/kotlin/dsl/tooling/builders/AbstractKotlinScriptModelCrossVersionTest.groovy
  subprojects/kotlin-dsl-tooling-builders/src/crossVersionTest/groovy/org/gradle/kotlin/dsl/tooling/builders/r41/KotlinBuildScriptTemplateModelCrossVersionSpec.groovy
  subprojects/kotlin-dsl-tooling-builders/src/crossVersionTest/groovy/org/gradle/kotlin/dsl/tooling/builders/r54/KotlinBuildScriptModelCrossVersionSpec.groovy
  subprojects/kotlin-dsl-tooling-builders/src/crossVersionTest/groovy/org/gradle/kotlin/dsl/tooling/builders/r54/PrecompiledScriptPluginModelCrossVersionSpec.groovy
  subprojects/kotlin-dsl-tooling-builders/src/crossVersionTest/groovy/org/gradle/kotlin/dsl/tooling/builders/r60/KotlinDslDefaultScriptsModelCrossVersionSpec.groovy
  subprojects/kotlin-dsl-tooling-builders/src/crossVersionTest/groovy/org/gradle/kotlin/dsl/tooling/builders/r60/KotlinDslGivenScriptsModelCrossVersionSpec.groovy
  subprojects/kotlin-dsl-tooling-builders/src/crossVersionTest/groovy/org/gradle/kotlin/dsl/tooling/builders/r60/KotlinDslScriptsModelCrossVersionSpec.groovy
  subprojects/kotlin-dsl-tooling-builders/src/crossVersionTest/groovy/org/gradle/kotlin/dsl/tooling/builders/r68/KotlinDslDefaultScriptsModelCrossVersionSpec.groovy
Labels: in:kotlin-dsl, @configuration-cache

#19567 Add a workflow to auto-add @dev-prod issue/PR to projects
  .github/workflows/add-to-dev-prod-project.yml
Labels: @dev-productivity

#19513 Don't exclude test with non-standard `TestSource` directly, but allow filtering on their containing class
  subprojects/testing-junit-platform/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestClassProcessor.java
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformFilteringIntegrationTest.groovy
  subprojects/testing-jvm/src/testFixtures/groovy/org/gradle/testing/fixture/JUnitCoverage.groovy
Labels: in:testing, @core, in:testing-junit5

#19416 Allow overriding Task methods without @Internal annotation
  subprojects/core-api/src/main/java/org/gradle/api/Task.java
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskDefinitionIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/ExecutionGlobalServices.java
Labels: @execution

#19365 Store complete sub-snapshots of filtered walk in VFS
  subprojects/build-cache-packaging/src/main/java/org/gradle/caching/internal/packaging/impl/TarBuildCacheEntryPacker.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/FileSystemSnapshotBuilder.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/history/impl/OutputSnapshotUtil.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CaptureStateAfterExecutionStepTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdaterTest.groovy
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/DirectorySnapshotBuilder.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/MerkleDirectorySnapshotBuilder.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/impl/DirectorySnapshotter.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/impl/FileSystemSnapshotFilter.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/impl/FilteredTrackingMerkleDirectorySnapshotBuilder.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultFileSystemAccess.java
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterAsDirectoryWalkerTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterStatisticsTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/vfs/impl/DefaultSnapshotHierarchyTest.groovy
Labels: @execution

#19545 Adjust ContinuousBuildChangeReportingIntegrationTest
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/ContinuousBuildChangeReportingIntegrationTest.groovy
Labels: @execution

#17422 Let `ZipFileTree` and `Install` avoid the zip-slip vulnerability
  subprojects/base-services/src/main/java/org/gradle/util/internal/GUtil.java
  subprojects/base-services/src/test/groovy/org/gradle/util/internal/GUtilTest.groovy
  subprojects/build-cache-packaging/src/main/java/org/gradle/caching/internal/packaging/impl/RelativePathParser.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/archive/ZipFileTree.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/UnzipTransform.java
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/ZipSlipIntegrationTest.groovy
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/zip.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/support/ZipTest.kt
  subprojects/resources/src/main/java/org/gradle/internal/resource/ExternalResourceName.java
  subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy
  subprojects/wrapper/src/main/java/org/gradle/wrapper/Install.java
  subprojects/wrapper/src/test/groovy/org/gradle/wrapper/InstallTest.groovy
Labels: a:chore

#19572 Document `UnitTestAndCompileExtension` methods
  build-logic/jvm/src/main/kotlin/gradlebuild/jvm/extension/UnitTestAndCompileExtension.kt
Labels: in:building-gradle

#19575 Extract elementWithRelativePathMatches from ExecutionNodeAccessHierarchy
  subprojects/core/src/main/java/org/gradle/execution/plan/ExecutionNodeAccessHierarchy.java
  subprojects/core/src/main/java/org/gradle/execution/plan/SingleFileTreeElementMatcher.java
Labels: @execution

#19344 fix typo in build_environment doc
  subprojects/docs/src/docs/userguide/running-builds/build_environment.adoc
Labels: in:remoting, a:documentation

#19588 Move WatchMode to org.gradle.internal.watch.registry
  subprojects/core/src/main/java/org/gradle/api/internal/StartParameterInternal.java
  subprojects/core/src/main/java/org/gradle/initialization/StartParameterBuildOptions.java
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/EnableFileSystemWatchingIntegrationTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/WatchMode.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DefaultFileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/WatchableHierarchies.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/BuildLifecycleAwareVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingNotSupportedVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/AbstractFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/registry/impl/NonHierarchicalFileWatcherUpdaterTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingNotSupportedVirtualFileSystemTest.groovy
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystemTest.groovy
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunner.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/action/BuildActionSerializer.java
  subprojects/launcher/src/test/groovy/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunnerTest.groovy
Labels: @execution

#19566 Introduce flakyTests=include/exclude/only
  .teamcity/src/main/kotlin/configurations/FlakyTestQuarantine.kt
  .teamcity/src/main/kotlin/configurations/FunctionalTest.kt
  build-logic/basics/src/main/kotlin/gradlebuild/basics/BuildParams.kt
  build-logic/basics/src/main/kotlin/gradlebuild/basics/testing/TestType.kt
  build-logic/integration-testing/src/main/kotlin/gradlebuild.integration-tests.gradle.kts
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractIntegrationTest.java
  subprojects/internal-integ-testing/src/main/resources/MultiVersionTestSpockConfig.groovy
  subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/IntegrationTest.groovy
  subprojects/internal-testing/src/main/resources/FlakyTestQuarantineSpockConfig.groovy
  subprojects/internal-testing/src/main/resources/GradleBuildSpockConfig.groovy
Labels: @dev-productivity

#19592 Introduce :wrapper-shared project
  .teamcity/subprojects.json
  settings.gradle.kts
  subprojects/base-services/src/main/java/org/gradle/util/internal/GUtil.java
  subprojects/base-services/src/test/groovy/org/gradle/util/internal/GUtilTest.groovy
  subprojects/core/build.gradle.kts
  subprojects/core/src/main/java/org/gradle/api/internal/file/archive/ZipFileTree.java
  subprojects/core/src/main/java/org/gradle/process/internal/worker/child/WorkerProcessClassPathProvider.java
  subprojects/dependency-management/build.gradle.kts
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/UnzipTransform.java
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DistributionIntegrationSpec.groovy
  subprojects/kotlin-dsl/build.gradle.kts
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/zip.kt
  subprojects/wrapper-shared/build.gradle.kts
  subprojects/wrapper-shared/src/integTest/groovy/org/gradle/integtests/ZipSlipIntegrationTest.groovy
  subprojects/wrapper-shared/src/main/java/org/gradle/util/internal/ZipSlip.java
  subprojects/wrapper-shared/src/test/groovy/org/gradle/util/internal/ZipSlipTest.groovy
  subprojects/wrapper/build.gradle.kts
  subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy
  subprojects/wrapper/src/main/java/org/gradle/wrapper/Install.java
Labels: @configuration-cache

#19596 Fix map property validation with the configuration cache enabled
  subprojects/model-core/src/integTest/groovy/org/gradle/api/provider/MapPropertyIntegrationTest.groovy
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/DefaultMapProperty.java
Labels: @configuration-cache, in:provider-api

#19610 Remove sourceCompatibility and targetCompatibility from build-logic-commons
  build-logic-commons/build-scan/build.gradle.kts
  build-logic-commons/code-quality-rules/build.gradle.kts
  build-logic-commons/code-quality/build.gradle.kts
  build-logic-commons/gradle-plugin/build.gradle.kts
Labels: @dev-productivity

#19611 Make FlakyTestQuarantine depend on QuickFeedbackLinux
  .teamcity/src/main/kotlin/configurations/FlakyTestQuarantine.kt
Labels: @dev-productivity

#19612 Remove experimental stages in pipeline
  .teamcity/src/main/kotlin/model/CIBuildModel.kt
  .teamcity/test-buckets.json
Labels: @dev-productivity

#19613 Add one more bucket for cross version tests
  .teamcity/src/main/kotlin/model/FunctionalTestBucketProvider.kt
Labels: @dev-productivity

#19598 Fingerprint all data from a`ResolvedComponentResult` used as a task intput
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/DependencyManagementResultsAsInputsIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementValueSnapshotterSerializerRegistry.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ResolvedComponentResultSerializer.java
Labels: @configuration-cache, in:execution-engine

#19599 Dogfood Task.notCompatibleWithConfigurationCache(reason)
  CONTRIBUTING.md
  build-logic-settings/cc-experiment-plugin/src/main/kotlin/gradlebuild.internal.cc-experiment.settings.gradle.kts
Labels: in:building-gradle, @configuration-cache

#19616 Remove keys.fedoraproject.org from DefaultKeyServers
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/DefaultKeyServers.java
Labels: @execution

#19620 Remove unused test resource `wrapper.properties`
  subprojects/wrapper/src/test/resources/org/gradle/wrapper/wrapper.properties
Labels: a:chore, @configuration-cache

#19551 Use real Android Studio sync for Android Studio sync performance test
  .teamcity/performance-test-durations.json
  .teamcity/performance-tests-ci.json
  .teamcity/src/main/kotlin/common/performance-test-extensions.kt
  .teamcity/src/main/kotlin/configurations/TestPerformanceTest.kt
  .teamcity/src/test/kotlin/PerformanceTestBuildTypeTest.kt
  build-logic/basics/src/main/kotlin/gradlebuild/basics/BuildEnvironment.kt
  build-logic/basics/src/main/kotlin/gradlebuild/basics/BuildParams.kt
  build-logic/dependency-modules/src/main/kotlin/gradlebuild.dependency-modules.gradle.kts
  build-logic/performance-testing/src/main/groovy/gradlebuild.performance-templates.gradle
  build-logic/performance-testing/src/main/kotlin/gradlebuild/performance/PerformanceTestPlugin.kt
  gradle/verification-metadata.xml
  settings.gradle.kts
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/internal-android-performance-testing/src/main/java/org/gradle/performance/android/GetModel.java
  subprojects/internal-android-performance-testing/src/main/java/org/gradle/performance/android/Inspector.java
  subprojects/internal-android-performance-testing/src/main/java/org/gradle/performance/android/Main.java
  subprojects/internal-android-performance-testing/src/main/java/org/gradle/performance/android/SyncAction.java
  subprojects/internal-android-performance-testing/src/main/java/org/gradle/performance/android/Timer.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/AbstractBuildExperimentRunner.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/CrossVersionPerformanceTestRunner.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleBuildExperimentRunner.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleInvocationSpec.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/MavenBuildExperimentRunner.java
  subprojects/performance/build.gradle.kts
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidStudioPerformanceTest.groovy
Labels: @execution

#19624 Polish `ConfigurationCacheProblemsListener`
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/ConfigurationCacheProblemsListener.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ConfigurationCacheProblems.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ProblemsListener.kt
  subprojects/configuration-cache/src/test/kotlin/org/gradle/configurationcache/serialization/codecs/AbstractUserTypeCodecTest.kt
Labels: a:chore, @configuration-cache

#19638 Fix method name typo in swift tests
  subprojects/language-native/src/integTest/groovy/org/gradle/language/swift/SwiftIncrementalBuildIntegrationTest.groovy
Labels: @dev-productivity

#19639 Clarify config cache doc around dependency resolution results as task inputs
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
Labels: @configuration-cache

#19626 Move shared code from `:wrapper` to `:wrapper-shared`
  .teamcity/subprojects.json
  subprojects/build-init/build.gradle.kts
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/AllDistributionIntegrationSpec.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DistributionIntegrationSpec.groovy
  subprojects/internal-performance-testing/build.gradle.kts
  subprojects/test-kit/build.gradle.kts
  subprojects/tooling-api/build.gradle.kts
  subprojects/wrapper-shared/build.gradle.kts
  subprojects/wrapper-shared/src/main/java/org/gradle/wrapper/BootstrapMainStarter.java
  subprojects/wrapper-shared/src/main/java/org/gradle/wrapper/Download.java
  subprojects/wrapper-shared/src/main/java/org/gradle/wrapper/DownloadProgressListener.java
  subprojects/wrapper-shared/src/main/java/org/gradle/wrapper/ExclusiveFileAccessManager.java
  subprojects/wrapper-shared/src/main/java/org/gradle/wrapper/GradleUserHomeLookup.java
  subprojects/wrapper-shared/src/main/java/org/gradle/wrapper/IDownload.java
  subprojects/wrapper-shared/src/main/java/org/gradle/wrapper/Install.java
  subprojects/wrapper-shared/src/main/java/org/gradle/wrapper/Logger.java
  subprojects/wrapper-shared/src/main/java/org/gradle/wrapper/PathAssembler.java
  subprojects/wrapper-shared/src/main/java/org/gradle/wrapper/SystemPropertiesHandler.java
  subprojects/wrapper-shared/src/main/java/org/gradle/wrapper/WrapperConfiguration.java
  subprojects/wrapper-shared/src/main/java/org/gradle/wrapper/WrapperExecutor.java
  subprojects/wrapper-shared/src/test/groovy/org/gradle/wrapper/DownloadTest.groovy
  subprojects/wrapper-shared/src/test/groovy/org/gradle/wrapper/ExclusiveFileAccessManagerTest.groovy
  subprojects/wrapper-shared/src/test/groovy/org/gradle/wrapper/GradleUserHomeLookupTest.groovy
  subprojects/wrapper-shared/src/test/groovy/org/gradle/wrapper/InstallTest.groovy
  subprojects/wrapper-shared/src/test/groovy/org/gradle/wrapper/PathAssemblerTest.java
  subprojects/wrapper-shared/src/test/groovy/org/gradle/wrapper/SystemPropertiesHandlerTest.groovy
  subprojects/wrapper-shared/src/test/groovy/org/gradle/wrapper/WrapperExecutorTest.groovy
  subprojects/wrapper/build.gradle.kts
  subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy
Labels: a:chore, @configuration-cache

#19647 jacoco-report-aggregation should not fail on missing execution data
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoAggregationIntegrationTest.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoPluginMultiVersionIntegrationTest.groovy
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/tasks/JacocoCoverageVerification.java
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/tasks/JacocoReport.java
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/TestReportAggregationPluginIntegrationTest.groovy
Labels: @core

#19657 Explicitly set source/targetCompatibility=11 for build-logic-commons
  build-logic-commons/build-scan/build.gradle.kts
  build-logic-commons/code-quality-rules/build.gradle.kts
  build-logic-commons/code-quality/build.gradle.kts
  build-logic-commons/gradle-plugin/build.gradle.kts
Labels: @dev-productivity

#19659 Set source/targetCompatibility=11 for build-logic
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.build-logic.groovy-dsl-gradle-plugin.gradle.kts
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.build-logic.kotlin-dsl-gradle-plugin.gradle.kts
Labels: @dev-productivity

#19569 Use VFS infrastructure for continuous build
  subprojects/core/src/main/java/org/gradle/execution/plan/BuildInputHierarchy.java
  subprojects/core/src/main/java/org/gradle/execution/plan/ExecutionNodeAccessHierarchy.java
  subprojects/core/src/main/java/org/gradle/execution/plan/ValuedVfsHierarchy.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java
  subprojects/core/src/test/groovy/org/gradle/internal/filewatch/SingleFirePendingChangesListenerTest.groovy
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/FileChangeListener.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/FileChangeListeners.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/file-watching/src/test/groovy/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystemTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractContinuousIntegrationTest.groovy
  subprojects/launcher/build.gradle.kts
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/ChangesDuringBuildContinuousIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/ContinuousBuildChangeReportingIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/SimpleJavaContinuousIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/SmokeContinuousIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/jdk7/SymlinkContinuousIntegrationTest.groovy
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/AccumulateBuildInputsListener.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/ContinuousBuildActionExecutor.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/ContinuousBuildTriggerHandler.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/FileEventCollector.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunner.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/LauncherServices.java
  subprojects/launcher/src/test/groovy/org/gradle/tooling/internal/provider/ContinuousBuildActionExecutorTest.groovy
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/VfsRelativePath.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultSnapshotHierarchy.java
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r26/TestLauncherCrossVersionSpec.groovy
  subprojects/tooling-api/src/testFixtures/groovy/org/gradle/integtests/tooling/fixture/ContinuousBuildToolingApiSpecification.groovy
Labels: @execution

#19662 Add useful `toString()` implementation to provider related types
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/BiProvider.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/DefaultValueSourceProviderFactory.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/OrElseFixedValueProvider.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/OrElseProvider.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/ValueSupplier.java
Labels: @configuration-cache

#19664 Remove now unnecessary base class `ConfigurationTimeProvider`
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/DefaultValueSourceProviderFactory.java
Labels: @configuration-cache

#19671 Fix no daemon tests for continuous build changes
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/options/TaskOptionFailureIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractContinuousIntegrationTest.groovy
  subprojects/language-jvm/src/testFixtures/groovy/org/gradle/api/tasks/compile/AbstractCompilerContinuousIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/BuildSessionServiceReuseContinuousIntegrationTest.groovy
Labels: @execution

#19665 Fix `Provider#orElse` compatibility with the configuration cache
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOptionsIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/tasks/JavaExec.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/ChangingProvider.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/DefaultProvider.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/OrElseProvider.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/Providers.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/ValueSupplier.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildSanityCheckConfigurationCacheSmokeTest.groovy
Labels: @configuration-cache

#19680 Do not run flaky tests in GH-Action
  .github/workflows/contributor-pr.yml
Labels: @dev-productivity

#19675 Fix change reporting tests on macOS
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/ContinuousBuildChangeReportingIntegrationTest.groovy
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/FileEventCollector.java
Labels: @execution

#19690 Remove not-necessary Flaky annotations from our code base
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
  subprojects/ide/src/crossVersionTest/groovy/org/gradle/plugins/ide/tooling/m3/ToolingApiEclipseModelCrossVersionSpec.groovy
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginTest.kt
  subprojects/kotlin-dsl-tooling-builders/src/crossVersionTest/groovy/org/gradle/kotlin/dsl/tooling/builders/r54/KotlinSettingsScriptModelCrossVersionSpec.groovy
  subprojects/kotlin-dsl-tooling-builders/src/crossVersionTest/groovy/org/gradle/kotlin/dsl/tooling/builders/r68/KotlinDslDefaultScriptsModelCrossVersionSpec.groovy
Labels: @dev-productivity

#19677 Do not treat parents of inputs as inputs for continuous build
  subprojects/core/src/main/java/org/gradle/execution/plan/BuildInputHierarchy.java
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/SimpleJavaContinuousIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/SmokeContinuousIntegrationTest.groovy
  subprojects/tooling-api/src/testFixtures/groovy/org/gradle/integtests/tooling/fixture/ContinuousBuildToolingApiSpecification.groovy
Labels: @execution

#19699 Increase ArtifactTransformParallelIntegrationTest http timeout
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformParallelIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/BlockingHttpServer.java
Labels: a:bug

#19695 Remove "used by scan plugin" annotations for enterprise subprojects
  subprojects/enterprise-operations/src/main/java/org/gradle/api/internal/artifacts/ResolveArtifactsBuildOperationType.java
  subprojects/enterprise-operations/src/main/java/org/gradle/api/internal/tasks/SnapshotTaskInputsBuildOperationType.java
  subprojects/enterprise-operations/src/main/java/org/gradle/caching/internal/operations/BuildCacheArchivePackBuildOperationType.java
  subprojects/enterprise-operations/src/main/java/org/gradle/caching/internal/operations/BuildCacheArchiveUnpackBuildOperationType.java
  subprojects/enterprise-operations/src/main/java/org/gradle/caching/internal/operations/BuildCacheRemoteStoreBuildOperationType.java
  subprojects/enterprise-operations/src/main/java/org/gradle/initialization/RunNestedBuildBuildOperationType.java
  subprojects/enterprise-operations/src/main/java/org/gradle/internal/taskgraph/CalculateTaskGraphBuildOperationType.java
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/GradleEnterprisePluginBuildState.java
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/GradleEnterprisePluginCheckInResult.java
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/GradleEnterprisePluginCheckInService.java
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/GradleEnterprisePluginConfig.java
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/GradleEnterprisePluginEndOfBuildListener.java
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/GradleEnterprisePluginMetadata.java
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/GradleEnterprisePluginRequiredServices.java
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/GradleEnterprisePluginService.java
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/GradleEnterprisePluginServiceFactory.java
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/GradleEnterprisePluginServiceRef.java
  subprojects/enterprise/src/main/java/org/gradle/internal/scan/config/BuildScanConfig.java
  subprojects/enterprise/src/main/java/org/gradle/internal/scan/config/BuildScanConfigProvider.java
  subprojects/enterprise/src/main/java/org/gradle/internal/scan/config/BuildScanPluginMetadata.java
  subprojects/enterprise/src/main/java/org/gradle/internal/scan/eob/BuildScanEndOfBuildNotifier.java
  subprojects/enterprise/src/main/java/org/gradle/internal/scan/scopeids/BuildScanScopeIds.java
  subprojects/enterprise/src/main/java/org/gradle/internal/scan/time/BuildScanBuildStartedTime.java
  subprojects/enterprise/src/main/java/org/gradle/internal/scan/time/BuildScanClock.java
Labels: @execution, in:enterprise-plugin

#19706 Use drop-down for vendor in RerunFlakyTest
  .teamcity/src/main/kotlin/util/RerunFlakyTest.kt
Labels: @dev-productivity, flaky-fix-it

#19698 Expose placeholder exception features to :enterprise
  subprojects/enterprise/build.gradle.kts
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/exceptions/PlaceholderExceptions.java
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/exceptions/package-info.java
Labels: @execution, in:enterprise-plugin

#19702 Extract :logging-api and :enterprise-logging into separate subprojects
  .github/CODEOWNERS
  .teamcity/subprojects.json
  settings.gradle.kts
  subprojects/base-annotations/src/main/java/org/gradle/internal/HasInternalProtocol.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/antbuilder/DefaultIsolatedAntBuilder.java
  subprojects/core/src/main/java/org/gradle/process/internal/worker/child/WorkerProcessClassPathProvider.java
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DistributionIntegrationSpec.groovy
  subprojects/enterprise-logging/build.gradle.kts
  subprojects/enterprise-logging/src/main/java/org/gradle/internal/logging/progress/ProgressLogger.java
  subprojects/enterprise-logging/src/main/java/org/gradle/internal/logging/progress/ProgressLoggerFactory.java
  subprojects/enterprise-logging/src/main/java/org/gradle/internal/logging/text/StyledTextOutput.java
  subprojects/enterprise-logging/src/main/java/org/gradle/internal/logging/text/StyledTextOutputFactory.java
  subprojects/enterprise/build.gradle.kts
  subprojects/logging-api/build.gradle.kts
  subprojects/logging-api/src/main/java/org/gradle/api/logging/LogLevel.java
  subprojects/logging-api/src/main/java/org/gradle/api/logging/Logger.java
  subprojects/logging-api/src/main/java/org/gradle/api/logging/Logging.java
  subprojects/logging-api/src/main/java/org/gradle/api/logging/LoggingManager.java
  subprojects/logging-api/src/main/java/org/gradle/api/logging/LoggingOutput.java
  subprojects/logging-api/src/main/java/org/gradle/api/logging/StandardOutputListener.java
  subprojects/logging-api/src/main/java/org/gradle/api/logging/configuration/ConsoleOutput.java
  subprojects/logging-api/src/main/java/org/gradle/api/logging/configuration/LoggingConfiguration.java
  subprojects/logging-api/src/main/java/org/gradle/api/logging/configuration/ShowStacktrace.java
  subprojects/logging-api/src/main/java/org/gradle/api/logging/configuration/WarningMode.java
  subprojects/logging-api/src/main/java/org/gradle/api/logging/configuration/package-info.java
  subprojects/logging-api/src/main/java/org/gradle/api/logging/package-info.java
  subprojects/logging-api/src/test/groovy/org/gradle/api/logging/LogLevelTest.groovy
  subprojects/logging/build.gradle.kts
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/ForkingTestClassProcessor.java
  subprojects/testing-base/src/test/groovy/org/gradle/api/internal/tasks/testing/worker/ForkingTestClassProcessorTest.groovy
Labels: in:logging, @execution, in:enterprise-plugin

#19705 Remove TAPI JDK compatibility tests from flaky quarantine
  subprojects/tooling-api/src/integTest/groovy/org/gradle/integtests/tooling/ToolingApiClientCurrentJdkCompatibilityTest.groovy
  subprojects/tooling-api/src/integTest/groovy/org/gradle/integtests/tooling/ToolingApiClientJdkCompatibilityTest.groovy
  subprojects/tooling-api/src/integTest/groovy/org/gradle/integtests/tooling/ToolingApiClientMinJdkCompatibilityTest.groovy
Labels: flaky-fix-it

#19708 Fix vendor dropdown for RerunFlakyTest
  .teamcity/src/main/kotlin/util/RerunFlakyTest.kt
Labels: @dev-productivity

#19709 Remove ClientShutdownCrossVersionSpec from quarantine
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r22/ClientShutdownCrossVersionSpec.groovy
Labels: flaky-fix-it

#19713 Use Adoptium as default vendor for RerunFlakyTest
  .teamcity/src/main/kotlin/util/RerunFlakyTest.kt
Labels: @dev-productivity

#19697 Async worker test fix
  build-logic/root-build/src/main/kotlin/gradlebuild.warmup-ec2.gradle.kts
  build-logic/uber-plugins/src/main/kotlin/gradlebuild.internal.kotlin-js.gradle.kts
  gradle/verification-metadata.xml
  subprojects/core/src/test/groovy/org/gradle/internal/work/DefaultAsyncWorkTrackerTest.groovy
Labels: in:workers, @dev-productivity, flaky-fix-it

#19717 Remove ContinuousBuildProgressEventsCrossVersionSpec from quarantine
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r25/ContinuousBuildProgressEventsCrossVersionSpec.groovy
Labels: flaky-fix-it

#19712 Merge release
  released-versions.json
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOptionsIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/tasks/JavaExec.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/ChangingProvider.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/DefaultProvider.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/OrElseProvider.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/Providers.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/ValueSupplier.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/JvmTestSuite.java
Labels: @dev-productivity

#19715 Remove Spock retry logic from continuous build tests
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractContinuousIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/RetryConditions.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/ChangesDuringBuildContinuousIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/RetryOnBuildFailureContinuousIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/internal/deployment/JavaApplicationDeploymentIntegrationTest.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/fixture/ContinuousBuildCrossVersionToolingApiSpecificationRetryTest.groovy
  subprojects/tooling-api/src/testFixtures/groovy/org/gradle/integtests/tooling/fixture/ContinuousBuildToolingApiSpecification.groovy
Labels: flaky-fix-it

#19704 Fix flakiness in ClassLoaderLeakAvoidanceSoakTest
  subprojects/soak/src/integTest/groovy/org/gradle/launcher/daemon/ClassLoaderLeakAvoidanceSoakTest.groovy
Labels: @dev-productivity, flaky-fix-it

#19723 Fix directory changes reporting test
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/ContinuousBuildChangeReportingIntegrationTest.groovy
Labels: flaky-fix-it

#19597 Fix dependency verification when first resolved configuration has dependency verification disabled
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationIntegrityCheckIntegTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/DependencyVerifyingModuleComponentRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/ArtifactVerificationOperation.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/ChecksumAndSignatureVerificationOverride.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/writer/WriteDependencyVerificationFile.java
Labels: @execution

#19703 Let signature verification detect keyrings file and useKeyServers flag changes
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationSignatureCheckIntegTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/signatures/BuildTreeDefinedKeys.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/signatures/CrossBuildSignatureVerificationService.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/signatures/DefaultSignatureVerificationServiceFactory.java
Labels: @execution

#19640 Review types excluded from annotation analysis
  subprojects/core-api/src/main/java/org/gradle/api/plugins/ExtensionAware.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/ExecutionGlobalServices.java
Labels: @execution

#19722 Fix shutdown for continuous build tests
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractContinuousIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/ChangesDuringBuildContinuousIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/SmokeContinuousIntegrationTest.groovy
Labels: flaky-fix-it

#19678 Add unit test for ContinuousBuildActionExecutor
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/DefaultFileChangeListeners.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java
  subprojects/launcher/src/test/groovy/org/gradle/tooling/internal/provider/ContinuousBuildActionExecutorTest.groovy
Labels: @execution

#19732 Un-@Deprecate methods without stable replacements
  subprojects/ide/src/main/java/org/gradle/plugins/ide/idea/model/IdeaModule.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/TestReport.java
Labels: @core, in:reporting-tasks, in:test-suites, in:documentation

#19742 Document implications of marking a task `notCompatibleWithConfigurationCache`
  subprojects/core-api/src/main/java/org/gradle/api/Task.java
Labels: @configuration-cache

#19721 Ignore small regressions for JavaIDEModelPerformanceTest
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/BaselineVersion.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/CrossVersionPerformanceResults.groovy
  subprojects/internal-performance-testing/src/test/groovy/org/gradle/performance/results/BaselineVersionTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIDEModelPerformanceTest.groovy
Labels: flaky-fix-it

#19719 Fix WatchedDirectoriesFileSystemWatchingIntegrationTest flakiness
  subprojects/file-watching/src/integTest/groovy/org/gradle/internal/watch/WatchedDirectoriesFileSystemWatchingIntegrationTest.groovy
Labels: flaky-fix-it

#19679 Remove old continuous build code
  subprojects/core/src/integTest/groovy/org/gradle/internal/filewatch/AbstractFileWatcherTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/internal/filewatch/DefaultFileSystemChangeWaiterTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/internal/filewatch/DefaultFileWatcherFactoryTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/internal/filewatch/jdk7/WatchServiceFileWatcherBackingTest.groovy
  subprojects/core/src/main/java/org/gradle/internal/filewatch/DefaultFileSystemChangeWaiter.java
  subprojects/core/src/main/java/org/gradle/internal/filewatch/DefaultFileSystemChangeWaiterFactory.java
  subprojects/core/src/main/java/org/gradle/internal/filewatch/DefaultFileWatcherEventListener.java
  subprojects/core/src/main/java/org/gradle/internal/filewatch/DefaultFileWatcherFactory.java
  subprojects/core/src/main/java/org/gradle/internal/filewatch/DefaultGatedChangeWaiter.java
  subprojects/core/src/main/java/org/gradle/internal/filewatch/FileSystemChangeWaiter.java
  subprojects/core/src/main/java/org/gradle/internal/filewatch/FileSystemChangeWaiterFactory.java
  subprojects/core/src/main/java/org/gradle/internal/filewatch/FileWatcher.java
  subprojects/core/src/main/java/org/gradle/internal/filewatch/FileWatcherEvent.java
  subprojects/core/src/main/java/org/gradle/internal/filewatch/FileWatcherEventListener.java
  subprojects/core/src/main/java/org/gradle/internal/filewatch/FileWatcherFactory.java
  subprojects/core/src/main/java/org/gradle/internal/filewatch/FileWatcherListener.java
  subprojects/core/src/main/java/org/gradle/internal/filewatch/jdk7/Jdk7FileWatcherFactory.java
  subprojects/core/src/main/java/org/gradle/internal/filewatch/jdk7/WatchPointsRegistry.java
  subprojects/core/src/main/java/org/gradle/internal/filewatch/jdk7/WatchServiceFileWatcherBacking.java
  subprojects/core/src/main/java/org/gradle/internal/filewatch/jdk7/WatchServicePoller.java
  subprojects/core/src/main/java/org/gradle/internal/filewatch/jdk7/WatchServiceRegistrar.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GlobalScopeServices.java
  subprojects/core/src/main/resources/org/gradle/initialization/removed-types.txt
  subprojects/core/src/test/groovy/org/gradle/internal/filewatch/DefaultFileWatcherEventListenerTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/filewatch/jdk7/WatchPointsRegistryTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/filewatch/jdk7/WatchServiceRegistrarTest.groovy
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/FileSystemSubset.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/ImmutableDirectoryTree.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/ImmutablePatternSet.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/FilteredMinimalFileTree.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/GeneratedSingletonFileTree.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/MinimalFileTree.java
  subprojects/file-collections/src/test/groovy/org/gradle/api/internal/file/FileSystemSubsetTest.groovy
  subprojects/file-collections/src/test/groovy/org/gradle/api/internal/file/collections/GeneratedSingletonFileTreeSpec.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/ContinuousBuildChangeReportingIntegrationTest.groovy
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/ContinuousBuildTriggerHandler.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/FileEventCollector.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/LauncherServices.java
Labels: @execution

#19754 Update cc documentation about `notCompatibleWithConfigurationCache`
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
Labels: @configuration-cache, in:documentation

#19768 Ignore `.tmp` for UndefinedBuildExecutionIntegrationTest
  subprojects/core/src/integTest/groovy/org/gradle/api/UndefinedBuildExecutionIntegrationTest.groovy
Labels: @dev-productivity

#19776 Fix small compiler problem
  subprojects/problems/src/testFixtures/groovy/org/gradle/problems/Closures.groovy
Labels: @execution

#19779 Mark `:docs:samplesMultiPage` as `notCompatibleWithConfigurationCache`
  build-logic-settings/cc-experiment-plugin/src/main/kotlin/gradlebuild.internal.cc-experiment.settings.gradle.kts
Labels: in:building-gradle, @configuration-cache

#19781 Add coverage for `fileCollection.filter(...).asFileTree.matching(...)`
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheFileTreeIntegrationTest.groovy
Labels: a:chore, @configuration-cache

#19783 Revert expectation of parallel execution from tests in Gradle build
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginVersionIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/pmd/PmdPluginDependenciesIntegrationTest.groovy
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/java/SamplesJavaTestingIntegrationTest.groovy
  subprojects/version-control/src/integTest/groovy/org/gradle/vcs/internal/NestedSourceDependencyIntegrationTest.groovy
Labels: a:bug, in:building-gradle, @core
