Repository gradle/gradle, pull requests merged in 2022-04, with the labels that each got.

#20342 Fix DirectorySnapshotterAsDirectoryWalkerTest
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterAsDirectoryWalkerTest.groovy
Labels: @dev-productivity

#20343 Update test bucket json
  .teamcity/test-buckets.json
Labels: @dev-productivity

#20271 Update wrapper to latest nightly
  build-logic/build-platform/build.gradle.kts
  gradle/verification-metadata.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: a:chore, in:building-gradle, @configuration-cache

#20338 Add end-to-end test for the configuration cache report using Playwright
  gradle/verification-metadata.xml
  subprojects/configuration-cache/build.gradle.kts
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheReportIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/configurationcache/ConfigurationCacheProblemsFixture.groovy
Labels: a:chore, in:configuration-cache, @configuration-cache

#20366 Workaround for srcDistribution causing up-to-date jar tasks
  build-logic/packaging/src/main/kotlin/gradlebuild.distributions.gradle.kts
Labels: @dev-productivity

#20365 Let CI ignore config cache report e2e test on non Windows platforms
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheReportIntegrationTest.groovy
Labels: in:configuration-cache, @configuration-cache

#20297 Exclude `buildSrc` sources in settings script model
  subprojects/kotlin-dsl-tooling-builders/src/crossVersionTest/groovy/org/gradle/kotlin/dsl/tooling/builders/r54/KotlinSettingsScriptModelCrossVersionSpec.groovy
  subprojects/kotlin-dsl-tooling-builders/src/crossVersionTest/groovy/org/gradle/kotlin/dsl/tooling/builders/r75/KotlinSettingsScriptModelCrossVersionSpec.groovy
  subprojects/kotlin-dsl-tooling-builders/src/main/kotlin/org/gradle/kotlin/dsl/tooling/builders/KotlinBuildScriptModelBuilder.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/resolver/SourcePathProvider.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/resolver/SourcePathProviderTest.kt
Labels: a:bug, in:kotlin-dsl

#20335 HTTP 401s should cause repository blocking
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/ErrorHandlingModuleComponentRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/transport/NetworkingIssueVerifier.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/ErrorHandlingModuleComponentRepositoryTest.groovy
Labels: a:feature, in:repository-declarations

#19581 Remove complexity around looking at http.nonProxyHosts
  subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/HttpProxySettings.java
  subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/JavaSystemPropertiesProxySettings.java
  subprojects/resources-http/src/test/groovy/org/gradle/internal/resource/transport/http/JavaSystemPropertiesProxySettingsTest.groovy
  subprojects/resources-s3/src/integTest/groovy/org/gradle/integtests/resource/s3/maven/MavenPublishS3IntegrationTest.groovy
  subprojects/resources-s3/src/main/java/org/gradle/internal/resource/transport/aws/s3/S3ConnectionProperties.java
  subprojects/resources-s3/src/test/groovy/org/gradle/internal/resource/transport/aws/s3/S3ConnectionPropertiesTest.groovy
Labels: @core

#20357 Extract common `maybeRoundLastModified` method
  subprojects/core/src/testFixtures/groovy/org/gradle/test/fixtures/FileMetadataTestFixture.groovy
  subprojects/native/src/test/groovy/org/gradle/internal/nativeintegration/filesystem/services/NativePlatformBackedFileMetadataAccessorTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterAsDirectoryWalkerTest.groovy
Labels: @dev-productivity

#20379 Extract common `maybeRoundLastModified` method
  subprojects/core/src/testFixtures/groovy/org/gradle/test/fixtures/FileMetadataTestFixture.groovy
  subprojects/native/src/test/groovy/org/gradle/internal/nativeintegration/filesystem/services/NativePlatformBackedFileMetadataAccessorTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/impl/DirectorySnapshotterAsDirectoryWalkerTest.groovy
Labels: @dev-productivity

#20381 Fix failing JavaExecDebugIntegrationTest
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecDebugIntegrationTest.groovy
Labels: @dev-productivity

#20380 Update JaCoCo to 0.8.8, re-enable tests on JDK 18
  subprojects/docs/src/docs/dsl/org.gradle.testing.jacoco.plugins.JacocoPluginExtension.xml
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/snippets/testing/jacoco-quickstart/groovy/build.gradle
  subprojects/docs/src/snippets/testing/jacoco-quickstart/kotlin/build.gradle.kts
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoAggregationIntegrationTest.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoCachingIntegrationTest.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoPluginIntegrationTest.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoReportRelocationIntegrationTest.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoTestRelocationIntegrationTest.groovy
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoPlugin.java
  subprojects/jacoco/src/test/groovy/org/gradle/internal/jacoco/JacocoAgentJarTest.groovy
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/JacocoIntegrationTest.kt
  subprojects/reporting/src/integTest/groovy/org/gradle/api/reporting/plugins/BuildDashboardPluginIntegrationTest.groovy
Labels: in:jacoco-plugin, @core

#20233 Add userguide chapter on building Gradle projects with GitHub Actions
  subprojects/docs/src/docs/userguide/img/ci-systems/github-actions-cache-details.png
  subprojects/docs/src/docs/userguide/img/ci-systems/github-actions-create-repository.png
  subprojects/docs/src/docs/userguide/img/ci-systems/github-actions-job-details.png
  subprojects/docs/src/docs/userguide/img/ci-systems/github-actions-workflow.png
  subprojects/docs/src/docs/userguide/img/ci-systems/github-actions-workflows.png
  subprojects/docs/src/docs/userguide/reference/ci-systems/github-actions.adoc
  subprojects/docs/src/docs/userguide/reference/ci-systems/jenkins.adoc
  subprojects/docs/src/docs/userguide/reference/ci-systems/travis-ci.adoc
  subprojects/docs/src/main/resources/header.html
Labels: @support

#20396 Fix typo of test name
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/DisambiguateArtifactTransformIntegrationTest.groovy
Labels: @core

#20384 Automate kotlin-dsl plugin publishing
  .teamcity/src/main/kotlin/util/PublishKotlinDslPlugin.kt
  .teamcity/src/main/kotlin/util/UtilProject.kt
Labels: @dev-productivity

#20404 Mark a @Flaky TAPI test
  subprojects/tooling-api/src/integTest/groovy/org/gradle/integtests/tooling/ToolingApiClientJdkCompatibilityTest.groovy
Labels: @dev-productivity

#20405 Rebaseline a list of flaky performance scenarios
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/AndroidIncrementalExecutionPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationCachePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaDependencyReportPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIDEModelPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIncrementalExecutionPerformanceTest.groovy
Labels: @dev-productivity

#20360 Fix dependency verification when Gradle metadata file name doesn't match actual file name
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/validation/GradleMetadataValidationResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationSignatureCheckIntegTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/DependencyVerifyingModuleComponentRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/DefaultModuleComponentArtifactIdentifier.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ModuleComponentArtifactIdentifier.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ModuleComponentFileArtifactIdentifier.java
  subprojects/dependency-management/src/testFixtures/groovy/org/gradle/integtests/fixtures/publish/ModuleVersionSpec.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/gradle/FileSpec.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/gradle/VariantMetadataSpec.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/maven/AbstractMavenModule.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/maven/DelegatingMavenModule.java
Labels: @execution

#20382 Switch to version 1.0.0-rc-1 of the Plugin Publish Plugin
  build-logic/build-platform/build.gradle.kts
  build-logic/publishing/src/main/kotlin/gradlebuild/pluginpublish/extension/PluginPublishExtension.kt
  gradle/verification-metadata.xml
  subprojects/docs/src/snippets/developingPlugins/publishingPlugins/groovy/build.gradle
  subprojects/docs/src/snippets/developingPlugins/publishingPlugins/kotlin/build.gradle.kts
Labels: @support

#20395 Add toString to transform related classes to make debugging easier
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/ConsumerVariantMatchResult.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformationRegistrationFactory.java
Labels: @core

#20393 Update sample to latest version of Android
  subprojects/docs/build.gradle
  subprojects/docs/src/samples/android-application/groovy/app/build.gradle
  subprojects/docs/src/samples/android-application/kotlin/app/build.gradle.kts
Labels: @core

#20397 Remove unused method
  subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultImmutableAttributesFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ModuleComponentResolveMetadata.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/resolver/MavenResolverTest.groovy
Labels: @core

#20409 Re-enable fork for compilation
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
Labels: @dev-productivity

#17918 #12049 add support for more groovydoc options to groovydoc task
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/docs/src/docs/dsl/org.gradle.api.tasks.javadoc.Groovydoc.xml
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/language-groovy/src/integTest/groovy/org/gradle/groovy/GroovyDocOptionsIntegrationTest.groovy
  subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/AntGroovydoc.java
  subprojects/language-groovy/src/main/java/org/gradle/api/tasks/javadoc/Groovydoc.java
  subprojects/language-groovy/src/main/java/org/gradle/api/tasks/javadoc/GroovydocAccess.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/GroovyBasePlugin.java
Labels: in:groovy-plugin, @core, from:contributor

#20422 Polish `DefaultPrecompiledScriptPluginsSupport`
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/DefaultPrecompiledScriptPluginsSupport.kt
Labels: in:kotlin-dsl, @configuration-cache

#20407 Fix build lifecycle documentation sample
  subprojects/docs/src/snippets/buildlifecycle/projectEvaluateEvents/kotlin/build.gradle.kts
Labels: in:configuration-model, a:documentation

#20245 Capture updated system properties
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheValueSourceIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/SystemPropertyInstrumentationInDynamicGroovyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/SystemPropertyInstrumentationInJavaIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/SystemPropertyInstrumentationInKotlinIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/SystemPropertyInstrumentationInStaticGroovyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultBuildTreeModelControllerServices.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/InstrumentedInputAccessListener.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/JsonModelWriter.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/PropertyProblem.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/CachedEnvironmentStateCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/services/EnvironmentChangeTracker.kt
  subprojects/configuration-cache/src/test/kotlin/org/gradle/configurationcache/services/EnvironmentChangeTrackerTest.kt
  subprojects/core/src/main/java/org/gradle/internal/classpath/AccessTrackingEnvMap.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/AccessTrackingProperties.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/AccessTrackingSet.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/AccessTrackingUtils.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/Instrumented.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingTransformer.java
  subprojects/core/src/test/groovy/org/gradle/internal/classpath/AbstractAccessTrackingMapTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/classpath/AccessTrackingEnvMapTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/classpath/AccessTrackingPropertiesNonStringTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/classpath/AccessTrackingPropertiesTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/classpath/AccessTrackingSetTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/classpath/DefaultCachedClasspathTransformerTest.groovy
Labels: @configuration-cache

#20425 Upgrade configuration-cache-report to 1.1
  build-logic/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
Labels: in:configuration-cache, @configuration-cache

#20411 Update docs to warn about aggregation plugins not working with Android
  subprojects/docs/src/docs/userguide/jvm/jacoco_report_aggregation_plugin.adoc
  subprojects/docs/src/docs/userguide/jvm/test_report_aggregation_plugin.adoc
Labels: @core, a:documentation, in:test-suites

#20378 Upgrade build Kotlin version to 1.6.20 GA
  build-logic-commons/gradle-plugin/build.gradle.kts
  build-logic/build-platform/build.gradle.kts
  build-logic/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
  build-logic/kotlin-dsl/src/main/kotlin/gradlebuild.kotlin-dsl-dependencies-embedded.gradle.kts
  gradle/verification-metadata.xml
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/library-versions.properties
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/AllDistributionIntegrationSpec.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/BinDistributionIntegrationSpec.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DistributionIntegritySpec.groovy
  subprojects/docs/src/docs/userguide/compatibility.adoc
  subprojects/docs/src/samples/build-organization/structuring-software-projects/groovy/platforms/plugins-platform/build.gradle
  subprojects/docs/src/samples/build-organization/structuring-software-projects/kotlin/platforms/plugins-platform/build.gradle.kts
  subprojects/docs/src/snippets/configurationCache/samConversion/groovy/build.gradle
  subprojects/docs/src/snippets/configurationCache/samConversion/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/java/toolchain-kotlin/groovy/build.gradle
  subprojects/docs/src/snippets/java/toolchain-kotlin/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/androidBuild/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/androidSingleBuild/kotlin/build.gradle.kts
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/NestedInputKotlinImplementationTrackingIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/KotlinGradlePluginVersions.groovy
  subprojects/kotlin-dsl-plugins/build.gradle.kts
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/DefaultPrecompiledScriptPluginsSupport.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/codegen/GradleApiExtensionsTest.kt
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/JvmTestSuite.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
Labels: @dev-productivity

#20434 Rebaseline two flaky performance tests to latest nightly
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationCachePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIncrementalExecutionPerformanceTest.groovy
Labels: @dev-productivity

#20433 Update wrapper to latest nightly with Kotlin 1.6.20
  gradle/wrapper/gradle-wrapper.properties
Labels: @dev-productivity

#20435 Include master performance test executions in pre-tested commit builds
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/ResultsStoreHelper.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/AbstractReportGenerator.java
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/DefaultPerformanceExecutionDataProvider.java
Labels: @dev-productivity

#20418 Fix typos in JaCoCo Report Aggregation Plugin doc
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/jvm/jacoco_report_aggregation_plugin.adoc
Labels: from:contributor

#20412 Fix dependency verification when there is an artifact entry without checksum in verification-metadata...
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationSignatureCheckIntegTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/verifier/DependencyVerifier.java
Labels: @execution

#20426 Close all Playwright resources explicitly
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheReportIntegrationTest.groovy
Labels: @configuration-cache

#20374 Alternate --show-version-switch
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/BuildActionsFactory.java
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/CommandLineActionCreator.java
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/ContinuingAction.java
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/DefaultCommandLineActionFactory.java
  subprojects/launcher/src/test/groovy/org/gradle/launcher/cli/BuildActionsFactoryTest.groovy
  subprojects/launcher/src/test/groovy/org/gradle/launcher/cli/DefaultCommandLineActionFactoryTest.groovy
Labels: @core

#20445 Rebaseline NativeBuildPerformanceTest
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeBuildPerformanceTest.groovy
Labels: @dev-productivity

#20446 Rebase some failing performance tests
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingSwiftPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/inception/BuildSrcApiChangePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeCleanBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftBuildPerformanceTest.groovy
Labels: @dev-productivity

#20363 Add NoHttpResponseException as a transient error
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/transport/NetworkingIssueVerifier.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/transport/NetworkingIssueVerifierTest.groovy
Labels: @support

#20431 Use serializable lambda for rename in CopySpecWrapper
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/CopySpecWrapper.java
Labels: in:configuration-cache, in:file-tasks, from:contributor

#20302 Add release notes for PMD threads
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/core-plugins/pmd_plugin.adoc
  subprojects/docs/src/snippets/codeQuality/codeQuality/groovy/build.gradle
  subprojects/docs/src/snippets/codeQuality/codeQuality/kotlin/build.gradle.kts
Labels: in:pmd-plugin, @support

#20410 Warn if root project name not set
  subprojects/core/src/main/java/org/gradle/initialization/DefaultProjectDescriptor.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/typesafe/TypeSafeProjectAccessorsIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/DefaultDependenciesAccessors.java
Labels: in:project-accessors, @support

#20440 Delete resolveArtifacts from ModuleComponentRepositoryAccess
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/BaseModuleComponentRepositoryAccess.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/CachingModuleComponentRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/DependencyVerifyingModuleComponentRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/ErrorHandlingModuleComponentRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/FilteredModuleComponentRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/LocalModuleComponentRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/ModuleComponentRepositoryAccess.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/RepositoryChainArtifactResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/StartParameterResolutionOverride.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/ExternalResourceResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/IvyResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/MavenResolver.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/CachingModuleComponentRepositoryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/ErrorHandlingModuleComponentRepositoryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/RepositoryChainArtifactResolverTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/resolver/MavenResolverTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/resolver/TestResolver.java
  subprojects/platform-base/src/main/java/org/gradle/language/base/internal/model/DefaultLibraryLocalComponentMetadata.java
Labels: @core

#20456 Rebaseline JavaConfigurationCachePerformanceTest
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationCachePerformanceTest.groovy
Labels: @dev-productivity

#20421 Fix incorrect output detection under the presence of filtered inputs
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/ExecutionGradleServices.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuterTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementBuildScopeServices.java
  subprojects/execution/src/integTest/groovy/org/gradle/internal/execution/IncrementalExecutionIntegrationTest.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/BroadcastChangingOutputsStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CaptureStateAfterExecutionStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ChangingOutputsContext.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CreateOutputsStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ExecuteStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/RemovePreviousOutputsStep.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/BroadcastChangingOutputsStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CaptureStateAfterExecutionStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CreateOutputsStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/ExecuteStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/RemovePreviousOutputsStepTest.groovy
Labels: @execution

#18830 Provide option to hide welcome message on gradle startup
  subprojects/architecture-test/src/test/java/org/gradle/architecture/test/ProviderMigrationArchitectureTest.java
  subprojects/core-api/src/main/java/org/gradle/StartParameter.java
  subprojects/core-api/src/main/java/org/gradle/api/launcher/cli/WelcomeMessageConfiguration.java
  subprojects/core-api/src/main/java/org/gradle/api/launcher/cli/WelcomeMessageDisplayMode.java
  subprojects/core-api/src/main/java/org/gradle/api/launcher/cli/package-info.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/running-builds/build_environment.adoc
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/cli/NotificationsIntegrationTest.groovy
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/DefaultCommandLineActionFactory.java
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/WelcomeMessageAction.java
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/converter/LayoutToPropertiesConverter.java
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/converter/StartParameterConverter.java
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/converter/WelcomeMessageBuildOptions.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/action/BuildActionSerializer.java
  subprojects/launcher/src/test/groovy/org/gradle/launcher/cli/WelcomeMessageActionTest.groovy
Labels: in:invoking-gradle, from:contributor

#20457 Rename OutputChangeListener.{beforeOutputChange -> invalidateCachesFor}
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/CleanupStaleOutputsExecuter.java
  subprojects/core/src/main/java/org/gradle/cache/internal/DefaultFileContentCacheFactory.java
  subprojects/core/src/test/groovy/org/gradle/cache/internal/DefaultFileContentCacheFactoryTest.groovy
  subprojects/ear/src/main/java/org/gradle/plugins/ear/Ear.java
  subprojects/execution/src/integTest/groovy/org/gradle/internal/execution/IncrementalExecutionIntegrationTest.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/OutputChangeListener.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/BuildCacheStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/CaptureStateAfterExecutionStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/RemovePreviousOutputsStep.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/SkipEmptyWorkStep.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/BuildCacheStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/CaptureStateAfterExecutionStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/RemovePreviousOutputsStepTest.groovy
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/SkipEmptyWorkStepTest.groovy
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/tasks/Jar.java
Labels: @execution

#20276 Require JDK 18 instead of Python for serveDocs
  build-logic/documentation/src/main/groovy/gradlebuild/docs/GradleBuildDocumentationPlugin.java
Labels: in:documentation-infrastructure, a:feature, @core

#20427 Fall back to hashing the zip entry when ABI extraction fails during fingerprinting
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/classpath/impl/DefaultCompileClasspathFingerprinter.java
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/normalization/KotlinCompileClasspathFingerprinter.kt
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/AbiExtractingClasspathResourceHasher.java
  subprojects/normalization-java/src/test/groovy/org/gradle/api/internal/changedetection/state/AbiExtractingClasspathResourceHasherTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/AbstractJavaGroovyCompileAvoidanceIntegrationSpec.groovy
Labels: a:bug, in:execution-engine

#20356 Clean up build configurations
  .teamcity/src/main/kotlin/common/Jvm.kt
  .teamcity/src/main/kotlin/common/JvmCategory.kt
  .teamcity/src/main/kotlin/common/JvmVendor.kt
  .teamcity/src/main/kotlin/common/Os.kt
  .teamcity/src/main/kotlin/configurations/GradleBuildConfigurationDefaults.kt
  .teamcity/src/main/kotlin/util/AdHocPerformanceScenario.kt
  .teamcity/src/main/kotlin/util/RerunFlakyTest.kt
  .teamcity/src/test/kotlin/ApplyDefaultConfigurationTest.kt
  .teamcity/src/test/kotlin/PerformanceTestBuildTypeTest.kt
  gradle/AttachAgentToDaemon.java
  gradle/DumpOpenFilesOnFailure.java
Labels: @dev-productivity

#20462 Optimise ClassPath deserialization from the config cache
  subprojects/base-services/src/main/java/org/gradle/internal/classpath/DefaultClassPath.java
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/Combinators.kt
  subprojects/core/src/main/java/org/gradle/api/internal/classpath/EffectiveClassPath.java
Labels: in:configuration-cache, @configuration-cache

#20442 Add providers to look up env vars and system properties by prefix
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/EnvVariableInjection.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/InstrumentedInputAccessListener.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprint.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintChecker.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintController.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintWriter.kt
  subprojects/core-api/src/main/java/org/gradle/api/provider/ProviderFactory.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/DefaultProviderFactory.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/sources/EnvironmentVariablesPrefixedByValueSource.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/sources/MapWithPrefixedKeysValueSource.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/sources/SystemPropertiesPrefixedByValueSource.java
Labels: @configuration-cache

#18275 Fix project.sync to allow configure preserve
  subprojects/architecture-test/src/changes/archunit_store/public-api-mutable-properties.txt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ProblemReportingCrossProjectModelAccess.kt
  subprojects/core-api/src/main/java/org/gradle/api/Project.java
  subprojects/core-api/src/main/java/org/gradle/api/file/SyncSpec.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/DefaultFileOperations.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/FileOperations.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/CopySpecInternal.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/CopySpecWrapper.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DelegatingCopySpecInternal.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/FileCopier.java
  subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultProject.java
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/delegates/ProjectDelegate.kt
Labels: @execution

#20474 Enable Test Distribution for performance tests
  .teamcity/src/main/kotlin/configurations/PerformanceTest.kt
  .teamcity/src/test/kotlin/PerformanceTestBuildTypeTest.kt
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
Labels: @dev-productivity

#20481 Fix test failures in .teamcity
  .teamcity/src/main/kotlin/common/VersionedSettingsBranch.kt
  .teamcity/src/main/kotlin/promotion/BasePublishGradleDistribution.kt
  .teamcity/src/test/kotlin/PromotionProjectTests.kt
Labels: @dev-productivity

#20483 Add openjdk 8 to JDK candidates
  .teamcity/src/main/kotlin/common/Os.kt
  .teamcity/src/test/kotlin/ApplyDefaultConfigurationTest.kt
  .teamcity/src/test/kotlin/PerformanceTestBuildTypeTest.kt
Labels: @dev-productivity

#20487 core-api: remove extraneous word in doc
  subprojects/core-api/src/main/java/org/gradle/api/file/DuplicatesStrategy.java
Labels: from:contributor

#20489 Follow-ups of enabling Test Distribution for performance tests
  .teamcity/src/main/kotlin/common/extensions.kt
  .teamcity/src/main/kotlin/common/performance-test-extensions.kt
  .teamcity/src/main/kotlin/projects/CheckProject.kt
  .teamcity/src/main/kotlin/projects/StageProject.kt
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
Labels: @dev-productivity

#20493 Report circular references in hash sets as problems
  build-logic/basics/src/main/kotlin/gradlebuild.minify.gradle.kts
  subprojects/base-services/src/main/java/org/gradle/internal/classpath/DefaultClassPath.java
  subprojects/configuration-cache/build.gradle.kts
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheCircularReferenceIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheIO.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/Codec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/Contexts.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/Identities.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/CollectionCodecs.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/LocalFileDependencyBackedArtifactSetCodec.kt
  subprojects/configuration-cache/src/test/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintCheckerTest.kt
Labels: in:configuration-cache, @configuration-cache

#20420 Add a task to automatically check/update contributors in release notes
  build-logic/build-update-utils/src/main/kotlin/gradlebuild/buildutils/tasks/AbstractCheckOrUpdateContributorsInReleaseNotes.kt
  build-logic/build-update-utils/src/main/kotlin/gradlebuild/buildutils/tasks/CheckContributorsInReleaseNotes.kt
  build-logic/build-update-utils/src/main/kotlin/gradlebuild/buildutils/tasks/UpdateContributorsInReleaseNotes.kt
  build-logic/documentation/build.gradle.kts
  build-logic/documentation/src/main/groovy/gradlebuild/docs/GradleReleaseNotesPlugin.java
  subprojects/docs/src/docs/release/notes.md
Labels: @dev-productivity

#19202 Nag user when using IncrementalTaskInputs
  gradle/dependency-management/agp-versions.properties
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/changedetection/state/TaskTypeUpToDateIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/FailingIncrementalTasksIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalBuildIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalTaskInputsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalTaskWithNormalizedInputsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/UntrackedTaskIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/project/taskfactory/DefaultTaskClassInfoStore.java
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/snippets/buildCache/caching-android-projects/kotlin/build.gradle.kts
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/AndroidGradlePluginVersions.groovy
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/GradleKotlinDslIntegrationTest.kt
  subprojects/kotlin-dsl/src/integTest/kotlin/org/gradle/kotlin/dsl/support/EmbeddedKotlinProviderTest.kt
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractAndroidSantaTrackerSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/BaseDeprecations.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginAndroidGroovyDSLSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginAndroidKotlinDSLSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ThirdPartyGradleModuleMetadataSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/WithAndroidDeprecations.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/WithKotlinDeprecations.groovy
Labels: @execution

#20494 Save and reload BuildCacheServiceRegistration from configuration cache
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/core/src/integTest/groovy/org/gradle/caching/configuration/internal/BuildCacheConfigurationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/caching/configuration/internal/BuildCacheConfigurationInternal.java
  subprojects/core/src/main/java/org/gradle/caching/configuration/internal/DefaultBuildCacheConfiguration.java
Labels: in:configuration-cache, @configuration-cache, from:contributor

#20500 Save and reload BuildCacheServiceRegistration from configuration cache
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedImplementationIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/caching/configuration/internal/BuildCacheConfigurationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/caching/configuration/internal/BuildCacheConfigurationInternal.java
  subprojects/core/src/main/java/org/gradle/caching/configuration/internal/DefaultBuildCacheConfiguration.java
  subprojects/docs/src/docs/release/notes.md
Labels: in:configuration-cache, @configuration-cache

#20505 Upgrade to latest nightly and remove workaround for not picking up changes.
  build-logic/packaging/src/main/kotlin/gradlebuild.distributions.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
Labels: @execution

#20512 Upgrade Kotlin to 1.5.21
  .teamcity/src/main/kotlin/util/PublishKotlinDslPlugin.kt
  build-logic-commons/gradle-plugin/build.gradle.kts
  build-logic/build-platform/build.gradle.kts
  build-logic/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
  build-logic/kotlin-dsl/src/main/kotlin/gradlebuild.kotlin-dsl-dependencies-embedded.gradle.kts
  gradle/verification-metadata.xml
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/library-versions.properties
  subprojects/docs/src/docs/userguide/compatibility.adoc
  subprojects/docs/src/samples/build-organization/structuring-software-projects/groovy/platforms/plugins-platform/build.gradle
  subprojects/docs/src/samples/build-organization/structuring-software-projects/kotlin/platforms/plugins-platform/build.gradle.kts
  subprojects/docs/src/snippets/configurationCache/samConversion/groovy/build.gradle
  subprojects/docs/src/snippets/configurationCache/samConversion/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/java/toolchain-kotlin/groovy/build.gradle
  subprojects/docs/src/snippets/java/toolchain-kotlin/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/androidBuild/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/androidSingleBuild/kotlin/build.gradle.kts
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/NestedInputKotlinImplementationTrackingIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/KotlinGradlePluginVersions.groovy
  subprojects/kotlin-dsl-plugins/build.gradle.kts
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
Labels: @dev-productivity

#20513 Update wrapper to latest nightly with Kotlin 1.6.21
  build-logic/build-platform/build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
Labels: @dev-productivity

#20495 Update configuration cache docs to reflect recent changes
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintWriter.kt.orig
  subprojects/core-api/src/main/java/org/gradle/api/provider/ValueSource.java
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
  subprojects/docs/src/snippets/valueProviders/envVarsSysPropsDoPrefix/groovy/build.gradle
  subprojects/docs/src/snippets/valueProviders/envVarsSysPropsDoPrefix/groovy/settings.gradle
  subprojects/docs/src/snippets/valueProviders/envVarsSysPropsDoPrefix/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/valueProviders/envVarsSysPropsDoPrefix/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/valueProviders/envVarsSysPropsDoValueSource/groovy/build.gradle
  subprojects/docs/src/snippets/valueProviders/envVarsSysPropsDoValueSource/groovy/settings.gradle
  subprojects/docs/src/snippets/valueProviders/envVarsSysPropsDoValueSource/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/valueProviders/envVarsSysPropsDoValueSource/kotlin/settings.gradle.kts
Labels: @configuration-cache

#20525 Clean up stale entries in verification file
  gradle/verification-metadata.xml
Labels: @dev-productivity

#20541 Avoid using Oracle JDK8 on Windows
  .teamcity/src/main/kotlin/common/JvmCategory.kt
  .teamcity/src/main/kotlin/model/CIBuildModel.kt
  build-logic/basics/src/main/kotlin/gradlebuild/basics/BuildParams.kt
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
  subprojects/plugins/src/integTest/groovy/org/gradle/groovy/compile/BasicGroovyCompilerIntegrationSpec.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/BasicJavaCompilerIntegrationSpec.groovy
Labels: @dev-productivity

#20542 Cherry-pick #20541 to `release`
  .teamcity/src/main/kotlin/common/JvmCategory.kt
  .teamcity/src/main/kotlin/model/CIBuildModel.kt
  build-logic/basics/src/main/kotlin/gradlebuild/basics/BuildParams.kt
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
  subprojects/plugins/src/integTest/groovy/org/gradle/groovy/compile/BasicGroovyCompilerIntegrationSpec.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/BasicJavaCompilerIntegrationSpec.groovy
Labels: @dev-productivity

#20526 Suppress compiler warnings
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/AbstractCodeQualityPlugin.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/query/ArtifactResolutionQuery.java
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/repositories/RepositoryContentDescriptor.java
  subprojects/core-api/src/main/java/org/gradle/api/provider/HasMultipleValues.java
  subprojects/ide-native/src/main/groovy/org/gradle/ide/visualstudio/plugins/VisualStudioPlugin.java
  subprojects/internal-testing/src/main/groovy/org/gradle/util/internal/RedirectStdOutAndErr.java
  subprojects/reporting/src/main/java/org/gradle/api/reporting/GenerateBuildDashboard.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/junit/AllExceptIgnoredTestRunnerBuilder.java
Labels: @dev-productivity

#20543 Use right target compatibility for Groovy compiler
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
Labels: @execution

#20552 Update samples with warning about aggregation android incompatibility
  subprojects/docs/src/samples/incubating/java/jvm-multi-project-with-code-coverage-distribution/README.adoc
  subprojects/docs/src/samples/incubating/java/jvm-multi-project-with-code-coverage-standalone/README.adoc
  subprojects/docs/src/samples/incubating/java/jvm-multi-project-with-test-aggregation-distribution/README.adoc
  subprojects/docs/src/samples/incubating/java/jvm-multi-project-with-test-aggregation-standalone/README.adoc
Labels: in:documentation

#20557 Disable java7 sample test on windows
  subprojects/docs/build.gradle
Labels: @dev-productivity

#20555 Speed up dependency resolution
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/dependencysubstitution/CachingDependencySubstitutionApplicator.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/excludes/ModuleExclusions.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/excludes/factories/NormalizingExcludeFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/excludes/simple/DefaultCompositeExclude.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/excludes/simple/DefaultExcludeAllOf.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/excludes/simple/DefaultExcludeAnyOf.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/excludes/specs/CompositeExclude.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/metadata/DefaultMavenImmutableAttributesFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ImmutableCapabilities.java
Labels: in:dependency-resolution, @support

#19864 Update Zinc used by the Scala plugin to 1.6.1
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
  subprojects/docs/src/docs/userguide/jvm/scala_plugin.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/snippets/scala/zincDependency/groovy/build.gradle
  subprojects/docs/src/snippets/scala/zincDependency/kotlin/build.gradle.kts
  subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/idea/IdeaIntegrationTest.groovy
  subprojects/scala/build.gradle.kts
  subprojects/scala/src/integTest/groovy/org/gradle/integtests/fixtures/ZincCoverage.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/ScalaPluginIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/UpToDateScalaCompileIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/ZincScalaCompilerIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/ZincScalaCompilerMultiVersionIntegrationTest.groovy
  subprojects/scala/src/integTest/resources/org/gradle/scala/compile/ZincScalaCompilerIntegrationTest/compilesScalaCodeIncrementally/src/main/scala/Other2.scala
  subprojects/scala/src/main/java/org/gradle/api/internal/tasks/scala/SbtLoggerAdapter.java
  subprojects/scala/src/main/java/org/gradle/api/internal/tasks/scala/TimeCheckingClassLoaderCache.java
  subprojects/scala/src/main/java/org/gradle/api/internal/tasks/scala/ZincScalaCompiler.java
  subprojects/scala/src/main/java/org/gradle/api/internal/tasks/scala/ZincScalaCompilerFactory.java
  subprojects/scala/src/main/java/org/gradle/api/plugins/scala/ScalaBasePlugin.java
  subprojects/scala/src/main/java/org/gradle/api/plugins/scala/ScalaPluginExtension.java
Labels: in:scala-plugin, @support, from:contributor

#20560 Add Kotlin version table
  subprojects/docs/src/docs/userguide/compatibility.adoc
Labels: in:kotlin-dsl, @support

#20565 Update aggregation samples to add warning about android plugin incompatibility
  subprojects/docs/src/samples/incubating/java/jvm-multi-project-with-code-coverage-distribution/README.adoc
  subprojects/docs/src/samples/incubating/java/jvm-multi-project-with-code-coverage-standalone/README.adoc
  subprojects/docs/src/samples/incubating/java/jvm-multi-project-with-test-aggregation-distribution/README.adoc
  subprojects/docs/src/samples/incubating/java/jvm-multi-project-with-test-aggregation-standalone/README.adoc
Labels: @core, in:documentation

#20567 Let config cache report serialization errors for incompatible tasks
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIncompatibleTasksIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ConfigurationCacheProblems.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ProblemsListener.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/Codec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/Contexts.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/beans/BeanPropertyWriter.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/CachedEnvironmentStateCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/TaskNodeCodec.kt
  subprojects/configuration-cache/src/test/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintCheckerTest.kt
Labels: in:configuration-cache, @configuration-cache

#20571 Fix flaky OverlappingOutputsIntegrationTest
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/changedetection/rules/OverlappingOutputsIntegrationTest.groovy
Labels: @dev-productivity

#19495 Delete distribution zip file after installing from the wrapper
  subprojects/docs/src/docs/release/notes.md
  subprojects/wrapper-shared/src/main/java/org/gradle/wrapper/Install.java
  subprojects/wrapper-shared/src/test/groovy/org/gradle/wrapper/InstallTest.groovy
  subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy
Labels: from:contributor

#20564 Update tested AGP versions
  gradle/dependency-management/agp-versions.properties
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/AndroidGradlePluginVersions.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerCachingSmokeTest.groovy
Labels: @configuration-cache

#20575 Fix flaky tests in ParallelTaskExecutionIntegrationTest
  subprojects/core/src/integTest/groovy/org/gradle/execution/taskgraph/ParallelTaskExecutionIntegrationTest.groovy
Labels: flaky-fix-it

#20578 Fix warnings in `subprojects/configuration-cache`
  subprojects/configuration-cache/build.gradle.kts
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/WorkNodeCodec.kt
Labels: a:chore, @configuration-cache

#20583 Use mirrored mavenCentral in configuration cache tests
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheExternalProcessInPluginIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheProblemReportingIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/SystemPropertyInstrumentationInKotlinIntegrationTest.groovy
Labels: flaky-fix-it

#20524 Remove build listener usage
  build-logic/lifecycle/src/main/kotlin/PrintStackTracesOnTimeoutBuildService.kt
  build-logic/lifecycle/src/main/kotlin/gradlebuild.lifecycle.gradle.kts
  build-logic/profiling/src/main/kotlin/gradlebuild.buildscan.gradle.kts
Labels: @dev-productivity

#20558 Fix flakyness in TaskExecutionIntegrationTest
  subprojects/core/src/integTest/groovy/org/gradle/api/FinalizerTaskIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskExecutionIntegrationTest.groovy
Labels: flaky-fix-it

#20587 Fix dependency metadata rule when removing elements
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/AbstractDependenciesMetadataAdapter.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/AbstractDependencyMetadataAdapter.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/DependencyConstraintMetadataAdapter.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/DependencyConstraintsMetadataAdapter.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/DirectDependenciesMetadataAdapter.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/DirectDependencyMetadataAdapter.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractRealisedModuleComponentResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractRealisedModuleResolveMetadataSerializationHelper.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/DefaultConfigurationMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/LazyToRealisedModuleComponentResolveMetadataHelper.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/VariantMetadataRules.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/DependencyMetadataRules.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/resolver/DependenciesMetadataAdapterTest.groovy
Labels: @support

#20604 Improve error messages on non-existing ref within closure
  subprojects/core/src/integTest/groovy/org/gradle/api/BuildScriptErrorIntegrationTest.groovy
  subprojects/model-core/src/main/java/org/gradle/util/internal/ClosureBackedAction.java
  subprojects/model-groovy/src/integTest/groovy/org/gradle/model/dsl/ModelMapDslIntegrationTest.groovy
  subprojects/version-control/src/integTest/groovy/org/gradle/vcs/internal/MappingSourceDependencyIntegrationTest.groovy
Labels: from:contributor
