Repository gradle/gradle, pull requests merged in 2022-08, with the labels that each got.

#21418 Smoke test Kotlin Gradle Plugin 1.7.20-Beta
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/KotlinGradlePluginVersions.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
Labels: a:chore

#21410 Very .m2/.gradle-enterprise is not polluted
  .teamcity/src/main/kotlin/common/extensions.kt
  .teamcity/src/main/kotlin/configurations/GradleBuildConfigurationDefaults.kt
Labels: in:building-gradle

#21425 Exit on failure from clean dir checking by default, but allow android dir checking to opt out if necessary
  .teamcity/src/main/kotlin/common/extensions.kt
  .teamcity/src/main/kotlin/configurations/GradleBuildConfigurationDefaults.kt
Labels: in:building-gradle

#21371 Re-deprecate methods for gradle 7.6
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/snippets/ide/ideaAdditionalTestSources/groovy/build.gradle
  subprojects/docs/src/snippets/ide/ideaAdditionalTestSources/kotlin/build.gradle.kts
  subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/AutoTestedSamplesIdeIntegrationTest.groovy
  subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/idea/IdeaModuleIntegrationTest.groovy
  subprojects/ide/src/main/java/org/gradle/plugins/ide/idea/model/IdeaModule.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractAutoTestedSamplesTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/GradleExecuter.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/NebulaPluginsSmokeTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestReportIntegrationTest.groovy
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/TestReport.java
Labels: a:chore, in:idea-plugin, in:reporting-tasks

#21407 Update test bucket json
  .teamcity/test-buckets.json
Labels: @dev-productivity

#21431 Implement Zinc bug workaround
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaFirstUsePerformanceTest.groovy
  subprojects/scala/src/main/java/org/gradle/api/internal/tasks/scala/ZincScalaCompiler.java
Labels: in:scala-plugin

#21389 Stop ProjectBuilder instances in more integration tests
  subprojects/kotlin-dsl/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/TaskContainerDslIntegrationTest.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/NamedContainersDslTest.kt
  subprojects/kotlin-dsl/src/testFixtures/kotlin/org/gradle/kotlin/dsl/fixtures/ProjectBuilder.kt
  subprojects/tooling-api/src/integTest/groovy/org/gradle/integtests/tooling/ToolingApiClasspathIntegrationTest.groovy
  subprojects/tooling-api/src/testFixtures/groovy/org/gradle/integtests/tooling/fixture/CrossVersionTestEngine.java
  subprojects/tooling-api/src/testFixtures/groovy/org/gradle/integtests/tooling/fixture/ToolingApiDistributionResolver.groovy
Labels: in:testing

#21447 Upgrade tested AGP versions
  gradle/dependency-management/agp-versions.properties
Labels: a:chore

#21448 Remove false claim from plugins user manual chapter
  subprojects/docs/src/docs/userguide/authoring-builds/plugins.adoc
Labels: a:bug, in:documentation

#21468 Not show build scan link for `updateReleasedVersions` task
  build-logic/basics/src/main/kotlin/gradlebuild/basics/BuildParams.kt
Labels: @dev-productivity

#21479 Use correct vcs root for non-master branches
  .teamcity/src/main/kotlin/configurations/GradleBuildConfigurationDefaults.kt
Labels: @dev-productivity

#21477 Update the version of the Grgit plugin used in a test
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/IsolatedAntBuilderMemoryLeakIntegrationTest.groovy
Labels: in:building-gradle

#21352 Collect failed tasks and report as TeamCity build problems
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.cache-miss-monitor.gradle.kts
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.code-quality.gradle.kts
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.collect-failed-tasks.gradle.kts
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild/AbstractBuildScanInfoCollectingService.kt
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild/BuildScanInfoCollectingServices.kt
  build-logic/build.gradle.kts
  build-logic/profiling/build.gradle.kts
  build-logic/profiling/src/main/kotlin/gradlebuild.buildscan.gradle.kts
  build-logic/profiling/src/main/kotlin/gradlebuild/buildscan/tasks/ExtractCodeQualityBuildScanData.kt
Labels: @dev-productivity

#21511 Adjust wording on upgrade guide
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
Labels: in:documentation

#17106 Remove deprecated AbstractTestTask methods
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/architecture-test/src/changes/archunit_store/provider-task-properties.txt
  subprojects/docs/src/docs/dsl/org.gradle.api.tasks.testing.AbstractTestTask.xml
  subprojects/docs/src/docs/userguide/compatibility.adoc
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/KotlinGradlePluginVersions.groovy
  subprojects/testing-base/src/main/java/org/gradle/api/tasks/testing/AbstractTestTask.java
Labels: @core

#21153 Report @Input annotation misapplied to File/Directory-based properties with useful error message
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/InputPropertyAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/execution/plan/DefaultNodeValidator.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/WorkValidationException.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ValidateStep.java
  subprojects/model-core/src/test/groovy/org/gradle/internal/reflect/validation/ValidationMessageCheckerTest.groovy
  subprojects/model-core/src/testFixtures/groovy/org/gradle/internal/reflect/validation/ValidationMessageChecker.groovy
  subprojects/model-core/src/testFixtures/groovy/org/gradle/internal/reflect/validation/ValidationMessageDisplayConfiguration.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/AbstractPluginValidationIntegrationSpec.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/RuntimePluginValidationIntegrationTest.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidatePluginsIntegrationTest.groovy
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/ValidatePlugins.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/SpringBootPluginSmokeTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestInputAnnotationFailuresIntegrationTest.groovy
Labels: @execution, in:execution-engine, in:problems

#21527 Fix deprecation warnings in smoke tests
  subprojects/smoke-test/build.gradle.kts
Labels: @dev-productivity

#17100 Remove deprecated Exec task method
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/architecture-test/src/changes/archunit_store/provider-task-properties.txt
  subprojects/core/src/main/java/org/gradle/api/tasks/AbstractExecTask.java
  subprojects/docs/src/docs/dsl/org.gradle.api.tasks.AbstractExecTask.xml
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/ExecIntegrationTest.groovy
Labels: @core

#21506 Add build parameters to run docsTest with configuration cache enabled
  build-logic/basics/src/main/kotlin/gradlebuild/basics/BuildParams.kt
  subprojects/docs/README.md
  subprojects/docs/build.gradle
  subprojects/docs/src/docsTest/java/org/gradle/docs/samples/BaseSamplesTest.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/logging/ConfigurationCacheOutputCleaner.java
Labels: @configuration-cache

#21546 Avoid printing ps output directly
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/timeout/JavaProcessStackTracesMonitor.java
Labels: @dev-productivity

#21540 Drop unused ScalaRuntime field
  subprojects/scala/src/main/java/org/gradle/api/tasks/scala/ScalaCompile.java
Labels: in:scala-plugin

#19158 Remove deprecated support for using tarTree() on resource without a backing file
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintWriter.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/FileCollectionCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/FileTreeCodec.kt
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/bundling/ArchiveIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/file/DefaultFileOperations.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/UnknownBackingFileReadableResource.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/archive/AbstractArchiveFileTree.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/archive/TarFileTree.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/FileParameterUtils.java
  subprojects/core/src/main/java/org/gradle/execution/plan/LocalTaskNodeExecutor.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/GenericFileTreeSnapshotter.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/DefaultFileCollectionSnapshotter.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/DefaultGenericFileTreeSnapshotter.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/FileSystemSnapshotBuilder.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/VirtualFileSystemServices.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/archive/AbstractArchiveFileTreeTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/archive/TarFileTreeTest.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuterTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/fingerprint/classpath/impl/DefaultClasspathFingerprinterTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/fingerprint/impl/AbsolutePathFileCollectionFingerprinterTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/fingerprint/impl/DefaultFileCollectionSnapshotterTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/fingerprint/impl/FileSystemSnapshotBuilderTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/api/file/FileCollectionMatchers.java
  subprojects/core/src/testFixtures/groovy/org/gradle/api/internal/file/TestFiles.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactoryTest.groovy
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/execution/src/integTest/groovy/org/gradle/internal/execution/IncrementalExecutionIntegrationTest.groovy
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/AbstractFileCollection.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/FileCollectionBackedFileTree.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/FileCollectionStructureVisitor.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/DefaultConfigurableFileCollection.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/FileTreeAdapter.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/FilteredMinimalFileTree.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/MinimalFileTree.java
  subprojects/file-collections/src/test/groovy/org/gradle/api/internal/file/DefaultFileCollectionFactoryTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskUpToDateIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/CompilationSourceDirs.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/continuous/AccumulateBuildInputsListener.java
  subprojects/plugins/src/test/groovy/org/gradle/api/tasks/testing/TestTest.groovy
Labels: @execution

#21534 Update documentation in JavaCompile to suggest configureEach {}
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
Labels: from:contributor

#21562 Polish JavaProcessStackTracesMonitor
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/timeout/IntegrationTestTimeoutInterceptor.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/timeout/JavaProcessStackTracesMonitor.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/ChainingHttpHandler.java
Labels: @dev-productivity

#21528 Import JUnit XML reports for cached Test tasks on TeamCity
  build-logic/lifecycle/src/main/kotlin/gradlebuild.teamcity-import-test-data.gradle.kts
  build.gradle.kts
Labels: @dev-productivity

#21566 Add ConfigCacheDocsTest to TeamCity
  .teamcity/src/main/kotlin/configurations/ConfigCacheDocsTest.kt
  .teamcity/src/main/kotlin/configurations/SmokeTests.kt
  .teamcity/src/main/kotlin/model/CIBuildModel.kt
Labels: @dev-productivity

#21569 Add thread dumps into TeamCity artifact rule
  .teamcity/src/main/kotlin/common/extensions.kt
Labels: @dev-productivity

#21570 Cherry pick dev prod improvements to release branch
  .teamcity/src/main/kotlin/common/extensions.kt
  build-logic/lifecycle/src/main/kotlin/gradlebuild.teamcity-import-test-data.gradle.kts
  build.gradle.kts
Labels: @dev-productivity

#21578 Cherry-pick 21352 to release
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.cache-miss-monitor.gradle.kts
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.code-quality.gradle.kts
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.collect-failed-tasks.gradle.kts
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild/AbstractBuildScanInfoCollectingService.kt
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild/BuildScanInfoCollectingServices.kt
  build-logic/build.gradle.kts
  build-logic/profiling/build.gradle.kts
  build-logic/profiling/src/main/kotlin/gradlebuild.buildscan.gradle.kts
  build-logic/profiling/src/main/kotlin/gradlebuild/buildscan/tasks/ExtractCodeQualityBuildScanData.kt
Labels: @dev-productivity

#21579 Fix threaddump artifact rule
  .teamcity/src/main/kotlin/common/extensions.kt
  build-logic/lifecycle/src/main/kotlin/PrintStackTracesOnTimeoutBuildService.kt
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/timeout/IntegrationTestTimeoutInterceptor.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/timeout/JavaProcessStackTracesMonitor.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/ChainingHttpHandler.java
Labels: @dev-productivity

#21567 Split the list of conf-cache incompatible snippets/samples
  subprojects/docs/build.gradle
Labels: @configuration-cache

#21538 Make Java launcher a nested input for Scala compilation
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AvailableJavaHomes.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/BuildOperationsFixture.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/jvm/JavaToolchainBuildOperationsFixture.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/JavaToolchainBuildOperationsIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/UpToDateScalaCompileIntegrationTest.groovy
  subprojects/scala/src/main/java/org/gradle/language/scala/tasks/AbstractScalaCompile.java
Labels: in:scala-plugin

#20097 Remove Serializable from PluginDeclaration
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/PluginDeclaration.java
Labels: @execution

#17079 Remove deprecated JavaExec.(get|set)Main
  build-logic/build-platform/build.gradle.kts
  gradle/verification-metadata.xml
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/architecture-test/src/changes/archunit_store/3c3e47be-b5ed-426a-8b9f-cfa00d3b09db
  subprojects/architecture-test/src/changes/archunit_store/provider-task-file-collection.txt
  subprojects/architecture-test/src/changes/archunit_store/provider-task-properties.txt
  subprojects/architecture-test/src/changes/archunit_store/provider-text-resource.txt
  subprojects/architecture-test/src/changes/archunit_store/public-api-mutable-properties.txt
  subprojects/core-api/src/main/java/org/gradle/process/JavaExecSpec.java
  subprojects/core/src/main/java/org/gradle/process/internal/DefaultJavaExecSpec.java
  subprojects/core/src/main/java/org/gradle/process/internal/JavaExecHandleBuilder.java
  subprojects/docs/README.md
  subprojects/docs/src/docs/dsl/org.gradle.api.tasks.JavaExec.xml
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/snippets/dependencyManagement/catalogs-settings/groovy/settings.gradle
  subprojects/docs/src/snippets/dependencyManagement/catalogs-settings/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/catalogs-toml/groovy/gradle/libs.versions.toml
  subprojects/docs/src/snippets/dependencyManagement/catalogs-toml/kotlin/gradle/libs.versions.toml
  subprojects/language-java/src/integTest/groovy/org/gradle/javadoc/JavadocIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/tasks/JavaExec.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/sources/process/DelegatingJavaExecSpec.java
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmComponentDependencies.java
  subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/ApplicationPluginTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AsciidoctorPluginSmokeTest.groovy
Labels: @core

#21586 Remove `@ToBeFixedForConfigurationCache` from `can publish java-library with dependencies`
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/AbstractMavenPublishJavaIntegTest.groovy
Labels: in:publishing-plugins, @configuration-cache

#21535 Deprecate usage of invalid Java toolchain specs
  subprojects/docs/src/docs/userguide/jvm/toolchains.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
  subprojects/platform-jvm/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainSpecIntegrationTest.groovy
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/JavaToolchainSpec.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/DefaultToolchainSpec.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainQueryService.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainSpecInternal.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/SpecificInstallationToolchainSpec.java
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/toolchain/internal/JavaToolchainQueryServiceTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaBasePlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/DefaultJavaPluginExtension.java
Labels: in:toolchains

#21536 Re-implement KillLeakingJavaProcesses
  .gitignore
  .teamcity/src/main/kotlin/common/extensions.kt
  .teamcity/src/main/kotlin/configurations/FlakyTestQuarantine.kt
  .teamcity/src/main/kotlin/configurations/GradleBuildConfigurationDefaults.kt
  .teamcity/src/main/kotlin/util/RerunFlakyTest.kt
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild/testcleanup/TestFilesCleanupRootPlugin.kt
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild/testcleanup/TestFilesCleanupService.kt
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild/testcleanup/extension/TestFilesCleanupBuildServiceRootExtension.kt
  build-logic/buildquality/src/main/kotlin/gradlebuild.configure-ci-artifacts.gradle.kts
  build-logic/cleanup/src/main/java/gradlebuild/cleanup/services/KillLeakingJavaProcesses.java
  build-logic/cleanup/src/main/kotlin/gradlebuild.cleanup.gradle.kts
  build-logic/cleanup/src/main/kotlin/gradlebuild/cleanup/services/DaemonTracker.kt
  build-logic/cleanup/src/main/kotlin/gradlebuild/cleanup/services/LeakingProcessKillPattern.kt
  build-logic/cleanup/src/main/kotlin/gradlebuild/cleanup/services/Process.kt
  build-logic/cleanup/src/main/kotlin/gradlebuild/cleanup/tasks/KillLeakingJavaProcesses.kt
  build-logic/cleanup/src/test/groovy/gradlebuild/cleanup/services/LeakingProcessKillPatternTest.groovy
  build-logic/profiling/src/main/kotlin/gradlebuild.buildscan.gradle.kts
Labels: @dev-productivity

#21601 Refine KillLeakingJavaProcesses
  build-logic/cleanup/src/main/java/gradlebuild/cleanup/services/KillLeakingJavaProcesses.java
  build-logic/cleanup/src/main/kotlin/gradlebuild.cleanup.gradle.kts
Labels: @dev-productivity

#21602 Cherry-pick #21536
  .gitignore
  .teamcity/src/main/kotlin/common/extensions.kt
  .teamcity/src/main/kotlin/configurations/FlakyTestQuarantine.kt
  .teamcity/src/main/kotlin/configurations/GradleBuildConfigurationDefaults.kt
  .teamcity/src/main/kotlin/util/RerunFlakyTest.kt
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild/testcleanup/TestFilesCleanupRootPlugin.kt
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild/testcleanup/TestFilesCleanupService.kt
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild/testcleanup/extension/TestFilesCleanupBuildServiceRootExtension.kt
  build-logic/buildquality/src/main/kotlin/gradlebuild.configure-ci-artifacts.gradle.kts
  build-logic/cleanup/src/main/java/gradlebuild/cleanup/services/KillLeakingJavaProcesses.java
  build-logic/cleanup/src/main/kotlin/gradlebuild.cleanup.gradle.kts
  build-logic/cleanup/src/main/kotlin/gradlebuild/cleanup/services/DaemonTracker.kt
  build-logic/cleanup/src/main/kotlin/gradlebuild/cleanup/services/LeakingProcessKillPattern.kt
  build-logic/cleanup/src/main/kotlin/gradlebuild/cleanup/services/Process.kt
  build-logic/cleanup/src/main/kotlin/gradlebuild/cleanup/tasks/KillLeakingJavaProcesses.kt
  build-logic/cleanup/src/test/groovy/gradlebuild/cleanup/services/LeakingProcessKillPatternTest.groovy
  build-logic/profiling/src/main/kotlin/gradlebuild.buildscan.gradle.kts
Labels: @dev-productivity

#21589 Let configuration cache handle cycles between included and root builds
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/AbstractCompositeBuildIntegrationTest.groovy
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildIncludeCycleIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/core/src/main/java/org/gradle/api/internal/BuildDefinition.java
  subprojects/core/src/main/java/org/gradle/internal/composite/ChildBuildRegisteringSettingsLoader.java
Labels: in:composite-builds, in:configuration-cache, @configuration-cache

#21440 Remove deprecated Upload task (Alternate Solution - Empty Placeholder Task)
  build-logic/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/TaskContainerExtensionsTest.kt
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/architecture-test/src/changes/archunit_store/provider-task-properties.txt
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/Configuration.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/BeforeResolveIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/Configurations.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/configurations/ConfigurationsTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationSpec.groovy
  subprojects/docs/src/docs/dsl/dsl.xml
  subprojects/docs/src/docs/dsl/org.gradle.api.tasks.Upload.xml
  subprojects/docs/src/docs/userguide/jvm/java_plugin.adoc
  subprojects/docs/src/docs/userguide/migration/migrating_from_groovy_to_kotlin_dsl.adoc
  subprojects/docs/src/samples/build-organization/structuring-software-projects/README.adoc
  subprojects/docs/src/samples/spring-boot-web-application/README.adoc
  subprojects/docs/src/snippets/kotlinDsl/applying-plugins-declarative/groovy/build.gradle
  subprojects/docs/src/snippets/kotlinDsl/applying-plugins-declarative/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/applying-plugins-imperative/groovy/build.gradle
  subprojects/docs/src/snippets/kotlinDsl/applying-plugins-imperative/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/configuring-tasks-spring-boot/groovy/build.gradle
  subprojects/docs/src/snippets/kotlinDsl/configuring-tasks-spring-boot/kotlin/build.gradle.kts
  subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyHttpsLegacyPublishIntegrationTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/AbstractIvyPublishIntegTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/AbstractLegacyIvyPublishTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/IvyEarProjectPublishIntegrationTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/IvyHttpLegacyPublishIntegrationTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/IvyHttpPublishIntegrationTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/IvyJavaProjectPublishIntegrationTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/IvyLocalPublishIntegrationTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/IvyPublishResolvedVersionsJavaIntegTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/IvySingleProjectPublishIntegrationTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/IvyVersionRangePublishIntegrationTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/integtests/publish/ivy/IvyWarProjectPublishIntegrationTest.groovy
  subprojects/ivy/src/testFixtures/groovy/org/gradle/api/publish/ivy/AbstractIvyRemoteLegacyPublishIntegrationTest.groovy
  subprojects/ivy/src/testFixtures/groovy/org/gradle/api/publish/ivy/WithUploadArchives.groovy
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/ConfigurationDeprecatedExtensions.kt
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/UploadTaskIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/tasks/Upload.java
  subprojects/plugins/src/test/groovy/org/gradle/api/tasks/UploadTest.groovy
  subprojects/resources-gcs/src/integTest/groovy/org/gradle/integtests/resource/gcs/ivy/IvyGcsUploadArchivesIntegrationTest.groovy
  subprojects/resources-s3/src/integTest/groovy/org/gradle/integtests/resource/s3/ivy/IvyS3UploadArchivesIntegrationTest.groovy
  subprojects/resources-sftp/src/integTest/groovy/org/gradle/api/publish/ivy/IvySftpLegacyPublishIntegrationTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/BomSupportPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/SpringBootPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/SpringDependencyManagementPluginSmokeTest.groovy
Labels: in:publishing-plugins, a:feature

#21607 Let config cache restore original field value when conventional value has incompatible type
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheConventionMappingIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/beans/BeanPropertyWriter.kt
Labels: in:configuration-cache, @configuration-cache

#21614 Don't generate psoutput files in tests
  build-logic/cleanup/src/main/java/gradlebuild/cleanup/services/KillLeakingJavaProcesses.java
Labels: @dev-productivity

#21605 Do not fallback to using equals on Java serialized values
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/changedetection/state/TaskCustomTypesInputPropertyIntegrationTest.groovy
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/model-core/src/main/java/org/gradle/internal/snapshot/impl/JavaSerializedValueSnapshot.java
Labels: @execution

#21587 Run doc snippets twice to check loading from the configuration cache
  subprojects/docs/build.gradle
  subprojects/docs/src/docsTest/java/org/gradle/docs/samples/IntegrationTestSamplesExecutor.java
Labels: @configuration-cache

#21606 Add note about improvement to config cache dependency resolution
  subprojects/docs/src/docs/release/notes.md
Labels: @configuration-cache

#21620 Fix configuration cache errors in writing-tasks/task-with-arguments
  subprojects/docs/build.gradle
  subprojects/docs/src/samples/writing-tasks/task-with-arguments/common/project-info/src/main/java/com/example/ProjectInfoTask.java
Labels: @configuration-cache

#21617 Remove gradlePromotionBranches VCS root
  .teamcity/src/main/kotlin/promotion/PublishBranchSnapshotFromQuickFeedback.kt
  .teamcity/src/main/kotlin/promotion/PublishNightlySnapshot.kt
  .teamcity/src/main/kotlin/promotion/PublishNightlySnapshotFromQuickFeedback.kt
  .teamcity/src/main/kotlin/promotion/PublishNightlySnapshotFromQuickFeedbackStepCheckReady.kt
  .teamcity/src/main/kotlin/promotion/PublishNightlySnapshotFromQuickFeedbackStepPromote.kt
  .teamcity/src/main/kotlin/promotion/PublishNightlySnapshotFromQuickFeedbackStepUpload.kt
  .teamcity/src/main/kotlin/promotion/StartReleaseCycleTest.kt
  .teamcity/src/main/kotlin/vcsroots/VcsRoots.kt
Labels: @dev-productivity

#21609 Add release note for --offline handling in config cache
  subprojects/docs/src/docs/release/notes.md
Labels: @configuration-cache, in:documentation

#17107 Remove deprecated Report methods
  build-logic/documentation/src/main/groovy/gradlebuild/docs/GradleJavadocsPlugin.java
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/architecture-test/src/changes/archunit_store/public-api-mutable-properties.txt
  subprojects/diagnostics/src/main/java/org/gradle/api/reporting/dependencies/HtmlDependencyReportTask.java
  subprojects/docs/src/docs/dsl/org.gradle.api.reporting.Report.xml
  subprojects/reporting/src/main/java/org/gradle/api/reporting/ConfigurableReport.java
  subprojects/reporting/src/main/java/org/gradle/api/reporting/Report.java
  subprojects/reporting/src/main/java/org/gradle/api/reporting/internal/SimpleReport.java
  subprojects/reporting/src/test/groovy/org/gradle/api/reporting/internal/TaskGeneratedSingleDirectoryReportTest.groovy
  subprojects/reporting/src/test/groovy/org/gradle/api/reporting/internal/TaskGeneratedSingleFileReportTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginAndroidGroovyDSLSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginAndroidKotlinDSLSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/NebulaPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/WithKotlinDeprecations.groovy
Labels: @core

#21631 Update cc-experiment plugin path in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: @configuration-cache

#21635 Merge release into master
  released-versions.json
  subprojects/build-operations/src/main/java/org/gradle/internal/operations/BuildOperationDescriptor.java
  subprojects/build-operations/src/main/java/org/gradle/internal/operations/OperationFinishEvent.java
  subprojects/build-operations/src/main/java/org/gradle/internal/operations/OperationStartEvent.java
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/AbstractCompositeBuildIntegrationTest.groovy
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildIncludeCycleIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheConventionMappingIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/beans/BeanPropertyWriter.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/ProviderCodecs.kt
  subprojects/core/src/main/java/org/gradle/api/internal/BuildDefinition.java
  subprojects/core/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/DependencyAdderExtensionModule.java
  subprojects/core/src/main/java/org/gradle/internal/composite/ChildBuildRegisteringSettingsLoader.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/DependencyAdderExtensions.kt
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/JavaToolchainBuildOperationsIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/tasks/javadoc/internal/JavadocToolAdapter.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/AbstractMinimalProvider.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/BiProvider.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/FlatMapProvider.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/MappingProvider.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/ProviderInternal.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/Providers.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/TransformBackedProvider.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/ValueSupplier.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/WithSideEffectProvider.java
  subprojects/model-core/src/main/java/org/gradle/internal/snapshot/impl/AbstractArraySnapshot.java
  subprojects/model-core/src/main/java/org/gradle/internal/snapshot/impl/AbstractListSnapshot.java
  subprojects/model-core/src/main/java/org/gradle/internal/snapshot/impl/AbstractMapSnapshot.java
  subprojects/model-core/src/main/java/org/gradle/internal/snapshot/impl/AbstractScalarValueSnapshot.java
  subprojects/model-core/src/main/java/org/gradle/internal/snapshot/impl/AbstractSetSnapshot.java
  subprojects/model-core/src/main/java/org/gradle/internal/snapshot/impl/EnumValueSnapshot.java
  subprojects/model-core/src/main/java/org/gradle/internal/snapshot/impl/ImmutableManagedValueSnapshot.java
  subprojects/model-core/src/main/java/org/gradle/internal/snapshot/impl/ImplementationValue.java
  subprojects/model-core/src/main/java/org/gradle/internal/snapshot/impl/ManagedValueSnapshot.java
  subprojects/model-core/src/main/java/org/gradle/internal/snapshot/impl/NullValueSnapshot.java
  subprojects/model-core/src/test/groovy/org/gradle/api/internal/provider/WithSideEffectProviderTest.groovy
  subprojects/model-core/src/testFixtures/groovy/org/gradle/api/internal/provider/ProviderSpec.groovy
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/DefaultJavaToolchainService.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/DefaultToolchainJavaCompiler.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/DefaultToolchainJavaLauncher.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainQueryService.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/impl/MapEntrySnapshot.java
Labels: @dev-productivity

#21582 Replace stalebot with actions/stale action
  .editorconfig
  .github/stale.yml
  .github/workflows/stale-issue.yml
Labels: @dev-productivity

#21633 Add note for Maven Publish support in config cache
  subprojects/docs/src/docs/release/notes.md
Labels: @configuration-cache, in:documentation

#21628 Fail when a task's input can't be resolved
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/MissingTaskDependenciesIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskExecutionContext.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/TaskExecution.java
  subprojects/core/src/main/java/org/gradle/execution/ProjectExecutionServices.java
  subprojects/core/src/main/java/org/gradle/execution/plan/LocalTaskNodeExecutor.java
  subprojects/core/src/main/java/org/gradle/execution/plan/MissingTaskDependencyDetector.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GradleScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuterTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/test/fixtures/AbstractProjectBuilderSpec.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationIntegrityCheckIntegTest.groovy
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/docs/userguide/troubleshooting/validation_problems.adoc
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/problems/ValidationProblemId.java
  subprojects/model-core/src/test/groovy/org/gradle/internal/reflect/validation/ValidationMessageCheckerTest.groovy
  subprojects/model-core/src/testFixtures/groovy/org/gradle/internal/reflect/validation/ValidationMessageChecker.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy
Labels: @execution

#17083 Remove deprecated (get|set)MainClassName in JavaApplication plugin
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/architecture-test/src/changes/archunit_store/provider-task-file-collection.txt
  subprojects/architecture-test/src/changes/archunit_store/provider-task-properties.txt
  subprojects/architecture-test/src/changes/archunit_store/public-api-mutable-properties.txt
  subprojects/docs/src/docs/dsl/org.gradle.jvm.application.tasks.CreateStartScripts.xml
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/ApplicationPluginConfigurationIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/ApplicationPluginIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaApplication.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/DefaultJavaApplication.java
  subprojects/plugins/src/main/java/org/gradle/jvm/application/tasks/CreateStartScripts.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/SpringBootPluginSmokeTest.groovy
Labels: @core

#21664 Remove unused PropertyValidationAccess class
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/PropertyValidationAccess.java
Labels: @execution

#21665 Increase lower version bound for TransformProgressEventCrossVersionSpec
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r51/TransformProgressEventCrossVersionSpec.groovy
Labels: @execution

#21622 Include klib as KNOWN_ZIP_EXTENSIONS for java normalization
  subprojects/core/src/integTest/groovy/org/gradle/normalization/ConfigureRuntimeClasspathNormalizationIntegrationTest.groovy
  subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/ZipHasher.java
Labels: @execution

#21625 Do not fall back to ignoring empty directories for skip when empty - Take 2
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/SkipWhenEmptyIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskInputFilePropertyRegistration.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/SnapshotTaskInputsBuildOperationResult.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/GetInputFilesVisitor.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/annotations/AbstractInputFilePropertyAnnotationHandler.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/DefaultFileCollectionSnapshotter.java
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/FileCollectionFingerprinterRegistrations.java
  subprojects/core/src/test/groovy/org/gradle/internal/fingerprint/impl/DefaultFileCollectionSnapshotterTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformationRegistrationFactory.java
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/execution/src/main/java/org/gradle/internal/execution/fingerprint/FileCollectionSnapshotter.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/fingerprint/impl/DefaultInputFingerprinter.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/fingerprint/impl/DefaultInputFingerprinterTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractAndroidSantaTrackerSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AsciidoctorPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginAndroidGroovyDSLSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginAndroidKotlinDSLSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ThirdPartyGradleModuleMetadataSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/WithAndroidDeprecations.groovy
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/DirectorySensitivity.java
Labels: @execution

#21670 Do not use `DeprecationLogger` in unit test
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactoryTest.groovy
Labels: @execution

#21645 Convert unknown implementation warning to error
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/tasks/SnapshotTaskInputsOperationIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalBuildIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/LambdaInputsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/NestedInputIntegrationTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuterTest.groovy
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/execution/src/main/java/org/gradle/internal/execution/history/changes/DefaultExecutionStateChangeDetector.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/history/changes/ImplementationChanges.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ValidateStep.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/history/changes/ImplementationChangesTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/InProcessGradleExecuter.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/OutputScrapingExecutionFailure.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/OutputScrapingExecutionResult.java
  subprojects/model-core/src/testFixtures/groovy/org/gradle/integtests/fixtures/ExecutionOptimizationDeprecationFixture.groovy
Labels: @execution

#21654 Add documentation for the new strongly-typed dependencies block (Test Suites)
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/jvm/jvm_test_suite_plugin.adoc
Labels: in:dependency-declarations, a:documentation, in:test-suites

#21693 Restore reporting of ignore empty directories to scans
  subprojects/core/src/integTest/groovy/org/gradle/api/internal/tasks/SnapshotTaskInputsOperationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/GetInputFilesVisitor.java
Labels: @execution

#21704 Fix typos
  .github/workflows/stale-issue.yml
  build-logic/lifecycle/src/main/kotlin/gradlebuild.lifecycle.gradle.kts
  subprojects/base-services/src/main/java/org/gradle/internal/service/scopes/PluginServiceRegistry.java
  subprojects/build-init/src/test/groovy/org/gradle/buildinit/plugins/internal/BuildScriptBuilderGroovyTest.groovy
  subprojects/build-init/src/test/groovy/org/gradle/buildinit/plugins/internal/BuildScriptBuilderKotlinTest.groovy
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildArtifactTransformIntegrationTest.groovy
  subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildTaskExcludeIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildOperationsIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheExternalProcessInstrumentationInJavaIntegrationTest.groovy
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/result/ComponentSelectionReason.java
  subprojects/core/src/integTest/groovy/org/gradle/api/CrossBuildScriptCachingIntegrationSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/execution/taskgraph/ParallelTaskExecutionIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/LoadBuildStructureBuildOperationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/classpath/DefaultModuleRegistry.java
  subprojects/core/src/main/java/org/gradle/internal/operations/notify/BuildOperationNotificationListenerRegistrar.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/file/FileOrUriNotationConverterTest.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/initialization/DefaultClassLoaderScopeTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/resource/local/UniquePathKeyFileStoreTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/service/scopes/ProjectBackedPropertyHostTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/VersionConflictResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformInputArtifactIntegrationTest.groovy
  subprojects/docs/src/docs/userguide/core-plugins/eclipse_plugin.adoc
  subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/component_metadata_rules.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_5.adoc
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
  subprojects/docs/src/docs/userguide/running-builds/performance.adoc
  subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/internal/EclipseJavaVersionMapper.java
  subprojects/internal-integ-testing/src/test/groovy/org/gradle/integtests/fixtures/logging/GroupedOutputFixtureTest.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoKotlinJvmPluginAggregationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractSourceIncrementalCompilationIntegrationTest.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/language/cpp/CppApplicationIntegrationTest.groovy
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/DaemonServerConnector.java
  subprojects/model-core/src/test/groovy/org/gradle/model/ManagedNamedTest.groovy
  subprojects/platform-base/src/integTest/groovy/org/gradle/language/base/VariantAspectExtractionIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/groovy/GroovySecurityManagerIssuesIntegrationTest.groovy
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/FileSystemAccess.java
  subprojects/testing-base/src/main/java/org/gradle/api/tasks/testing/TestFailureDetails.java
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r43/ToolingApiUnsupportedProviderCrossVersionSpec.groovy
Labels: from:contributor

#21716 Detect Java toolchain usage when setting executable on Test task
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/JavaToolchainBuildOperationsIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java
Labels: in:testing

#21713 Use immutable data structures for keys in toolchain cache
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/CurrentJvmToolchainSpec.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/DefaultToolchainSpec.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainQueryService.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainSpecInternal.java
  subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/SpecificInstallationToolchainSpec.java
  subprojects/platform-jvm/src/test/groovy/org/gradle/jvm/toolchain/internal/DefaultToolchainSpecTest.groovy
Labels: in:toolchains

#21751 Update tested agp version to 7.4.0-alpha10
  gradle/dependency-management/agp-versions.properties
Labels: @configuration-cache

#21555 Make a few doc snippets compatible with the configuration cache
  subprojects/docs/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-attributeSubstitutionRule/groovy/consumer/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/customizingResolution-attributeSubstitutionRule/kotlin/consumer/build.gradle.kts
  subprojects/docs/src/snippets/tasks/incrementalBuild-incrementalBuildAdvanced/groovy/buildSrc/src/main/java/org/example/Instrument.java
  subprojects/docs/src/snippets/tasks/incrementalBuild-incrementalBuildAdvanced/groovy/buildSrc/src/main/java/org/example/ProcessTemplates.java
  subprojects/docs/src/snippets/tasks/incrementalBuild-incrementalBuildAdvanced/kotlin/buildSrc/src/main/java/org/example/Instrument.java
  subprojects/docs/src/snippets/tasks/incrementalBuild-incrementalBuildAdvanced/kotlin/buildSrc/src/main/java/org/example/ProcessTemplates.java
Labels: @configuration-cache

#21739 Turn warning into error: transform input artifact of type File
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformValuesInjectionIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformer.java
Labels: @execution

#21740 Turn deprecation into error: classpath files containing path separator
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/file-collections/src/integTest/groovy/org/gradle/api/file/FileCollectionIntegrationTest.groovy
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/AbstractFileCollection.java
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/javadoc/JavadocIntegrationTest.groovy
Labels: @execution
