Repository gradle/gradle, pull requests merged in 2022-02, with the labels that each got.

#19777 Ensure consistent order for RuntimeClasspathNormalization.filters
  subprojects/core/src/integTest/groovy/org/gradle/normalization/ConfigureRuntimeClasspathNormalizationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/normalization/internal/DefaultRuntimeClasspathNormalization.java
Labels: @execution

#19770 Add CLASS or RUNTIME limitation to annotation processors
  subprojects/docs/src/docs/userguide/jvm/java_plugin.adoc
Labels: @execution

#19760 Add --groups option to tasks task
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/TaskReportTaskIntegrationTest.groovy
  subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/TaskReportTask.java
  subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/internal/AggregateMultiProjectTaskReportModel.java
  subprojects/diagnostics/src/test/groovy/org/gradle/api/tasks/diagnostics/internal/AggregateMultiProjectTaskReportModelTest.groovy
  subprojects/docs/src/docs/dsl/org.gradle.api.tasks.diagnostics.TaskReportTask.xml
  subprojects/docs/src/docs/release/notes.md
Labels: in:reporting-tasks

#19731 Propagate verification error in input validation
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationIntegrityCheckIntegTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationSignatureCheckIntegTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/DefaultLenientConfiguration.java
  subprojects/ide/src/test/groovy/org/gradle/plugins/ide/internal/tooling/eclipse/EclipseModelBuilderDependenciesTest.groovy
Labels: in:dependency-verification

#19774 Fix retry support of CrossVersionTestEngine
  subprojects/tooling-api/src/testFixtures/groovy/org/gradle/integtests/tooling/fixture/CrossVersionTestEngine.java
Labels: @dev-productivity

#19789 Run historical performance tests independent
  .teamcity/src/main/kotlin/model/CIBuildModel.kt
Labels: @dev-productivity

#19773 Force-enable watching when using continuous build
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractContinuousIntegrationTest.groovy
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunner.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/LauncherServices.java
  subprojects/launcher/src/test/groovy/org/gradle/tooling/internal/provider/FileSystemWatchingBuildActionRunnerTest.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r26/TestLauncherCrossVersionSpec.groovy
  subprojects/tooling-api/src/testFixtures/groovy/org/gradle/integtests/tooling/fixture/ContinuousBuildToolingApiSpecification.groovy
Labels: @execution

#19775 Update documentation for continuous build
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/reference/command_line_interface.adoc
Labels: @execution

#19755 Fix potential bugs in DefaultMutableAttributeContainer, simplify toString for easier debugging
  subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultMutableAttributeContainer.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/attributes/DefaultMutableAttributeContainerTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/jvm/internal/AbstractJvmPluginServicesTest.groovy
Labels: a:bug, @core, in:dependency-declarations

#19799 Merge release
  released-versions.json
  subprojects/core/src/integTest/groovy/org/gradle/normalization/ConfigureRuntimeClasspathNormalizationIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/normalization/internal/DefaultRuntimeClasspathNormalization.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationIntegrityCheckIntegTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationSignatureCheckIntegTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/DefaultLenientConfiguration.java
  subprojects/ide/src/test/groovy/org/gradle/plugins/ide/internal/tooling/eclipse/EclipseModelBuilderDependenciesTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidBuildPerformanceTest.groovy
Labels: @dev-productivity

#19798 Do not share resolvable artifacts between verified and non-verified resolve contexts
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/DependencyVerifyingModuleComponentRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/ResolveIvyFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/ArtifactVerificationOperation.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/ChecksumAndSignatureVerificationOverride.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/writer/WriteDependencyVerificationFile.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/modulecache/ResolvedArtifactCaches.java
Labels: in:dependency-verification

#19800 Rebaseline JavaFirstUsePerformanceTest
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaFirstUsePerformanceTest.groovy
Labels: @dev-productivity

#19801 Remove mention of Android build cache
  subprojects/docs/src/docs/userguide/build-cache/build_cache.adoc
Labels: @execution

#19772 Exit continuous build when not watching anything
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/FileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DefaultFileWatcherRegistry.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/BuildLifecycleAwareVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/FileSystemWatchingInformation.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingNotSupportedVirtualFileSystem.java
  subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/WatchingVirtualFileSystem.java
  subprojects/files/src/main/java/org/gradle/internal/file/FileHierarchySet.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractContinuousIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/SmokeContinuousIntegrationTest.groovy
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/ContinuousBuildActionExecutor.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/ContinuousBuildTriggerHandler.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/LauncherServices.java
  subprojects/launcher/src/test/groovy/org/gradle/tooling/internal/provider/ContinuousBuildActionExecutorTest.groovy
Labels: @execution

#19805 Let `max-problems` ignore problems from `notCompatibleWithConfigurationCache` tasks
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIncompatibleTasksIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ConfigurationCacheProblems.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ConfigurationCacheProblemsSummary.kt
Labels: @configuration-cache

#19810 Update wrapper to latest nightly
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore, in:building-gradle, @configuration-cache

#19617 Improve VfsRelativePath
  subprojects/core/src/main/java/org/gradle/execution/plan/ValuedVfsHierarchy.java
  subprojects/core/src/test/groovy/org/gradle/execution/plan/ValuedVfsHierarchyTest.groovy
  subprojects/functional/src/main/java/org/gradle/internal/collect/PersistentList.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/AbstractStorePathRelationshipHandler.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/ChildMap.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SnapshotUtil.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/VfsRelativePath.java
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/AbstractFileSystemNodeWithChildrenTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/AbstractIncompleteFileSystemNodeTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/VfsRelativePathTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/VirtualFileSystemTestSpec.groovy
Labels: @execution

#19825 Let config cache resolve `FilteredFileTree`s lazily
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheFileTreeIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/FileTreeCodec.kt
Labels: @configuration-cache

#19826 Store `FilteredMinimalFileTree` patterns to the configuration cache
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheFileTreeIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/FileTreeCodec.kt
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/FilteredMinimalFileTree.java
Labels: @configuration-cache

#19655 Fix build Java version assertion
  build-logic/settings.gradle.kts
  settings.gradle.kts
Labels: @dev-productivity

#19681 Include unit tests in Flaky test quarantine builds
  .teamcity/src/main/kotlin/configurations/FlakyTestQuarantine.kt
  .teamcity/src/main/kotlin/configurations/FunctionalTest.kt
  .teamcity/src/test/kotlin/CIConfigIntegrationTests.kt
Labels: flaky-fix-it

#19836 Remove build JDK vendor assertions
  settings.gradle.kts
Labels: @dev-productivity

#19841 Re-enable Kotlin plugin smoke tests
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractAndroidSantaTrackerSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AsciidoctorPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/BaseDeprecations.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinAndroidDeprecations.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginAndroidGroovyDSLSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginAndroidKotlinDSLSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/SmokeTestGradleRunner.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ThirdPartyGradleModuleMetadataSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/WithAndroidDeprecations.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/WithKotlinDeprecations.groovy
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/android-kotlin-example-kotlin-dsl/app/build.gradle.kts
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/android-kotlin-example-kotlin-dsl/app/src/main/kotlin/org/gradle/smoketest/kotlin/android/StringPrinterFragment.kt
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/android-kotlin-example/app/build.gradle
  subprojects/smoke-test/src/smokeTest/resources/org/gradle/smoketests/android-kotlin-example/app/src/main/kotlin/org/gradle/smoketest/kotlin/android/StringPrinterFragment.kt
Labels: @execution

#19846 Add 'CleanUpBuild' tag to kill process build steps
  .teamcity/src/main/kotlin/common/extensions.kt
Labels: @dev-productivity

#19855 Merge release
  released-versions.json
Labels: @dev-productivity

#19865 Propagate exit codes correctly in Windows scripts
  subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/windowsStartScript.txt
Labels: in:wrapper, windows

#19823 Return adapted child for getNode(ancestor)
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SnapshotUtil.java
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/AbstractIncompleteFileSystemNodeTest.groovy
Labels: @execution

#19641 Trim proxy port from System property
  subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/JavaSystemPropertiesProxySettings.java
  subprojects/resources-http/src/test/groovy/org/gradle/internal/resource/transport/http/JavaSystemPropertiesProxySettingsTest.groovy
Labels: @execution

#19872 Fix unreproducible test name
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/GradleRunnerGradleVersionIntegrationTest.groovy
Labels: @dev-productivity

#19885 Configure mirror for :kotlinNpmInstall task
  build-logic/basics/src/main/kotlin/gradlebuild/basics/BuildParams.kt
  build-logic/jvm/src/main/kotlin/gradlebuild/propagated-env-variables.kt
  build-logic/uber-plugins/src/main/kotlin/gradlebuild.internal.kotlin-js.gradle.kts
Labels: @dev-productivity

#19887 Upgrade tested AGP versions
  build-logic-settings/cc-experiment-plugin/src/main/kotlin/gradlebuild.internal.cc-experiment.settings.gradle.kts
  gradle/dependency-management/agp-versions.properties
  subprojects/docs/src/docs/userguide/compatibility.adoc
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidPluginsSmokeTest.groovy
Labels: @configuration-cache

#19144 Add other possible solution for OUTPUT_FILE_VALIDATOR
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/TaskParametersIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/ValidationActions.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/taskfactory/AnnotationProcessingTaskFactoryTest.groovy
  subprojects/model-core/src/test/groovy/org/gradle/internal/reflect/validation/ValidationMessageCheckerTest.groovy
  subprojects/model-core/src/testFixtures/groovy/org/gradle/internal/reflect/validation/ValidationMessageChecker.groovy
Labels: @execution, in:execution-engine

#19858 Make `TaskExecutionListener` task agnostic
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprint.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintChecker.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintController.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintWriter.kt
  subprojects/core/src/main/java/org/gradle/api/execution/internal/DefaultTaskInputsListeners.java
  subprojects/core/src/main/java/org/gradle/api/execution/internal/TaskInputsListener.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuter.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/TaskExecution.java
  subprojects/core/src/main/java/org/gradle/execution/ProjectExecutionServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/DefaultWorkInputListeners.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/ExecutionGlobalServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/ExecutionGradleServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GlobalScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/execution/ExecuteActionsTaskExecuterTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformContinuousBuildIntegrationTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactoryTest.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/UnitOfWork.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/WorkInputListener.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/WorkInputListeners.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/SkipEmptyWorkStep.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/SkipEmptyWorkStepTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractContinuousIntegrationTest.groovy
  subprojects/launcher/build.gradle.kts
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/BuildScriptChangesContinuousBuildIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/SmokeContinuousIntegrationTest.groovy
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/AccumulateBuildInputsListener.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/ContinuousBuildActionExecutor.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/LauncherServices.java
  subprojects/launcher/src/test/groovy/org/gradle/launcher/continuous/ContinuousIntegrationTestFixtureTest.groovy
  subprojects/launcher/src/test/groovy/org/gradle/tooling/internal/provider/ContinuousBuildActionExecutorTest.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/TestLauncherSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r25/ContinuousBuildCancellationCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r25/ContinuousBuildCrossVersionSpec.groovy
  subprojects/tooling-api/src/testFixtures/groovy/org/gradle/integtests/tooling/fixture/ContinuousBuildToolingApiSpecification.groovy
Labels: @execution

#19916 Extract workflow logic to bash script
  .github/workflows/add-to-dev-prod-project.yml
  .github/workflows/add-to-github-project.sh
Labels: @dev-productivity

#19919 Make `:outgoingVariants` and `:resolvableConfigurations` tasks work with the configuration cache
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/ExclusiveVariantsIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/LazyAttributesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/derived/MultiProjectVariantResolutionIntegrationTest.groovy
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/OutgoingVariantsReportTaskIntegrationTest.groovy
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/ResolvableConfigurationsReportTaskIntegrationTest.groovy
  subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/AbstractConfigurationReportTask.java
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoPluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/JavaPluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/JvmTestSuitePluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/jvm/JavaLibraryOutgoingElementsBuilderIntegrationTest.groovy
Labels: @configuration-cache, in:reporting-tasks

#19923 Automatically add execution items to project
  .github/workflows/add-to-dev-prod-project.yml
Labels: @execution

#19929 Rebasline RealLifeAndroidStudioPerformanceTest
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidStudioPerformanceTest.groovy
Labels: @dev-productivity

#19696 Simplify build cache load/store logic
  subprojects/build-cache-base/src/main/java/org/gradle/caching/internal/origin/OriginMetadataFactory.java
  subprojects/build-cache/build.gradle.kts
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/BuildCacheController.java
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/BuildCacheLoadCommand.java
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/BuildCacheStoreCommand.java
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/DefaultBuildCacheController.java
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/NoOpBuildCacheController.java
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/RootBuildCacheControllerRef.java
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/service/BaseRemoteBuildCacheServiceHandle.java
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/service/BuildCacheLoadResult.java
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/service/DefaultLocalBuildCacheServiceHandle.java
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/service/LoadTarget.java
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/service/LocalBuildCacheServiceHandle.java
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/service/NullLocalBuildCacheServiceHandle.java
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/service/NullRemoteBuildCacheServiceHandle.java
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/service/OpFiringRemoteBuildCacheServiceHandle.java
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/service/RemoteBuildCacheServiceHandle.java
  subprojects/build-cache/src/main/java/org/gradle/caching/local/internal/DirectoryBuildCacheService.java
  subprojects/build-cache/src/test/groovy/org/gradle/caching/internal/controller/DefaultBuildCacheControllerPackOperationExecutorTest.groovy
  subprojects/build-cache/src/test/groovy/org/gradle/caching/internal/controller/DefaultBuildCacheControllerTest.groovy
  subprojects/build-cache/src/test/groovy/org/gradle/caching/internal/origin/OriginMetadataFactoryTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CacheTaskOutputIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedTaskIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/caching/internal/BuildCacheServices.java
  subprojects/core/src/main/java/org/gradle/caching/internal/controller/impl/DefaultBuildCacheCommandFactory.java
  subprojects/core/src/main/java/org/gradle/caching/internal/services/BuildCacheControllerFactory.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/ExecutionGradleServices.java
  subprojects/core/src/test/groovy/org/gradle/caching/internal/controller/BuildCacheControllerFactoryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactoryTest.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/BuildCacheStep.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/BuildCacheStepTest.groovy
Labels: @execution

#19877 Remove special case when snapshotting file trees with a missing root
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/DefaultFileCollectionSnapshotter.java
  subprojects/docs/src/snippets/tasks/incrementalBuild-incrementalBuildAdvanced/groovy/buildSrc/src/main/java/org/example/Instrument.java
  subprojects/docs/src/snippets/tasks/incrementalBuild-incrementalBuildAdvanced/kotlin/buildSrc/src/main/java/org/example/Instrument.java
  subprojects/language-native/src/test/groovy/org/gradle/language/assembler/tasks/AssemblerTest.groovy
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/impl/RelativePathFingerprintingStrategy.java
  subprojects/snapshots/src/test/groovy/org/gradle/internal/fingerprint/impl/PathNormalizationStrategyTest.groovy
Labels: @execution

#19928 Rebaseline performance tests with stale baselines
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/AndroidIncrementalExecutionPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingNativePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/buildcache/TaskOutputCachingSwiftPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ArchiveTreePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/DeprecationCreationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/IdeIntegrationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/LargeDependencyGraphPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/ParallelDownloadsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/RichConsolePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/TaskCreationPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/corefeature/VerboseTestOutputPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/inception/BuildSrcApiChangePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaCleanAssemblePerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaDependencyReportPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeBuildDependentsPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/NativeCleanBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/RealWorldNativePluginPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftBuildPerformanceTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/nativeplatform/SwiftCleanBuildPerformanceTest.groovy
Labels: @dev-productivity

#19905 Move unused methods from ReadOnlyFileSystemNode
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/AbstractFileSystemLocationSnapshot.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/AbstractIncompleteFileSystemNode.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/DirectorySnapshot.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/FileSystemNode.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/ReadOnlyFileSystemNode.java
  subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/SnapshotUtil.java
  subprojects/snapshots/src/main/java/org/gradle/internal/vfs/impl/DefaultSnapshotHierarchy.java
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/AbstractFileSystemLeafSnapshotTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/AbstractFileSystemNodeWithChildrenTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/AbstractIncompleteFileSystemNodeTest.groovy
  subprojects/snapshots/src/test/groovy/org/gradle/internal/snapshot/DirectoryNodeTest.groovy
Labels: @execution

#19886 Make :dependencyInsight compatible with the configuration cache
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/CapabilitiesCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/alignment/AlignmentIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/capabilities/CapabilitiesLocalComponentIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/constraints/DependencyConstraintsIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/locking/MixedDependencyLockingIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/locking/MultiProjectDependencyLockingIntegrationTest.groovy
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/DependencyInsightReportTaskIntegrationTest.groovy
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/DependencyInsightReportVariantDetailsIntegrationTest.groovy
  subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/DependencyInsightReportTask.java
  subprojects/scala/src/integTest/groovy/org/gradle/scala/ScalaPluginIntegrationTest.groovy
Labels: @configuration-cache, in:dependency-resolution

#19947 Use new GH action for adding to projects
  .github/workflows/add-to-dev-prod-project.yml
  .github/workflows/add-to-github-project.sh
Labels: @dev-productivity

#19949 Rebasline JavaIDEModelPerformanceTest
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIDEModelPerformanceTest.groovy
Labels: @dev-productivity

#19984 Revert #19877: Remove special case when snapshotting file trees with a missing root
  subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/DefaultFileCollectionSnapshotter.java
  subprojects/language-native/src/test/groovy/org/gradle/language/assembler/tasks/AssemblerTest.groovy
  subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/impl/RelativePathFingerprintingStrategy.java
  subprojects/snapshots/src/test/groovy/org/gradle/internal/fingerprint/impl/PathNormalizationStrategyTest.groovy
Labels: @execution

#19985 Fix AbstractMinimalProvider.toString()
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/AbstractMinimalProvider.java
  subprojects/model-core/src/test/groovy/org/gradle/api/internal/provider/AbstractMinimalProviderTest.groovy
Labels: @execution

#19652 Use Kotlin 1.6.20-M1
  build-logic/basics/src/main/kotlin/gradlebuild/basics/util/KotlinSourceParser.kt
  build-logic/build-platform/build.gradle.kts
  build-logic/uber-plugins/src/main/kotlin/gradlebuild.kotlin-library.gradle.kts
  gradle.properties
  gradle/verification-metadata.xml
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheException.kt
Labels: @dev-productivity

#19994 Rebaseline JavaIncrementalExecutionPerformanceTest
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaIncrementalExecutionPerformanceTest.groovy
Labels: @dev-productivity

#19922 Deprecate already joined paths when calling FileCollection.getAsPath
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/file-collections/src/integTest/groovy/org/gradle/api/file/FileCollectionIntegrationTest.groovy
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/AbstractFileCollection.java
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/javadoc/JavadocIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/tasks/javadoc/Javadoc.java
Labels: @execution

#19672 Pass more information to top exception on build cache load/store failure
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/DefaultBuildCacheController.java
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CacheTaskArchiveErrorIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedCustomTaskExecutionIntegrationTest.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/BuildCacheStep.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/BuildCacheStepTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractIntegrationSpec.groovy
Labels: @execution

#19997 Make `accepted-public-api-changes.json` a configuration cache input
  build-logic/binary-compatibility/src/main/groovy/gradlebuild.binary-compatibility.gradle
Labels: in:building-gradle, @configuration-cache

#19988 Add input artifact name to inputs
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformInputArtifactIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java
  subprojects/dependency-management/src/test/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformInvocationTest.groovy
Labels: @execution

#20004 Fix configuration cache report after upgrade to Kotlin 1.6.20-M1
  gradle.properties
Labels: in:building-gradle, @configuration-cache

#19986 Expand generics on Provider.zip()
  subprojects/core-api/src/main/java/org/gradle/api/provider/Provider.java
  subprojects/core-api/src/main/java/org/gradle/api/provider/ProviderFactory.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/BiProvider.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/DefaultProviderFactory.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/ProviderInternal.java
Labels: @execution

#19902 Fix the type of the processResources task in the documentation
  subprojects/docs/src/docs/userguide/jvm/building_java_projects.adoc
  subprojects/docs/src/docs/userguide/jvm/java_plugin.adoc
  subprojects/docs/src/docs/userguide/migration/migrating_from_maven.adoc
Labels: in:file-tasks

#19891 Fix modularized JavaDoc when exclusions are used
  subprojects/language-java/src/integTest/groovy/org/gradle/javadoc/JavadocModularizedJavaIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/tasks/javadoc/Javadoc.java
  subprojects/language-java/src/main/java/org/gradle/external/javadoc/CoreJavadocOptions.java
  subprojects/language-java/src/main/java/org/gradle/external/javadoc/MinimalJavadocOptions.java
  subprojects/language-java/src/test/groovy/org/gradle/external/javadoc/StandardJavadocDocletOptionsTest.java
Labels: in:modular-java, a:documentation, in:javadoc-task

#19977 Do not show VFS verbose logs by default
  gradle.properties
Labels: @execution, in:virtual-file-system

#20014 Clarify release notes re: aggregation plugins
  subprojects/docs/src/docs/release/notes.md
Labels: @core, a:documentation

#20018 Make testJavaVersion/testJavaVendor configurable in adhoc performance test
  .teamcity/src/main/kotlin/common/performance-test-extensions.kt
  .teamcity/src/main/kotlin/util/AdHocPerformanceScenario.kt
Labels: @dev-productivity

#20028 Fix mapping a ValueProvider with configuration caching
  subprojects/model-core/src/integTest/groovy/org/gradle/api/provider/PropertyIntegrationTest.groovy
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/Collectors.java
Labels: @configuration-cache

#19893 Enable config cache state debugging via Gradle property
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheDebugLogIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheBuildOperations.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheIO.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultConfigurationCache.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/ConfigurationCacheStartParameter.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/Contexts.kt
  subprojects/core/src/main/java/org/gradle/api/internal/StartParameterInternal.java
  subprojects/core/src/main/java/org/gradle/initialization/StartParameterBuildOptions.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/configurationcache/ConfigurationCacheBuildOperationsFixture.groovy
  subprojects/launcher/src/main/java/org/gradle/launcher/cli/CommandLineAction.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/action/BuildActionSerializer.java
Labels: @configuration-cache

#20027 Allow configuring the quiet period for continuous build
  subprojects/core/src/main/java/org/gradle/api/internal/StartParameterInternal.java
  subprojects/core/src/main/java/org/gradle/initialization/StartParameterBuildOptions.java
  subprojects/docs/src/docs/userguide/reference/command_line_interface.adoc
  subprojects/docs/src/docs/userguide/running-builds/build_environment.adoc
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/ContinuousBuildChangeReportingIntegrationTest.groovy
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/action/BuildActionSerializer.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/continuous/ContinuousBuildActionExecutor.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/continuous/ContinuousBuildTriggerHandler.java
Labels: @execution

#19938 Make test tasks shouldRunAfter jar tasks in the same project by default
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/MavenConversionIntegrationTest.groovy
  subprojects/docs/src/snippets/testing/test-suite-plugin/tests/checkTaskOutput.out
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/BlockingHttpServer.java
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/JavaPluginIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java
Labels: in:testing, a:feature, @core, in:java-plugins

#19970 Add optional artifacts to component metadata
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/derived/DerivedVariantsResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenCustomPackagingResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenPomPackagingResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/maven/MavenSnapshotResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/VariantFilesMetadataRulesIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/CacheLayout.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/CachingModuleComponentRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/RepositoryChainArtifactResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/DefaultArtifactSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/LenientPlatformResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/ExternalResourceResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/IvyResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/MavenResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractModuleComponentResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractRealisedModuleResolveMetadataSerializationHelper.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/FixedComponentArtifacts.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/JavaEcosystemVariantDerivationStrategy.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ModuleComponentOptionalArtifactMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ModuleComponentResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/maven/DefaultMavenModuleResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/maven/RealisedMavenModuleResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/ComponentArtifactMetadata.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/CacheLayoutTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/resolver/MavenResolverTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/external/model/DefaultMutableMavenModuleResolveMetadataTest.groovy
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/dependency_resolution.adoc
Labels: @core

#20036 Use Kotlin 1.7.0-dev-1904 to fix incremental compilation
  build-logic/basics/src/main/kotlin/gradlebuild.repositories.gradle.kts
  build-logic/binary-compatibility/src/test/kotlin/gradlebuild/binarycompatibility/AbstractBinaryCompatibilityTest.kt
  build-logic/build-platform/build.gradle.kts
  build-logic/settings.gradle.kts
  settings.gradle.kts
Labels: @dev-productivity

#19979 Fix documentation issues regarding range selection
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/VersionConflictResolutionIntegrationTest.groovy
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/dependency_resolution.adoc
Labels: in:dependency-resolution, a:documentation

#20012 Support for constraints on projects
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/constraints/DependencyConstraintsIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/constraints/PublishedDependencyConstraintsIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/moduleconverter/dependencies/DefaultDependencyDescriptorFactory.java
Labels: in:dependency-resolution
