Repository gradle/gradle, pull requests merged in 2023-07, with the labels that each got.

#25580 Update test bucket json
  .teamcity/test-buckets.json
Labels: @dev-productivity

#25578 Upgrade wrapper to Gradle 8.2
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore

#25468 Resolve poor performance when running a subset of finalized tasks
  .teamcity/performance-test-durations.json
  .teamcity/performance-tests-ci.json
  gradle.properties
  subprojects/core/src/main/java/org/gradle/execution/plan/FinalizerGroup.java
  subprojects/core/src/main/java/org/gradle/execution/plan/Node.java
  subprojects/core/src/main/java/org/gradle/execution/plan/TaskNode.java
  subprojects/core/src/test/groovy/org/gradle/execution/plan/DefaultExecutionPlanTest.groovy
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidBuildPerformanceTest.groovy
Labels: in:scheduler, in:performance-test, 10 min review, platform:release-coordination, platform:build-infrastructure

#25129 Decouple Maven publishing from component
  subprojects/architecture-test/src/changes/archunit_store/internal-api-nullability.txt
  subprojects/core/src/main/java/org/gradle/api/internal/component/SoftwareComponentInternal.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/projectmodule/DefaultProjectDependencyPublicationResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/projectmodule/DefaultProjectPublication.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/projectmodule/ProjectComponentPublication.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/projectmodule/DefaultProjectDependencyPublicationResolverTest.groovy
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publication/DefaultIvyPublication.java
  subprojects/language-native/src/main/java/org/gradle/swiftpm/internal/NativeProjectPublication.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/DefaultMavenPom.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/DefaultMavenPomDependencies.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/DefaultMavenPublication.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/MavenPomDependencies.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/MavenPomInternal.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/MavenPublicationInternal.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/package-info.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/tasks/MavenPomFileGenerator.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/tasks/GenerateMavenPom.java
  subprojects/maven/src/test/groovy/org/gradle/api/publish/maven/internal/publication/DefaultMavenPublicationTest.groovy
  subprojects/maven/src/test/groovy/org/gradle/api/publish/maven/internal/tasks/MavenPomFileGeneratorTest.groovy
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/metadata/ModuleMetadataSpecBuilder.java
  subprojects/publish/src/main/java/org/gradle/api/publish/tasks/GenerateModuleMetadata.java
  subprojects/publish/src/test/groovy/org/gradle/api/publish/internal/metadata/GradleModuleMetadataWriterTest.groovy
Labels: 30 min review, platform:software

#25458 Fix ready-for-merge tests that fail because of file encoding problems
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/SwiftApplicationInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/SwiftLibraryInitIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/AbstractHttpScriptPluginIntegrationSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/BuildScriptExecutionIntegrationSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/HttpScriptPluginInEncodingtegrationSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/HttpScriptPluginIntegrationSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopySpecEncodingIntegrationSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopySpecIntegrationSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskEncodingIntegrationSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskIntegrationSpec.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/xcode/XcodeMultipleProjectIntegrationTest.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/xcode/XcodeMultipleSwiftProjectIntegrationTest.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/xcode/XcodeSingleSwiftProjectIntegrationTest.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/xcode/XcodeSwiftApplicationWithXCTestProjectIntegrationTest.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/xcode/XcodeSwiftBothLibraryLinkageWithXCTestProjectIntegrationTest.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/xcode/XcodeSwiftExternalSourceDependenciesIntegrationTest.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/xcode/XcodeSwiftSharedLibraryLinkageWithXCTestProjectIntegrationTest.groovy
  subprojects/ide-native/src/integTest/groovy/org/gradle/ide/xcode/XcodeSwiftStaticLibraryLinkageWithXCTestProjectIntegrationTest.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/language/swift/SwiftApplicationCppInteroperabilityIntegrationTest.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/language/swift/SwiftDependenciesCppInteroperabilityIntegrationTest.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/language/swift/SwiftLibraryCppInteroperabilityIntegrationTest.groovy
  subprojects/maven/src/crossVersionTest/groovy/org/gradle/api/publish/maven/MavenPublishCrossVersionIntegrationTest.groovy
  subprojects/platform-native/src/testFixtures/groovy/org/gradle/language/swift/AbstractSwiftMixedLanguageIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/bundling/JarEncodingIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/bundling/JarIntegrationTest.groovy
  subprojects/testing-native/src/integTest/groovy/org/gradle/nativeplatform/test/xctest/SwiftXCTestCppInteroperabilityIntegrationTest.groovy
  subprojects/testing-native/src/integTest/groovy/org/gradle/nativeplatform/test/xctest/XCTestTestFrameworkIntegrationTest.groovy
Labels: @execution

#25596 Full nagging for deprecation of NameMatcher
  subprojects/core/src/main/java/org/gradle/util/NameMatcher.java
Labels: a:chore

#25575 Fix stale documentation in Category.java.
  subprojects/core-api/src/main/java/org/gradle/api/attributes/Category.java
Labels: from:contributor

#25591 Tidy up some filenames and documentation from #25382
  subprojects/testing-junit-platform/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestExecutionListener.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/failure/RootAssertionToFailureMapper.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/failure/mappers/OpenTestAssertionFailedMapper.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/failure/mappers/OpenTestMultipleFailuresErrorMapper.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitTestEventAdapter.java
  subprojects/testing-jvm-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/failure/mappers/OpenTestMultipleFailuresMapperTestError.groovy
Labels: @ide-experience

#25597 Ensure the transform identities are unique per execution history store
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/MutableTransformExecution.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/MutableTransformWorkspaceIdentity.java
Labels: in:artifact-transforms

#25471 Avoid carrying current build op into worker context
  subprojects/build-operations/src/main/java/org/gradle/internal/operations/CurrentBuildOperationPreservingRunnable.java
  subprojects/build-operations/src/main/java/org/gradle/internal/operations/CurrentBuildOperationRef.java
  subprojects/build-operations/src/test/groovy/org/gradle/internal/operations/CurrentBuildOperationPreservingRunnableTest.groovy
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultBuildController.java
  subprojects/core/src/main/java/org/gradle/execution/taskgraph/DefaultTaskExecutionGraph.java
  subprojects/core/src/main/java/org/gradle/process/internal/DefaultExecHandle.java
  subprojects/core/src/main/java/org/gradle/process/internal/streams/OutputStreamsForwarder.java
  subprojects/core/src/main/java/org/gradle/process/internal/worker/DefaultMultiRequestWorkerProcessBuilder.java
  subprojects/core/src/main/java/org/gradle/process/internal/worker/request/WorkerAction.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/timeout/impl/DefaultTimeoutHandler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/DaemonJavaCompiler.java
  subprojects/language-jvm/src/testFixtures/groovy/org/gradle/api/tasks/compile/AbstractCompilerDaemonReuseIntegrationTest.groovy
  subprojects/messaging/src/main/java/org/gradle/internal/dispatch/AsyncDispatch.java
  subprojects/plugins/build.gradle.kts
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/daemon/JavaCompilerDaemonFailureIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/daemon/JavaCompilerDaemonReuseIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/daemon/ScalaCompilerDaemonReuseIntegrationTest.groovy
  subprojects/soak/src/integTest/groovy/org/gradle/jvm/JavaCompilationSoakTest.groovy
  subprojects/workers/build.gradle.kts
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerDaemonFailureLoggingIntegrationTest.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerDaemonLoggingIntegrationTest.groovy
Labels: a:bug, in:workers, in:java-plugins, build-script-change, 30 min review, platform:jvm, platform:release-coordination, platform:core, platform:bt-ge-build-cache, platform:execution

#25626 Allow lazy configuration dependencies to resolve current project
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ProjectDependencyResolveIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/moduleconverter/dependencies/DefaultLocalConfigurationMetadataBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/local/model/DefaultLocalConfigurationMetadata.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/moduleconverter/dependencies/DefaultLocalConfigurationMetadataBuilderTest.groovy
Labels: 10 min review, platform:software

#25607 Omit link to CC report when no CC problems exist
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/AbstractConfigurationCacheIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheProblemReportingIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/ConfigurationCacheStartParameter.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ConfigurationCacheProblems.kt
  subprojects/docs/src/snippets/configurationCache/problemsFixed/tests/store-another.out
  subprojects/docs/src/snippets/configurationCache/problemsFixed/tests/store.out
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/AbstractGradleExecuter.java
  subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/file/TestFile.java
Labels: in:configuration-cache

#25640 Prepare for Gradle 8.2.1
  released-versions.json
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  version.txt
Labels: a:chore

#25625 Don't use `withVariantReselection` for Jacoco report aggregation with only the `classes` attribute present
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoAggregationIntegrationTest.groovy
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoReportAggregationPlugin.java
Labels: in:testing, in:jacoco-plugin, 1 min review, platform:jvm

#25642 Bump OpenTest4j required version in testing from 1.3.0-RC2 to 1.3.0
  subprojects/testing-jvm-infrastructure/build.gradle.kts
Labels: @ide-experience

#25641 Merge release into master
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ProjectDependencyResolveIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/moduleconverter/dependencies/DefaultLocalConfigurationMetadataBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/local/model/DefaultLocalConfigurationMetadata.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/moduleconverter/dependencies/DefaultLocalConfigurationMetadataBuilderTest.groovy
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/GradleRunnerUnsupportedFeatureFailureIntegrationTest.groovy
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/GradleRunnerUnsupportedGradleVersionFailureIntegrationTest.groovy
  subprojects/test-kit/src/main/java/org/gradle/testkit/runner/internal/ToolingApiGradleExecutor.java
  subprojects/test-kit/src/main/java/org/gradle/testkit/runner/internal/feature/BuildResultOutputFeatureCheck.java
  subprojects/test-kit/src/main/java/org/gradle/testkit/runner/internal/feature/TestKitFeature.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/DefaultGradleConnector.java
Labels: 20 min review, platform:software, platform:extensibility, platform:ide

#25627 Enable persistent compiler daemons by default
  subprojects/docs/src/docs/release/notes.md
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/ForkCapableRelocationIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/DaemonJavaCompiler.java
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/daemon/JavaCompilerDaemonReuseIntegrationTest.groovy
  subprojects/soak/src/integTest/groovy/org/gradle/jvm/JavaCompilationSoakTest.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerDaemonLifecycleTest.groovy
Labels: 1 min review, platform:jvm, platform:release-coordination, platform:core, platform:build-infrastructure, platform:documentation

#25652 Remove all unwanted occurrences of o.g.unsafe.c-c
  gradle.properties
  subprojects/docs/src/docs/userguide/running-builds/performance.adoc
  subprojects/docs/src/snippets/configurationCache/disallowedTypes/groovy/gradle.properties
  subprojects/docs/src/snippets/configurationCache/disallowedTypes/kotlin/gradle.properties
  subprojects/docs/src/snippets/configurationCache/noProblem/groovy/gradle.properties
  subprojects/docs/src/snippets/configurationCache/problemsFixed/groovy/gradle.properties
  subprojects/docs/src/snippets/configurationCache/problemsFixed/kotlin/gradle.properties
  subprojects/docs/src/snippets/configurationCache/problemsFixedReuse/groovy/gradle.properties
  subprojects/docs/src/snippets/configurationCache/problemsFixedReuse/kotlin/gradle.properties
  subprojects/docs/src/snippets/configurationCache/problemsGroovy/groovy/gradle.properties
  subprojects/docs/src/snippets/configurationCache/problemsKotlin/kotlin/gradle.properties
  subprojects/docs/src/snippets/configurationCache/projectAtExecution/groovy/gradle.properties
  subprojects/docs/src/snippets/configurationCache/projectAtExecution/kotlin/gradle.properties
  subprojects/docs/src/snippets/configurationCache/projectAtExecutionFixed/groovy/gradle.properties
  subprojects/docs/src/snippets/configurationCache/projectAtExecutionFixed/kotlin/gradle.properties
  subprojects/docs/src/snippets/configurationCache/stableFeatureFlag/common/gradle.properties
  subprojects/docs/src/snippets/configurationCache/topLevel/common/gradle.properties
  subprojects/launcher/src/test/groovy/org/gradle/launcher/cli/converter/StartParameterConverterTest.groovy
Labels: @configuration-cache, a:documentation, 5 min review

#25657 Finalize 8.2.1 release notes
  subprojects/docs/src/docs/release/notes.md
Labels: a:chore

#25545 support environment variables for maven toolchain
  subprojects/jvm-services/src/main/java/org/gradle/jvm/toolchain/internal/MavenToolchainsInstallationSupplier.java
  subprojects/jvm-services/src/test/groovy/org/gradle/jvm/toolchain/internal/MavenToolchainsInstallationSupplierTest.groovy
Labels: from:contributor

#25619 Apply coarse locking on all projects to solve deprecation warning
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/build/TestProjectInitiation.groovy
  subprojects/kotlin-dsl-tooling-builders/src/crossVersionTest/groovy/org/gradle/kotlin/dsl/tooling/builders/r83/KotlinBuildScriptModelCrossVersionSpec.groovy
  subprojects/kotlin-dsl-tooling-builders/src/integTest/groovy/org/gradle/kotlin/dsl/tooling/builders/KotlinDslScriptsModelSpec.groovy
  subprojects/kotlin-dsl-tooling-builders/src/main/kotlin/org/gradle/kotlin/dsl/tooling/builders/KotlinDslScriptsModelBuilder.kt
Labels: a:bug, in:tooling-api, in:kotlin-dsl

#25653 Fix broken looking link to JavaCompile on Build Environment docs page
  subprojects/docs/src/docs/userguide/running-builds/build_environment.adoc
Labels: a:documentation, 1 min review, platform:documentation

#25665 Fix backward compatibility for task options where only negated option is set
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/options/BooleanOptionElement.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/options/OptionReaderTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TaskBooleanOptionIntegrationTest.groovy
Labels: @execution, in:writing-tasks

#25667 Update gitstream automations for various requests
  .cm/change_categories.cm
  .cm/code_experts.cm
  .cm/complex_changes.cm
  .cm/estimated_time_to_review.cm
  .cm/includes_todos.cm
  .cm/lacks_tests.cm
  .cm/percentage_new.cm
Labels: cm-changes

#25621 Move some project configuration at project creation time
  subprojects/core/src/main/java/org/gradle/api/internal/project/ProjectFactory.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/DefaultProjectSpec.groovy
  subprojects/core/src/test/groovy/org/gradle/api/internal/project/ProjectFactoryTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/RepositoriesDeclaredInSettingsIntegrationTest.groovy
Labels: in:repository-declarations

#25675 Cherry pick: Associate each component in the dependency graph with the correct repository in build operation results
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ResolveConfigurationDependenciesBuildOperationIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/ResolveConfigurationResolutionBuildOperationDetails.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/DynamicVersionResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/ModuleComponentGraphSpecificResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/RepositoryChainComponentMetaDataResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/projectmodule/ProjectDependencyResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ComponentState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ModuleResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/NodeState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/selectors/ComponentStateFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/selectors/SelectorStateResolverResults.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/ComponentGraphResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/ComponentGraphSpecificResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/result/BuildableComponentIdResolveResult.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/result/BuildableComponentResolveResult.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/result/ComponentIdResolveResult.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/result/ComponentResolveResult.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/result/DefaultBuildableComponentIdResolveResult.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/result/DefaultBuildableComponentResolveResult.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/RepositoryChainComponentMetaDataResolverTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/projectmodule/ProjectDependencyResolverTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/DependencyGraphBuilderTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/selectors/SelectorStateResolverTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/query/DefaultArtifactResolutionQueryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/resolve/result/DefaultBuildableComponentIdResolveResultTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/resolve/result/DefaultBuildableComponentResolveResultTest.groovy
  subprojects/version-control/src/main/java/org/gradle/vcs/internal/resolver/VcsDependencyResolver.java
Labels: in:dependency-resolution

#25677 Update percentage display in comment
  .cm/percentage_new.cm
Labels: cm-changes

#25567 Disable GE plugin until 3.15 if Isolated Projects is enabled
  subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/GradleEnterprisePluginCheckInIntegrationTest.groovy
  subprojects/enterprise/src/main/java/org/gradle/internal/enterprise/impl/DefaultGradleEnterprisePluginCheckInService.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/BuildScanPluginSmokeTest.groovy
Labels: in:build-scan

#25598 Full nagging for deprecation of GUtil
  subprojects/core/src/main/java/org/gradle/util/NameMatcher.java
  subprojects/logging/src/main/java/org/gradle/util/GUtil.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractAndroidSantaTrackerSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractKotlinPluginAndroidSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/SmokeTestGradleRunner.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/ThirdPartyGradleModuleMetadataSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/WithAndroidDeprecations.groovy
Labels: a:chore

#24593 Make progress bar robust against excessive progress reports (#24576)
  subprojects/architecture-test/src/changes/archunit_store/internal-api-nullability.txt
  subprojects/logging/src/main/java/org/gradle/internal/logging/console/ProgressBar.java
  subprojects/logging/src/test/groovy/org/gradle/internal/logging/console/ProgressBarTest.groovy
Labels: from:contributor, :wave: team-triage

#25510 Do not use VFS to snapshot results of File.list and the likes
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/extensions/FileSystemExtensions.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintController.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/fingerprint/ConfigurationCacheFingerprintWriter.kt
Labels: @configuration-cache

#24702 Disable embedded testing jetty server stop timeout
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/HttpServerFixture.groovy
Labels: 1 min review, platform:build-infrastructure

#25662 Fix the name for Isolated Projects settings event
  subprojects/core/src/integTest/groovy/org/gradle/operations/configuration/IsolatedProjectsSettingsBuildOperationsIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/initialization/BuildOptionBuildOperationProgressEventsEmitter.java
  subprojects/enterprise-operations/src/main/java/org/gradle/operations/configuration/IsolatedProjectsSettingsFinalizedProgressDetails.java
Labels: in:build-scan

#25685 Finalize 8.2.1 release notes
  subprojects/docs/src/docs/release/notes.md
Labels: a:chore

#25692 Upgrade wrapper to 8.2.1
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore

#25690 Merge release into master to clean up conflicts
  .teamcity/src/main/kotlin/model/CIBuildModel.kt
  gradle.properties
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/options/BooleanOptionElement.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/options/OptionReaderTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TaskBooleanOptionIntegrationTest.groovy
Labels: a:chore

#25695 Update to a recent nightly wrapper
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore

#25684 Mark flaky JavaCrossCompilationIntegrationTest
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaCrossCompilationIntegrationTest.groovy
Labels: 1 min review, platform:jvm

#25632 Upgrade embedded Kotlin to 1.9.0
  build-logic-commons/gradle-plugin/build.gradle.kts
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.ci-reporting.gradle.kts
  build-logic/binary-compatibility/src/test/kotlin/gradlebuild/binarycompatibility/KotlinInternalFilteringTest.kt
  build-logic/binary-compatibility/src/test/kotlin/gradlebuild/binarycompatibility/SinceAndIncubatingRulesKotlinTest.kt
  build-logic/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
  build-logic/kotlin-dsl/src/main/kotlin/gradlebuild.kotlin-dsl-dependencies-embedded.gradle.kts
  gradle/dependency-management/kotlin-versions.properties
  gradle/verification-metadata.xml
  gradle/wrapper/gradle-wrapper.properties
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/library-versions.properties
  subprojects/configuration-cache/build.gradle.kts
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/AllDistributionIntegrationSpec.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DistributionIntegrationSpec.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DocsDistributionIntegrationSpec.groovy
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/compatibility.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_8.adoc
  subprojects/docs/src/samples/build-organization/structuring-software-projects/groovy/platforms/plugins-platform/build.gradle
  subprojects/docs/src/samples/build-organization/structuring-software-projects/kotlin/platforms/plugins-platform/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/androidBuild/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/androidSingleBuild/kotlin/build.gradle.kts
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/KotlinGradlePluginVersions.groovy
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/KotlinDslPluginCustomKotlinOptionsIntegrationTest.kt
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/PrecompiledScriptPluginIntegrationTest.kt
  subprojects/kotlin-dsl-plugins/build.gradle.kts
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginTest.kt
  subprojects/kotlin-dsl-plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/base/KotlinDslBasePlugin.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/KotlinCompiler.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/codegen/GradleApiExtensionsTest.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/support/KotlinCompilerTest.kt
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginSmokeTest.groovy
Labels: in:kotlin-dsl

#25717 Fix check if 'module-info.java' exists in 'addModuleInfoToCompile()'
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/JavaClassChangeIncrementalCompilationIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/DefaultSourceFileClassNameConverter.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/FileNameDerivingClassNameConverter.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/SourceFileClassNameConverter.java
Labels: in:java-plugins, 1 min review, platform:jvm

#25715 Upgradlew to latest non-branch release snapshot
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore

#25654 Improve error when running snippet that requires --write-locks
  subprojects/docs/src/snippets/dependencyManagement/dependencyLocking-lockingAllConfigurations/groovy/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/dependencyLocking-lockingAllConfigurations/kotlin/build.gradle.kts
Labels: 1 min review, platform:documentation

#25639 Fix and clean JacocoAggregationReportPlugin
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoReportAggregationPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmEcosystemAttributesDetails.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmPluginServices.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/JvmEcosystemAttributesDetails.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/JvmEcosystemUtilities.java
  subprojects/plugins/src/main/java/org/gradle/jvm/component/internal/DefaultJvmSoftwareComponent.java
Labels: in:testing, in:jacoco-plugin, 1 min review, platform:jvm

#25678 Recognize certain options as making workers unreliable on Windows
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/ForkCapableRelocationIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/JavaAgentFixture.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/daemon/JavaCompilerDaemonReuseIntegrationTest.groovy
  subprojects/workers/src/main/java/org/gradle/workers/internal/DaemonForkOptionsBuilder.java
  subprojects/workers/src/test/groovy/org/gradle/workers/internal/DaemonForkOptionsBuilderTest.groovy
Labels: 10 min review, platform:jvm, platform:execution, platform:build_infrastructure

#25676 Make startup failures from workers attach to the operation
  subprojects/build-operations/src/main/java/org/gradle/internal/operations/CurrentBuildOperationRef.java
  subprojects/core/src/main/java/org/gradle/process/internal/DefaultExecHandle.java
  subprojects/core/src/main/java/org/gradle/process/internal/ExecHandleRunner.java
  subprojects/core/src/main/java/org/gradle/process/internal/streams/EmptyStdInStreamsHandler.java
  subprojects/core/src/main/java/org/gradle/process/internal/streams/ExecOutputHandleRunner.java
  subprojects/core/src/main/java/org/gradle/process/internal/streams/ForwardStdinStreamsHandler.java
  subprojects/core/src/main/java/org/gradle/process/internal/streams/OutputStreamsForwarder.java
  subprojects/core/src/main/java/org/gradle/process/internal/worker/DefaultMultiRequestWorkerProcessBuilder.java
  subprojects/core/src/main/java/org/gradle/process/internal/worker/DefaultWorkerProcess.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/bootstrap/DaemonOutputConsumer.java
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/daemon/JavaCompilerDaemonFailureIntegrationTest.groovy
  subprojects/process-services/src/main/java/org/gradle/process/internal/ExecHandle.java
  subprojects/process-services/src/main/java/org/gradle/process/internal/StreamsHandler.java
  subprojects/soak/src/integTest/groovy/org/gradle/jvm/JavaCompilationSoakTest.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerDaemonFailureLoggingIntegrationTest.groovy
  subprojects/workers/src/main/java/org/gradle/workers/internal/WorkerDaemonFactory.java
Labels: a:bug, a:feature, in:workers, 20 min review, platform:jvm, platform:core, platform:execution, platform:bt_ge_build_cache, platform:release_coordination

#25710 Fix issues in lexing
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/execution/Combinators.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/execution/KotlinGrammar.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/execution/Lexer.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/execution/KotlinGrammarTest.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/execution/LexerTest.kt
Labels: in:kotlin-dsl

#25711 Adds column to location descriptor
  subprojects/build-events/src/main/java/org/gradle/internal/build/event/types/DefaultProblemEvent.java
  subprojects/problems/src/main/java/org/gradle/api/problems/interfaces/ProblemLocation.java
  subprojects/problems/src/main/java/org/gradle/api/problems/internal/DefaultProblemBuilder.java
  subprojects/problems/src/main/java/org/gradle/api/problems/internal/DefaultProblemLocation.java
  subprojects/problems/src/test/groovy/org/gradle/api/problems/internal/DefaultProblemBuilderTest.groovy
  subprojects/tooling-api-builders/src/main/java/org/gradle/tooling/internal/provider/runner/ProblemsProgressEventConsumer.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/events/problems/ProblemDescriptor.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/events/problems/internal/DefaultProblemsOperationDescriptor.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/parameters/BuildProgressListenerAdapter.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/protocol/InternalProblemEvent.java
Labels: @ide-experience, 10 min review, platform:core, platform:ide

#25688 Erase annotations on top-level script blocks - final touches
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/execution/Combinators.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/execution/KotlinGrammar.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/execution/ProgramParserAnnotationErasureTest.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/execution/ProgramParserTest.kt
Labels: in:kotlin-dsl

#25722 Update Gradle Documentation for getResolutionResult method
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/ResolvableDependencies.java
Labels: from:contributor

#25648 Skip too new versioned directories of multi-release JARs when instrumenting
  subprojects/architecture-test/src/changes/archunit_store/internal-api-nullability.txt
  subprojects/base-services/src/main/java/org/gradle/internal/classanalysis/AsmConstants.java
  subprojects/base-services/src/main/java/org/gradle/internal/classloader/TransformReplacer.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingClasspathFileTransformer.java
  subprojects/core/src/test/groovy/org/gradle/internal/classpath/DefaultCachedClasspathTransformerTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/classpath/InstrumentingClasspathFileTransformerTest.groovy
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/internal-testing/build.gradle.kts
  subprojects/internal-testing/src/main/groovy/org/gradle/test/fixtures/archive/JarTestFixture.groovy
Labels: @configuration-cache

#25748 Remove Justin from triggering gitStream, per request
  .cm/code_experts.cm
  .cm/includes_todos.cm
  .cm/percentage_new.cm
Labels: cm-changes

#25749 Minor: add an anchor for linking in the configuration cache docs
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
Labels: a:documentation

#25672 Documentation updates following Project.buildDir deprecation
  subprojects/docs/src/docs/dsl/dsl.xml
  subprojects/docs/src/docs/dsl/org.gradle.api.Project.xml
  subprojects/docs/src/docs/dsl/org.gradle.api.file.ProjectLayout.xml
  subprojects/docs/src/docs/userguide/api/groovy_build_script_primer.adoc
  subprojects/docs/src/docs/userguide/authoring-builds/working_with_files.adoc
  subprojects/docs/src/docs/userguide/core-plugins/base_plugin.adoc
  subprojects/docs/src/docs/userguide/core-plugins/distribution_plugin.adoc
  subprojects/docs/src/docs/userguide/core-plugins/jacoco_plugin.adoc
  subprojects/docs/src/docs/userguide/jvm/building_java_projects.adoc
  subprojects/docs/src/docs/userguide/jvm/java_plugin.adoc
  subprojects/docs/src/docs/userguide/jvm/java_testing.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_8.adoc
  subprojects/docs/src/docs/userguide/native/building_cpp_projects.adoc
  subprojects/docs/src/docs/userguide/native/building_swift_projects.adoc
  subprojects/docs/src/docs/userguide/native/cpp_application_plugin.adoc
  subprojects/docs/src/docs/userguide/native/cpp_library_plugin.adoc
  subprojects/docs/src/docs/userguide/native/cpp_unit_test_plugin.adoc
  subprojects/docs/src/docs/userguide/native/swift_application_plugin.adoc
  subprojects/docs/src/docs/userguide/native/swift_library_plugin.adoc
  subprojects/docs/src/docs/userguide/native/xctest_plugin.adoc
  subprojects/docs/src/docs/userguide/reference/command_line_interface.adoc
  subprojects/docs/src/snippets/antMigration/importBuild/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/buildCache/cacheable-bundle/groovy/build.gradle
  subprojects/docs/src/snippets/buildCache/cacheable-bundle/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/files/copy/groovy/build.gradle
  subprojects/docs/src/snippets/files/copy/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/tasks/incrementalTask/groovy/build.gradle
  subprojects/docs/src/snippets/tasks/incrementalTask/kotlin/build.gradle.kts
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/files/SamplesCopyIntegrationTest.groovy
Labels: a:documentation

#25763 Add minimum version to finalizer test
  subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/android/RealLifeAndroidBuildPerformanceTest.groovy
Labels: in:performance-test, 1 min review, platform:release_coordination

#25764 Polish `JUnitPlatformTestClassProcessor`
  subprojects/testing-junit-platform/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestClassProcessor.java
Labels: in:testing

#25775 Alternate proposal for updating the Java compat table
  subprojects/docs/src/docs/userguide/compatibility.adoc
Labels: a:documentation

#25767 Fix typo in version of toolchain installations
  subprojects/docs/src/docs/userguide/jvm/toolchains.adoc
Labels: from:contributor

#25744 Allow java-test-fixtures to be applied standalone
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/TestFixturesSupport.java
  subprojects/plugins/src/integTest/groovy/org/gradle/java/fixtures/StandaloneTestFixturesIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaTestFixturesPlugin.java
Labels: 10 min review, platform:jvm, platform:software

#25694 Add more tests for transform executions build operations
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformExecutionBuildOperationIntegrationTest.groovy
Labels: 20 min review, platform:software

#25779 Add cheatsheet of PR emojis
  .github/PULL_REQUEST_TEMPLATE.md
Labels: a:documentation, 1 min review, platform:build_infrastructure

#25800 Skip RemotePreconditionProbingTest on non-remote executor
  subprojects/internal-testing/src/main/groovy/org/gradle/test/preconditions/UnitTestPreconditions.groovy
  subprojects/internal-testing/src/main/resources/valid-precondition-combinations.csv
  subprojects/precondition-tester/src/test/groovy/org/gradle/test/precondition/RemotePreconditionProbingTest.groovy
Labels: 1 min review, platform:build_infrastructure

#25801 Add full stop to option description
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/BuildInitPluginIntegrationTest.groovy
  subprojects/build-init/src/main/java/org/gradle/api/tasks/wrapper/Wrapper.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/tasks/InitBuild.java
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/options/TaskOptionIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/options/BooleanOptionElement.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/options/OptionReaderTest.groovy
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/tasks/diagnostics/HelpTaskIntegrationTest.groovy
  subprojects/docs/src/snippets/tasks/commandLineOption-optionValues/tests/helpTaskOptions.out
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TaskBooleanOptionIntegrationTest.groovy
Labels: a:bug, in:writing-tasks, 1 min review, platform:jvm, platform:software, platform:documentation

#25796 Revise CODEOWNERS based on last AC meeting
  .github/CODEOWNERS
Labels: 1 min review, platform:build_infrastructure

#25720 Modify dependency set in withDependencies callback instead of underly…
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testsuites/TestSuitesIntegrationTest.groovy
Labels: 1 min review, platform:jvm

#25797 Update screenshots of gradle builds on Jenkins
  subprojects/docs/src/docs/userguide/img/ci-systems/jenkins-build-scan.png
  subprojects/docs/src/docs/userguide/img/ci-systems/jenkins-build-step.png
  subprojects/docs/src/docs/userguide/img/ci-systems/jenkins-scm.png
  subprojects/docs/src/docs/userguide/reference/ci-systems/jenkins.adoc
Labels: a:documentation, from:contributor

#25817 Update wrapper following 8.3-rc-1 release
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore

#25820 Update wrapper to 8.4-20230719142735+0000
  gradle/verification-metadata.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore, @execution, 1 min review

#25825 Merge release into master
  released-versions.json
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/AllDistributionIntegrationSpec.groovy
  subprojects/docs/src/docs/release/notes.md
  subprojects/launcher/src/main/resources/release-features.txt
Labels: 1 min review, platform:core, platform:documentation

#25554 Support @Option with task properties of type ListProperty and SetProperty
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/options/AbstractOptionIntegrationSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/options/TaskOptionIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/options/FieldOptionElement.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/options/MethodOptionElement.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/options/OptionReaderTest.groovy
Labels: a:bug, in:provider-api, p:lazy-migration, 10 min review

#25811 Add smoke test for custom BuildConfig field Android recipe
  subprojects/model-core/src/integTest/groovy/org/gradle/api/provider/MapPropertyIntegrationTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidDeprecations.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidGradleRecipesKotlinSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/WithKotlinDeprecations.groovy
Labels: @configuration-cache, in:smoke-test

#25843 Update Composite Builds Declared Substitutions Sample to `using` instead of `with`
  subprojects/docs/src/samples/build-organization/composite-builds/declared-substitution/README.adoc
Labels: a:documentation, from:contributor

#24847 docs: Make the configuration avoidance API table more readable
  subprojects/docs/src/docs/userguide/extending-gradle/task_configuration_avoidance.adoc
Labels: a:documentation, from:contributor

#25778 Further consolidate Maven dependency mapping
  subprojects/architecture-test/src/changes/archunit_store/internal-api-nullability.txt
  subprojects/core/src/main/java/org/gradle/api/internal/component/SoftwareComponentInternal.java
  subprojects/docs/src/docs/userguide/migration/upgrading_version_8.adoc
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/AbstractMavenPublishJavaIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishJavaIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishMultiProjectIntegTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishPomCustomizationIntegTest.groovy
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/dependencies/DefaultMavenDependency.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/dependencies/DefaultMavenPomDependencies.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/dependencies/DefaultMavenProjectDependency.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/dependencies/MavenDependency.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/dependencies/MavenPomDependencies.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/DefaultMavenPom.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/DefaultMavenPomDependencies.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/DefaultMavenPublication.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/MavenComponentParser.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/MavenPomDependencies.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/MavenPomInternal.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/MavenPublicationInternal.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/tasks/MavenPomFileGenerator.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/plugins/MavenPublishPlugin.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/tasks/GenerateMavenPom.java
  subprojects/maven/src/test/groovy/org/gradle/api/publish/maven/internal/publication/DefaultMavenPublicationTest.groovy
  subprojects/maven/src/test/groovy/org/gradle/api/publish/maven/internal/publisher/ValidatingMavenPublisherTest.groovy
  subprojects/maven/src/test/groovy/org/gradle/api/publish/maven/internal/tasks/MavenPomFileGeneratorTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlatformPlugin.java
  subprojects/plugins/src/main/java/org/gradle/jvm/component/internal/DefaultJvmSoftwareComponent.java
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/component/MavenPublishingAwareVariant.java
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/metadata/InvalidPublicationChecker.java
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/metadata/ModuleMetadataSpecBuilder.java
Labels: 30 min review, platform:jvm, platform:software, platform:documentation

#25740 Re-enable load-after-store for tests in testing-jvm
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/ListenerBroadcastCodec.kt
  subprojects/messaging/src/main/java/org/gradle/internal/event/BroadcastDispatch.java
  subprojects/messaging/src/main/java/org/gradle/internal/event/ListenerBroadcast.java
  subprojects/testing-base/src/testFixtures/groovy/org/gradle/testing/AbstractTestFrameworkIntegrationTest.groovy
  subprojects/testing-jvm/build.gradle.kts
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/AbstractTestTaskIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/ParallelTestExecutionIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/AbstractTestNGFilteringIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/SampleTestNGIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGFilteringIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGUpToDateCheckIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testsuites/dependencies/TestSuitesGroovyDSLDependenciesIntegrationTest.groovy
Labels: in:testing, in:configuration-cache, @configuration-cache

#25848 Avoid resolving `MapProperty` provider too early
  subprojects/model-core/src/integTest/groovy/org/gradle/api/provider/MapPropertyIntegrationTest.groovy
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/DefaultMapProperty.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidGradleRecipesKotlinSmokeTest.groovy
Labels: in:configuration-model

#25845 Changed qualifier version in the docs
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/dependency_resolution.adoc
Labels: from:contributor

#25854 Fix Property Upgrade codegen default values
  subprojects/internal-instrumentation-processor/src/main/java/org/gradle/internal/instrumentation/extensions/property/PropertyUpgradeClassSourceGenerator.java
  subprojects/internal-instrumentation-processor/src/main/java/org/gradle/internal/instrumentation/processor/codegen/TypeUtils.java
  subprojects/internal-instrumentation-processor/src/test/groovy/org/gradle/internal/instrumentation/extensions/property/PropertyUpgradeCodeGenTest.groovy
Labels: @execution, p:lazy-migration, 1 min review, platform:configuration_cache

#25876 Remove execution team from trial per request
  .cm/change_categories.cm
  .cm/code_experts.cm
  .cm/complex_changes.cm
  .cm/estimated_time_to_review.cm
  .cm/includes_todos.cm
  .cm/lacks_tests.cm
  .cm/percentage_new.cm
Labels: cm-changes

#25883 Cherry-pick "Skip RemotePreconditionProbingTest on non-remote executor" to release
  subprojects/internal-testing/src/main/groovy/org/gradle/test/preconditions/UnitTestPreconditions.groovy
  subprojects/internal-testing/src/main/resources/valid-precondition-combinations.csv
  subprojects/precondition-tester/src/test/groovy/org/gradle/test/precondition/RemotePreconditionProbingTest.groovy
Labels: 1 min review, platform:build_infrastructure

#25879 Update Gradle Enterprise Gradle plugin to v3.14
  build-logic-commons/gradle-plugin/build.gradle.kts
  build-logic/build-platform/build.gradle.kts
  settings.gradle.kts
  subprojects/core/src/main/java/org/gradle/plugin/management/internal/autoapply/AutoAppliedGradleEnterprisePlugin.java
  subprojects/docs/src/docs/userguide/reference/ci-systems/github-actions.adoc
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/BuildScanPluginSmokeTest.groovy
Labels: 1 min review, build-script-change, platform:documentation, platform:release_coordination

#25777 Verify support for running on Java 20
  .teamcity/src/main/kotlin/common/JvmCategory.kt
  .teamcity/src/main/kotlin/common/JvmVendor.kt
  .teamcity/src/main/kotlin/common/JvmVersion.kt
  .teamcity/src/test/kotlin/ApplyDefaultConfigurationTest.kt
  .teamcity/src/test/kotlin/PerformanceTestBuildTypeTest.kt
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/MavenConversionDynamicPomIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/MavenConversionIntegrationTest.groovy
  subprojects/build-init/src/integTest/resources/org/gradle/buildinit/plugins/MavenConversionIntegrationTest/emptySource/some-thing/pom.xml
  subprojects/build-init/src/integTest/resources/org/gradle/buildinit/plugins/MavenConversionIntegrationTest/emptyTarget/some-thing/pom.xml
  subprojects/build-init/src/integTest/resources/org/gradle/buildinit/plugins/MavenConversionIntegrationTest/enforcerplugin/some-thing/pom.xml
  subprojects/build-init/src/integTest/resources/org/gradle/buildinit/plugins/MavenConversionIntegrationTest/expandProperties/some-thing/pom.xml
  subprojects/build-init/src/integTest/resources/org/gradle/buildinit/plugins/MavenConversionIntegrationTest/flatmultimodule/some-thing/webinar-parent/pom.xml
  subprojects/build-init/src/integTest/resources/org/gradle/buildinit/plugins/MavenConversionIntegrationTest/insecureProtocolAllow/some-thing/pom.xml
  subprojects/build-init/src/integTest/resources/org/gradle/buildinit/plugins/MavenConversionIntegrationTest/insecureProtocolDefaultHandling/some-thing/pom.xml
  subprojects/build-init/src/integTest/resources/org/gradle/buildinit/plugins/MavenConversionIntegrationTest/insecureProtocolFail/some-thing/pom.xml
  subprojects/build-init/src/integTest/resources/org/gradle/buildinit/plugins/MavenConversionIntegrationTest/insecureProtocolUpgrade/some-thing/pom.xml
  subprojects/build-init/src/integTest/resources/org/gradle/buildinit/plugins/MavenConversionIntegrationTest/insecureProtocolWarn/some-thing/pom.xml
  subprojects/build-init/src/integTest/resources/org/gradle/buildinit/plugins/MavenConversionIntegrationTest/multiModule/some-thing/pom.xml
  subprojects/build-init/src/integTest/resources/org/gradle/buildinit/plugins/MavenConversionIntegrationTest/multiModuleNoBackReferences/some-thing/pom.xml
  subprojects/build-init/src/integTest/resources/org/gradle/buildinit/plugins/MavenConversionIntegrationTest/multiModuleWithNestedParent/some-thing/pom.xml
  subprojects/build-init/src/integTest/resources/org/gradle/buildinit/plugins/MavenConversionIntegrationTest/multiModuleWithRemoteParent/some-thing/pom.xml
  subprojects/build-init/src/integTest/resources/org/gradle/buildinit/plugins/MavenConversionIntegrationTest/remoteparent/some-thing/pom.xml
  subprojects/build-init/src/integTest/resources/org/gradle/buildinit/plugins/MavenConversionIntegrationTest/singleModule/some-thing/pom.xml
  subprojects/build-init/src/integTest/resources/org/gradle/buildinit/plugins/MavenConversionIntegrationTest/testsJar/some-thing/pom.xml
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/library-versions.properties
  subprojects/core/src/integTest/groovy/org/gradle/JansiEndUserIntegrationTest.groovy
  subprojects/internal-instrumentation-processor/src/test/groovy/org/gradle/internal/instrumentation/InstrumentationCodeGenTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/DefaultGradleDistribution.groovy
  subprojects/internal-testing/src/main/resources/valid-precondition-combinations.csv
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/BaseIncrementalCompilationAfterFailureIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/AbstractIncrementalCompileIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/BasicJavaCompilerIntegrationSpec.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/integtests/ScalaAnnotationProcessingIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/integtests/fixtures/ScalaCoverage.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/AbstractToolchainZincScalaCompileIntegrationTest.groovy
  subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/enduser/GradleRunnerMiscEndUserIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestTaskJdkRelocationIntegrationTest.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r25/TestProgressCrossVersionSpec.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerDaemonIntegrationTest.groovy
  subprojects/workers/src/testFixtures/groovy/org/gradle/workers/fixtures/WorkerExecutorFixture.groovy
Labels: 30 min review, platform:jvm, platform:software, platform:extensibility, platform:ide, platform:execution, platform:build_infrastructure, platform:configuration_cache

#25862 Don't keep compiler daemons alive on Windows
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/DaemonJavaCompiler.java
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/daemon/JavaCompilerDaemonReuseIntegrationTest.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerDaemonLifecycleTest.groovy
Labels: a:bug, in:workers, 1 min review, platform:jvm, platform:execution

#25529 Platformize JavaPlatform and JvmEcosystem plugins
  .teamcity/subprojects.json
  build-logic-commons/code-quality-rules/src/main/resources/checkstyle/suppressions.xml
  platforms/jvm/java-platform/build.gradle.kts
  platforms/jvm/java-platform/src/integTest/groovy/org/gradle/integtests/resolve/platforms/JavaPlatformEcosystemIntegrationTest.groovy
  platforms/jvm/java-platform/src/integTest/groovy/org/gradle/integtests/resolve/platforms/JavaPlatformResolveIntegrationTest.groovy
  platforms/jvm/java-platform/src/integTest/groovy/org/gradle/integtests/resolve/platforms/NativeAlignmentWithJavaPlatformResolveIntegrationTest.groovy
  platforms/jvm/java-platform/src/main/java/org/gradle/api/internal/java/DefaultJavaPlatformExtension.java
  platforms/jvm/java-platform/src/main/java/org/gradle/api/plugins/JavaPlatformExtension.java
  platforms/jvm/java-platform/src/main/java/org/gradle/api/plugins/JavaPlatformPlugin.java
  platforms/jvm/java-platform/src/main/resources/META-INF/gradle-plugins/org.gradle.java-platform.properties
  platforms/jvm/java-platform/src/test/java/org/gradle/api/plugins/JavaPlatformPluginTest.groovy
  settings.gradle.kts
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/BuildInitPlugin.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/BuildConverter.java
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/maven/PomProjectInitDescriptor.java
  subprojects/composite-builds/build.gradle.kts
  subprojects/core-api/src/main/java/org/gradle/api/plugins/jvm/PlatformDependencyModifiers.java
  subprojects/core-api/src/main/java/org/gradle/api/plugins/jvm/package-info.java
  subprojects/core/src/main/java/org/gradle/api/internal/initialization/DefaultScriptClassPathResolver.java
  subprojects/dependency-management/build.gradle.kts
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/platforms/PlatformResolveIntegrationTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/plugins/jvm/internal/PlatformDependencyModifiersTest.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DistributionIntegrationSpec.groovy
  subprojects/distributions-jvm/build.gradle.kts
  subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/EclipsePlugin.java
  subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoReportAggregationPlugin.java
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/compile/JavaModuleCrossCompileIntegrationTest.groovy
  subprojects/platform-jvm/src/main/java/org/gradle/api/plugins/JvmEcosystemPlugin.java
  subprojects/platform-jvm/src/main/java/org/gradle/api/plugins/internal/JavaConfigurationVariantMapping.java
  subprojects/platform-jvm/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmEcosystemAttributesDetails.java
  subprojects/platform-jvm/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmPluginServices.java
  subprojects/platform-jvm/src/main/java/org/gradle/api/plugins/jvm/internal/JvmEcosystemAttributesDetails.java
  subprojects/platform-jvm/src/main/java/org/gradle/api/plugins/jvm/internal/JvmEcosystemUtilities.java
  subprojects/platform-jvm/src/main/java/org/gradle/api/plugins/jvm/internal/JvmPluginServices.java
  subprojects/platform-jvm/src/main/resources/META-INF/gradle-plugins/org.gradle.jvm-ecosystem.properties
  subprojects/platform-jvm/src/test/groovy/org/gradle/api/plugins/JvmEcosystemPluginTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/jvm/GeneratedSourcesDirectorySetContributorIntegrationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/GroovyBasePlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaBasePlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/TestReportAggregationPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/PluginAuthorServices.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmFeature.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmLanguageGeneratedSourceDirectoryBuilder.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmLanguageSourceDirectoryBuilder.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmLanguageUtilities.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/JvmLanguageGeneratedSourceDirectoryBuilder.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/JvmLanguageSourceDirectoryBuilder.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/JvmLanguageUtilities.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/package-info.java
  subprojects/plugins/src/main/java/org/gradle/api/tasks/GroovyRuntime.java
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/jvm/internal/AbstractJvmPluginServicesTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/jvm/internal/DefaultJvmPluginServicesTest.groovy
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/jvm/internal/SourceDirectorySetJvmPluginServicesTest.groovy
  subprojects/scala/src/main/java/org/gradle/api/plugins/scala/ScalaBasePlugin.java
  subprojects/scala/src/main/java/org/gradle/api/tasks/ScalaRuntime.java
Labels: build-script-change, 30 min review, platform:jvm, platform:software, platform:ide, a:platformization, platform:build_infrastructure

#25902 Add ProviderFactory to Groovy DSL reference
  subprojects/docs/src/docs/dsl/dsl.xml
  subprojects/docs/src/docs/dsl/org.gradle.api.provider.ProviderFactory.xml
  subprojects/docs/src/docs/userguide/authoring-builds/authoring_maintainable_build_scripts.adoc
  subprojects/docs/src/docs/userguide/extending-gradle/custom_gradle_types.adoc
  subprojects/docs/src/docs/userguide/extending-gradle/lazy_configuration.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
Labels: a:documentation

#25903 Polish release notes for 8.2 RC2
  subprojects/docs/src/docs/release/notes.md
Labels: a:chore

#25901 Document and test building for older Kotlin language versions
  subprojects/docs/src/docs/userguide/migration/upgrading_version_8.adoc
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/KotlinGradlePluginVersions.groovy
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginCrossVersionSmokeTest.kt
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginGradlePluginCrossVersionSmokeTest.kt
Labels: in:kotlin-dsl

#25909 Fix failing docs tests on Java 20
  subprojects/docs/src/docsTest/java/org/gradle/docs/samples/BaseSamplesTest.java
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/groovy/buildSrc/build.gradle
  subprojects/docs/src/samples/build-organization/multi-project-with-convention-plugins/kotlin/buildSrc/build.gradle.kts
  subprojects/docs/src/samples/build-organization/publishing-convention-plugins/groovy/convention-plugins/build.gradle
  subprojects/docs/src/samples/build-organization/publishing-convention-plugins/kotlin/convention-plugins/build.gradle.kts
  subprojects/docs/src/samples/groovy/library-publishing/groovy/my-library/build.gradle
  subprojects/docs/src/samples/groovy/library-publishing/kotlin/my-library/build.gradle.kts
  subprojects/docs/src/samples/incubating/build-organization/publishing-convention-plugins/groovy/convention-plugins/build.gradle
  subprojects/docs/src/samples/incubating/build-organization/publishing-convention-plugins/kotlin/convention-plugins/build.gradle.kts
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/logging/SpringBootWebAppTestOutputNormalizer.groovy
Labels: 5 min review, platform:documentation, platform:build_infrastructure

#25858 Fix incoming dir path for GE plugin performance testing
  platforms/enterprise/enterprise-plugin-performance/build.gradle.kts
  platforms/enterprise/enterprise-plugin-performance/src/testFixtures/groovy/org/gradle/performance/AbstractBuildScanPluginPerformanceTest.groovy
Labels: in:build-scan, 1 min review, build-script-change, platform:gradle_enterprise

#25911 Merge `release` into `master`
  released-versions.json
  subprojects/core/src/main/java/org/gradle/internal/problems/DefaultProblemDiagnosticsFactory.java
  subprojects/docs/src/docs/dsl/dsl.xml
  subprojects/docs/src/docs/dsl/org.gradle.api.provider.ProviderFactory.xml
  subprojects/docs/src/docs/userguide/authoring-builds/authoring_maintainable_build_scripts.adoc
  subprojects/docs/src/docs/userguide/extending-gradle/custom_gradle_types.adoc
  subprojects/docs/src/docs/userguide/extending-gradle/lazy_configuration.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_8.adoc
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/KotlinGradlePluginVersions.groovy
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginCrossVersionSmokeTest.kt
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginGradlePluginCrossVersionSmokeTest.kt
  subprojects/logging/src/integTest/groovy/org/gradle/DeprecatedUsageBuildOperationProgressIntegrationTest.groovy
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/LoggingDeprecatedFeatureHandler.java
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/NoOpProblemDiagnosticsFactory.java
  subprojects/logging/src/test/groovy/org/gradle/internal/deprecation/LoggingDeprecatedFeatureHandlerTest.groovy
  subprojects/problems/src/main/java/org/gradle/problems/buildtree/ProblemDiagnosticsFactory.java
  subprojects/smoke-test/build.gradle.kts
Labels: a:chore

#25897 Improve how imports are added to plugin definitions for PropertyUpgradesBinaryCompatibilityCrossVersionSpec
  subprojects/integ-test/build.gradle.kts
  subprojects/integ-test/src/crossVersionTest/groovy/org/gradle/integtests/AbstractPropertyUpgradesBinaryCompatibilityCrossVersionSpec.groovy
  subprojects/integ-test/src/crossVersionTest/groovy/org/gradle/integtests/PropertyUpgradesBinaryCompatibilityCrossVersionSpec.groovy
Labels: @execution, p:lazy-migration

#25915 Reset release notes and features
  subprojects/docs/src/docs/release/notes.md
  subprojects/launcher/src/main/resources/release-features.txt
Labels: a:chore

#25922 Update wrapper following 8.3-rc2 release
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore

#25815 Obtain types for JDK classes when generating accessors
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/ProjectSchemaAccessorsIntegrationTest.kt
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/ProjectSchemaLambdaAccessorsIntegrationTest.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/codegen/ApiTypeProvider.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/ClassBytesRepository.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/codegen/GradleApiExtensionsTest.kt
Labels: in:kotlin-dsl

#25930 Change flaky deprecation warnings to "maybe"
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/BaseDeprecations.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/WithAndroidDeprecations.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/WithReportDeprecations.groovy
Labels: 1 min review, platform:release_coordination

#25931 Update Ant to match bundled version
  build-logic/build-platform/build.gradle.kts
Labels: a:chore

#25933 Print Android Studio logs for Performance tests on sync failure
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/CrossVersionPerformanceTestRunner.groovy
Labels: @execution, in:performance-test

#25936 Fix regression in copy spec fileMode/dirMode mutation
  subprojects/architecture-test/src/changes/archunit_store/internal-api-symmetrical-accessors-nullability.txt
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskChildSpecIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/CopySpecResolver.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/SingleParentCopySpec.java
Labels: in:file-tasks

#25831 Deprecate KotlinDslAssignment.isAssignmentOverloadEnabled()
  subprojects/kotlin-dsl-plugins/src/integTest/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginCrossVersionSmokeTest.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/assignment/internal/KotlinDslAssignment.kt
Labels: in:kotlin-dsl, @execution, p:lazy-migration

#25939 Make TestNG filtering compatible with CC
  subprojects/testing-jvm/build.gradle.kts
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/AbstractTestNGFilteringIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/SampleTestNGIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGFilteringIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGUpToDateCheckIntegrationTest.groovy
  subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/testng/TestNGOptions.java
Labels: in:testing, @configuration-cache

#25950 Rebaseline performance tests
  gradle.properties
Labels: a:chore, in:performance-test, 1 min review

#25925 Ignore failures while shutting down daemon connection
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/client/DaemonClient.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/DefaultIncomingConnectionHandler.java
Labels: in:daemon, 1 min review, platform:core

#25956 Rebaseline performance test
  gradle.properties
Labels: 1 min review

#25871 Use host platform for windows sdk resource compiler
  subprojects/architecture-test/src/changes/archunit_store/internal-api-nullability.txt
  subprojects/language-native/src/integTest/groovy/org/gradle/language/rc/WindowsResourcesIntegrationTest.groovy
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/internal/services/NativeBinaryServices.java
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/msvcpp/DefaultWindowsSdkLocator.java
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/msvcpp/WindowsKitSdkInstall.java
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/msvcpp/WindowsKitWindowsSdkLocator.java
  subprojects/platform-native/src/test/groovy/org/gradle/nativeplatform/toolchain/internal/msvcpp/WindowsKitWindowsSdkLocatorTest.groovy
Labels: from:contributor

#25955 Fixing JUnitJupiterCategoriesOrTagsCoverageIntegrationTest
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junit/jupiter/JUnitJupiterCategoriesOrTagsCoverageIntegrationTest.groovy
Labels: from:contributor

#25771 Use providers properly in "Caching Java projects" snippets
  subprojects/docs/src/docs/userguide/build-cache/caching_java_projects.adoc
  subprojects/docs/src/snippets/buildCache/integration-tests/groovy/build.gradle
  subprojects/docs/src/snippets/buildCache/integration-tests/kotlin/build.gradle.kts
Labels: a:documentation
