Repository gradle/gradle, pull requests merged in 2023-02, with the labels that each got.

#23717 Run nightly promotion build once per week for old release branches
  .teamcity/src/main/kotlin/common/VersionedSettingsBranch.kt
  .teamcity/src/main/kotlin/configurations/StagePasses.kt
  .teamcity/src/main/kotlin/model/FunctionalTestBucketGenerator.kt
  .teamcity/src/main/kotlin/promotion/PublishNightlySnapshot.kt
  .teamcity/src/main/kotlin/promotion/SanityCheck.kt
  .teamcity/src/main/kotlin/promotion/StartReleaseCycleTest.kt
  .teamcity/src/test/kotlin/ApplyDefaultConfigurationTest.kt
  .teamcity/src/test/kotlin/PerformanceTestBuildTypeTest.kt
  .teamcity/src/test/kotlin/PromotionProjectTests.kt
  .teamcity/src/test/kotlin/VersionedSettingsBranchTest.kt
Labels: @dev-productivity

#23649 Add test cases for Property assignment for Groovy and Kotlin
  subprojects/model-core/src/integTest/groovy/org/gradle/api/provider/PropertyAssignmentIntegrationTest.groovy
Labels: @execution

#23718 Fix failing santaTracker performance tests on m1 mac
  .teamcity/src/main/kotlin/common/Os.kt
  .teamcity/src/test/kotlin/PerformanceTestBuildTypeTest.kt
  build-logic/performance-testing/src/main/groovy/gradlebuild.performance-templates.gradle
Labels: @dev-productivity

#23667 Trusted GPG-key should only accept 160-bit fingerprints
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationSignatureCheckIntegTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/DefaultLenientConfiguration.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/StartParameterResolutionOverride.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/ChecksumAndSignatureVerificationOverride.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/writer/WriteDependencyVerificationFile.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/exceptions/ComponentVerificationException.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/exceptions/DependencyVerificationException.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/exceptions/InvalidGpgKeyIdsException.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/serializer/DependencyVerificationsXmlReader.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/verifier/DependencyVerificationConfiguration.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/verifier/DependencyVerifierBuilder.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/writer/PgpKeyGrouperTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/verification/serializer/DependencyVerificationsXmlReaderTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/verification/serializer/DependencyVerificationsXmlWriterTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/verification/verifier/DependencyVerifierBuilderTest.groovy
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/dependency_verification.adoc
Labels: in:dependency-verification

#23738 Upgrade tested AGP 7.4.0 to 7.4.1
  gradle/dependency-management/agp-versions.properties
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/WithReportDeprecations.groovy
Labels: a:chore

#23739 Clarify kotlin dsl plugins block interpreter unsupported syntax
  subprojects/docs/src/docs/release/notes.md
Labels: in:kotlin-dsl

#23726 Use JDK 19
  .teamcity/src/main/kotlin/common/JvmCategory.kt
  .teamcity/src/main/kotlin/common/JvmVersion.kt
  .teamcity/src/test/kotlin/ApplyDefaultConfigurationTest.kt
  .teamcity/src/test/kotlin/PerformanceTestBuildTypeTest.kt
Labels: @dev-productivity

#23749 Upgrade embedded Kotlin to 1.8.10
  build-logic/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/library-versions.properties
  subprojects/docs/src/docs/userguide/compatibility.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/samples/build-organization/structuring-software-projects/groovy/platforms/plugins-platform/build.gradle
  subprojects/docs/src/samples/build-organization/structuring-software-projects/kotlin/platforms/plugins-platform/build.gradle.kts
  subprojects/docs/src/snippets/configurationCache/samConversion/groovy/build.gradle
  subprojects/docs/src/snippets/configurationCache/samConversion/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/androidBuild/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/androidSingleBuild/kotlin/build.gradle.kts
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/NestedInputKotlinImplementationTrackingIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/KotlinGradlePluginVersions.groovy
  subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoKotlinJvmPluginAggregationTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
Labels: in:kotlin-dsl

#23671 Prepare 6.9.4
  .teamcity/src/main/kotlin/common/extensions.kt
  buildSrc/subprojects/basics/src/main/kotlin/gradlebuild.repositories.gradle.kts
  gradle/verification-metadata.xml
  gradle/wrapper/gradle-wrapper.properties
  released-versions.json
  subprojects/docs/build.gradle
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/snippets/dependencyManagement/declaringRepositories-multipleRepositories/groovy/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/declaringRepositories-multipleRepositories/kotlin/build.gradle.kts
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/GradleKotlinDslIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/RepoScriptBlockUtil.groovy
  subprojects/kotlin-dsl-tooling-builders/src/crossVersionTest/groovy/org/gradle/kotlin/dsl/tooling/builders/r54/KotlinBuildScriptModelCrossVersionSpec.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractCrossTaskIncrementalCompilationIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/JavaSourceIncrementalCompilationIntegrationTest.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/language/cpp/CppToolChainChangesIntegrationTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/integtests/publish/maven/MavenWagonPublishIntegrationTest.groovy
  subprojects/platform-native/src/testFixtures/groovy/org/gradle/nativeplatform/fixtures/NativeToolChainTestRunner.java
  subprojects/samples/src/integTest/groovy/org/gradle/integtests/samples/dependencymanagement/SamplesDeclaringRepositoriesIntegrationTest.groovy
  version.txt
Labels: a:chore

#23756 Bump :kotlin-dsl-plugins version for Kotlin 1.8.10
  build-logic/kotlin-dsl/src/main/kotlin/gradlebuild.kotlin-dsl-dependencies-embedded.gradle.kts
  gradle/verification-metadata.xml
  subprojects/kotlin-dsl-plugins/build.gradle.kts
Labels: in:kotlin-dsl

#23763 Upgrade release wrapper with Kotlin 1.8.10
  build-logic-commons/gradle-plugin/build.gradle.kts
  gradle/verification-metadata.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: in:kotlin-dsl

#23746 Build when TestDistributionExtension is not present
  build-logic/buildquality/src/main/kotlin/gradlebuild.arch-test.gradle.kts
  build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts
Labels: @dev-productivity

#23064 Annotations 24.0.0
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
  subprojects/distributions-dependencies/build.gradle.kts
Labels: from:contributor, pending:pr-dco

#23366 Fix dependency reporting tasks for CC
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/AbstractConfigurationCacheIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheProjectReportIntegTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/result/DefaultResolutionResult.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/result/DefaultResolvedComponentResult.java
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/plugins/ProjectReportsPluginIntegrationSpec.groovy
  subprojects/diagnostics/src/integTest/groovy/org/gradle/api/reporting/dependencies/HtmlDependencyReportTaskIntegrationTest.groovy
  subprojects/diagnostics/src/main/java/org/gradle/api/reporting/dependencies/HtmlDependencyReportTask.java
  subprojects/diagnostics/src/main/java/org/gradle/api/reporting/dependencies/internal/HtmlDependencyReporter.java
  subprojects/diagnostics/src/main/java/org/gradle/api/reporting/dependencies/internal/JsonProjectDependencyRenderer.java
  subprojects/diagnostics/src/main/java/org/gradle/api/reporting/dependencies/internal/ProjectPageRenderer.java
  subprojects/diagnostics/src/main/java/org/gradle/api/reporting/dependencies/internal/ProjectsPageRenderer.java
  subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/ProjectReportTask.java
  subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/internal/ProjectDetails.java
  subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/internal/ProjectsWithConfigurations.java
Labels: in:configuration-cache, @configuration-cache

#23770 Fix the references dispay text
  subprojects/docs/src/docs/userguide/migration/migrating_from_groovy_to_kotlin_dsl.adoc
Labels: from:contributor

#23764 Merge `release` into `master`
  build-logic/kotlin-dsl/src/main/kotlin/gradlebuild.kotlin-dsl-dependencies-embedded.gradle.kts
  gradle/verification-metadata.xml
  released-versions.json
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/kotlin-dsl-plugins/build.gradle.kts
Labels: a:chore

#21702 Polish DefaultAttributesSchema and ComponentAttributeMatcher
  subprojects/core/src/test/groovy/org/gradle/api/internal/artifacts/TargetJvmVersionRulesTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultDependencyManagementServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/attributes/AttributesSchemaInternal.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/attributes/DefaultAttributesSchema.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/attributes/EmptySchema.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/PreferJavaRuntimeVariant.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/AttributeMatcher.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/ComponentAttributeMatcher.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/MultipleCandidateMatcher.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/dsl/dependencies/GradlePluginVariantsSupportTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/DefaultVersionedComponentChooserTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/resolver/ComponentMetadataDetailsAdapterTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/attributes/DefaultAttributeSelectionSchemaTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/attributes/DefaultAttributesSchemaTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/external/model/AbstractDependencyMetadataRulesTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/external/model/VariantFilesMetadataRulesTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/model/AttributeConfigurationSelectorTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/model/AttributePrecedenceSchemaAttributeMatcherTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/model/ComponentAttributeMatcherTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/model/JavaEcosystemAttributeMatcherTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/model/LocalComponentDependencyMetadataTest.groovy
Labels: @core

#23774 Update `master` wrapper
  build-logic-commons/gradle-plugin/build.gradle.kts
  gradle/verification-metadata.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore

#23779 Fix deprecation comments left over for 8.0
  subprojects/core-api/src/main/java/org/gradle/StartParameter.java
  subprojects/core/src/main/java/org/gradle/api/internal/AbstractTask.java
  subprojects/core/src/main/java/org/gradle/api/tasks/GradleBuild.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/CompileOptions.java
Labels: a:chore

#23769 Fix typo: "an configures" -> "and configures"
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/RepositoryHandler.java
Labels: from:contributor

#23789 Make release7x RFR green
  build-logic/performance-testing/src/main/kotlin/gradlebuild/performance/tasks/DetermineBaselines.kt
  build-logic/performance-testing/src/test/kotlin/gradlebuild/performance/tasks/DetermineBaselinesTest.kt
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/DistributionLocatorIntegrationTest.groovy
  subprojects/kotlin-dsl-tooling-builders/src/crossVersionTest/groovy/org/gradle/kotlin/dsl/tooling/builders/r54/KotlinSettingsScriptModelCrossVersionSpec.groovy
  subprojects/kotlin-dsl-tooling-builders/src/crossVersionTest/groovy/org/gradle/kotlin/dsl/tooling/builders/r75/KotlinSettingsScriptModelCrossVersionSpec.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/m9/GradlePropertiesToolingApiCrossVersionSpec.groovy
Labels: @dev-productivity

#23788 Disable more failing native tests on release6x
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/IsolatingIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/language/cpp/CppIncrementalBuildIntegrationTest.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/language/objectivec/MixedObjectiveCIntegrationTest.groovy
  subprojects/language-native/src/integTest/groovy/org/gradle/language/swift/SwiftApplicationIntegrationTest.groovy
  subprojects/platform-native/src/testFixtures/groovy/org/gradle/nativeplatform/fixtures/AvailableToolChains.java
Labels: @dev-productivity

#23647 resolve https://github.com/gradle/gradle/issues/23620
  subprojects/jvm-services/src/main/java/org/gradle/jvm/toolchain/internal/LinuxInstallationSupplier.java
Labels: from:contributor

#23798 Add contributor to release notes
  subprojects/docs/src/docs/release/notes.md
Labels: a:chore

#23775 Remove usage of `org.jetbrains.kotlin.android.extensions` plugin in snippets
  subprojects/docs/src/snippets/kotlinDsl/androidBuild/kotlin/app/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/androidBuild/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/androidSingleBuild/kotlin/build.gradle.kts
Labels: a:documentation

#23800 Merge release7x to release
  .teamcity/src/main/kotlin/common/Os.kt
  .teamcity/src/main/kotlin/common/VersionedSettingsBranch.kt
  .teamcity/src/main/kotlin/configurations/StagePasses.kt
  .teamcity/src/main/kotlin/model/FunctionalTestBucketGenerator.kt
  .teamcity/src/main/kotlin/promotion/PublishNightlySnapshot.kt
  .teamcity/src/main/kotlin/promotion/SanityCheck.kt
  .teamcity/src/main/kotlin/promotion/StartReleaseCycleTest.kt
  .teamcity/src/test/kotlin/ApplyDefaultConfigurationTest.kt
  .teamcity/src/test/kotlin/PerformanceTestBuildTypeTest.kt
  .teamcity/src/test/kotlin/PromotionProjectTests.kt
  .teamcity/src/test/kotlin/VersionedSettingsBranchTest.kt
Labels: @dev-productivity

#23801 Mark flaky KotlinScriptDependenciesResolverTest
  subprojects/kotlin-dsl/src/integTest/kotlin/org/gradle/kotlin/dsl/resolver/KotlinScriptDependenciesResolverTest.kt
Labels: @dev-productivity

#23791 Set bt-dev-prod team as CODEOWNERS for all build scripts
  .github/CODEOWNERS
Labels: @dev-productivity

#23805 Use MySQL dialect and INSERT IGNORE for H2 database
  subprojects/build-cache/src/main/java/org/gradle/caching/local/internal/H2BuildCacheService.java
  subprojects/build-cache/src/main/resources/db/migration/V001__init_schema.sql
  subprojects/build-cache/src/main/resources/h2/schemas/org.gradle.caching.local.internal.H2BuildCacheService.sql
  subprojects/build-cache/src/test/groovy/org/gradle/caching/local/internal/H2BuildCacheServiceTest.groovy
Labels: @execution

#23714 Capture output while collecting accessors schema for Kotlin precompiled script plugins
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/PrecompiledScriptPluginIntegrationTest.kt
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/DefaultPrecompiledScriptPluginsSupport.kt
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/PrecompiledScriptException.kt
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/tasks/GeneratePrecompiledScriptPluginAccessors.kt
Labels: in:kotlin-dsl

#23639 Let version catalog be usable in Kotlin DSL `plugins {}` block with IDE support
  subprojects/core/src/main/java/org/gradle/api/internal/DefaultClassPathProvider.java
  subprojects/core/src/main/java/org/gradle/api/internal/catalog/ExternalModuleDependencyFactory.java
  subprojects/core/src/main/java/org/gradle/initialization/DependenciesAccessors.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/CatalogPluginsKotlinDSLIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/DefaultDependenciesAccessors.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/LibrariesSourceGenerator.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/catalog/LibrariesSourceGeneratorTest.groovy
  subprojects/docs/src/docs/userguide/migration/upgrading_version_8.adoc
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/tasks/CompilePrecompiledScriptPluginPlugins.kt
  subprojects/kotlin-dsl-tooling-builders/src/main/kotlin/org/gradle/kotlin/dsl/tooling/builders/KotlinBuildScriptModelBuilder.kt
  subprojects/kotlin-dsl/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/PluginSpecBuilderAccessorsIntegrationTest.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/PluginDependenciesSpecScope.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/ProjectExtensions.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/ScriptHandlerScope.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/GeneratePluginSpecBuilderAccessors.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/GenerateVersionCatalogAccessors.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/GradleScopeServices.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/Stage1BlocksAccessorClassPath.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/execution/Interpreter.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/execution/PartialEvaluator.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/execution/ResidualProgram.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/execution/ResidualProgramCompiler.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/precompile/v1/PrecompiledScriptTemplates.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/KotlinScriptEvaluator.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/CompiledKotlinBuildScript.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/CompiledKotlinPluginsBlock.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/KotlinCompiler.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/KotlinScriptHost.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/PluginDependenciesSpecScopeInternal.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/ScriptHandlerScopeInternal.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/bytecode/KotlinMetadata.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/accessors/PluginDependencySpecAccessorsTest.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/accessors/PluginSpecBuilderAccessorsClassPathTest.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/execution/PartialEvaluatorTest.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/execution/TestWithCompiler.kt
  subprojects/kotlin-dsl/src/testFixtures/kotlin/org/gradle/kotlin/dsl/fixtures/SimplifiedKotlinScriptEvaluator.kt
Labels: in:kotlin-dsl, in:dependency-version-catalog

#23808 Fix sorting of accepted api changes to work on Chrome
  build-logic/binary-compatibility/src/main/groovy/gradlebuild/EnrichedReportRenderer.groovy
  build-logic/binary-compatibility/src/main/kotlin/gradlebuild/binarycompatibility/AbstractAcceptedApiChangesMaintenanceTask.kt
Labels: in:building-gradle

#23825 Mark flaky DependencyArtifactDownloadProgressEventCrossVersionTest
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r81/DependencyArtifactDownloadProgressEventCrossVersionTest.groovy
Labels: @dev-productivity

#23826 Update tested AGP versions
  gradle/dependency-management/agp-versions.properties
  subprojects/docs/src/docs/userguide/compatibility.adoc
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidSantaTrackerCachingSmokeTest.groovy
Labels: a:chore

#23731 Fix behavior for nested DeprecationLogger.whileDisabled invocations
  gradle.properties
  subprojects/logging/src/main/java/org/gradle/internal/deprecation/DeprecationLogger.java
  subprojects/logging/src/test/groovy/org/gradle/internal/deprecation/DeprecationLoggerTest.groovy
  subprojects/model-core/src/main/java/org/gradle/internal/instantiation/generator/AbstractClassGenerator.java
  subprojects/model-core/src/main/java/org/gradle/internal/instantiation/generator/AsmBackedClassGenerator.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/KotlinPluginSmokeTest.groovy
Labels: a:bug, in:deprecation-logging

#23832 Document now unecessary workaround for catalogs in KTS `plugins {}` in upgrade guide
  subprojects/docs/src/docs/userguide/migration/upgrading_version_8.adoc
Labels: in:kotlin-dsl

#23820 Notes 8.0 split cc parallel
  subprojects/docs/src/docs/css/release-notes.css
  subprojects/docs/src/docs/release/notes.md
Labels: a:documentation

#23835 Tweak cache cleanup documentation to use a clear, more consistent pattern
  subprojects/docs/src/docs/userguide/reference/directory_layout.adoc
  subprojects/docs/src/snippets/initScripts/multiVersionCacheRetention/groovy/gradleUserHome/init.d/cache-settings.gradle
  subprojects/docs/src/snippets/initScripts/multiVersionCacheRetention/groovy/gradleUserHome/init.d/gradle8/cache-settings.gradle
  subprojects/docs/src/snippets/initScripts/multiVersionCacheRetention/kotlin/gradleUserHome/init.d/cache-settings.gradle.kts
  subprojects/docs/src/snippets/initScripts/multiVersionCacheRetention/kotlin/gradleUserHome/init.d/gradle8/cache-settings.gradle.kts
Labels: a:documentation

#23842 Fix typo: `--nodaemon` -> `--no-daemon`
  subprojects/docs/src/docs/userguide/running-builds/gradle_daemon.adoc
Labels: a:documentation

#23829 Deprecate COD-Kotlin DSL combination
  subprojects/core/src/integTest/groovy/org/gradle/api/ConfigurationOnDemandIntegrationTest.groovy
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/KotlinScriptPluginFactory.kt
Labels: in:kotlin-dsl, in:configure-on-demand

#23850 Add test coverage for `BuildOperationListener` build services
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildServiceIntegrationTest.groovy
Labels: in:configuration-cache, @configuration-cache

#23846 Discard listeners from builds without work
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildServiceIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
Labels: @configuration-cache

#23845 Use snapshot data from cache instead of resnapshotting in NextGenBuildCacheController
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/NextGenBuildCacheController.java
  subprojects/build-cache/src/test/groovy/org/gradle/caching/internal/controller/NextGenBuildCacheControllerTest.groovy
  subprojects/core/src/main/java/org/gradle/caching/internal/services/NextGenBuildCacheControllerFactory.java
Labels: @execution, in:build-cache

#23852 Release notes final 8.0
  subprojects/docs/src/docs/release/notes.md
Labels: a:documentation

#23642 Remove unnecessary LazyPublishArtifact constructors
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/ArtifactFile.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/LazyPublishArtifact.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/dsl/ArtifactFileTest.groovy
  subprojects/docs/src/samples/build-organization/structuring-software-projects/groovy/platforms/plugins-platform/build.gradle
  subprojects/docs/src/samples/build-organization/structuring-software-projects/groovy/platforms/product-platform/build.gradle
  subprojects/docs/src/samples/build-organization/structuring-software-projects/kotlin/platforms/plugins-platform/build.gradle.kts
  subprojects/docs/src/samples/build-organization/structuring-software-projects/kotlin/platforms/product-platform/build.gradle.kts
  subprojects/docs/src/samples/spring-boot-web-application/groovy/app/build.gradle
  subprojects/docs/src/samples/spring-boot-web-application/kotlin/app/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/applying-plugins-declarative/groovy/build.gradle
  subprojects/docs/src/snippets/kotlinDsl/applying-plugins-declarative/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/applying-plugins-imperative/groovy/build.gradle
  subprojects/docs/src/snippets/kotlinDsl/applying-plugins-imperative/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/configuring-tasks-spring-boot/groovy/build.gradle
  subprojects/docs/src/snippets/kotlinDsl/configuring-tasks-spring-boot/kotlin/build.gradle.kts
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/artifact/MavenArtifactNotationParserFactory.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/JvmPluginsHelper.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/SpringBootPluginSmokeTest.groovy
Labels: in:publishing-plugins

#23720 Let Kotlin standalone script compilation show compiler warnings by default
  subprojects/docs/src/docs/userguide/migration/upgrading_version_8.adoc
  subprojects/docs/src/snippets/initScripts/customLogger/groovy/customLogger.init.gradle
  subprojects/docs/src/snippets/initScripts/customLogger/kotlin/customLogger.init.gradle.kts
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/GradleKotlinDslIntegrationTest.kt
  subprojects/kotlin-dsl/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/KotlinBuildScriptIntegrationTest.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/KotlinCompiler.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/Logger.kt
  subprojects/kotlin-dsl/src/testFixtures/kotlin/org/gradle/kotlin/dsl/fixtures/Testing.kt
Labels: in:kotlin-dsl

#23786 Fix broken links generated by Gradle
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/BuildScriptBuilder.java
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/server/health/gc/GarbageCollectionMonitoringIntegrationTest.groovy
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/health/HealthExpirationStrategy.java
  subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/HttpClientHelper.java
Labels: in:daemon, from:contributor

#23711 Further Simplify Capabilities Type Hierarchy
  subprojects/core-api/src/main/java/org/gradle/api/internal/capabilities/CapabilitiesMetadataInternal.java
  subprojects/core-api/src/main/java/org/gradle/api/internal/capabilities/CapabilityInternal.java
  subprojects/core-api/src/main/java/org/gradle/api/internal/capabilities/ImmutableCapability.java
  subprojects/core-api/src/main/java/org/gradle/api/internal/capabilities/ShadowedCapability.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/DependencyManagementResultsAsInputsIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/capabilities/CapabilitiesRulesIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/capabilities/PublishedCapabilitiesIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ModuleComponentSelectorSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/CapabilityNotationParserFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/DefaultDependencyHandler.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/GradleModuleMetadataParser.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/modulecache/ModuleMetadataSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolutionstrategy/DefaultCapabilitiesResolution.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/ArtifactSetFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ComponentState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/NodeState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/conflicts/DefaultCapabilitiesConflictHandler.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/conflicts/UpgradeCapabilityResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/CapabilitySerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ComponentSelectorSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/CapabilitiesSupport.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractMutableModuleComponentResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractRealisedModuleResolveMetadataSerializationHelper.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/DefaultImmutableCapability.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/DefaultMutableCapabilities.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ImmutableCapabilities.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ImmutableCapability.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/JavaEcosystemVariantDerivationStrategy.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ProjectDerivedCapability.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ShadowedImmutableCapability.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/VariantMetadataRules.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/AttributeConfigurationSelector.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/resolver/DefaultArtifactSelector.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ModuleComponentSelectorSerializerTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/DefaultArtifactSetTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/conflicts/DefaultCapabilitiesConflictHandlerTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ComponentSelectorSerializerTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/external/model/DefaultModuleComponentSelectorTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/model/AttributeConfigurationSelectorTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/model/LocalComponentDependencyMetadataTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlatformPlugin.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/DefaultJavaFeatureSpec.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/TestFixturesDependencyModifiers.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmPluginServices.java
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmVariantBuilder.java
  subprojects/publish/src/test/groovy/org/gradle/api/publish/internal/metadata/GradleModuleMetadataWriterTest.groovy
Labels: in:publishing-plugins

#23859 Update tested AGP version
  gradle/dependency-management/agp-versions.properties
Labels: a:chore

#23854 Deprecate 'org.gradle.cache.cleanup' property
  subprojects/build-cache/src/integTest/groovy/org/gradle/caching/local/internal/DirectoryBuildCacheCleanupIntegrationTest.groovy
  subprojects/core-api/src/main/java/org/gradle/internal/cache/MonitoredCleanupActionDecorator.java
  subprojects/core/src/integTest/groovy/org/gradle/cache/internal/GradleUserHomeCleanupServiceIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/cache/DefaultCacheConfigurations.java
  subprojects/core/src/main/java/org/gradle/cache/internal/GradleUserHomeCacheCleanupActionDecorator.java
  subprojects/core/src/main/java/org/gradle/cache/internal/GradleUserHomeCleanupService.java
  subprojects/core/src/main/java/org/gradle/cache/internal/GradleUserHomeCleanupServices.java
  subprojects/core/src/main/java/org/gradle/cache/internal/LegacyCacheCleanupEnablement.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/DefaultClasspathTransformerCacheFactory.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/GradleUserHomeScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/service/scopes/SettingsScopeServices.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/cache/DefaultCacheConfigurationsTest.groovy
  subprojects/core/src/test/groovy/org/gradle/cache/internal/GradleUserHomeCacheCleanupActionDecoratorTest.groovy
  subprojects/core/src/test/groovy/org/gradle/cache/internal/GradleUserHomeCleanupServiceTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/classpath/DefaultCachedClasspathTransformerTest.groovy
  subprojects/core/src/testFixtures/groovy/org/gradle/cache/internal/GradleUserHomeCleanupFixture.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/caching/DefaultArtifactCacheLockingAccessCoordinatorIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementGradleUserHomeScopeServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/DefaultArtifactCaches.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/WritableArtifactCacheLockingAccessCoordinator.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/ImmutableTransformationWorkspaceServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/DependenciesAccessorsWorkspaceProvider.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/DefaultArtifactCacheLockingAccessCoordinatorTest.groovy
  subprojects/docs/src/docs/userguide/migration/upgrading_version_8.adoc
  subprojects/execution/src/main/java/org/gradle/internal/execution/workspace/impl/DefaultImmutableWorkspaceProvider.java
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/cache/GradleUserHomeServices.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/cache/KotlinDslWorkspaceProvider.kt
Labels: a:chore

#23875 Improve load-after-store coverage for `:plugins` module
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/BasePluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/JavaPluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecWithExecutableJarIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaProjectOutgoingVariantsIntegrationTest.groovy
  subprojects/plugins/src/integTest/resources/org/gradle/groovy/compile/ApiGroovyCompilerIntegrationSpec/canEnableAndDisableAllOptimizations/build.gradle
  subprojects/plugins/src/integTest/resources/org/gradle/groovy/compile/ApiGroovyCompilerIntegrationSpec/canEnableAndDisableIntegerOptimization/build.gradle
  subprojects/plugins/src/integTest/resources/org/gradle/groovy/compile/InvokeDynamicGroovyCompilerSpec/canEnableAndDisableInvokeDynamicOptimization/build.gradle
Labels: @configuration-cache, in:java-plugins

#23876 Enable `load-after-store` coverage for `:plugins`
  subprojects/language-jvm/src/testFixtures/groovy/org/gradle/api/tasks/compile/AbstractCompilerDaemonReuseIntegrationTest.groovy
  subprojects/plugins/build.gradle.kts
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/bundling/JarIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/groovy/GroovyBasePluginIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/integtests/resolve/consistency/JavaProjectResolutionConsistencyIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaApplicationOutgoingVariantsIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaLibraryConsumptionIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaLibraryFeatureCompilationIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/JavaLibraryOutgoingVariantsIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/BasicJavaCompilerIntegrationSpec.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/fixtures/AbstractJavaTestFixturesIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/jvm/BucketOfDependenciesIntegrationTest.groovy
Labels: in:configuration-cache, @configuration-cache, in:java-plugins

#23880 Test against CodeNarc versions supported by the toolchain JDK
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcNonJvmIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcPluginToolchainsIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcPluginVersionIntegrationTest.groovy
  subprojects/code-quality/src/testFixtures/groovy/org/gradle/quality/integtest/fixtures/CodeNarcCoverage.groovy
Labels: a:bug, in:codenarc-plugin

#23873 Fix sample tag filtering in sample when no tags are specified
  subprojects/docs-asciidoctor-extensions-base/src/main/java/org/gradle/docs/asciidoctor/SampleIncludeProcessor.java
  subprojects/docs-asciidoctor-extensions-base/src/test/groovy/org/gradle/docs/asciidoctor/SampleIncludeProcessorTest.groovy
  subprojects/docs/src/docs/userguide/authoring-builds/software-product/composite_builds.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
Labels: in:documentation-infrastructure

#23377 Reduce overhead of getting console columns
  subprojects/logging/src/main/java/org/gradle/internal/logging/console/DefaultWorkInProgressFormatter.java
Labels: from:contributor

#23897 Add test for error loading gradle properties from included build task
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheGradlePropertiesIntegrationTest.groovy
Labels: in:composite-builds, in:configuration-cache, @configuration-cache

#23899 Improve `application` plugin test coverage
  subprojects/core/src/main/java/org/gradle/process/internal/DefaultJavaForkOptions.java
  subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/ApplicationPluginIntegrationTest.groovy
Labels: @configuration-cache, in:java-plugins

#23771 Avoid eager instantiation of shared services
  subprojects/core/src/integTest/groovy/org/gradle/api/services/BuildServiceIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/AbstractValidatingProperty.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/ValidationAction.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/ValidationActions.java
  subprojects/core/src/main/java/org/gradle/api/services/internal/BuildServiceProvider.java
  subprojects/core/src/main/java/org/gradle/api/services/internal/ConsumedBuildServiceProvider.java
  subprojects/core/src/main/java/org/gradle/api/services/internal/RegisteredBuildServiceProvider.java
Labels: @configuration-cache

#23822 Ensure settings location preserved even if missing
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheHost.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/core/src/test/groovy/org/gradle/groovy/scripts/TextResourceScriptSourceTest.java
  subprojects/resources/src/main/java/org/gradle/internal/resource/DefaultTextFileResourceLoader.java
  subprojects/resources/src/main/java/org/gradle/internal/resource/EmptyFileTextResource.java
  subprojects/resources/src/main/java/org/gradle/internal/resource/UriTextResource.java
  subprojects/resources/src/test/groovy/org/gradle/internal/resource/UriTextResourceTest.groovy
Labels: @configuration-cache

#23653 Support ConfigurableFileCollection = FileCollection assignment for Groovy and Kotlin
  subprojects/core-api/src/main/java/org/gradle/api/file/ConfigurableFileCollection.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/collections/DefaultConfigurableFileCollection.java
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/KotlinDslAssignmentIntegrationTest.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinAssignmentExtensions.kt
  subprojects/model-core/src/integTest/groovy/org/gradle/api/provider/PropertyAssignmentIntegrationTest.groovy
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/PropertyInternal.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/support/LazyGroovySupport.java
  subprojects/model-core/src/main/java/org/gradle/internal/instantiation/generator/AbstractClassGenerator.java
  subprojects/model-core/src/main/java/org/gradle/internal/instantiation/generator/AsmBackedClassGenerator.java
Labels: in:kotlin-dsl, in:groovy-dsl, @execution

#23907 Enable `load-after-store` coverage for `:wrapper`
  subprojects/wrapper/build.gradle.kts
  subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperProjectIntegrationTest.groovy
Labels: in:wrapper, @configuration-cache

#23915 Some fixes for `ArtifactCollection` instances loaded from the cache
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/ArtifactCollectionCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformParallelIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/ArtifactCollectionInternal.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultArtifactCollection.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/ArtifactSetToFileCollectionFactory.java
Labels: in:configuration-cache, @configuration-cache, in:artifact-transforms

#23916 Enable `load-after-store` test coverage for `:integ-test`
  subprojects/integ-test/build.gradle.kts
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/ApplicationIntegrationSpec.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/CacheProjectIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/JavaCompileOnlyDependencyIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/MixInCoreTypesTransformingClassLoaderIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/MultiProjectDependencyIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/StaleOutputIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskUpToDateIntegrationTest.groovy
Labels: in:testing, @configuration-cache

#23921 Restore --no-rebuild command line option
  subprojects/core/src/integTest/groovy/org/gradle/api/ConfigurationOnDemandIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/initialization/StartParameterBuildOptions.java
  subprojects/docs/src/docs/userguide/authoring-builds/organizing_gradle_projects.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/docs/src/docs/userguide/reference/command_line_interface.adoc
Labels: in:invoking-gradle

#23926 Update Scala target computation
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/jvm/scala_plugin.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/AbstractGradleExecuter.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/logging/ZincScalaCompilerOutputNormalizer.groovy
  subprojects/internal-integ-testing/src/test/groovy/org/gradle/integtests/fixtures/logging/ZincScalaCompilerOutputNormalizerTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/ScalaPluginIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/ScalaCompileIntegrationTest.groovy
  subprojects/scala/src/main/java/org/gradle/api/tasks/scala/internal/ScalaCompileOptionsConfigurer.java
  subprojects/scala/src/test/groovy/org/gradle/scala/compile/internal/ScalaCompileOptionsConfigurerTest.groovy
Labels: in:scala-plugin

#23931 Grouped output assertions for transformations
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/TransformationLoggingIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/logging/GroupedOutputFixture.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/logging/GroupedTaskOutputFixture.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/logging/GroupedTransformationOutputFixture.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/logging/GroupedWorkOutputFixture.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/logging/comparison/ExhaustiveLinesSearcher.java
  subprojects/internal-integ-testing/src/test/groovy/org/gradle/integtests/fixtures/logging/GroupedOutputFixtureTest.groovy
Labels: in:testing

#23940 Fix upgrade guides
  subprojects/docs/src/docs/userguide/migration/upgrading_version_6.adoc
  subprojects/docs/src/main/resources/header.html
Labels: a:documentation

#23913 Backport "Fix incremental compilation with modules" to 7.6.1
  subprojects/docs/src/docs/userguide/jvm/java_plugin.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/BaseIncrementalCompilationAfterFailureIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/CrossTaskIncrementalJavaCompilationIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/DefaultJavaCompileSpec.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompileSpec.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JdkJavaCompiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/RecompilationSpec.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/transaction/CompileTransaction.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/reflect/GradleStandardJavaFileManager.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/DefaultJavaCompileSpecTest.groovy
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/incremental/transaction/CompileTransactionTest.groovy
  subprojects/language-jvm/src/main/java/org/gradle/api/internal/tasks/compile/DefaultJvmLanguageCompileSpec.java
  subprojects/language-jvm/src/main/java/org/gradle/api/internal/tasks/compile/JvmLanguageCompileSpec.java
  subprojects/scala/src/main/java/org/gradle/language/scala/tasks/AbstractScalaCompile.java
Labels: @execution

#23936 Update tested AGP versions
  gradle/dependency-management/agp-versions.properties
Labels: a:chore

#23942 Relax presence of Scala compiler warnings
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/ScalaCompileIntegrationTest.groovy
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/ScalaCompileJavaToolchainIntegrationTest.groovy
Labels: in:scala-plugin

#23953 Update wrapper to 8.0.1
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore

#23956 Allow for easy customization of Kotlin options in `kotlin-dsl` projects
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/KotlinDslPluginCustomKotlinOptionsIntegrationTest.kt
  subprojects/kotlin-dsl-plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslCompilerPlugins.kt
  subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/KotlinCompiler.kt
Labels: in:kotlin-dsl

#23946 Trusted GPG-key should only accept 160-bit fingerprints
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationSignatureCheckIntegTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/StartParameterResolutionOverride.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/ChecksumAndSignatureVerificationOverride.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/exceptions/ComponentVerificationException.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/exceptions/DependencyVerificationException.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/exceptions/InvalidGpgKeyIdsException.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/serializer/DependencyVerificationsXmlReader.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/verifier/DependencyVerificationConfiguration.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/verification/verifier/DependencyVerifierBuilder.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/writer/PgpKeyGrouperTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/verification/serializer/DependencyVerificationsXmlReaderTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/verification/serializer/DependencyVerificationsXmlWriterTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/verification/verifier/DependencyVerifierBuilderTest.groovy
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/dependency_verification.adoc
Labels: in:dependency-verification

#23912 Request max heap memory when starting worker process
  subprojects/core/src/integTest/groovy/org/gradle/process/internal/worker/DefaultWorkerProcessBuilderIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/process/internal/worker/DefaultWorkerProcessBuilder.java
  subprojects/core/src/test/groovy/org/gradle/process/internal/worker/DefaultWorkerProcessBuilderSpec.groovy
Labels: a:feature, in:workers

#23938 Use Hash key salt for BuildCacheNG to not conflict with old build cache
  subprojects/build-cache-http/src/integTest/groovy/org/gradle/caching/NextGenBuildCacheHttpIntegrationTest.groovy
  subprojects/build-cache/src/integTest/groovy/org/gradle/caching/NextGenBuildCacheIntegrationTest.groovy
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/NextGenBuildCacheController.java
  subprojects/build-cache/src/test/groovy/org/gradle/caching/internal/controller/NextGenBuildCacheControllerTest.groovy
  subprojects/core/src/main/java/org/gradle/caching/internal/BuildCacheServices.java
  subprojects/core/src/main/java/org/gradle/caching/internal/services/NextGenBuildCacheControllerFactory.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/caching/CachingStateFactory.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/caching/impl/DefaultCachingStateFactory.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ResolveCachingStateStep.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractIntegrationSpec.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/AbstractGradleExecuter.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/GradleExecuter.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/HttpBuildCacheServer.groovy
Labels: @execution, in:build-cache

#23944 Fix physical memory monitoring in constrained Linux docker containers
  subprojects/docs/src/docs/release/notes.md
  subprojects/process-services/src/main/java/org/gradle/process/internal/health/memory/CGroupMemoryInfo.java
  subprojects/process-services/src/main/java/org/gradle/process/internal/health/memory/DefaultOsMemoryInfo.java
  subprojects/process-services/src/main/java/org/gradle/process/internal/health/memory/MemInfoOsMemoryInfo.java
  subprojects/process-services/src/test/groovy/org/gradle/process/internal/health/memory/CGroupMemoryInfoTest.groovy
  subprojects/process-services/src/test/groovy/org/gradle/process/internal/health/memory/MemInfoOsMemoryInfoTest.groovy
Labels: a:bug

#23975 Release note for 6.9.4
  subprojects/docs/src/docs/release/notes.md
Labels: a:chore

#23969 Add navigation component for mobile devices
  subprojects/docs/src/docs/css/manual.css
  subprojects/docs/src/main/resources/footer.html
Labels: from:contributor

#24006 Prepare for release 8.0.2
  released-versions.json
  version.txt
Labels: a:chore

#23948 Clarify handling of secrets and configuration cache
  subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
Labels: in:configuration-cache, a:documentation

#24015 Update EOL policy
  subprojects/docs/src/docs/userguide/migration/feature_lifecycle.adoc
Labels: a:documentation

#23991 Clear root metadata when adding or removing configurations
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/AddingConfigurationIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationContainer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/moduleconverter/DefaultRootComponentMetadataBuilder.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationContainerSpec.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationContainerTest.groovy
Labels: a:regression

#24025 Release notes for 7.6.1
  subprojects/docs/src/docs/release/notes.md
Labels: a:chore

#24027 Ignore tests to unblock 7.6.1
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/continuous/MultiProjectContinuousIntegrationTest.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerDaemonLoggingIntegrationTest.groovy
Labels: a:chore

#24011 Add "How Gradle Works" blog into contribution documentation
  CONTRIBUTING.md
Labels: from:contributor

#23807 Enable agent-based instrumentation by default
  build-logic/integration-testing/src/main/kotlin/gradlebuild/integrationtests/shared-configuration.kt
  subprojects/integ-test/src/crossVersionTest/groovy/org/gradle/integtests/TapiAgentInstrumentationCrossVersionSpec.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/instrumentation/agent/AgentApplicationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/AbstractGradleExecuter.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/configuration/DaemonParameters.java
  subprojects/launcher/src/test/groovy/org/gradle/launcher/daemon/configuration/BuildProcessTest.groovy
  subprojects/tooling-api/build.gradle.kts
Labels: @configuration-cache

#24049 Merge changes from `release7x`
  released-versions.json
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/AddingConfigurationIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationContainer.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationContainerSpec.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationContainerTest.groovy
  subprojects/docs/src/docs/userguide/migration/feature_lifecycle.adoc
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/DistributionLocatorIntegrationTest.groovy
Labels: a:chore

#24059 Detect more cases when Scala target is already configured in parameters
  subprojects/scala/src/main/java/org/gradle/api/tasks/scala/internal/ScalaCompileOptionsConfigurer.java
  subprojects/scala/src/test/groovy/org/gradle/scala/compile/internal/ScalaCompileOptionsConfigurerTest.groovy
Labels: in:scala-plugin

#24003 Augment upgrading guide for Kotlin Gradle Plugin 1.8
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
Labels: in:kotlin-dsl, a:documentation

#23970 Reduce the padding of footer for mobile devices
  subprojects/docs/src/docs/css/manual.css
Labels: from:contributor

#24056 Fix issue with test exception that cannot be deserialized
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/TestFailureSerializationException.java
  subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/worker/TestEventSerializer.java
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junit/JUnitIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junitplatform/JUnitPlatformIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGIntegrationTest.groovy
Labels: a:bug, in:testing-junit5, in:testing-junit4, in:testing-testng

#24072 Restore an edge case of non-javac toolchain tools being used as a Java compiler (Gradle 8.0.x)
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileToolchainIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/AbstractJavaCompileSpecFactory.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
Labels: in:toolchains
