Repository gradle/gradle, pull requests merged in 2023-05, with the labels that each got.

#24965 Expose correct repository name through ResolveConfigurationDependenciesBuildOperationType when repositories are mutated between resolution
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/repositories/IvyArtifactRepository.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ResolveConfigurationDependenciesBuildOperationIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ResolveConfigurationRepositoriesBuildOperationIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/ResolveConfigurationResolutionBuildOperationDetails.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/ResolveConfigurationResolutionBuildOperationResult.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/RepositoryChainModuleSource.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/ResolvedGraphComponent.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ComponentState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ComponentResultSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/DefaultResolutionResultBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/DetachedComponentResult.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/AbstractAuthenticationSupportedRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/AbstractResolutionAwareArtifactRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultFlatDirArtifactRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultIvyArtifactRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultMavenArtifactRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultMavenLocalArtifactRepository.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/descriptor/FlatDirRepositoryDescriptor.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/descriptor/IvyRepositoryDescriptor.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/descriptor/MavenRepositoryDescriptor.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/descriptor/RepositoryDescriptor.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/descriptor/UrlRepositoryDescriptor.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/layout/AbstractRepositoryLayout.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/layout/DefaultIvyPatternRepositoryLayout.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/layout/GradleRepositoryLayout.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/layout/IvyRepositoryLayout.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/layout/MavenRepositoryLayout.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/metadata/AbstractMetadataSource.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/metadata/AbstractRepositoryMetadataSource.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/metadata/DefaultArtifactMetadataSource.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/metadata/DefaultGradleModuleMetadataSource.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/metadata/DefaultImmutableMetadataSources.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/metadata/ImmutableMetadataSources.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/metadata/MetadataSource.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/metadata/RedirectingGradleMetadataModuleMetadataSource.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/ExternalResourceResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/IvyResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/MavenResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/PatternBasedResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/result/DefaultResolvedComponentResult.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/result/ResolvedComponentResultInternal.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/DependencyResolverIdentifierTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/ResolveIvyFactoryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ComponentResultSerializerTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/DefaultResolutionResultBuilderSpec.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/DefaultFlatDirArtifactRepositoryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/DefaultIvyArtifactRepositoryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/DefaultMavenArtifactRepositoryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/resolver/ExternalResourceResolverTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/resolver/IvyResolverTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/resolver/MavenResolverTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/resolver/TestResolver.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/plugins/IvyPublishPlugin.java
Labels: @configuration-cache, in:dependency-resolution

#24969 Refactor worker daemon logging test to reduce flakiness
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerDaemonLoggingIntegrationTest.groovy
Labels: a:chore, in:workers, 1 min review, platform:core

#24843 Deprecate running test task successfully when no test executed
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/GroovyApplicationInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/GroovyLibraryInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/JavaApplicationInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/JavaLibraryInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/KotlinApplicationInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/KotlinLibraryInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/ScalaApplicationInitIntegrationTest.groovy
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/ScalaLibraryInitIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginVersionIntegrationTest.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/codenarc/CodeNarcTestFixture.groovy
  subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/pmd/PmdPluginDependenciesIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/caching/configuration/internal/BuildCacheCompositeConfigurationIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ResolveConfigurationDependenciesBuildOperationIntegrationTest.groovy
  subprojects/docs/src/docs/userguide/migration/upgrading_version_8.adoc
  subprojects/docs/src/snippets/kotlinDsl/accessors/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/accessors/kotlin/src/test/java/TestSource.java
  subprojects/docs/src/snippets/testing/patch-module/groovy/build.gradle
  subprojects/docs/src/snippets/testing/patch-module/kotlin/build.gradle.kts
  subprojects/enterprise/src/integTest/groovy/org/gradle/internal/enterprise/test/TestTaskPropertiesServiceIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/JavaProjectIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/ProjectLayoutIntegrationTest.groovy
  subprojects/platform-native/src/testFixtures/groovy/org/gradle/nativeplatform/fixtures/app/SwiftXCTestWithDepAndCustomXCTestSuite.groovy
  subprojects/plugins/src/integTest/resources/org/gradle/groovy/compile/GroovyCompilerIntegrationSpec/gradle3235/build.gradle
  subprojects/plugins/src/integTest/resources/org/gradle/groovy/compile/GroovyCompilerIntegrationSpec/gradle3235/src/test/groovy/DummyFileForCompilation.groovy
  subprojects/testing-base/src/main/java/org/gradle/api/tasks/testing/AbstractTestTask.java
  subprojects/testing-base/src/testFixtures/groovy/org/gradle/testing/AbstractTestFrameworkIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestTaskFailOnNoTestIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junit/AbstractJUnitCategoriesOrTagsCoverageIntegrationSpec.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junit/junit4/JUnit4CategoriesOrTagsCoverageIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junit/junit4/JUnit4JUnitIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junit/platform/JUnitPlatformIntegrationSpec.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junit/platform/JUnitPlatformIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junit/platform/JUnitPlatformLauncherSessionListenerIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGFailOnNoTestIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGTestFrameworkIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGUpToDateCheckIntegrationTest.groovy
  subprojects/testing-native/src/integTest/groovy/org/gradle/nativeplatform/test/xctest/SwiftXCTestIntegrationTest.groovy
  subprojects/testing-native/src/integTest/groovy/org/gradle/nativeplatform/test/xctest/XCTestWithApplicationDependenciesIntegrationTest.groovy
Labels: in:testing, a:bug

#24999 Remove flakiness annotation
  subprojects/core/src/integTest/groovy/org/gradle/execution/taskgraph/ParallelTaskExecutionIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/api/tasks/JavaExecDebugIntegrationTest.groovy
Labels: a:chore, 1 min review, platform:jvm

#24945 Update test bucket json
  .teamcity/test-buckets.json
Labels: @dev-productivity

#24985 Modernize test project generation
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/generator/FileContentGenerator.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/generator/GroovyDslFileContentGenerator.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/generator/KotlinDslFileContentGenerator.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/generator/TestProjectGenerator.groovy
  subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/generator/TestProjectGeneratorConfiguration.groovy
Labels: 1 min review, platform:build-infrastructure

#25003 Include opposite task options in documentation
  subprojects/build-init/src/main/java/org/gradle/buildinit/tasks/InitBuild.java
  subprojects/docs/src/docs/userguide/core-plugins/build_init_plugin.adoc
  subprojects/docs/src/docs/userguide/dep-man/04-modeling-features/variant_model.adoc
  subprojects/docs/src/docs/userguide/jvm/java_testing.adoc
  subprojects/docs/src/docs/userguide/native/native_software.adoc
  subprojects/docs/src/docs/userguide/reference/command_line_interface.adoc
Labels: @execution, a:documentation

#24974 Binary upgrades infrastructure
  subprojects/internal-instrumentation-api/src/main/java/org/gradle/internal/instrumentation/api/annotations/UpgradedProperty.java
  subprojects/internal-instrumentation-processor/src/main/java/org/gradle/internal/instrumentation/extensions/property/PropertyUpgradeAnnotatedMethodReader.java
  subprojects/internal-instrumentation-processor/src/main/java/org/gradle/internal/instrumentation/extensions/property/PropertyUpgradeClassSourceGenerator.java
  subprojects/internal-instrumentation-processor/src/main/java/org/gradle/internal/instrumentation/extensions/property/PropertyUpgradeRequestExtra.java
  subprojects/internal-instrumentation-processor/src/test/groovy/org/gradle/internal/instrumentation/extensions/property/PropertyUpgradeCodeGenTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidPluginsSmokeTest.groovy
Labels: @execution, in:execution-engine

#25004 Mark JavaApplicationDeploymentIntegrationTest LocalOnly
  subprojects/plugins/src/integTest/groovy/org/gradle/internal/deployment/JavaApplicationDeploymentIntegrationTest.groovy
Labels: in:testing, flaky-fix-it

#24995 Split tests to improve parallel execution
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/versions/AbstractRichVersionConstraintsIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/versions/AbstractVersionRangeResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/versions/IvyRichVersionConstraintsIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/versions/MavenRichVersionConstraintsIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/versions/VersionConflictResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/versions/VersionRangeResolvePairBatch1IntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/versions/VersionRangeResolvePairBatch2IntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/versions/VersionRangeResolvePreferPairBatch1IntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/versions/VersionRangeResolvePreferPairBatch2IntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/versions/VersionRangeResolveRejectPairIntegrationTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/selectors/SelectorStateResolverTest.groovy
  subprojects/dependency-management/src/testFixtures/groovy/org/gradle/resolve/scenarios/VersionRangeResolveTestScenarios.groovy
Labels: a:chore

#25011 Update snakeyaml to 2.0
  gradle/verification-metadata.xml
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/swift/SwiftDepsHandler.java
Labels: a:chore

#25024 Remove some hotspots in dependency graph resolution
  subprojects/architecture-test/src/changes/archunit_store/internal-api-nullability.txt
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/ConfigurationsProvider.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationContainer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DetachedConfigurationsProvider.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/clientmodule/ClientModuleResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/DefaultVersionedComponentChooser.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/VersionedComponentChooser.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/moduleconverter/DefaultRootComponentMetadataBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/moduleconverter/dependencies/DefaultLocalConfigurationMetadataBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/DependencyGraphBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ConfigurationBoundExternalDependencyMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/DefaultModuleComponentGraphResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ExternalComponentResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ModuleComponentGraphResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ModuleComponentGraphResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ModuleComponentGraphResolveStateFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ModuleComponentResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/local/model/DefaultLocalComponentGraphResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/local/model/DefaultLocalComponentMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/local/model/LocalComponentGraphResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/AbstractComponentGraphResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/ComponentArtifactResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/ComponentGraphResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/ComponentGraphResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/ComponentResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/DefaultComponentGraphResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/result/BuildableModuleComponentMetaDataResolveResult.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/DefaultVersionedComponentChooserTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/local/model/DefaultLocalComponentMetadataTest.groovy
  subprojects/messaging/src/main/java/org/gradle/internal/serialize/Int2ObjectMapSerializer.java
  subprojects/messaging/src/test/groovy/org/gradle/internal/serialize/Int2ObjectMapSerializerTest.groovy
Labels: @configuration-cache, in:dependency-resolution

#25023 Add cross-process file locking around H2 build cache
  subprojects/build-cache-http/src/integTest/groovy/org/gradle/caching/NextGenBuildCacheHttpIntegrationTest.groovy
  subprojects/build-cache/src/integTest/groovy/org/gradle/caching/NextGenBuildCacheIntegrationTest.groovy
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/StatefulNextGenBuildCacheService.java
  subprojects/build-cache/src/main/java/org/gradle/caching/local/internal/H2BuildCacheService.java
  subprojects/build-cache/src/main/java/org/gradle/caching/local/internal/H2BuildCacheServiceFactory.java
  subprojects/build-cache/src/main/java/org/gradle/caching/local/internal/LockOnDemandCrossProcessBuildCacheService.java
  subprojects/build-cache/src/test/groovy/org/gradle/caching/local/internal/H2BuildCacheServiceTest.groovy
  subprojects/persistent-cache/src/main/java/org/gradle/cache/FileLockManager.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/CacheInitializationAction.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/DefaultPersistentDirectoryStore.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/ExclusiveCacheAccessingWorker.java
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/LockOnDemandCrossProcessCacheAccess.java
Labels: @execution

#24849 Add a gradle property for --project-cache-dir
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheDirIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/initialization/StartParameterBuildOptions.java
Labels: from:contributor

#25040 Remove Thread.sleep() in NextGenBuildCacheController
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/NextGenBuildCacheController.java
Labels: @execution, in:build-cache

#25048 Update wrapper to 8.3-20230511225831+0000
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore, @execution

#25062 Ignore BuildCacheNG compileAll for cache misses
  build-logic-commons/gradle-plugin/src/main/kotlin/gradlebuild.cache-miss-monitor.gradle.kts
Labels: @dev-productivity

#25046 Make `DirectoryProperty.(dir|file)` compatible with cc
  subprojects/architecture-test/src/changes/archunit_store/internal-api-nullability.txt
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheProjectLayoutIntegrationTest.groovy
  subprojects/core-api/src/main/java/org/gradle/api/internal/lambdas/SerializableLambdas.java
  subprojects/core-api/src/main/java/org/gradle/api/internal/lambdas/package-info.java
  subprojects/file-collections/src/main/java/org/gradle/api/internal/file/DefaultFilePropertyFactory.java
Labels: in:configuration-cache, @configuration-cache

#25058 Fix ClassCastException in Eclipse WTP
  subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/AbstractIdeIntegrationTest.groovy
  subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/eclipse/EclipseWtpIntegrationTest.groovy
  subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/internal/WtpComponentFactory.java
Labels: 5 min review

#25038 Always pass JAVA_HOME to daemon process
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsKotlinBuildSrcIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/CommandLineIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/AbstractGradleExecuter.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/GradleExecuter.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/InProcessGradleExecuter.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/NoDaemonGradleExecuter.java
  subprojects/internal-testing/src/main/groovy/org/gradle/test/precondition/PreconditionVerifier.groovy
Labels: @dev-productivity

#24663 Implement splitting source-sets in Kotlin DSL reference
  build-logic/build-platform/build.gradle.kts
  build-logic/documentation/src/main/groovy/gradlebuild/docs/GradleBuildDocumentationPlugin.java
  build-logic/documentation/src/main/groovy/gradlebuild/docs/GradleKotlinDslReferencePlugin.java
  gradle/verification-metadata.xml
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DocsDistributionIntegrationSpec.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/GradleBuildExternalPluginsValidationSmokeTest.groovy
Labels: in:kotlin-dsl, a:documentation

#25070 Make AC own the CODEOWNERS file
  .github/CODEOWNERS
Labels: 1 min review

#25066 Update CODEOWNERS based on AC assignments
  .github/CODEOWNERS
Labels: 1 min review

#25068 Update bt-build-scan ownership based on AC assignments
  .github/CODEOWNERS
Labels: 1 min review

#24605 Reactivate tests
  subprojects/tooling-api/src/integTest/groovy/org/gradle/integtests/tooling/ToolingApiIntegrationTest.groovy
Labels: in:tooling-api

#24954 Fix missing example project link on Core Dep Management Doc in User Manual
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DocsDistributionIntegrationSpec.groovy
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/core_dependency_management.adoc
  subprojects/docs/src/docs/userguide/img/dependency-management-resolution.png
  subprojects/docs/src/docs/userguide/img/gradle-core-test-build-scan-dependencies.png
  subprojects/docs/src/snippets/dependencyManagement/introductionCoreDependencies/groovy/build.gradle
  subprojects/docs/src/snippets/dependencyManagement/introductionCoreDependencies/groovy/settings.gradle
  subprojects/docs/src/snippets/dependencyManagement/introductionCoreDependencies/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/introductionCoreDependencies/kotlin/settings.gradle.kts
  subprojects/docs/src/snippets/dependencyManagement/introductionCoreDependencies/tests/dependencyIntroReport.sample.conf
Labels: a:documentation

#25082 Disable compacting and compression for H2 datastore
  subprojects/build-cache/src/main/java/org/gradle/caching/local/internal/H2BuildCacheService.java
Labels: @execution, in:build-cache

#25067 Update gradle/bt-execution ownership based on AC assignments
  .github/CODEOWNERS
Labels: 1 min review

#24973 Update configuration team ownership in CODEOWNERS
  .github/CODEOWNERS
Labels: @configuration-cache

#25100 Update CODEOWNERS for documentation owners
  .github/CODEOWNERS
Labels: 1 min review

#25076 Fix several memory hotspots in dependency resolution
  build-logic/basics/src/main/kotlin/gradlebuild.minify.gradle.kts
  subprojects/dependency-management/build.gradle.kts
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultDependencyManagementServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementBuildScopeServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementBuildTreeScopeServices.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/ResolutionStrategyInternal.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/DefaultConfigurationResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/InMemoryResolutionResultBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/dependencysubstitution/CachingDependencySubstitutionApplicator.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/dependencysubstitution/DefaultDependencySubstitutionApplicator.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/dependencysubstitution/DefaultDependencySubstitutions.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/dependencysubstitution/DependencySubstitutionsInternal.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/ConnectionFailureRepositoryDisabler.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/RepositoryDisabler.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/projectmodule/ProjectArtifactResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolutionstrategy/DefaultResolutionStrategy.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/DefaultArtifactDependencyResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/ResolvedGraphComponent.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ComponentState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ComponentDetailsSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ComponentResultSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ComponentSelectionDescriptorFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/DefaultResolutionResultBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ResolvedComponentVisitor.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/StreamingResolutionResultBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ThisBuildOnlyComponentDetailsSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ThisBuildOnlySelectedVariantSerializer.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ComponentVariant.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/local/model/DefaultLocalComponentGraphResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/DefaultComponentGraphResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/VariantArtifactSelectionCandidates.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/resolver/ArtifactSelector.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/resolver/DefaultArtifactSelector.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/ComponentResultSerializerTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/DefaultResolutionResultBuilderSpec.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/StreamingResolutionResultBuilderTest.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/AllDistributionIntegrationSpec.groovy
Labels: @configuration-cache, in:dependency-resolution

#25083 Update embedded Kotlin from 1.8.20 to 1.8.21
  build-logic/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
  subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/library-versions.properties
  subprojects/docs/src/docs/userguide/compatibility.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_8.adoc
  subprojects/docs/src/samples/build-organization/structuring-software-projects/groovy/platforms/plugins-platform/build.gradle
  subprojects/docs/src/samples/build-organization/structuring-software-projects/kotlin/platforms/plugins-platform/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/androidBuild/kotlin/build.gradle.kts
  subprojects/docs/src/snippets/kotlinDsl/androidSingleBuild/kotlin/build.gradle.kts
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java
Labels: in:kotlin-dsl

#25105 Associate each component in the dependency graph with the correct repository in build operation results
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ResolveConfigurationDependenciesBuildOperationIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/ResolveConfigurationResolutionBuildOperationDetails.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/DynamicVersionResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/ModuleComponentGraphSpecificResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/RepositoryChainComponentMetaDataResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/projectmodule/ProjectDependencyResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ComponentState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ModuleResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/NodeState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/selectors/ComponentStateFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/selectors/SelectorStateResolverResults.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/ComponentGraphResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/ComponentGraphSpecificResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/result/BuildableComponentIdResolveResult.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/result/BuildableComponentResolveResult.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/result/ComponentIdResolveResult.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/result/ComponentResolveResult.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/result/DefaultBuildableComponentIdResolveResult.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/result/DefaultBuildableComponentResolveResult.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/RepositoryChainComponentMetaDataResolverTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/projectmodule/ProjectDependencyResolverTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/DependencyGraphBuilderTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/selectors/SelectorStateResolverTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/query/DefaultArtifactResolutionQueryTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/resolve/result/DefaultBuildableComponentIdResolveResultTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/resolve/result/DefaultBuildableComponentResolveResultTest.groovy
  subprojects/version-control/src/main/java/org/gradle/vcs/internal/resolver/VcsDependencyResolver.java
Labels: @configuration-cache, in:dependency-resolution

#25087 Add Property upgrades interceptors stub
  subprojects/architecture-test/src/changes/archunit_store/internal-api-nullability.txt
  subprojects/core/src/main/java/org/gradle/api/internal/DynamicModulesClassPathProvider.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/GroovyCallInterceptorsProvisionTools.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingTransformer.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/declarations/package-info.java
  subprojects/core/src/main/java/org/gradle/process/internal/worker/child/WorkerProcessClassPathProvider.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/DynamicModulesClassPathProviderTest.groovy
  subprojects/instrumentation-declarations/build.gradle.kts
  subprojects/instrumentation-declarations/src/main/java/org/gradle/internal/instrumentation/property/upgrades/PropertyUpgradesInterceptorStub.java
  subprojects/internal-instrumentation-api/src/main/java/org/gradle/internal/instrumentation/api/declarations/InterceptorDeclaration.java
Labels: @execution, in:provider-api

#25109 Wordsmithing Improvements to "What is Gradle?"
  subprojects/docs/src/docs/userguide/what_is_gradle.adoc
Labels: a:documentation, 1 min review, platform:documentation

#25088 Let config cache support `ArrayDeque` serialization natively
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheSupportedTypesIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/CollectionCodecs.kt
Labels: in:configuration-cache, @configuration-cache, 1 min review

#25119 Don't warn when kotlin projects redundantly set the allowed usage on the test fixtures runtime configuration
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java
  subprojects/plugins/src/integTest/groovy/org/gradle/java/fixtures/AbstractJavaProjectTestFixturesIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/fixtures/AbstractTestFixturesIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/fixtures/JavaLibraryTestFixturesIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/fixtures/JavaTestFixturesIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/fixtures/KotlinTestFixturesIntegrationTest.groovy
Labels: in:testing, in:java-plugins, 20 min review, platform:jvm, platform:software

#25122 for pmd 7 pmd-java and pmd-ant are required
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdPlugin.java
  subprojects/code-quality/src/test/groovy/org/gradle/api/plugins/quality/PmdPluginTest.groovy
Labels: from:contributor

#25138 Set continuation indent to 4 in IntelliJ explicitly
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
Labels: a:chore, @execution

#25120 Fix unnecessary code block in project reports plugin docs
  subprojects/docs/src/docs/userguide/core-plugins/project_report_plugin.adoc
Labels: from:contributor

#25146 Bump kotlin-dsl plugins version
  build-logic/kotlin-dsl/src/main/kotlin/gradlebuild.kotlin-dsl-dependencies-embedded.gradle.kts
  gradle/verification-metadata.xml
  subprojects/kotlin-dsl-plugins/build.gradle.kts
Labels: in:kotlin-dsl

#25151 Update CODEOWNERS for kotlin-dsl
  .github/CODEOWNERS
Labels: in:kotlin-dsl

#25145 Ensure code-quality plugin tool configurations are configured as runtime classpaths
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdPlugin.java
  subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/AbstractCodeQualityPlugin.java
  subprojects/code-quality/src/test/groovy/org/gradle/api/plugins/quality/CheckstylePluginTest.groovy
  subprojects/code-quality/src/test/groovy/org/gradle/api/plugins/quality/CodeNarcPluginTest.groovy
  subprojects/code-quality/src/test/groovy/org/gradle/api/plugins/quality/PmdPluginTest.groovy
Labels: platform:jvm, 5 min review

#24029 README: update logo to switch based on light/dark-mode
  README.md
  gradle-dark-green-primary.png
  gradle-white-primary.png
Labels: from:contributor

#25153 Update copyright year on documentation footer
  subprojects/docs/src/main/resources/footer.html
Labels: a:documentation

#25152 Upgrade master wrapper to latest nightly
  build-logic-commons/gradle-plugin/build.gradle.kts
  gradle/verification-metadata.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: in:kotlin-dsl

#25113 Apply --tests filter to subsequent builds running from config cache
  subprojects/architecture-test/src/changes/archunit_store/internal-api-nullability.txt
  subprojects/base-services/src/main/java/org/gradle/util/Path.java
  subprojects/base-services/src/test/groovy/org/gradle/util/PathTest.groovy
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultBuildController.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultIncludedBuildTaskGraph.java
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/BuildTreeConfigurationCache.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheAwareBuildTreeWorkController.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheIO.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheState.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultConfigurationCache.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/VintageBuildTreeLifecycleControllerFactory.kt
  subprojects/core/src/main/java/org/gradle/composite/internal/BuildController.java
  subprojects/core/src/main/java/org/gradle/execution/EntryTaskSelector.java
  subprojects/core/src/main/java/org/gradle/execution/TaskNameResolvingBuildTaskScheduler.java
  subprojects/core/src/main/java/org/gradle/execution/plan/BuildWorkPlan.java
  subprojects/core/src/main/java/org/gradle/internal/build/BuildWorkGraph.java
  subprojects/core/src/main/java/org/gradle/internal/build/DefaultBuildLifecycleController.java
  subprojects/core/src/main/java/org/gradle/internal/build/DefaultBuildWorkGraphController.java
  subprojects/core/src/main/java/org/gradle/internal/buildtree/BuildTreeWorkGraph.java
  subprojects/core/src/main/java/org/gradle/internal/buildtree/DefaultBuildTreeWorkPreparer.java
  subprojects/tooling-api-builders/src/main/java/org/gradle/tooling/internal/provider/runner/TestExecutionBuildConfigurationAction.java
  subprojects/tooling-api-builders/src/test/groovy/org/gradle/tooling/internal/provider/runner/TestExecutionBuildTaskSchedulerTest.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r76/TestLauncherTestSpecCrossVersionSpec.groovy
Labels: in:testing, in:configuration-cache, @configuration-cache

#25089 Support Providers for IvyPublication artifact notations
  subprojects/architecture-test/src/changes/archunit_store/internal-api-nullability.txt
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/LazyPublishArtifact.java
  subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyPublishArtifactCustomizationIntegTest.groovy
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/artifact/AbstractIvyArtifact.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/artifact/DefaultIvyArtifactSet.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/artifact/IvyArtifactNotationParserFactory.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/artifact/SingleOutputTaskIvyArtifact.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/artifact/package-info.java
  subprojects/ivy/src/test/groovy/org/gradle/api/publish/ivy/internal/artifact/IvyArtifactNotationParserFactoryTest.groovy
  subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishArtifactCustomizationIntegTest.groovy
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/artifact/MavenArtifactNotationParserFactory.java
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/PublicationInternal.java
Labels: 20 min review, platform:software

#25170 Use relative links to major doc sections
  subprojects/docs/src/docs/userguide/about_manual.adoc
Labels: a:documentation, 1 min review, platform:documentation

#25156 Extract logic that calculates diagnostics for a problem into a shared service
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/architecture-test/src/changes/archunit_store/internal-api-nullability.txt
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheProblemReportingIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheStableConfigurationCacheIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheUnsupportedTypesIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/ProcessInBuildScriptIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/ProcessInInitScriptIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/ProcessInPluginBuildScriptIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/process/instrument/ProcessInstrumentationInStaticGroovyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/isolated/IsolatedProjectsAccessFromGroovyDslIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/CrossProjectConfigurationReportingTaskExecutionGraph.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/CrossProjectModelAccessTrackingParentDynamicObject.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ProblemReportingCrossProjectModelAccess.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ReportingTaskDependencyUsageTracker.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/ConfigurationCacheProblemsListener.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/DefaultProblemFactory.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ProblemFactory.kt
  subprojects/configuration-cache/src/test/kotlin/org/gradle/configurationcache/services/ConfigurationCacheEnvironmentChangeTrackerTest.kt
  subprojects/core/src/main/java/org/gradle/initialization/exception/DefaultExceptionAnalyser.java
  subprojects/core/src/main/java/org/gradle/internal/buildtree/BuildTreeScopeServices.java
  subprojects/core/src/main/java/org/gradle/internal/buildtree/InitDeprecationLoggingActionExecutor.java
  subprojects/core/src/main/java/org/gradle/internal/featurelifecycle/ScriptUsageLocationReporter.java
  subprojects/core/src/main/java/org/gradle/internal/problems/DefaultProblemDiagnosticsFactory.java
  subprojects/core/src/main/java/org/gradle/internal/problems/DefaultProblemLocationAnalyzer.java
  subprojects/core/src/main/java/org/gradle/internal/problems/ProblemLocationAnalyzer.java
  subprojects/core/src/main/java/org/gradle/internal/problems/package-info.java
  subprojects/core/src/test/groovy/org/gradle/initialization/exception/DefaultExceptionAnalyserTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/problems/DefaultProblemDiagnosticsFactoryTest.groovy
  subprojects/core/src/test/groovy/org/gradle/testfixtures/ProjectBuilderTest.groovy
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/LauncherServices.java
  subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/SessionFailureReportingActionExecuter.java
  subprojects/logging/build.gradle.kts
  subprojects/logging/src/integTest/groovy/org/gradle/DeprecatedUsageBuildOperationProgressIntegrationTest.groovy
  subprojects/logging/src/main/java/org/gradle/internal/deprecation/DeprecatedFeatureUsage.java
  subprojects/logging/src/main/java/org/gradle/internal/deprecation/DeprecationLogger.java
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/DefaultDeprecatedUsageProgressDetails.java
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/FeatureUsage.java
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/LoggingDeprecatedFeatureHandler.java
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/NoOpProblemDiagnosticsFactory.java
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/StackTraceSanitizer.java
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/package-info.java
  subprojects/logging/src/test/groovy/org/gradle/internal/deprecation/DeprecationLoggerTest.groovy
  subprojects/logging/src/test/groovy/org/gradle/internal/deprecation/DeprecationMessagesTest.groovy
  subprojects/logging/src/test/groovy/org/gradle/internal/deprecation/LoggingDeprecatedFeatureHandlerTest.groovy
  subprojects/logging/src/test/groovy/org/gradle/internal/featurelifecycle/SimulatedJavaCallLocation.java
  subprojects/logging/src/test/groovy/org/gradle/internal/featurelifecycle/SimulatedSingleMessageLogger.java
  subprojects/logging/src/test/groovy/org/gradle/internal/featurelifecycle/StackTraceSanitizerTest.groovy
  subprojects/model-core/src/test/groovy/org/gradle/api/internal/provider/TransformBackedProviderTest.groovy
  subprojects/problems/src/main/java/org/gradle/problems/Location.java
  subprojects/problems/src/main/java/org/gradle/problems/Problem.java
  subprojects/problems/src/main/java/org/gradle/problems/ProblemDiagnostics.java
  subprojects/problems/src/main/java/org/gradle/problems/buildtree/ProblemDiagnosticsFactory.java
  subprojects/problems/src/main/java/org/gradle/problems/package-info.java
  subprojects/tooling-api/src/integTest/groovy/org/gradle/integtests/tooling/ToolingApiClasspathIntegrationTest.groovy
Labels: in:configuration-cache, in:problems

#25167 Add section on binary compatibility checks to CONTRIBUTING
  CONTRIBUTING.md
Labels: a:documentation

#25131 Fix package statement parsing error in Kotlin precompiled scripts
  subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/PrecompiledScriptPluginIntegrationTest.kt
  subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/PrecompiledScriptPlugin.kt
  subprojects/kotlin-dsl-provider-plugins/src/test/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/PrecompiledScriptPluginTest.kt
  subprojects/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/execution/LexerTest.kt
Labels: in:kotlin-dsl

#25116 Add cleanup for H2 based cache
  subprojects/build-cache/src/integTest/groovy/org/gradle/caching/internal/NextGenBuildCacheBuildOperationsIntegrationTest.groovy
  subprojects/build-cache/src/integTest/groovy/org/gradle/caching/local/internal/AbstractBuildCacheCleanupIntegrationTest.groovy
  subprojects/build-cache/src/integTest/groovy/org/gradle/caching/local/internal/DirectoryBuildCacheCleanupIntegrationTest.groovy
  subprojects/build-cache/src/integTest/groovy/org/gradle/caching/local/internal/H2BuildCacheCleanupIntegrationTest.groovy
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/StatefulNextGenBuildCacheService.java
  subprojects/build-cache/src/main/java/org/gradle/caching/local/internal/H2BuildCacheService.java
  subprojects/build-cache/src/main/java/org/gradle/caching/local/internal/H2BuildCacheServiceFactory.java
  subprojects/build-cache/src/main/java/org/gradle/caching/local/internal/LockOnDemandCrossProcessBuildCacheService.java
  subprojects/build-cache/src/main/resources/h2/schemas/org.gradle.caching.local.internal.H2BuildCacheService.sql
  subprojects/build-cache/src/test/groovy/org/gradle/caching/local/internal/H2BuildCacheServiceTest.groovy
Labels: @execution, in:build-cache

#24582 Allow convention mapping to work with Property properties
  subprojects/model-core/src/integTest/groovy/org/gradle/api/provider/ProviderConventionMappingIntegrationTest.groovy
  subprojects/model-core/src/main/java/org/gradle/internal/extensibility/ConventionAwareHelper.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/JavaPropertyReflectionUtil.java
Labels: @execution, in:provider-api

#25183 [Backport] Use compiler API data for incremental compilation after failure
  subprojects/docs/src/docs/userguide/jvm/java_plugin.adoc
  subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
  subprojects/java-compiler-plugin/src/main/java/org/gradle/internal/compiler/java/IncrementalCompileTask.java
  subprojects/java-compiler-plugin/src/main/java/org/gradle/internal/compiler/java/listeners/classnames/ClassNameCollector.java
  subprojects/java-compiler-plugin/src/test/groovy/com/gradle/internal/compiler/java/listeners/ConstantsCollectorTest.groovy
  subprojects/java-compiler-plugin/src/testFixtures/java/org/gradle/internal/compiler/java/TestCompiler.java
  subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/ApiGroovyCompiler.java
  subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/GroovyRecompilationSpecProvider.java
  subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/AggregatingIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/IsolatingIncrementalAnnotationProcessingIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractJavaGroovyIncrementalCompilationSupport.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/BaseIncrementalCompilationAfterFailureIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/CrossTaskGroovyJavaJointIncrementalCompilationIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/CrossTaskIncrementalJavaCompilationIntegrationTest.groovy
  subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/GroovyJavaJointIncrementalCompilationIntegrationTest.groovy
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/ApiCompilerResult.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/CompilationClassBackupService.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/CompilationFailedException.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/CompilationFatalException.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/DefaultJavaCompileSpec.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/IncrementalCompilationAwareJavaCompiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompileSpec.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JdkJavaCompiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JdkTools.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/SelectiveCompiler.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/AbstractRecompilationSpecProvider.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/JavaRecompilationSpecProvider.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/RecompilationSpec.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/RecompilationSpecProvider.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/SourceFileChangeProcessor.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/transaction/CompileTransaction.java
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/reflect/GradleStandardJavaFileManager.java
  subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
  subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/incremental/transaction/CompileTransactionTest.groovy
  subprojects/language-jvm/src/main/java/org/gradle/api/internal/tasks/compile/DefaultJvmLanguageCompileSpec.java
  subprojects/language-jvm/src/main/java/org/gradle/api/internal/tasks/compile/JvmLanguageCompileSpec.java
  subprojects/scala/src/main/java/org/gradle/language/scala/tasks/AbstractScalaCompile.java
Labels: in:groovy-plugin, @execution, in:java-plugins

#25196 Fix build operations emitted for next-gen build cache
  subprojects/build-cache/src/integTest/groovy/org/gradle/caching/internal/NextGenBuildCacheBuildOperationsIntegrationTest.groovy
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/CacheManifest.java
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/DefaultNextGenBuildCacheAccess.java
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/NextGenBuildCacheAccess.java
  subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/NextGenBuildCacheController.java
Labels: @execution

#25090 Account for Gradle 7.6.2 metadata cache layout
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/CacheLayout.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/CacheLayoutTest.groovy
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/dependency_resolution.adoc
  subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/CacheVersionMapping.java
Labels: a:chore

#25216 Apply separate stack trace limits to deprecation logging and configuration cache problems
  subprojects/architecture-test/src/changes/archunit_store/internal-api-nullability.txt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/DefaultProblemFactory.kt
  subprojects/core/src/main/java/org/gradle/internal/problems/DefaultProblemDiagnosticsFactory.java
  subprojects/core/src/test/groovy/org/gradle/internal/problems/DefaultProblemDiagnosticsFactoryTest.groovy
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/LoggingDeprecatedFeatureHandler.java
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/NoOpProblemDiagnosticsFactory.java
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/StackTraceSanitizer.java
  subprojects/logging/src/test/groovy/org/gradle/internal/deprecation/DeprecationLoggerTest.groovy
  subprojects/logging/src/test/groovy/org/gradle/internal/deprecation/DeprecationMessagesTest.groovy
  subprojects/logging/src/test/groovy/org/gradle/internal/deprecation/LoggingDeprecatedFeatureHandlerTest.groovy
  subprojects/problems/src/main/java/org/gradle/problems/buildtree/ProblemDiagnosticsFactory.java
  subprojects/problems/src/main/java/org/gradle/problems/buildtree/ProblemStream.java
  subprojects/problems/src/main/java/org/gradle/problems/buildtree/package-info.java
Labels: in:problems

#25217 Bump wrapper
  gradle/wrapper/gradle-wrapper.properties
Labels: @execution

#25194 Check for lazy properties for ConventionMapping more efficiently
  subprojects/model-core/src/main/java/org/gradle/internal/extensibility/ConventionAwareHelper.java
Labels: @execution, in:provider-api

#25219 Mention plugin compatibility changes in the upgrading guide for 8.2
  subprojects/docs/src/docs/userguide/migration/upgrading_version_8.adoc
Labels: in:kotlin-dsl

#25220 Fix issue with changing environment variables and compiler daemon reuse
  subprojects/architecture-test/src/changes/archunit_store/internal-api-nullability.txt
  subprojects/base-services/src/main/java/org/gradle/internal/jvm/Jvm.java
  subprojects/base-services/src/test/groovy/org/gradle/internal/jvm/AppleJvmTest.groovy
  subprojects/base-services/src/test/groovy/org/gradle/internal/jvm/JvmTest.groovy
  subprojects/core/src/main/java/org/gradle/process/internal/DefaultProcessForkOptions.java
  subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/util/DefaultJavaForkOptionsTest.groovy
  subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/msvcpp/VisualCppPlatformToolProvider.java
  subprojects/scala/src/integTest/groovy/org/gradle/scala/compile/daemon/ScalaCompilerDaemonReuseIntegrationTest.groovy
  subprojects/scala/src/main/java/org/gradle/language/scala/tasks/AbstractScalaCompile.java
Labels: a:bug, in:scala-plugin, 20 min review, platform:jvm, platform:core

#25229 Fix issue where incorrect test filters could be used on a configuration cache hit
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultBuildController.java
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/DefaultIncludedBuildTaskGraph.java
  subprojects/core/src/main/java/org/gradle/composite/internal/BuildController.java
  subprojects/core/src/main/java/org/gradle/execution/EntryTaskSelector.java
  subprojects/core/src/main/java/org/gradle/execution/plan/BuildWorkPlan.java
  subprojects/core/src/main/java/org/gradle/internal/build/BuildWorkGraph.java
  subprojects/core/src/main/java/org/gradle/internal/build/DefaultBuildLifecycleController.java
  subprojects/core/src/main/java/org/gradle/internal/build/DefaultBuildWorkGraphController.java
  subprojects/core/src/main/java/org/gradle/internal/buildtree/BuildTreeWorkGraph.java
  subprojects/tooling-api-builders/src/main/java/org/gradle/tooling/internal/provider/runner/TestExecutionBuildConfigurationAction.java
  subprojects/tooling-api-builders/src/test/groovy/org/gradle/tooling/internal/provider/runner/TestExecutionBuildTaskSchedulerTest.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r76/TestLauncherTestSpecCrossVersionSpec.groovy
Labels: in:tooling-api, @configuration-cache
