Repository gradle/gradle, pull requests merged in 2023-08, with the labels that each got.

#25969 Merge release into master
  released-versions.json
  subprojects/architecture-test/src/changes/archunit_store/internal-api-symmetrical-accessors-nullability.txt
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyTaskChildSpecIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/CopySpecResolver.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/DefaultCopySpec.java
  subprojects/core/src/main/java/org/gradle/api/internal/file/copy/SingleParentCopySpec.java
  subprojects/scala/src/integTest/groovy/org/gradle/integtests/fixtures/ScalaCoverage.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/BaseDeprecations.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/WithAndroidDeprecations.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/WithReportDeprecations.groovy
Labels: 10 min review, platform:jvm, platform:release_coordination

#25970 Update test bucket json
  .teamcity/test-buckets.json
Labels: @dev-productivity

#25952 Make cc debug profile name for fingerprints unique
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheDebugLogIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheIO.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultConfigurationCache.kt
Labels: in:logging, in:configuration-cache, @configuration-cache

#25976 Change failing deprecation warnings to 'maybe'
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidPluginsSmokeTest.groovy
Labels: 1 min review, platform:release_coordination

#25940 Simplify `ScriptClassPathInitializer`
  subprojects/composite-builds/src/main/java/org/gradle/composite/internal/CompositeBuildClassPathInitializer.java
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/fixtures/ToolingApiSpec.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/initialization/DefaultScriptClassPathResolver.java
  subprojects/core/src/main/java/org/gradle/api/internal/initialization/ScriptClassPathInitializer.java
Labels: a:chore, 1 min review

#25937 Ignore test when using config cache
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerExecutorParallelBuildOperationsIntegrationTest.groovy
Labels: a:chore, in:workers, 1 min review, platform:execution

#25928 docs: View and Debug Dependencies: add a note about `buildEnvironment`
  subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/viewing_debugging_dependencies.adoc
  subprojects/docs/src/docs/userguide/reference/command_line_interface.adoc
Labels: a:documentation, from:contributor

#25918 Consolidate Ivy version mapping and project resolution
  subprojects/architecture-test/src/changes/archunit_store/internal-api-nullability.txt
  subprojects/core/src/main/java/org/gradle/api/internal/component/SoftwareComponentInternal.java
  subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyPublishJavaIntegTest.groovy
  subprojects/ivy/src/integTest/groovy/org/gradle/api/publish/ivy/IvyPublishMultiProjectIntegTest.groovy
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/IvyDependency.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/artifact/AbstractIvyArtifact.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/artifact/ArchiveTaskBasedIvyArtifact.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/artifact/FileBasedIvyArtifact.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/artifact/IvyArtifactInternal.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/artifact/IvyArtifactNotationParserFactory.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/artifact/NormalizedIvyArtifact.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/artifact/PublishArtifactBasedIvyArtifact.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/artifact/SingleOutputTaskIvyArtifact.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/dependency/DefaultIvyDependency.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/dependency/DefaultIvyDependencySet.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/dependency/DefaultIvyProjectDependency.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/dependency/IvyDependency.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/dependency/IvyDependencyInternal.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publication/DefaultIvyModuleDescriptorAuthor.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publication/DefaultIvyModuleDescriptorDescription.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publication/DefaultIvyModuleDescriptorLicense.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publication/DefaultIvyModuleDescriptorSpec.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publication/DefaultIvyPublication.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publication/DefaultIvyPublicationIdentity.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publication/IvyComponentParser.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publication/IvyModuleDescriptorSpecInternal.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publication/IvyPublicationInternal.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publisher/DefaultReadOnlyIvyPublicationIdentity.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publisher/DependencyResolverIvyPublisher.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publisher/IvyNormalizedPublication.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publisher/IvyPublicationCoordinates.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publisher/ValidatingIvyPublisher.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/tasks/IvyDescriptorFileGenerator.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/tasks/package-info.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/plugins/IvyPublishPlugin.java
  subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/tasks/GenerateIvyDescriptor.java
  subprojects/ivy/src/test/groovy/org/gradle/api/publish/ivy/internal/artifact/IvyArtifactNotationParserFactoryTest.groovy
  subprojects/ivy/src/test/groovy/org/gradle/api/publish/ivy/internal/publication/DefaultIvyModuleDescriptorSpecTest.groovy
  subprojects/ivy/src/test/groovy/org/gradle/api/publish/ivy/internal/publication/DefaultIvyPublicationTest.groovy
  subprojects/ivy/src/test/groovy/org/gradle/api/publish/ivy/internal/publisher/IvyDescriptorFileGeneratorTest.groovy
  subprojects/ivy/src/test/groovy/org/gradle/api/publish/ivy/internal/publisher/ValidatingIvyPublisherTest.groovy
  subprojects/ivy/src/test/groovy/org/gradle/api/publish/ivy/plugins/IvyPublishPluginTest.groovy
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/DefaultMavenPublication.java
  subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/MavenComponentParser.java
  subprojects/publish/src/main/java/org/gradle/api/publish/internal/component/DefaultAdhocSoftwareComponent.java
Labels: 30 min review, platform:software

#25968 Fix configuration cache debug log for space usage analysis
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheDebugLogIntegrationTest.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheIO.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultConfigurationCache.kt
Labels: in:configuration-cache, @configuration-cache

#25995 Adjust smoke tests for AGP usage of deprecated GUtil once per Gradle daemon
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractAndroidSantaTrackerSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/BaseDeprecations.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/WithAndroidDeprecations.groovy
Labels: a:chore

#26001 Update release notes for 8.3 RC3
  subprojects/docs/src/docs/release/notes.md
Labels: a:chore

#25878 Improve List/Set/Map property upgrades and implement multi-value property views
  subprojects/internal-instrumentation-processor/src/main/java/org/gradle/internal/instrumentation/extensions/property/PropertyUpgradeAnnotatedMethodReader.java
  subprojects/internal-instrumentation-processor/src/main/java/org/gradle/internal/instrumentation/extensions/property/PropertyUpgradeClassSourceGenerator.java
  subprojects/internal-instrumentation-processor/src/main/java/org/gradle/internal/instrumentation/extensions/property/PropertyUpgradeRequestExtra.java
  subprojects/internal-instrumentation-processor/src/test/groovy/org/gradle/internal/instrumentation/extensions/property/PropertyUpgradeCodeGenTest.groovy
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/views/ListPropertyListView.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/views/MapPropertyMapView.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/views/SetPropertySetView.java
  subprojects/model-core/src/main/java/org/gradle/api/internal/provider/views/package-info.java
  subprojects/model-core/src/test/groovy/org/gradle/api/internal/provider/views/AbstractHasMultiValuesPropertyCollectionViewTest.groovy
  subprojects/model-core/src/test/groovy/org/gradle/api/internal/provider/views/ListPropertyListViewTest.groovy
  subprojects/model-core/src/test/groovy/org/gradle/api/internal/provider/views/MapPropertyMapViewTest.groovy
  subprojects/model-core/src/test/groovy/org/gradle/api/internal/provider/views/SetPropertySetViewTest.groovy
Labels: @execution, p:lazy-migration

#25776 Dependency locking - better error handling when lockfile is corrupted
  subprojects/dependency-management/src/main/java/org/gradle/internal/locking/LockFileReaderWriter.java
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/locking/LockFileReaderWriterTest.groovy
Labels: from:contributor

#25860 Normalize archives before instrumenting
  subprojects/core/src/integTest/groovy/org/gradle/internal/classpath/BuildScriptClasspathIntegrationSpec.groovy
  subprojects/core/src/main/java/org/gradle/internal/classpath/ClasspathFileHasher.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/DefaultCachedClasspathTransformer.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentingClasspathFileTransformer.java
  subprojects/core/src/test/groovy/org/gradle/internal/classpath/DefaultCachedClasspathTransformerTest.groovy
  subprojects/core/src/test/groovy/org/gradle/internal/classpath/InstrumentingClasspathFileTransformerTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/ArtifactBuilder.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/GradleBackedArtifactBuilder.java
Labels: @configuration-cache

#23457 Let 'init' put convention plugins into "build-logic" dir while migrating maven projects with incubating.
  subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/MavenConversionIntegrationTest.groovy
  subprojects/build-init/src/main/java/org/gradleinternal/buildinit/plugins/internal/maven/Maven2Gradle.java
Labels: in:build-init-plugin, in:maven-integration, from:contributor

#26005 Update wrapper following 8.3 RC3 release
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore

#25993 providing actionable guidance in MissingLockStateException
  subprojects/dependency-management/src/main/java/org/gradle/internal/locking/MissingLockStateException.java
  subprojects/dependency-management/src/test/groovy/org/gradle/internal/locking/DefaultDependencyLockingProviderTest.groovy
Labels: from:contributor

#25991 Move configuration metadata logic to builder
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/metadata/ProjectMetadataController.kt
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/moduleconverter/dependencies/DefaultLocalConfigurationMetadataBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractConfigurationMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractVariantBackedConfigurationMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/LazyRuleAwareWithBaseConfigurationMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/local/model/DefaultLocalComponentMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/local/model/DefaultLocalConfigurationMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/local/model/LocalConfigurationMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/local/model/LocalVariantMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/ConfigurationMetadata.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/DependencyGraphBuilderTest.groovy
Labels: 10 min review, platform:software, platform:configuration_cache

#26008 Remove exception from Javadoc on getAlltasks() in TaskExecutionGraph
  subprojects/core-api/src/main/java/org/gradle/api/execution/TaskExecutionGraph.java
Labels: a:documentation

#26002 Don't inspect syntethic classes for ArchUnit non-nullability test
  subprojects/architecture-test/src/changes/archunit_store/internal-api-nullability.txt
  subprojects/architecture-test/src/changes/archunit_store/public-api-mutable-properties.txt
  subprojects/architecture-test/src/changes/archunit_store/stored.rules
  subprojects/architecture-test/src/test/java/org/gradle/architecture/test/ArchUnitFixture.java
  subprojects/architecture-test/src/test/java/org/gradle/architecture/test/InternalNullabilityTest.java
Labels: a:chore, @execution

#26010 Merge `release` into `master`
  released-versions.json
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractAndroidSantaTrackerSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AndroidPluginsSmokeTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/BaseDeprecations.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/WithAndroidDeprecations.groovy
Labels: a:chore

#26012 [Doc-only] Adjust wording about CC in the "build performance" doc
  subprojects/docs/src/docs/userguide/running-builds/performance.adoc
Labels: a:documentation

#26014 Introduce JetBrains as a known JVM vendor.
  platforms/jvm/toolchains-jvm/src/main/java/org/gradle/jvm/toolchain/JvmVendorSpec.java
  subprojects/docs/src/docs/release/notes.md
  subprojects/docs/src/docs/userguide/jvm/toolchains.adoc
  subprojects/jvm-services/src/main/java/org/gradle/internal/jvm/inspection/JvmVendor.java
Labels: in:toolchains, from:contributor

#26017 Add basic integration testing infrastructure for validating Problem event emissions
  subprojects/build-cache/src/integTest/groovy/org/gradle/caching/NextGenBuildCacheIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheGroovyClosureIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/CrossProcessFileLockIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/FinalizerTaskIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/UndefinedBuildExecutionIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/services/BuildServiceParallelExecutionIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/ConcurrentBuildsIncrementalBuildIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/bundling/ConcurrentArchiveIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/BuildInitializationBuildOperationsIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/CalculateTaskGraphBuildOperationIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/InternalGradleFailuresIntegrationTest.groovy
  subprojects/core/src/integTest/groovy/org/gradle/initialization/LoadBuildStructureBuildOperationIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/caching/ConcurrentBuildsCachingIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformParallelIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ConcurrentBuildsArtifactTransformIntegrationTest.groovy
  subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/BuildSourceBuilderIntegrationTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractIntegrationSpec.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractTaskRelocationIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/CommandLineIntegrationSpec.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/GradleConfigurabilityIntegrationSpec.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/StacktraceIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/SupportedBuildJvmIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/cli/NotificationsIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/DaemonFeedbackIntegrationSpec.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/DaemonLifecycleSpec.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/DaemonReportStatusIntegrationSpec.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/DaemonReuseIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/ProcessCrashHandlingIntegrationTest.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/StoppingDaemonIntegrationSpec.groovy
  subprojects/launcher/src/integTest/groovy/org/gradle/launcher/daemon/server/health/gc/GarbageCollectionMonitoringIntegrationTest.groovy
  subprojects/persistent-cache/src/integTest/groovy/org/gradle/cache/internal/DefaultFileLockManagerContentionIntegrationTest.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/impldeps/GradleImplDepsConcurrencyIntegrationTest.groovy
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/daemon/JavaCompilerDaemonFailureIntegrationTest.groovy
  subprojects/testing-base/src/integTest/groovy/org/gradle/testing/TestExecutionBuildOperationsContinuousIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junit/AbstractJUnitTestFailureIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/junit/junit4/AbstractJUnit4TestFailureIntegrationTest.groovy
  subprojects/version-control/src/integTest/groovy/org/gradle/vcs/internal/ParallelSourceDependencyIntegrationTest.groovy
  subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperSupportedBuildJvmIntegrationTest.groovy
Labels: platform:jvm, 5 min review, platform:software, platform:extensibility, platform:core, platform:execution, platform:build_infrastructure, platform:bt_ge_build_cache, platform:configuration_cache

#26022 Adjust `KnownJvmVendor.JETBRAINS` to use common name instead of legal one
  subprojects/jvm-services/src/main/java/org/gradle/internal/jvm/inspection/JvmVendor.java
Labels: in:toolchains, from:contributor

#26024 Fix grouping per owner of method instruction for generated JvmBytecodeCallInterceptor
  subprojects/internal-instrumentation-processor/src/main/java/org/gradle/internal/instrumentation/model/CallableOwnerInfo.java
  subprojects/internal-instrumentation-processor/src/test/groovy/org/gradle/internal/instrumentation/extensions/property/PropertyUpgradeCodeGenTest.groovy
  subprojects/internal-instrumentation-processor/src/test/groovy/org/gradle/internal/instrumentation/processor/codegen/jvmbytecode/InterceptJvmCallsGeneratorTest.groovy
Labels: @execution, p:lazy-migration

#26023 Fix typos in Javadoc
  subprojects/core/src/main/java/org/gradle/api/internal/file/archive/AbstractArchiveFileTreeElement.java
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/plugins/ide/tooling/r33/BuildActionCompositeBuildCrossVersionSpec.groovy
Labels: a:documentation, from:contributor

#26028 Ensure the preconditions have a consistent order
  subprojects/internal-testing/src/main/groovy/org/gradle/test/precondition/PredicatesFile.java
Labels: 1 min review, platform:build_infrastructure

#25927 Use Windows system commit to limit workers
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/health/LowMemoryDaemonExpirationStrategy.java
  subprojects/launcher/src/test/groovy/org/gradle/launcher/daemon/server/health/LowMemoryDaemonExpirationStrategyTest.groovy
  subprojects/native/src/main/java/org/gradle/internal/nativeintegration/services/NativeServices.java
  subprojects/process-services/src/integTest/groovy/org/gradle/process/internal/health/memory/DefaultOsMemoryInfoIntegrationTest.groovy
  subprojects/process-services/src/main/java/org/gradle/process/internal/health/memory/DefaultAvailableOsMemoryStatusAspect.java
  subprojects/process-services/src/main/java/org/gradle/process/internal/health/memory/DefaultMemoryManager.java
  subprojects/process-services/src/main/java/org/gradle/process/internal/health/memory/DefaultOsMemoryInfo.java
  subprojects/process-services/src/main/java/org/gradle/process/internal/health/memory/DefaultUnavailableOsMemoryStatusAspect.java
  subprojects/process-services/src/main/java/org/gradle/process/internal/health/memory/MBeanOsMemoryInfo.java
  subprojects/process-services/src/main/java/org/gradle/process/internal/health/memory/OsMemoryStatus.java
  subprojects/process-services/src/main/java/org/gradle/process/internal/health/memory/OsMemoryStatusAspect.java
  subprojects/process-services/src/main/java/org/gradle/process/internal/health/memory/OsMemoryStatusSnapshot.java
  subprojects/process-services/src/main/java/org/gradle/process/internal/health/memory/WindowsOsMemoryInfo.java
  subprojects/process-services/src/test/groovy/org/gradle/process/internal/health/memory/CGroupMemoryInfoTest.groovy
  subprojects/process-services/src/test/groovy/org/gradle/process/internal/health/memory/DefaultMemoryManagerTest.groovy
  subprojects/process-services/src/test/groovy/org/gradle/process/internal/health/memory/DefaultOsMemoryInfoTest.groovy
  subprojects/process-services/src/test/groovy/org/gradle/process/internal/health/memory/MemInfoOsMemoryInfoTest.groovy
  subprojects/soak/build.gradle.kts
  subprojects/soak/src/integTest/groovy/org/gradle/workers/internal/WorkerPruningSoakTest.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerDaemonExpirationIntegrationTest.groovy
  subprojects/workers/src/main/java/org/gradle/workers/internal/WorkerDaemonClientsManager.java
Labels: a:feature, in:workers, build-script-change, 30 min review, platform:core, platform:execution, platform:release_coordination

#26032 docs: Fix typo in "subprojects"
  subprojects/docs/src/docs/userguide/authoring-builds/multi-project/sharing_build_logic_between_subprojects.adoc
Labels: from:contributor

#25895 Add `@LeaksFileHandles` to a few tests
  subprojects/build-cache-http/src/integTest/groovy/org/gradle/caching/NextGenBuildCacheHttpIntegrationTest.groovy
  subprojects/build-cache/src/integTest/groovy/org/gradle/caching/NextGenBuildCacheIntegrationTest.groovy
  subprojects/build-cache/src/integTest/groovy/org/gradle/caching/internal/NextGenBuildCacheBuildOperationsIntegrationTest.groovy
  subprojects/build-cache/src/test/groovy/org/gradle/caching/internal/controller/NextGenBuildCacheControllerTest.groovy
Labels: @dev-productivity, 1 min review, platform:execution, platform:bt_ge_build_cache

#26033 Remove usage of Java14HomeAvailable requirement
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/preconditions/IntegTestPreconditions.groovy
  subprojects/internal-testing/src/main/resources/valid-precondition-combinations.csv
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/BasicJavaCompilerIntegrationSpec.groovy
Labels: 1 min review, platform:jvm, platform:build_infrastructure

#26034 Allow nested types with kotlinx package
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/NestedInputIntegrationTest.groovy
  subprojects/model-core/src/main/java/org/gradle/internal/properties/annotations/NestedValidationUtil.java
  subprojects/model-core/src/testFixtures/groovy/org/gradle/internal/reflect/validation/ValidationMessageChecker.groovy
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidatePluginsIntegrationTest.groovy
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractKotlinPluginSmokeTest.groovy
Labels: @execution, in:work-validation, 5 min review, platform:extensibility, platform:release_coordination, platform:configuration_cache

#26038 Update gitStream catagories to match CODEOWNERS as of today
  .cm/change_categories.cm
  .github/CODEOWNERS
Labels: cm-changes

#26040 Remove WindowsMemory registration, check-cast instead
  subprojects/distributions-dependencies/build.gradle.kts
  subprojects/native/src/main/java/org/gradle/internal/nativeintegration/services/NativeServices.java
  subprojects/process-services/src/main/java/org/gradle/process/internal/health/memory/WindowsOsMemoryInfo.java
Labels: a:regression, 1 min review, build-script-change, platform:release_coordination

#25994 Update Tutorial section for the Gradle BT manual
  subprojects/docs/src/docs/userguide/img/tutorial/intellij-idea-dep-man.png
  subprojects/docs/src/docs/userguide/img/tutorial/project-structure.png
  subprojects/docs/src/docs/userguide/tutorial/part1_gradle_init.adoc
  subprojects/docs/src/docs/userguide/tutorial/part2_gradle_tasks.adoc
  subprojects/docs/src/docs/userguide/tutorial/part3_gradle_dep_man.adoc
  subprojects/docs/src/docs/userguide/tutorial/part4_gradle_plugins.adoc
  subprojects/docs/src/docs/userguide/tutorial/part5_gradle_inc_builds.adoc
  subprojects/docs/src/docs/userguide/tutorial/part6_gradle_caching.adoc
  subprojects/docs/src/docs/userguide/tutorial/part7_gradle_refs.adoc
Labels: a:documentation

#25983 Simplify test task state to make it CC-friendly
  subprojects/plugins/src/test/groovy/org/gradle/api/tasks/testing/TestTaskSpec.groovy
  subprojects/testing-base/src/main/java/org/gradle/api/tasks/testing/AbstractTestTask.java
Labels: in:testing, @configuration-cache

#26027 Fix rendering issues and incompleteness of Single Page guide (HTML/PDF) in the User Manual
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/AllDistributionIntegrationSpec.groovy
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DocsDistributionIntegrationSpec.groovy
  subprojects/docs/src/docs/userguide/reference/directory_layout.adoc
  subprojects/docs/src/docs/userguide/troubleshooting.adoc
  subprojects/docs/src/docs/userguide/userguide_single.adoc
Labels: a:documentation

#26011 Try harder to Delete Files on Windows
  subprojects/files/src/main/java/org/gradle/internal/file/impl/DefaultDeleter.java
  subprojects/files/src/test/groovy/org/gradle/internal/file/impl/DefaultDeleterTest.groovy
Labels: in:file-tasks, from:contributor

#26025 Drop support for complex event broadcasting types
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheIO.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/ListenerBroadcastCodec.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/UnsupportedTypesCodecs.kt
  subprojects/configuration-cache/src/test/kotlin/org/gradle/configurationcache/serialization/codecs/AbstractUserTypeCodecTest.kt
Labels: in:configuration-cache, @configuration-cache

#26046 Make severity optional in Problems API
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/flow/FlowParametersInstantiator.kt
  subprojects/core/src/main/java/org/gradle/api/internal/catalog/parser/TomlCatalogFileParser.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/AbstractValidatingProperty.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/ValidationActions.java
  subprojects/core/src/main/java/org/gradle/execution/DefaultTaskSelector.java
  subprojects/core/src/main/java/org/gradle/execution/plan/MissingTaskDependencyDetector.java
  subprojects/core/src/main/java/org/gradle/groovy/scripts/internal/DefaultScriptCompilationHandler.java
  subprojects/core/src/main/java/org/gradle/internal/operations/BuildOperationProxyFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransform.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/DefaultVersionCatalogBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/LibrariesSourceGenerator.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/model/annotations/AbstractInputFilePropertyAnnotationHandler.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/model/annotations/AbstractInputPropertyAnnotationHandler.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/model/annotations/InputPropertyAnnotationHandler.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/model/annotations/ServiceReferencePropertyAnnotationHandler.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ValidateStep.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/validation/ValidationProblemPropertyAnnotationHandler.java
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/LoggingDeprecatedFeatureHandler.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/annotations/AbstractTypeAnnotationHandler.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/annotations/DefaultTypeMetadataStore.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/annotations/NestedValidationUtil.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/annotations/impl/DefaultTypeAnnotationMetadataStore.java
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/internal/ValidateAction.java
  subprojects/problems/src/main/java/org/gradle/api/problems/NoOpProblems.java
  subprojects/problems/src/main/java/org/gradle/api/problems/Problems.java
  subprojects/problems/src/main/java/org/gradle/api/problems/interfaces/ProblemBuilder.java
  subprojects/problems/src/main/java/org/gradle/api/problems/interfaces/ProblemBuilderDefiningLocation.java
  subprojects/problems/src/main/java/org/gradle/api/problems/interfaces/ProblemBuilderDefiningSeverity.java
  subprojects/problems/src/main/java/org/gradle/api/problems/internal/DefaultProblem.java
  subprojects/problems/src/main/java/org/gradle/api/problems/internal/DefaultProblemBuilder.java
  subprojects/problems/src/main/java/org/gradle/api/problems/internal/DefaultProblems.java
Labels: 20 min review, platform:software, platform:extensibility, platform:build_infrastructure, platform:configuration_cache, platform:core_execution

#25875 Implement recursive assertion error mapping.
  subprojects/testing-junit-platform/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestExecutionListener.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/failure/DefaultThrowableToTestFailureMapper.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/failure/TestFailureMapper.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/failure/ThrowableToTestFailureMapper.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/failure/mappers/AssertErrorMapper.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/failure/mappers/AssertjMultipleAssertionsErrorMapper.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/failure/mappers/JUnitComparisonTestFailureMapper.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/failure/mappers/OpenTestAssertionFailedMapper.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/failure/mappers/OpenTestMultipleFailuresErrorMapper.java
  subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitTestEventAdapter.java
  subprojects/testing-jvm-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/failure/mappers/AssertjMultipleAssertionsErrorMapperTest.groovy
  subprojects/testing-jvm-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/failure/mappers/JUnitComparisonTestFailureMapperTest.groovy
  subprojects/testing-jvm-infrastructure/src/test/groovy/org/gradle/api/internal/tasks/testing/failure/mappers/OpenTestMultipleFailuresMapperTestError.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r83/TestFailureProgressEventCrossVersionTest.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r84/TestFailureProgressEventCrossVersionTest.groovy
  subprojects/tooling-api/src/testFixtures/groovy/org/gradle/integtests/tooling/fixture/TestFailureSpecification.groovy
Labels: 30 min review, platform:jvm, platform:ide

#26055 Clarify build logic external library isolation
  subprojects/docs/src/docs/userguide/developing-plugins/designing_gradle_plugins.adoc
Labels: in:plugin-development, a:documentation

#26059 Improve naming in Problems API
  subprojects/build-events/src/main/java/org/gradle/internal/build/event/types/DefaultProblemEvent.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/ProblemRecordingTypeValidationContext.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/validation/DefaultTypeAwareProblemBuilder.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/validation/TypeValidationProblemRenderer.java
  subprojects/problems/src/main/java/org/gradle/api/problems/interfaces/Problem.java
  subprojects/problems/src/main/java/org/gradle/api/problems/interfaces/ProblemBuilder.java
  subprojects/problems/src/main/java/org/gradle/api/problems/internal/DefaultProblem.java
  subprojects/problems/src/main/java/org/gradle/api/problems/internal/DefaultProblemBuilder.java
  subprojects/tooling-api-builders/src/main/java/org/gradle/tooling/internal/provider/runner/ProblemsProgressEventConsumer.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/events/problems/ProblemDescriptor.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/events/problems/internal/DefaultProblemsOperationDescriptor.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/parameters/BuildProgressListenerAdapter.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/protocol/InternalProblemEvent.java
Labels: 5 min review, platform:ide, platform:configuration_cache

#26063 Re-enable persistent compiler daemons on Windows
  subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/DaemonJavaCompiler.java
  subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/daemon/JavaCompilerDaemonReuseIntegrationTest.groovy
  subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerDaemonLifecycleTest.groovy
Labels: a:feature, in:workers, in:java-plugins, 1 min review, platform:jvm, platform:core_execution

#26083 Fix failing PropertyUpgradesBinaryCompatibilityCrossVersionSpec
  subprojects/core/src/main/java/org/gradle/configuration/DefaultImportsReader.java
  subprojects/integ-test/src/crossVersionTest/groovy/org/gradle/integtests/AbstractPropertyUpgradesBinaryCompatibilityCrossVersionSpec.groovy
Labels: 1 min review

#26073 Remove `init` method from the Problems service API
  subprojects/configuration-cache/src/test/kotlin/org/gradle/configurationcache/ConfigurationCacheKeyTest.kt
  subprojects/core/src/main/java/org/gradle/internal/buildtree/InitProblems.java
  subprojects/problems/src/main/java/org/gradle/api/problems/Problems.java
Labels: 1 min review, platform:configuration_cache

#26069 Fix repeated dynamic invocations not intercepted in Groovy
  subprojects/core/src/main/java/org/gradle/internal/classpath/InstrumentedClosuresTracker.java
  subprojects/core/src/main/java/org/gradle/internal/classpath/intercept/CallInterceptorsSet.java
  subprojects/core/src/test/groovy/org/gradle/internal/classpath/GroovyDynamicDispatchingInterceptingTest.groovy
Labels: in:configuration-cache

#25360 Show why configuration cache test is ignored
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/UnsupportedWithConfigurationCacheRule.groovy
Labels: @execution, stale

#26099 Fix flaky JavaCompileParallelIntegrationTest
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileParallelIntegrationTest.groovy
Labels: 1 min review, platform:jvm

#25379 Fix flaky AutoConsoleBuildResultReportingFunctionalTest
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/taskgrouping/AbstractConsoleBuildResultFunctionalTest.groovy
Labels: 1 min review

#25788 Add source links to Kotlin DSL Reference docs
  build-logic/basics/src/main/kotlin/gradlebuild/basics/BuildEnvironment.kt
  build-logic/build-platform/build.gradle.kts
  build-logic/documentation/src/main/groovy/gradlebuild/docs/GradleBuildDocumentationPlugin.java
  build-logic/documentation/src/main/groovy/gradlebuild/docs/GradleDocumentationExtension.java
  build-logic/documentation/src/main/groovy/gradlebuild/docs/GradleKotlinDslReferencePlugin.java
  gradle/verification-metadata.xml
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/DocsDistributionIntegrationSpec.groovy
  subprojects/docs/src/docs/release/notes.md
Labels: in:kotlin-dsl

#26074 add "ADVICE" severity
  subprojects/problems/src/main/java/org/gradle/api/problems/interfaces/DocLink.java
  subprojects/problems/src/main/java/org/gradle/api/problems/interfaces/Problem.java
  subprojects/problems/src/main/java/org/gradle/api/problems/interfaces/ProblemBuilder.java
  subprojects/problems/src/main/java/org/gradle/api/problems/interfaces/Severity.java
Labels: 1 min review

#26082 Move Gradle Enterprise plugin services to correct service scope
  platforms/enterprise/enterprise/src/main/java/org/gradle/internal/enterprise/impl/GradleEnterprisePluginServices.java
Labels: in:build-scan

#26072 Change order of the PropertyBuilder, so `message` is the first one in the sequence
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/flow/FlowParametersInstantiator.kt
  subprojects/core/src/main/java/org/gradle/api/internal/catalog/parser/TomlCatalogFileParser.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/AbstractValidatingProperty.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/ValidationActions.java
  subprojects/core/src/main/java/org/gradle/execution/DefaultTaskSelector.java
  subprojects/core/src/main/java/org/gradle/execution/plan/MissingTaskDependencyDetector.java
  subprojects/core/src/main/java/org/gradle/groovy/scripts/internal/DefaultScriptCompilationHandler.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransform.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/DefaultVersionCatalogBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/LibrariesSourceGenerator.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/model/annotations/AbstractInputFilePropertyAnnotationHandler.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/model/annotations/AbstractInputPropertyAnnotationHandler.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/model/annotations/InputPropertyAnnotationHandler.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/model/annotations/ServiceReferencePropertyAnnotationHandler.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ValidateStep.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/validation/ValidationProblemPropertyAnnotationHandler.java
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/LoggingDeprecatedFeatureHandler.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/annotations/AbstractTypeAnnotationHandler.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/annotations/DefaultTypeMetadataStore.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/annotations/NestedValidationUtil.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/annotations/impl/DefaultTypeAnnotationMetadataStore.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/validation/TypeAwareProblemBuilder.java
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/internal/ValidateAction.java
  subprojects/problems/src/main/java/org/gradle/api/problems/NoOpProblems.java
  subprojects/problems/src/main/java/org/gradle/api/problems/Problems.java
  subprojects/problems/src/main/java/org/gradle/api/problems/interfaces/ProblemBuilderDefiningLocation.java
  subprojects/problems/src/main/java/org/gradle/api/problems/interfaces/ProblemBuilderDefiningMessage.java
  subprojects/problems/src/main/java/org/gradle/api/problems/internal/DefaultProblemBuilder.java
  subprojects/problems/src/main/java/org/gradle/api/problems/internal/DefaultProblems.java
Labels: 10 min review, platform:software, platform:extensibility, platform:build_infrastructure, platform:configuration_cache, platform:core_execution

#26084 Remove location information from Problem data structures
  subprojects/build-events/src/main/java/org/gradle/internal/build/event/types/DefaultProblemEvent.java
  subprojects/tooling-api-builders/src/main/java/org/gradle/tooling/internal/provider/runner/ProblemsProgressEventConsumer.java
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r83/ProblemProgressEventCrossVersionTest.groovy
  subprojects/tooling-api/src/main/java/org/gradle/tooling/events/problems/ProblemDescriptor.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/events/problems/internal/DefaultProblemsOperationDescriptor.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/parameters/BuildProgressListenerAdapter.java
  subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/protocol/InternalProblemEvent.java
Labels: 1 min review, platform:ide

#26123 Merge release into master
  released-versions.json
Labels: 1 min review

#26109 Document Configuration attribute behavior in upgrade guide
  subprojects/docs/src/docs/userguide/migration/upgrading_version_8.adoc
Labels: a:documentation, 1 min review, platform:documentation

#26105 Rename `message` to `label` and `description` to `details`
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/flow/FlowParametersInstantiator.kt
  subprojects/core/src/main/java/org/gradle/api/internal/catalog/parser/TomlCatalogFileParser.java
  subprojects/core/src/main/java/org/gradle/api/internal/catalog/problems/DefaultCatalogProblemBuilder.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/AbstractValidatingProperty.java
  subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/ValidationActions.java
  subprojects/core/src/main/java/org/gradle/execution/DefaultTaskSelector.java
  subprojects/core/src/main/java/org/gradle/execution/plan/MissingTaskDependencyDetector.java
  subprojects/core/src/main/java/org/gradle/groovy/scripts/internal/DefaultScriptCompilationHandler.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransform.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/DefaultVersionCatalogBuilder.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/LibrariesSourceGenerator.java
  subprojects/execution/src/integTest/groovy/org/gradle/internal/execution/IncrementalExecutionIntegrationTest.groovy
  subprojects/execution/src/main/java/org/gradle/internal/execution/model/annotations/AbstractInputFilePropertyAnnotationHandler.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/model/annotations/AbstractInputPropertyAnnotationHandler.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/model/annotations/InputPropertyAnnotationHandler.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/model/annotations/ServiceReferencePropertyAnnotationHandler.java
  subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ValidateStep.java
  subprojects/execution/src/test/groovy/org/gradle/internal/execution/steps/ValidateStepTest.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/validation/ValidationProblemPropertyAnnotationHandler.java
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/LoggingDeprecatedFeatureHandler.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/annotations/AbstractTypeAnnotationHandler.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/annotations/DefaultTypeMetadataStore.java
  subprojects/model-core/src/main/java/org/gradle/internal/properties/annotations/NestedValidationUtil.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/annotations/impl/DefaultTypeAnnotationMetadataStore.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/validation/TypeAwareProblemBuilder.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/validation/TypeValidationProblemRenderer.java
  subprojects/model-core/src/test/groovy/org/gradle/internal/properties/annotations/DefaultTypeMetadataStoreTest.groovy
  subprojects/model-core/src/testFixtures/groovy/org/gradle/internal/reflect/annotations/TestAnnotationHandlingSupport.groovy
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/internal/ValidateAction.java
  subprojects/problems/src/main/java/org/gradle/api/problems/NoOpProblems.java
  subprojects/problems/src/main/java/org/gradle/api/problems/Problems.java
  subprojects/problems/src/main/java/org/gradle/api/problems/interfaces/Problem.java
  subprojects/problems/src/main/java/org/gradle/api/problems/interfaces/ProblemBuilder.java
  subprojects/problems/src/main/java/org/gradle/api/problems/interfaces/ProblemBuilderDefiningLabel.java
  subprojects/problems/src/main/java/org/gradle/api/problems/internal/DefaultProblem.java
  subprojects/problems/src/main/java/org/gradle/api/problems/internal/DefaultProblemBuilder.java
  subprojects/problems/src/main/java/org/gradle/api/problems/internal/DefaultProblems.java
  subprojects/problems/src/test/groovy/org/gradle/api/problems/internal/DefaultProblemBuilderTest.groovy
  subprojects/tooling-api-builders/src/main/java/org/gradle/tooling/internal/provider/runner/ProblemsProgressEventConsumer.java
Labels: 20 min review, platform:software, platform:extensibility, platform:ide, platform:build_infrastructure, platform:configuration_cache, platform:core_execution

#26119 Replace LGPL licensed Checkstyle XSLT with Apache licensed version
  platforms/jvm/code-quality/build.gradle.kts
  platforms/jvm/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginHtmlReportIntegrationTest.groovy
  platforms/jvm/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginMultiProjectTest.groovy
  platforms/jvm/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginToolchainsIntegrationTest.groovy
  platforms/jvm/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle/CheckstylePluginVersionIntegrationTest.groovy
  platforms/jvm/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/CheckstyleInvoker.groovy
  platforms/jvm/code-quality/src/main/resources/checkstyle-noframes-sorted.xsl
  platforms/jvm/code-quality/src/testFixtures/groovy/org/gradle/quality/integtest/fixtures/CheckstyleCoverage.groovy
Labels: 20 min review, platform:jvm, build-script-change

#26137 Only emit planned transform operation in project context
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformBuildOperationIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformStepNode.java
  subprojects/dependency-management/src/testFixtures/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformTestFixture.groovy
  subprojects/logging/src/integTest/groovy/org/gradle/internal/logging/console/AbstractConsoleBuildPhaseFunctionalTest.groovy
Labels: 20 min review, platform:software

#26151 Correct comments in unix start script template
  subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
Labels: in:wrapper, in:java-plugins, a:documentation, 1 min review

#26120 Cleanup Overview and Running Gradle section based on Github issues
  subprojects/distributions-integ-tests/src/integTest/groovy/org/gradle/AllDistributionIntegrationSpec.groovy
  subprojects/docs/src/docs/css/javadoc.css
  subprojects/docs/src/docs/css/manual.css
  subprojects/docs/src/docs/userguide/authoring-builds/software-product/composite_builds.adoc
  subprojects/docs/src/docs/userguide/authoring-builds/tutorial_using_tasks.adoc
  subprojects/docs/src/docs/userguide/getting-started/installation.adoc
  subprojects/docs/src/docs/userguide/getting-started/tutorial/part3_gradle_dep_man.adoc
  subprojects/docs/src/docs/userguide/img/octicons-16.svg
  subprojects/docs/src/docs/userguide/optimizing-performance/gradle_daemon.adoc
  subprojects/docs/src/docs/userguide/releases/migrating/migrating_from_groovy_to_kotlin_dsl.adoc
  subprojects/docs/src/docs/userguide/running-builds/build_environment.adoc
  subprojects/docs/src/docs/userguide/running-builds/gradle_wrapper.adoc
Labels: a:documentation

#25770 Fix Groovy lazy property assignment for NamedDomainObjectContainer
  subprojects/model-core/src/integTest/groovy/org/gradle/api/provider/PropertyAssignmentIntegrationTest.groovy
  subprojects/model-core/src/main/java/org/gradle/internal/metaobject/AbstractDynamicObject.java
  subprojects/model-core/src/main/java/org/gradle/internal/metaobject/BeanDynamicObject.java
  subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/plugins/JavaGradlePluginPluginIntegrationTest.groovy
Labels: @execution, p:lazy-migration

#26156 docs: Fix Deprecated keyword in getting started
  subprojects/docs/src/docs/userguide/getting-started/tutorial/part4_gradle_plugins.adoc
Labels: a:documentation, from:contributor

#26158 Update wrapper to 8.4-20230821223421+0000
  gradle/wrapper/gradle-wrapper.properties
Labels: a:chore, @execution

#26138 Add integration testing coverage for Problems API
  .teamcity/subprojects.json
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AbstractIntegrationSpec.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/BuildOperationTreeQueries.groovy
  subprojects/problems/build.gradle.kts
  subprojects/problems/src/integTest/groovy/org/gradle/api/problems/ProblemsServiceIntegrationTest.groovy
  subprojects/problems/src/main/java/org/gradle/api/problems/internal/DefaultProblems.java
Labels: 30 min review, platform:build_infrastructure, build-script-change

#26153 Polish Javadoc and API surface
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/validation/DefaultPluginId.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/validation/DelegatingProblemBuilder.java
  subprojects/model-core/src/main/java/org/gradle/internal/reflect/validation/TypeValidationProblemRenderer.java
  subprojects/problems/src/main/java/org/gradle/api/problems/Problem.java
  subprojects/problems/src/main/java/org/gradle/api/problems/ProblemBuilder.java
  subprojects/problems/src/main/java/org/gradle/api/problems/ProblemBuilderDefiningDocumentation.java
  subprojects/problems/src/main/java/org/gradle/api/problems/ProblemBuilderDefiningGroup.java
  subprojects/problems/src/main/java/org/gradle/api/problems/ProblemBuilderDefiningLabel.java
  subprojects/problems/src/main/java/org/gradle/api/problems/ProblemBuilderDefiningLocation.java
  subprojects/problems/src/main/java/org/gradle/api/problems/ProblemBuilderDefiningType.java
  subprojects/problems/src/main/java/org/gradle/api/problems/ProblemBuilderSpec.java
  subprojects/problems/src/main/java/org/gradle/api/problems/ProblemGroup.java
  subprojects/problems/src/main/java/org/gradle/api/problems/ProblemLocation.java
  subprojects/problems/src/main/java/org/gradle/api/problems/Problems.java
  subprojects/problems/src/main/java/org/gradle/api/problems/ProblemsPluginId.java
  subprojects/problems/src/main/java/org/gradle/api/problems/internal/DefaultProblemBuilder.java
  subprojects/problems/src/main/java/org/gradle/api/problems/internal/GradleExceptionWithProblem.java
Labels: 10 min review, platform:configuration_cache

#26164 Move test instrumentation interceptors to a separate SourceSet
  subprojects/core/build.gradle.kts
  subprojects/core/src/testInterceptors/java/org/gradle/internal/classpath/BasicCallInterceptionTestInterceptorsDeclaration.java
  subprojects/core/src/testInterceptors/java/org/gradle/internal/classpath/InheritedMethodTestReceiver.java
  subprojects/core/src/testInterceptors/java/org/gradle/internal/classpath/InheritedMethodsInterceptionTestInterceptorsDeclaration.java
  subprojects/core/src/testInterceptors/java/org/gradle/internal/classpath/InterceptorTestReceiver.java
Labels: @execution, p:lazy-migration

#26182 Clean up performance build directory on Windows
  .teamcity/src/main/kotlin/common/performance-test-extensions.kt
  .teamcity/src/main/kotlin/configurations/PerformanceTest.kt
Labels: 1 min review, platform:build_infrastructure

#26180 Quarantine flaky NextGenBuildCache tests
  subprojects/build-cache-http/src/integTest/groovy/org/gradle/caching/NextGenBuildCacheHttpIntegrationTest.groovy
  subprojects/build-cache/src/integTest/groovy/org/gradle/caching/NextGenBuildCacheIntegrationTest.groovy
  subprojects/build-cache/src/integTest/groovy/org/gradle/caching/internal/NextGenBuildCacheBuildOperationsIntegrationTest.groovy
  subprojects/build-cache/src/test/groovy/org/gradle/caching/internal/controller/NextGenBuildCacheControllerTest.groovy
Labels: 1 min review, platform:bt_ge_build_cache, platform:core_execution

#26175 Mention Tooling API compatibility in TestKit documentation
  subprojects/docs/src/docs/userguide/authoring-builds/test_kit.adoc
Labels: a:documentation, 1 min review, platform:documentation

#26170 Unify all "configuration-cache.inputs.unsafe.ignore*" property names
  subprojects/core/src/main/java/org/gradle/initialization/StartParameterBuildOptions.java
  subprojects/docs/src/docs/userguide/optimizing-performance/configuration_cache.adoc
  subprojects/docs/src/docs/userguide/running-builds/build_environment.adoc
Labels: @configuration-cache

#25826 Fix using modifiers with version catalogs
  subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/DependencyModifier.java
  subprojects/core-api/src/main/java/org/gradle/api/plugins/jvm/PlatformDependencyModifiers.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/plugins/jvm/internal/PlatformDependencyModifiersTest.groovy
  subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/TestFixturesDependencyModifiers.java
  subprojects/plugins/src/test/groovy/org/gradle/api/plugins/jvm/internal/TestFixturesDependencyModifiersTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testsuites/dependencies/TestSuitesGroovyDSLDependenciesIntegrationTest.groovy
  subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testsuites/dependencies/TestSuitesKotlinDSLDependenciesIntegrationTest.groovy
Labels: a:bug, in:dependency-version-catalog, in:test-suites, 20 min review, platform:jvm, platform:software

#26176 Add testcases for `ValidationProblemSerialization`
  subprojects/logging/src/main/java/org/gradle/internal/deprecation/Documentation.java
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/internal/ValidationProblemSerialization.java
  subprojects/plugin-development/src/test/groovy/org/gradle/plugin/devel/tasks/internal/ValidationProblemSerializationTest.groovy
  subprojects/problems/src/main/java/org/gradle/api/problems/internal/DefaultProblemLocation.java
  subprojects/problems/src/main/java/org/gradle/api/problems/internal/DefaultReportableProblem.java
Labels: 20 min review, platform:extensibility

#26166 docs: Update documentation to reflect actual plugin behavior
  subprojects/docs/src/docs/userguide/core-plugins/pmd_plugin.adoc
Labels: a:documentation, from:contributor

#26172 Fix scheduling of finalizers after last finalized task
  subprojects/core/src/integTest/groovy/org/gradle/api/FinalizerTaskIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/execution/plan/Node.java
Labels: @execution, in:scheduler

#26080 Fix always ignored tests
  subprojects/core/src/integTest/groovy/org/gradle/api/tasks/JavaExecJavaVersionIntegrationSpec.groovy
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AvailableJavaHomes.java
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/preconditions/IntegTestPreconditions.groovy
  subprojects/internal-testing/src/main/resources/valid-precondition-combinations.csv
  subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileJavaVersionIntegrationTest.groovy
Labels: 1 min review, platform:jvm, platform:build_infrastructure

#26171 Disable another shellcheck related to `ulimit` command
  subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
Labels: in:wrapper

#26186 Moves test for the groovy compiler toolchains into the language-groovy project
  .teamcity/subprojects.json
  platforms/jvm/language-groovy/build.gradle.kts
  platforms/jvm/toolchains-jvm/build.gradle.kts
  subprojects/language-groovy/src/integTest/groovy/org/gradle/groovy/compile/AbstractToolchainGroovyCompileIntegrationTest.groovy
  subprojects/language-groovy/src/integTest/groovy/org/gradle/groovy/compile/GroovyCompileToolchainIntegrationTest.groovy
  subprojects/language-groovy/src/integTest/groovy/org/gradle/groovy/compile/HigherToolchainGroovyCompileIntegrationTest.groovy
  subprojects/language-groovy/src/integTest/groovy/org/gradle/groovy/compile/LowerToolchainGroovyCompileIntegrationTest.groovy
  subprojects/language-groovy/src/integTest/groovy/org/gradle/groovy/compile/SameToolchainGroovyCompileIntegrationTest.groovy
  subprojects/language-groovy/src/integTest/groovy/org/gradle/jvm/toolchain/AbstractJavaToolchainDownloadSpiIntegrationTest.groovy
  subprojects/language-groovy/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainDownloadIntegrationTest.groovy
  subprojects/language-groovy/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainDownloadSpiAuthenticationIntegrationTest.groovy
  subprojects/language-groovy/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainDownloadSpiIntegrationTest.groovy
  subprojects/language-groovy/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainDownloadSpiKotlinIntegrationTest.groovy
  subprojects/language-groovy/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainIntegrationTest.groovy
  subprojects/language-groovy/src/integTest/groovy/org/gradle/jvm/toolchain/ShowToolchainsIntegrationTest.groovy
Labels: platform:jvm, 5 min review, a:platformization, platform:build_infrastructure, build-script-change

#26003 Add tests to verify existing root component behavior
  platforms/core-configuration/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/delegates/ScriptHandlerDelegate.kt
  subprojects/architecture-test/src/changes/accepted-public-api-changes.json
  subprojects/core-api/src/main/java/org/gradle/api/initialization/dsl/ScriptHandler.java
  subprojects/core-api/src/main/java/org/gradle/internal/deprecation/DeprecatableConfiguration.java
  subprojects/core/src/main/java/org/gradle/api/internal/initialization/DefaultScriptHandler.java
  subprojects/core/src/main/java/org/gradle/api/internal/initialization/DefaultScriptHandlerFactory.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/DetachedConfigurationsIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/RootComponentResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ScriptDependencyResolveIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/ConfigurationRolesIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/AttributeMatchingConfigurationSelector.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/LocalComponentDependencyMetadata.java
  subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/PalantirConsistentVersionsPluginSmokeTest.groovy
Labels: 30 min review, platform:software, platform:release_coordination, platform:kotlin_dsl

#25515 Allow variant reselection to reselect variants referenced by dependencies with artifacts
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/LocalFileDependencyBackedArtifactSetCodec.kt
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/ResolutionResultApiIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/attributes/ProjectVariantResolutionIntegrationTest.groovy
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/derived/JvmDerivedVariantsIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/DefaultConfigurationResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/DefaultLenientConfiguration.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/ComponentResolversChain.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/DefaultArtifactDependencyResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/ArtifactSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/BuildDependenciesOnlyVisitedArtifactSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/DefaultArtifactSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/DefaultResolvedVariantSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/DefaultVisitedArtifactResults.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/FileDependencyArtifactSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/LocalFileDependencyBackedArtifactSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/NoBuildDependenciesArtifactSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/ResolvedArtifactsGraphVisitor.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/ResolvedVariantSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/VariantResolvingArtifactSet.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/VisitedArtifactsResults.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/AttributeMatchingVariantSelector.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultVariantSelectorFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/VariantSelectorFactory.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/local/model/DefaultLocalComponentGraphResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/ComponentArtifactResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/ComponentArtifactResolveVariantState.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/DefaultComponentGraphResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/VariantArtifactResolveState.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/VariantResolveMetadata.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/VariantWithOverloadAttributes.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/resolver/DefaultVariantArtifactResolver.java
  subprojects/dependency-management/src/main/java/org/gradle/internal/resolve/resolver/VariantArtifactResolver.java
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/DefaultLenientConfigurationTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/DefaultArtifactSetTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/DefaultVisitedArtifactResultsTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/NoBuildDependenciesArtifactSetTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/resolveengine/artifact/VariantResolvingArtifactSetTest.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/AttributeMatchingVariantSelectorSpec.groovy
  subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/transform/DefaultVariantSelectorFactoryTest.groovy
Labels: 30 min review, platform:software, platform:configuration_cache

#26193 Fix failing kotlin-dsl-tooling-builder
  platforms/core-configuration/kotlin-dsl-tooling-builders/src/crossVersionTest/groovy/org/gradle/kotlin/dsl/tooling/builders/r54/KotlinBuildScriptModelCrossVersionSpec.groovy
Labels: 1 min review, platform:kotlin_dsl

#26117 Fix file content reading within zip archive
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredBuildInputsIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/internal/classpath/Instrumented.java
Labels: @configuration-cache, from:contributor

#26101 Format deprecation entries in build operation trace
  subprojects/base-services/src/main/java/org/gradle/internal/operations/trace/CustomOperationTraceSerialization.java
  subprojects/logging/src/integTest/groovy/org/gradle/DeprecatedUsageBuildOperationProgressIntegrationTest.groovy
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/DefaultDeprecatedUsageProgressDetails.java
  subprojects/plugin-development/build.gradle.kts
Labels: 10 min review, platform:extensibility, build-script-change

#26194 Bump Configuration Cache report to 1.3
  build-logic/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
Labels: @configuration-cache, 1 min review

#26205 Migrate integration tests for language-groovy to new home in platforms
  platforms/jvm/language-groovy/src/integTest/groovy/org/gradle/groovy/compile/AbstractToolchainGroovyCompileIntegrationTest.groovy
  platforms/jvm/language-groovy/src/integTest/groovy/org/gradle/groovy/compile/GroovyCompileToolchainIntegrationTest.groovy
  platforms/jvm/language-groovy/src/integTest/groovy/org/gradle/groovy/compile/HigherToolchainGroovyCompileIntegrationTest.groovy
  platforms/jvm/language-groovy/src/integTest/groovy/org/gradle/groovy/compile/LowerToolchainGroovyCompileIntegrationTest.groovy
  platforms/jvm/language-groovy/src/integTest/groovy/org/gradle/groovy/compile/SameToolchainGroovyCompileIntegrationTest.groovy
  platforms/jvm/language-groovy/src/integTest/groovy/org/gradle/jvm/toolchain/AbstractJavaToolchainDownloadSpiIntegrationTest.groovy
  platforms/jvm/language-groovy/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainDownloadIntegrationTest.groovy
  platforms/jvm/language-groovy/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainDownloadSpiAuthenticationIntegrationTest.groovy
  platforms/jvm/language-groovy/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainDownloadSpiIntegrationTest.groovy
  platforms/jvm/language-groovy/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainDownloadSpiKotlinIntegrationTest.groovy
  platforms/jvm/language-groovy/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainIntegrationTest.groovy
  platforms/jvm/language-groovy/src/integTest/groovy/org/gradle/jvm/toolchain/ShowToolchainsIntegrationTest.groovy
Labels: a:chore, 1 min review, platform:jvm

#24592 Make scheduled executor service tasks robust against exceptions (#24575)
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/Daemon.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/health/gc/GarbageCollectionCheck.java
  subprojects/launcher/src/test/groovy/org/gradle/launcher/daemon/server/DaemonTest.groovy
  subprojects/launcher/src/test/groovy/org/gradle/launcher/daemon/server/health/gc/GarbageCollectionCheckTest.groovy
  subprojects/logging/src/main/java/org/gradle/internal/logging/console/ThrottlingOutputEventListener.java
  subprojects/logging/src/test/groovy/org/gradle/internal/logging/console/ThrottlingOutputEventListenerTest.groovy
  subprojects/process-services/src/main/java/org/gradle/process/internal/health/memory/DefaultMemoryManager.java
  subprojects/process-services/src/test/groovy/org/gradle/process/internal/health/memory/DefaultMemoryManagerTest.groovy
Labels: a:feature, in:execution-engine, from:contributor

#26213 Clean up performance build directory at the beginning
  .teamcity/src/main/kotlin/common/performance-test-extensions.kt
  .teamcity/src/main/kotlin/configurations/GradleBuildConfigurationDefaults.kt
  .teamcity/src/main/kotlin/configurations/PerformanceTest.kt
  .teamcity/src/main/kotlin/util/RerunFlakyTest.kt
  .teamcity/src/test/kotlin/ApplyDefaultConfigurationTest.kt
Labels: 1 min review, platform:build_infrastructure

#25644 Fix NPE in incremental compilation of projects with '*' annotation processor and 'module-info.java'
  platforms/jvm/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/AbstractIncrementalAnnotationProcessingIntegrationTest.groovy
  platforms/jvm/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/AggregatingIncrementalAnnotationProcessingIntegrationTest.groovy
  platforms/jvm/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/AggregatingProcessingStrategy.java
  platforms/jvm/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/ElementUtils.java
  platforms/jvm/language-java/src/testFixtures/groovy/org/gradle/language/fixtures/AnnotationProcessorFixture.groovy
Labels: from:contributor

#26184 Update foojay plugin version to 0.7.0
  build-logic-commons/settings.gradle.kts
  build-logic/settings.gradle.kts
  platforms/jvm/language-groovy/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainDownloadIntegrationTest.groovy
  settings.gradle.kts
  subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/SimpleGlobalFilesBuildSettingsDescriptor.java
  subprojects/docs/src/docs/userguide/getting-started/tutorial/part1_gradle_init.adoc
  subprojects/docs/src/snippets/java/toolchain-foojay/groovy/settings.gradle
  subprojects/docs/src/snippets/java/toolchain-foojay/kotlin/settings.gradle.kts
  subprojects/soak/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainDownloadSoakTest.groovy
Labels: 1 min review, platform:jvm, platform:software, platform:documentation, platform:release_coordination, build-script-change

#26216 Remove AGP 8.2.0-dev from test versions
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/versions/AndroidGradlePluginVersions.groovy
Labels: 1 min review, platform:build_infrastructure

#26215 Beanify `DocLink`, so Kotlin/Groovy would use property accessors
  platforms/core-configuration/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/DefaultPrecompiledScriptPluginsSupport.kt
  platforms/jvm/toolchains-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainQueryService.java
  platforms/jvm/toolchains-jvm/src/main/java/org/gradle/jvm/toolchain/internal/install/DefaultJavaToolchainProvisioningService.java
  subprojects/build-cache-http/src/integTest/groovy/org/gradle/caching/http/internal/HttpBuildCacheServiceIntegrationTest.groovy
  subprojects/build-cache-http/src/main/java/org/gradle/caching/http/internal/DefaultHttpBuildCacheServiceFactory.java
  subprojects/core/src/integTest/groovy/org/gradle/api/HttpScriptPluginIntegrationSpec.groovy
  subprojects/core/src/integTest/groovy/org/gradle/api/resource/TextResourceIntegrationTest.groovy
  subprojects/core/src/main/java/org/gradle/api/internal/plugins/DefaultObjectConfigurationAction.java
  subprojects/core/src/main/java/org/gradle/api/internal/resources/DefaultTextResourceFactory.java
  subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/http/HttpsToHttpRedirectResolveIntegrationTest.groovy
  subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultUrlArtifactRepository.java
  subprojects/launcher/src/main/java/org/gradle/launcher/daemon/client/NoUsableDaemonFoundException.java
  subprojects/logging/src/main/java/org/gradle/api/internal/DocumentationRegistry.java
  subprojects/logging/src/main/java/org/gradle/internal/deprecation/DeprecatedFeatureUsage.java
  subprojects/logging/src/main/java/org/gradle/internal/deprecation/Documentation.java
  subprojects/logging/src/main/java/org/gradle/internal/deprecation/DocumentedFailure.java
  subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/DefaultDeprecatedUsageProgressDetails.java
  subprojects/logging/src/test/groovy/org/gradle/internal/deprecation/DeprecatedFeatureUsageTest.groovy
  subprojects/logging/src/test/groovy/org/gradle/internal/deprecation/DocumentationTest.groovy
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/internal/precompiled/PrecompiledGroovyPluginsPlugin.java
  subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/internal/ValidationProblemSerialization.java
  subprojects/plugin-development/src/test/groovy/org/gradle/plugin/devel/tasks/internal/ValidationProblemSerializationTest.groovy
  subprojects/problems/src/integTest/groovy/org/gradle/api/problems/ProblemsServiceIntegrationTest.groovy
  subprojects/problems/src/main/java/org/gradle/api/problems/DocLink.java
Labels: platform:jvm, 5 min review, platform:software, platform:extensibility, platform:bt_ge_build_cache, platform:kotlin_dsl, platform:core_execution

#26204 Make Isolated Projects setting part of the Configuration Cache key
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheKeyIntegrationTest.groovy
  subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/isolated/IsolatedProjectsFixture.groovy
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheKey.kt
  subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/ConfigurationCacheStartParameter.kt
  subprojects/configuration-cache/src/test/kotlin/org/gradle/configurationcache/ConfigurationCacheKeyTest.kt
  subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/GradleContextualExecuter.java
Labels: in:project-isolation, 10 min review, platform:build_infrastructure, platform:configuration_cache

#24520 Don't fail TestLauncher execution when only tasks are configured
  subprojects/tooling-api-builders/src/main/java/org/gradle/tooling/internal/provider/runner/TestExecutionResultEvaluator.java
  subprojects/tooling-api-builders/src/test/groovy/org/gradle/tooling/internal/provider/runner/TestExecutionResultEvaluatorTest.groovy
  subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r82/TestLauncherTaskExecutionCrossVersionSpec.groovy
Labels: 5 min review, platform:ide
